### ISSUE TITLE
"Unexpected token :" for JSON-LD (ld+json). SublimeLinter getting scope wrong? 

### ISSUE THREAD

**Issue by jaepage** [SublimeLinter/SublimeLinter#1000]
If I place a JSON-LD script element in an HTML file, ESLint throws an error of "Unexpected token :". 

Google doc: https://developers.google.com/search/docs/guides/intro-structured-data

Google example snippet: 

        <script type="application/ld+json">
            {
                "@context": "http://schema.org",
                "@type": "Organization",
                "url": "http://www.example.com",
                "name": "Unlimited Ball Bearings Corp.",
                "contactPoint": {
                    "@type": "ContactPoint",
                    "telephone": "+1-401-555-1212",
                    "contactType": "Customer service"
                }
            }
        </script>

Disabling ESLint in Sublime Text menubar's "Toggle" command removes the error. 

Adding `/* eslint-disable unexpected-token */` doesn't remove the error. 

Does SublimeLinter think this script element is JavaScript, despite the type specification of JSON-LD? 

Can this be prevented, please? 

- ESLint 4.17.0
- SublimeLinter 3.10.10
- Sublime Text 3.0
- macOS 10.13.3 High Sierra

**Comment by kaste** [comment]
Do not double post, okay?

**Comment by jaepage** [comment]
I apologize. It's not clear to me whether this is an issue with ESLint, SublimeLinter-ESLint, or SublimeLinter. How am I to know which, please? Thank you.
