### ISSUE TITLE
Improve "linter's executable not found" types of error messages

### ISSUE THREAD

**Issue by mandx** [SublimeLinter/SublimeLinter#1003]
In a project which I know I don't have ESLint configured, STLinter attempted to lint a file I temporarily opened and this showed up:
```
WARNING: eslint cannot locate 'eslint'
```
Now, I know why the message comes up, the issue here is about the wording itself, it could be improved I guess, for example:
```
WARNING: eslint linter cannot locate the 'eslint' executable
```

**Comment by kaste** [comment]
I think we would be very happy of any PR's in this area. ❤️

**Comment by kaste** [comment]
We probably can do something here based on more user feedback and commitment. Closing for now.
