### ISSUE TITLE
Make Linter.lint and Linter.process_match return namedtuples instead of dicts

### ISSUE THREAD

**Issue by FichteFoll** [SublimeLinter/SublimeLinter#1012]
Currently they return a (list of) static dict(s) with 7 fixed elements.

https://github.com/SublimeLinter/SublimeLinter/blob/9ace287896ce56b2f2e8b5ae88bd32f5f0cf565e/lint/linter.py#L916-L924

Similar to #711 (af5527935df20303ae4afbdf8476aafb33cde0ac).

**Comment by kaste** [comment]
#711 was a mistake. A namedtuple is not really better than a tuple when almost all keys are optional. It should be a dict, ideally we would just use match.groupdict(). But that ship has sailed.

Here, the type on an error is not static as well. What we return here is the starting point for our data transformations in the views (and the small one in the backend).

**Comment by FichteFoll** [comment]
I prefer passing around self-referencing data structures rather than dictionaries with static keys, but you do you.
