### ISSUE TITLE
syncing cursor position to the panel is buggy

### ISSUE THREAD

**Issue by braver** [SublimeLinter/SublimeLinter#1014]
https://github.com/SublimeLinter/SublimeLinter/pull/1010#issuecomment-368131162

**Comment by kaste** [comment]
A good test is something like this

![image](https://user-images.githubusercontent.com/8558/36630512-9621ef7a-1967-11e8-8ba3-b9ef00698207.png)

If you have multiple errors per line, you cannot jump to them. You immediately jump to the next *line* not the next *error*.

**Comment by braver** [comment]
@kaste I don't know what you mean here. `next_result` also jumps between errors on the same line. Scrolling of the panel view works correctly also in this case after #1015.

For me, as far as I can tell with a test like that, it behaves correctly after #1015. What else do you want to change?

**Comment by kaste** [comment]
It jumps from 'matched' to 'break' when I hit F4:

![lz9x0i055w](https://user-images.githubusercontent.com/8558/36634046-f6bed0f0-199e-11e8-90a7-1514887586a1.gif)

**Comment by braver** [comment]
What does the panel show for you here?

**Comment by kaste** [comment]
The panel is correct. I mean it doesn't show that much bc it is without #1010, so I have no line marker. Sorting (mostly) affects files with multiple linters, I have only flake8 here.

**Comment by kaste** [comment]
Please take a closer look where my cursor is before the jump 

```
 matched
^
```
