### ISSUE TITLE
Using 'next_result' is broken

### ISSUE THREAD

**Issue by kaste** [SublimeLinter/SublimeLinter#1018]
We use 'next_result' as a recommendation to go to the next result (essentially F4 on Windows). As soon as you open a Find all which opens the 'Find results' view, this command will not work anymore. Instead it will correctly iterate the search results. But our panel never gains focus again. You can close the 'Find results' view, and still not iterate through the lint errors. You can `ctrl-k a` to open the errors panel, and still are not able to iterate through the lint errors. You have to literally click (activate) the panel, so Sublime will reactivate the shortcut/command 'next_result' for it. 

- Either don't use 'next_result' (this would help #1010 as well) at all, and instead recommend the Goto command. (We could implement going to the next file for that command as well.)
- Actually focus the panel on 'ctrl-k a'

**Comment by FichteFoll** [comment]
I'm not sure if you *can* focus an output panel. It seems like they get focused when they are created or something, but not when you re-show them? Not at a computer right now.

**Comment by braver** [comment]
We should advertise the Goto commands. I’m also totally ok with removing the position-synchronization with the panel and thereby closing #1010. It was a good experiment, just doesn’t work reliably enough.

**Comment by kaste** [comment]
The position sync works 100%. I just used the go-to commands so I never noticed that next_result is actually broken. If we drop next_result #1010 looks and works fine.

**Comment by kaste** [comment]
However, if we focus the panel, we might want two way sync between panel and views. T.i. a user should be able to navigate the panel via keyboard.

**Comment by braver** [comment]
> next_result is actually broken

`next_result` is just a ST feature we get for free and it works like that for every panel. As such, we can't fix it and shouldn't try to change its behaviour. Even our position sync is questionable (if cool and useful).

> If we drop next_result

It is not something we *can* drop, it is not ours.

Really, we shouldn't try to make next_result work better, it is what it is. We should just leave it and not advertise it, instead we should point to our own commands.

> However, if we focus the panel, we might want two way sync between panel and views. T.i. a user should be able to navigate the panel via keyboard.

Let's not go there.

**Comment by FichteFoll** [comment]
>You can ctrl-k a to open the errors panel, and still are not able to iterate through the lint errors. You have to literally click (activate) the panel, so Sublime will reactivate the shortcut/command 'next_result' for it.

I would actually think of this as a ST bug. Alas, I'm with @braver and would declare "no action to take".

**Comment by braver** [comment]
Yes, alas is the word to use here. I think I'll just remove mention of next/prev_result from the readme etc. and call it a day.

**Comment by FichteFoll** [comment]
Hm, imo it's still worth mentioning that it is supported, albeit it can bug out in some situations as outlined in OP, which I think of as ST bugs. It could, however, occur that indicating support for them would cause people to blame SL for `next_result` problems when it's in fact just re-using ST behavior.

**Comment by braver** [comment]
It's just a built-in feature. Although I don't think many people will know about, I don't really feel like telling people about it and then having to discuss its shortcomings. If people do know about it and find out it works here too, they can consider it some little extra nugget of functionality they got for free. It's not like ST documents what "next_result" means in any way.
