### ISSUE TITLE
'SublimeLinter' doens't appear in package control

### ISSUE THREAD

**Issue by estevao** [SublimeLinter/SublimeLinter#1019]
I'm using SublimeText3 Build3143 on macOS Sierra and there's no 'SublimeLinter' option to select, only SublimeLinter-annotations, bandit, etc.

PS. This happens even if adding the repo manually.

Any ideas? Thanks.

**Comment by JavadSM** [comment]
Same here

**Comment by brksm** [comment]
Same here

Package seems to be "missing" here https://packagecontrol.io/packages/SublimeLinter

**Comment by kaste** [comment]
Package control is down.

**Comment by grenudi** [comment]
@kaste, Why? For how long? And where is some kind of official announcement?

**Comment by kaste** [comment]
It's just down. 😄

**Comment by FichteFoll** [comment]
wbond/package_control#1334

**Comment by grenudi** [comment]
That is not really looks like it is just down
