### ISSUE TITLE
Sublime Linter appears twice in Preferences

### ISSUE THREAD

**Issue by Saevon** [SublimeLinter/SublimeLinter#1033]
You can see below that the menu option is there twice.
<img width="828" alt="screen shot 2018-02-28 at 7 15 17 pm" src="https://user-images.githubusercontent.com/570036/36825384-eb82a73c-1cbb-11e8-9778-48f5ebf397ef.png">

Clicking the first option (When you don't Have a `User Preferences` file for SublimeLinter) auto-fills the following, instead of creating an empty JSON file. (See the first picture on the right side to see what the auto-generated file *should* look like)
<img width="368" alt="screen shot 2018-02-28 at 7 16 22 pm" src="https://user-images.githubusercontent.com/570036/36825388-edb2feda-1cbb-11e8-9152-e9500293a349.png">

**Comment by braver** [comment]
I cannot reproduce this. Please check your packages folder and caches to see if you have some old stuff still hanging around.

**Comment by braver** [comment]
Does this still happen after the 4.0 upgrade?

**Comment by Saevon** [comment]
(Will check when I get home tonight, I think the cache is most likely)

**Comment by kaste** [comment]
This is unlikely to get a fixable issue bc the menus are set declarative.

**Comment by FichteFoll** [comment]
I suspect that you have an unextracted version of sublimelinter in your normal Packages folder (not "Installed Packages"). Remove it if that is the case.

**Comment by Saevon** [comment]
Just checked, it was indeed a cached copy. Thanks!
