### ISSUE TITLE
error panel shows for "settings file not found" after upgrade

### ISSUE THREAD

**Issue by braver** [SublimeLinter/SublimeLinter#1039]
After the old settings are backed up, I got a "Settings file not found" error. Which is kinda odd... It's also just for that one moment. 🤷‍♂️

**Comment by freder** [comment]
same

![screen shot 2018-03-02 at 17 40 58](https://user-images.githubusercontent.com/724844/36910414-f70e1a42-1e40-11e8-92b7-2fc53e65771d.png)

**Comment by kaste** [comment]
Great, thats a 🐛 in Sublime, haha

**Comment by kaste** [comment]
Should we fix this?

**Comment by braver** [comment]
Not sure we can efficiently. In a few days everyone should be upgraded and the problem will go away. 🤷🏼‍♂️

**Comment by kaste** [comment]
The fix would be in #1060. I don't think we need to throw here, you wrote that.

**Comment by sebastienbarre** [comment]
So uh... I start my Sublime Editor today, and suddenly my Sublime Linter settings are renamed to "SublimeLinter (old).sublime-settings", and zero of them are ported to the new user settings, so nothing lints. Is there some documented upgrade path? Or a way to force install 3.0? Thanks

**Comment by kaste** [comment]
So far, we have only some problems with our default coloring that affects unregistered/free users of Sublime. Otherwise, you copy the relevant parts from your old config into the new one. 

syntax_map is probably important if that is vastly different from the default.
