### ISSUE TITLE
[Version 4] Old documentation

### ISSUE THREAD

**Issue by prog1dev** [SublimeLinter/SublimeLinter#1044]
On http://www.sublimelinter.com/en/latest/ there is no info about version 4

**Comment by braver** [comment]
I kinda hoped that would auto-update right about now. Am looking into it. For now, the current versions of the docs are pretty easy to browse here: https://github.com/SublimeLinter/SublimeLinter/tree/master/docs

**Comment by braver** [comment]
docs are updated now!

**Comment by prog1dev** [comment]
@braver looks like I dont have permission 😄 
[screenshot](https://imgur.com/a/OVvvz)

**Comment by braver** [comment]
Try it without the /latest? Or does it always redirect to that.

**Comment by prog1dev** [comment]
now it works
thanks
