### ISSUE TITLE
@ file name substitution symlink

### ISSUE THREAD

**Issue by slifin** [SublimeLinter/SublimeLinter#1047]
I'm running a command similar to:

```phan -k /Users/username_here/.phan/config.php --include-analysis-file-list @ -i -q -m checkstyle```

In a custom plugin I made, this worked okay in sublime linter 3 but now it's broken in sublime linter 4

Now I believe the complication is that the file I'm linting on is within a folder inside /private/var/www/my-folder which has a symlink from /var/www/my-folder I suspect between versions of sublime linter the @ subsitution for the file name has stopped using the full /private/var/www/my-folder version in favour of /var/www/my-folder

on the terminal if I run 

```phan -k /Users/username_here/.phan/config.php --include-analysis-file-list /private/var/www/my-folder/my-file.php -i -q -m checkstyle```
it works but this does not work:
```phan -k /Users/username_here/.phan/config.php --include-analysis-file-list /var/www/my-folder/my-file.php -i -q -m checkstyle```

Is there anyway I can debug what sublimelinter is substituting with, and is there a way I can modify behaviour here to give a full path?

Within sublime's project file I have ```/private/var/www/my-folder``` as the path

**Comment by slifin** [comment]
Seems like it's not the file name resolving, I've tried putting the true path in hard coded and I still don't get lint errors :\

**Comment by slifin** [comment]
<img width="995" alt="screen shot 2018-03-02 at 12 52 15" src="https://user-images.githubusercontent.com/198857/36899797-8ffcddde-1e18-11e8-8df3-80d7eb3bd960.png">
Did anything change between 3 and 4 which could have broken a plugin like above?

**Comment by slifin** [comment]
Ah it's the linter that is the problem

**Comment by kaste** [comment]
Hi :wave:. Enable debug in the SublimeLinter settings and look or post the log.

**Comment by slifin** [comment]
Sorry I turned this issue into a bit of a pinball ticket but if by some weird fluke you (as the reader) also made their own phan plugin and use phan and use this plugin: https://github.com/mattriverm/PhanUnusedVariable

I think this is why: https://github.com/mattriverm/PhanUnusedVariable/issues/32 you might not be seeing linting errors of unused variables
