### ISSUE TITLE
[Version 4] SublimeLinter.sublime-settings is NOT generated/created after upgrading or even clean installing SL4 

### ISSUE THREAD

**Issue by darkred** [SublimeLinter/SublimeLinter#1049]
Using ST 3 dev build 3157, SublimeLinter 4, SublimeLinter-eslint 4.0, ESlint 4.18.1 in win10x64

I had SL 3.10.10.
The settings I had were the following [SublimeLinter (old).sublime-settings](https://gist.github.com/darkred/d4bf32f83bf1eee93fbfceea7173893d).

After upgrading to SL 4.0 no `SublimeLinter.sublime-settings` file is generated:
![2018-03-02_145100](https://user-images.githubusercontent.com/723651/36899746-2796e35a-1e29-11e8-8fdb-8183627a5993.jpg)
![2018-03-02_144919](https://user-images.githubusercontent.com/723651/36899722-0d65d892-1e29-11e8-941a-6c37225be44c.jpg)
Even if I remove SL and SL-eslint and re-install them, the file is not automatically generated. 

Shouldn't the settings (at least some of them) be migrated from the previous settings, on upgrade?
Or, after removing+reinstalling SL4, shouldn't a minimal  `SublimeLinter.sublime-settings` file be created?

Should I manually copy the settings from `SublimeLinter (old).sublime-settings` to a new `SublimeLinter.sublime-settings` file? (removing 'user' and un-indent one level)

**Comment by darkred** [comment]
For reference, the upgrade instructions:

  

>   How to upgrade
>   -------------------------------
>   
>   Your old settings will be backed up to SublimeLinter old.sublime-settings.
>   You may want to compare them to the new settings and check if you want to
>   migrate anything.
>   
>   To migrate your settings, first remove the "user" level and un-indent/flatten
>   everything a level. Check the default settings to remove settings that don't
>   exist anymore:
>   
>   - mark_style
>   - error_color
>   - gutter_theme_excludes
>   - passive_warnings
>   - show_errors_on_save
>   - tooltip_fontsize, tooltip_theme, tooltip_theme_excludes, tooltips
>   - warning_color
>   - wrap_find
>   - python_paths
>   
>   You can keep the "linters" settings block if it contains customizations that
>   you need. It's also safe to remove it otherwise.
>   
>   If you use the ${project} settings token you should change that to ${folder}.
>   
>   You can now change your color scheme to one without the (SL) suffix. After
>   doing so you can remove the Packages/User/SublimeLinter directory. It holds
>   augmented color schemes that are no longer needed.
>

**Comment by braver** [comment]
From the [upgrade info message](https://github.com/SublimeLinter/SublimeLinter/blob/master/messages/4.0.0-rc.1.txt):

> Default settings are no longer copied to the user settings.


> To migrate your settings, first remove the "user" level and un-indent/flatten
> everything a level. Check the default settings to remove settings that don't
> exist anymore:
> 
> - mark_style
> - error_color
> - gutter_theme_excludes
> - passive_warnings
> - show_errors_on_save
> - tooltip_fontsize, tooltip_theme, tooltip_theme_excludes, tooltips
> - warning_color
> - wrap_find
> - python_paths
> 
> You can keep the "linters" settings block if it contains customizations that
> you need. It's also safe to remove it otherwise.
> 
> If you use the ${project} settings token you should change that to ${folder}.

There is no need to populate your user settings with anything. Your old settings doesn't seem to contain any customisations, so you can probably keep it as is?

**Comment by MannyC** [comment]
> You can keep the "linters" settings block if it contains customizations that
you need. It's also safe to remove it otherwise.

Don't see it mentioned that the SL4 seems to be ignoring the `@disabled` property on the linters.  Removing the `@` worked.

**Comment by braver** [comment]
Good point, I'll update the docs.

**Comment by darkred** [comment]
I misunderstood in the following phrase the 'new settings' part 
as 'the migrated settings', instead of 'the new **default** settings':
> Your old settings will be backed up to SublimeLinter old.sublime-settings.
> You may want to compare them to the new settings and check if you want to migrate anything.

Keeping it as it is, works ok. Thanks for replying, @braver
