### ISSUE TITLE
Flake8 ignore rules stopped working on SublimeLinter 4

### ISSUE THREAD

**Issue by srus** [SublimeLinter/SublimeLinter#1050]
Hi, I got the update of SublimeLinter on ST3 today, restarted ST and then SublimeLinter stopped working properly. I have some ignore rules for Python Flake8, but it looks like SublimeLinter stopped using them. 

Then I found in the console the following error:

`Unable to open /home/xxxxxx/.config/sublime-text-3/Packages/SublimeLinter/SublimeLinter.sublime-settings`

The container folder doesn't exist, actually. I've tried manually creating that folder and the Default Settings file and it looks like I don't get the error anymore, but still, SublimeLinter is ignoring my settings for Flake8.

This is my User Settings file:

```
// SublimeLinter Settings - User
{
    "lint_mode": "load_save",
    "linters": {
        "flake8": {
            "ignore": "E501,E127,E128,W191",
        }
    }
}
```

System info:
Ubuntu 16.04
Sublime Text 3.0
SublimeLinter 4.0.1
SublimeLinter-flake8 4.0.1

**Comment by srus** [comment]
I've enabled the `debug` setting and this is what I get in the console:

```
SublimeLinter: #14 SublimeLinter.sublime-package:782: 'flake8' is linting 'xxxxxx.py'
SublimeLinter: #14 SublimeLinter.sublime-package:48: flake8: wanted python is 'None'
SublimeLinter: #14 SublimeLinter.sublime-package:99: flake8: trying to use globally installed flake8
SublimeLinter: #14 SublimeLinter.sublime-package:1178: flake8: xxxxxx.py ['/usr/local/bin/flake8', '--format', 'default', '-']
SublimeLinter: #14 SublimeLinter.sublime-package:1181: flake8: cwd: /home/xxxx/yyyyy/zzzz/
SublimeLinter: #14 SublimeLinter.sublime-package:809: flake8 output:
    stdin:160:79: E501 line too long (101 > 79 characters)
    stdin:63:79: E501 line too long (120 > 79 characters)
    stdin:65:79: E501 line too long (124 > 79 characters)
    stdin:127:79: E501 line too long (85 > 79 characters)
    stdin:157:79: E501 line too long (91 > 79 characters)
    stdin:29:79: E501 line too long (92 > 79 characters)
    stdin:28:79: E501 line too long (93 > 79 characters)
    stdin:109:79: E501 line too long (94 > 79 characters)
    stdin:71:79: E501 line too long (96 > 79 characters)
    stdin:128:79: E501 line too long (98 > 79 characters)
```

**Comment by kaste** [comment]
A couple of weeks ago, flake8 lost these settings. You should use the `args` setting.

**Comment by byaka** [comment]
lol thx, it helps for me^^
```json
// SublimeLinter Settings - User
{
    "lint_mode": "load_save",
    "linters": {
        "flake8": {
            "args": ["--ignore=E501,E127,E128,W191"],
        }
    }
}
```

**Comment by aphearin** [comment]
I had a very similar problem when migrating to v4. Thorough explanation here: https://github.com/SublimeLinter/SublimeLinter/issues/1070. Using the `args` syntax resolved the issue for me as well.

**Comment by sambarluc** [comment]
On Sublime Linter 4.6.3, I would say that this is still an issue, and the "args" sintax does not fix it. I had to manually create the missing `~/.config/sublime-text-3/Packages/SublimeLinter/SublimeLinter.sublime-settings`
