### ISSUE TITLE
no highlighting of errors and can't set gutter style

### ISSUE THREAD

**Issue by Shelagh-Lewins** [SublimeLinter/SublimeLinter#1051]
Eslint just auto-upgraded to version 4.0.1 and now I don't see any highlighting of where errors are in the line; previously they were clearly marked with a red outline. The icons in the gutter are white when they used to be red, yellow etc. The status bar text no longer tells me what my errors are.
I've looked at the upgrade notes and have tried to set gutter style but it didn't make any difference.
Can you give clear instructions on how to get back to a usable linting style after the upgrade?

**Comment by DevBrent** [comment]
Same problem here. This is a great upgrade. Even after the warnings and properly migrating some of my settings or using default settings, errors are not highlighted.

**Comment by DevBrent** [comment]
Update, even with both "styles" set to squiggly_underline, I'm getting outline styles on certain errors.

![image](https://user-images.githubusercontent.com/4075001/36908902-9f0b0160-1e0a-11e8-93db-f306ff9b9fcb.png)

![image](https://user-images.githubusercontent.com/4075001/36908919-ab917bda-1e0a-11e8-9902-379a91b5ef73.png)

**Comment by Shelagh-Lewins** [comment]
Does it matter whether gutter_theme is 'circle' or 'Circle'? The comments say` // Circle` but neither seems to do anything.

Did you find a way to change the error color?

I currently have` "mark_style": "fill" `which is at least visible.

**Comment by kaste** [comment]
@DevBrent Sublime cannot draw squiggles on whitespace, so we draw outlines for these.

@Shelagh-Lewins The colors are defined using the `scope` setting.

**Comment by Shelagh-Lewins** [comment]
@kaste thanks, but I don't understand from the comments how to use scope to set color? And is it possible to make the outline stronger like it was in version 3?

**Comment by Shelagh-Lewins** [comment]
@kaste thanks - the gutter icons, how can I get those to be different coloured dots like they were in version 3?

**Comment by DevBrent** [comment]
@Shelagh-Lewins It appears certain color-schemes give me all white circle icons..try changing color schemes.

**Comment by kaste** [comment]
Actually, why not start simple. Set theme to "none" and icon to 'dot'. Now they get colorized using the scope, e.g. the have the same color as the under or outlines

**Comment by DevBrent** [comment]
@kaste region.redish is black on some color schemes. this doesn't make sense.
![image](https://user-images.githubusercontent.com/4075001/36910261-376b3e18-1e0e-11e8-9a5f-271ef35c57d1.png)

**Comment by kaste** [comment]
Something like this

![image](https://user-images.githubusercontent.com/8558/36910252-79dc59a8-1e40-11e8-835b-58306f0c261a.png)

**Comment by DevBrent** [comment]
@kaste which color scheme are you using so I can get back to work today? I need a dark color scheme that works with SL4.

**Comment by kaste** [comment]
Yeah, but then it's just not defined, so it falls back to something (in that case) stupid. If I define

![image](https://user-images.githubusercontent.com/8558/36910427-03bfa4ae-1e41-11e8-9331-926dd5178ebe.png)

everything gets white.

**Comment by DevBrent** [comment]
Ahhhh.....
> region.<colorish> are automatically generated scopes in ST > 3148.

![image](https://user-images.githubusercontent.com/4075001/36910528-02eb44de-1e0f-11e8-823c-00be2bc431b2.png)

**Comment by kaste** [comment]
Every color scheme should have a decent `markup.deleted`, `markup.changed`, no?

**Comment by kaste** [comment]
Otherwise, just add it

```
		<dict>
			<key>name</key>
			<string>Deleted</string>
			<key>scope</key>
			<string>markup.deleted</string>
			<key>settings</key>
			<dict>
				<key>foreground</key>
				<string>#DF6A73</string>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>Changed</string>
			<key>scope</key>
			<string>markup.changed</string>
			<key>settings</key>
			<dict>
				<key>foreground</key>
				<string>#C679DD</string>
			</dict>
		</dict>

```

**Comment by Shelagh-Lewins** [comment]
@kaste, I have ST 3143, what's the impact of this? I don't understand what the scope colours are, are they somehow related to localisation? It seems very complicated...

And, with the default settings gutter 'none' and icon 'dot', the gutter icons are just white.

**Comment by kaste** [comment]
The scopes are how Sublime actually does all the colors. (Syntax highlighting, icon coloring in the gutter, underlines.) But as I said a Sublime theme/style should have these defined. I mean you have colored code, not just white on black. No?

**Comment by DevBrent** [comment]
Theme already has this.... Maybe the duplicate string sub-elements aren't being parsed by SL4?

Maybe it should be <string> 
```
<dict>
			<key>name</key>
			<string>diff.deleted</string>
			<key>scope</key>
			<string>markup.deleted</string>
			<key>settings</key>
			<dict>
				<key>background</key>
				<string>#151515</string>
				<key>foreground</key>
				<string>#CF5340</string>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>diff.changed</string>
			<key>scope</key>
			<string>markup.changed</string>
			<key>settings</key>
			<dict>
				<key>background</key>
				<string>#B4D388</string>
				<key>foreground</key>
				<string>#92BFBF</string>
			</dict>
		</dict>
```

This theme also has some interesting sublime linter stuff.

```
<dict>
			<key>name</key>
			<string>SublimeLinter Annotations</string>
			<key>scope</key>
			<string>sublimelinter.outline.notes</string>
			<key>settings</key>
			<dict>
				<key>background</key>
				<string>#EDE480</string>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>SublimeLinter Outline</string>
			<key>scope</key>
			<string>sublimelinter.outline.illegal</string>
			<key>settings</key>
			<dict>
				<key>background</key>
				<string>#F18260</string>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>SublimeLinter Underline</string>
			<key>scope</key>
			<string>sublimelinter.underline.illegal</string>
			<key>settings</key>
			<dict>
				<key>background</key>
				<string>#CF5340</string>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>SublimeLinter Warning Outline</string>
			<key>scope</key>
			<string>sublimelinter.outline.warning</string>
			<key>settings</key>
			<dict>
				<key>background</key>
				<string>#F49D62</string>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>SublimeLinter Warning Underline</string>
			<key>scope</key>
			<string>sublimelinter.underline.warning</string>
			<key>settings</key>
			<dict>
				<key>background</key>
				<string>#CF5340</string>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>SublimeLinter Violation Outline</string>
			<key>scope</key>
			<string>sublimelinter.outline.violation</string>
			<key>settings</key>
			<dict>
				<key>background</key>
				<string>#777777</string>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>SublimeLinter Violation Underline</string>
			<key>scope</key>
			<string>sublimelinter.underline.violation</string>
			<key>settings</key>
			<dict>
				<key>background</key>
				<string>#FF000050</string>
			</dict>
		</dict>
```

**Comment by kaste** [comment]
Are then just use one of them! 

What do you mean by

> Maybe the duplicate string sub-elements aren't being parsed by SL4

?

**Comment by DevBrent** [comment]
What do you mean just use one of them? Like region.changedish lol?

**Comment by kaste** [comment]
Haha. Sublime doesn't like the background you have here. If you just use markup.deleted etc.  Remove the background coloring, and 🌮

**Comment by braver** [comment]
> What do you mean just use one of them

If your theme defines e.g. `sublimelinter.underline.violation`, you can use that scope. We're not automatically using `sublimelinter.something` scopes anymore. 

In general [scopes](https://www.sublimetext.com/docs/3/scope_naming.html) are like `constant.numeric` or `entity.name.class`. If you see a nice color, you can find out what scope it is by using the menu option Tools > Developer > Show Scope Name:

<img width="274" alt="screen shot 2018-03-02 at 18 16 50" src="https://user-images.githubusercontent.com/2543659/36912123-10a7c124-1e46-11e8-84ad-4631e54c3d5e.png">

In this case you can hit the "copy" button and use that entire scope, but usually something shorter also works, like `keyword.control`.

**Comment by byaka** [comment]
for me helped upgrading to 3157 version

**Comment by Shelagh-Lewins** [comment]
Any thoughts why my gutter icons are white? The text highlighting is in colour, red and yellow.

```
"gutter_theme": "none",

"styles": [
        {
            "mark_style": "fill",
            "priority": 1,
            "scope": "region.yellowish markup.changed.sublime_linter markup.warning.sublime_linter",
            "icon": "dot",
            "types": [
                "warning"
            ]
        },
        {
            "mark_style": "fill",
            "priority": 1,
            "scope": "region.redish markup.deleted.sublime_linter markup.error.sublime_linter",
            "icon": "dot",
            "types": [
                "error"
            ]
        }
    ],
```

**Comment by kaste** [comment]
Haha @braver I thought this is a plugin I installed.

But have you checked, if you set a background and foreground Sublime draws the background!

**Comment by DevBrent** [comment]
I really miss warning color and error color.

**Comment by DevBrent** [comment]
That's good news at least. Right now I'm limited to the choices of the theme developers it seems, and everything about predawn is nice except there are bugs with how some of the scopes are parsed only now in SL4 it seems. Maybe the bugs were always there. I noted one thing in their variables... you were looking for `markup.error.sublime_linter` and they had `sublimelinter.mark.error`

**Comment by 2Pacalypse-** [comment]
I also don't get any highlighting of errors at all. SublimeLinter successfully lints the file and displays the errors in the console, but then it outputs an error when it tries to highlight them. Log:
```
Traceback (most recent call last):
  File "lint.events in /Users/engine/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 28, in broadcast
  File "highlight_view in /Users/engine/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 91, in on_lint_result
  File "highlight_view in /Users/engine/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 308, in prepare_highlights_data
  File "highlight_view in /Users/engine/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 350, in get_scope
  File "lint.style in /Users/engine/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 54, in wrapper
  File "lint.style in /Users/engine/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 97, in get_val
AttributeError: 'NoneType' object has no attribute 'split'
```
Any ideas?

**Comment by braver** [comment]
@2Pacalypse- that looks like something completely different. Please enable the debug setting and open a new issue with the full output from the console.

**Comment by cnk** [comment]
I am also missing colors that would help distinguish linter errors (small white dots) from git annotations. My current Theme is Flatland Dark. I'll try some of the suggestions earlier in the thread but have a possibly related question, did `"show_errors_on_save": true,` go away? Having the list of errors show up at the top of my window was my major means of insisting I adhere to the team linting settings.

**Comment by braver** [comment]
> did "show_errors_on_save": true, go away?

Yes, it's gone. If you really want to enforce stuff, pre-commit hooks are the way to go.

**Comment by kaste** [comment]
@cnk I think about this one.

**Comment by kaste** [comment]
@cnk I have (actually had bc SL4 broke them naturally) had two plugins for that. One that flashed/colorized the status bar in red or some other color when I had errors/warnings. One that showed a toast message.

**Comment by sebastienbarre** [comment]
> I really miss warning_color and error_color.

@DevBrent if you figured out an easy way to bring these back, please hit me up (which files to edit, etc). Thx

**Comment by braver** [comment]
I’ll document a way to set up custom colors for ST > 3148 later, hopefully this week.

**Comment by arcman77** [comment]
@2Pacalypse-

Removing this file `\\Sublime Text 3\\Packages\\User\\SublimeLinter (old).sublime-settings` solved that issue for me

**Comment by brownieboy** [comment]
I was having issues with the Mac Classic colour scheme, which is actually a hangover from Sublime Text 2.  Under the latest stable build of Sublime, 3143 as I write this, the error and warning indicators (gutter and text highlighted) were all black.

Upgrading to dev build 3165 fixed that for me.  I now have red warnings and yellow warnings, just like I did in SublimeLinter 3.
