### ISSUE TITLE
[contrib-clang] Linter Crashed

### ISSUE THREAD

**Issue by jjbaca** [SublimeLinter/SublimeLinter#1052]
The new version is giving me issues. It is not highlighting the erros and shows me messages like this one basically every time I type a word:
SublimeLinter: #1 clang main.c ERROR:

 Linter crashed.

Traceback (most recent call last):
  File "lint.backend in /home/student/.config/sublime-text-3/Installed Packages/SublimeLinter.sublime-package", line 97, in execute_lint_task
  File "lint.linter in /home/student/.config/sublime-text-3/Installed Packages/SublimeLinter.sublime-package", line 794, in lint
  File "lint.linter in /home/student/.config/sublime-text-3/Installed Packages/SublimeLinter.sublime-package", line 500, in get_cmd
  File "/home/student/.config/sublime-text-3/Packages/SublimeLinter-contrib-clang/linter.py", line 78, in cmd
    if persist.get_syntax(self.view) in ['c', 'c improved']:
AttributeError: 'module' object has no attribute 'get_syntax'

**Comment by braver** [comment]
The clang plugin needs to be updated: https://github.com/nirm03/SublimeLinter-clang/issues/33

**Comment by JeremyCraigMartinez** [comment]
Related to https://github.com/SublimeLinter/SublimeLinter/issues/1041?

**Comment by braver** [comment]
@JeremyCraigMartinez could be. The flow plugin is huge so there might be something wrong there similar to the clang plugin here. I don't know the first thing about flow though, so not sure how to test for that.

**Comment by kaste** [comment]
clang has a PR since about a month.

**Comment by braver** [comment]
Yeah, we'll give it some time and if the situation doesn't improve we can always overtake the repo.

**Comment by kaste** [comment]
Ah it doesn't have contrib in the repo name, so I thought you could merge.

**Comment by braver** [comment]
Sadly no. But I'm not against a "~hostile~ friendly takeover" if it takes too long. It's open source for a reason 😉

**Comment by jjbaca** [comment]
They say "persist.get_syntax should become util.get_syntax". Is that what I have to do? If so, how do I do it? I tried to get there but I can't find it.

**Comment by braver** [comment]
This PR is basically what needs to happen: https://github.com/nirm03/SublimeLinter-clang/pull/35/files

**Comment by braver** [comment]
A 1.1.0 with fix has been published, should be available within an hour.

**Comment by jjbaca** [comment]
I just reinstalled everything. Now It is not showing anything. No errors from the linter (which is good) or errors in the code (such as undeclared variables, unused ones, wrong loop syntax, calling functions, etc)  It is like it's not active anymore.
Any suggestions? 
Thanks

**Comment by braver** [comment]
Have a debug log?
