### ISSUE TITLE
Could you please not delete my configuration because of an update?

### ISSUE THREAD

**Issue by timmyrs** [SublimeLinter/SublimeLinter#1053]
I just had to reconfigure SublimeLinter, which was a pain in the ass the first time already, because of some stupid update. Please don't do that again, thanks.

**Comment by braver** [comment]
The docs are pretty clear about why that happened and what happened. Also, your config was backed up.

If you think this update is stupid, you can just manually install some old version so you don't have to deal with us actually maintaining this thing for you for free.

**Comment by timmyrs** [comment]
I saw the backup, but it was empty.

**Comment by braver** [comment]
Well that's never happened before. Weird.

**Comment by timmyrs** [comment]
I just noticed `ignore_match` no longer exists... So, how do I manually install an old version?

**Comment by displayadrian** [comment]
To manually install the previous version:

1. Uninstall SublimeLinter via Package Control

2. Download the ZIP file from here: https://github.com/SublimeLinter/SublimeLinter/releases/tag/v3.10.10

3. Place the unzipped folder in your Packages folder (not User)

4. Rename the folder as SublimeLinter

5. Restart Sublime

6. Edit prefs and restore from the backup in Packages > Users which would have been created by the new version

**Comment by timmyrs** [comment]
Thank you. Just got around to doing it, but it's so much better to have a stable plugin that doesn't crash or delete my configuration and way easier to maintain.
