### ISSUE TITLE
[Version 4] with the default lint mode, "background", the linter is not run when a file is opened

### ISSUE THREAD

**Issue by darkred** [SublimeLinter/SublimeLinter#1054]
Using ST 3 dev build 3157, SublimeLinter 4.0.1, SublimeLinter-eslint 4.0.0, ESlint 4.18.1 in win10x64

I quote from the SublimeLinter.sublime-settings:

```javascript
    // Lint Modes determine when the linter is run
    // background: asynchronously on every change
    // load_save: when a file is opened and every time it's saved
    // manual: only when calling the Lint This View command
    "lint_mode": "background",
```

i.e. i. SL4 with the default lint mode, "background", whenever you open a file, the linter is not run. It's only run if you modify the file, i.e. type or delete something on it.
But, if you don't want or just forget to modify it, then it's not linted, giving you the wrong impression that the file is fine.

_For reference, in SL3, with the "background" lint mode, the file was linted on load._

What I'd prefer is having a 4th mode, something like" load_and_background",
i.e. lint the file on load, and then lint it again asynchronously on every change.

<br/>

So, could you please consider adding such a lint mode? That's my suggestion.

**Comment by braver** [comment]
Hm, that's a bug actually, it should just run right away.

**Comment by darkred** [comment]
As I see, regarding file loading, the linter is only run when you first launch ST, on the restored files from last session.
The linter is not run when you open a file via the windows explorer context menu, neither via File Open, nor via File|'Open Recent' entries.

**Comment by darkred** [comment]
Thank you for fixing this.
