### ISSUE TITLE
Opening a new file does not trigger linting (sometimes?)

### ISSUE THREAD

**Issue by alecthomas** [SublimeLinter/SublimeLinter#1063]
I've seen this with the gometalinter plugin and the builtin Python plugins.

**Comment by kaste** [comment]
That's not specific.

**Comment by alecthomas** [comment]
Well, for me it *never* lints a newly opened file. It is 100% reproducible.

**Comment by alecthomas** [comment]
I'll look in the debug logs next time.

**Comment by kaste** [comment]
Do you have #1056

**Comment by braver** [comment]
Check the version number in the debug log. It should say 4.0.2. If it does and the problem still occurs please reopen this issue.

**Comment by josezulu** [comment]
I have 4.0.2, lint_mode on load_save. Opening files does not trigger linting. Saving a file does.
I'm not sure what @alecthomas means by "new" files, I'm opening files which already exist.
If the file is already in the buffer when ST opens, then it does lint them.

**Comment by alecthomas** [comment]
I _was_ seeing this under the same conditions, but with the latest update from PackageControl I no longer have any issues. I am using `"lint_mode": "background"`.

**Comment by braver** [comment]
I think we need to look at the other lint modes some more.
