### ISSUE TITLE
SL4: html entities are not rendered in error output

### ISSUE THREAD

**Issue by sebastienbarre** [SublimeLinter/SublimeLinter#1065]
Here is what I'm seeing now with SL4:
```
Controller/TimeEntriesController.php:
    95:10   error          phpcs: error        Method name &quot;TimeEntriesController::index_table&quot; is not in camel caps format
   400:10   error          phpcs: error        Method name &quot;TimeEntriesController::time_card&quot; is not in camel caps format
```
Note the `&quot;` instead of `"`.

**Comment by kaste** [comment]
What is the linter output here? Please open the Sublime console for that. It should print `output: ...` if debug is True. (I don't think we do the quoting here. At least intentional.)

**Comment by sebastienbarre** [comment]
```
SublimeLinter: #1 SublimeLinter.sublime-package:809: phpcs output:
    <?xml version="1.0" encoding="UTF-8"?>
    <checkstyle version="2.7.1">
    <file name="${file}">
     <error line="95" column="10" severity="error" message="Method name &quot;TimeEntriesController::index_table&quot; is not in camel caps format" source="PSR1.Methods.CamelCapsMethodName.NotCamelCaps"/>
     <error line="400" column="10" severity="error" message="Method name &quot;TimeEntriesController::time_card&quot; is not in camel caps format" source="PSR1.Methods.CamelCapsMethodName.NotCamelCaps"/>
 ```
So it appears in the XML. I think what might be happening is that SL3 was rendering them correctly. Right now it's pretty hard to read.
Thanks

**Comment by kaste** [comment]
Okay, we should switch to a different report mode here as well.

**Comment by braver** [comment]
👍🏻We’re not set up to deal with XML here, so if the linter can give use something else that’d be ideal.

**Comment by kaste** [comment]
@braver Currently this linter parses XML, we could use `--report=emacs` style https://github.com/squizlabs/PHP_CodeSniffer/wiki/Reporting#printing-an-emacs-report which is probably trivial to parse via regex. Otherwise, we could use JSON.

**Comment by braver** [comment]
I think that’s a bit rough to expose to users as “code” but losing that isn’t a terrible compromise imo. How about the CSV report?

**Comment by kaste** [comment]
Well you cannot parse CSV using a regex.

**Comment by braver** [comment]
True, but perhaps there is a library to parse it with? I don't know, just throwing ideas around. If using emacs format is easy but we don't have error codes, that sounds like a good solution to me. Lot's of linters don't provide codes for us.

**Comment by kaste** [comment]
Erm, I pinged you bc that's regex land, and you know who does the regexes.

I only do json.

**Comment by braver** [comment]
Haha, sure. I’ll try to whip up a PR.

**Comment by braver** [comment]
Can you guys test https://github.com/SublimeLinter/SublimeLinter-phpcs/pull/28 for me?

**Comment by sebastienbarre** [comment]
It works (at least for errors). Thanks @braver

**Comment by braver** [comment]
🎉

**Comment by braver** [comment]
2.0.1 for the phpcs plugin has been released
