### ISSUE TITLE
SL4: are you passing filenames different to linters?

### ISSUE THREAD

**Issue by sebastienbarre** [SublimeLinter/SublimeLinter#1066]
Sorry for the less-than-ideal scope for that bug, but that auto-upgrade to SL4 has been really hard to debug today. 

I'm using "[SublimeLinter/SublimeLinter-phpcs: SublimeLinter plugin for PHP, using phpcs](https://github.com/SublimeLinter/SublimeLinter-phpcs)" as one of my linters. It is no longer working  properly. Since the last release was [early 2016](https://github.com/SublimeLinter/SublimeLinter-phpcs/releases), I doubt it will be upgraded. 

The gist of the issue is that linting rules in PHPCS can be tweaked to specify that a rule should be ignored for files matching specific patterns. 

For example:
```xml
  <rule ref="PSR1.Methods.CamelCapsMethodName">
    <exclude-pattern>*/*Controller.php</exclude-pattern>
  </rule>
```
This above says that the `PSR1.Methods.CamelCapsMethodName` rule should be ignored if the file  being validated matches the `*/*Controller.php` pattern (anything ending with `Controller.php`, that is).

This  was working great with SL3, but no longer with SL4 -- the file is no longer ignored and I'm getting a ton of validation errors. Since SublimeLinter/SublimeLinter-phpcs  has not changed, I'm wondering if SL4 is properly passing the filename being linted to its linters, or if it is passing it in a different way now, that would prevent linters from assessing which file is being linted.

Thanks

**Comment by braver** [comment]
Yes, we use temporary files that have a generated unique filename. The plugin should be updated to work with this, e.g. not use temporary files. The repo is in the SL org, so I bet there is someone in the team who can look into it.

**Comment by kaste** [comment]
PR is at https://github.com/SublimeLinter/SublimeLinter-phpcs/pull/26

**Comment by kaste** [comment]
@sebastienbarre Please review and test the PR and report back!

**Comment by sebastienbarre** [comment]
Unfortuantely, this didn't work.

Note that [SublimeLinter/SublimeLinter-phpmd: SublimeLinter plugin for php, using phpmd.](https://github.com/SublimeLinter/SublimeLinter-phpmd) is using the same kind of filtering.

It is likely other linters provide that filtering/exclude feature, so maybe fix it in SL4 instead?

If you need a temporary file, it would be probably help a long way if your temporary file "looked" like the original source file. For example, if you are validating `${folder}/foo/bar/yo.php` then consider using a unique temporary basename, but append it with something that look like the original filename, so we can slightly tweak our regular expressions. In this case, maybe `tmp2wsdce412_foo_bar_yo.php`, where your unique temporary basename `tmp2wsdce412_` acts as the project folder, and the rest is the path to the file, with slashes replaced with underscores. 

In the PHPCS/PHPMD regular expressions used to exclude files we can then add `_` as a possible directory delimiter (on top of the usual `/` or `\`). If the operating systems has limits on the filename length, keep the temporary prefix, but prune the rest to fit (say, `tmp2wsdce412_bar_yo.php`, where `foo_` was cut).

My 2 cents.

**Comment by kaste** [comment]
Can you post which command etc SL was running now.

**Comment by sebastienbarre** [comment]
How do you do that?

**Comment by kaste** [comment]
Enable debug mode, open the Sublime console, and look what's going on.

**Comment by sebastienbarre** [comment]
Here you go, let me know if you need more:
```
SublimeLinter: #1 SublimeLinter.sublime-package:782: 'phpcs' is linting 'TimeEntriesController.php'
SublimeLinter: #1 SublimeLinter.sublime-package:1178: phpcs: TimeEntriesController.php ['/Users/barre/.composer/vendor/bin/phpcs', '--report=checkstyle', '--stdin-path=${file}', '-']
SublimeLinter: #1 SublimeLinter.sublime-package:1181: phpcs: cwd: /Users/barre/Development/Src/kwik/master
SublimeLinter: #2 SublimeLinter.sublime-package:782: 'php' is linting 'TimeEntriesController.php'
SublimeLinter: #2 SublimeLinter.sublime-package:1178: php: TimeEntriesController.php ['/usr/bin/php', '-l', '-n', '-d', 'display_errors=On', '-d', 'log_errors=Off']
SublimeLinter: #2 SublimeLinter.sublime-package:1181: php: cwd: /Users/barre/Development/Src/kwik/master
```

**Comment by kaste** [comment]
Oh my God, I fucked up the PR. Haha.

**Comment by kaste** [comment]
Okay I updated the PR please pull. (Please post the log as you did before.)

**Comment by sebastienbarre** [comment]
Works, thanks. 

```
SublimeLinter: #1 SublimeLinter.sublime-package:782: 'php' is linting 'TimeEntriesController.php'
SublimeLinter: #1 SublimeLinter.sublime-package:1178: php: TimeEntriesController.php ['/usr/bin/php', '-l', '-n', '-d', 'display_errors=On', '-d', 'log_errors=Off']
SublimeLinter: #1 SublimeLinter.sublime-package:1181: php: cwd: /Users/barre/Development/Src/kwik/master
SublimeLinter: #2 SublimeLinter.sublime-package:782: 'phpcs' is linting 'TimeEntriesController.php'
SublimeLinter: #2 SublimeLinter.sublime-package:1178: phpcs: TimeEntriesController.php ['/Users/barre/.composer/vendor/bin/phpcs', '--report=checkstyle', '-', '--stdin-path=/Users/barre/Development/Src/kwik/master/Controller/TimeEntriesController.php']
SublimeLinter: #2 SublimeLinter.sublime-package:1181: phpcs: cwd: /Users/barre/Development/Src/kwik/master
```

**Comment by sebastienbarre** [comment]
Note that SL4 does not find linters the way SL3 did. Is this something fixable, known, do you need an issue for this?

**Comment by sebastienbarre** [comment]
For example, this is what I see:
```
SublimeLinter: SublimeLinter.sublime-package:103: PATH:
    /usr/bin
    /bin
    /usr/sbin
    /sbin
```

This is not the PATH of my interactive shell. I know I can add something to `paths.osx`, but SL3 was finding them fine, which might be a problem for people who are being auto-upgraded to SL4. 

Moreover, my Sublime settings are version controlled and shared between different machines, so the less hard-coded paths I have to add, the better :)

Thanks

**Comment by kaste** [comment]
In SL4 the path should auto-repair here. On Mac, it takes some time before PATH is correct.

**Comment by sebastienbarre** [comment]
Ok. 

Thanks for the quick fix. [This guy](https://github.com/SublimeLinter/SublimeLinter-phpmd/blob/master/linter.py) might need some love too, but no rush.

**Comment by braver** [comment]
the path isn't printed but you should see `environment variables loaded using: /usr/local/bin/fish -l` or something like that.
