### ISSUE TITLE
Some SublimeLinter plugins no longer working

### ISSUE THREAD

**Issue by Cooperdale** [SublimeLinter/SublimeLinter#1069]
Hello, I think I upgraded as described in the readme, but some lints I was using no longer work.

I get this:
`SublimeLinter: SublimeLinter.sublime-package:1055: WARNING: phplint deactivated, cannot locate ''`
`SublimeLinter: SublimeLinter.sublime-package:1055: WARNING: htmltidy deactivated, cannot locate ''`

Are these maybe not yet compatible with version 4?

**Comment by braver** [comment]
Are the executables for those linters in your $PATH?

**Comment by kaste** [comment]
Probably restart Sublime. Then post a bit more from the console so that I can easily see when these warnings are outputted.

**Comment by Cooperdale** [comment]
It was a path problem actually. Sorry. It was probably there before the update.
