### ISSUE TITLE
tempfile_suffix : real file vs tmp file

### ISSUE THREAD

**Issue by NotSqrt** [SublimeLinter/SublimeLinter#107]
Hi !

For SublimeLinter-pylint, I just tested this:

``` python
    @property
    def tempfile_suffix(self):
        """
        Use the real file if possible
        """
        mode = persist.settings.get('lint_mode', 'background')
        if mode in ('load/save', 'save only') or not self.view.is_dirty():
            return '-'
        else:
            return 'py'
```

The purpose is to find a middle ground between :
- the ability to check relative imports with pylint, which requires the use of the real file,
- and background linting on temporary files

Should this snippet stay in my linter, or would it be a nice addition to SublimeLinter ?

**Comment by braver** [comment]
Right now, this sits in pylint just fine (it's OOP for a reason), but PR's are of course welcome.
