### ISSUE TITLE
User-Settings error when upgrading to v4

### ISSUE THREAD

**Issue by aphearin** [SublimeLinter/SublimeLinter#1070]
### Summary

After updating to SublimeLinter v4 and rebooting st3, I was flashed a message that my Package Control user settings files had been moved to a backup location. Then I saw a display for an error message: 
```
Settings file not found: Packages/User/SublimeLinter.sublime-settings
```
I do not know the cause; I was not provided a reason for why this happened. However, I keep a backup copy of my user-settings file elsewhere on disk. So I tried to reimplement the settings file by navigating through st3 via `Preferences/PackageSettings/SublimeLinter/Settings`, and when I copy-and-paste the contents of my previously functional user-settings file and try to save, I now receive an error:

```
SublimeLinter: ERROR:

 Invalid settings in 'Packages/User/SublimeLinter.sublime-settings':
Additional properties are not allowed ('user' was unexpected)
```
Here is [a gist showing the previously functional user-settings file.](https://gist.github.com/aphearin/fbd189a184fce21de6935d4530b2a56e) 

It seems that the v4 upgrade has changed the format of how the json file is interpreted into settings recognized by SublimeLinter. I have tried uninstalling and reinstalling SublimeLinter, and then trying to adapt and match patterns from my previously functional user-settings file, but without much success: the behavior of SublimeLinter does not seem to respond to changes in the settings file. A copy of my attempt to adapt my previous settings to work with the new v4 json format can be found in [this second gist. ](https://gist.github.com/aphearin/1597c42811aa152f51ba94b28eeb0bf6)

### Environment

I am operating on Mac OS 10.12.6, with ST3 Build 3143

**Comment by kaste** [comment]
For flake8 see https://github.com/SublimeLinter/SublimeLinter/issues/1050

**Comment by aphearin** [comment]
Thanks @kaste - this resolves my issue.

**Comment by Senomo** [comment]
Hi!
I have a similar problem after update 4v SublimeLinter, but this solution does not help.
Tell me why SublimeLinter does not accept 'user'?

My error message
```
`SublimeLinter: ERROR:

 Invalid settings in 'Packages/User/SublimeLinter.sublime-settings':
Additional properties are not allowed ('user' was unexpected)`
```

My config

```
// SublimeLinter Settings - User
{
    "user": {
        "debug": true,
        "delay": 0.25,
        "error_color": "D02000",
        "gutter_theme": "Packages/SublimeLinter/gutter-themes/Circle/Circle.gutter-theme",
        "gutter_theme_excludes": [],
        "lint_mode": "background",
        "linters": {
            "jscs": {
                "@disable": false,
                "args": [],
                "excludes": []
            },
            "jshint": {
                "@disable": false,
                "args": [],
                "excludes": []
            },
            "jsl": {
                "@disable": false,
                "args": [],
                "excludes": []
            },
            "php": {
                "@disable": false,
                "args": [],
                "excludes": []
            },
            "phplint": {
                "@disable": false,
                "args": [],
                "excludes": []
            }
        },
        "mark_style": "outline",
        "no_column_highlights_line": false,
        "passive_warnings": false,
        "paths": {
            "linux": [],
            "osx": [],
            "windows": []
        },
        "python_paths": {
            "linux": [],
            "osx": [],
            "windows": []
        },
        "rc_search_limit": 3,
        "shell_timeout": 10,
        "show_errors_on_save": false,
        "show_marks_in_minimap": true,
        "sublimelinter": true,
        "sublimelinter_executable_map": {
            "php": "C:\\Program Files\\PHP_5.6\\php.exe" //путь до вашей папки с php.exe
        },
        "syntax_map": {
            "js": "js",
            "php": "php",
            "python django": "python"
        },
        "warning_color": "DDB700",
        "wrap_find": true
    }
}
```

**Comment by braver** [comment]
Because: https://github.com/SublimeLinter/SublimeLinter/blob/master/messages/4.0.0.txt


> Changes to settings
> -------------------------------------------
> 
> Default settings now have documentation in line.
> Default settings can no longer be edited.
> Default settings are no longer copied to the user settings.
> - Learn about the configuration options for each linter in the docs and
  > in the README of the linter plugin.
> 
> The "user" node has been removed from settings.
> A python version can no longer be set globally.
> The "chdir" setting has been renamed to "working_dir".
> 
> The settings "ignore_matches" and "demote_to_warning_matches" have been removed.
> Your linter should have settings to modify the rules or severity levels.
> 
> Settings tokens (e.g. ${folder}) are now expanded using SublimeText features,
> so there are more tokens you can use. The docs covers this in more detail.
> 
> The new output panel and filtering have supplanted the "make_warnings_passive"
> and "show_errors_on_save" features.
> 
> Settings can be specified in your user settings, or in project configuration
> (*.sublime-project files). Inline settings, inline overrides, shebang settings
> and .sublimelinterrc files are no longer supported.

**Comment by aphearin** [comment]
These docs are well written @braver, but they are not at all "discoverable".  It would have been helpful if st3 had flashed a link to this page upon upgrade .

**Comment by braver** [comment]
You should have seen a post upgrade message with this information. Also, we pushed messages to SL3 users a few times with links to this document.

**Comment by randonia** [comment]
I'm here because I also didn't notice this message during ST3's upgrade. I don't think it is the fault of the SublimeLinter team, ST3 should have a more authoritative method of notifying users of breaking changes IMO :) Those patch notes often are easy to just dismiss/ignore.

Thanks for your quick answer @braver

**Comment by morenopc** [comment]
@braver Can you give me an example of how to `"ignore_match": [".*proprietary attribute"]` at version 4? Thanks.

**Comment by braver** [comment]
@morenopc what linter are you using?

**Comment by braver** [comment]
Oh, nevermind
