### ISSUE TITLE
SublimeLinter do not lints at all (v4)

### ISSUE THREAD

**Issue by ilblog** [SublimeLinter/SublimeLinter#1071]
- OS X
- ST3
- Latest ver of Sublime Linter
- Latest ver of SublimeLinter-eslint
- eslint properly installed and in PATH (latest ver)

Default configuration and only few packages installed.

Whatever I do Sublime Linter displays `E:0 W:0` at the status bar, but do not lint at all. Even shortcut CTRL+cmd+L do not work.

```
SublimeLinter: SublimeLinter.sublime-package:71: Logging installed; log level INFO
SublimeLinter: SublimeLinter.sublime-package:62: debug mode: on
SublimeLinter: SublimeLinter.sublime-package:63: version: 4.0.2
```
I there would be chance to download prev version would be happy

Update: It seems that jshint with SublimeLinter-jshint works flawlesly

**Comment by kaste** [comment]
Eslint plugin does not recognize the syntax of your view. Setup syntax_map in the User settings or set selector in the linter settings.

**Comment by ilblog** [comment]
Thank you for a tip

**Comment by ilblog** [comment]
Works. Thank you
