### ISSUE TITLE
linters no longer work

### ISSUE THREAD

**Issue by JovannyElias** [SublimeLinter/SublimeLinter#1075]
How can I correct the path so that my all my linters work properly. I am fairly new to coding so any detailed help would be great. I have tried to look elsewhere but had not luck. thanks 

`DPI scale: 1.25
startup, version: 3143 windows x64 channel: stable
executable: /C/Program Files/Sublime Text 3/sublime_text.exe
working dir: /C/Program Files/Sublime Text 3
packages path: /C/Users/Jovanny/AppData/Roaming/Sublime Text 3/Packages
state path: /C/Users/Jovanny/AppData/Roaming/Sublime Text 3/Local
zip path: /C/Program Files/Sublime Text 3/Packages
zip path: /C/Users/Jovanny/AppData/Roaming/Sublime Text 3/Installed Packages
ignored_packages: ["Vintage"]
Errors parsing theme:
icon_file_type is missing layer0.opacity, setting to 1.0 for backwards compatibility
icon_folder is missing layer0.opacity, setting to 1.0 for backwards compatibility
pre session restore time: 0.206906
font face "Menlo" could not be found, defaulting to "Consolas"
startup time: 0.295906
first paint time: 0.300906
reloading plugin Default.auto_indent_tag
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.install_package_control
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.quick_panel
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.settings
reloading plugin Default.show_scope_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin Default.ui
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin 0_package_control_loader.00-package_control
reloading plugin 0_package_control_loader.01-pygments
reloading plugin 0_package_control_loader.50-pyyaml
reloading plugin 0_package_control_loader.55-jsonschema
reloading plugin Emmet.emmet-plugin
reloading plugin Environment Settings.EnvironmentSettings
reloading plugin Markdown Preview.helper
reloading plugin Markdown Preview.markdown_settings
reloading plugin Markdown Preview.markdown_wrapper
reloading plugin Markdown Preview.MarkdownPreview
reloading plugin Package Control.1_reloader
reloading plugin Package Control.2_bootstrap
reloading plugin Package Control.Package Control
reloading plugin requirementstxt.requirements
reloading plugin SideBarEnhancements.SideBar
reloading plugin SideBarEnhancements.SideBarAPI
reloading plugin SideBarEnhancements.SideBarDefaultDisable
reloading plugin SublimeLinter-csslint.linter
reloading plugin SublimeLinter-html-tidy.linter
reloading plugin SublimeLinter-jshint.linter
reloading plugin SublimeLinter-json.linter
reloading plugin SublimeLinter-pycodestyle.linter
reloading plugin SublimeLinter-pyflakes.linter
reloading plugin SublimeLinter-pyyaml.linter
reloading plugin SublimeLinter.__init__
reloading plugin SublimeLinter.busy_indicator_view
reloading plugin SublimeLinter.commands
reloading plugin SublimeLinter.goto_commands
reloading plugin SublimeLinter.highlight_view
reloading plugin SublimeLinter.log_handler
reloading plugin SublimeLinter.message_view
reloading plugin SublimeLinter.panel_view
reloading plugin SublimeLinter.status_bar_view
reloading plugin SublimeLinter.sublime_linter
reloading plugin SublimeLinter.tooltips_view
reloading plugin Anaconda.anaconda
reloading plugin Anaconda.setup
reloading plugin Anaconda.version
plugins loaded
SublimeLinter: SublimeLinter.sublime-package:71: Logging installed; log level INFO
SublimeLinter: SublimeLinter.sublime-package:62: debug mode: on
SublimeLinter: SublimeLinter.sublime-package:63: version: 4.0.2
Emmet: No need to update PyV8
SublimeLinter: SublimeLinter.sublime-package:252: detected syntax: python
SublimeLinter: #1 SublimeLinter.sublime-package:782: 'pycodestyle' is linting 'purpledecagon.py'
SublimeLinter: #1 SublimeLinter.sublime-package:48: pycodestyle: wanted python is 'None'
SublimeLinter: #2 SublimeLinter.sublime-package:782: 'pyflakes' is linting 'purpledecagon.py'
SublimeLinter: #2 SublimeLinter.sublime-package:48: pyflakes: wanted python is 'None'
SublimeLinter: #1 SublimeLinter.sublime-package:99: pycodestyle: trying to use globally installed pycodestyle
SublimeLinter: #1 SublimeLinter.sublime-package:103: PATH:
    C:\Program Files (x86)\Common Files\Intel\Shared Libraries\redist\intel64\compiler
    C:\ProgramData\Oracle\Java\javapath
    C:\Program Files\ImageMagick-6.8.9-Q16
    C:\Program Files (x86)\Intel\iCLS Client\
    C:\Program Files\Intel\iCLS Client\
    C:\WINDOWS\system32
    C:\WINDOWS
    C:\WINDOWS\System32\Wbem
    C:\WINDOWS\System32\WindowsPowerShell\v1.0\
    C:\Program Files (x86)\Intel\OpenCL SDK\2.0\bin\x86
    C:\Program Files (x86)\Intel\OpenCL SDK\2.0\bin\x64
    C:\Program Files\Intel\Intel(R) Management Engine Components\DAL
    C:\Program Files\Intel\Intel(R) Management Engine Components\IPT
    C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL
    C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT
    C:\Program Files\Condusiv Technologies\ExpressCache\
    C:\Program Files\nodejs\
    C:\HashiCorp\Vagrant\bin
    C:\Program Files (x86)\Skype\Phone\
    C:\Users\Jovanny\AppData\Local\Programs\Python\Python37\python.exe
    C:\Users\Jovanny\AppData\Local\Programs\Python\Python37\
    C:\Users\Jovanny\AppData\Local\Programs\Python\Python37\Scripts\
    C:\Ruby200\bin
    C:\Users\Jovanny\AppData\Roaming\npm
    C:\Users\Jovanny\AppData\Local\Microsoft\WindowsApps
    C:\Program Files\Microsoft VS Code\bin
    C:\Program Files\Sublime Text 3

SublimeLinter: #2 SublimeLinter.sublime-package:99: pyflakes: trying to use globally installed pyflakes
SublimeLinter: #1 SublimeLinter.sublime-package:107: WARNING: cannot locate 'pycodestyle'. Fill in the 'python' or 'executable' setting.
SublimeLinter: #2 SublimeLinter.sublime-package:107: WARNING: cannot locate 'pyflakes'. Fill in the 'python' or 'executable' setting.
Package Control: Skipping automatic upgrade, last run at 2018-03-03 18:08:21, next run at 2018-03-03 19:08:21 or after
SublimeLinter: #3 SublimeLinter.sublime-package:782: 'pycodestyle' is linting 'purpledecagon.py'
INFO:SublimeLinter.lint.linter:'pycodestyle' is linting 'purpledecagon.py'
SublimeLinter: #3 SublimeLinter.sublime-package:48: pycodestyle: wanted python is 'None'
INFO:SublimeLinter.lint.base_linter.python_linter:pycodestyle: wanted python is 'None'
SublimeLinter: #4 SublimeLinter.sublime-package:782: 'pyflakes' is linting 'purpledecagon.py'
INFO:SublimeLinter.lint.linter:'pyflakes' is linting 'purpledecagon.py'
SublimeLinter: #4 SublimeLinter.sublime-package:48: pyflakes: wanted python is 'None'
INFO:SublimeLinter.lint.base_linter.python_linter:pyflakes: wanted python is 'None'
SublimeLinter: #3 SublimeLinter.sublime-package:99: pycodestyle: trying to use globally installed pycodestyle
INFO:SublimeLinter.lint.base_linter.python_linter:pycodestyle: trying to use globally installed pycodestyle
SublimeLinter: #4 SublimeLinter.sublime-package:99: pyflakes: trying to use globally installed pyflakes
INFO:SublimeLinter.lint.base_linter.python_linter:pyflakes: trying to use globally installed pyflakes
SublimeLinter: #3 SublimeLinter.sublime-package:107: WARNING: cannot locate 'pycodestyle'. Fill in the 'python' or 'executable' setting.
SublimeLinter: #4 SublimeLinter.sublime-package:107: WARNING: cannot locate 'pyflakes'. Fill in the 'python' or 'executable' setting.
WARNING:SublimeLinter.lint.base_linter.python_linter:cannot locate 'pycodestyle'. Fill in the 'python' or 'executable' setting.
WARNING:SublimeLinter.lint.base_linter.python_linter:cannot locate 'pyflakes'. Fill in the 'python' or 'executable' setting.
`

**Comment by kaste** [comment]
Hi 👋 

You probably just forgot to `pip install pycodestyle pyflakes`. You have to do this on the command line-

**Comment by JovannyElias** [comment]
Thank you. works perfectly now.

**Comment by braver** [comment]
🎉

**Comment by geoidesic** [comment]
Didn't work for me.
