### ISSUE TITLE
SL4: disabling a linter plugin has no effect until a Sublime restart

### ISSUE THREAD

**Issue by Mitranim** [SublimeLinter/SublimeLinter#1076]

**Comment by kaste** [comment]
There are multiple ways to disable a linter. So could you provide a description here.

**Comment by Mitranim** [comment]
Pretty sure SL4 doesn't provide any way to disable a linter, so you're left with the only option: disable that linter plugin entirely. SL4, however, keeps calling it until a Sublime restart.

**Comment by braver** [comment]
If you disable a plugin via package control you need to restart Sublime Text. There is a reload command for SL that may also work, but restarting is a safe bet.

We have a whole bunch of documentation out there that is probably pretty clear about how to disable linters: http://www.sublimelinter.com/en/stable/linter_settings.html

**Comment by Mitranim** [comment]
I appreciate the response but don't you think it's a very fiddly solution for something that required just two key combinations in SL3? Shouldn't SL4 just check if a plugin is disabled before running a lint?

**Comment by Mitranim** [comment]
Consider misbehaving plugins. Currently, `SublimeLinter-contrib-eslint_d` crashes in anonymous buffers, which causes SL4 to show an error panel. With background linting, this happens _after every keystroke_. Of course this needs to be fixed on the linter level, but it would also be nice if SL4 required a workaround as simple as disabling a plugin. Which SL3 used to.

**Comment by Mitranim** [comment]
This all makes sense. How about checking if a plugin is disabled before running a lint? You'd think that would be a no-brainer.

**Comment by Mitranim** [comment]
The above is not just for broken plugins. I do occasionally toggle linting during normal work; sometimes you're deep in thought writing experimental half-pseudocode and don't want any distractions. Can, of course, toggle the entire SL, but that also affects other languages...

**Comment by braver** [comment]
Ok, I think the title needs to be rephrased, but now this topic raises some interesting points.

**Comment by braver** [comment]
So, what I’m thinking is this. SL3 used to manipulate the settings file. That’s not good. The right thing to do is toggle the linter only for that view, in the view settings. They aren’t saved anywhere, but that’s exactly what you want: stop linting this view because I’m just messing about. There is a toggle word-wrap command that works the same way. If I’m right we already use the view setting, so it should be doable to wire up a toggle command.

**Comment by kaste** [comment]
@Mitranim I already moved/refactored the code in a direction to make these things possible. Currently there is no need for an extra issue here. For the specific way @braver describes here, we have an open issue.

**Comment by braver** [comment]
👍🏻

**Comment by trych** [comment]
Sorry, I don't quite undrestand. What is the current status? How do I quickly, temporarily disable the linting?
Do I need to set the flag to false in the SublimeLinter settings and then restart? That seems like a really cumbersome workflow.

**Comment by braver** [comment]
You can set up your settings like so and comment/uncomment the lines that say "disable":

```json
// SublimeLinter Settings - User
{
    "linters": {
        "annotations": {
            // "disable": true,
        },
        "pycodestyle": {
            // "disable": true,
        }
    }
}
```
