### ISSUE TITLE
Possible typo/inconsistency

### ISSUE THREAD

**Issue by Odyseus** [SublimeLinter/SublimeLinter#1077]
Hello, everybody.

There is a possible typo/inconsistency in the [file with the new changes](https://raw.githubusercontent.com/SublimeLinter/SublimeLinter/master/messages/4.0.0-rc.1.txt) on the new version 4. It reads:

```
Note that "@disabled" is now "disabled", without the "@".
```

All throughout the documentation the `disable` name is used as the key name for that linter setting.

**Comment by braver** [comment]
🤔

**Comment by ntwb** [comment]
FYI: I believe another change is required, see my comment on the commit https://github.com/SublimeLinter/SublimeLinter/commit/77e7b3890ef609329df20418267bf2611d56e862#commitcomment-27920147

**Comment by kiddick** [comment]
So what should we don now with settings for linter especially with same keyword `disable`?
`disable` has different meaning for pylint for example "disable": "C0103, C0111, R0903, R0901, R0913",

**Comment by braver** [comment]
pylint has a setting called `--disable=`. It used to have an inline override for `disable`, but inline overrides no longer work in SL4.
