### ISSUE TITLE
Linter is not showing any errors

### ISSUE THREAD

**Issue by jjbaca** [SublimeLinter/SublimeLinter#1080]
After having some issues with the update a couple days ago, I reinstalled everything over right now. It is not showing any kind of errors, such as undeclared variables, unused ones, loop syntax, function calling, pointers. Absolutely nothing. Any suggestions?
Thank you

**Comment by kaste** [comment]
Please enable debug mode in the user settings. Restart Sublime and post full console log.

**Comment by jjbaca** [comment]
I don't see such as option. It just opens a windows with this:
{
	"color_scheme": "Packages/User/SublimeLinter/Monokai (SL).tmTheme",
	"font_size": 9,
	"hot_exit": false,
	"ignored_packages":
	[
		"Vintage"
	]
}
Do I need to change something there?

**Comment by braver** [comment]
You need to look for the SublimeLinter settings, not the general ST ones.

**Comment by jjbaca** [comment]
I'm sorry, I get to this part:
// Set to true to print extra information in the console.
    "debug": false,
But it doesn't allow me to edit it. Do I need to press something to activate it?

**Comment by braver** [comment]
Screenshot or it didn't happen :)

**Comment by jjbaca** [comment]
![2018-03-05_0424](https://user-images.githubusercontent.com/35800760/36971922-51693214-203b-11e8-8966-4eae5afce830.png)
Did that work?

**Comment by jjbaca** [comment]
When I click or double-click to edit the "false", nothing happens.

**Comment by braver** [comment]
Yes, the left part isn’t editable, that’s the defaults. You copy the value you want to edit to the right.

**Comment by sebastienbarre** [comment]
@jjbaca your previous SL3 settings were not backported. You can still find them in the package directory, the settings file was renamed. I used that, alongside the new SL4 settings, to back-port most of them.

**Comment by misterkek** [comment]
I have the same problem. Linter stopped working about 2 days ago. I reinstalled Sublime and Linter, then put my previous settings:

`{
    "user":
    {
        "debug": true,
        "delay": 0.25,
        "error_color": "D02000",
        "gutter_theme": "Packages/SublimeLinter/gutter-themes/Circle/Circle.gutter-theme",
        "gutter_theme_excludes":
        [
        ],
        "lint_mode": "background",
        "linters":
        {
            "csslint":
            {
                "@disable": false,
                "args":
                [
                ],
                "errors": "",
                "excludes":
                [
                ],
                "ignore": "",
                "warnings": ""
            },
            "hlint":
            {
                "@disable": false,
                "args":
                [
                ],
                "excludes":
                [
                ]
            },
            "htmltidy":
            {
                "@disable": false,
                "args":
                [
                ],
                "excludes":
                [
                ]
            },
            "jscs":
            {
                "@disable": false,
                "args":
                [
                ],
                "excludes":
                [
                ]
            },
            "jshint":
            {
                "@disable": false,
                "args":
                [
                ],
                "excludes":
                [
                ]
            },
            "jsl":
            {
                "@disable": false,
                "args":
                [
                ],
                "excludes":
                [
                ]
            },
            "php":
            {
                "@disable": false,
                "args":
                [
                ],
                "excludes":
                [
                ]
            },
            "phplint":
            {
                "@disable": false,
                "args":
                [
                ],
                "excludes":
                [
                ]
            }
        },
        "mark_style": "outline",
        "no_column_highlights_line": false,
        "passive_warnings": false,
        "paths":
        {
            "linux":
            [
            ],
            "osx":
            [
            ],
            "windows":
            [
            ]
        },
        "python_paths":
        {
            "linux":
            [
            ],
            "osx":
            [
            ],
            "windows":
            [
            ]
        },
        "rc_search_limit": 3,
        "shell_timeout": 10,
        "show_errors_on_save": false,
        "show_marks_in_minimap": true,
        "sublimelinter": true,
        "sublimelinter_executable_map":
        {
            "css": "node",
            "html": "F:\\programming\\tidy.exe",
            "php": "F:\\programming\\php\\php.exe"
        },
        "syntax_map":
        {
            "css": "css",
            "html (django)": "html",
            "html (rails)": "html",
            "html 5": "html",
            "js": "js",
            "php": "php",
            "python django": "python"
        },
        "tooltip_fontsize": "1rem",
        "tooltip_theme": "Packages/SublimeLinter/tooltip-themes/Default/Default.tooltip-theme",
        "tooltip_theme_excludes":
        [
        ],
        "tooltips": false,
        "use_current_shell_path": false,
        "warning_color": "DDB700",
        "wrap_find": true
    }
}
`

and Linter showed an error:
`SublimeLinter: ERROR:
Invalid settings in 'Packages/User/SublimeLinter.sublime-settings':
Additional properties are not allowed ('user' was unexpected)`.

Then I cut "user" and now I'm getting:
`SublimeLinter: ERROR:
Invalid settings in 'Packages/User/SublimeLinter.sublime-settings':
Additional properties are not allowed ('tooltips', 'passive_warnings', 'gutter_theme_excludes', 'sublimelinter', 'show_errors_on_save', 'tooltip_theme', 'warning_color', 'mark_style', 'sublimelinter_executable_map', 'error_color', 'tooltip_fontsize', 'rc_search_limit', 'wrap_find', 'python_paths', 'use_current_shell_path', 'tooltip_theme_excludes' were unexpected)`

I don't now what to do.

**Comment by braver** [comment]
The info is here, as noted in the message you got when the upgrade happened: https://github.com/SublimeLinter/SublimeLinter/blob/master/messages/4.0.0.txt

> How to upgrade
> -------------------------------
> 
> Your old settings will be backed up to SublimeLinter old.sublime-settings.
> You may want to compare them to the new default settings and check if you want
> to migrate anything.
> 
> To migrate your settings, first remove the "user" level and un-indent/flatten
> everything a level. Check the default settings to remove settings that don't
> exist anymore:
> 
> - mark_style
> - error_color
> - gutter_theme_excludes
> - passive_warnings
> - show_errors_on_save
> - tooltip_fontsize, tooltip_theme, tooltip_theme_excludes, tooltips
> - warning_color
> - wrap_find
> - python_paths
> 
> You can keep the "linters" settings block if it contains customizations that
> you need. It's also safe to remove it otherwise.
> Note that "@disable" is now "disable", without the "@".
> 
> If you use the ${project} settings token you should change that to ${folder}.

**Comment by misterkek** [comment]
@braver thanks, I missed this, sorry.

No I have this settings:
`{
        "debug": true,
        "gutter_theme": "Packages/SublimeLinter/gutter-themes/Circle/Circle.gutter-theme",
        "linters":
        {
            "csslint":
            {
                "disable": false,
                "args":
                [
                ],
                "errors": "",
                "excludes":
                [
                ],
                "ignore": "",
                "warnings": ""
            },
            "hlint":
            {
                "disable": false,
                "args":
                [
                ],
                "excludes":
                [
                ]
            },
            "htmltidy":
            {
                "htmltidy": {
                    "cmd": "F:\\programming\\tidy.exe"
                }
            },
            "jscs":
            {
                "disable": false,
                "args":
                [
                ],
                "excludes":
                [
                ]
            },
            "jshint":
            {
                "disable": false,
                "args":
                [
                ],
                "excludes":
                [
                ]
            },
            "jsl":
            {
                "disable": false,
                "args":
                [
                ],
                "excludes":
                [
                ]
            },
            "php":
            {
                "php": {
                    "cmd": "F:\\programming\\php\\php.exe"
                }
            },
            "phplint":
            {
                "disable": false,
                "args":
                [
                ],
                "excludes":
                [
                ]
            }
        }
}
`

Did I set everything right? Because it still does not work.
In fact, I did not quite understand where to insert the paths to the folders (tidy and php)

**Comment by misterkek** [comment]
Any ideas?

**Comment by kaste** [comment]
@misterkek You never showed the log after you fixed the settings.

**Comment by kaste** [comment]
Ah, `php` is a super old linter, in that case `php` must be "globally" available (if I read the linter plugin correct). Or you have to setup https://github.com/SublimeLinter/SublimeLinter/blob/master/docs/troubleshooting.rst#adding-to-the-paths-setting

We probably update this linter later.

**Comment by braver** [comment]
@misterkek your configuration is also broken here:

```json
"htmltidy":
            {
                "htmltidy": {
                    "cmd": "F:\\programming\\tidy.exe"
                }
            },
```

and here

```
"php":
            {
                "php": {
                    "cmd": "F:\\programming\\php\\php.exe"
                }
            },
```

**Comment by jjbaca** [comment]
Hey, sorry for disappearing. I stopped programming for a couple days. So, I just tried it again and it's still not showing errors. This is the message I got from the console:
DPI scale: 1
startup, version: 3143 linux x64 channel: stable
executable: /opt/sublime_text/sublime_text
working dir: /home/student
packages path: /home/student/.config/sublime-text-3/Packages
state path: /home/student/.config/sublime-text-3/Local
zip path: /opt/sublime_text/Packages
zip path: /home/student/.config/sublime-text-3/Installed Packages
ignored_packages: ["Vintage"]
pre session restore time: 0.166043
startup time: 0.230862
first paint time: 0.234573
reloading plugin Default.auto_indent_tag
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.install_package_control
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.quick_panel
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.settings
reloading plugin Default.show_scope_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin Default.ui
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin 0_package_control_loader.00-package_control
reloading plugin 0_package_control_loader.01-pygments
reloading plugin 0_package_control_loader.50-backrefs
reloading plugin 0_package_control_loader.50-markupsafe
reloading plugin 0_package_control_loader.50-pymdownx
reloading plugin 0_package_control_loader.50-python-markdown
reloading plugin 0_package_control_loader.50-pyyaml
reloading plugin 0_package_control_loader.51-python-jinja2
reloading plugin 0_package_control_loader.55-jsonschema
reloading plugin 0_package_control_loader.55-mdpopups
reloading plugin BracketHighlighter.bh_core
reloading plugin BracketHighlighter.bh_logging
reloading plugin BracketHighlighter.bh_plugin
reloading plugin BracketHighlighter.bh_popup
reloading plugin BracketHighlighter.bh_regions
reloading plugin BracketHighlighter.bh_remove
reloading plugin BracketHighlighter.bh_rules
reloading plugin BracketHighlighter.bh_search
reloading plugin BracketHighlighter.bh_swapping
reloading plugin BracketHighlighter.bh_wrapping
reloading plugin BracketHighlighter.support
reloading plugin Package Control.1_reloader
reloading plugin Package Control.2_bootstrap
reloading plugin Package Control.Package Control
reloading plugin SublimeLinter-clang.linter
reloading plugin SublimeLinter.__init__
reloading plugin SublimeLinter.busy_indicator_view
reloading plugin SublimeLinter.goto_commands
reloading plugin SublimeLinter.highlight_view
reloading plugin SublimeLinter.log_handler
reloading plugin SublimeLinter.message_view
reloading plugin SublimeLinter.panel_view
reloading plugin SublimeLinter.status_bar_view
reloading plugin SublimeLinter.sublime_linter
reloading plugin SublimeLinter.tooltips_view
reloading plugin TrailingSpaces.trailing_spaces
plugins loaded
SublimeLinter: SublimeLinter.sublime-package:71: Logging installed; log level INFO
SublimeLinter: SublimeLinter.sublime-package:62: debug mode: on
SublimeLinter: SublimeLinter.sublime-package:63: version: 4.1.0
SublimeLinter: SublimeLinter.sublime-package:292: detected syntax: c improved
SublimeLinter: #1 SublimeLinter.sublime-package:742: 'clang' is linting 'helper.c'
SublimeLinter: #1 SublimeLinter.sublime-package:103: PATH:
    /home/student/bin
    /home/student/.local/bin
    /usr/local/sbin
    /usr/local/bin
    /usr/sbin
    /usr/bin
    /sbin
    /bin
    /usr/games
    /usr/local/games
SublimeLinter: #1 SublimeLinter.sublime-package:1040: clang: helper.c ['/usr/bin/clang', '-fsyntax-only', '-fno-caret-diagnostics', '-Wall', '-x', 'c', '-']
SublimeLinter: #1 SublimeLinter.sublime-package:1043: clang: cwd: /home/student/Desktop/cse320/hw2-jjbaca/src
SublimeLinter: #1 SublimeLinter.sublime-package:769: clang output:
    <stdin>:1:10: fatal error: 'helper.h' file not found
Package Control: Skipping automatic upgrade, last run at 2018-03-14 13:03:43, next run at 2018-03-14 14:03:43 or after

**Comment by braver** [comment]
Any idea why the linter cannot find `helper.h`?

**Comment by jjbaca** [comment]
I think is because it is in another folder. helper.c is on "project/src", helper.h is on "project/include". I just use a Makefile

**Comment by jjbaca** [comment]
So, I uninstalled and reinstalled everything again. As you will see, the ".h" error is gone but, still no other error are shown. This the new message if the console:
DPI scale: 1
startup, version: 3143 linux x64 channel: stable
executable: /opt/sublime_text/sublime_text
working dir: /home/student
packages path: /home/student/.config/sublime-text-3/Packages
state path: /home/student/.config/sublime-text-3/Local
zip path: /opt/sublime_text/Packages
zip path: /home/student/.config/sublime-text-3/Installed Packages
ignored_packages: ["Vintage"]
pre session restore time: 0.088911
startup time: 0.157198
first paint time: 0.161355
reloading plugin Default.auto_indent_tag
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.install_package_control
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.quick_panel
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.settings
reloading plugin Default.show_scope_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin Default.ui
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin 0_package_control_loader.00-package_control
reloading plugin 0_package_control_loader.01-pygments
reloading plugin 0_package_control_loader.50-backrefs
reloading plugin 0_package_control_loader.50-markupsafe
reloading plugin 0_package_control_loader.50-pymdownx
reloading plugin 0_package_control_loader.50-python-markdown
reloading plugin 0_package_control_loader.50-pyyaml
reloading plugin 0_package_control_loader.51-python-jinja2
reloading plugin 0_package_control_loader.55-jsonschema
reloading plugin 0_package_control_loader.55-mdpopups
reloading plugin BracketHighlighter.bh_core
reloading plugin BracketHighlighter.bh_logging
reloading plugin BracketHighlighter.bh_plugin
reloading plugin BracketHighlighter.bh_popup
reloading plugin BracketHighlighter.bh_regions
reloading plugin BracketHighlighter.bh_remove
reloading plugin BracketHighlighter.bh_rules
reloading plugin BracketHighlighter.bh_search
reloading plugin BracketHighlighter.bh_swapping
reloading plugin BracketHighlighter.bh_wrapping
reloading plugin BracketHighlighter.support
reloading plugin Package Control.1_reloader
reloading plugin Package Control.2_bootstrap
reloading plugin Package Control.Package Control
reloading plugin SublimeLinter.__init__
reloading plugin SublimeLinter.busy_indicator_view
reloading plugin SublimeLinter.goto_commands
reloading plugin SublimeLinter.highlight_view
reloading plugin SublimeLinter.log_handler
reloading plugin SublimeLinter.message_view
reloading plugin SublimeLinter.panel_view
reloading plugin SublimeLinter.status_bar_view
reloading plugin SublimeLinter.sublime_linter
reloading plugin SublimeLinter.tooltips_view
plugins loaded
SublimeLinter: SublimeLinter.sublime-package:71: Logging installed; log level INFO
SublimeLinter: SublimeLinter.sublime-package:62: debug mode: on
SublimeLinter: SublimeLinter.sublime-package:63: version: 4.1.0
Package Control: Skipping automatic upgrade, last run at 2018-03-14 14:22:42, next run at 2018-03-14 15:22:42 or after

**Comment by braver** [comment]
What linters do you have installed?

**Comment by kaste** [comment]
Yeah, haha, you forgot to install the clang linter. For clang you also must setup the include_dirs setting.

**Comment by jjbaca** [comment]
Ok, I just installed the clang. Now, the missing file error is being shown again. However, that is not the issue I need to solve. I need to now how to make the linter fully functional again. Not just that error.

**Comment by braver** [comment]
> For clang you also must setup the include_dirs setting.

👆🏻

**Comment by jjbaca** [comment]
Can you please tell me how to do it?

**Comment by jjbaca** [comment]
I think I got it. I just copied and pasted, from the old users settings, into the "linters" in the new settings, the following:
"clang": {
                "@disable": false,
                "args": [],
                "excludes": [],
                "extra_flags": "-std=gnu11 -pedantic",
                "include_dirs": [
                    "../include",
                    "include/"
                ]
            }
So far, it is highlighting me the errors that I am expecting to. However, I want to give it a couple more tests and I will let you know...
If you have more suggestions, please let me know.
Thank you.

**Comment by braver** [comment]
That looks good. You can remove the `@` from `@disable` though, that's the old format. The other stuff is mostly as it was. You can probably make the `include_dirs` a bit smarter using [settings expansion](https://github.com/SublimeLinter/SublimeLinter/blob/master/docs/settings.rst#settings-expansion), but that would take some experimentation and I know nothing about it honestly.

**Comment by jjbaca** [comment]
I just removed the @. It seems entertaining but, I don't think I'm gonna play with the settings. I am gonna stick to the way I have it now.
Thanks again.

**Comment by jjbaca** [comment]
So, the linter it not giving me any more issues. It's responding perfectly. I guess you guys can close the issue now and, if I have any more problems, I will open another issue.
Thank you very much for your help.
