### ISSUE TITLE
AttributeError: 'module' object has no attribute 'debounce'

### ISSUE THREAD

**Issue by DanielSmedegaardBuus** [SublimeLinter/SublimeLinter#1083]
Hi :)

Okay, so it seems today SL was upgraded to v4 — at least today I got a popup saying that my preferences file had been moved to `(old)` and so on. I remembered the warning earlier that a new major version of SL was coming up, so I went here and followed the guide to port my old settings to the new SL 4. 

Unfortunately, I've been unable to get SL 4 to lint anything. It's just nothing happening. Don't know if it's an incompatibility thing with eslinter or something, but I've already spent too much of my work hours on it, so I decided to just use the 3.10.10 package offered here and block updates to SublimeLinter in Package Control. 

I had rsync'ed my Sublime folder before fiddling around, so I reverted to the backup and extracted the 3.10.10 tar.gz to Packages/SublimeLinter. After a restart, I'm now even worse off, getting an error like this in the console every time SL tries to lint:

```
AttributeError: 'module' object has no attribute 'debounce'
Traceback (most recent call last):
  File "/Users/daniel/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 521, in on_selection_modified_async
    callback.on_selection_modified_async(v)
  File "highlight_view in /Users/daniel/Dropbox/Home/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 160, in on_selection_modified_async
```

Any ideas?

Thanks :)

**Comment by DanielSmedegaardBuus** [comment]
Ok, I live very close to work, so I simply went home and made a copy of the Sublime folder I had there, and everything works fine now with the V3 version that was not yet updated there :)

Feel free to delete this thread if you deem it to be irrelevant or some random fluke (which may very well be the case). I'm leaving it here, closed, in case it's of interest to you 👍 

Cheers!

**Comment by FichteFoll** [comment]
If you end up trying v4 on your home machine, please include a debug log when it does not work.

**Comment by braver** [comment]
Yeah, I'm gonna say random fluke until we have more evidence 😉

**Comment by kaste** [comment]
You probably needed another restart here. If a module does not contain a member (here the function `debounce`), reloading the module after update failed.

**Comment by DanielSmedegaardBuus** [comment]
Hey, sorry for not responding till now :) I'm just really busy getting an API to full test coverage before this afternoon, so I haven't had time to try to get V4 to work on my puters. 

I sync my Sublime folders in the cloud, so my home puter was exhibiting the exact same issues. AFAICT, only JS linting via eslint was broken — e.g. JSON linting worked fine. One thing, though. After restoring from a backup and then blocking SL updates in package control, everything worked fine until the SL-eslint package upgraded as well. Restored that, blocked it as well, then again back to fine.

Perhaps it was just SL upgrading to V4 and being incompatible with an old SL-eslint package? And now that both are available in updated form, perhaps it's perfectly fine to upgrade... Hmmm... I should have time to try that right now, hang on...

**Comment by DanielSmedegaardBuus** [comment]
Yeah, okay, it now fails to update with,

```
unloading plugin SublimeLinter.commands
unloading plugin SublimeLinter.sublimelinter
reloading settings Packages/SublimeLinter/SublimeLinter.sublime-settings
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
Package Control: The dependency 'jsonschema' is not currently installed; installing...
Package Control: The dependency 'jsonschema' is not available
Package Control: The dependency 'jsonschema' could not be installed or updated
ignored packages updated to: ["Material Theme", "Vintage"]
reloading plugin SublimeLinter.commands
reloading plugin SublimeLinter.sublimelinter
SublimeLinter: debug mode: on 
SublimeLinter: temp directory: /var/folders/zn/5hmmrpp15_s9c7kvyrzd7p240000gn/T/SublimeLinter3-daniel 
reloading settings Packages/SublimeLinter/SublimeLinter.sublime-settings
SublimeLinter: daemon detected a reload 
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
```

After this, it remains at v3, but with SL-eslint at v4.

I'll have to try this again later when I have more time :)

Cheers!

**Comment by DanielSmedegaardBuus** [comment]
And now I had more time, and this time it finally succeeded :D 

It initially spewed a ton of python errors and something about eslint being disabled due to tooltip-something not being implemented, but it did, for the first time, present update messages about both SL4 and SL-eslint4, and after a restart, JS linting now works :)
