### ISSUE TITLE
Show the output panel on-save if there are errors.

### ISSUE THREAD

**Issue by minitauros** [SublimeLinter/SublimeLinter#1084]
Since the upgrade to 4, there isn't a tooltip any more that screams in my face that my code contains errors when I save a file that contains errors. This used to be the most useful feature to me in Sublimelinter. Is there any way to get it back? Maybe I've just not set the right settings?

**Comment by braver** [comment]
Nope, that thing is gone. I can recommend pre-commit hooks. But if more people want the nag screen, perhaps we need something like that.

**Comment by kaste** [comment]
Probably a toast message. 😄

**Comment by minitauros** [comment]
I loved the nag screen! Maybe an option to switch it on/off could be implemented for those people that like a in-your-face style notification? :no_mouth:

**Comment by kaste** [comment]
@braver I actually needed this feat always, but I never liked the blocking thingy from SL3. So, I rolled my own. But without a ('THERE ARE STILL ERRORS') friendly message... I'm lost

**Comment by braver** [comment]
Ok, cool. We can do an output panel? Or expose an api so people can roll their own, and we can publish a plugin (e.g. with the toast thing).

**Comment by FichteFoll** [comment]
An option to open the panel when there are errors on save?

**Comment by braver** [comment]
Oh, yeah, sure, we should just open the existing panel, if it isn't empty. And with a setting obviously.

**Comment by FichteFoll** [comment]
Only show if if there are errors *for the saved file*, however. There might be errors shown in the panel but not for the current view.

**Comment by braver** [comment]
Perhaps that could be configurable too, if you want to be error-free for all files you touched you may want to keep that panel empty.

**Comment by gillibrand** [comment]
Yup, I really want to see errors on save too.

**Comment by clementprevot** [comment]
I really loved this nag-screen every time I save my file. I think that the "Open the panel if not empty for the current view" thing would be pretty nice. Ideally, it should also be able to ignore (or not, depending on a setting like "make warning passive") the warning and only consider errors.

If you could make it happen it would be great :+1:

**Comment by albanh** [comment]
+1 for getting this feature added back in some way, it was really useful.

**Comment by jprada014** [comment]
As I stated in #1150, this can be emulated (as a workaround) by using the plugin _SublimeOnSaveBuild_ after configuring a _Build System_ for your language.

Then, set the ST preferences with:

```
"show_panel_on_build": false,
"show_errors_inline": true
```

But I preferred SublimeLinter's "show_errors_on_save" one, as _SublimeOnSaveBuild_ need an additional menu command action to remove the error message after save or fixing the error and then saving again to remove the tool tip that messes with the format.

Also you have to press ESC to close the panel, even when there is not an error on build/save.

**Comment by pnlarsson** [comment]
+1 Really missing sublime telling me of the errors I make

**Comment by braver** [comment]
Don't "plus one" this or any other issue or I'll lock it. If the issue is open that means we're probably going to do something about it. Plus-ones will just distract us and postpone the feature.

**Comment by FichteFoll** [comment]
You can also always post a reaction to the issue itself to show your support of an issue.

**Comment by braver** [comment]
If anyone is interested in this, here is a PR you can try: #1172
