### ISSUE TITLE
Remove: Intent to remove 'versioning' feature

### ISSUE THREAD

**Issue by kaste** [SublimeLinter/SublimeLinter#1087]
The version check feature is mostly unused and confuses people. Note that all sub linters like NodeLinter, PythonLinter et.al. do not implement it. (But of course, plugin authors still provide the versioning attributes without knowing that they don't do anything.)

Currently 'versioning' was a simple 'on-off' check. This is not very useful.

**Comment by braver** [comment]
👍

**Comment by FichteFoll** [comment]
I seem to remember the version check being implemented (or working, rather) for PythonLinter, but I could be imagining. I do specify a minimum version requirement for mypy at least, but the last incompatible version is more than a year old.

I don't know how the current implementation behaves exactly, but have you considered whether it's worth to fix this feature instead?

**Comment by braver** [comment]
Well, it's feature that nobody uses but it's there in the README's. If a plugin ever used that, probably the last time anyone looked at the version numbers is at least 3 years ago. If it for some reason becomes useful, we can look at it again then with an actual use case and implement it anew and better.

**Comment by kaste** [comment]
I said in the description that this was never implemented for our subclasses namely PythonLinter et.al. It confuses people bc they declare it anyway.

**Comment by FichteFoll** [comment]
>If it for some reason becomes useful, we can look at it again then with an actual use case and implement it anew and better.

I can agree with that. If it's not implemented at all currently, nobody is going to miss it either.

`mypy` is the only linter plugin I maintain and nobody complained there so far. I'll create a new issue to implement the feature anew, if it does come up in the future.
