### ISSUE TITLE
Remove element from status bar

### ISSUE THREAD

**Issue by slifin** [SublimeLinter/SublimeLinter#1090]
I could be wrong but I think sublimelinter 4 has added this section to the status bar
<img width="102" alt="screen shot 2018-03-05 at 11 30 40" src="https://user-images.githubusercontent.com/198857/36972855-ab7b6d4e-2068-11e8-8e82-11c72138086b.png">
Is there a setting I can use to delete or modify this section? 

I've tried navigating to here: http://www.sublimelinter.com/en/latest/mark_styles.html#status-bar-info via the documentation but there's a 404 there

**Comment by braver** [comment]
Check #1081
