### ISSUE TITLE
Installation docs are missing

### ISSUE THREAD

**Issue by gorgos** [SublimeLinter/SublimeLinter#1091]
Hello, I can't find any docs for the installation. Is this because of the upgrade to version 4?

http://www.sublimelinter.com/en/latest/installation.html

There are also no docs in the repository here for the installation.

**Comment by braver** [comment]
What links to that URL exactly?

You install SublimeLinter via package control, it has no other installation steps. The linter plugins require more effort, but they all have a readme telling you what to do.

**Comment by gorgos** [comment]
https://github.com/alexstep/SublimeLinter-contrib-solium was linking to it, but you also see the 'Installation' link in Google.
<img width="601" alt="screen shot 2018-03-05 at 16 40 06" src="https://user-images.githubusercontent.com/659390/36983927-f5ea1c88-2093-11e8-81b7-976bdf1d2135.png">

**Comment by braver** [comment]
Oh, yeah, probably some more third party plugins that link to that page. There used to be documentation telling you how to use package control, but nowadays we think that's a given (and package control has its own docs anyway).
