### ISSUE TITLE
Warning/error colours have changed

### ISSUE THREAD

**Issue by slifin** [SublimeLinter/SublimeLinter#1092]
Before SublimeLinter 4, with plugin for the phantom
![image](https://user-images.githubusercontent.com/198857/36977648-c85eea1a-2079-11e8-8892-d7871cebecfd.png)

After SublimeLinter 4
<img width="313" alt="screen shot 2018-03-05 at 13 34 33" src="https://user-images.githubusercontent.com/198857/36977701-f6a91f6c-2079-11e8-9deb-b213762a12ab.png">

Is there a way to get the bright red back?

**Comment by braver** [comment]
I have some notes about that here: https://github.com/SublimeLinter/SublimeLinter/issues/1074

Full docs are coming soon.
