### ISSUE TITLE
How to disable tooltip

### ISSUE THREAD

**Issue by slifin** [SublimeLinter/SublimeLinter#1093]
<img width="1399" alt="screen shot 2018-03-05 at 13 35 16" src="https://user-images.githubusercontent.com/198857/36977733-1334647a-207a-11e8-84c8-f4e5234f3223.png">

Is there a way to disable the new tooltip?

**Comment by braver** [comment]
There are 2 settings: `show_hover_line_report` and `show_hover_region_report`. The default settings (on the left if you open your settings) have documentation about this.
