### ISSUE TITLE
Version 4 AttributeError for PHP -l

### ISSUE THREAD

**Issue by jrlooney** [SublimeLinter/SublimeLinter#1096]
new version installed. I created a new User settings based on defaults. Only linter installed is 'SublimeLinter-php'.  Created some obvious errors in a .php but linter does not highlight them. Console shows this:

> SublimeLinter: #7 SublimeLinter.sublime-package:782: 'php' is linting 'uc.datecheck.php'
> SublimeLinter: #7 SublimeLinter.sublime-package:1178: php: uc.datecheck.php ['/usr/bin/php', '-l', '-n', '-d', 'display_errors=On', '-d', 'log_errors=Off']
> SublimeLinter: #7 SublimeLinter.sublime-package:1181: php: cwd: /Users/jameslooney/Desktop/vm/jim
> SublimeLinter: #7 SublimeLinter.sublime-package:809: php output:
> 
>     Parse error: syntax error, unexpected '$DateVal' (T_VARIABLE) in - on line 13
>     Errors parsing -
> SublimeLinter: #7 SublimeLinter.sublime-package:850: php: No match for line: ''
> SublimeLinter: #7 SublimeLinter.sublime-package:850: php: No match for line: 'Errors parsing -'
> Traceback (most recent call last):
>   File "lint.events in /Users/jameslooney/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 28, in broadcast
>   File "highlight_view in /Users/jameslooney/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 91, in on_lint_result
>   File "highlight_view in /Users/jameslooney/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 308, in prepare_highlights_data
>   File "highlight_view in /Users/jameslooney/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 350, in get_scope
>   File "lint.style in /Users/jameslooney/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 54, in wrapper
>   File "lint.style in /Users/jameslooney/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 97, in get_val
> AttributeError: 'NoneType' object has no attribute 'split'

**Comment by jrlooney** [comment]
disregard. restarting "fixed" it.

**Comment by braver** [comment]
🎉
