### ISSUE TITLE
globally enable/disable linting with a command

### ISSUE THREAD

**Issue by a-dpq** [SublimeLinter/SublimeLinter#1101]
Today when I launched Sublime I got an error that said SublimeLinter couldn't read my user settings for the plugin. I've since uninstalled and reinstalled the plugin, and I noticed that the SublimeLinter menu (which used to be located in the Tools menu) has disappeared. It seems there's no way to toggle individual linters anymore.

How can I fix this? After reading through some of the recent issues here, it seems that many people are having problems after an upgrade.

**Comment by FichteFoll** [comment]
You should read the update message, if you haven't already.

https://github.com/SublimeLinter/SublimeLinter/blob/master/messages/4.0.0.txt

**Comment by a-dpq** [comment]
Thanks for the pointer. From the upgrade message:

> Commands to change settings or toggle linters have been removed.
> - Settings can be changed by modifying your user settings.
> - Linters may be disabled in the user settings,
>   or in your project configuration.

Do I understand correctly that the only way to toggle linters now is by editing the user settings? This seems like a step backward in terms of usability. I frequently toggle individual linters on and off when necessary.

I've also tried to edit the user settings for the highlight style, but it doesn't seem to have any effect.

**Comment by a-dpq** [comment]
I toggle linters dozens of times a day. There are situations when I just want to code without seeing errors pop up and disappear as I type, which I find distracting. Then I'll lint it later on, when I want to see the errors highlighted. It was really helpful to have a keyboard command to quickly toggle linters.

The highlight style issue has resolved itself after a few restarts now, by the way.

**Comment by FichteFoll** [comment]
Would disabling linters for a single file help your workflow? If yes, that would be the goal of #98.

**Comment by a-dpq** [comment]
I'd like to be able to toggle them globally (as was possible before the update), since I typically work across several files at once. My workflow for a project looks like this:

1. Create new code without worrying about minor errors (keep linters off)
2. Refine existing code (turn linters on)

**Comment by kaste** [comment]
Hm, is there a command you can send to PackageControl to disable/enable SublimeLinter? So we can assign a keyboard shortcut to it.

**Comment by FichteFoll** [comment]
You can just add your package to `ignored_packages` directly, but you can't remove it again because the package will get unloaded (duh).

**Comment by a-dpq** [comment]
A keyboard command would be really nice.

**Comment by mhkeller** [comment]
I agree with @a-dpq. Sometimes I'm working on a collaborative project that has an `.eslintrc` file, sometimes I'm doing a one-off script that I want to be linted but don't want to create an `.eslintrc` so I use the built-in `-contrib-standard` linting. Other times I want to disable everything to write pseudo-code or something quick. The "enable/disable linting" and "enable/disable linter" commands in the command palette were very useful for this.

**Comment by braver** [comment]
Yeah, I'm already totally convinced we need this. Now we just need someone to write a PR 😉 

Possible direction:

- disable SL in package control
- remove our views (e.g. highlights, statusbar, etc) when SL unloads (that's a good idea anyway)

We could make a command that immediately disables SL, but we can't make a command to bring it back. So, if we do it by disabling the package, we should just do #1148 and not make commands. That also means you don't get keybindings.

We could make a little plugin that provides the toggle, but having to install another package for that purpose sounds inelegant to me. 

The other direction would be to create a killswitch that basically toggles SL but keeps it loaded.

**Comment by kaste** [comment]
Closed now in #1149

**Comment by braver** [comment]
👍🏻
