### ISSUE TITLE
Add "How to upgrade" section to the docs

### ISSUE THREAD

**Issue by FichteFoll** [SublimeLinter/SublimeLinter#1102]
There should be a section on the upgrade process from 3 to 4 in the docs on the website, imho. This is usually the first place you'd look at.

**Comment by FichteFoll** [comment]
Also, there are currently no docs for plugin developers about all the things that have changed, such as attributes and inline settings being removed, the "selectors" change, etc.

**Comment by billinghamj** [comment]
There is also a list of no-longer-supported configuration parameters, but absolutely no information whatsoever about how to replicate the equivalent config using the new style thing.

Honestly this seems like a bit of a disaster. Why would such a major change be released with zero explanation of why anything has been changed, how to adapt to it, etc.

**Comment by ryami333** [comment]
Agreed, this is catastrophic to the point that I've abandoned Sublime altogether and I'll review in a couple of weeks when everything has normalized again.

**Comment by billinghamj** [comment]
If anyone is trying to figure out how to deal with rendering options, I found this comment from the default config to be somewhat helpful:

```
    // Global styles for all linters.
    // - mark_style options:
    //   "fill", "outline",
    //   "solid_underline", "squiggly_underline", "stippled_underline"
    //   "none"
    // - priority determines which mark is show in the gutter;
    //   error marks will still always overwrite warning marks.
    // - scope is used to determine the color;
    //   region.<colorish> are automatically generated scopes in ST > 3148.
    // - types is an array which can contain "warning" and/or "error".
    // - codes is an array which can contain error codes provided by a linter.
    // - icon can be:
    //   one of the default icons: "circle", "dot" or "bookmark"
    //   or a path to an icon file like (e.g. "Packages/icons/warning.png")
    //   or "none" to remove the icon
    //   or one provided by a gutter theme (e.g. "warning" or "error")
    //      in theme Default: "warning", "error", "cog", "x",
    //      and "diamond", "heart", "pointer", "square", "star", "triangle" all
    //      also have an -outline variant.
    // Note: At least one of those targets is required: types or codes.
    // Styles can also be specified per linter.
```

Unfortunately, colours remain entirely unknown. Despite many issues referring to it, none provide any clear instructions or explanation.

**Comment by billinghamj** [comment]
I have found that removing `region.redish` and `markup.error.sublime_linter` from the scope, leaving it with just `markup.deleted.sublime_linter` did result in red blocks. Unfortunately, doing the same for warnings resulted in purple blocks :|

**Comment by billinghamj** [comment]
`comment region.yellowish` seems to produce a somewhat-tolerable style for warning blocks

**Comment by billinghamj** [comment]
As far as I can tell, there is no replacement for any of these:

- `passive_warnings`
- `rc_search_limit`
- `show_errors_on_save`
- `use_current_shell_path`
- `wrap_find`

😑

**Comment by billinghamj** [comment]
It also appears as though all SL3 docs have been removed completely from https://sublimelinter.readthedocs.io/ - all links on Google have 404'd

**Comment by braver** [comment]
I’ll add something more detailed to the docs about what disappeared and why, and what’s new.

**Comment by billinghamj** [comment]
@braver Much appreciated 👍

**Comment by braver** [comment]
FYI, docs for v3 are now available too.

**Comment by billinghamj** [comment]
For anyone who needs the link: http://www.sublimelinter.com/en/v3.10.10/

**Comment by braver** [comment]
For more background on some changes:

https://forum.sublimetext.com/t/sublimelinter-4-beta/34022/37?u=braver


> Also, there are currently no docs for plugin developers about all the things that have changed, such as attributes and inline settings being removed, the "selectors" change, etc.

All current plugin authors have been notified about the deprecations, and plugins in the org have already been updated for them. The "selectors" change is optional for now which buys us time to test it and eventually upgrade the plugins. Nothing needs to happen with old plugins, and all of this is documented for new plugins. 

> This is usually the first place you'd look at.

People have a really hard time finding that one actually. It is pretty visible in the readme though.
