### ISSUE TITLE
'excludes' was unexpected

### ISSUE THREAD

**Issue by nolde** [SublimeLinter/SublimeLinter#1104]
Using v4.0.2, I am now getting this message out of the blue:
```
SublimeLinter: ERROR:

 Invalid settings in 'Packages/User/SublimeLinter.sublime-settings':
Additional properties are not allowed ('excludes' was unexpected)
```
My user config looks like this:
```json
// SublimeLinter Settings - User
{
	"excludes": ["*.test.js"]
}
```

It started happening after a strange message told me it couldn't access my sublime linter config. I restarted ST3, and the error message above started to show up.

I removed all SublimeLinter linters and SublimeLinter itself, reinstalled, restarted ST3, and still get the same issue.

I am on Windows 10, ST3 build 3143.

**Comment by kaste** [comment]
This setting must go in a linter section e.g. eslint

**Comment by nolde** [comment]
You are correct. The problem was only the sudden vanishing of the config file.

**Comment by FichteFoll** [comment]
Your old user settings file has been renamed. It's still located in the User package.
