### ISSUE TITLE
Copy the warning text to clipboard from the hover phantom

### ISSUE THREAD

**Issue by evandrocoan** [SublimeLinter/SublimeLinter#1113]
I was trying to copy the warning, but I cannot select the text on the phanthom. 

![image](https://user-images.githubusercontent.com/5332158/37010824-1e0b0d16-20cc-11e8-8fb4-61bbbc1719cd.png)

What would be required to allow me to select the text?

**Comment by braver** [comment]
We would need to introduce a “copy” button in the popup, the text in these things isn’t interactive.

**Comment by nvtkaszpir** [comment]
@evandrocoan as a workaround you can open SublimeLinter Show All Errors from command menu, and then you should be able to copy it.

**Comment by braver** [comment]
Yeah let’s go with that, a “copy” button in the popup doesn’t make a whole lot of sense.
