### ISSUE TITLE
Linter does not show phantom if the cursor is not on the current line

### ISSUE THREAD

**Issue by evandrocoan** [SublimeLinter/SublimeLinter#1115]
![back3](https://user-images.githubusercontent.com/5332158/37011364-87c77be8-20ce-11e8-9fb7-a9c034ad09d5.gif)

1. Debug https://gist.github.com/evandrocoan/263843916891ce188dde4c22883c34c4

**Comment by FichteFoll** [comment]
FWIW, that's a popup.

**Comment by braver** [comment]
AKA thingamajig
