### ISSUE TITLE
SublimeLinter 4.0.3 only shows E / W in a white text area, not in the actual files

### ISSUE THREAD

**Issue by Shelagh-Lewins** [SublimeLinter/SublimeLinter#1120]
SL 4.0.1 was kind of working, it randomly kept telling me it couldn't find the config file even though I had not opened or closed any files and it had been OK a minute before, so I kept having to close Sublime Text and reopen it (when curiously it did find its config file). But this morning it has upgraded to 4.0.3 and it is even more broken.

Instead of seeing linting errors and warnings in the file, I'm seeing a large white error text area at the bottom of the screen which contains both error messages for my files and deprecation warnings for my .eslintrc file.

1. How can I get the linter working again?

2. What am I supposed to do about the deprecated features?

**Comment by FichteFoll** [comment]
What's the exact text that is being shown?

**Comment by Shelagh-Lewins** [comment]
The message starts with this:

`[{"filePath":"/home/folder/file.jsx","messages":[{"ruleId":"no-unused-vars","severity":2,"message":"'toastr' is defined but never used."`

Then there is the entire content of my .jsx file, and finally this:

`(node:12812) DeprecationWarning: [eslint] The 'ecmaFeatures' config file property is deprecated, and has no effect. (found in /home/folder/path/.eslintrc)`

**Comment by Shelagh-Lewins** [comment]
Thanks to another thread I have resolved the problem with eslint and sublimeLinter; I needed to edit my .eslintrc file to remove the deprecated properties. So now I'm back using the newer version installed via Package Control, which is the better place to be. Thank you for your help.

**Comment by Shelagh-Lewins** [comment]
Note that the fact the message says the deprecated property *has no effect* made me assume it had no effect, i.e. was not the problem.

**Comment by braver** [comment]
Oh, aha. That "no effect" isn't our message, that comes from eslint itself and it could probably be phrased more clearly. So, if I'm right you're up and running now. If not, let me know.
