### ISSUE TITLE
Sometimes throws an error after uninstall about panel-syntax

### ISSUE THREAD

**Issue by Shelagh-Lewins** [SublimeLinter/SublimeLinter#1122]
I am trying to remove SublimeLinter 4.0.3 which installed itself this morning and see if I can figure out how to reinstall the old version 3 so I can do some work.

But when I selected Package Control > remove package > SublimeLint 4.0.3 I saw an error popup:

`Error loading syntax file "Packages/SublimeLinter/panel/panel.sublime-syntax": Unable to read Packages/SublimeLinter/panel/panel.sublime-syntax`

I also noticed that there was a second package SublimeLinter-eslint in Package Control, listed as v 4.0.1. Is there some conflict between the recent and latest versions?

**Comment by FichteFoll** [comment]
@braver I think destroying the panel when plugins are unloaded might just be enough to get rid of that message.

**Comment by braver** [comment]
Ok, that's worth a try.

**Comment by kaste** [comment]
We do this https://github.com/SublimeLinter/SublimeLinter/pull/1025

**Comment by FichteFoll** [comment]
So the problem would be that ST unloads the syntax definition before running plugins? That's quite unfortunate and should be reported upstream.

**Comment by braver** [comment]
@FichteFoll didn't you already report something along those lines?

**Comment by FichteFoll** [comment]
I reported something for Package Control, but that's only for mitigating the issue, and not in a clean way. Ideally, ST itself would just unload plugins first before it unloads other resource files that might have been in use before the plugins' unload handlers removed the references.

**Comment by kaste** [comment]
We just put the '.sublime-syntax' in the root dir and 🎉 🎆 ?

**Comment by FichteFoll** [comment]
You mean `Packages/SL_panel.sublime-syntax`?

Interesting idea, but I'd copy the file to `sublime.cache_path() / "SublimeLinter" / "panel.sublime-syntax"` instead.

**Comment by Cooperdale** [comment]
As you can see in the above reference, I am having this error after upgrading. It all worked initially, then it started doing this and the plugin doesn't seem to work anymore.

**Comment by kaste** [comment]
We still need full console logs when this happens!

**Comment by Cooperdale** [comment]
Actually I'm getting different errors each time I start Sublime, now that particular error seems to be gone, but for instance I got this:
`SublimeLinter:` #1 csslint stylesheet.css ERROR:
 Linter crashed.`

**Comment by kaste** [comment]
csslint is broken https://github.com/SublimeLinter/SublimeLinter/issues/1151

**Comment by ErikSwan** [comment]
Just got this error on Linux, full console log below. I've replaced some sensitive directory paths with `[redacted]`:

[sublime_console_log.txt](https://github.com/SublimeLinter/SublimeLinter/files/1808950/sublime_console_log.txt)

**Comment by kaste** [comment]
@ErikSwan Thanks for the log.

**Comment by ErikSwan** [comment]
Here's another one, this time on the Windows side. It seems like this error happens whenever SublimeLinter gets upgraded via Package Control.
[sublime_console_log_windows.txt](https://github.com/SublimeLinter/SublimeLinter/files/1826457/sublime_console_log_windows.txt)

**Comment by kaste** [comment]
We shipped a proposed fix with 4.1. Since this is throwing on unload/uninstall we have to wait for updates from 4.1 to a later version.

**Comment by braver** [comment]
Seems to be better now.
