### ISSUE TITLE
How to install v 3.10.10?

### ISSUE THREAD

**Issue by Shelagh-Lewins** [SublimeLinter/SublimeLinter#1123]
I'd like to install the old version 3.10.10 as recommended here:

https://github.com/SublimeLinter/SublimeLinter/releases/tag/v3.10.10

But there are no instructions and I can't get it working.

I've extracted the package to user/.config/sublime-text-3/packages
I've restored my old .eslintrc config file
I've restarted Sublime Text 3.

No linting :(

Anybody have any idea what else I need to do? Thank you!

**Comment by DanielKoehler** [comment]
Check the console output on startup ( ctrl+` shortcut or the View > Show Console menu ). 

If you have an import error, check that you copied it to `[...]/packages/SublimeLinter` not `[...]/packages/SublimeLinter-3.10.10`

**Comment by braver** [comment]
Indeed, you need to extract to `Package/SublimeLinter`

**Comment by Shelagh-Lewins** [comment]
@braver, thank you - you are exactly right, I renamed the folder to Packages/SublimeLinter and now my .scss files are being correctly linted.

SublimeLinter-eslint is not working however, and in the console I see this:

reloading plugin SublimeLinter-eslint.linter
SublimeLinter: ERROR: eslint disabled, not fully implemented 

I have SublimeLinter-eslint v4.0.1

**Comment by Shelagh-Lewins** [comment]
Thanks to another thread I have resolved the problem with eslint and sublimeLinter; I needed to edit my .eslintrc file to remove the deprecated properties. So now I'm back using the newer version installed via Package Control, and everything seems to be working as it should. Thank you for your help.

**Comment by braver** [comment]
Awesome, thank you for your patience in figuring it all out.

**Comment by Shelagh-Lewins** [comment]
Thank you for your help! These linters are awesome tools, they really help me out.
