### ISSUE TITLE
SublimeLinter does not update properly

### ISSUE THREAD

**Issue by markusdd** [SublimeLinter/SublimeLinter#1124]
As another issue I've seen that only reinstalling and manually cleaning up old stuff gets SublimeLinter running again after update to 4.0:

- old patched SublimeLinter themes files are still lying around
- Linter settings in JSON format did break for flake8, I had to convert everything to the "args" method
- some colleagues received several errors that 'Default' Gutter Theme was unavailable
- User settings broke because the "user" section was removed
- New depenedencies were installed when reinstalling SublimeLinter, the update seems to miss something

The only way I could properly fix it was to remove and reinstall sublimelinter and then completely redo the config file in some cases. Build 3143 for Sublime.

There should be a mechanism that cleans up these issues during upgrade, this caused a lot of headache during the last days as we have a large Userbase of SublimeLinter. (Nevertheless: thanks for the great tool, it is a vital part of our quality assurance)

**Comment by braver** [comment]
> then completely redo the config file in some cases

Yes, that's the only way. We tried to migrate user settings, but there were too many corner cases to make that work reliably. Also, SL3 just dumped all settings into the user settings and there is no need for that anymore. This is an opportunity to have only the settings you need to change from the defaults, which will help us move forwards. 

SL3 did a number of other things that make a mess of the user environment, like creating color schemes etc. There is no good way to automatically clean up after SL3 without making more of a mess of it. It's never a good idea to just blindly remove files from user space, let alone change settings etc. 

So, yeah, sadly some manual labor is involved but it had to happen. Much of this is [documented](https://github.com/SublimeLinter/SublimeLinter/blob/master/messages/4.0.0.txt), but a lot of it is also very situational and users kinda have to figure some stuff out by themselves.

> New depenedencies were installed when reinstalling SublimeLinter, the update seems to miss something

Yeah, one restart is sometimes not enough. SublimeLinter and PackageControl do their best, but it's sometimes a bit rough.

**Comment by markusdd** [comment]
ok, just to make a recipe to get everyone back up running:

1) remove User/SublimeLinter themes
2) reinstall sublimeLinter and restart Sublime Text to fix up dependencies
3) clean user config file and provide a new 'sane default' to the people from where they can customize
4) redo project configs for flake 8

Do you think this will cover most cases?

**Comment by braver** [comment]
Do mind that you need to switch your users to a different color scheme **before** you remove the `User/SublimeLinter` folder. Their user settings will point to the `<something> (SL)` color scheme and it will make ST really hard to work with if you remove the (SL) color scheme before setting it to something else.

**Comment by markusdd** [comment]
yep that is understood.
Now we just need to get that annoying gutter icon behavior resolved and I think we're back up and running.

**Comment by braver** [comment]
Ok, I'm closing this one but ping me if there are issues I can help with. The icon thing is over at #1121
