### ISSUE TITLE
baffled

### ISSUE THREAD

**Issue by Stockton-pr** [SublimeLinter/SublimeLinter#1127]
spent 3 hours reading docs and issues but cannot understand why SL(4) refuses to find per project eslint in node_modules/.bin/eslint?
is this designed in for some reason? even explicitly setting the path in *.sublime-project makes no difference- not being able to use eslint on a per project basis makes sublime text unusable versus for eg Atom. I respect your ambition and work but I am lost on this one.

**Comment by FichteFoll** [comment]
You said you have a ST project for your ... js project and want to use the local `eslint` executable, correct? This should be supported, so there's probably something with your setup.

Please provide a debug log after you attempted to lint a file in your project. http://www.sublimelinter.com/en/latest/troubleshooting.html

**Comment by Stockton-pr** [comment]
thanks for your interst mate i flipped out and deleted everything but essentially i copied the path code from settings into sublime.project and wrote the apth out in full to home/me/project/node_modules/.bin/eslint, i.e exactly waht would work from the CL. pointers welcome - or if you acn link to a config that works i would be grateful!

**Comment by braver** [comment]
Not 100% what your setup looks like now, but if you configure the path you leave out the executable itself.

**Comment by kaste** [comment]
eslint plugin generally finds the package.json and then uses the locally installed eslint

**Comment by Stockton-pr** [comment]
generally?Yes this would be my version of the expected behaviour but  I just get WARNING: eslint cannot locate 'eslint' on 3 projects all with eslint installed --save-dev to the project and available to the CL remaining baffled but open to a solution

**Comment by Stockton-pr** [comment]
SublimeLinter: #3 SublimeLinter.sublime-package:103: PATH:
    /opt/sublime_text/home/ps/.npm-packages/bin
    /usr/local/bin
    /usr/bin
    /bin
    /usr/local/games
    /usr/games
SublimeLinter: WARNING: eslint cannot locate 'eslint' 

After I installed globally and updated settings > paths

// Provide extra paths to be searched when locating system executables.
    "paths": {
        "linux": ["home/ps/.npm-packages/bin/"],
        "osx": [],
        "windows": []
    },

What a carry-on! this plugin has a mind of its own am closing b/c manymore yaks to shave. Atom is zero config thanks anyway.
