### ISSUE TITLE
Show lint errors in sublime console

### ISSUE THREAD

**Issue by andrewmiroshnichenko** [SublimeLinter/SublimeLinter#1128]
From some time (I believe after upgrade to SL4) I found that now there are no lint warning/error messages in Sublime Text console.
In editor all works fine and errors are show in the gutter, messages appears on hover and so on.
But it was very helpful to see these messages duplicates in console. Is there any way to turn it on?

**Comment by FichteFoll** [comment]
Why would you want to see errors on the console? Does the panel (*SublimeLinter: Show All Errors*) help?

**Comment by andrewmiroshnichenko** [comment]
Awww, didn't know about this panel :(
This is exactly what I wanted.
Thanks for your time, @FichteFoll

**Comment by freder** [comment]
@FichteFoll is there any way to get the name of the rule in the status bar?
I don't want to have the `show all errors` panel open all the time :|

<img width="755" alt="screen shot 2018-03-06 at 21 27 40" src="https://user-images.githubusercontent.com/724844/37056728-857b119e-2185-11e8-9492-36e82c960fef.png">

**Comment by braver** [comment]
If you have a new feature request please open a new issue. Also, please don't spam individual contributors, we'll look at your issue when we get to it.

As for your request, no there is currently no option for that.
