### ISSUE TITLE
Context Menu

### ISSUE THREAD

**Issue by Slapbox** [SublimeLinter/SublimeLinter#1131]
> The context menu now only lists the Lint This View command. The tools menu has been removed.

Unfortunately I'm not even seeing the `Lint This View` command in 4.0.0 and greater. Any thoughts?

**Comment by FichteFoll** [comment]
Provide a debug log and the entire rest of your console: http://www.sublimelinter.com/en/latest/troubleshooting.html

**Comment by tmathews** [comment]
Not seeing context menu or changes to styles in User preferences either.

**Comment by braver** [comment]
If this still doesn't work, re-open with more info!

**Comment by Slapbox** [comment]
I rolled back to 3.x. When I have time I'll try to provide logs for debugging.

**Comment by Slapbox** [comment]
This issue appears to have been caused by `C:\Users\MyUser\AppData\Roaming\Sublime Text 3\Packages\User\SublimeLinter (old).sublime-settings` already existing. When recreating it was attempted, I guess execution stopped for the SublimeLinter plugin. Removing this file and restarting Sublime Text restored functionality.

**Comment by braver** [comment]
🎉
