### ISSUE TITLE
Lint error shown in panel, but not in gutter. No lint errors listed.

### ISSUE THREAD

**Issue by vegar** [SublimeLinter/SublimeLinter#1132]
Have uninstalled and re-installed SublimeLinter and SublimeLinter-eslint after 4.x update.

The linter is set to run linter in background, and it does, but the output of eslint is shown in a panel at bottom instead of in gutter.

![image](https://user-images.githubusercontent.com/764517/37040561-735b2470-215a-11e8-9a59-2c11481c62fe.png)

I've changed my config to have `"debug": true` and `"gutter_theme": "Hands"`.

Statusbar contains the expected `W: {warnings} E: {errors}` text, but `warnings` and `errors` reports `0`.

When running `Show all errors`, no errors are reported.

![2018-03-06_16-19-49](https://user-images.githubusercontent.com/764517/37040758-da0a17e4-215a-11e8-89da-a80732bb5110.gif)

The console doesn't contain much information, but it's clear that eslint is found and that it both runs and reports errors.

> SublimeLinter: #15 SublimeLinter.sublime-package:782: 'eslint' is linting 'dropdown-button.component.js'
> [2018-03-06 16:16:42,975 - INFO     - SublimeLinter.lint.linter] 'eslint' is linting 'dropdown-button.component.js'
> SublimeLinter: #15 SublimeLinter.sublime-package:1178: eslint: dropdown-button.component.js ['C:\\Source\\flis\\WebApiRole\\node_modules\\.bin\\eslint.cmd', '--format', 'json', '--stdin', '--stdin-filename', 'C:\\Source\\flis\\WebApiRole\\src\\app\\components\\button\\dropdown-button.component.js']
> [2018-03-06 16:16:42,979 - INFO     - SublimeLinter.lint.linter] eslint: dropdown-button.component.js ['C:\\Source\\flis\\WebApiRole\\node_modules\\.bin\\eslint.cmd', '--format', 'json', '--stdin', '--stdin-filename', 'C:\\Source\\flis\\WebApiRole\\src\\app\\components\\button\\dropdown-button.component.js']
> SublimeLinter: #15 SublimeLinter.sublime-package:1181: eslint: cwd: C:\Source\flis
> [2018-03-06 16:16:42,979 - INFO     - SublimeLinter.lint.linter] eslint: cwd: C:\Source\flis
> SublimeLinter: #15 SublimeLinter.sublime-package:809: eslint output:
>     [{"filePath":"C:\\Source\\flis\\WebApiRole\\src\\app\\components\\button\\dropdown-button.component.js","messages":[{"ruleId":"quotes","severity":2,"message":"Strings must use singlequote.","line":16,"column":17,"nodeType":"Literal","source":"      restrict: \"EA\",","endLine":16,"endColumn":21,"fix":{"range":[260,264],"text":"'EA'"}},{"ruleId":"no-multi-spaces","severity":2,"message":"Multiple spaces found before '}'.","line":24,"column":13,"nodeType":"Punctuator","source":"      }     })","fix":{"range":[482,487],"text":" "}},{"ruleId":"object-curly-newline","severity":2,"message":"Expected a line break before this closing brace.","line":24,"column":13,"nodeType":"ObjectExpression","source":"      }     })","fix":{"range":[487,487],"text":"\n"}}],"errorCount":3,"warningCount":0,"fixableErrorCount":3,"fixableWarningCount":0,"source":"(function() {\n  'use strict';\n\n  DropdownButtonComponentCtrl.$inject = [];\n\n  function DropdownButtonComponentCtrl() {\n    var vm = this;\n\n    vm.$onInit = function() {\n\n    };\n  }\n\n  angular.module('finale')\n    .component('dropdownButton', {\n      restrict: \"EA\",\n\n      templateUrl: 'src/app/components/button/dropdown-button.component.html',\n      controller: 'DropdownButtonComponentCtrl',\n      transclude: true,\n      bindings: {\n        icon: '@',\n        items: '<'\n      }     })\n    .controller('DropdownButtonComponentCtrl', DropdownButtonComponentCtrl);\n}());\n"}]
>     The rule `angular/service-name` will be split up to different rules in the next version. Please read the docs for more information
> [2018-03-06 16:16:49,946 - INFO     - SublimeLinter.lint.linter] eslint output:
>     [{"filePath":"C:\\Source\\flis\\WebApiRole\\src\\app\\components\\button\\dropdown-button.component.js","messages":[{"ruleId":"quotes","severity":2,"message":"Strings must use singlequote.","line":16,"column":17,"nodeType":"Literal","source":"      restrict: \"EA\",","endLine":16,"endColumn":21,"fix":{"range":[260,264],"text":"'EA'"}},{"ruleId":"no-multi-spaces","severity":2,"message":"Multiple spaces found before '}'.","line":24,"column":13,"nodeType":"Punctuator","source":"      }     })","fix":{"range":[482,487],"text":" "}},{"ruleId":"object-curly-newline","severity":2,"message":"Expected a line break before this closing brace.","line":24,"column":13,"nodeType":"ObjectExpression","source":"      }     })","fix":{"range":[487,487],"text":"\n"}}],"errorCount":3,"warningCount":0,"fixableErrorCount":3,"fixableWarningCount":0,"source":"(function() {\n  'use strict';\n\n  DropdownButtonComponentCtrl.$inject = [];\n\n  function DropdownButtonComponentCtrl() {\n    var vm = this;\n\n    vm.$onInit = function() {\n\n    };\n  }\n\n  angular.module('finale')\n    .component('dropdownButton', {\n      restrict: \"EA\",\n\n      templateUrl: 'src/app/components/button/dropdown-button.component.html',\n      controller: 'DropdownButtonComponentCtrl',\n      transclude: true,\n      bindings: {\n        icon: '@',\n        items: '<'\n      }     })\n    .controller('DropdownButtonComponentCtrl', DropdownButtonComponentCtrl);\n}());\n"}]
>     The rule `angular/service-name` will be split up to different rules in the next version. Please read the docs for more information
> SublimeLinter: #15 SublimeLinter-eslint.sublime-package:50: ERROR: [{"filePath":"C:\\Source\\flis\\WebApiRole\\src\\app\\components\\button\\dropdown-button.component.js","messages":[{"ruleId":"quotes","severity":2,"message":"Strings must use singlequote.","line":16,"column":17,"nodeType":"Literal","source":"      restrict: \"EA\",","endLine":16,"endColumn":21,"fix":{"range":[260,264],"text":"'EA'"}},{"ruleId":"no-multi-spaces","severity":2,"message":"Multiple spaces found before '}'.","line":24,"column":13,"nodeType":"Punctuator","source":"      }     })","fix":{"range":[482,487],"text":" "}},{"ruleId":"object-curly-newline","severity":2,"message":"Expected a line break before this closing brace.","line":24,"column":13,"nodeType":"ObjectExpression","source":"      }     })","fix":{"range":[487,487],"text":"\n"}}],"errorCount":3,"warningCount":0,"fixableErrorCount":3,"fixableWarningCount":0,"source":"(function() {\n  'use strict';\n\n  DropdownButtonComponentCtrl.$inject = [];\n\n  function DropdownButtonComponentCtrl() {\n    var vm = this;\n\n    vm.$onInit = function() {\n\n    };\n  }\n\n  angular.module('finale')\n    .component('dropdownButton', {\n      restrict: \"EA\",\n\n      templateUrl: 'src/app/components/button/dropdown-button.component.html',\n      controller: 'DropdownButtonComponentCtrl',\n      transclude: true,\n      bindings: {\n        icon: '@',\n        items: '<'\n      }     })\n    .controller('DropdownButtonComponentCtrl', DropdownButtonComponentCtrl);\n}());\n"}]
> The rule `angular/service-name` will be split up to different rules in the next version. Please read the docs for more information
> 
> [2018-03-06 16:16:49,948 - ERROR    - SublimeLinter.plugin.eslint] [{"filePath":"C:\\Source\\flis\\WebApiRole\\src\\app\\components\\button\\dropdown-button.component.js","messages":[{"ruleId":"quotes","severity":2,"message":"Strings must use singlequote.","line":16,"column":17,"nodeType":"Literal","source":"      restrict: \"EA\",","endLine":16,"endColumn":21,"fix":{"range":[260,264],"text":"'EA'"}},{"ruleId":"no-multi-spaces","severity":2,"message":"Multiple spaces found before '}'.","line":24,"column":13,"nodeType":"Punctuator","source":"      }     })","fix":{"range":[482,487],"text":" "}},{"ruleId":"object-curly-newline","severity":2,"message":"Expected a line break before this closing brace.","line":24,"column":13,"nodeType":"ObjectExpression","source":"      }     })","fix":{"range":[487,487],"text":"\n"}}],"errorCount":3,"warningCount":0,"fixableErrorCount":3,"fixableWarningCount":0,"source":"(function() {\n  'use strict';\n\n  DropdownButtonComponentCtrl.$inject = [];\n\n  function DropdownButtonComponentCtrl() {\n    var vm = this;\n\n    vm.$onInit = function() {\n\n    };\n  }\n\n  angular.module('finale')\n    .component('dropdownButton', {\n      restrict: \"EA\",\n\n      templateUrl: 'src/app/components/button/dropdown-button.component.html',\n      controller: 'DropdownButtonComponentCtrl',\n      transclude: true,\n      bindings: {\n        icon: '@',\n        items: '<'\n      }     })\n    .controller('DropdownButtonComponentCtrl', DropdownButtonComponentCtrl);\n}());\n"}]
> The rule `angular/service-name` will be split up to different rules in the next version. Please read the docs for more information

The console mentions `ERROR`, but I'm not sure if it's because the linter reports errors in my code, or if it doesn't like the warning about rule deprecations...

Any hints on how to make lint great again?

**Comment by FichteFoll** [comment]
The problem is that the eslint plugin attempts to parse the outputs of eslint as JSON, but because of the deprecation message that fails.
It should probably split output by line and only attempt to parse the first, while logging any additional lines as warnings (which will be shown in the status bar, for example).

https://github.com/SublimeLinter/SublimeLinter-eslint/blob/4ecc891b6162e242b2d91a6c435e7ec68e29036a/linter.py#L50

**Comment by vegar** [comment]
I would love to look into this myself, but python is a cup of tea that I've never tasted....
