### ISSUE TITLE
Upgrade to SublimeLinter 4 should migrate settings

### ISSUE THREAD

**Issue by jdelman** [SublimeLinter/SublimeLinter#1135]
Sublime just _automatically_ upgraded me to Linter 4. It stopped working. 

This is my workflow -- it's part of how I (and many people) program and it's how many people make a living. My tools shouldn't be slowing me down. OK, I know, `auto_upgrade` is a setting, and I've changed it accordingly... but:

Shouldn't upgrading, especially automatically, migrate my settings instead of blowing them away and making me start from scratch?

**Comment by jdelman** [comment]
Sorry, I realize this are dupes of #1103 #1097 etc...

**Comment by FichteFoll** [comment]
TL;DR: the settings were changed *significantly* and the authors (and myself as well) think that spending some 5 minutes of your time to re-import your absolutely necessary settings will be worth it.

**Comment by braver** [comment]
Indeed. I would have loved to have migrated everyone's settings but it's actually a really hard thing to do well so after a few tries we canceled that plan.
