### ISSUE TITLE
Display rule name(s) in status bar

### ISSUE THREAD

**Issue by freder** [SublimeLinter/SublimeLinter#1137]
the previous version used to display the name of the rule(s) in the status bar. I would like for this behavior to return (or to be configurable), because I find it a bit cumbersome having to open the `show all errors` panel first (or even worse: having to pick up the mouse and hover over the gutter ...).

<img width="755" alt="screen shot 2018-03-06 at 21 27 40" src="https://user-images.githubusercontent.com/724844/37057517-ed1e45c6-2187-11e8-9bdd-c98501bb0f3c.png">

**Comment by jhundley9109** [comment]
I second this. I'd like statusbar.messages_template to show up in the statusbar by default (as it did with the previous release) without either clicking on the gutter icon or showing the "Output: SublimeLinter" menu.

**Comment by FichteFoll** [comment]
Currently, the status bar messages are only shown when your caret is within the region of the highlighted error. I guess this could be made configurable.

**Comment by jhundley9109** [comment]
Hmm, I don't think any new functionality is needed really, its just the messaging in the status bar doesn't behave quite the same as it did in the previous version. It seems the warnings aren't shown on the same trigger they were before. Perhaps it showed the message in the status bar when your cursor was simply on the same line as the syntax error. 

I know I didn't have to move the cursor to the beginning of the line when I misspelled a variable name in order for the status bar to tell me what the syntax error was. Now it appears I do have to do that.

I hope this helps, thanks for your time on this project!

**Comment by jhundley9109** [comment]
Ah I see, my issue isn't quite the same as the OP's request. They are related but not quite the same...

**Comment by bs85** [comment]
Seconding this, having to move the cursor horizontally to see the error in the status bar feels really bad compared to the old behavior when you're only using your keyboard. Could there be a setting to enable the old behavior?

**Comment by FichteFoll** [comment]
Regarding the issue in OP: I would implement this with `status_bar.messages_template` and instead of a single `{messages}` variable I would offer `{code}`, `{message}`, `{type}` etc. for a *single* message, which is then joined with `"; "`. If the template is empty, nothing would be shown of course.

**Comment by gerardroche** [comment]
It would be great if a message template system like GitGutter (https://github.com/jisaacks/GitGutter#status-bar-text-template) was implemented for the status bar.

Relates also to: https://github.com/SublimeLinter/SublimeLinter/pull/1081

**Comment by braver** [comment]
The basic template thing is in already place now. Multiple messages are already joined with `";"`, so you don't have to worry about that.

So we need to add `"{type}"` (i.e. "error" or "warning") `"{code}"` (e.g. "D103") and `"{linter}"` (e.g. "flake8") in addition to the current `"{message}"` placeholder. 

If anyone want to have a go at it, by my guest. Don't be scared, it's just a little 🐍 😉

**Comment by GlassGruber** [comment]
Hey there! 
This feature is great! I'm facing a funny issue, this is the template I use:
```json
"statusbar.messages_template": "{linter} - {type} ({code}): {message} -- Ignore inline with `# noqa: {code}`"
```
When on a basic annotations like `@todo: clean up` this is what is displayed.
```
annotations - warning (@todo): clean up -- Ignore inline with `# noqa: @todo`"
```

It's a neglectable issue, but maybe it could be addressed moving the "statusbar.messages_template" setting to the linter settings? Or better make global setting overridable by linter template setting? 

This way you can also have customized messages for each linter as a bonus!

**Comment by braver** [comment]
Ah, yes, the templates throughout SublimeLinter, for tooltips, output panel, and status bar, are all generic. We just expose the status bar to the settings so you can optimize the space it takes for your own purposes. 

I don't think we want the added complexity of making them specific for each linter, just so you can reconstruct your own linter feedback. I'd have to see a better use case for it than this one.

**Comment by kaste** [comment]
We have what I think a similar request to show urls to each reported problem.  Of course linters could provide documentation about itself, its rules or here: about how to disable a specific rule inline. Well, we could even write these `#noqa` or `// disable-next-line` if the user clicks on something or otherwise invokes such an action. So, I think in a broader sense, this can get a valid feature request.
