### ISSUE TITLE
None of SublimeLinter node.js linters work (Win 7 x64)

### ISSUE THREAD

**Issue by Starojitski** [SublimeLinter/SublimeLinter#114]
I tried installing jshint, csslint and jscs. All three work fine in CLI.
But when i run them in ST3 i get following message in console:

For `jscs`

```
SublimeLinter: jscs version query: C:\Users\Konstantin\AppData\Roaming\npm\jscs.cmd --version 
SublimeLinter: jscs version: 1.8.4 
SublimeLinter: jscs: (>= 1.0.10) satisfied by 1.8.4 
SublimeLinter: jscs activated: C:\Users\Konstantin\AppData\Roaming\npm\jscs.cmd SublimeLinter: jscs: toys.js ['C:\\Users\\Konstantin\\AppData\\Roaming\\npm\\jscs.cmd', '-r', 'checkstyle', '--config', 'D:\\htdocs\\toys\\catalog\\view\\javascript\\.jscsrc'] 
SublimeLinter: jscs output:
Welcome to Git (version 1.8.4-preview20130916)


Run 'git help git' to display the help index.
Run 'git help <command>' to display help for specific commands.
sh.exe": /c: is a directory 
```

For `jshint`

```
SublimeLinter: jshint version query: C:\Users\Konstantin\AppData\Roaming\npm\jshint.cmd --version 
SublimeLinter: WARNING: no jshint version could be extracted from:
Welcome to Git (version 1.8.4-preview20130916)


Run 'git help git' to display the help index.
Run 'git help <command>' to display help for specific commands.
sh.exe": /c: is a directory
```

For `csslint`

```
SublimeLinter: csslint version query: C:\Users\Konstantin\AppData\Roaming\npm\csslint.cmd --version 
SublimeLinter: WARNING: no csslint version could be extracted from:
Welcome to Git (version 1.8.4-preview20130916)

Run 'git help git' to display the help index.
Run 'git help <command>' to display help for specific commands.
sh.exe": /c: is a directory
```

Since all three display very similar behavior i assume that the problem does not lie in linters but either in SublimeLinter plugin or higher up the tree (ST3 or Windows)

Seeing that in all 3 cases there is `Welcome to Git (...` it seemed to me that either SublimeLinter or ST3 tries to execute command through git.exe instead of cmd.exe
Also the line `sh.exe": /c: is a directory` is probably something like `sh.exe": /c:\C:\Users\Konstantin\AppData\Roaming\npm\jscs.cmd` that does not execute properly

I uninstalled Git from windows and now the messages i get are:

```
SublimeLinter: jscs version query: C:\Users\Konstantin\AppData\Roaming\npm\jscs.cmd --version 
SublimeLinter: ERROR: could not launch ['C:\\Users\\Konstantin\\AppData\\Roaming\\npm\\jscs.cmd', '--version'] 
SublimeLinter: reason: [WinError 2] The system cannot find the file specified 
SublimeLinter: PATH: C:\Program .....
SublimeLinter: WARNING: no jscs version could be extracted from:
```

Anyine any idea?

Thanks in advance,

Konstantin

**Comment by arvind07** [comment]
It seems weird but in my case the solution is different. I was getting following error:
`FileNotFoundError: [WinError 3] The system cannot find the path specified: 'c:\\users\\arvind~1\\appdata\\local\\temp\\SublimeLinter3-arvind\\app.js'
 `

I checked the `c:\\users\\arvind~1\\appdata\\local\\temp\\` folder and found that it had not `SublimeLinter3-arvind` folder. I created this folder manually and JSHint it started working..
