### ISSUE TITLE
`executable` setting requires `can_lint` override.

### ISSUE THREAD

**Issue by veelo** [SublimeLinter/SublimeLinter#1142]
The [`executable`](https://github.com/SublimeLinter/SublimeLinter/blob/master/docs/linter_settings.rst#executable) setting does not work for contributed linters unless they override `can_lint` like
```python
    @classmethod
    def can_lint(cls):
            """Assume the linter can lint."""
            return True
```

**Comment by braver** [comment]
Duplicate of #1086
