### ISSUE TITLE
Erroneous linter setting example on default settings file

### ISSUE THREAD

**Issue by Odyseus** [SublimeLinter/SublimeLinter#1143]
Hello, everybody.

The default **SublimeLinter.sublime-settings** file comes with an example linter setting for **flake8** ([L54](https://github.com/SublimeLinter/SublimeLinter/blob/master/SublimeLinter.sublime-settings#L54)). It reads:

```json
"flake8": {
    "python": null,
    "disable": false,
    "args": [],
    "excludes": [],
    "ignore": "",
    "max-complexity": -1,
    "max-line-length": null,
    "select": ""
}
```

The `ignore`, `max-complexity` and `max-line-length` keys are invalid settings values for SublimeLinter 4+. It should read somewhat like:

```json
"flake8": {
    "python": null,
    "disable": false,
    "args": [
        "--max-complexity", "-1",
        "--max-line-length", "100",
        "--ignore", "E731,E402"
    ],
    "excludes": [],
    "select": ""
}
```

I'm not really sure if the `select` key is valid or not. That key [isn't documented](https://github.com/SublimeLinter/SublimeLinter/blob/master/docs/linter_settings.rst) and I couldn't find its use in the [SublimeLinter-flake8](https://github.com/SublimeLinter/SublimeLinter-flake8) repository.

**Comment by FichteFoll** [comment]
Good spot. These should definitely be updated.

`select` was a linter-specific setting for inline overrides, much like `ignore`. Since that feature has been removed in SL4, the flake8 plugin doesn't parse that anymore and they should instead be provided in `args`.

I'm not sure about `excludes`, though. Note that it is also specified in the example `csslint` configuration only a few lines earlier.

**Comment by Odyseus** [comment]
Hello, @FichteFoll.

The `excludes` key seems to be valid and working as expected and it is also in the documentation.

I said *valid and working as expected* because I have the **SublimeLinter-contrib-sass-lint** and the **SublimeLinter-csslint** linters installed and enabled. In the SASS linter I have `"excludes": ["*.css"]` configured so when I open a CSS file, the SASS linter doesn't lint the CSS file (a thing that bothered me for a long time until I *discovered* the `excludes` option).

**Comment by FichteFoll** [comment]
Ah right, I forgot about this linter-agnostic setting. (documented [here](https://sublimelinter.readthedocs.io/en/latest/linter_settings.html#excludes))

**Comment by braver** [comment]
Thanks for reporting!
