### ISSUE TITLE
File "lint.events in \Data\Installed Packages\SublimeLinter.sublime-packages", line 28, in broadcast

### ISSUE THREAD

**Issue by deuterium2h** [SublimeLinter/SublimeLinter#1145]
Here are the warnings I've encountered after upgrading to SublimeLinter 4.

- ` File "lint.events in "SublimeDir"\Data\Installed Packages\SublimeLinter.sublime-package", line 28, in broadcast`
- ` File "highlight_view in "SublimeDir"\Data\Installed Packages\SublimeLinter.sublime-package", line 91, in on_lint_result`
- ` File "highlight_view in "SublimeDir"\Data\Installed Packages\SublimeLinter.sublime-package", line 312, in prepare_highlights_data`

Apologies if there's already a same issue submitted. I'm quite new here. Thanks!

**Comment by braver** [comment]
Thanks for reporting. Does the error persist after restarting ST?

**Comment by deuterium2h** [comment]
Yes, I also tried reloading the linter, and removing the user defined settings. Btw, I'm using the build 3143 of ST3

**Comment by braver** [comment]
Ok, we're going to need a full [debug log](https://github.com/SublimeLinter/SublimeLinter/blob/master/docs/troubleshooting.rst#debug-mode) then.

**Comment by arcman77** [comment]
I'm also having this issue

**Comment by braver** [comment]
Ehm, triple backticks around the multi-line code blocks please!

**Comment by arcman77** [comment]
@braver Okay, updated. I seriously don't know what the deal is though. I'm using:
SublimeLinter: 4.0.6
SublimeLinter-eslint: 4.0.3
ESLint: 5.0.1

**Comment by braver** [comment]
Well, let’s start from the top of that log. It complains about your old SublimeLinter settings. Please back that up somewhere and remove it, then try again.

**Comment by arcman77** [comment]
@braver that fixed it :)

**Comment by braver** [comment]
Cool! 😀

**Comment by FichteFoll** [comment]
@deuterium2h we need a [debug log](https://github.com/SublimeLinter/SublimeLinter/blob/master/docs/troubleshooting.rst#debug-mode) to understand what's going on.

**Comment by deuterium2h** [comment]
I'm sorry I forgot about this. I just did a restart on my laptop and the warnings were gone. The linter is working fine now, I guess? But I did have the similar debug log from @arcman77 
Should I close this thread? I really didn't know what happened before.

**Comment by braver** [comment]
Well upgrades are a bit rocky right now, so if it solves itself like that it's probably ok. Not like we can really investigate this any further now that it's gone :) Just open a new issue if you do run into something again.
