### ISSUE TITLE
Replicating behaviour or old "show_errors_on_save" setting

### ISSUE THREAD

**Issue by jprada014** [SublimeLinter/SublimeLinter#1150]
Is there any way of replicate the behaviour of the now removed ` { "show_errors_on_save": true }` setting?

This settings unabled the file to be saved and displayed the error very clear.

As a workaround, this can be emulated using the plugin _SublimeOnSaveBuild_ after configuring a _Build System_ for your language, but I preferred SublimeLinter one, as _SublimeOnSaveBuild_ need an additional menu command action to remove the error message after save.

**Comment by FichteFoll** [comment]
Duplicate of #1084.
