### ISSUE TITLE
Improvement: add command to toggle linting (for specific linter) in this view

### ISSUE THREAD

**Issue by Narretz** [SublimeLinter/SublimeLinter#1154]
This is for version 4. It looks like the list of commands is much shorter than it was in SL3, so this might be a request to bring this behavior back. Sometimes I don't want any / a specific linter linting in a view, e.g. if I'm looking at a minified Javascript file or a file that is simply loaded from folder that doesn't have a linter configured. Then it would be cool if I could say "hey don't lint this view until I re-enable it"

**Comment by FichteFoll** [comment]
Related: https://github.com/SublimeLinter/SublimeLinter/issues/1149
