### ISSUE TITLE
Error loading syntax file

### ISSUE THREAD

**Issue by Cooperdale** [SublimeLinter/SublimeLinter#1160]
Hello, after the upgrade to the latest version I get this error when opening Sublime:

`Error loading syntax file: "Packages/SublimeLinter/panel/panel.sublime-syntax"
Unable to read Packages/SublimeLinter/panel/panel.sublime-syntax`

What can I do to fix this? Thanks.

**Comment by braver** [comment]
Oh, so it does that with upgrades too. Interesting. But we're already tracking this in #1122

**Comment by kaste** [comment]
Please send us a full console log the next time this happens bc we still have not enough information about this bug.
