### ISSUE TITLE
Do not create and update the panel in the background

### ISSUE THREAD

**Issue by kaste** [SublimeLinter/SublimeLinter#1163]
- It's sane, c'mon haha what were we smoking? 😒 
- Most of the time probably the panel-syntax would be unused 🤡 
- If the user re-opens it via ctrl-k a, it may gain enough focus, so that `next_result` works again. 🤘

**Comment by braver** [comment]
Well the nice thing of this is that next_result works right away. This is from before we had the new goto commands (and we just killed the old goto commands). Seemed like a reasonably good idea then. Now though, not so much.
