### ISSUE TITLE
No highlight using outline style when linter reports only line number

### ISSUE THREAD

**Issue by braver** [SublimeLinter/SublimeLinter#1168]
@kaste I get underscores with pydocstyle. 

<img width="120" alt="screen shot 2018-03-08 at 17 31 51" src="https://user-images.githubusercontent.com/2543659/37162916-c8c2c664-22f6-11e8-8b4e-c323eb48741f.png">

This is with stippled_underlines. With outlines it draws nothing at all. You can basically run any py file in SL with pydocstyle to reproduce.

Example pydocstyle (@ master) output (it only reports line numbers):
```
SublimeLinter: #39 linter.py:809: pydocstyle output:
    /var/folders/cp/659wm5bs1pl2kpz8j9jvckrw0000gn/T/tmpf_z1f2.py:1 at module level:
            D100: Missing docstring in public module
    /var/folders/cp/659wm5bs1pl2kpz8j9jvckrw0000gn/T/tmpf_z1f2.py:10 in public class `TooltipController`:
            D101: Missing docstring in public class
    /var/folders/cp/659wm5bs1pl2kpz8j9jvckrw0000gn/T/tmpf_z1f2.py:28 in public class `SublimeLinterLineReportCommand`:
            D101: Missing docstring in public class
    /var/folders/cp/659wm5bs1pl2kpz8j9jvckrw0000gn/T/tmpf_z1f2.py:29 in public method `run`:
            D102: Missing docstring in public method
    /var/folders/cp/659wm5bs1pl2kpz8j9jvckrw0000gn/T/tmpf_z1f2.py:88 in public function `join_msgs`:
            D103: Missing docstring in public function
    /var/folders/cp/659wm5bs1pl2kpz8j9jvckrw0000gn/T/tmpf_z1f2.py:132 in public function `get_current_pos`:
            D103: Missing docstring in public function
```

**Comment by eproxus** [comment]
Just reported #1206, these two seem related somehow.

**Comment by braver** [comment]
Actually, our default settings describes exactly happens here and what the solution is:

```
"no_column_highlights_line": true
```

So, yeah. Perhaps setting this to true is a better default, but 🤷‍♂️

**Comment by FichteFoll** [comment]
>With outlines it draws nothing at all.

Has this been fixed? Underlines are fine imo, but outlines not being drawn at all is a problem imo. (This has actually been useful in the past, because iirc they do get drawn but are really small instead and almost unnoticeable.)
The fix would probably to use a different style for zero-width regions.

**Comment by braver** [comment]
We currently state that this a design choice and there is a setting if you want to change the behaviour. I guess I'm still finding out new things about this project too ;)

S ,nothing changed since SL3 in this regard and I don't feel like introducing yet another fallback since we're still having a discussion about that. If it's important that we change something here, it'll surface again by itself later.

**Comment by kaste** [comment]
- We want to ensure regions have a length of at least 1

- We can improve the WS fallback for underline style. Iff the region is at the beginning of a line and has a length of 1, we can set the region length to 0, and trick Sublime into drawing an underline.

**Comment by kaste** [comment]
Hm.

![image](https://user-images.githubusercontent.com/8558/37830099-bd863e32-2ea1-11e8-8e81-23aa613c34cf.png)


These underlines have different weights. 😳

**Comment by braver** [comment]
Second screenshot looks better IMO.
