### ISSUE TITLE
improve the UX of the outline fallback for underline styles

### ISSUE THREAD

**Issue by PrinceNebulon** [SublimeLinter/SublimeLinter#1171]
After upgrading to the latest version, the one where the [settings changed](https://github.com/SublimeLinter/SublimeLinter/blob/master/messages/4.0.0.txt), and updating my settings, some things are using the `outline` mark style even though I've overridden the defaults to `squiggly_underline`. 

This screenshot illustrates the issue:

* There is a red outline on line 1
* There is a purple outline on line 4
* I expect both of these scenarios to use squiggly underlines like they did prior to the upgrade

![image](https://user-images.githubusercontent.com/1349974/37171231-70c774c2-22ca-11e8-93a1-5152873da4be.png)

I'm not sure where the purple is coming from. I expect that to be yellow. That's less of an issue, but I'd also like to know where that color is coming from and how to change it.

It's quite possible I could be missing some new config option. Any guidance would be appreciated.

[edit: removed logs and settings as they're irrelevant to the discussion /@braver]

**Comment by braver** [comment]
Thanks for upgrading and including all the info. There should be a note about this in the default settings: Sublime Text doesn’t draw underlines on white space. Therefore, we now draw outlines whenever there is white space in a problem region. 

That said, we’re looking for feedback here and maybe this should become optional.

**Comment by tmathews** [comment]
Is there a way to just have the gutter dot and remove the outline? I don't quite find it appealing for my tastes.

**Comment by braver** [comment]
Sure, you set "mark_style" to "none" and they're gone.

**Comment by tmathews** [comment]
I'd rather still have squiggles for issues without white-space problem, and disable with whitespace problem. Or have a way to disable outline encapsulation.

**Comment by braver** [comment]
Ok, the fallback is here to stay but we can discuss possible improvements and fine-tuning.

**Comment by tmathews** [comment]
I'd just like an option to turn off outline encapsulation for regions and use the gutter. Places where the column number is known should have an underline (of desired style). This way for large issues (such as in/consistent returns) it won't encapsulate the whole method and I'll look at the gutter for the error, where as other errors it'll be pointed out immediately. This also helps with the other errors as the outline encapsulation won't block them and I can actually see them.

**Comment by PrinceNebulon** [comment]
@braver Thanks for pointing out the note about whitespace. It totally says that, but I guess it didn't sink in for me when I was reading through that.

Could you help me create a style that only applies to eslint indentation? I saw the comment above the styles block in the default settings that says "codes is an array which can contain error codes provided by a linter". However, when I try to use the codes property on a style, I get the error `Additional properties are not allowed ('codes' was unexpected)` upon saving my user settings. 

Style in my config:

```
  "styles": [
    {
      "icon": "dot",
      "mark_style": "none",
      "priority": 1,
      "scope": "region.redish markup.deleted.sublime_linter markup.error.sublime_linter",
      "codes": [
        "indent"
      ]
    }
  ]
```

Debug message from eslint:

```
{
  "column": 1,
  "endColumn": 2,
  "endLine": 1,
  "fix": {
    "range": [
      0,
      1
    ],
    "text": ""
  },
  "line": 1,
  "message": "Expected indentation of 0 tabs but found 1.",
  "nodeType": "Identifier",
  "ruleId": "indent",
  "severity": 1,
  "source": "\t$(document).ready(() => {"
}
```

**Comment by braver** [comment]
@PrinceNebulon To create styles for a rule in eslint, you put a styles block in the settings for the eslint linter. The global styles block doesn't take a "codes" option. An abbreviated example from my setup:

```json
"linters": {
    "eslint": {
        "styles": [
            {
                "scope": "variable.function",
                "priority": 0,
                "icon": "diamond-outline",
                "types": ["error", "warning"]
            },
            {
                "scope": "variable.function",
                "priority": 1,
                "icon": "triangle-outline",
                "codes": ["D100"]
            }
        ]
    }
}
```

**Comment by eproxus** [comment]
Would an acceptable alternative fallback implementation be to draw an underline up until the first whitespace? Alternatively, repeat the error (probably ugly) for all non-whitespace sections in the line...

**Comment by braver** [comment]
> to draw an underline up until the first whitespace

There are a few cases here that all need a suitable solution. You can probably have these regions to highlight:

1. `[some text] [whitespace] [some text]`
2. `[some text] [whitespace]`
3. `[whitespace] [some text]`
4. `[whitespace]`

So, if there is non-whitespace in the region you could indeed just highlight the first non-whitespace you find inside that region. You could also just look forward until you find any non-whitespace and highlight that, but that could be a few lines down from the actual problem (e.g. if you have a trailing whitespace problem). If there is only whitespace left (e.g. at EOF) there would be nothing to highlight.  In case of 4, your region might touch some non-whitespace before it, so you may want to highlight that.

**Comment by eproxus** [comment]
I just really want my underlines 😄

The heuristic could be:
1. Outline any line that is only whitespace
2. On other lines, underline non-whitespace regions

**Comment by braver** [comment]
Well, you want make sure you only underline 1 non-whitespace word, because otherwise it would look like you have multiple problems.

**Comment by eproxus** [comment]
@braver Good point. I guess the Sublime bug better get fixed then. Thanks!

**Comment by Slapbox** [comment]
If you're able to use it without it crashing (it crashes on just a tiny number of my files) you can use the `eslint_d` plugin for SublimeLinter to circumvent this. Unfortunately that plugin is no longer supported, but the settings available on `eslint` currently are unacceptably distracting. They do as much harm as good.

**Comment by braver** [comment]
Current status:

- We need the outlines unless we create a smart system that finds a word to highlight in case there is only whitespace in a region.
- To prevent highlighting multi-line regions we would need to re-interpret the report from the linter and perhaps only highlight the first word if there is a first word.

But what we're seeing mostly is that the highlights get in the way of editing, in general not specifically for regions that have whitespace. And we have solutions for that.  We don't have any feedback that says that those aren't good solutions, personally I'm happy about how that works.

So, I'm labeling as "awaiting response" so that unless someone brings something new to the discussion within 14 days this issue will auto-close.

**Comment by eproxus** [comment]
> And we have solutions for that.

@braver What solutions do you refer to?

**Comment by Slapbox** [comment]
Is there any solution to this? My workaround no longer works on newer versions of `ESLint` or `ESLint_d`, and the linting styles are still an abomination.

**Comment by braver** [comment]
> I'm perfectly fine with whitespace not being decorated.

That would mean some errors to not get highlighted at all. That’s not acceptable.

I already outlined some options to make the highlighting less distracting. Have you tried them?

**Comment by Slapbox** [comment]
Thanks for your reply @braver . I've tried everything I've found outlined in the docs and pointed to by you across various issues. I've probably spent longer than I should scouring the site, but the outlines remain horrendously distracting even after trying all available options.

I'd much prefer no highlighting and just a gutter icon to forced outlining. Is there any way? In previous versions all errors were covered without outlining whitespace, by underlining other relevant portions of the code. Is there no way to restore this functionality either?

**Comment by braver** [comment]
You could set `"mark_style"` to none. 

We've had various discussions about trying to recreate the old behaviour. It's not impossible but probably pretty hard. Essentially, we don't currently have someone motivated enough to make the attempt.

**Comment by Slapbox** [comment]
>we don't currently have someone motivated enough to make the attempt.

Understood

Unfortunately setting `mark_style` to none disables marks both with and without whitespace, as you know. I might go this route, but it's a bummer.
