### ISSUE TITLE
Toggle disable/enable SublimeLinter in not available anymore? 

### ISSUE THREAD

**Issue by asfktz** [SublimeLinter/SublimeLinter#1178]
Hi! seems like recently the option to disable a linter is not available anymore, is it?

If so, how can I temporarily disable a linter?

**Comment by braver** [comment]
Linters hava a [“disable”] setting that when true disables it: https://github.com/SublimeLinter/SublimeLinter/blob/master/docs/linter_settings.rst#disable

We’re looking into how to best quickly toggle linters: https://github.com/SublimeLinter/SublimeLinter/issues/1149
