### ISSUE TITLE
ValueError: path is on mount 'S:', start on mount 'C:'

### ISSUE THREAD

**Issue by bmix** [SublimeLinter/SublimeLinter#1179]
On Windows 10, using SublimeLinter 4, I have some symlinks from within my home at `C:\Users\bmix` to `S:\Users\bmix`. I occasionally get the following error. What does it mean?

> Traceback (most recent call last):
>   File "lint.events in C:\Users\bmix\AppData\Roaming\Sublime Text 3\Installed Packages\SublimeLinter.sublime-package", line 28, in broadcast
>   File "panel_view in C:\Users\bmix\AppData\Roaming\Sublime Text 3\Installed Packages\SublimeLinter.sublime-package", line 48, in on_lint_result
>   File "panel_view in C:\Users\bmix\AppData\Roaming\Sublime Text 3\Installed Packages\SublimeLinter.sublime-package", line 277, in fill_panel
>   File "panel_view in C:\Users\bmix\AppData\Roaming\Sublime Text 3\Installed Packages\SublimeLinter.sublime-package", line 166, in create_path_dict
>   File "panel_view in C:\Users\bmix\AppData\Roaming\Sublime Text 3\Installed Packages\SublimeLinter.sublime-package", line 166, in <dictcomp>
>   File "./python3.3/ntpath.py", line 564, in relpath
> ValueError: path is on mount 'S:', start on mount 'C:'

**Comment by kaste** [comment]
Thanks for reporting. That's a bug.
