### ISSUE TITLE
Reduce number of gutter themes

### ISSUE THREAD

**Issue by pykong** [SublimeLinter/SublimeLinter#1186]
The development of SL4 was much about reducing old cruft.
I do not consider all gutter themes which SL ships with to be high quality.
e.g. the `knob` theme is not that great, IMHO.

Maybe we want to reduce the number of default themes.
Say down to five.

The old themes could still be hosted in separate repos, still available for installation via
PackageControl.

Just a suggestion of mine.

**Comment by braver** [comment]
The old themes are basically legacy fan service, the only one that counts is "Default". Some people like them so we keep them around. They cost us no effort right now anyway. Perhaps in SL5 we can be even more rigorous and spin them off to separate repos, but right now that would only result in me having to explain to everyone where the icons went and how to install them. So, some day perhaps. You can always count on me to cut out cruft if I find a reason to do so 😉

**Comment by pykong** [comment]
Alright. We need to save some fun for SL5. :-)
