### ISSUE TITLE
Extreme CPU Usage

### ISSUE THREAD

**Issue by Kautenja** [SublimeLinter/SublimeLinter#1196]
I've encountered an issue where SublimeLinter is consuming a ridiculous amount of resources. I initially believed it to be the result of a component linter, but have since removed all linters. It would seem that SublimeLinter itself spawns a Python process on save (though more occur than how many saves I dispatch) that ramps up to 100% then slowly tapers off before terminating. I've removed and reinstalled SublimeLinter (with no additional linters installed) and observe the behavior returns with fresh installs. I also notice that the `plugin_host` process ramps up to about 20% CPU usage (it normally sits below 1% with all other plugins and no SublimeLinter). I never experienced poor performance using a version prior to 4.0.4 so I'm assuming this has to do with something in a recent update.

#### Versioning

OS: MacOS 10.13.3
ST3: build 3143
SublimeLinter: 4.0.6

#### Example of Massive Spawn of Python Programs

<img width="696" alt="screen shot 2018-03-13 at 3 28 44 pm" src="https://user-images.githubusercontent.com/2184469/37368877-7c13814a-26d5-11e8-9c5f-456d29258a45.png">

**Comment by FichteFoll** [comment]
Are you sure you removed all other linter plugins? If there are no linters, SL doesn't really do anything.

Please provide a debug log.

**Comment by Kautenja** [comment]
Whoops, it would appear that Package Control somehow lost track of a `pyflakes` contrib package that I had to find and remove manually. After doing so CPU usage problems are resolved with my normal stack of linters. Apologies for the time waste, closing issue.
