### ISSUE TITLE
GitGutter overrides v4 gutter marks

### ISSUE THREAD

**Issue by dndrsn** [SublimeLinter/SublimeLinter#1197]
GitGutter's "protected_regions" () previously allowed SublimeLinter gutter marks to take precedence.  

Some combination in the following GitGutter settings used to work:
```
  "protected_regions": [
    "sublimelinter-warning-marks",
    "sublimelinter-error-marks",
    "sublimelinter-warning-gutter-marks",
    "sublimelinter-error-gutter-marks",
    "lint-underline-illegal",
    "lint-underline-violation",
    "lint-underline-warning",
    "lint-outlines-illegal",
    "lint-outlines-violation",
    "lint-outlines-warning",
    "lint-annotations",
    "bookmarks"
  ]
```
It no longer works in v4.  Perhaps the SublimeLinter region names just changed?

**Comment by braver** [comment]
GitGutter’s default set includes the correct scopes: https://github.com/jisaacks/GitGutter/blob/master/GitGutter.sublime-settings#L133

It seems to work reasonably well on my machine.

**Comment by dndrsn** [comment]
I'll try to figure out exactly why it doesn't work for me.  I've tried resetting my SublimeLinter and GitGutter prefs to the defaults and still have the issue.  I can see the linter gutter mark show and then be immediately replaced by the git gutter mark.  Same behavior across multiple languages.  Worked fine in V3.

**Comment by dndrsn** [comment]
Uninstalling and reinstalling GitGutter seems to have resolved the issue.  No idea why that might help.  I assume order of installation doesn't affect package load order or anything like that?  Just a thought.  WFM now.

**Comment by braver** [comment]
Ok. We'll keep an eye out, the managing gutter icons for multiple packages hasn't been the most robust thing in the ecosystem ever.
