### ISSUE TITLE
Outline and underline are too thin

### ISSUE THREAD

**Issue by martinbohman** [SublimeLinter/SublimeLinter#1203]
In SL 4, the outline and underline markers are too thin. They seem to have a thickness of only 1px which is almost invisible on a 2560x1440 27" monitor. See attached picture for example of outline with color yellowish.

I suggest one of the following:
* Add an option to select thickness of outline/underline
* Add additional mark styles (e.g. "strong_outline", "strong_underline")
* Make the current ones thicker

Example of current situation:
![screen shot 2018-03-14 at 12 54 50](https://user-images.githubusercontent.com/6624586/37400994-f13a82a0-2786-11e8-9f30-160a328dd7b2.png)

**Comment by braver** [comment]
> - Add an option to select thickness of outline/underline
> - Add additional mark styles (e.g. "strong_outline", "strong_underline")

This is impossible on our end, the styles are provided by Sublime Text and we cannot add new ones.

> - Make the current ones thicker

You can try two things:

- Use different scopes to get more contrasty colors. Here's a little how-to: https://github.com/SublimeLinter/SublimeLinter/blob/master/docs/settings.rst#styles-colors
- Use one of the other highlight styles.

**Comment by martinbohman** [comment]
Ah, I see. My bad. Thanks for clarifying. 
For anyone else having this problem: I played around with my color scheme options to get a yellow outline with better contrast and thus satisfying visibility.

**Comment by braver** [comment]
👍
