### ISSUE TITLE
Show assigned linters in the status bar per view

### ISSUE THREAD

**Issue by kaste** [SublimeLinter/SublimeLinter#1205]

**Comment by FichteFoll** [comment]
Will this be enabled by default? How many linters do you think are reasonable to be displayed? What do you expect to be the average?

Note that SublimeLinter-contrib-sublimesyntax needs to be active for all views in order to detect whether a view is into a test file.

**Comment by braver** [comment]
The average is probably 1, sometimes 2, in exceptional situations 3. I wouldn't enable this by default actually, the status bar is crowded enough as it is.

**Comment by kaste** [comment]
This is not actionable right now. I think it should be on by default though. The problem is that linters get first enabled (AKA assigned) to buffers. And later they get excluded via different rules e.g. `excludes` or the `disabled` setting. And then they run and get "disabled" bc the executable cannot be found.

So we need to rethink the enabled/disabled design here.

**Comment by FichteFoll** [comment]
Couldn't you hook the lint end event here? It would seem hard to remove linters from the "active" list though.
