### ISSUE TITLE
"no_column_highlights_line" does not respect settings in "styles"

### ISSUE THREAD

**Issue by eproxus** [SublimeLinter/SublimeLinter#1206]
The setting `"no_column_highlights_line"` does not use the styles from `"styles"` section. Setting the style for errors to `"solid_underline"` and `"no_column_highlights_line"` to `true` will use the style `"outline"` on lines with no column information.

SublimeLinter v4.0.6, Sublime Text 3157.

**Comment by eproxus** [comment]
Another piece of the puzzle: using the style `"fill"` works, it's just the underline styles that doesn't work 😕

**Comment by eproxus** [comment]
Oh yeah, lines with code usually have white spaces in them 😄

So this is not possible to achieve in Sublime Text?

**Comment by braver** [comment]
Nope, the underlines simply don't work on whitespace so we need outlines for this to work reliably. More info is here: #1171

**Comment by eproxus** [comment]
That's sad, thanks.

Some documentation explaining this would be appreciated, probably directly in the default config file.

**Comment by braver** [comment]
The info is in the styles section (which has a lot of info...): https://github.com/SublimeLinter/SublimeLinter/blob/master/SublimeLinter.sublime-settings#L110

**Comment by eproxus** [comment]
Just saw that 🤦‍♂️ Sorry

**Comment by braver** [comment]
😀
