### ISSUE TITLE
Please stop showing change log with every update

### ISSUE THREAD

**Issue by mdmower** [SublimeLinter/SublimeLinter#1208]
Could you please either disable change log auto-display with each update, or at least offer an option to disable their auto-display in settings?

**Comment by braver** [comment]
We don't control how that works, we just try to include a useful message (but only if we have something important to report). Package control is the one that displays the messages, if it's configurable it's probably in here somewhere: https://packagecontrol.io/docs/settings

**Comment by FichteFoll** [comment]
You can't hide update messages at the moment. https://github.com/wbond/package_control/issues/1231

Imo the update messages that SL shows are reasonable and something users should be interested in. It's not like they are spamming you with affiliate links either.

**Comment by mattwomple** [comment]
> Imo the update messages that SL shows are reasonable

No, their frequency and the necessity to restart SublimeText make them unreasonable. This package has become a nuisance since 4.0; I'm done with it. I hope the developers eventually concede that the updates need to be silenced.

**Comment by braver** [comment]
Pleas switch to manual updates if you can’t deal with us actually maintaining this thing.

**Comment by kaste** [comment]
Starting with the next release we will ship a (hopefully silent) hot-reloader. Writing issues already is a contribution! And pinging here was okay bc it was a closed issue and I completely forgot about it.
