### ISSUE TITLE
Log deprecation warnings

### ISSUE THREAD

**Issue by kaste** [SublimeLinter/SublimeLinter#1217]
Log deprecation warnings for the following:

- Declared `syntax`, `selectors`
- Declared `version_args`, `version_re`, `version_requirement`
- Declared `inline_settings`, `inline_overrides`, `comment_re`, `shebang_match`
- ~~Declared `executable`~~
- Overriden `build_cmd`
- Overriden `insert_args`
- ~~Accessed `executable_path`~~ ✔️ #1241 
- Implemented `can_lint`
- Implemented `can_lint_syntax`
- Uses `@python` in cmd

**Comment by braver** [comment]
With a checklist like this, I could also go through our plugins and update them, and open issues in the 3rd party ones. I don’t really expect the maintainers or users to read depreciation warnings and to undertake action. Usually maintainers are missing and I’m pessimistic about users fixing these things (perhaps I should be more optimistic here).
