### ISSUE TITLE
lint_mode "save only" missing

### ISSUE THREAD

**Issue by adamcobabe** [SublimeLinter/SublimeLinter#1222]
Not sure why "save only" lint_mode is missing in the new version. Please bring it back.

**Comment by FichteFoll** [comment]
It's right there:

https://github.com/SublimeLinter/SublimeLinter/blob/fda38b611e070f2b9dd64b804f67d719ca428593/SublimeLinter.sublime-settings#L38-L42

**Comment by gvuyk** [comment]
"load_save" != "save_only"
It was nice for reading other people's code

**Comment by braver** [comment]
Why not use “manual” for that?

**Comment by adamcobabe** [comment]
Because it's nice to be able to view other's code and not see thousands of lint issues AND not have to remember to manually lint on my own code--two birds, one stone. Good for refactoring.

**Comment by braver** [comment]
Well I can see that. Shouldn’t be hard to implement either.

**Comment by kaste** [comment]
I would like to see a change here for background mode as well and change the behavior of the BackendController.

We can have three modes (background|save|manual) plus a flag `lint_on_load(true|false)`. Basically I could set background and lint_on_load to false for navigating through a code base, and linting would begin when I begin to write code. 

Also to change: we hit on save in background mode which is not necessary.

```
	on_activated => skip if lint_on_load == false or lint_mode == manual
    on_save => skip if lint_mode != save
    on_modified => skip if lint_mode != background
```

This becomes a bit more complicated for

- when saving a project file fire `config_changed` event
- on_activate check if the syntax changed. For convenience we hit here bc there is a good chance that the assigned linters changed as well

Notable: if the config changes, we currently hit every view regardless of the lint_mode
