### ISSUE TITLE
gutter theme not working on latest version

### ISSUE THREAD

**Issue by eswizardry** [SublimeLinter/SublimeLinter#1224]
Since last week, I got SublimeLinter updated I find some setting syntax has changed.
So, I have to copy new syntax from default and create a new user setting.

Other settings seem to work fine except "gutter_theme".
I change to all theme but gutter still uses the default theme.
A small circle with white color on a gutter.

`"gutter_theme": "Blueberry Round",`

**Comment by braver** [comment]
If you want to use another gutter theme, you have to update your styles to use the correct icons (“warning” and “error” usually)

**Comment by eswizardry** [comment]
Thank you for the suggestion. Now it's work fine.
Closing issue.
