### ISSUE TITLE
bring `show_errors_on_save` back to SL 4

### ISSUE THREAD

**Issue by ppuschmann** [SublimeLinter/SublimeLinter#1225]
I've been using SL3 a lot and especially liked the feature `show_errors_on_save` a lot,
where I got this "annoying" drop-down field when there was a listing-error in the file at save.

Is there any chance to get this functionality back?

My motivation:
To get a big visual bell at saving files with the ability to directly jump to the erroneous line.
(e.g. duplicate keys in YAML-files, ...)

To show some gutter-information and status-bar information is quite good,
but the "drop-down" was ideal for me.

To use <ctrl>+<cmd>+<a> is one option, but this isn't fired at save.

**Comment by braver** [comment]
4.1.1 already has this, look for the `show_panel_on_save` setting. We're even making it more better: #1221
