### ISSUE TITLE
TypeError: 'NoneType' object is not iterable for mdl linter

### ISSUE THREAD

**Issue by fmasuhr** [SublimeLinter/SublimeLinter#1229]
I am getting a similar bug as in https://github.com/SublimeLinter/SublimeLinter/issues/1207 which should be solved by version SL 4.1.1. But I am still getting it with the new SL version and the [mdl](https://github.com/roadhump/SublimeLinter-contrib-mdl) linter:

```
SublimeLinter: SublimeLinter.sublime-package:71: Logging installed; log level INFO
SublimeLinter: SublimeLinter.sublime-package:62: debug mode: on
SublimeLinter: SublimeLinter.sublime-package:63: version: 4.1.1
SublimeLinter: SublimeLinter.sublime-package:292: detected syntax: markdown
SublimeLinter: #1 SublimeLinter.sublime-package:747: 'mdl' is linting 'README.md'
SublimeLinter: #1 __init__.py:1273: ERROR: Linter crashed.

Traceback (most recent call last):
  File "lint.backend in /Users/fmasuhr/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 97, in execute_lint_task
  File "lint.linter in /Users/fmasuhr/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 759, in lint
  File "lint.linter in /Users/fmasuhr/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 469, in get_cmd
TypeError: 'NoneType' object is not iterable
```

As the mdl linter is still using the deprecated `executable_path` it is using the not iterable `NoneType` here. It is already failing some lines before the introduced fix in PR #1209.

**Comment by kaste** [comment]
Hm, that linter is unmaintained. (@braver opened an issue there a few months ago without a response.) So, the fix is easy. But if I open a PR, it doesn't help if nobody merges.

**Comment by braver** [comment]
Hmm, @fmasuhr please give the maintainers a notice and if they don’t respond we’ll take over the plugin.

**Comment by braver** [comment]
Opened an issue wrt transfer https://github.com/roadhump/SublimeLinter-contrib-mdl/issues/3

**Comment by fmasuhr** [comment]
@braver Thank you for taking care of that! I hope you can take over the plugin

**Comment by kaste** [comment]
Fix is in #1241

**Comment by fmasuhr** [comment]
@kaste Thanks a lot for the fast implementation here

**Comment by ChainsawBaby** [comment]
I get this error in a few other linter as well, like scss, mdl and php.
attenzione/SublimeLinter-scss-lint#50

**Comment by kaste** [comment]
`scss` plugin does not use the deprecated `executable`/`executable_path` setting. So it is not affected here. I tested mdl and php with this patch. 🤞 (Though php was working before via a wrong hotfix.)

**Comment by braver** [comment]
FYI the plugin has been assimilated and updated.

**Comment by fmasuhr** [comment]
@braver Thanks a lot It works fine for me now
