### ISSUE TITLE
Feature: additional filtering in regex for certain linters

### ISSUE THREAD

**Issue by nvtkaszpir** [SublimeLinter/SublimeLinter#1238]
**Description:**
Unfortunately some linters are not processing single file, but they process input file with its dependencies.
For example ansible-lint does that. In the effect it:
- runs slower (hardly to avoid that because it is linter specific)
- returns multiple lines for processed files
I know that it should be rather handled by linter itself, but I've found some

**Actual behavior:**
As a result SublimeLinter is displaying errors/warnings in currently viewed file, even though they are caused by other files. Example output - multiple lines for all dependent files:
```text
SublimeLinter: #3420 linter.py:774: ansiblelint output:
    /home/kaszpir/vagrant/vagrant-racktables/play_sys.yml:10: [EANSIBLE0013] Use shell only when shell functionality is required
    /home/kaszpir/vagrant/vagrant-racktables/.galaxy/geerlingguy.apache/tasks/main.yml:20: [EANSIBLE0013] Use shell only when shell functionality is required
    /home/kaszpir/vagrant/vagrant-racktables/.galaxy/geerlingguy.mysql/tasks/setup-Archlinux.yml:11: [EANSIBLE0016] Tasks that run when changed should likely be handlers
    /home/kaszpir/vagrant/vagrant-racktables/.galaxy/geerlingguy.php/tasks/install-from-source.yml:95: [EANSIBLE0013] Use shell only when shell functionality is required
    /home/kaszpir/vagrant/vagrant-racktables/.galaxy/geerlingguy.php/tasks/setup-Debian.yml:22: [EANSIBLE0016] Tasks that run when changed should likely be handlers
    /home/kaszpir/vagrant/vagrant-racktables/.galaxy/yatesr.timezone/tasks/timezone.yml:2: [EANSIBLE0011] All tasks should be named
```

Screenshot with confusing linter errors - we can clearly see bizarre linting errors in lines 20,22,30:

![linter-bad-output](https://user-images.githubusercontent.com/1480252/37570365-3fd65df6-2aef-11e8-87a3-e0d8341966c3.png)

**Suggested solution:**
Add additional filter to regex matcher to filter out only relevant lines.
Or add additional checking of the file viewed within linter output.

**Expected behavior:**
Display linting errors which correspond only to specific file. Other dependent files are not present.
```text
SublimeLinter: #3420 linter.py:774: ansiblelint output:
    /home/kaszpir/vagrant/vagrant-racktables/play_sys.yml:10: [EANSIBLE0013] Use shell only when shell functionality is required
```

**Comment by kaste** [comment]
This is relatively trivial to implement in the specific linter plugin. Such a feature must be first implemented in a couple of linters before can pull it into core.

(Is ansiblelint maintained?)

**Comment by nvtkaszpir** [comment]
ansible-lint is maintained, so maybe I should report feature request there.
Right now I know I can use ``--exclude=path1 --exclude=path2`` to avoid linting stuff which come from libraries.
I'm trying to modify linter.py for that:
```json
    defaults = {
        'selector': 'source.ansible',
        'args': '--nocolor -p',
        '--exclude= +': ['.galaxy'],
    }
    inline_overrides = ['exclude']

```

... and appears it works as expected.

**Comment by nvtkaszpir** [comment]
Hm now I tink this should be done inside SublimeLinter-contrib-ansible - just to parse output to match currently viewed file.

**Comment by nvtkaszpir** [comment]
Got it working with overriding find_error() method, but looks like the way ansible-lint \ is not working well with nested dependencies, because it currently processes playbooks only.

Would need extra logic to detect if given ansible role is included in playbooks in the directories above and then process those with ansible-lint and processes each output separately.

So I think this is rather linter issues, which can be solved with adjusting linter executable or sublime-linter-pluginname, without touching SublimeLinter itself.

So the choice is between:
- leave it as is, so that custom plugins additionally process output
- extend SublimeLinter core package to allow additional capture groups in regex matchers (we got error/message/code/line and so on, so maybe add additional ones like folder, file_path, filename, etc?)

**Comment by FichteFoll** [comment]
This is a pretty easy decision. If it's just for one linter, it should obviously go into that linter's plugin.

Only once multiple linters start having these demands, it might make sense to include in the core.

**Comment by braver** [comment]
> leave it as is, so that custom plugins additionally process output

Yes, that’s the best approach. Our default behavior can be extended exactly for that reason. If this were a very common situation or it couldn’t be dealt with in the plugin, that might open it up for a change in core.

**Comment by kaste** [comment]
Push your recent code to the PR so I can have a look.

**Comment by nvtkaszpir** [comment]
I think the best idea would be actually detect if the ansible playbook is opened, then run linter for that and apply linting results to other opened windows.

**Comment by kaste** [comment]
That would be interesting, but you need some python skills here, really.

**Comment by kaste** [comment]
Instead of `find_errors` it is possible enough to define the regex so that you capture the filename. In `split_match`, you can then look at `match.group('filename')` and if it doesn't match `self.view.file_name()` you just return None for that match/line to skip it. 😏

**Comment by nvtkaszpir** [comment]
https://github.com/nvtkaszpir/SublimeLinter-contrib-ansible-lint/blob/sublimelinter4-filter-view/linter.py something like this. But still I think it needs much more code to properly handle pretty limited ansible-lint (due the way it was designed to be used).

Instead, trying with ansible-review, and it looks much more promising. https://github.com/nvtkaszpir/SublimeLinter-contrib-ansible-review

**Comment by kaste** [comment]
Okay, `find_errors` is not that bad here. Note that `version_*` and `inline_overrides` are deprecated and non-functional.
