### ISSUE TITLE
Ignore specific warnings

### ISSUE THREAD

**Issue by displayadrian** [SublimeLinter/SublimeLinter#1244]
Please could someone offer some advice on settings to ignore specific warnings?

I used ignore_match previously but that has now been done away with.

I am trying to pass the errors as arguments instead but my attempts are disabling the linter altogether.

Example:

```
// SublimeLinter Settings - User
{
  "linters": {
    "htmltidy": {
      "args": [
        "--ignore", "unescaped & or unknown entity \"&utm_source\""
      ]
    }
  }
}
```

Thanks in advance

**Comment by braver** [comment]
SublimeLinter and its plugins just interface with the underlying linter executable. If you want to configure your linter, that's where you should look. Some take configuration files, some command line "args", some both. What do the docs of htmltidy tell you here?

**Comment by displayadrian** [comment]
Thanks for your response. I've tried to configure this from the htmltidy side but I'm none the wiser after reading its documentation.

**Comment by kaste** [comment]
So, we discussed this at (some) length. `html-tidy` is almost a validator. It is too strict and you cannot configure it properly. 

This is trivial to fix in the linter plugin. PRs welcome.
