### ISSUE TITLE
Heavy CPU usage and spikes with pylint after migrating to v4

### ISSUE THREAD

**Issue by kiddick** [SublimeLinter/SublimeLinter#1251]
In average `top` shows about  6-8 `pylint` processes which heavy loads CPU
My config
```
{
    "SublimeLinter": {
        "@python": 3,
        "linters": {
            "pep8": {
                "disable": true,
                "max-line-length": 120
            },
            "pycodestyle": {
                "disable": true
            },
            "pyflakes": {
                "disable": true
            },
            "pylint": {
                "args": [
                    "--disable=C0103, C0111, R0903, R0901, R0913",
                    "--max-line-length=120",
                    "--generated-members=__table__,db.*,conf.*",
                    "--jobs=4"
                ],
                "disable": false,
                "enable": "",
                "excludes": [],
                "jobs": 4,
                "rcfile": "",
                "show-codes": true
            }
        }
    }
}
```

**Comment by kaste** [comment]
Please try #1234 and #1250

**Comment by kaste** [comment]
How long does one `pylint` call take? What's your debounce delay? (If testing #1234 do not set a delay.)

**Comment by kiddick** [comment]
Hm.. I've launched same command from console.. and one pylint call tooks really long about 5-10 secs.. Seems it is due to I have a lot of custom paths from buildout, so it goes to `--init-hook="import sys;sys.path.append()` with injecting about 70 paths with eggs..

Pure call w/o appending a lot of patch tooks less 1 sec..

**Comment by kiddick** [comment]
But on the other hand same behavior was ok with 3rd verson of SL

**Comment by kaste** [comment]
Haha, yeah sure, in SL3 processing was strictly sequential.

**Comment by braver** [comment]
> 5-10 secs

Perhaps "load_save" mode is a better idea here unless you like your laptops hot.

**Comment by kaste** [comment]
Seriously, a working #1250 will help you. So help us and check it out.

**Comment by kaste** [comment]
Tracked in #1201
