### ISSUE TITLE
Automatically hide panel when no errors

### ISSUE THREAD

**Issue by Sembiance** [SublimeLinter/SublimeLinter#1258]
I'm currently using `"show_panel_on_save" : "view"` and `"lint_mode" : "load_save"`, which works great, showing the panel when there are errors when I save.

After I fix the errors though, the panel remains with just a message `"No lint results."`

I then have to press 'Escape' to remove the panel.

It would be great to introduce an option `"hide_panel_on_no_errors" : true` that would automatically hide the panel when the errors are resolved.

**Comment by kaste** [comment]
Maybe without the option: When 'we' (instead of the user) opened the panel, then close it automatically if no errors left. If the user opened the panel, do not touch it.

**Comment by PombaM** [comment]
Would greatly appreciate this feature!
