### ISSUE TITLE
Sublime tex 3

### ISSUE THREAD

**Issue by Duytd8698** [SublimeLinter/SublimeLinter#1259]
i have an error while install SublimeLinter: 
Invalid settings in 'Packages/User/SublimeLinter.sublime-settings':
Additional properties are not allowed ('mark_style' was unexpected)
my setting user:
{
"lint_mode": "background",
    "linters": {
        "csslint": {
            "@disable": false,
            "args": [],
            "errors": "",
            "excludes": [],
            "ignore": "",
            "warnings": ""
        },
        "htmltidy": {
            "@disable": false,
            "args": [],
            "excludes": []
        },
        "jshint": {
            "@disable": false,
            "args": [],
            "excludes": []
        },
        "php": {
            "@disable": false,
            "args": [],
            "excludes": []
        },
        "phplint": {
            "@disable": false,
            "args": [],
            "excludes": []
        }
    },
    "mark_style": "outline",
}

**Comment by braver** [comment]
Your settings are incorrect for SublimeLinter 4. When you open your settings, the default settings in the left half of you screen will show you lots of examples. You can also find some documentation in this repo and on sublimelinter.com
