### ISSUE TITLE
Line Hover issue

### ISSUE THREAD

**Issue by Resike** [SublimeLinter/SublimeLinter#1268]
I have gutter "icon": "none", set for my warnings, however entering the region still shows the line report about it (show_hover_line_report = true), while i think it should only do that when the gutter icon is visible aka not set to "none".

**Comment by braver** [comment]
I get your point, however... The styles settings only affect the visualization, not the underlying data. If there are problems on a line, the line report can tell you so, regardless of whether you’ve visually hidden some of them. It’s a feature, not a bug, and can be quite useful like that. If a linter reports problems you don’t want to know about, the styles settings aren’t the right thing to configure.

**Comment by kaste** [comment]
Huh? The 'hover ux' is generally that you have a visual artifact and then you expect a tooltip to be shown when you hover over that element. 

You cannot hover over nothing and then some popup pops up. Of course, the `highlights_view` must share state with the `tooltip/hover_view` bc both most work hand-in-hand. (It is just that in our implementation they are completely separate things.)

**Comment by braver** [comment]
You hover over the line number. 🤷🏼‍♂️

I get the point, but there is something to be said for the current solution too (not having the icon, but still being able to get the tooltip) and I don’t want to complicate this. Perhaps a year from now with more experience and more feedback, but definitely not right now.

**Comment by braver** [comment]
We can leave it open as a discussion towards “enhancement”, but that usually doesn’t yield much insight.

**Comment by Resike** [comment]
// Show a report for problems on a line by hovering over the gutter.

This will just make me want to disable this setting instead.

**Comment by braver** [comment]
If you’re using the style settings as a filter for what problems to deal with or not, that’s not what it’s designed to do. See #1255

**Comment by Resike** [comment]
Why would i do that?

I have a custom linter that only shows one and one warning type. You can guess that i don't want to see whats is this warning about every time i hover on a not-even visible region. While i still prefer to see syntax error messages.

It doesn't really matter since i hacked it to work for my way.

**Comment by Resike** [comment]
I mean it's up to you how would you prefer to handle this, but i don't see an issue about supporting both versions.

**Comment by kaste** [comment]
I don't think a fight is right here. And honestly, @braver I think you're wrong here. I saw this issue yesterday popping up, and actually was in the middle of solving it before this 'discussion' here started. 

E.g. if you have a 'quiet view' t.i. without any highlighted regions you clearly don't expect tooltips to pop up somewhere. 

So I have it already ready and will PR now. Took 20 minutes not a year.

**Comment by braver** [comment]
@kaste for the UX to make sense ALL views have to share state with the highlighting. We need to have strong vision here, not just one or two complaints.

**Comment by kaste** [comment]
That's just not true imo. Here the UX is not about error filtering. It is a mouse interaction.

On a webapp, you have to visually indicate what a link is. You cannot click on some word and get to a different website. And you clearly don't expect a tooltip. Look at this site here (GitHub), you clearly see where a tooltip might pop up.

**Comment by braver** [comment]
I guess all I’m saying is I need to see a good PR (which I’m sure you’re capable of) and I need time to test it against ideas I have about this. I haven’t had time to really appreciate SL in its current state and I don’t want everyone to attack perceived issues left and right without me being able to guard the design.
