### ISSUE TITLE
Can't stop jshint from linting alongside eslint

### ISSUE THREAD

**Issue by shamilovtim** [SublimeLinter/SublimeLinter#1270]
I am trying to use eslint with react-native / es7 and cannot disable jshint. I've tried uninstalling jslint and as far as I can tell there is no separate plugin called jshint. 

![screen shot 2018-03-24 at 4 37 29 pm](https://user-images.githubusercontent.com/3495974/37868740-d17f9a2e-2f81-11e8-9cce-5c3d6f0091a1.png)

**Comment by shamilovtim** [comment]
The only solution I've found thus far is to put // jshint ignore: start at the top of every file. Is there a way to expand this to all of sublime rather than needing to put it at the top of my js files?

**Comment by kaste** [comment]
If you uninstall a SublimeLinter plugin you must restart Sublime for now. 😞 

But a proper 

```
"linters": {
     "jshint": {
         "disable": true,
```

will do the job. And then you can enable it per project. 👍

**Comment by shamilovtim** [comment]
great advice. thanks!

**Comment by MaxiSantos** [comment]
I've also disable jshint following this
[http://www.sublimelinter.com/en/stable/settings.html](http://www.sublimelinter.com/en/stable/settings.html)

`"SublimeLinter.linters.jshint.disable": true`
