### ISSUE TITLE
file only linters loose errors as soon as you edit again

### ISSUE THREAD

**Issue by kaste** [SublimeLinter/SublimeLinter#1272]

**Comment by braver** [comment]
That is by design originally. Not saying it's good, just saying there was an idea behind it.

**Comment by kaste** [comment]
Hm, don't get it. Why?

**Comment by braver** [comment]
I guess that as you’re editing the highlights don’t update, even though the problem may have already been solved. I’m not sure what happens with the regions, how they move around while editing... may end up being quite confusing.

That said, I disagree with a lot of the design of SL3, so 🤷🏼‍♂️

**Comment by kaste** [comment]
The regions are okay, the other views (status bar message under cursor, panel view) do not 'sync'. But that's just as in '[load_]save' mode.
