### ISSUE TITLE
PHP Linter Problem in 4.2.0 (WIN)

### ISSUE THREAD

**Issue by solariz** [SublimeLinter/SublimeLinter#1277]
Hey,

I just updated from prev. 3.x to 4.2 unfortunately PHP Linter seems to have some trouble running.
As soon as I save a PHP File I get the error msg popup 

> "php is not recognized as an internal or external command, operable program or bach file."

php.exe is already in the windows enviroment PATH, verified working. 

Looking into debug output it actually seems to find it and execute php but looks like the php output is unexpected.

```
SublimeLinter: SublimeLinter.sublime-package:75: Logging installed; log level INFO
SublimeLinter: SublimeLinter.sublime-package:65: debug mode: on
SublimeLinter: SublimeLinter.sublime-package:66: version: 4.2.0
SublimeLinter: SublimeLinter.sublime-package:319: detected syntax: php
SublimeLinter: #1 SublimeLinter.sublime-package:746: 'php' is linting 'create_blacklist.php'
SublimeLinter: #1 SublimeLinter.sublime-package:337: 'executable_path' has been deprecated. Just use an ordinary binary name instead. 
SublimeLinter: #1 SublimeLinter.sublime-package:539: php: wanted executable is 'C:\utils\PHP7\php.exe'
SublimeLinter: #1 SublimeLinter.sublime-package:1044: php: create_blacklist.php ['C:\\utils\\PHP7\\php.exe', '-l', '-n', '-d', 'display_errors=On', '-d', 'log_errors=Off']
SublimeLinter: #1 SublimeLinter.sublime-package:1047: php: cwd: C:\Users\mg\Documents\MobaXterm\slash\RemoteFiles\133444_4_10
SublimeLinter: #1 SublimeLinter.sublime-package:773: php output:
    No syntax errors detected in -
SublimeLinter: #1 SublimeLinter.sublime-package:814: php: No match for line: 'No syntax errors detected in -'
```

I'm using windows PHP:

> PHP 7.0.10 (cli) (built: Aug 18 2016 09:48:53) ( ZTS )
> Copyright (c) 1997-2016 The PHP Group
> Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies

this is my simple Config:

```
{
  "debug": true,
  "linters": {
      "php":
      {
          "executable": "C:\\utils\\PHP7\\php.exe"
      },
  }
}

```

Thanks for any hints what Im doing wrong.

**Comment by solariz** [comment]
i just upgrade PHP7 to the latest Version:

> PHP 7.2.3 (cli) (built: Feb 28 2018 05:48:02) ( NTS MSVC15 (Visual C++ 2017) x64 )
> Copyright (c) 1997-2018 The PHP Group
> Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies

but Error is still there, a bit different but still same effect:

```
SublimeLinter: #6 SublimeLinter.sublime-package:773: php output:
    No syntax errors detected in Standard input code
SublimeLinter: #6 SublimeLinter.sublime-package:814: php: No match for line: 'No syntax errors detected in Standard input code'
```

**Comment by kaste** [comment]
Here the log output tells you that you have no lint errors/problems in your buffer. So you're actually green.

**Comment by solariz** [comment]
you are right, I found the Problem causing this popup message was not caused by sublime linter. Sublime3 had a plugin "PHP Syntax Checker" enabled, wherever this came from. This conflicted with linter and cause this funny behavior.

Another Notice to all whoever encounter those Problems:
If you add PHP to your win10 Enviroment PATH; It will only be active globally for other apps (excluded cmd shell) after you relogin your user. So after changing PATH in order to have sublime the newest PATH Info best is to reboot / logout-in.


Now it's working.  

thanks,
closed
