### ISSUE TITLE
Don't check single files more than once per time

### ISSUE THREAD

**Issue by SDemonUA** [SublimeLinter/SublimeLinter#1285]
Hello, I often work on a file openned in several buffers (side by side edit). And I noticed that when I save file it spawns two linters - one per buffer. But it is all the same file (and often this file is REALLY big). This leads to huge CPU usage and as results lags and noise from coolers.

**Comment by kaste** [comment]
Thanks for reporting!

Sublime generally fires the events per buffer, and currently `debounce` only in `background` mode. Probably a min debouce time of say 1ms should be enough.

**Comment by SDemonUA** [comment]
Well, I use `load_save` cuz `background` was like pain&suffer on files over 10k lines. I would be happy to have smaller files, but I can't.

**Comment by kaste** [comment]
Which linters are you using?

**Comment by SDemonUA** [comment]
Basically it is jshint. But my my active is jshint, tslint, perl (perl -c), csslint

**Comment by kaste** [comment]
Would like to fix after #1234 bc it has a useful refactoring about the debounce delay.
