### ISSUE TITLE
Deprecate and remove magic appending the filename or tempfile name to `cmd`

### ISSUE THREAD

**Issue by kaste** [SublimeLinter/SublimeLinter#1290]
If `code` is None (which means we want to lint an actual file, the original or a temp file) SL3 magix append the filename to `cmd` (if there is nor marker for it). 

https://github.com/SublimeLinter/SublimeLinter/blob/6d07b3653b14deadb824ecbb48c03ee9bacb3d1b/lint/linter.py#L1072-L1077

And

https://github.com/SublimeLinter/SublimeLinter/blob/6d07b3653b14deadb824ecbb48c03ee9bacb3d1b/lint/util.py#L307-L312

We want explicit behavior.

**Comment by kaste** [comment]
So basically we must find the linters where `temfile_suffix` is set and add `${file}` to cmd if it is '-', otherwise we must add `${temp_file}`

**Comment by kaste** [comment]
We must first agree on the name here. But 'file_on_disk' is a good one.

Note, for gotype the cmd would be `gotype -e -t .` and then `is_file_only_linter = lambda: True`

**Comment by braver** [comment]
You know, we could go around all contrib plugins and ask if they want to transfer. So far everyone is happy to have someone else maintain their thing, or it’s unmaintained and we can just move it. I don’t see why anyone would want a plugin that’s not part of the org, and it would allow us to refactor where we want.

**Comment by kaste** [comment]
And, no, I don't *want* more linters in the org. I want more contributors.

**Comment by braver** [comment]
I want more linters in the org and then also more contributors 😉 . The reality of all open source "communities" however, is that the number of actual contributors is two orders of magnitude smaller than the open source evangelists think.

**Comment by braver** [comment]
Ha, SL2 *was* a monorepo :)
