### ISSUE TITLE
gutter icons "protected regions" don't always work

### ISSUE THREAD

**Issue by braver** [SublimeLinter/SublimeLinter#1302]
Perhaps since recent work on master. 

<img width="245" alt="screen shot 2018-04-09 at 20 55 20" src="https://user-images.githubusercontent.com/2543659/38516862-79e332ee-3c38-11e8-9ed3-1749b1873cbe.png">

They do sometimes show, and it feels like a race condition somewhere.

Also, sometimes I can get the line report tooltip even if the icon is hidden by GitGutter, and sometimes I can't get the line report tooltip no matter what. The inline tooltip for regions is more reliable however.

![tooltips](https://user-images.githubusercontent.com/2543659/38517220-81970ca8-3c39-11e8-8748-20fa3dac08b5.gif)

**Comment by kaste** [comment]
👍

**Comment by kaste** [comment]
Why do you have all htmltidy errors on the last char of the line? 

I have

![image](https://user-images.githubusercontent.com/8558/38575470-c48fe0da-3cfb-11e8-974c-1dc74ddc3a0a.png)

![image](https://user-images.githubusercontent.com/8558/38575485-d40826e4-3cfb-11e8-88ea-eae7d8087c41.png)

**Comment by kaste** [comment]
Ah, you mark the newline char. That's probably not even ws at the end of the line.

**Comment by braver** [comment]
<img width="401" alt="screen shot 2018-04-10 at 21 00 37" src="https://user-images.githubusercontent.com/2543659/38577798-3c06a198-3d02-11e8-925e-86ffb6c354c1.png">

Yes, it's marking the newline char.

**Comment by kaste** [comment]
But why?

**Comment by kaste** [comment]
Hm, but what's wrong with your htmltidy? It squiggles 'uthor' LOL

**Comment by braver** [comment]
LOL, I dunno man, it's just this: https://github.com/SublimeLinter/SublimeLinter-html-tidy/blob/master/linter.py. Tweaking the line_col_base doesn't seem to help.
