### ISSUE TITLE
If you close the 'initial' view into a buffer, `linter.view` becomes invalid state

### ISSUE THREAD

**Issue by kaste** [SublimeLinter/SublimeLinter#1308]
Super 🐛 

Repro

- Open first view into file
- Lint
- Open second view into file
- Lint
- Close *first* view
- Switch to second view
- Lint

In the debug you should see something like this 

![image](https://user-images.githubusercontent.com/8558/38560751-a2829732-3cd6-11e8-9514-92a9295d4611.png)

T.i. `view.file_name() == None; view.buffer_id() == 0`

**Comment by kaste** [comment]
Also:

![image](https://user-images.githubusercontent.com/8558/38560859-e77ebfdc-3cd6-11e8-84b7-2821177a0d57.png)

Buffer as seen from the event `188`

**Comment by kaste** [comment]
This is a disaster bug, and I will first provide a hotfix/patch.

**Comment by braver** [comment]
Wow, on my system this just crashes ST.

**Comment by kaste** [comment]
(Yeah, but this is only in master afaik.)
