### ISSUE TITLE
Optimimize what to do when `config_changes` fires

### ISSUE THREAD

**Issue by kaste** [SublimeLinter/SublimeLinter#1312]
Just linting all views makes me want to not change the settings bc it makes my fan sing. I know we inherited this, but if we write down what we actually want to achieve we probably can code it (more efficient).

```
if `gutter_theme, highlights.*, show_marks_in_minimap, styles` change => redraw highlights
if `linters, no_column_highlights_line` changes => re-lint
otherwise => do_nothing
```

- [ ] If the project file config triggers it is enough to only re-lint views from the current related window.  
- [ ] `lint_all_views` is completely misnamed bc it doesn't do that, although an actual command to lint all view (of the current window) would be probably nice.

**Comment by FichteFoll** [comment]
Well, the settings affect a lot of aspects of SL wrt highlighting, linter settings, etc., so just re-running all linters is definitely the easiest way to pick up those changes.

**Comment by braver** [comment]
Exactly. You may have changed the styles, or the rules (excludes, args, etc) with which the linters run. Especially if you’re running file-only linters, their reports probably don’t match your settings anymore. You could try to interpret the impact of each setting individually and update the state accordingly, or you simply tear down and rebuild the state. 

User stories:

- I lint a file, get red highlights.
- Change the style to blue.
- Switch back to the file and I expect the highlights to be blue.

- I lint a file with some args.
- Change the args in settings.
- Get some coffee, talk to a colleague.
- Get back to the file, and want to be sure the way it was linted matches the current settings.

The assumption is that there is no need to be efficient/performant here usually, except perhaps if you have lots of files open and you don’t want your laptop to heat up. Another assumption is that you set your settings, perhaps tweak it later, and you’re done with them. Unless you’re a SL dev and are testing various settings, and have way too many linters installed, of course. 😉

**Comment by kaste** [comment]
Hm, 

```
if `gutter_theme, show_marks_in_minimap, styles` change => redraw highlights
if `linters, no_column_highlights_line` changes => re-lint
otherwise => do_nothing
```

Of course it is relatively likely that I change the project linter settings `args, executable`. I don't know if these settings can be observed at all, but of course we do nothing here. So the user usually does the `<space>,<backwards>`-is-it-working dance.

**Comment by kaste** [comment]
EDIT: we already do a lint all when a project file changes.

**Comment by braver** [comment]
@kaste can you phrase this issue in a way that’s actionable, or is there more you’d like to discuss?

**Comment by kaste** [comment]
Updated issue but unassigned. This is still 'low impact'.
