### ISSUE TITLE
Using htmltidy with gjslint - WARNING: {} deactivated, cannot locate \'{}\'

### ISSUE THREAD

**Issue by markwylde** [SublimeLinter/SublimeLinter#132]
I've been trying to resolve this all day but haven't a really weird problem. I have a web application that has both HTML and JS files in the same project. I am using the Linter htmltidy and Linter gjslint plugins.

When I open sublime which remembers an HTML file opened from last time, the htmltidy works perfectly and tells me the errors in the HTML file.

When I open sublime which remembers a JS file opened from last time, the gjslint works perfectly and tells me the errors in the JS file.

The problem is now if sublime remembers an HTML file being opened, and then I open in a new tab or close the current tab and open a new tab/window, the JS won't parse and gives the error below. The same thing happens if I start on a JS file and move to an HTML.

It basically looks like the linter is working for the first type of file I open (html for example), but then as soon as I move to another type of file (js for example) it fails.

The error message I'm getting in the console when trying to Link an HTML file is:

```
The error message I'm getting in the console when trying to Link an HTML file is:
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 303, in on_activated
    callback.on_activated(v)
  File "/Users/markwylde/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/sublimelinter.py", line 282, in on_activated
    self.check_syntax(view)
  File "/Users/markwylde/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/sublimelinter.py", line 209, in check_syntax
    Linter.assign(view, reset=True)
  File "/Users/markwylde/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/linter.py", line 723, in assign
    if not linter_class.disabled and linter_class.can_lint(syntax):
  File "X/functools.py", line 233, in wrapper
  File "/Users/markwylde/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/linter.py", line 1492, in can_lint
    status = 'WARNING: {} deactivated, cannot locate \'{}\''.format(cls.name, executable)
UnboundLocalError: local variable 'executable' referenced before assignment
```

I should probably add I'm using Mac OSX Yosemite and Sublime Text 3.

Thanks for any help you can give me.

**Comment by Startouf** [comment]
I do have the same problem under windows. I only have SublimeLinter-jshint however.

Other plugins installed

BracketHighlighter
GitGutter-Edge
Sass
SublimeLinter
SublimeLinter -php, -ruby, -rubocop,

**Comment by bmix** [comment]
Windows 7 x64 Home Premium
SublimeText3 build 3083
default Python: ActivePython 2.7.6.9
Python3: ActivePython 3.4.1.0
No additional linter arguments configured.

I also have this error-message. Though, I see no pattern, yet.

SublimeLinter was working fine since I first installed it, using html-tidy, xmllint and jslint add-ins. Then, after I installed a few new Sublime packages, linting stopped. I realized, that SublimeLinter reported, it could not find the linter executables, though it did so before. So I de-installed linter add-ins, SublimeLinter and re-installed all of these. Still, it would not find the linter executable, which, however, was clearly in my path. (I use Cygwin on Windows 7). I checked both with `where tidy` (result: `C:\Cygwin\bin\tidy.exe`) and `which tidy` (result: `/usr/bin/tidy`). I then added the path, as recommended as last-resort by the user-guide to the SublimeLinter-Sublime.settings. This last-resort activated Tidy.exe but not the node.js linters, though, I added the paths as well (system (OS) and SublimeLinter paths). SublimeLinter still says, it can't find them. I do not understand this, since it was all working flawlessly before.

However, HTMLTidy linting was working only for so long. Suddenly this error, reported here by markwylde, started to appear.

As a reference I post all the log I have, from SublimeText3 startup till error: Note, that I have activated HTML, JS and CSS files. Also note, that I have replaced the default Javascript and CSS modes with CSS3, CSSComb and Javascript Ultimate.

The following log describes these activities:

Starting SublimeText3 with a generic plain-text pane as frontmost. Besides that it has panes opened, that contain CSS, JSON and XHTML files. I then activate (in this order) CSS, HTML and JSON.
While it still doesn't find csslint it does find Tidy, but Tidy errors out with the mentioned error. The `Could not import subprocess32 module, falling back to subprocess module` seems to stem from SublimeCondeIntel and is regarded to be a warning only, not an error by its author (see: https://github.com/SublimeCodeIntel/SublimeCodeIntel/issues/328#issuecomment-24916403)

    DPI scale: 1
    startup, version: 3083 windows x64 channel: stable
    executable: /C/Program Files/Sublime Text 3/sublime_text.exe
    working dir: /C/Program Files/Sublime Text 3
    packages path: /C/Users/bmix/AppData/Roaming/Sublime Text 3/Packages
    state path: /C/Users/bmix/AppData/Roaming/Sublime Text 3/Local
    zip path: /C/Program Files/Sublime Text 3/Packages
    zip path: /C/Users/bmix/AppData/Roaming/Sublime Text 3/Installed Packages
    ignored_packages: ["Vintage", "JavaScript", "xpath", "Markdown", "ePub", "CSS"]
    top level value must be an array
    pre session restore time: 0.213292
    startup time: 0.249292
    first paint time: 0.254292
    reloading plugin Default.block
    reloading plugin Default.comment
    reloading plugin Default.copy_path
    reloading plugin Default.delete_word
    reloading plugin Default.detect_indentation
    reloading plugin Default.duplicate_line
    reloading plugin Default.echo
    reloading plugin Default.exec
    reloading plugin Default.fold
    reloading plugin Default.font
    reloading plugin Default.goto_line
    reloading plugin Default.history_list
    reloading plugin Default.indentation
    reloading plugin Default.kill_ring
    reloading plugin Default.mark
    reloading plugin Default.new_templates
    reloading plugin Default.open_context_url
    reloading plugin Default.open_file_settings
    reloading plugin Default.open_in_browser
    reloading plugin Default.pane
    reloading plugin Default.paragraph
    reloading plugin Default.paste_from_history
    reloading plugin Default.quick_panel
    reloading plugin Default.save_on_focus_lost
    reloading plugin Default.scroll
    reloading plugin Default.set_unsaved_view_name
    reloading plugin Default.side_bar
    reloading plugin Default.sort
    reloading plugin Default.swap_line
    reloading plugin Default.switch_file
    reloading plugin Default.symbol
    reloading plugin Default.transform
    reloading plugin Default.transpose
    reloading plugin Default.trim_trailing_white_space
    reloading plugin Diff.diff
    reloading plugin HTML.encode_html_entities
    reloading plugin HTML.html_completions
    reloading plugin 0_package_control_loader.00-package_control
    reloading plugin 0_package_control_loader.02-bz2
    reloading plugin BracketHighlighter.bh_core
    reloading plugin BracketHighlighter.bh_logging
    reloading plugin BracketHighlighter.bh_plugin
    reloading plugin BracketHighlighter.bh_regions
    reloading plugin BracketHighlighter.bh_remove
    reloading plugin BracketHighlighter.bh_rules
    reloading plugin BracketHighlighter.bh_search
    reloading plugin BracketHighlighter.bh_swapping
    reloading plugin BracketHighlighter.bh_wrapping
    reloading plugin BracketHighlighter.ure
    reloading plugin Colorsublime.colorsublime-plugin
    reloading plugin CSS Primer.cssprimer
    reloading plugin CSS3.css3_completions
    reloading plugin CSS3.rgb_to_hex
    reloading plugin CSS3.validator
    reloading plugin GitGutter.git_gutter
    reloading plugin GitGutter.git_gutter_change
    reloading plugin GitGutter.git_gutter_compare
    reloading plugin GitGutter.git_gutter_events
    reloading plugin GitGutter.git_gutter_handler
    reloading plugin GitGutter.git_helper
    reloading plugin GitGutter.view_collection
    reloading plugin HTMLBeautify.HTMLBeautify
    reloading plugin JavaScript Ultimate.install
    reloading plugin JsonTree.JsonTree
    reloading plugin MarkdownEditing.bootstrap
    reloading plugin MarkdownEditing.custom_find_under_expand
    reloading plugin MarkdownEditing.distraction_free_mode
    reloading plugin MarkdownEditing.footnotes
    reloading plugin MarkdownEditing.gather_missing_links
    reloading plugin MarkdownEditing.indent_list_item
    reloading plugin MarkdownEditing.indent_list_multiitem
    reloading plugin MarkdownEditing.insert_references
    reloading plugin MarkdownEditing.jumpToMarker
    reloading plugin MarkdownEditing.lint
    reloading plugin MarkdownEditing.list_markdown_references
    reloading plugin MarkdownEditing.numbered_list
    reloading plugin MarkdownEditing.paste_as_link
    reloading plugin MarkdownEditing.paste_as_reference
    reloading plugin MarkdownEditing.quote_indenting
    reloading plugin MarkdownEditing.switch_list_bullet_type
    reloading plugin MarkdownEditing.underlined_headers
    reloading plugin Package Control.bootstrap
    reloading plugin Package Control.Package Control
    reloading plugin SideBarGit.SideBarGitCommands
    reloading plugin SideBarGit.StatusBarBranch
    reloading plugin SublimeLinter-contrib-jslint.linter
    SublimeLinter: jslint linter loaded 
    reloading plugin SublimeLinter-csslint.linter
    SublimeLinter: csslint linter loaded 
    reloading plugin SublimeLinter-html-tidy.linter
    SublimeLinter: htmltidy linter loaded 
    reloading plugin SublimeLinter-json.linter
    SublimeLinter: json linter loaded 
    reloading plugin SublimeLinter-xmllint.linter
    SublimeLinter: xmllint linter loaded 
    reloading plugin Surround.Surround
    reloading plugin VAlign.valign
    reloading plugin CSScomb.CSScomb
    reloading plugin GitSavvy.git_savvy
    reloading plugin Licence Snippets.Licence Snippets
    reloading plugin Preview.Preview
    reloading plugin SublimeCodeIntel.ordereddict
    reloading plugin SublimeCodeIntel.SublimeCodeIntel
    reloading plugin SublimeLinter.commands
    reloading plugin SublimeLinter.sublimelinter
    reloading plugin Terminal.Terminal
    plugins loaded
    SublimeLinter: debug mode: on 
    SublimeLinter: temp directory: c:\users\bmix\appdata\local\temp\SublimeLinter3-bmix 
    SublimeLinter: found existing HTML syntax, version 3 
    SublimeLinter: found existing Rails syntax, version 1 
    top level value must be an array
    Package Control: Skipping automatic upgrade, last run at 2015-04-03 17:21:51, next run at 2015-04-03 18:21:51 or after
    SublimeLinter: computed PATH from system:
    C:\Cygwin\bin
    C:\Users\bmix\AppData\Roaming\npm\node_modules
    C:\ProgramData\Oracle\Java\javapath
    C:\Program Files (x86)\ActiveState Komodo IDE 8\
    C:\Python27\
    C:\Python27\Scripts
    C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common
    C:\Program Files\Java\jdk1.7.0_45\bin
    C:\PROGRA~1\MATROX~1\System64
    C:\PROGRA~1\MATROX~1\System32
    C:\Program Files\Common Files\Microsoft Shared\Windows Live
    C:\Windows\system32
    C:\Windows
    C:\Windows\System32\Wbem
    C:\Windows\System32\WindowsPowerShell\v1.0\
    C:\Program Files (x86)\FreeArc\PowerPack\bin
    C:\Program Files (x86)\e\cmd
    C:\Program Files (x86)\QuickTime Alternative\QTSystem
    C:\Program Files (x86)\Sudowin\Clients\Console
    C:\Program Files\TortoiseSVN\bin
    C:\Program Files (x86)\Verschiedenes
    C:\Program Files\Calibre2\
    C:\Program Files\TortoiseGit\bin
    C:\Program Files\nodejs\
    C:\Program Files (x86)\Git\cmd
     
    SublimeLinter: WARNING: csslint deactivated, cannot locate 'csslint' 
    SublimeLinter: htmltidy activated: C:\Cygwin\bin\tidy.exe 
    Traceback (most recent call last):
      File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 304, in on_activated
        callback.on_activated(v)
      File "C:\Users\bmix\AppData\Roaming\Sublime Text 3\Packages\SublimeLinter\sublimelinter.py", line 282, in on_activated
        self.check_syntax(view)
      File "C:\Users\bmix\AppData\Roaming\Sublime Text 3\Packages\SublimeLinter\sublimelinter.py", line 209, in check_syntax
        Linter.assign(view, reset=True)
      File "C:\Users\bmix\AppData\Roaming\Sublime Text 3\Packages\SublimeLinter\lint\linter.py", line 723, in assign
        if not linter_class.disabled and linter_class.can_lint(syntax):
      File "./functools.py", line 251, in wrapper
      File "C:\Users\bmix\AppData\Roaming\Sublime Text 3\Packages\SublimeLinter\lint\linter.py", line 1492, in can_lint
        status = 'WARNING: {} deactivated, cannot locate \'{}\''.format(cls.name, executable)
    UnboundLocalError: local variable 'executable' referenced before assignment
    SublimeLinter: json activated: <builtin> 
    + Info: processing `JSON': please wait...
    reloading Packages/User/SublimeLinter.sublime-settings
    Could not import subprocess32 module, falling back to subprocess module
