### ISSUE TITLE
"toggle highlights" off by default

### ISSUE THREAD

**Issue by krishnaghatti** [SublimeLinter/SublimeLinter#1323]
Is there a way to keep the highlights toggle to off by default?
I have to go to the command pallet and choose the "toggle highlights" for each file opened.

<img width="1014" alt="screen shot 2018-04-18 at 1 42 09 am" src="https://user-images.githubusercontent.com/10704122/38894113-f99ca41c-42a9-11e8-8c6f-02b156e75385.png">

**Comment by braver** [comment]
Do you want to have them “off” permanently, or just by default and them switch them on when needed?

**Comment by krishnaghatti** [comment]
I want them to be off by default, but should be able to enable when required.

**Comment by middlesister** [comment]
+1

It would be great if this could be a project/user specific setting.

**Comment by kaste** [comment]
I also would like to see/test that. (I wrote the current toggler here, and it just came naturally from the code and data model we had there. I don't think a global toggler is completely naive, trivial code. But then, the code changed since then anyways. 🤷‍♀️ )

**Comment by kaste** [comment]
Okay, after looking at it it seems relatively trivial to add.

I cannot do a project wide setting bc we don't have such a layer (yet?). So it would be global switch. We also do not persist settings, so it would be a default after starting Sublime. Like `highlights.on_after_start: true|false`.

I also don't know if we need both, a toggler for views and a global toggler for the whole app. 🤷‍♂️

**Comment by kaste** [comment]
Something very similar has been implemented as a plugin https://github.com/kaste/SublimeLinter-addon-filter

Look esp. for the on/off switch at the bottom. Install via Package Control; search for SublimeLinter-addon-filter

**Comment by krishnaghatti** [comment]
@kaste Thank you for the update. I was using the plugin for a few days now. Just to clarify, the "off" part of the toggle will switch the linter off completely right?

**Comment by kaste** [comment]
The linters actually run in the background but don't produce any visual outcome when off. This is similar to the toggle highlights command and has the advantage of being very fast or immediate.

If you want to actually toggle linters, there is another plugin for that as well. Search for addon-toggler or something like that in Package Control.

**Comment by AndrewMast** [comment]
I created a pull request to allow this (#1576).
