### ISSUE TITLE
Factor out useful procedures from `reposition_match`

### ISSUE THREAD

**Issue by kaste** [SublimeLinter/SublimeLinter#1331]
Currently `reposition_match` does a lot of things in one unit. Factor out the useful procedures into `VirtualView` methods so that a user can implement our new `parse_output` and use parts of what `reposition_match` does a-la-cart. (E.g. eslint should use `parse_output` instead of a combination of `find_errors` and `reposition_match`)

**Comment by kaste** [comment]
Not really the right direction, really.

**Comment by braver** [comment]
👌🏻
