### ISSUE TITLE
Apply basic styling to message_view

### ISSUE THREAD

**Issue by kaste** [SublimeLinter/SublimeLinter#1340]
The fanciest possible styling for our error panel would be possible if we did them in Markdown, but a super simple styling that just styles the header would be IMO enough. This is so that end users see that this is not 'the console' that pops up but a stylized error message.

Our header currently looks like

```
SublimeLinter ....
==================

The content

```

So colorizing the first two lines would be dope I think.

**Comment by braver** [comment]
That’d be nifty and not probably not hard either. We just have to ship another syntax and apply it to the panel.
