### ISSUE TITLE
Linter says `(erred)` after version 4.3

### ISSUE THREAD

**Issue by MambaWong** [SublimeLinter/SublimeLinter#1348]
![qq 20180426122044](https://user-images.githubusercontent.com/16932438/39285654-4fc69d5e-494c-11e8-85e5-9a46e166a103.png)
![qq 20180426122055](https://user-images.githubusercontent.com/16932438/39285655-5106dbf2-494c-11e8-9026-65827d46f399.png)

**Comment by mfsimon** [comment]
In macOS: "cppcheck(erred), gcc(erred)". Fresh SL, ST install to no avail. SL 4.3.1, ST 3164

**Comment by kaste** [comment]
Fix for cpplint: https://github.com/SublimeLinter/SublimeLinter-cpplint/pull/14

https://github.com/SublimeLinter/SublimeLinter-cpplint/releases/tag/1.0.11

**Comment by kaste** [comment]
PR for gcc https://github.com/SublimeLinter/SublimeLinter-gcc/pull/11

**Comment by kaste** [comment]
🤞

**Comment by MambaWong** [comment]
OK, Thanks!!!

**Comment by clustfe** [comment]
Sublimelinter-phpmd not work after upgrade...ToT

`annotations(ok), php(ok), phpmd(erred)`

Sublimetext Console's said:
```
SublimeLinter: WARNING: phpmd output:
Start tag expected, '<' not found
```

**Comment by kaste** [comment]
@MambaWong 🎉 

@ariaviran This is probably unrelated to 4.3 see https://github.com/SublimeLinter/SublimeLinter-tslint/issues/32 for a solution

**Comment by kaste** [comment]
@clustfe https://github.com/SublimeLinter/SublimeLinter-phpmd/pull/16

https://github.com/SublimeLinter/SublimeLinter-phpmd/releases/tag/1.2.0

**Comment by clustfe** [comment]
Thanks!
Sublimelinter-phpmd works! :smile:

**Comment by kaste** [comment]
@clustfe 🎆

**Comment by mfsimon** [comment]
Hello Herr Kaste. 

<code>cppcheck</code> now works for me. Thank you! 

<code>gcc</code> debug:
<pre><code>Linter crashed.

Traceback (most recent call last):
  File "/Users/mfsimon/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package/lint/backend.py", line 87, in execute_lint_task
    errors = linter.lint(code, view_has_changed, settings) or []
  File "/Users/mfsimon/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package/lint/linter.py", line 713, in lint
    cmd = self.get_cmd()
  File "/Users/mfsimon/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package/lint/linter.py", line 496, in get_cmd
    cmd = cmd()
  File "/Users/mfsimon/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter-gcc.sublime-package/linter.py", line 134, in cmd
    settings = self.get_syntax_specific_settings(c_or_cpp)
  File "/Users/mfsimon/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter-gcc.sublime-package/linter.py", line 166, in get_syntax_specific_settings
    settings['include_dirs'].append(os.path.dirname(file_path))
KeyError: 'include_dirs'
</code></pre>

**Comment by kaste** [comment]
@mfsimon Please report the gcc error in their repo https://github.com/SublimeLinter/SublimeLinter-gcc/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc

Just from looking at it, it seems like an impossible state. So, maybe three times restart Sublime and 🤞 , then report over there.

**Comment by braver** [comment]
Looks like we covered this. New similar issues should probably go into the respective plugin's repo.
