### ISSUE TITLE
Regression for user args starting with `@`

### ISSUE THREAD

**Issue by kaste** [SublimeLinter/SublimeLinter#1349]
`phpmd` defines 

```
	'@rulesets:,': 'cleancode,codesize,controversial,design,naming,unusedcode'
```

Don't know if this actually worked before, but sure, I made it non-working in SL 4.3. (As always: Remove cruft you don't understand. LOL)

This is btw the same as setting

```
	'args': 'cleancode,codesize,controversial,design,naming,unusedcode'
```

**Comment by kaste** [comment]
Interesting, `args` can actually be expressed as `'@args +'` 🤔 (We currently handle it in a separate method `get_user_args`.)

**Comment by braver** [comment]
LOL, we find new nuggets every week
