### ISSUE TITLE
Status bar counters not showing when show linter is false

### ISSUE THREAD

**Issue by josezulu** [SublimeLinter/SublimeLinter#1352]
With the below setting, counters do not show at all.

`"statusbar.counters_template": "W: {} E: {}",`
`"statusbar.show_active_linters": false,`

I used to have the Errors and Warnings showing clearly visible (I don't need the name of the linter):

`E: 1 W: 4. Line 1234, Column 1`

Also, I liked it when I could place the errors first, any chance to get that back? Errors are more important than warnings, from an order point of view, like so:

`"statusbar.counters_template": "E: {error} W: {warning}",`

Maybe a silly question, but I always have hard time trying to find the version changes. Where in the code tree are they located?

**Comment by braver** [comment]
I restored the template setting so you can do `"(w:1 e:0)"` if that makes it easier to understand for you. It's a trivial thing and I'd like to keep it trivial. Some more templating features would be nice here, but it's not important enough and perhaps better served with a plugin at some point.
The old style will not return and I doubt we'll enhance this further. Although if someone makes a nice PR I'd definitely consider merging it of course, as with anything.
