### ISSUE TITLE
"disabled, not fully implemented"

### ISSUE THREAD

**Issue by eblot** [SublimeLinter/SublimeLinter#1359]
Since a couple of days (likely an automatic ST3 upgrade), I cannot get Python linters to work.

The console shows the following:

    reloading plugin SublimeLinter-contrib-clang-tidy.linter
    reloading plugin SublimeLinter-contrib-polylint.linter
    reloading plugin SublimeLinter-flake8.linter
    flake8 disabled, not fully implemented
    reloading plugin SublimeLinter-pycodestyle.linter
    pycodestyle disabled, not fully implemented
    reloading plugin SublimeLinter-pylint.linter
    pylint disabled, not fully implemented

How to troubleshoot this issue (and what does it means)? Thanks.

**Comment by kaste** [comment]
You're probably using the old SublimeLinter version<4 with new linter plugins 🤔

**Comment by eblot** [comment]
You are very right. Thanks.
