### ISSUE TITLE
Disable update message in console?

### ISSUE THREAD

**Issue by notDavid** [SublimeLinter/SublimeLinter#1367]
Hi,

too often i'm interrupted by this message in the console:

> SublimeLinter has been installed or upgraded. Please restart Sublime Text.

can it be disabled by a configuration setting?

**Comment by braver** [comment]
No, you should restart Sublime Text and then it's gone. If you do not like the automatic updates, you can [disable them](https://packagecontrol.io/docs/settings). Just remember to manually update once in a while or when you run into problems.
