### ISSUE TITLE
How to turn off the new release startup notification?

### ISSUE THREAD

**Issue by caub** [SublimeLinter/SublimeLinter#1378]
Is it possible to turn the version update message off? to avoid this prompt on every new release:

![2018-05-04-003624_1128x1004_scrot](https://user-images.githubusercontent.com/3134574/39605965-3d862366-4f33-11e8-9f1b-e7107b7f0956.png)

It's great to make releases notes, but it could be cool to be able to not be notified, if for example I use Sublime occasionally only

**Comment by braver** [comment]
That’s a package control feature, I’m not sure it has a setting to turn them off.
