### ISSUE TITLE
Could I release a linter only to people who using SL4 and how?

### ISSUE THREAD

**Issue by jfcherng** [SublimeLinter/SublimeLinter#1381]
I would love to adopt some ideas which I saw from `SublimeLinter-clang` but some of them could be SL4-only.

AFAIK, [people](https://github.com/SublimeLinter/SublimeLinter-gcc/issues/10#issuecomment-386905919) may still using SL3 for some reasons.

Is there a way to release a linter only to people who using SL4?

**Comment by braver** [comment]
We still have a VERSION you can use to switch an implementation. However, we’re removing SL3 support wherever we can find it: if people are able to manually install SL3, they’re able to manually install old versions of plugins. 

All linters are SL4-only going forward. If someone needs one of the contrib linters that aren’t upgraded yet, they can point them out to us so we can perhaps move them into the org and upgrade them. But the only way forward is forwards anyway.

**Comment by kaste** [comment]
Let's face it, how Package Control handles semversioning is just masquerade. People either freeze the package or always have the latest version, breaking or not.

**Comment by braver** [comment]
Well, semver itself is a complete masquerade anyway too 😉
