### ISSUE TITLE
SublimeText build 3170 No Sublimelinter settings

### ISSUE THREAD

**Issue by agoldh20** [SublimeLinter/SublimeLinter#1383]
I've upgraded my ST3 to build 3170 and after installed package SublimeLinter-flake8. I have no linter and no settings to turn on debug mode.

On ubuntu 16.04

**Comment by kaste** [comment]
There is always something in View > Console to look at. 😀

**Comment by agoldh20** [comment]
Great thanks! I see now I didn’t have sublimelinter, only the flake8 addon for sublime linter.  Fixed now.
