### ISSUE TITLE
pyflakes not showing all messages

### ISSUE THREAD

**Issue by vgoklani** [SublimeLinter/SublimeLinter#1384]
I can see "pyflakes(erred)" in the status bar, but don't see any updates in the main screen. This only happens sometimes, and only for certain types of errors (i.e. indentation issues). I'm using the latest version of everything, via package control. How to fix? Thanks 👍

**Comment by kaste** [comment]
Hi 👋 !

If pyflakes `(erred)` it should also log to the console. Open it via `View > Console`.

**Comment by vgoklani** [comment]
Hi - yes i see the messages in the console. But I don't see anything regarding sublimelinter, or why the messages aren't propagating to the UI. It's not practical to keep checking the console, so the question is why aren't the errors propagating to the UI?

**Comment by kaste** [comment]
Generally speaking, erred means that we have output on stderr, but that pyflakes otherwise reports lint errors on stdout. Basically this could mean, normal lint problems go to stdout, configuration errors or hard crashes go to stderr.

You maybe should turn on debug mode and look what's going on here. If you have debug off, you still should see the stderr output in the console, marked as warning.

**Comment by braver** [comment]
@kaste 

<img width="520" alt="screen shot 2018-05-11 at 11 12 45" src="https://user-images.githubusercontent.com/2543659/39916937-47cd1ae4-550c-11e8-803f-562f42bdd285.png">

So, this isn't a report of a configuration or runtime error, it's simply lint output and should be treated as such. How do I change SL-pylint for this?

**Comment by kaste** [comment]
It's pyflakes. They really use both streams for reporting see https://github.com/PyCQA/pyflakes/blob/master/pyflakes/reporter.py

Can someone reproduce an `unexpectedError` https://github.com/PyCQA/pyflakes/blob/c2742b69e4801e3fe9d15862eb720a3a1e585d6e/pyflakes/reporter.py#L28-L37

**Comment by braver** [comment]
> They really use both streams for reporting see

Indeed they do. Which probably also leads us to the correct solution for https://github.com/SublimeLinter/SublimeLinter-pyflakes/issues/10

> Can someone reproduce an unexpectedError

Nope

**Comment by kaste** [comment]
Okay, PR at https://github.com/SublimeLinter/SublimeLinter-pyflakes/pull/11
