### ISSUE TITLE
Disabling a linter via Package Control should have immediate effect

### ISSUE THREAD

**Issue by kaste** [SublimeLinter/SublimeLinter#1389]
When you disable a linter plugin you have to restart Sublime which is not really supergut.

I already have a solution for this here https://github.com/kaste/SublimeLinter-addon-toggler
see: https://github.com/kaste/SublimeLinter-addon-toggler/blob/master/package_control_listener.py

**Comment by kaste** [comment]
This saved my life today. ⚡️

**Comment by braver** [comment]
This would be super nice!

**Comment by kaste** [comment]
Ad: You can toggle debug mode, and switch lint_mode now too.

(Exploring what you can actually do with the current system.)

**Comment by braver** [comment]
@kaste since the add-on is out there, is this even something we want to do something about?

**Comment by kaste** [comment]
We just need to copy that file over here bc it is self-contained, but we've got zero reactions here so maybe nobody needs the feature and I only scratched my own itch.

**Comment by braver** [comment]
SublimeLinter isn’t the only package that needs a restart if you enable or disable it. I don’t see it as a big problem, you usually just install what you need and leave it at that. And we don’t get a lot of feedback even on features people use every day, so we may add this, it breaks at some point, and never hear about it.

If nobody responds soon I’ll close it, we can always revisit and reconsider at any point in the future.
