### ISSUE TITLE
SL no longer usable

### ISSUE THREAD

**Issue by coreyward** [SublimeLinter/SublimeLinter#1399]
Hey don't mean to abuse Issues to file a grievance, but I've had to completely disable SublimeLinter because over the last few months it's gotten progressively worse. First the feature to toggle a particular linter was removed, so I would toggle Highlights to make working somewhat sane (e.g. using SCSS with CSS Modules and React = camelCaseClassNames that the linter complains about). Most recently, though, this doesn't disable the gutter indicators, and that's been mucking with GitGutter (which is infinitely more valuable). I tried disabling linting altogether, but it appears that feature was removed as well, even using preferences. 

I don't know what's going on with dev on this project, but as the title mentions, it seems like it's completely crapped the bed and is no longer usable. 

Please do set me straight if there's something I can do to restore behavior from, say, a year ago, without ruining compatibility with the plugins. Otherwise, I'll just leave it disabled and go back to using terminal. 

Thank you!

**Comment by braver** [comment]
In general we’ve been completely rebuilding SublimeLinter. It had become unmaintainable, several features were completely broken, most features had terrible design and/or completely misunderstood the available api’s. It was basically a clusterfuck that hadn’t seen real maintenance for 4 years and had no path forward. We took a radical approach to get it moving again, but of course, every broken or insane feature it had was someone’s favorite, so we’ve had some backlash. The alternative was to do nothing, so we’ll take it. If people really can’t live with it now, GitHub holds all the old versions of SL and the plugins so you can install them manually.

> it seems like it's completely crapped the bed

People get cranky when they don’t understand things. I hope I gave you some perspective so we can talk, understand each other and not be cranky.

I love getting feedback, so let’s see what we can do here. We don’t get a lot of constructive feedback, and we really need that to improve SL. 

> First the feature to toggle a particular linter was removed

You can do this via [settings](https://github.com/SublimeLinter/SublimeLinter/blob/master/SublimeLinter.sublime-settings#L57) but not via command palette. Also, you can disable or enable linters via [ST projects](http://www.sublimelinter.com/en/stable/settings.html#project), if you haven’t always set it up correctly.

We’re looking at ways to bring the toggle back, but the old behavior was broken in several ways (although of course it worked for some people) and had to go. @kaste is already working on something and you could give that a try: https://github.com/kaste/SublimeLinter-addon-toggler

If you only want to run a linter sometimes, there is also a “manual” mode you can use.

> camelCaseClassNames that the linter complains about

What linter is that? Can’t you configure this warning?

> Most recently, though, this doesn't disable the gutter indicators

That’s correct, at least for now. We haven’t had any real feedback here, so we didn’t know if we should change it. It should be easy to take out the icons as well.

> and that's been mucking with GitGutter

Our gutter icons have always taken precedence over Gitgutter‘s, although of course before SL4 this was also mostly broken and unreliable. You’re the first to prefer to see GitGutter’s icons though, so perhaps we need a setting here.

> I tried disabling linting altogether

Unless you’ve got tons of linters installed you can simply disable each linter via settings. Or disable the packages via package control.

**Comment by kaste** [comment]
I think, the toggling problem has been solved via my plugin. I have to use it daily. But it is not as snappy as the toggle highlights command SL ships which I can use like bam bam bam. On off on off. 

Toggling a linter to on means I have to wait for the actual lint result.

I'll probably try a hack for gutter icons as well, but this would also require relinting I guess. Generally the gutter icons are not as reliable as I want them basically bc we need cooperation with all the other plugins. We only have one gutter! But there is an open issue at least for that.

**Comment by coreyward** [comment]
@braver Thanks for the additional info! I had no idea that any of these issues existed. I started using it at the advice of the broader ST3 community and had attributed quirks to my own setup being off. 

I think it would be useful if the README acknowledged or called out the current state of the project, what's going on with it, and possibly pointed to where new or uninformed users (👋 ) can learn about how to use or setup SL to work for them. 

Separately, I'd be happy to contribute some time to the project but I don't have any context for what needs work. Are there resources to ramp new devs on the project?

**Comment by braver** [comment]
We’ve had some communication ramping up to the 4.0 release, but documentation beyond what’s already on SublimeLinter.com has been on-demand. And there hasn’t been much demand. Time has been sucked up refactoring and perfecting, not so much enhancing the onboarding experience.

What setup you need depends on what plugins you’re using and they tend to have some info in their readme. E.g. most python linters are set-it-and-forget-it, but you can make your nvm/rbenv/virtual_env setup as complex as you like. Also some linters don’t even work without a config file. So it’s tough to write general howto’s about that. The questions that do come by now and then are so situational they usually don’t yield anything that could go in a doc.

So, documentation could use some work. It could see some examples, explanations of what the commands do, etc. Perhaps a 101 with some common scenarios etc.

Other issues that are easy to get into and will help get your feet wet are labeled as such: https://github.com/SublimeLinter/SublimeLinter/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22

Mostly though, we need someone who cares enough about some of the more niche feature requests and work flows to comment on the open issues and have an opinion on where they should go. I’m basically really happy with what we’ve got now and busy enough as it is, so I’m not super motivated to discuss things like “do we need a setting to toggle highlights off by default” and “whether that should also toggle the gutter icons”. I think it could be better, but those fringe areas miss focus to ever get off the ground.
