### ISSUE TITLE
user mark_style not respected

### ISSUE THREAD

**Issue by hinxx** [SublimeLinter/SublimeLinter#1400]
In latest version (installed today) on Linux Mint I can only get errors to have squiggly line, while warnings seem to remain outlined. My user settings:

```
    "styles": [
        {
            "mark_style": "squiggly_underline",
            "priority": 1,
            "scope": "region.yellowish markup.warning.sublime_linter",
            "icon": "dot",
            "types": [
                "warning"
            ]
        },
        {
            "mark_style": "squiggly_underline",
            "priority": 1,
            "scope": "region.redish markup.error.sublime_linter",
            "icon": "dot",
            "types": [
                "error"
            ]
        }
    ],

```
![screenshot_2018-05-12_14-52-43](https://user-images.githubusercontent.com/2725009/39957495-2b680466-55f4-11e8-9e41-29f64e0044df.png)

**Comment by braver** [comment]
Please see #1171

**Comment by hinxx** [comment]
Thanks, if I understand the other thread, it is not possible to have whitespace underlined at the moment..

**Comment by braver** [comment]
Exactly, that’s not possible in Sublime Text.
