### ISSUE TITLE
feature_request(statusbar): disable “sublimesyntax(ok)” from status bar

### ISSUE THREAD

**Issue by Kristinita** [SublimeLinter/SublimeLinter#1401]
### 1. Summary

It would be nice, if would be possible hide `sublimesyntax(ok)` text of [**SublimeLinter-contrib-sublime-syntax**](https://github.com/FichteFoll/SublimeLinter-contrib-sublime-syntax) from status bar.

### 2. Argumentation

I get `sublimesyntax(ok)` text in status bar, when I open [**file with any syntax**](https://github.com/FichteFoll/SublimeLinter-contrib-sublime-syntax/blob/master/linter.py#L39-L41).

![sublime-syntax](https://i.imgur.com/GoKoKoU.png)

I need this linter for my syntax tests files, but for all another files I don't need this linter and status bar text. Because of `sublimesyntax(ok)` text, I can't see [**another messages in status bar**](https://github.com/SublimeLinter/SublimeLinter/issues/563).

### 3. Examples of possible solutions

Allow linting only in files, that contains same symbols in:

1. filename
1. first line
1. file content

**Example**:

SublimeLinter-contrib-sublime-syntax will lint files, that contains:

1. `syntax_test` in filename **or**
1. `SYNTAX TEST` in first line **or**
1. `SYNTAX TEST` in content

### 4. Examples in other apps

[**ApplySyntax**](https://github.com/facelessuser/ApplySyntax) can apply syntax for files, that contains same text in:

1. [**file name**](http://facelessuser.github.io/ApplySyntax/usage/#file-path-rule)
1. [**first line**](http://facelessuser.github.io/ApplySyntax/usage/#first-line-rule)
1. [**content**](http://facelessuser.github.io/ApplySyntax/usage/#content-rule)

### 5. Do not offer

1. Yes, I know, that [**I can hide all linters from status bar**](https://github.com/SublimeLinter/SublimeLinter/issues/563#issuecomment-384982240). But I need another linters for required files. It would be nice, if would be possible hide specific linters in files, where linters not required.
1. Yes, I know, that I can disable linter (<kbd>Ctrl+Shift+P</kbd> (<kbd>⌘⇧p</kbd> for Mac) → `Package Control: Disable Package` → `SublimeLinter-contrib-sublime-syntax`). But it disables linter for all files include linter required.

Thanks.

**Comment by kaste** [comment]
braver ist correct here I think that a negative exclude should work. However, the linter plugin should probably not select all views as lintable, and then decide later during run that it's actually not applicable to this view. So an issue against the linter plugin seems to be more appropriate. As a hint, the linter can implement 'can_lint_view'. Consider making a PR over there, it's usually the fastest way to get the issue resolved.

**Comment by braver** [comment]
Now that I read into it some more @kaste is correct and there are some options here:

- change the plugin to use `can_lint_view` instead of checking eligibility in `run`
- only enable the linter when you’re actively working on syntaxes
- use projects to selectively enable the linter
