### ISSUE TITLE
Linters cannot find their binaries

### ISSUE THREAD

**Issue by slifin** [SublimeLinter/SublimeLinter#1410]
SublimeLinter: WARNING: phanlinter cannot locate 'phan_client'
SublimeLinter: WARNING: WARNING: phpcs cannot locate 'phpcs'

both binaries haven't moved since when they did work, they reside at:
```/Users/adriansmith/.composer/vendor/bin/phpcs```
and 
```/Users/adriansmith/.composer/vendor/bin/phan_client```

```/Users/adriansmith/.composer/vendor/bin exists in my $PATH in fish and bash```

**Comment by slifin** [comment]
weird it's working now with no changes

**Comment by braver** [comment]
🤷‍♂️
