### ISSUE TITLE
with demote_while_editing, highlights don't show until you change selection (after opening)

### ISSUE THREAD

**Issue by braver** [SublimeLinter/SublimeLinter#1412]
I think I'd prefer the highlights to render immediately and then go away as soon as I start typing. Right now though, it seems you need to interact with the file (e.g. move the cursor) before the highlights are rendered.

![delay](https://user-images.githubusercontent.com/2543659/40164886-0841edec-59bb-11e8-867c-2a94fc6983b3.gif)

**Comment by kaste** [comment]
While I intentionally coded it as 'opening a file is busy'. It never gets idle before you move the cursor. So marked as bug.

**Comment by braver** [comment]
Wow, "idle" is a really weird word if you look at it a long time.

It is me, or does `idle= False` mean it isn't idle? Just a few lines later you use `idle` to mean `show`.
