### ISSUE TITLE
Panel configuration: multiple outputs

### ISSUE THREAD

**Issue by jeremylan** [SublimeLinter/SublimeLinter#1413]
Hi

Thank you for this great project.

I'm using to write some React Native code, and I'm having a problem with the output panel multiple outputs.

There are two outputs in the panel:

    Output:SublimeLinter
    Output:SublimeLinter Messages

Ideally I would always like to see the error outputs in SublimeLinter only. If I switch manually to the right output, at every save the plugin will switch automatically to SublimeLinter Messages instead which is very annoying.

Is there any way to disable that particular Output only? I tried searching in the Settings and I even looked at the code in `message_view.py` but could not find anything.

Any idea?

Thanks

![screen shot 2018-05-18 at 1 52 14 pm](https://user-images.githubusercontent.com/5846306/40215342-4b9e1226-5aa3-11e8-9c27-b2d926093a8e.png)

**Comment by kaste** [comment]
Hi :wave:

Usually you shouldn't see the Message panel at all bc it opens only on unhandled errors.

In this case, eslint puts something on stderr that maybe shouldn't be there.

Please post the error message. Think about the eslint message. Is it something you can turn off via eslintrc.

**Comment by jeremylan** [comment]
Hi 

Thanks for the quick reply.

The error is created by an issue in node-fs-extra, there is a fix already merged for next version of Node:

[Pull Request](https://github.com/nodejs/node/pull/20504)

The error is:

    SublimeLinter: #167 eslint index.js ERROR:
    ========================================== 

    (node:18029) ExperimentalWarning: The fs.promises API is experimental

I understand this error will disappear when the new node is released but for my curiosity is there a way to control the output panels via SublimeLinter settings or eslintrc? 

I could not really find any documentation on this, and the SublimeText build system output documentation is not the easiest at a quick glance...

Thanks

**Comment by braver** [comment]
I think this goes into the same category as `DeprecationWarning`, and I think we suppress those.

**Comment by kaste** [comment]
Yes, must be solved in eslint repo.

**Comment by kaste** [comment]
@jeremylan If you will, you can make a PR here https://github.com/SublimeLinter/SublimeLinter-eslint

You basically add this warning here https://github.com/SublimeLinter/SublimeLinter-eslint/blob/34824ed3cc6e27b6a91b7376b717b28ccd3d3dcf/linter.py#L42-L45

**Comment by braver** [comment]
@jeremylan @kaste I'm yak shaving and waiting for builds to complete anyway: https://github.com/SublimeLinter/SublimeLinter-eslint/pull/250

**Comment by jeremylan** [comment]
Thanks I had forked and was creating a PR and saw you've already done it @braver!
I'll delete the fork now 

Thanks for the prompt resolution :)

**Comment by kaste** [comment]
Hi again. I have a question.

You have the following

> (node:18029) ExperimentalWarning: The fs.promises API is experimental

Where is that `(node:18029)` coming from? Is this number an ever changing pid (ProcessID)? I'm asking bc when we post errors on the Message panel, we post every unique error only *once* to reduce annoyingness. Obviously, if this pid changes all the time the error pops up all the time. You cannot dismiss it so to speak. 

Can this additional output configured?

**Comment by jeremylan** [comment]
Hi @kaste 

I assume that is the pid.
You can see the error description here:

https://github.com/jprichardson/node-fs-extra/pull/578#issuecomment-389058537

It's all output from the Node code I guess.

I can confirm yesterday's fix worked, I updated the eslint package and it's all working

**Comment by kaste** [comment]
@braver Do you also see this output `(node:xxx)`? I don't have it.

**Comment by braver** [comment]
@kaste my laptop’s battery died, so I can’t check until later next week...
