### ISSUE TITLE
output panel only for current view

### ISSUE THREAD

**Issue by braver** [SublimeLinter/SublimeLinter#1415]
The output panel lists all result for all files in the current window. It would be nice if you could have a panel with just the errors for the current file. 

I imagine this would be setting:

```
"show all errors per": "window" | "view"
```

**Comment by ouweiya** [comment]
+1

**Comment by ouweiya** [comment]
Is there any way to temporarily work around?
When there are ten files, the error message will become very large?

**Comment by kaste** [comment]
@ouweiya I'm not aware of any work around here. I think this really needs to be implemented, aka the hard way.

**Comment by ouweiya** [comment]
@kaste I think there is a compromise way, just clear the output records.
When I'm used to using `"lint_mode": "manual"`, it remembers the history of previous errors and can only be cleared by closing the file.
![c](https://user-images.githubusercontent.com/28357731/46008999-da2f0a00-c0f0-11e8-9855-0afa89b07cec.gif)

**Comment by kaste** [comment]
Exactly when should should we forget the old results? (This would also erase all gutter marks and code highlights btw.)

**Comment by haolly** [comment]
Or just provide some command to clear the result
