### ISSUE TITLE
Error gutter becomes to white instead of red

### ISSUE THREAD

**Issue by imageslr** [SublimeLinter/SublimeLinter#1419]
Dear Developers, I am a beginner of web development. My SublimeLinter's gutter color suddenly becomes to white instead of red as the following picture.

![image](https://user-images.githubusercontent.com/17822028/40311607-eaf15c2e-5d42-11e8-9136-37624964f29d.png)

It's inconvenient for me to capture where error happens. Could you please tell me how to fix it?

Here is my setting:

```JSON
// SublimeLinter Settings - User
{
    //"lint_mode": "load_save"
    "debug": true,
    "paths":
    {
        "linux": [],
        "osx": [
            "/usr/local/bin/"
        ],
        "windows": []
    }
}
```

And my SL version is Version 3.0, build 3143. 

Thank you all.

**Comment by braver** [comment]
There is a new version of Sublime Text out, you should upgrade to that and it should sort out your colors.

Also, I wanna know what color scheme that is 😁

**Comment by imageslr** [comment]
Thank you for your response. My editor theme is Material-Theme.sublime-theme, default.

**Comment by braver** [comment]
Thanks, let us know if version 3.1 (3176) of Sublime Text fixes your issue.

**Comment by imageslr** [comment]
Yes, It fixes my issue. Thanks.
