### ISSUE TITLE
Change linter_class.__init__ signature

### ISSUE THREAD

**Issue by kaste** [SublimeLinter/SublimeLinter#1425]
Currently the signature is `linter_class.__init__(view, syntax)`. However, `syntax` is unused and should be removed here. The new sig should be 

```
	def __init__(self, view, *, settings)
```

Since linter instances are now throw-away objects, we can inject `settings` immediately. 

PRO

- No need for `linter_context` (threadLocal) anymore.
- The settings are available as soon as we meet an instance. (Currently, the settings are only avail after the backend started `lint()`.
- settings are *consistent* for the life-time of the instance

CON

- Breaking change, although I never met a plugin overriding `__init__`

**Comment by braver** [comment]
I find these hits for seemingly overriding `init`:


```
SublimeLinter-contrib-CFLint/linter.py:
   54      }
   55  
   56:     def __init__(self, view, syntax):
   57          """Override init to dynamically set config_file."""
   58  
   59:         Linter.__init__(self, view, syntax)
   60  
   61          settings = self.get_view_settings()

sublimelinter-contrib-livecodelint/linter.py:
   42      livecodelint_path = ''
   43  
   44:     def __init__(self, view, syntax):
   45          """Initialize and load lc-community-server from settings if present."""
   46  
   47:         Linter.__init__(self, view, syntax)
   48  
   49      def run(self, cmd, code):

SublimeLinter-contrib-scalac/linter.py:
  185      """
  186  
  187:     def __init__(self, json_data):
  188          """
  189          Initialize a new Rule from the given JSON data.
```
