### ISSUE TITLE
include path to invalid property in settings validation messages

### ISSUE THREAD

**Issue by alecthomas** [SublimeLinter/SublimeLinter#1429]
SublimeLinter just upgraded and is now giving me the following completely unhelpful message:

![image](https://user-images.githubusercontent.com/41767/40505652-ebceaf44-5f62-11e8-89f2-b0b945d4cce0.png)

I have no idea what config key this is referring to, and so have no way of fixing it.

**Comment by alecthomas** [comment]
I mean, I fixed it by just nuking all the empty config entries, but I'm suggesting that the error message report the path to the invalid field.

**Comment by kaste** [comment]
And you're raight @alecthomas  PR at #1431
