### ISSUE TITLE
Add option to delay linting until tab is focused

### ISSUE THREAD

**Issue by alecthomas** [SublimeLinter/SublimeLinter#1432]
I often have 4-5 windows open, each with a number of tabs. In total I could have 20-30 files open.

When I restart Sublime, SublimeLinter will lint every view immediately. Some linters are fairly heavyweight, and this can result in my machine becoming unusable for an extended period of time.

Would it be possible to add an option to delay linting until a tab is focused for the first time?

**Comment by kaste** [comment]
Hm, at startup we only lint the visible views from the active (top-most) window. 

(Although there is a bug here, with ST 3.1 we lint the active *view* twice; bc ST 3.1 will call on_activate_async with a synthetic event.)

**Comment by alecthomas** [comment]
@kaste okay, I may have been mistaken about the other windows... I do have 8 tabs open in the front window.

The Go linters (which I wrote) can take 1-2 seconds per file, so it felt like it was doing all windows. I'll double check. But either way, is it possible to just do the currently focused tab?

**Comment by kaste** [comment]
Not the tabs, but the groups in Sublime parlance count here. So you can have 7 tabs open, but only one of them visible. Or 2 side by side.

To turn this off is not planned. We plan a different switch for lint-on-file-load. If you would set this to false, zero views gets linted on startup as well.

Also very interesting is to just persist the errors and marks in the workspace, so they are available instantly. (Only relint if the file actually changed.) But that's the future.

**Comment by braver** [comment]
@alecthomas @kaste does the current release (via #1434) address this sufficiently?

**Comment by alecthomas** [comment]
It does seem to be quite a bit improved, thanks!

**Comment by braver** [comment]
Ok, then I’ll mark this resolved. As @kaste mentioned there are plans to make some changes to lint modes that can improve this further.

**Comment by braver** [comment]
Oh, and thank for reporting and helping make SL better!
