### ISSUE TITLE
syntax_map Replacement

### ISSUE THREAD

**Issue by viluon** [SublimeLinter/SublimeLinter#1441]
Hello,

I am the maintainer of [LuaExtended](https://packagecontrol.io/packages/LuaExtended), an alternative Lua syntax definition for ST3. With the not-so-recent deprecation of `syntax_map`, it is now harder for my users to configure linting properly. I have already opened a pull request over at SublimeLinter/SublimeLinter-lua#8, but I'd like to avoid this manual change in the future.

Would it be possible to implement a selector to selector map, similar to `syntax_map`? It would definitely help my users with configuring their Lua linters to work with my package. It would be even better, of course, if my package could set these mappings automagically, and just work out of the box with any Lua linter.

**Comment by viluon** [comment]
@braver If I remember correctly, the reason why I created a new scope for LuaExtended is that if I were using `source.lua`, the original Lua snippets would merge with those specific to LuaExtended. I didn't want this, as most of the new snippets are improvements over the official ones (not extra features). I'm not aware of any solution to this problem that would let me reuse `source.lua` (feel free to educate me!).

**Comment by braver** [comment]
@viluon as your package intends to replace the default package (which provides those snippets), you could instruct users to disable that package if they don’t want the features it provides. You could even go so far as disabling it for them when users install your package.

By introducing the new scope, you break everything from syntax highlighting to linter plugins. Basically every package that wants to support lua will have to know about and explicitly support your extended version. The scopes are intended to prevent that.

Also, if you’re improving on the default lua package, why don’t you contribute to the default package? It’s open source these days, with several active maintainers helping each other, testing and reviewing. It’s an uphill battle trying be better than the default packages.
