### ISSUE TITLE
`shlex.split` is not Windows safe

### ISSUE THREAD

**Issue by kaste** [SublimeLinter/SublimeLinter#1442]
We use `shlex.split` for `cmd` and `args` if they're provided as strings. This works okay for simple stuff, but in the end it does not split confirming to Windows rules. (E.g. never split a Windows path with it bc it doesn't like `\`s.)

**Comment by braver** [comment]
At some point you have to conclude that life on Earh isn’t compatible with Windows...

**Comment by kaste** [comment]
🙄
