### ISSUE TITLE
Display all errors inline, between the code, using phantoms 

### ISSUE THREAD

**Issue by Cerberus-tm** [SublimeLinter/SublimeLinter#1443]
Is there a way to display all current error and warning texts inline, that is, either at the end of the line, or on a new line? Example:

![im](https://user-images.githubusercontent.com/4452023/40806092-f4bfc9c8-650f-11e8-9240-62d5bc72b2c9.png)

Or:

![im](https://i.imgur.com/IGrgfiv.png)

This can be really helpful when you want to see all errors at a glance, and inside the code, so you can immediately tell which error is where. This is not something you would normally want active all the time, but it can be super helpful, e.g. when you want to quickly scan a file with many warnings and errors and deal with the ones that 'matter' immediately. You won't have to hover the mouse over each one. Nor will you have to glance back and forth and scroll all the time between the code and the error window.

There used to be a [plugin ](https://github.com/alexkuz/SublimeLinter-inline-errors) that did this, but it no longer works with SL 4. And someone made a separate build of SL long ago, but that is old and probably no longer works either.

I'd like to know if something like this would be possible. If not, I'd love for this feature to be considered in the future. Or I'd love a hint as to how one could implement this (although I'm really not a programmer and I know too little about Python and the SL code).

**Comment by braver** [comment]
I think a third party add-on might be able to do this. It’s not very compatible with the “background” lint mode, but perhaps it can done on save, or on demand. I’m not against having such a feature, it has been requested before. It is tricky to implement well, but if someone wants to have a go...

**Comment by Cerberus-tm** [comment]
Exactly: on demand or on save would be perfect. Even if it doesn't work "well", it would be really nice as a special mode, something you use when you need it.

This plug-in used to work, until SL4:
https://github.com/alexkuz/SublimeLinter-inline-errors

I just have no idea how to fix or adapt this to work with SL4. Apparently, the commands went to a different place in SL4, or something.

**Comment by kaste** [comment]
Hm. I already made a plugin but it's not on GitHub yet. Can review it and decide if it's pushable.

**Comment by Cerberus-tm** [comment]
@kaste Ooh that would be great! What a happy surprise! I'd be happy to alpha-test it if needed.

**Comment by Cerberus-tm** [comment]
@kaste Hi, if you have a version that works at some alpha level, I'd love to test it. But of course I understand completely if you'd rather not have that or if you have other things on your mind, and no hurry! Just your friendly neighbourhood dog barking.

**Comment by kaste** [comment]
It's just not ready.

**Comment by Cerberus-tm** [comment]
OK, I see, thanks for your message.

**Comment by DeeeeLAN** [comment]
By chance, has this received any love in the last year?

**Comment by kaste** [comment]
Yeah some ❤️ but it always looked 🤢 . Was way too noisy. Pixels jumped. 😆

**Comment by kaste** [comment]
Closing this bc it looks like I'm in charge and this isn't very welcoming for new, potential contributors. 

Note though that this is not a technical thing. The UI/UX should have been described bc that's where the implementations usually fail. (In what I tried, it was always noisy and distracting.)

**Comment by Cerberus-tm** [comment]
@GustavoOly Thanks, that looks great! I will try and see if I can get it to work (at the moment, Package Control does not seem to be working at all in my Sublime Text, even though all the installed packages are still working, no how idea how that's possible).
