### ISSUE TITLE
Linter can't find Node after Sublime Text upgrade

### ISSUE THREAD

**Issue by tsrahm** [SublimeLinter/SublimeLinter#1444]
I've been running SublimeLinter with eslint installed locally in my project successfully for over a year. After a recent Sublime Text upgrade, I began receiving this error:
```javascript
SublimeLinter: #1 linter.py:49: ERROR: env: node: No such file or directory
```
I'm not sure that I resolved the actual cause of this error, but I did get it working again by installing eslint globally, and then using this setting:
```javascript
"linters": {
  "eslint": {
      "env": {"PATH":"/path/to/executable/"}
  }
}
```
using the path to the globally installed eslint executable.

Any idea how I can use the locally installed eslint?

**Comment by braver** [comment]
Are you using nvm? The way Sublime loads your env variables in 3.1 times is better for everyone, except those with a shell slowed down by nvm it seems... You should be able to patch PATH as you’re doing to help it find node. I think that should also still allow it to use the locally installed eslint, but I don’t know the nitty gritty of it.

**Comment by braver** [comment]
You may want to have a look at this issue:  https://github.com/SublimeLinter/SublimeLinter/issues/1118#issuecomment-393030063, more people are having trouble setting it up with nvm.

**Comment by kaste** [comment]
You basically need to know which node for that particular local eslint.

**Comment by tsrahm** [comment]
Ok, well, it seems my solution is the right one for this issue.
Thanks

**Comment by tsrahm** [comment]
Thanks for your quick response @braver and @kaste!
