### ISSUE TITLE
Use standard view settings where appropriate

### ISSUE THREAD

**Issue by zx8** [SublimeLinter/SublimeLinter#1446]
The [docs](http://www.sublimelinter.com/en/stable/settings.html#settings-stack) state:

> SublimeLinter merges settings from several sources to calculate the value. Settings are merged in the following order:
> 1. Default settings
> 2. User settings
> 3. Project settings (only “linters” settings)

Would it be possible to include "syntax-specific" settings between User settings and Project settings?

My use case is the following:
- I'm using https://github.com/asbjornenge/Docker.tmbundle/pull/24 to embed ShellScript in Dockerfiles
- I'm using https://github.com/SublimeLinter/SublimeLinter-shellcheck for Shell linting
- ShellCheck requires a shell to be specified in order to provide suggestions, and complains with: _"Tips depend on target shell and yours is unknown. Add a shebang. [SC2148]"_
- Adding a shebang to a Dockerfile does not make sense

--- 

I tried to solve this by adding the following to the Dockerfile syntax-specific settings:
```
  "linters": {
    "shellcheck": {
      "args": "--shell=sh"
    }
  }
```

But it had no effect. I'm assuming this is because syntax-specific overrides are ignored?

**Comment by braver** [comment]
Syntax specific overrides aren't handled. 

What you're doing is a pretty specific hack to try and make linting work for embedded code. I would expect you to use the same shell for the other scripts in that project, so why not set the shell arg for the project?

**Comment by zx8** [comment]
I don't use Sublime projects as my workload is not predictable and varies from day-to-day, and maintaining multiple projects just isn't feasible.

Also, this is quite specific to the `RUN` step in Dockerfiles, which ([by default](https://docs.docker.com/engine/reference/builder/#run)) uses `sh` – everywhere else, I tend to use `bash`, which is why a syntax-specific Dockerfile override for `sublimelinter-shellcheck` would be super useful, especially since `syntax_map` has been deprecated in favour of scope selectors.

**Comment by kaste** [comment]
Hm, I think we should handle this here. For SL4 we redid the global settings to follow Sublime standards, but we did not touch the project/view-settings thing. Basically every setting that somehow depends on a view or its window. 

However, since these settings are a shared, flat key-value store, they would more look like 

```
"SublimeLinter.linters.shellcheck.args": "--shell=sh"
 ^^^^^^^^^^^^^ namespace  *we could use SL as well
               ^^^^^^^^^^^^^^^^^^^^^^^ flattened obj
```

With this working, we don't have to reinvent the wheel or fight Sublime in any way (AFAIK). E.g. we can disable a linter for a view, for a project, for a syntax, or globally.

**Comment by braver** [comment]
Sure, we can do this and it would totally fit with the design of Sublime Text. I don't think this particular case specifically warrants the effort, but I'm not against it if you can envision how to do it easily.

**Comment by kaste** [comment]
The special case is really too niche. But the thinking, hey I just modify the syntax settings to make it work, is 👍 Sublime thinking. 

I don't think we need non-standard project settings, when we get more for the buck using the Sublime standard. Also, it solves feat requests to disable or modify a linter for just that specific *view*, which Sublime can do I think if we #usetheplatform
