### ISSUE TITLE
SublimeLinter  triggering plugin_host failure

### ISSUE THREAD

**Issue by alecthomas** [SublimeLinter/SublimeLinter#1455]
This is going to be a tricky one, as there's no useful error to report, but I have iteratively disabled all plugins and SublimeLinter is definitely the one triggering the failure.

This is the error I see:

```
SublimeLinter: #71 util.py:264: Running `/Users/aat/.go/bin/golangci-lint run --enable-all --fast --print-issued-lines=false --tests --enable typecheck .`
error: plugin_host has exited unexpectedly, plugin functionality won't be available until Sublime Text has been restarted
```

I've done a bit of searching, and quite a few people have had this issue in the past due to unrelated plugins, so I suspect the underlying cause is not SublimeLinter itself but something it is using, or something the linter plugin is using. That said, the linter is not doing anything too exotic.

Some more information:

- On Sublime Text 3 version 3170, I can edit for a non-zero amount of time; minutes, to 10's of minutes.
- On the latest Sublime Text 3 version 3176, the plugin host crashes as soon as SublimeLinter does its first lint pass.

**Comment by alecthomas** [comment]
Upon further investigation, it looks like the linter binary is crashing with a SIGSEGV. That's obviously not great, but I wouldn't think that should cause the plugin_host to terminate :(

Maybe this is a bug in Sublime itself.

**Comment by kaste** [comment]
I think Sublime changed and probably regressed here. I also had a plugin crash. Do you use the build-system (aka `Default.exec` package?).

Also: https://forum.sublimetext.com/t/subprocess-triggers-plugin-host-crash/37336

**Comment by kaste** [comment]
Pretty sure we can't do anything here. We don't even have me too's here, so I'm closing.
