### ISSUE TITLE
PythonLinter pipenv check assuming cwd

### ISSUE THREAD

**Issue by theFroh** [SublimeLinter/SublimeLinter#1458]
Just finished poking around trying to find why automatic retrieval of the project's current environment via pipenv wasn't happening when trying to set up flake8.

The primary issue appears to be that while the correct project `cwd` (as determined by SublimeLinter's own heuristics) is fetched, this is not used when bailing early in pipenv guessing portion.

https://github.com/SublimeLinter/SublimeLinter/blob/4cb7f74ff181b535f41f5dba20a4b9bfa0d5fe31/lint/base_linter/python_linter.py#L133-L154

`project_path` will be typically relative (unless the user has edited the `folders` block in their settings), meaning the Pipfile will not be found unless Sublime Text was launched, or had its actual CWD changed to, the same directory as the project file.

I think `get_project_path` is redundant here, as this should (correctly) already be retrieved in the `cwd` variable by this point via `self.get_working_dir(settings)`.

**Comment by kaste** [comment]
Yes, that seems to be outdated code. Wanna make a PR?

Edge case is cwd can be None.

**Comment by theFroh** [comment]
Sure, I've been using just `cwd or ...` as per the PR, which behaves as expected.
