### ISSUE TITLE
SublimeLinter problem

### ISSUE THREAD

**Issue by ParvezNewton** [SublimeLinter/SublimeLinter#1462]
I trying to use flake8 package but I am getting following problems:
In the output of sublime linter, it is showing No lint results 
SublimeLinter: WARNING: cannot locate 'flake8'. Fill in the 'python' or 'executable' setting.
Package Control: Skipping automatic upgrade, last run at 2018-07-09 18:17:05, next run at 2018-07-09 19:17:05 or after
SublimeLinter: WARNING: cannot locate 'flake8'. Fill in the 'python' or 'executable' setting.
Unable to open /C/Users/Lenovo/AppData/Roaming/Sublime Text 3/Packages/SublimeLinter/SublimeLinter.sublime-settings

**Comment by kaste** [comment]
Hi!

Make sure you have flake8 actually installed. 

Otherwise, is flake8 globally available, t.i. can you execute flake8 from the command line?

@braver we have an unable to open SublimeLinter settings error here. 🤔

**Comment by braver** [comment]
> we have an unable to open SublimeLinter settings error here

that just sucks ⚾️ 🏀

**Comment by gothraven** [comment]
I am having the same problem
```shell
$> Flake8 --version
3.5.0 (mccabe: 0.6.1, pycodestyle: 2.3.1, pyflakes: 1.6.0) CPython 3.7.0 on Darwin
$> python --version
Python 3.7.0
```

SublimeLinter Setting
```
{
	"linters": {
       "eslint": {
           "disable": false,
           "args": [],
           "excludes": [],
           "env": {
               "PATH": "~/.nvm/versions/node/v8.10.0/bin:$PATH"
           },
      "flake8": {
          "@disable": false,
          "args": [],
          "builtins": "",
          "excludes": [".git","__pycache__","__init__.py","core/migrations/*.py","**/*_tests.py","runtests.py"],
          "executable": "",
          "ignore": "D203, E261, E402, F405",
          "jobs": "3",
          "max-complexity": 5,
          "max-line-length": 80,
          "select": "",
          "show-code": false
          },
      },
   },
}
```

**Comment by braver** [comment]
@gothraven why is Flake8 capitalized?

**Comment by gothraven** [comment]
that wasn't a copy past of my shell commande, I did rewrite it, but if you want the real commande, then here is it:

⬇️⬇️⬇️⬇️⬇️⬇️⬇️⬇️⬇️⬇️⬇️⬇️⬇️⬇️⬇️
```shell
➜  core_api git:(feature/set_up_flake8) ✗ flake8 --version
/Users/gothraven/Abricot/abricot-fleet/core-api/.direnv/python-3.7.0/lib/python3.7/site-packages/pycodestyle.py:113: FutureWarning: Possible nested set at position 1
  EXTRANEOUS_WHITESPACE_REGEX = re.compile(r'[[({] | []}),;:]')
3.5.0 (mccabe: 0.6.1, pycodestyle: 2.3.1, pyflakes: 1.6.0) CPython 3.7.0 on Darwin
```

**Comment by braver** [comment]
@gothraven please also show a debug log from the ST console.

http://www.sublimelinter.com/en/stable/troubleshooting.html

**Comment by gothraven** [comment]
I enabled debug and I have this in my Sublime console, and nothing else

```
SublimeLinter: WARNING: flake8 output:
/Users/gothraven/Abricot/abricot-fleet/core-api/.direnv/python-3.7.0/lib/python3.7/site-packages/pycodestyle.py:113: FutureWarning: Possible nested set at position 1
  EXTRANEOUS_WHITESPACE_REGEX = re.compile(r'[[({] | []}),;:]')
```

```
$> which flake8
/Users/gothraven/Abricot/abricot-fleet/core-api/.direnv/python-3.7.0/bin/flake8
```

**Comment by braver** [comment]
@gothraven so it never logs `SublimeLinter: WARNING: cannot locate 'flake8'.` for you?

**Comment by gothraven** [comment]
It used to log that yesterday, but now it doesn't, (I dont know why) though nothing works yet!

**Comment by braver** [comment]
LOL :) Gotta love computers

**Comment by gothraven** [comment]
I think it has something to do with the fact that i use `.direnv/` and/or `virtualenv`

**Comment by gothraven** [comment]
I found the best solution for me is to add this to SublimeLinter Settings

```json
{
     "executable": ["py", "-m", "flake8"]
}
```

**Comment by kaste** [comment]
Oh. I thought py is only available on Windows. For Windows it is a really good solution bc you can even tell it to use a specific version etc.

**Comment by gothraven** [comment]
Ow sorry, I wanted to write "python" instead of "py"  😅

**Comment by braver** [comment]
Good news!

**Comment by kaste** [comment]
If you open the settings, you should have a side-by-side view. On the left you see the 'default' configuration with a lot of comments. 

Something like this should do the trick. 

```json
	"linters": {
		"flake8": {
			"executable": "..."
		}
	},

**Comment by michelleowen** [comment]
I installed pycodestyle with pip. But when I do "which pycodestyle", it gives me nothing. So I know the executable path is not in $PATH. My question is, how to find the executable path for pycodestyle?

**Comment by kaste** [comment]
@michelleowen If it's not in your $PATH I would maybe just use the `python` setting ameliorated instead and point to the correct python binary. SublimeLinter will then basically run `/here/is/my/python -m pycodestyle`. 

I think `pip` actually logs where it puts the binaries at the end of an install. So maybe a `pip uninstall; pip install <again>` will also give you that information. 🤞

**Comment by jithu7432** [comment]
> > "executable": ["python", "-m", "flake8"]
> 
> Where do you put this? I tried and got an error: "SublimeLinter: WARNING: Invalid settings in 'Packages/User/SublimeLinter.sublime-settings'"


_Packages/User/SublimeLinter.sublime-settings_
```json
{
   "linters":{
      "pyflakes":{
         "disable":false,
         "executable":"/home/jithin/.local/venv/bin/pyflakes",
      }
   }
}
```
