### ISSUE TITLE
Support for URL's in linter outputs

### ISSUE THREAD

**Issue by fatbasstard** [SublimeLinter/SublimeLinter#1463]
Hi,

I would like to add URL's to linter output message to help people with information about the error/warning. This is a feature that "the" Atom linter supports and works pretty sweet: 

https://steelbrain.me/linter/types/linter-message-v2.html
Example:
![image](https://user-images.githubusercontent.com/35613489/42558170-b92c29aa-84f0-11e8-9112-3e2bdd7f3ce3.png)
 
I'd love to see this feature in SublimeLinter 😄 

If it's already possible, documentation and/or help about it would be great 😉

Sublime itself supports something for this: https://www.sublimetext.com/docs/3/api_reference.html#sublime.Phantom

p.s.
Bonus context: We're working on a CloudFormation linter (https://github.com/awslabs/cfn-python-lint) and every linter rule contains a source url now, explaining where the linter output originates from. Would be great if we can make this information directly available for the users

**Comment by kaste** [comment]
Hi @fatbasstard, 

the blocker here is of course that none of the relevant linters (afaik) provide such an url. (But these urls are anyway probably a simple, static map from error type -> url.) 

Of course, you can just do and prove it! You just need a clear idea of the desired UI/UX to begin with. (E.g. you could add an entry to the right click context menu.)

**Comment by braver** [comment]
Which probably mostly works, until they change something about their website...

Anyway, the tooltips we show are html-ish: https://www.sublimetext.com/docs/3/minihtml.html. It's pretty easy to add a clickable link to them. I guess a linter plugin could set a url attribute using a template string where replace part of that template with the error code. It's probably not even that complicated.

**Comment by kaste** [comment]
This is of course super trivial to implement. #1480 for a strawman, really don't know how this should look like, which is the important thing here. And, again, none of the relevant linters actually output urls to their rules.

**Comment by kaste** [comment]
Via #1480 the UI would look like this.

![image](https://user-images.githubusercontent.com/8558/44166552-eb393400-a0cb-11e8-9c30-e20f5c3f7658.png)

I think this is relatively distracting, but more important it is not accessible. So, we need a command/action for that additionally. I still think that the approach using the (right-click) context menu could work out nicely.

- it hides (useful, additional) functionality you rarely use and keeps the main UI clean
- it is accessible (bc command driven)
- it can be developed as a plugin (on top of the current SL)
- we can use text like "Lookup 'eslint no-unused-vars'", "Show 'no-unused-vars' documentation"

**Comment by kaste** [comment]
That's a chicken egg problem here. Nobody told us where we can find URLs for rule names for any linter. If we had such a "service" we could add clickable links but not the other way around.

**Comment by braver** [comment]
Agreed. Also, big feature requests like this need to see more interaction before it warrants the effort.
