### ISSUE TITLE
ZipImportError while updating to v4.7.0

### ISSUE THREAD

**Issue by jrappen** [SublimeLinter/SublimeLinter#1468]
```text
Traceback (most recent call last):
  File "..\sublime_plugin.py", line 116, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
zipimport.ZipImportError: bad local file header in ..\Data\Installed Packages\SublimeLinter.sublime-package
```

* Sublime Text 3175 x64 portable
* Win 10 Pro 1803 x64
* Package Control v3.3.0
* SublimeLinter v4.7.0

**Comment by kaste** [comment]
Probably just restart, and Package control will fix that?

**Comment by jrappen** [comment]
Restarting helps, but not having the error in the first place would be better I suppose?

**Comment by kaste** [comment]
Yeah, okay, but if a package manager fails to upgrade/download a package it's not the fault of the package. We just publish on GitHub, we don't zip.

**Comment by braver** [comment]
This is indeed more likely a package control bug.

**Comment by braver** [comment]
Or maybe not: https://github.com/jdavisclark/JsFormat/issues/170#issuecomment-213031454

**Comment by kaste** [comment]
@braver That's a different stacktrace. We also don't do stuff with `sys.path`. (Actually, Package Control does a lot of magic stuff.)

Ref issue: https://github.com/wbond/package_control/issues/947

@jrappen Which SublimeLinter plugins do you use? Do you have black-for-flake?

**Comment by jrappen** [comment]
@kaste currently only using annotations

**Comment by kaste** [comment]
Closing. This issue is not moving and it is still unlikely that *we* do something wrong here. I'm subsribed to https://github.com/wbond/package_control/issues/947 which also doesn't move.
