### ISSUE TITLE
Linter not working (gcc)

### ISSUE THREAD

**Issue by Ovog** [SublimeLinter/SublimeLinter#1469]
A few days ago sublime linter stoped showing me errors, even if I purposely wrote them.

I enabled debug mode, and here is a copy of the log

DPI mode: system
DPI scale: 1
startup, version: 3176 windows x64 channel: stable
executable: /E/Programs/Sublime Text 3/sublime_text.exe
working dir: /E/Programs/Sublime Text 3
packages path: /C/Users/Javier/AppData/Roaming/Sublime Text 3/Packages
state path: /C/Users/Javier/AppData/Roaming/Sublime Text 3/Local
zip path: /E/Programs/Sublime Text 3/Packages
zip path: /C/Users/Javier/AppData/Roaming/Sublime Text 3/Installed Packages
ignored_packages: ["Vintage"]
pre session restore time: 0.234063
startup time: 0.278062
first paint time: 0.279062
reloading plugin Default.arithmetic
reloading plugin Default.auto_indent_tag
reloading plugin Default.block
reloading plugin Default.colors
reloading plugin Default.comment
reloading plugin Default.convert_color_scheme
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.install_package_control
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.quick_panel
reloading plugin Default.rename
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.settings
reloading plugin Default.show_scope_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin Default.ui
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin ShellScript.ShellScript
reloading plugin 0_package_control_loader.00-package_control
reloading plugin 0_package_control_loader.01-pygments
reloading plugin 0_package_control_loader.50-backrefs
reloading plugin 0_package_control_loader.50-markupsafe
reloading plugin 0_package_control_loader.50-pymdownx
reloading plugin 0_package_control_loader.50-python-markdown
reloading plugin 0_package_control_loader.50-pyyaml
reloading plugin 0_package_control_loader.51-python-jinja2
reloading plugin 0_package_control_loader.55-jsonschema
reloading plugin 0_package_control_loader.55-mdpopups
reloading plugin BracketHighlighter.bh_core
reloading plugin BracketHighlighter.bh_logging
reloading plugin BracketHighlighter.bh_plugin
reloading plugin BracketHighlighter.bh_popup
reloading plugin BracketHighlighter.bh_regions
reloading plugin BracketHighlighter.bh_remove
reloading plugin BracketHighlighter.bh_rules
reloading plugin BracketHighlighter.bh_search
reloading plugin BracketHighlighter.bh_swapping
reloading plugin BracketHighlighter.bh_wrapping
reloading plugin BracketHighlighter.support
reloading plugin Package Control.1_reloader
reloading plugin Package Control.2_bootstrap
reloading plugin Package Control.Package Control
reloading plugin PackageResourceViewer.package_resource_viewer
reloading plugin PackageResourceViewer.package_resources
reloading plugin Skins.skins
reloading plugin SublimeLinter-gcc.linter
gcc: Defining 'cls.syntax' has been deprecated. Use http://www.sublimelinter.com/en/stable/linter_settings.html#selector
gcc: Implementing 'cls.can_lint_syntax' has no effect anymore. You can safely remove these methods.
reloading plugin SublimeLinter.__init__
reloading plugin SublimeLinter.active_linters_view
reloading plugin SublimeLinter.busy_indicator_view
reloading plugin SublimeLinter.goto_commands
reloading plugin SublimeLinter.highlight_view
reloading plugin SublimeLinter.log_handler
reloading plugin SublimeLinter.message_view
reloading plugin SublimeLinter.panel_view
reloading plugin SublimeLinter.status_bar_view
reloading plugin SublimeLinter.sublime_linter
reloading plugin SublimeLog.SublimeLog
reloading plugin ColorPicker.sublimecp
reloading plugin SublimeGDB.resultparser
reloading plugin SublimeGDB.sublimegdb
plugins loaded
SublimeLinter: log_handler.py:74: Logging installed; log level INFO
SublimeLinter: sublime_linter.py:50: debug mode: on
SublimeLinter: sublime_linter.py:51: version: 4.7.0
SublimeLinter: sublime_linter.py:250: Delay buffer 25 for 0.0s
SublimeLinter: linter.py:886: Checking lint mode background vs lint reason on_load
SublimeLinter: #1 linter.py:906: 'gcc' is linting 'Absorcion.c'
SublimeLinter: #1 util.py:198: PATH:
    C:\Program Files (x86)\Common Files\Oracle\Java\javapath
    C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common
    C:\ProgramData\Oracle\Java\javapath
    C:\Program Files (x86)\Cuminas\Document Express DjVu Plug-in\
    C:\Windows\system32
    C:\Windows
    C:\Windows\System32\Wbem
    C:\Windows\System32\WindowsPowerShell\v1.0\
    C:\Program Files (x86)\Skype\Phone\
    E:\Programs\Mantenimiento\PuTTY\
    E:\Archivos de programa\ATI\Catalyst\ATI.ACE\Core-Static
    C:\Program Files\MiKTeX 2.9\miktex\bin\x64\
    C:\MinGW\bin
    E:\Programs\gnuplot\bin
    E:\Archivos de Juego\Anaconda3
    E:\Archivos de Juego\Anaconda3\Scripts
    E:\Archivos de Juego\Anaconda3\Library\bin

SublimeLinter: #1 linter.py:1262: Running ...

  E:\Universidad\Trimestre 12\Fisica Computacional\Codigos Propios\Absorcion de un material  (working dir)
  > type Absorcion.c | C:\MinGW\bin\gcc.exe -c -Wall -O0 -std=c99 -I'E:\Universidad\Trimestre 12\Fisica Computacional\Codigos Propios\Absorcion de un material' -x c -o 'c:\users\javier\appdata\local\temp\SublimeLinter-gcc.o' -

SublimeLinter: #1 linter.py:1276: WARNING: Exception: [Errno 32] Broken pipe
SublimeLinter: sublime_linter.py:444: Linting buffer 25 took 0.10s
Package Control: Skipping automatic upgrade, last run at 2018-07-15 19:16:56, next run at 2018-07-15 20:16:56 or after
SublimeLinter: sublime_linter.py:250: Delay buffer 25 for 0.3s
SublimeLinter: linter.py:886: Checking lint mode background vs lint reason None
SublimeLinter: #2 linter.py:906: 'gcc' is linting 'Absorcion.c'
SublimeLinter: #2 linter.py:1262: Running ...

  E:\Universidad\Trimestre 12\Fisica Computacional\Codigos Propios\Absorcion de un material  (working dir)
  > type Absorcion.c | C:\MinGW\bin\gcc.exe -c -Wall -O0 -std=c99 -I'E:\Universidad\Trimestre 12\Fisica Computacional\Codigos Propios\Absorcion de un material' -x c -o 'c:\users\javier\appdata\local\temp\SublimeLinter-gcc.o' -

SublimeLinter: #2 linter.py:1276: WARNING: Exception: [Errno 32] Broken pipe
SublimeLinter: sublime_linter.py:444: Linting buffer 25 took 0.07s
SublimeLinter: sublime_linter.py:250: Delay buffer 25 for 0.3s
SublimeLinter: sublime_linter.py:250: Delay buffer 25 for 0.3s
SublimeLinter: linter.py:886: Checking lint mode background vs lint reason None
SublimeLinter: #3 linter.py:906: 'gcc' is linting 'Absorcion.c'
SublimeLinter: #3 linter.py:1262: Running ...

  E:\Universidad\Trimestre 12\Fisica Computacional\Codigos Propios\Absorcion de un material  (working dir)
  > type Absorcion.c | C:\MinGW\bin\gcc.exe -c -Wall -O0 -std=c99 -I'E:\Universidad\Trimestre 12\Fisica Computacional\Codigos Propios\Absorcion de un material' -x c -o 'c:\users\javier\appdata\local\temp\SublimeLinter-gcc.o' -

SublimeLinter: #3 linter.py:1276: WARNING: Exception: [Errno 32] Broken pipe
SublimeLinter: sublime_linter.py:444: Linting buffer 25 took 0.07s
SublimeLinter: sublime_linter.py:250: Delay buffer 25 for 0.3s
SublimeLinter: linter.py:886: Checking lint mode background vs lint reason None
SublimeLinter: #4 linter.py:906: 'gcc' is linting 'Absorcion.c'
SublimeLinter: #4 linter.py:1262: Running ...

  E:\Universidad\Trimestre 12\Fisica Computacional\Codigos Propios\Absorcion de un material  (working dir)
  > type Absorcion.c | C:\MinGW\bin\gcc.exe -c -Wall -O0 -std=c99 -I'E:\Universidad\Trimestre 12\Fisica Computacional\Codigos Propios\Absorcion de un material' -x c -o 'c:\users\javier\appdata\local\temp\SublimeLinter-gcc.o' -

SublimeLinter: #4 linter.py:1276: WARNING: Exception: [Errno 32] Broken pipe
SublimeLinter: sublime_linter.py:444: Linting buffer 25 took 0.07s
SublimeLinter: sublime_linter.py:250: Delay buffer 25 for 0.1s
SublimeLinter: linter.py:886: Checking lint mode background vs lint reason None
SublimeLinter: #5 linter.py:906: 'gcc' is linting 'Absorcion.c'
SublimeLinter: #5 linter.py:1262: Running ...

  E:\Universidad\Trimestre 12\Fisica Computacional\Codigos Propios\Absorcion de un material  (working dir)
  > type Absorcion.c | C:\MinGW\bin\gcc.exe -c -Wall -O0 -std=c99 -I'E:\Universidad\Trimestre 12\Fisica Computacional\Codigos Propios\Absorcion de un material' -x c -o 'c:\users\javier\appdata\local\temp\SublimeLinter-gcc.o' -

SublimeLinter: #5 linter.py:1276: WARNING: Exception: [Errno 32] Broken pipe
SublimeLinter: sublime_linter.py:444: Linting buffer 25 took 0.07s
SublimeLinter: sublime_linter.py:250: Delay buffer 25 for 0.1s
SublimeLinter: linter.py:886: Checking lint mode background vs lint reason None
SublimeLinter: #6 linter.py:906: 'gcc' is linting 'Absorcion.c'
SublimeLinter: #6 linter.py:1262: Running ...

  E:\Universidad\Trimestre 12\Fisica Computacional\Codigos Propios\Absorcion de un material  (working dir)
  > type Absorcion.c | C:\MinGW\bin\gcc.exe -c -Wall -O0 -std=c99 -I'E:\Universidad\Trimestre 12\Fisica Computacional\Codigos Propios\Absorcion de un material' -x c -o 'c:\users\javier\appdata\local\temp\SublimeLinter-gcc.o' -

SublimeLinter: sublime_linter.py:250: Delay buffer 25 for 0.1s
SublimeLinter: #6 linter.py:1276: WARNING: Exception: [Errno 32] Broken pipe
SublimeLinter: #6 sublime_linter.py:413: Buffer 25 inconsistent. Aborting lint.
SublimeLinter: sublime_linter.py:444: Linting buffer 25 took 0.07s
SublimeLinter: linter.py:886: Checking lint mode background vs lint reason None
SublimeLinter: #7 linter.py:906: 'gcc' is linting 'Absorcion.c'
SublimeLinter: #7 linter.py:1262: Running ...

  E:\Universidad\Trimestre 12\Fisica Computacional\Codigos Propios\Absorcion de un material  (working dir)
  > type Absorcion.c | C:\MinGW\bin\gcc.exe -c -Wall -O0 -std=c99 -I'E:\Universidad\Trimestre 12\Fisica Computacional\Codigos Propios\Absorcion de un material' -x c -o 'c:\users\javier\appdata\local\temp\SublimeLinter-gcc.o' -

SublimeLinter: #7 linter.py:1276: WARNING: Exception: [Errno 32] Broken pipe
SublimeLinter: sublime_linter.py:444: Linting buffer 25 took 0.07s
SublimeLinter: sublime_linter.py:250: Delay buffer 25 for 0.0s
SublimeLinter: linter.py:886: Checking lint mode background vs lint reason on_save
SublimeLinter: #8 linter.py:906: 'gcc' is linting 'Absorcion.c'
SublimeLinter: #8 linter.py:1262: Running ...

  E:\Universidad\Trimestre 12\Fisica Computacional\Codigos Propios\Absorcion de un material  (working dir)
  > type Absorcion.c | C:\MinGW\bin\gcc.exe -c -Wall -O0 -std=c99 -I'E:\Universidad\Trimestre 12\Fisica Computacional\Codigos Propios\Absorcion de un material' -x c -o 'c:\users\javier\appdata\local\temp\SublimeLinter-gcc.o' -

SublimeLinter: #8 linter.py:1276: WARNING: Exception: [Errno 32] Broken pipe
SublimeLinter: sublime_linter.py:444: Linting buffer 25 took 0.07s
indexing: Unable to write to index, index is likely corrupted, and will be recreated after restarting.
Running gcc -std=c99 -lm -Wall Absorcion.c -o Absorcion
SublimeLinter: sublime_linter.py:250: Delay buffer 36 for 0.1s
SublimeLinter: sublime_linter.py:250: Delay buffer 36 for 0.1s
reloading settings Packages/User/Preferences.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings

Anyone has any idea what happened?

**Comment by braver** [comment]
@kaste could the broken pipe be caused by the [shlex.split fix](https://github.com/SublimeLinter/SublimeLinter/commit/5719dd4e2e1e0c6059ff54e9115a4298827f2aa9)?

**Comment by braver** [comment]
@Ovog thanks for reporting, a version is out now that reverts a change and should fix your setup. The windows shell eco system is a bit complicated I'm afraid.

**Comment by JunChiehWang** [comment]
Hi I have the same issue too, here is the error message:

reloading settings Packages/User/SublimeLinter.sublime-settings
SublimeLinter: log_handler.py:74      Logging installed; log level INFO
SublimeLinter: sublime_linter.py:248  Delay linting 'comm.cpp' for 0.0s
SublimeLinter: linter.py:1056         g++: Checking lint mode 'background' vs lint reason 'on_load'.  Ok.
SublimeLinter: #31 linter.py:1073     g++: linting 'comm.cpp'
SublimeLinter: #31 linter.py:847      g++: wanted executable is '['g++']'
SublimeLinter: #31 linter.py:1569     ERROR:   Execution failed

  [WinError 2] The system cannot find the file specified

  V:\code\LAMMPS\mylammps2  (working dir)
  > type src\comm.cpp | g++ -Wall -std=c++14 -o c:\users\jwang1~1\appdata\local\temp\SublimeLinter-gcc.o -x c++ -

SublimeLinter: sublime_linter.py:482  Linting 'comm.cpp' took 0.04s
SublimeLinter: sublime_linter.py:248  Delay linting 'comm.cpp' for 0.1s
SublimeLinter: linter.py:1056         g++: Checking lint mode 'background' vs lint reason 'on_modified'.  Ok.
SublimeLinter: sublime_linter.py:450  Buffer 253 inconsistent. Aborting lint.
SublimeLinter: sublime_linter.py:248  Delay linting 'comm.cpp' for 0.1s
SublimeLinter: linter.py:1056         g++: Checking lint mode 'background' vs lint reason 'on_modified'.  Ok.
SublimeLinter: #32 linter.py:1073     g++: linting 'comm.cpp'
SublimeLinter: #32 linter.py:847      g++: wanted executable is '['g++']'
SublimeLinter: #32 linter.py:1569     ERROR:   Execution failed

  [WinError 2] The system cannot find the file specified

  V:\code\LAMMPS\mylammps2  (working dir)
  > type src\comm.cpp | g++ -Wall -std=c++14 -o c:\users\jwang1~1\appdata\local\temp\SublimeLinter-gcc.o -x c++ -

SublimeLinter: sublime_linter.py:482  Linting 'comm.cpp' took 0.03s

**Comment by kaste** [comment]
You set `"executable": ["g++"]` in your settings which is not what you want. Probably do not set `executable` at all, but if you do, set it to an abs path to a binary.
