### ISSUE TITLE
Cannot change "gutter_theme"

### ISSUE THREAD

**Issue by SilentGene** [SublimeLinter/SublimeLinter#1471]
The issue is no matter what gutter theme I specified other than "Default" the gutter icon would change to a grey dot.
e.g.
` "gutter_theme": "Blueberry Cross",`
and the icons will turn to grey dots.

**Comment by braver** [comment]
And that do you set for the icons?

From the default settings:
```
// Note that you may need to change the "icon" property in "styles"
// to an icon in the theme (they usually include "warning" and "error")
```

**Comment by SilentGene** [comment]
Sorry, I missed that configuration.
But there is another question, in the default settings file, there is only a style setting for "warning":
`"types": ["warning"]`
should I just add another "styles" and specified ""types": ["error"]", and then specified the icon for error.png?

**Comment by braver** [comment]
The way the rules are combined probably makes that the default settings work without explicitly defining the "error" type style. What you're saying is correct though, I would add something like this to my settings:

```
"styles": [
        {
            "icon": "warning",
            "types": ["warning"]
        },
        {
            "icon": "error",
            "types": ["error"]
        }
    ]
```

**Comment by SilentGene** [comment]
Thanks @braver
