### ISSUE TITLE
Update to 4.7.2 broke custom rulesets.

### ISSUE THREAD

**Issue by JoshChris** [SublimeLinter/SublimeLinter#1473]
Hi, package control automatically upgraded me this morning to version 4.7.2. After the upgrade, I had to update my project settings to accommodate the new format. However, upon update, my custom rules broke.

Here are my package settings:
```
{
	"folders":
	[
		{
			"path": "/path/to/root/folder"
		}
	],
	"settings":
	{
        	"SublimeLinter.linters.phpcs.standard": "~/path/to/phpcs-psr2-tabs.xml",
        	"SublimeLinter.linters.phpmd.rulesets": "~/path/to/phpmd-ruleset.xml"
	}
}
```

I am getting lint errors, so I can confirm that the linters are working... they're just not using my custom rules. Please let me know if I can provide more information to help solve this.

**Comment by braver** [comment]
The SL 4.7.2 upgrade probably coincided with an update to the phpcs plugin. Instead of the `standard` setting, you should switch to setting the standard via `args` that are then passed on to phpcs just like they would on the command line.  So,

```
"SublimeLinter.linters.phpcs.standard": "~/path/to/phpcs-psr2-tabs.xml",
```
becomes
```
"SublimeLinter.linters.phpcs.args": "--standard=~/path/to/phpcs-psr2-tabs.xml",
```

Let me know if that works for you!

**Comment by JoshChris** [comment]
Yup, that did it! Thank you!

**Comment by braver** [comment]
🎉
