### ISSUE TITLE
Doesn't work without one or multiple restarts

### ISSUE THREAD

**Issue by LeEnno** [SublimeLinter/SublimeLinter#1479]
I know there have been timing issues which prevented SublimeLinter from running with correct environment variables and paths every now and then. I thought this was fixed for good with a recent Sublime Text update and a new API callback. But for a few weeks I have the following problem:

Most times linting doesn't work for me without restarts. I get `(erred)` in the status bar at the bottom for rubocop and reek. Usually I restart Sublime once or twice and it works the way one would expect.

Since this happens for both rubocop and reek the issue doesn't seem to be linter specific.

Here are 2 logs, the first one shows the error occuring, the other one shows how everything works after a restart of Sublime.

Log 1 👎:

```
SublimeLinter: log_handler.py:74: Logging installed; log level INFO
SublimeLinter: sublime_linter.py:50: debug mode: on
SublimeLinter: sublime_linter.py:51: version: 4.7.2
SublimeLinter: sublime_linter.py:250: Delay buffer 26 for 0.0s
SublimeLinter: linter.py:887: Checking lint mode background vs lint reason on_load
SublimeLinter: linter.py:887: Checking lint mode background vs lint reason on_load
SublimeLinter: #1 linter.py:907: 'reek' is linting 'shop_gallery_controller.rb'
SublimeLinter: #1 util.py:142: PATH:
    /usr/bin
    /bin
    /usr/sbin
    /sbin
SublimeLinter: #2 linter.py:907: 'rubocop' is linting 'shop_gallery_controller.rb'
SublimeLinter: #1 linter.py:1197: Automatically appending the filename to cmd has been deprecated. Use $file, $temp_file or $file_on_disk instead.
SublimeLinter: #2 linter.py:1263: Running ...

  /Users/Enno/Sites/pictrs/master/pictrs  (working dir)
  $ cat app/controllers/shop_gallery_controller.rb | /usr/bin/ruby -S rubocop --format emacs --force-exclusion --stdin /Users/Enno/Sites/pictrs/master/pictrs/app/controllers/shop_gallery_controller.rb

SublimeLinter: #1 linter.py:1263: Running ...

  /Users/Enno/Sites/pictrs/master/pictrs  (working dir)
  $ /usr/bin/ruby -S reek /var/folders/l2/j37t2cjs5ssgcgsrk1xyt1x40000gn/T/tmp3tvsad.rb

SublimeLinter: #2 linter.py:589: WARNING: rubocop output:
/usr/bin/ruby: No such file or directory -- rubocop (LoadError)

SublimeLinter: #2 linter.py:591: Note: above warning will become an error in the future. Implement `on_stderr` if you think this is wrong.
SublimeLinter: #1 linter.py:589: WARNING: reek output:
/usr/bin/ruby: No such file or directory -- reek (LoadError)

SublimeLinter: #1 linter.py:591: Note: above warning will become an error in the future. Implement `on_stderr` if you think this is wrong.
SublimeLinter: sublime_linter.py:444: Linting buffer 26 took 0.08s
Emmet: No need to update PyV8
Package Control: Skipping automatic upgrade, last run at 2018-08-14 10:27:54, next run at 2018-08-14 11:27:54 or after
```

Log 2 👍:

```
SublimeLinter: log_handler.py:74: Logging installed; log level INFO
SublimeLinter: sublime_linter.py:50: debug mode: on
SublimeLinter: sublime_linter.py:51: version: 4.7.2
Load settings: Open-Include
SublimeLinter: sublime_linter.py:250: Delay buffer 26 for 0.0s
SublimeLinter: linter.py:887: Checking lint mode background vs lint reason on_load
SublimeLinter: linter.py:887: Checking lint mode background vs lint reason on_load
SublimeLinter: #1 linter.py:907: 'reek' is linting 'shop_gallery_controller.rb'
SublimeLinter: #1 util.py:142: PATH:
    /Users/Enno/.rvm/gems/ruby-2.2.4/bin
    /Users/Enno/.rvm/gems/ruby-2.2.4@global/bin
    /Users/Enno/.rvm/rubies/ruby-2.2.4/bin
    /usr/local/bin
    /usr/bin
    /bin
    /usr/sbin
    /sbin
    /Applications/VMware Fusion.app/Contents/Public
    /Users/Enno/.rvm/bin
SublimeLinter: #2 linter.py:907: 'rubocop' is linting 'shop_gallery_controller.rb'
SublimeLinter: #1 linter.py:1197: Automatically appending the filename to cmd has been deprecated. Use $file, $temp_file or $file_on_disk instead.
SublimeLinter: #2 linter.py:1263: Running ...

  /Users/Enno/Sites/pictrs/master/pictrs  (working dir)
  $ cat app/controllers/shop_gallery_controller.rb | /Users/Enno/.rvm/bin/rvm-auto-ruby -S rubocop --format emacs --force-exclusion --stdin /Users/Enno/Sites/pictrs/master/pictrs/app/controllers/shop_gallery_controller.rb

SublimeLinter: #1 linter.py:1263: Running ...

  /Users/Enno/Sites/pictrs/master/pictrs  (working dir)
  $ /Users/Enno/.rvm/bin/rvm-auto-ruby -S reek /var/folders/l2/j37t2cjs5ssgcgsrk1xyt1x40000gn/T/tmp7n9l9s.rb

Emmet: No need to update PyV8
Package Control: Skipping automatic upgrade, last run at 2018-08-14 10:27:54, next run at 2018-08-14 11:27:54 or after
SublimeLinter: #2 linter.py:955: rubocop output:
    /Users/Enno/Sites/pictrs/master/pictrs/app/controllers/shop_gallery_controller.rb:1:1: C: Unnecessary utf-8 encoding comment.
    ...
    ...
    ...
    /Users/Enno/Sites/pictrs/master/pictrs/app/controllers/shop_gallery_controller.rb:2115:11: C: Avoid more than 3 levels of block nesting.
SublimeLinter: #1 linter.py:955: reek output:
    /var/folders/l2/j37t2cjs5ssgcgsrk1xyt1x40000gn/T/tmp7n9l9s.rb -- 20 warnings:
      [1372, 1372, 1374, 1376]:DuplicateMethodCall: ShopGalleryController#_add_pw_to_session calls 'album.shop' 4 times [https://github.com/troessner/reek/blob/master/docs/Duplicate-Method-Call.md]
      ...
      ...
      ...
      [1253]:TooManyStatements: ShopGalleryController#redaktion_register has approx 14 statements [https://github.com/troessner/reek/blob/master/docs/Too-Many-Statements.md]
SublimeLinter: #1 linter.py:995: reek: No match for line: '/var/folders/l2/j37t2cjs5ssgcgsrk1xyt1x40000gn/T/tmp7n9l9s.rb -- 20 warnings:'
SublimeLinter: sublime_linter.py:444: Linting buffer 26 took 7.00s
```

System information:
- OSX 10.12.6
- Sublime Text 3.1.1 Build 3176
- SublimeLinter v4.7.2

I'm happy to assist if you need more information.

**Comment by braver** [comment]
>  I thought this was fixed for good with a recent Sublime Text update and a new API callback.

Sadly there isn't a new API callback. In stead, your shell has 1 second to report the env to Sublime Text, otherwise it falls back to the default. If for some reason your setup is too slow for this to work, you can specify the executable for each linter in SublimeLinter so it doesn't have to rely on PATH.

Perhaps you're using rvm. This and nvm are known to slow down the shell enough that Sublime Text's behavior doesn't work (or work reliably). This problem isn't specific to SublimeLinter and isn't something we can fix. Hopefully we provide enough features to work around it.

**Comment by LeEnno** [comment]
Thx for your response. I thought I read a comment from Sublime's creator adding some callback and everyone wildly celebrating that and referencing the corresponding issue. Dream or memory? 🤔 Never mind.

You're correct, I'm using rvm. The current situation sucks but at least we have a fix, so thank you.

I don't know if this is expected but:

1. I had to make sure GEM_PATH was set correctly.
2. The executable needs to be `rvm-auto-ruby`, no matter what linter. So my config looks like this right now (exactly the same for all linters):

```json
{
  "linters": {
      "hamllint": {
        "env": {"GEM_PATH":"/Users/Enno/.rvm/gems/ruby-2.3.1"},
        "executable": "/Users/Enno/.rvm/bin/rvm-auto-ruby"
      },
      "rubocop": {
        "env": {"GEM_PATH":"/Users/Enno/.rvm/gems/ruby-2.3.1"},
        "executable": "/Users/Enno/.rvm/bin/rvm-auto-ruby"
      },
      "reek": {
        "env": {"GEM_PATH":"/Users/Enno/.rvm/gems/ruby-2.3.1"},
        "executable": "/Users/Enno/.rvm/bin/rvm-auto-ruby"
      }
  }
}
```

Is that the way it's intended? Or did I stumble upon another wird behavior?

**Comment by braver** [comment]
Yeah, that's basically what the work around is. Because the env isn't loaded you need to patch it with whatever the program needs to have. 

>The current situation sucks but at least we have a fix, so thank you.

Totally. :)

**Comment by kaste** [comment]
I would like to comment here.

```
        "env": {"GEM_PATH":"/Users/Enno/.rvm/gems/ruby-2.3.1"},
        "executable": "/Users/Enno/.rvm/bin/rvm-auto-ruby"
```

This usually confuses me. You specify a specific version as GEM_PATH, but `rvm-auto-ruby` as executable. I think pointing to the specific, related ruby bin would be more consistent. 

E.g. _executable_ could be `/Users/Enno/.rvm/rubies/ruby-2.3.1/bin/ruby`. No? 🤷‍♀️

**Comment by LeEnno** [comment]
Honestly, I gave up trying to understand what rvm, Sublime or even SublimeLinter are trying to do under the hood because it usually confuses me as well. For example I really don't understand why the `executable` has to be `ruby` instead of the actual linter (i.e. `rubocop`).

When trying your suggestion (adding the specific `ruby` instead of `rvm-auto-ruby`) which sounds very reasonable to me I get the following log:

```
SublimeLinter: log_handler.py:74: Logging installed; log level INFO
SublimeLinter: sublime_linter.py:50: debug mode: on
SublimeLinter: sublime_linter.py:51: version: 4.7.2
SublimeLinter: sublime_linter.py:250: Delay buffer 25 for 0.0s
SublimeLinter: linter.py:887: Checking lint mode background vs lint reason on_load
SublimeLinter: #1 linter.py:907: 'rubocop' is linting 'exception_notification.rb'
SublimeLinter: #1 linter.py:688: rubocop: wanted executable is '/Users/Enno/.rvm/rubies/ruby-2.3.1/bin/ruby'
SublimeLinter: #1 linter.py:1263: Running ...

  /Users/Enno/Sites/pictrs/master/pictrs  (working dir)
  $ cat config/initializers/exception_notification.rb | /Users/Enno/.rvm/rubies/ruby-2.3.1/bin/ruby -S rubocop --format emacs --force-exclusion --stdin /Users/Enno/Sites/pictrs/master/pictrs/config/initializers/exception_notification.rb

SublimeLinter: #1 linter.py:589: WARNING: rubocop output:
Ignoring oga-1.3.1 because its extensions are not built.  Try: gem pristine oga --version 1.3.1
Ignoring ruby-ll-2.1.2 because its extensions are not built.  Try: gem pristine ruby-ll --version 2.1.2
/Users/Enno/.rvm/rubies/ruby-2.3.1/bin/ruby: No such file or directory -- rubocop (LoadError)

SublimeLinter: #1 linter.py:591: Note: above warning will become an error in the future. Implement `on_stderr` if you think this is wrong.
SublimeLinter: sublime_linter.py:444: Linting buffer 25 took 0.25s
```

Not the result we were hoping for, right?

**Comment by kaste** [comment]
> For example I really don't understand why the executable has to be ruby instead of the actual linter (i.e. rubocop).

That's what I was thinking too, so I made https://github.com/SublimeLinter/SublimeLinter-rubocop/pull/55 but we don't have ruby testers. (Basically, all ruby linters are SublimeLinter v3.)

Just curious, if you run `rvm info 2.3.1` it will print all ENV variables 🤞 ? GEM_HOME?

**Comment by LeEnno** [comment]
> Just curious, if you run rvm info 2.3.1 it will print all ENV variables 🤞 ? GEM_HOME?

Output:

```
PATH:         "/Users/Enno/.rvm/gems/ruby-2.3.1/bin:/Users/Enno/.rvm/gems/ruby-2.3.1@global/bin:/Users/Enno/.rvm/rubies/ruby-2.3.1/bin:/Users/Enno/.rvm/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
GEM_HOME:     "/Users/Enno/.rvm/gems/ruby-2.3.1"
GEM_PATH:     "/Users/Enno/.rvm/gems/ruby-2.3.1:/Users/Enno/.rvm/gems/ruby-2.3.1@global"
MY_RUBY_HOME: "/Users/Enno/.rvm/rubies/ruby-2.3.1"
IRBRC:        "/Users/Enno/.rvm/rubies/ruby-2.3.1/.irbrc"
RUBYOPT:      ""
gemset:       ""
```

**Comment by LeEnno** [comment]
>  I thought I read a comment from Sublime's creator adding some callback and everyone wildly celebrating that and referencing the corresponding issue. Dream or memory? 🤔

I found what I meant back then: https://github.com/SublimeTextIssues/Core/issues/1877

I honestly don't understand it completely but you are probably aware of it and it probably doesn't fix anything?

**Comment by kaste** [comment]
Well, that's a lot of stuff rvm-auto-ruby sets here. So the question is, if you set all these ENV variables in the SL settings and executable to `/Users/Enno/.rvm/rubies/ruby-2.3.1/bin/ruby`, does it work? If this works, is there a minimal set of vars we absolutely have to set? How could we automate this?

**Comment by LeEnno** [comment]
This seems to work on every start now:

```
"env": {
  "GEM_PATH": "/Users/Enno/.rvm/gems/ruby-2.3.1:/Users/Enno/.rvm/gems/ruby-2.3.1@global",
  "PATH": "/Users/Enno/.rvm/gems/ruby-2.3.1/bin:/Users/Enno/.rvm/gems/ruby-2.3.1@global/bin:/Users/Enno/.rvm/rubies/ruby-2.3.1/bin:/Users/Enno/.rvm/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
},
"executable": "/Users/Enno/.rvm/rubies/ruby-2.3.1/bin/ruby"
```

**Comment by kaste** [comment]
Hi @LeEnno! Can you check #1509? It patches the environment Sublime uses, and it also prints a diff between the environment Sublime had and what you usually get on the Terminal/shell. 

That should make it super easy 🤞 to spot any differences. If there are any significant changes, you could also try to undo/unset all the above settings. Maybe it will work automagically after that change.

**Comment by LeEnno** [comment]
Test 1) Running `subl` from user folder (`/Users/Enno`) in terminal:

```
<> Running: '/bin/bash -ilc env'
<> Finished in 0.51s
<> Environment will change!
-> Changed:
_=/usr/bin/env
 |/usr/local/bin/subl (previous value)
SHLVL=2
     |1 (previous value)
PWD=/Applications/Sublime Text.app/Contents/MacOS
   |/Users/Enno (previous value)
```

Test 2) Running `subl` from a project folder (`/Users/Enno/Sites/pictrs/master/pictrs`) in terminal:
*(As a reminder: 2.3.1 is my project's ruby, 2.2.4 is rvm's default on my system.)*

```
<> Running: '/bin/bash -ilc env'
<> Finished in 0.54s
<> Environment will change!
-> Changed:
SHLVL=2
     |1 (previous value)
_=/usr/bin/env
 |/usr/local/bin/subl (previous value)
PATH=/Users/Enno/.rvm/gems/ruby-2.2.4/bin:/Users/Enno/.rvm/gems/ruby-2.2.4@global/bin:/Users/Enno/.rvm/rubies/ruby-2.2.4/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/VMware Fusion.app/Contents/Public:/Users/Enno/.rvm/gems/ruby-2.2.4/bin:/Users/Enno/.rvm/gems/ruby-2.2.4@global/bin:/Users/Enno/.rvm/rubies/ruby-2.2.4/bin:/Users/Enno/.rvm/gems/ruby-2.3.1/bin:/Users/Enno/.rvm/gems/ruby-2.3.1@global/bin:/Users/Enno/.rvm/rubies/ruby-2.3.1/bin:/Users/Enno/.rvm/bin:/Users/Enno/.rvm/bin
    |/Users/Enno/.rvm/gems/ruby-2.2.4/bin:/Users/Enno/.rvm/gems/ruby-2.2.4@global/bin:/Users/Enno/.rvm/rubies/ruby-2.2.4/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/VMware Fusion.app/Contents/Public:/Users/Enno/.rvm/gems/ruby-2.3.1/bin:/Users/Enno/.rvm/gems/ruby-2.3.1@global/bin:/Users/Enno/.rvm/rubies/ruby-2.3.1/bin:/Users/Enno/.rvm/bin:/Users/Enno/.rvm/bin (previous value)
PWD=/Applications/Sublime Text.app/Contents/MacOS
   |/Users/Enno/Sites/pictrs/master/pictrs (previous value)
```

Test 3) Starting Sublime Text via GUI:

```
<> Running: '/bin/bash -ilc env'
<> Finished in 0.46s
<> Environment will change!
-> Added:
SHLVL=1
_=/usr/bin/env
PWD=/Applications/Sublime Text.app/Contents/MacOS
-> Changed:
PATH=/Users/Enno/.rvm/gems/ruby-2.2.4/bin:/Users/Enno/.rvm/gems/ruby-2.2.4@global/bin:/Users/Enno/.rvm/rubies/ruby-2.2.4/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/VMware Fusion.app/Contents/Public:/Users/Enno/.rvm/gems/ruby-2.2.4/bin:/Users/Enno/.rvm/gems/ruby-2.2.4@global/bin:/Users/Enno/.rvm/rubies/ruby-2.2.4/bin:/Users/Enno/.rvm/bin:/Users/Enno/.rvm/bin
    |/Users/Enno/.rvm/gems/ruby-2.2.4/bin:/Users/Enno/.rvm/gems/ruby-2.2.4@global/bin:/Users/Enno/.rvm/rubies/ruby-2.2.4/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/VMware Fusion.app/Contents/Public:/Users/Enno/.rvm/bin (previous value)
```

----------

Weird thing is: I removed the manual configuration mentioned in the comments above and linters seem to work fine now. Hooray, but... is this expected? The results tell me that env vars still seem to be kinda off, don't they?

If you need any more test results let me know. Happy to help.

**Comment by kaste** [comment]
Sure, this should fix env related problems, so that it 'just works'. 

@braver Note that env calls only take 0.5s, so Sublime itself actually runs a different thing to determine a 'good' user env. (Also: it's just `bin/bash` nothing fancy here.

**Comment by kaste** [comment]
Oops, thanks for testing of course @LeEnno 

It looks like we need to run this for each working / project dir to get the best possible ENV. (IIRC Atom runs this per window.)

To get at least consistent results, we could choose to run it from a 'neutral' dir. (E.g. `/Applications/Sublime Text.app/Contents/MacOS` in this case)

**Comment by braver** [comment]
@kaste .5s should be within the 1s window, but I'm not sure what Sublime does here or how the timeout works (it might be a 1s window for more things than getting the env). That said, on my machine your test file reports

```
<> Running: '/usr/local/bin/fish -ilc env'
<> Finished in 0.01s
<> Environment will change!
```

So, in contrast with that, .5s takes *ages*, and I don't think it's super weird that it hits that timeout anyway.

**Comment by kaste** [comment]
@braver Sublime runs without the `-i` (Atom and vscode both use `-il` and so I just went with that. If vscode does it it must be industry standard anyway.)
