### ISSUE TITLE
Linting all files

### ISSUE THREAD

**Issue by NathanDeckinga** [SublimeLinter/SublimeLinter#1487]
I'm sure this is something that I have done wrong, but I'll be damned if I can figure out where I took a left turn.  I recently got a new laptop and installed SublimeText + SublimeLinter + flake8 (among other things) and it all works - perhaps a bit too well.  Not only is it linting my python files, but it is also linting my text files, and my json files, and really everything I open.  None of which are valid python 3 syntax obviously.

I did my best to copy over my settings from my previous laptop, but the behavior I am seeing is different.  It is totally possible that I missed something, or that something changed in the versions I'm using, so my assumption is that I've got something wrong.  I have looked at the docs and I've tried a few things but nothing has worked to date.

Is this a real bug or is there a setting that I'm missing somewhere?  How do I get SublimeLinter to only lint the file types I want linted?  Or is this a flake8 setting?

**Comment by kaste** [comment]
My first guess is that you copy pasted the default settings to the user settings. And you maybe copied the selector setting, and set it to the empty string which would select all buffers.

**Comment by NathanDeckinga** [comment]
Thank you - that was it.  I didn't try that one as the comment said something about views as opposed to file types or extension.  But it looks right.

In case anyone else is searching for this : http://www.sublimelinter.com/en/stable/linter_settings.html?highlight=selector#selector
