### ISSUE TITLE
Windows Per-project Standards ${folder} slashes not escaped properly

### ISSUE THREAD

**Issue by bs-thomas** [SublimeLinter/SublimeLinter#1488]
Hello there,
I noticed on Windows 10 Pro 64bit, Sublime Text 3 environment, the ${folder} path is returning "C:wamp64wwwcodebase" (missing all the slashes).

The following is the console output in Sublime:

```
SublimeLinter: #75 linter.py:1263: Running ...

  C:\wamp64\www\codebase  (working dir)
  > type _laravel\packages\beamstyle\core\src\Helpers\DateTime.php | "C:\Users\Thomas Cheng\AppData\Roaming\Composer\vendor\bin\phpcs.bat" --report=emacs --standard=C:wamp64wwwcodebase/ruleset.xml --stdin-path=C:\wamp64\www\codebase\_laravel\packages\beamstyle\core\src\Helpers\DateTime.php -

SublimeLinter: #75 linter.py:955: phpcs output:
    ERROR: the "C:wamp64wwwcodebase/ruleset.xml" coding standard is not installed. The installed coding standards are MySource, PEAR, PSR1, PSR12, PSR2, Squiz and Zend

```

**Comment by bs-thomas** [comment]
https://github.com/SublimeLinter/SublimeLinter-phpcs/issues/40

**Comment by kaste** [comment]
That's a quoting thing. I assume you set `"args": "--standard=${folder}/ruleset.xml"`. If you change this to `"args": "--standard='${folder}/ruleset.xml'"` it should work 🤞. You can also try `"args": ["--standard=${folder}/ruleset.xml"]` (if you use an array, you should not quote).

Note that this is not a Windows thing, you would have to quote on the other systems as well.

🤔 For `cmd` we first call `shlex.split` then `substitute_vars`, for `args` the other way around. Seems like if we would do it the cmd-way we would get less quoting scenarios. I wouldn't want to do this without proper unit tests, honestly. 🤔

**Comment by bs-thomas** [comment]
Ah you're suggestion with arrays seemed to work for me.  I think that's good enough as long as I'm not in the hard-coding deadend.

Thank you very much @kaste !
