### ISSUE TITLE
Sublime Linter works, but does not appear in tools menu

### ISSUE THREAD

**Issue by jimgreer** [SublimeLinter/SublimeLinter#1489]
I'm having a strange problem. I've installed SublimeLinter and SublimeLinter-eslint. It works in that it's showing errors, but it doesn't show in the tools menu. This is an issue because I want to run the linter manually, not automatically. I'm not sure how to do this if it isn't in the menu.

I don't see any errors in the console.

**Comment by kaste** [comment]
SublimeLinter v4 doesn't add anything to the 'Tools' menu. In the context menu you'll find 'Lint this view' though, otherwise use the command palette (ctrl+p), or `["ctrl+k", "l"]`

**Comment by braver** [comment]
In Sublime Text, you can find commands in the command palette, not in one of the menus.

**Comment by jimgreer** [comment]
Ok, I'm dumb. Thank you.

**Comment by braver** [comment]
Well, I doubt that’s the case 😉 so I take it as good feedback on the discoverability of features, but in general packages don’t expose commands via the menus.
