### ISSUE TITLE
Identification of errors in the code PHP/JS/CSS/HTML

### ISSUE THREAD

**Issue by Development-IT** [SublimeLinter/SublimeLinter#1494]
Tell me how to properly configure the ability to highlight errors in the code PHP/JS/CSS/HTML? After updating the package, the old instructions do not work.

**Comment by braver** [comment]
Look for the linter plugins in package control for each language (e.g. PHP lint, PHP cs, eslint, stylelint, html tidy). Each should have installation and configuration information for your operating system in their readme. If there is anything specific you need help with, let us know.

**Comment by Development-IT** [comment]
It is necessary to prescribe the way to PHP. Old instructions do not work. Can you reset the link to a new one?

**Comment by braver** [comment]
The instructions for PHP look current to me. What are the “old instructions” you mentioned?

**Comment by Development-IT** [comment]
https://habr.com/post/262137/
Can you reset the current instruction for the languages I have specified? While only managed to configure error control in the HTML and PHP. JS and CSS remain open. Which error interpreter is better to use? Nodejs does not work.

**Comment by braver** [comment]
Are you asking me to correct that blog post? Why not ask the author? I can't even read Cyrillic.

For eslint and stylelint you need nodejs, there is no alternative. Please refer to the readmes of those plugins to set it up.
