### ISSUE TITLE
Installation of SublimeLinter v4.8.0 fails

### ISSUE THREAD

**Issue by dopexxx** [SublimeLinter/SublimeLinter#1495]
I'm a Sublime user trying to install SublimeLinter. I followed the installation [guide](http://www.sublimelinter.com/en/v3.10.10/installation.html) and installed SublimeLinter version 4.8.0. However, I can't lint anything ("lint this view", `Ctrl+Cmd+L`) and also I can't change the lint mode, i.e. if I use PackageControl to type `SublimeLinter: Choose Lint Mode` nothing shows up.

OS: High Sierra
Sublime: 3.1.1

**Comment by kaste** [comment]
Which linter plugins have you installed? The lint_mode can be changed in the settings `Preferences: SublimeLinter Settings`. Maybe you should enable debug mode and see in the console `View > Show/Hide Console` if something happens at all, or log a hint.

**Comment by dopexxx** [comment]
Under `Preferences`, I do not see any `SublimeLinter Settings`. I enabled debug mode and when I start Sublime it shows (among other stuff):

`
reloading plugin SublimeLinter.__init__
reloading plugin SublimeLinter.active_linters_view
reloading plugin SublimeLinter.busy_indicator_view
reloading plugin SublimeLinter.goto_commands
reloading plugin SublimeLinter.highlight_view
reloading plugin SublimeLinter.log_handler
reloading plugin SublimeLinter.message_view
reloading plugin SublimeLinter.panel_view
reloading plugin SublimeLinter.status_bar_view
reloading plugin SublimeLinter.sublime_linter
`

and then, if I e.g. try to lint the selected view it says:
`command: sublime_linter_lint`

And still, no lintering is performed at all...
Any ideas?

**Comment by dopexxx** [comment]
It's a completely fresh version of Sublime, I just installed `PackageControl` and `SublimeLinter`

**Comment by kaste** [comment]
OK, you first have to decide which linter you want to use. For example, if you're doing javascript. You may choose `eslint` as your linter. Make sure to install that linter `npm install eslint` using the command line. 

Regardless of the linter you use, first install the linter, then install a SublimeLinter plugin which acts as a bridge between this command line linter and SublimeLinter itself. See https://packagecontrol.io/browse/labels/SublimeLinter for the available plugins.
