### ISSUE TITLE
Do not search for global cmd in (overriden) `context_sensitive_executable_path`

### ISSUE THREAD

**Issue by kaste** [SublimeLinter/SublimeLinter#1503]
Found via #1501 

https://github.com/SublimeLinter/SublimeLinter/blob/aad20f8a8dec07ad3f184009874eb123b333d7eb/lint/base_linter/node_linter.py#L56-L63

You can probably find the same line in ComposerLinter. 

It should be possible to just return `False, None` here, and SublimeLinter will search for a global cmd.

**Comment by braver** [comment]
@kaste that doesn't sound like a big change?

**Comment by kaste** [comment]
It's trivial but at time I was already writing the tests. And this particular line/block of code is not covered by tests yet. 

Ideally we first write the test to protect our features, then change the code, and since it is a non-breaking internal refactoring the test should remain as before. 🙄

**Comment by kaste** [comment]
FWIW the reason for the duplicated code was to improve the error message. `PythonLinter` has a hint to fill in the 'python' setting. 

For node, we could remind the user to 'npm [-g] install eslint'.

**Comment by kaste** [comment]
No need to remove duplicated code as we want in the long run better error messages in the long run. Actually, `NodeLinter` has improved a lot here, `PythonLinter` is okay and I may improve it as I've seen some small niceties in vim's ale, and `Composer` and `Ruby` are just rotten 🤷‍♂.
