### ISSUE TITLE
Disabling gutter icons via "None" doesn't work?

### ISSUE THREAD

**Issue by spacesuitdiver** [SublimeLinter/SublimeLinter#1504]
This issue (https://github.com/SublimeLinter/SublimeLinter/issues/469) seems to suggest that one can specify "None" for the `gutter_theme` in order to disable gutters. This doesn't seem to work with later version of SublimeLinter. 

Can anyone assist in how I might disable gutters (I primarily lint using the panel and inline marks)? Thanks!

EDIT (solved), should be as easy as adding this to styles (globally).
```
    "styles": [
        {
            "icon": "none",
        }
    ]
```

**Comment by braver** [comment]
🎉
