### ISSUE TITLE
(bug) mark style: fill isn't working

### ISSUE THREAD

**Issue by codesurgery** [SublimeLinter/SublimeLinter#1505]
Seems that on my version of the latest Sublime Text build 3175, on Mac OS Mojave, mark style: fill isn't showing anything.

I've been wondering why it's not highlighting for ages, when I switched to outline it started working again.

Here's some screenshots to show (as you can see, only fill style filled is not displaying correctly):

<img width="1216" alt="screen shot 2018-10-05 at 7 36 30 pm" src="https://user-images.githubusercontent.com/43038457/46553918-add87200-c8d6-11e8-9e20-b01f5df84eff.png">
<img width="1219" alt="screen shot 2018-10-05 at 7 36 45 pm" src="https://user-images.githubusercontent.com/43038457/46553919-ae710880-c8d6-11e8-8a1f-b8850075c89b.png">
<img width="1220" alt="screen shot 2018-10-05 at 7 36 59 pm" src="https://user-images.githubusercontent.com/43038457/46553920-ae710880-c8d6-11e8-83b2-7735cb29f326.png">
<img width="1219" alt="screen shot 2018-10-05 at 7 37 13 pm" src="https://user-images.githubusercontent.com/43038457/46553921-ae710880-c8d6-11e8-9fb9-2184263c6604.png">
<img width="1218" alt="screen shot 2018-10-05 at 7 37 31 pm" src="https://user-images.githubusercontent.com/43038457/46553922-ae710880-c8d6-11e8-8c4b-342f8b6ed290.png">

**Comment by kaste** [comment]
Hi!

`fill` generally works for me 🤔 	

![image](https://user-images.githubusercontent.com/8558/46559010-42e76500-c8ef-11e8-941b-189ffb7b15fe.png)

Could you try different `scope` values

Latest version is 3176 btw.

**Comment by minikN** [comment]
> @minikN I can't recreate the issue at all, fill works just fine with those settings. I need more information to look into this, screenshots/captures also help.

Alright, no problem.
`"mark_style" : "outline"`
![image](https://user-images.githubusercontent.com/1888338/50724612-c97b3080-10f0-11e9-9770-a195cda559c1.png)

`"mark_style" : "solid_underline"`
![image](https://user-images.githubusercontent.com/1888338/50724621-034c3700-10f1-11e9-8692-e323a5208e09.png)

The same works for every other style, however with `"mark_style" : "fill"`
![image](https://user-images.githubusercontent.com/1888338/50724634-2aa30400-10f1-11e9-86d5-6900e7a286d7.png)

This happens.
SublimeLinter version `4.9.0`
SublimeLinter-php version `1.3.0`

**Comment by braver** [comment]
What happens when you switch to the Adaptive theme and the Mariana color scheme?

**Comment by minikN** [comment]
> What happens when you switch to the Adaptive theme and the Mariana color scheme?

Yep you are right. It works that way. The theme is not the problem. But the color scheme. If I select any Monokai Pro color scheme it doesn't work. Using any of the standard sublime color scheme (even with the Monokai Pro theme) works.

Damn. Guess I need to create another issue over at their GitHub.

**Comment by braver** [comment]
Well, glad we figured that out 👍

**Comment by minikN** [comment]
> Well, glad we figured that out

Absolutely. Thanks for the assistance.
