### ISSUE TITLE
Show output panel when linting manually

### ISSUE THREAD

**Issue by redtopia** [SublimeLinter/SublimeLinter#1510]
Is it possible to show linter output in the console when linting manually? The behavior I want is when I hit CTL-K, "L" (manual lint), a linter job is executed, and the console opens up with the output. Currently, I need to hit CTL-K, "L" followed by CTL-K, "A".

**Comment by redtopia** [comment]
Thank you for the suggestions... something is not working (I have never created a ST command). When I hit the key binding, nothing happens. I put the .py file in `C:\Users\JP\AppData\Roaming\Sublime Text 3\Packages\User\` What can I do to figure out why it's not being called, or to debug?

**Comment by kaste** [comment]
Open the Sublime console. (View > Show Console)

After that, save the file you created. It should log 'reloaded ...'. If we did a typo and it won't compile it should show a traceback. Now you can try to invoke the key binding and see if it throws.

Put a 'print("hello")' inside the run function to see if the command actually runs.

**Comment by redtopia** [comment]
Looks like there's a problem:

```
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 116, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 853, in _load_module
  File "<frozen importlib._bootstrap>", line 980, in get_code
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "C:\Users\JP\AppData\Roaming\Sublime Text 3\Packages\User\run_lint_in_panel.py", line 8
    self.window.run_command("show_panel", {"panel": panel_view.OUTPUT_PANEL})
                                                                            ^
TabError: inconsistent use of tabs and spaces in indentation
```

**Comment by kaste** [comment]
Yeah, okay that comes from editing here in GitHub. You can convert tabs to spaces in Sublime and save again.

I also updated the code above, but Github doesn't show WS chars so it's not so easy to get this correct here.

**Comment by redtopia** [comment]
Thanks... looks like it's compiling properly now, but nothing is running. Where exactly would I put the `print("hello")` call? I'm not a Python programmer, so I don't know the call stack here... how does the `LintAndPanel.run()` method get called?

**Comment by kaste** [comment]
Here:

```
class LintAndPanel(sublime_plugin.WindowCommand):
    def run(self):
        print('hello')
        self.window.run_command("sublime_linter_lint")
        self.window.run_command("show_panel", {"panel": panel_view.OUTPUT_PANEL})
```

**Comment by kaste** [comment]
Hm, I have it working. Do you have setup a key binding without typo. I usually fail here 😬 

```
  { "keys": ["ctrl+alt+shift+l"], "command": "lint_and_panel" },
```

Sometimes, when there was a really bad error in a file, you have to restart Sublime bc it won't reload the file correctly after. (Of course, it will tell you it just reloaded, 🙄.)

**Comment by redtopia** [comment]
Maybe a little progress here... I created a new key binding file, and now I'm getting:

```
Unable to parse binding [{command: run_lint_in_panel, keys: [ctrl+alt+shift+l]}]
```

My key binding file looks like this:

```
[
	{ "keys": ["ctrl+alt+shift+l"], "command": "run_lint_in_panel" }
]
```

My command file is named `run_lint_in_panel.py` and is located in: `C:\Users\JP\AppData\Roaming\Sublime Text 3\Packages\User`

**Comment by kaste** [comment]
The command is called `lint_and_panel` just like the class. (You define multiple commands in a file.)

**Comment by redtopia** [comment]
That clarifies things... I didn't understand how the names are mapped. It's running now... however, it looks like it's executing lint on more than just the open file. Any ideas? It's better than nothing, but maybe there's a different set of commands that would execute the linter only on the open file.

**Comment by redtopia** [comment]
Maybe the console doesn’t get cleared and that’s what’s confusing.

**Comment by kaste** [comment]
Yeah, that's the feat request at #1415 probably.

**Comment by kaste** [comment]
Closing since it looks resolved.
