### ISSUE TITLE
How to produce the beautiful linting shown in the example screenshot?

### ISSUE THREAD

**Issue by Ornataweaver** [SublimeLinter/SublimeLinter#1512]
What shortcut should I use?
(We found this later: in Command Palette type "SublimeLinter: Show All Errors" with the shortcut "ctrl+cmd+A" 🍺, producing the beauty I first saw in this repo 👌)

I tried building,
Command Palette,
installing many other linters,
etc.

All I get when I build is a colorless white text showing errors. Which shows full paths and is boring to read. And explanations are too long.

**Comment by braver** [comment]
Can you share a screenshot of what you're getting? It's a bit hard to guess what you're looking at :)

**Comment by Ornataweaver** [comment]
Of course, thanks.
I thought this error was because of "pydocstyle" and didn't see "SublimeLinter" in it before.
I reinstalled pydocs style and yet I get "No such file or directory: '/usr/local/bin/pydocstyle'", although the binary exists at the address.

<img width="1440" alt="screen shot 2018-10-26 at 11 35 08 am" src="https://user-images.githubusercontent.com/27126408/47553620-66149b80-d914-11e8-837a-7270b0e4d35e.png">

For example, I didn't define 'a' to get an error and when I build I get this:

<img width="1440" alt="screen shot 2018-10-26 at 11 35 15 am" src="https://user-images.githubusercontent.com/27126408/47553629-69a82280-d914-11e8-9f70-ee7f7416b778.png">

**Comment by braver** [comment]
Ok, some things to cover here:

- SublimeLinter doesn't do anything with the build system. You set it up and it runs in the background. You can set up a build system to do similar things, but then it doesn't touch any of SL's features like the markers, output panel etc.

- You seem to have set up flake8, pep8, pydocstyle and pylint, but none of them work (they display as "erred" in the status bar). Your first screenshot tells you what's wrong, it cannot find the executables. 

To find out what's going on, check our [troubleshooting guide](http://www.sublimelinter.com/en/stable/troubleshooting.html) for more information. If you can't get it to work with that, please report back with a debug log.

**Comment by Ornataweaver** [comment]
I think the problem is not with pydocstyle but with my python:
```bash
bash: /usr/local/bin/pydocstyle: /usr/local/opt/python/bin/python2.7: bad interpreter: Not a directory
```
I got this when I tried to run 'pydocstyle' in Terminal.

pep8 and flake8 seem to be working:
<img width="1440" alt="screen shot 2018-10-26 at 7 47 54 pm" src="https://user-images.githubusercontent.com/27126408/47579183-22dc1c00-d958-11e8-86f0-8c5355862a0b.png">

Would you tell me the name of the linter in the screenshot? Thanks.
I also suggest you consider adding the name under the image.

**Comment by braver** [comment]
You're definitely having issues though, you should fix those first:
<img width="184" alt="screen shot 2018-10-26 at 18 57 03" src="https://user-images.githubusercontent.com/2543659/47581157-f7a1fe80-d950-11e8-9d10-eb65f700bfb1.png">

The example screenshot already notes the linters in use...?

**Comment by Ornataweaver** [comment]
Thanks, I disabled all except "pycodestyle" and "pylint". Then installed "pycodestyle" with "brew" for mac, and "pylint" with "pip install pylint".
This solved the errors.

then in Command Palette I found "SublimeLinter: Show All Errors" with the shortcut "ctrl+cmd+A" 🍺, producing the beauty I first saw in this repo 👌:
<img width="1440" alt="screen shot 2018-10-26 at 10 03 03 pm" src="https://user-images.githubusercontent.com/27126408/47585817-4e1c3680-d96b-11e8-918b-9b1d9a08ff34.png">

This finishes this issue.
• I suggest adding a hint to "SublimeLinter: Show All Errors" below the example for beginners like me.
• Why installing linters via SublimeLinter gave errors, and installing them via brew and pip solved them?
Should we close this issue?

**Comment by braver** [comment]
> I suggest adding a hint to "SublimeLinter: Show All Errors" below the example for beginners like me.

Yeah we could do a bit better with documentation. Noted!

> Why installing linters via SublimeLinter gave errors, and installing them via brew and pip solved them?

SublimeLinter is merely an interface to the command line utilities, you need to install the utilities themselves as well. The documentation clearly points that out, but I guess it can be missed especially if you’re new to this thing.

**Comment by Ornataweaver** [comment]
Thank you for your time.

**Comment by kaste** [comment]
🎉

**Comment by Ornataweaver** [comment]
I thought about adding an issue called "Things to add to Documentation" or "Things to add to README.md".
Then add
• (in Command Palette type "SublimeLinter: Show All Errors") under the image in readme.
As one of the options to it.

What do you think?
