### ISSUE TITLE
Run tests automatically against master and PRs

### ISSUE THREAD

**Issue by kaste** [SublimeLinter/SublimeLinter#1514]
Ideally we use a different service for the tests so that Travis and the "other thing" can run in parallel. 

Multi-Platform is not important bc we currently don't have tests that should behave differently here.

**Comment by braver** [comment]
How does one run the tests now? With some more info I might be able to set it up.

**Comment by kaste** [comment]
Just install the UnitTesting package https://github.com/SublimeText/UnitTesting

Maybe restart 3 times 🙄. Then run Test Current Package or File. 

Super easy

**Comment by kaste** [comment]
https://github.com/SublimeText/UnitTesting/blob/master/README.md#appveyor-ci on how to integrate this

**Comment by kaste** [comment]
When you're at it. Can you update Travis integration to GithubApp or how is this called now. I think they integrate the failures now in the GitHub UI. My Hope is that they show lint errors basically inline.

**Comment by braver** [comment]
@kaste I have already enabled the Travis "app" integration for the entire SublimeLinter org, but as I understand it open source projects still need to be migrated to travis.com by them.

**Comment by kaste** [comment]
Ok, then they're way behind. The planned rollout was Q2. And I think they wanted to retire the old "thing" in October.

Okay, this is basically running on travis now. codecov.io must have been enabled sometime before bc it shows old data although we didn't had any coverage bc we didn't had any tests. It also just uploaded and commented on the PR.

**Comment by braver** [comment]
Yeah, there used to be some test and a coverage check. Coverage was around a measly 10% and it would complain when it went down just 0,1% because some community contribution changed something. Also, nobody knew what it tested or how it worked, so we ditched the tests and coverage check late last year.
