### ISSUE TITLE
how to change icons? 

### ISSUE THREAD

**Issue by matianhe** [SublimeLinter/SublimeLinter#1522]
<img width="67" alt="screen shot 2018-11-26 at 18 47 19" src="https://user-images.githubusercontent.com/24929062/49009519-bdc05400-f1ab-11e8-9fef-8fc557d62312.png">
Are there built in?

**Comment by matianhe** [comment]
I want to use heart.

**Comment by braver** [comment]
The default settings have a lot of information in them, have a look at [the part about styles](https://github.com/SublimeLinter/SublimeLinter/blob/master/SublimeLinter.sublime-settings#L157).

**Comment by matianhe** [comment]
The heart icon is not there?
I try this     
- Blueberry Cross 
- Blueberry Round
- Circle
- Danish Royalty
……

**Comment by braver** [comment]
That's the icon theme, you need to select an icon from that theme (Default in this case): https://github.com/SublimeLinter/SublimeLinter/blob/master/SublimeLinter.sublime-settings#L195
