### ISSUE TITLE
SublimeLinter is not showing in Package Control

### ISSUE THREAD

**Issue by ndrc81** [SublimeLinter/SublimeLinter#1523]
I see that this issue was also raised in Feb  25 - 27 but it appears to be back again.  I am unable to find SublimeLinter in Package Control in Sublime Text.  I am using the Unregistered Version (during my trial period - so far only two weeks), V3.1.1 Build 3176.

**Comment by braver** [comment]
Well it is still listed. What exactly do you mean by “is not showing”? Screenshot or it didn’t happen 😉

**Comment by ndrc81** [comment]
![image](https://user-images.githubusercontent.com/11664418/49149309-c2822680-f2d7-11e8-9dcf-e55d27ce9b6f.png)

I wish it wasn't true - but when I type SublimeLInter or Linter  in Package Control all I can see are the SublimeLinter-Plugins not the framework.

**Comment by braver** [comment]
In that view it won't show package you've already installed.

**Comment by kaste** [comment]
@ndrc81 You can have a package installed but *disabled*. Try the `enable package` command as well.

**Comment by ndrc81** [comment]
Thanks for the responses.  I will report back later when I can get back to my machine and try these out.  Cheers.

**Comment by ndrc81** [comment]
Ok - apologies for the noob mistake, I must have already installed SublimeLinter when I first installed Sublime 3.  There was likely never an issue - I am able to install the plugins successfully.  Thanks again for your patience.  Cheers.

**Comment by braver** [comment]
🎉
