### ISSUE TITLE
You replaced my local plugin with yours, without me asking.

### ISSUE THREAD

**Issue by envygeeks** [SublimeLinter/SublimeLinter#1524]
Today I started using SublimeText 3, so I decided to install your linter... then I decided that since your linter crashes the plugin host randomly, and sublimelinter-contrib-gometalinter is the reason, and it didn't do what I wanted, I would make my own linter, so I installed it, as soon as I restarted, you assumed I gave you permission to replace my plugin with your upstream sublimelinter-contrib-golint, which I did not want. A few questions

1.) What makes you better at managing my plugins than plugin manager?
2.) Why is it okay for you to replace a plugin that originates from me, and my repos.
3.) If I install a package locally outside of your stuff you should respect that

**Comment by envygeeks** [comment]
It was Sublime, taking the fight there.

**Comment by kaste** [comment]
You're basically wrong in your assumptions that *we* did that. With a bit of luck you can find a 'Backup' in the sibling folder of 'Installed Packages'.
