### ISSUE TITLE
SublimeLinter paths variable not working or ignored

### ISSUE THREAD

**Issue by Skarlso** [SublimeLinter/SublimeLinter#1525]
Hi!

So I setup a project where I have `phpcs` and `phpstan` installed into `vendor/bin`.

I was trying to setup configuration for the linter to pick this fact up and use that binary location with `paths` like this:

```json
// SublimeLinter Settings - User
{
    "linters":
    {
        "paths": {
            "linux": [],
            "osx": [
                "./vendor/bin"
            ],
            "windows": []
        },
        "phpcs":
        {
            "standard": "./phpcs.xml"
        },
        "rubocop":
        {
            "args":
            [
                "--config",
                "./.rubocop.yml"
            ],
            "use_bundle_exec": true
        }
    }
}
```

Or:

```json
// SublimeLinter Settings - User
{
    "linters":
    {
        "phpcs":
        {
            "standard": "./phpcs.xml"
        },
        "phpstan":
        {
            "paths":
            {
                "linux": [],
                "osx": [
                    "./vendor/bin"
                ],
                "windows": []
            }
        },
        "rubocop":
        {
            "args":
            [
                "--config",
                "./.rubocop.yml"
            ],
            "use_bundle_exec": true
        }
    }
}
```

The documentation is rather unclear on where I have to actually put this setting. Logic dictates that I want this setting under the linter I'm specifying a binary location for.

I also tried it under the Global user setting just for good measures.

Yet, all I'm getting is:

```
Please refer to the readme of this plugin and our troubleshooting guide: http://www.sublimelinter.com/en/stable/troubleshooting.html
reloading settings Packages/User/SublimeLinter.sublime-settings
error: Error trying to parse settings: Unexpected character, expected a comma or closing bracket in Packages/User/SublimeLinter.sublime-settings:23:9
reloading settings Packages/User/SublimeLinter.sublime-settings
SublimeLinter: WARNING: phpstan cannot locate 'phpstan'
Please refer to the readme of this plugin and our troubleshooting guide: http://www.sublimelinter.com/en/stable/troubleshooting.html
```

Which says it can't find `phpstan`.

```
❯ file vendor/bin/phpstan
vendor/bin/phpstan: a /usr/bin/env php script text executable, ASCII text
```

It is there.

Any help / advice please? I would rather not globally install phpstan.

Thanks!

**Comment by kaste** [comment]
You hit the dark side of SublimeLinter. `paths` is still an old setting coming from SublinterLinter version 3, and it is applied globally. It must be placed like here https://github.com/SublimeLinter/SublimeLinter/blob/f147f974321a227241db62c831958afda74491d5/SublimeLinter.sublime-settings#L121-L125 as a top key. (Yes, logic dictates it should go under a specific linter, but we're not there yet.)

**Comment by Skarlso** [comment]
Hi @kaste!

So, like this? 

```json
// SublimeLinter Settings - User
{
    "paths": {
        "linux": [],
        "osx": [
            "./vendor/bin"
        ],
        "windows": []
    },
    "linters":
    {
        "phpcs":
        {
            "standard": "./phpcs.xml"
        },
        "rubocop":
        {
            "args":
            [
                "--config",
                "./.rubocop.yml"
            ],
            "use_bundle_exec": true
        }
    }
}
```

This is the file that opens when I go [Preferences]->[Package Settings]->[SublimeLinter]->[Settings].

And I have it as global right there as top? And it still says phpstan not found. I'm starting sublime text via a symlink like `sublime .` to load the folder.

**Comment by kaste** [comment]
Yes, this looks okay. I would try an absolute path though. Maybe set 'debug' to 'true' here for now in case it outputs something interesting.

**Comment by Skarlso** [comment]
But the sample isn't using absolute path either. :D It's using `~`. :) But I'll try. :)

**Comment by Skarlso** [comment]
Yep, absolute path worked. :/

```
SublimeLinter: WARNING: phpstan output:
Note: Using configuration file /Users/gbrautigam/acquia/hosting-api/docroot/phpstan.neon.
Note: Using the option --errorFormat is deprecated. Use --error-format instead.
```

This is different but I know why this is. So. My problem is that the location can change from folder to folder and this is a global path. That's why I wanted it to be relative. And that's why I didn't wanted to install it globally because different projects use different versions and settings of phpstan. 

Ah well, I see now. Thanks. I hope this is in the works. :D

**Comment by kaste** [comment]
I think we expand `~` normally but the `.` changes its meaning. 

Now, if you actually installed the binary within a 'virtual env' underneath your project, you can try the following: 

Instead of defining `paths` you can for example set `executable` to `${folder}/vendor/bin/phpcs`

```
    linters:
		phpcs:
			executable: "${folder}/vendor/bin/phpcs"
```

**Comment by kaste** [comment]
Now, `vendor/bin` looks like composer, and it should actually pick that by default if it finds a `composer.json` in the project root.

**Comment by kaste** [comment]
👍
