### ISSUE TITLE
Syntax Error in contrib.json

### ISSUE THREAD

**Issue by MadimetjaShika** [SublimeLinter/SublimeLinter#1531]
Hi There,

In an attempt to migrate my Sublime config to a new machine, I got errors that both ``SublimeLinter`` and ``SublimeLinter-eslint`` could not be found on the package repo. After digging deeper, [Package Control](https://packagecontrol.io/packages/SublimeLinter) reports a parse error on the ``contrib.json`` file, which appears to be rendering both plugins unavailable on Package Control.

There's an unexpected comma in the JSON file,

<img width="1107" alt="screenshot 2019-01-04 at 11 54 51" src="https://user-images.githubusercontent.com/6643245/50682943-21deff00-1019-11e9-91b3-b6e2cd9b947e.png">

Not too sure where one can edit this file to submit a PR? Or could someone please fix the syntax error.

Thanks.

**Comment by kaste** [comment]
Thanks for reporting.
