### ISSUE TITLE
InvalidCertificateException - sublimeText3

### ISSUE THREAD

**Issue by ftslo** [SublimeLinter/SublimeLinter#1536]
Not sure if this is the correct channel to post this issue. 

Ever since updating to Mac OSX Mojave 10.14.2, SublimeText 3 has displayed the following console notifications on start up of the program.

```
Package Control: Error downloading package. HTTP exception InvalidCertificateException (Host codeload.github.com returned an invalid certificate ([SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:548))) downloading https://codeload.github.com/SublimeLinter/SublimeLinter/zip/4.9.1.
error: Package Control

Unable to download SublimeLinter. Please view the console for more details.
reloading settings Packages/User/Preferences.sublime-settings
```

Is this something that is handled by the plugin writer or by SublimeText or GitHub? Thanks.

**Comment by kaste** [comment]
Generally, this is more a `PackageControl` issue. PackageControl had some problems and was down the last days. Maybe this is related.
