### ISSUE TITLE
Improve orientation in error panel

### ISSUE THREAD

**Issue by kaste** [SublimeLinter/SublimeLinter#1549]
For testing you need to have more errors than fit on screen, also ideally coming from multiple files.

- If you navigate your buffer, it looks like we're showing the error line always in the middle of the panel, which results in visual clutter bc the panel always scrolls back and forth.

- Almost never, the current filename line is at the top of the panel. 

Instead, we should try to scroll so that the current filename gets on the first shown line of the panel. Navigating within a file should only scroll if necessary. We should try to avoid scrolling too much. Errors from the next file should not appear if possible (t.i. if we still have enough errors to show from the current active file).

**Comment by braver** [comment]
You may remember I was never a fan of all the scrolling and the “cursor” in the first place. I could get behind a solution that tries to do less. If you have a lot of output in the panel and you try to make sense of it, you can interact with the panel to navigate. Put the user in control of the panel. I do like the idea of it scrolling to the currently active file when you open the panel though. Or, optionally, have only the current file in the panel.
