### ISSUE TITLE
Shall we keep a changelog ?

### ISSUE THREAD

**Issue by asfaltboy** [SublimeLinter/SublimeLinter#1551]
1. I found it odd that SublimeLinter doesn't have a history/changelog file or related page in docs.
  Some reasoning for doing this can be found here: https://keepachangelog.com/en/1.0.0/
  By the way, messages for package-control are short and informative and should be kept that way, while still pointing at the full changelog (useful for maintainers / developers of related linter plugins).

2. Specifically, what brought me here today, was looking for the change that deprecated `util.communicate`, and what is the recommended action, while looking into alecthomas/SublimeLinter-contrib-gometalinter#24

**Comment by braver** [comment]
We have basically two maintainers, one and a half really, and most of the plugin authors don’t actively maintain their plugins. I.e. if we break something we go out and open issues and PR’s across the ecosystem where needed. We could have spent the hours needed to maintain a log on the off chance it might save someone else a few minutes, but it’s simply not efficient. This is GitHub, it already has a log and a search feature. And you can ask questions here too.

So, that’s why we don’t have a log.

I’m only half a maintainer, perhaps @kaste will be able to tell you more about your particular case.

**Comment by kaste** [comment]
I love changelogs but we have to be realistic here that's true. It is not that a changlog is  *generally* too much work but the lack of interest doesn't justify it. 

Currently we are in a 'ask us anything' phase. 

Now you actually also stumbled upon a stupidly short deprecation message. We usually write better ones and they should be helpful and lead the reader to a solution. 

So TLDR currently I'm committed rather to write good deprecation messages but a changelog. This way we can have tests around them, and basically they form some inline documentation.

**Comment by braver** [comment]
@asfaltboy please file a specific issue if you need help with anything.
