### ISSUE TITLE
icu4c version 62 no longer available for Mac

### ISSUE THREAD

**Issue by OKNoah** [SublimeLinter/SublimeLinter#1555]
I can no longer find a way to install icu4c 62/62.1 on Mac. `brew install icu4c` gets version 63.1. Doing `brew log icu4c` no longer shows any 62/62.1 results.

icu4c seems to be a dependency of this plugin. Is there a way it can be bumped to version 63?

Also, the official website does not list a Mac version: http://site.icu-project.org/download/62#TOC-ICU4C-Download

**Comment by OKNoah** [comment]
So the steps to fix the missing icu4c errors are:

```
git -C (brew --repo homebrew/core) fetch --unshallow 
cd (brew --prefix)/Homebrew/Library/Taps/homebrew/homebrew-core
git checkout 575eb4b -- Formula/icu4c.rb
brew uninstall  --ignore-dependencies icu4c
brew install icu4c
```

The first step is the one I just added to fix the problem of no 62 versions being in the log.

**Comment by kaste** [comment]
You're probably in the wrong repo.

**Comment by OKNoah** [comment]
@kaste Why do you say that? I was getting an error from SublimeLinter that icu4c was not found.

**Comment by kaste** [comment]
Well I never heard of icu4c. Can you provide a screenshot or log?

**Comment by braver** [comment]
> I was getting an error from SublimeLinter that icu4c was not found

What does this mean? Screenshot or it didn't happen. We don't use icu and certainly don't expect you to `brew install` anything.

**Comment by OKNoah** [comment]
@kaste It seems that Node requires the icu4c files. However, Node in my terminal requires version 63 and yet the error in Sublime says version 62. I don't know how Sublime plugins work, but does it use another version of Node or something?

Currently I can't run Node and SublimeLinter at the same time, which obviously makes development hard.

@braver This is a really rude response and I'm not going to engage with you except to say that if you truly think I'm joking, go look at my years of Github contributions and ask why I'd suddenly start making up completely unentertaining stories about errors.

**Comment by kaste** [comment]
We don't use node. Sublime plugins are written in python.

**Comment by OKNoah** [comment]
@kaste That's what I thought. For now I've switched back to 62.1 and changes the default node to 8.11.4 and both seem to be working. Hopefully it stays that way. Thanks anyway for the help. Hopefully if anyone else runs into it they'll find this post.

**Comment by kaste** [comment]
🤷‍♂️

**Comment by braver** [comment]
@OKNoah sorry, didn’t mean to be super rude. But “an error” is not a detailed enough report for us to follow up on. Screenshots would’ve provided the necessary contact.
