### ISSUE TITLE
linter(erred) shown even though 'disable_if_not_dependency' is True

### ISSUE THREAD

**Issue by KidkArolis** [SublimeLinter/SublimeLinter#1559]
I'm working on a SublimeLinter plugin: https://github.com/KidkArolis/SublimeLinter-contrib-healthier.

I'm turning on the following default in the next version:

```
defaults = {
  ...
  'disable_if_not_dependency': True
}
```

I think that makes sense for most npm based linters, especially these more niche ones. In any case, right now, in the status bar I'm still getting `healthier(erred)` in every project, even if the project doesn't depend on healthier.

It's because, this line calls notify_failure when no bin is found even if   'disable_if_not_dependency': True is configured.

https://github.com/SublimeLinter/SublimeLinter/blob/1152b89b386e17f3da6d9520392e2370d4bb4b9e/lint/linter.py#L955-L958

I can open a PR that takes into account `disable_if_not_dependency` before calling notify_failure in this case? In the meantime, I'm exploring if I can use a custom cmd to workaround this issue.

**Comment by KidkArolis** [comment]
With my custom run method I now see `healthier(ok)` instead of `healthier(erred)` which maybe is better. Or is it? I guess I was hoping to disable the plugin if the project is not depending on this package.

Wondering what you think about this aspect / if you've discussed this before?

**Comment by kaste** [comment]
So apparently nobody uses this switch 👌 

Honestly, it shouldn't say 'ok' nor 'erred'. The correct behavior is that 'healthier' doesn't appear in the status bar at all 😁 

And actually ... I think ... something like this must be implemented in `can_lint_view`. 

Well, the docstring in `context_sensitive_executable_path` says `Return (True, None) if you want to skip the linter` but honestly this is .. vague?  At this point, you can actually only say skip-me-for-now. This is the same as throwing `TransientError` here or in `split_match` or whatever.

**Comment by kaste** [comment]
(`build_cmd` is not a safe API for end-users)

**Comment by KidkArolis** [comment]
I could have a look at this. But at first glance it seemed non trivial, because can_lint_view is a class method and all the node linter executable finder code is instance methods.

**Comment by kaste** [comment]
That's what I thought. Honestly, that code is super old object-oriented mess. Whenever I look at it I close the file. It's basically 100 lines of code for 'find the nearest 'package.json' given a path'.

**Comment by kaste** [comment]
(It's all instance methods because the cache(!) is on the instance but we throw away the instance after usage bc we run linters in parallel and don't want mutation hell. Read alone `read_manifest` where it actually reads the package.json file twice, once inline, once indirect via `hash_manifest`.)

**Comment by kaste** [comment]
I was able to make a not-totally-ugly PR at #1565 😅
