### ISSUE TITLE
Can't disable linters in User Settings or Project 

### ISSUE THREAD

**Issue by jtleathers** [SublimeLinter/SublimeLinter#1561]
I'm trying to disable phpcs and eslint for a specific project but the following code does not work even after closing the project and closing Sublime Text. Is there something else that needs to be done?

```
{
	"folders":
	[
		{
			"path": "D:\\www\\marinacalendar"
		}
	],
    "settings": {
        "SublimeLinter.linters.eslint.@disable": true, 
        "SublimeLinter.linters.phpcs.@disable": true,
	}
}
```

I have also just tried disabling phpcs in user settings but this doesn't work either:
```
{
	"linters":{
		"phpcs": {
		    "@disable": true,
		    "args": ["--standard=WordPress-Core"],
		    "excludes": [],
		    "standard": "WordPress"
		},
		"eslint": {
		    "@disable": true,
                },
	}
}
```

I'm running the following: 
Sublime Text v3.1.1
SublimeLinter v4.9.4
SublimeLinter-phpcs v2.3.0
SublimeLinter-eslint v4.1.5 

I have to disable/enable SublimeLinter-phpcs and SublimeLinter-eslint when switching between projects as it's the only way I can find to turn them off.

Any help would be much appreciated. Thanks.

**Comment by braver** [comment]
It’s “disable” without the “@“.

http://www.sublimelinter.com/en/stable/linter_settings.html

**Comment by jtleathers** [comment]
I knew it was something obvious. Thank you @braver !

**Comment by braver** [comment]
🎉 😄
