### ISSUE TITLE
Installation Instructions are incomplete

### ISSUE THREAD

**Issue by bramus** [SublimeLinter/SublimeLinter#1567]
Basically [it](https://sublimelinter.readthedocs.io/en/stable/installation.html) says that you need package manager, and that you might need to restart but it stops right there. What I'm missing is a mention of the name of the package that needs to be installed _(which is missing crucial information)_.

**Comment by kaste** [comment]
Yeah, agree, could be better. Can you make a PR?

**Comment by kaste** [comment]
I close this now, don't looks like you want to interact here.
