### ISSUE TITLE
Theme error after upgrading to Sublime 3.2

### ISSUE THREAD

**Issue by dcook-squiz** [SublimeLinter/SublimeLinter#1570]
I just updated Sublime to 3.2 and received an error popping up on every file saying `Packages/User/SublimeLinter/Tomorrow-Night (SL).tmTheme` could not be found.

So apparently SublimeLinter copies your theme? I checked and the file was still there, so I don't know what the issue is

**Comment by dcook-squiz** [comment]
I fixed by uninstalling SublimeLinter then reinstalling.

**Comment by kaste** [comment]
Maybe SublimeLinter did something like that in the past, 🤷‍♂️, but current versions don't do that.

**Comment by dcook-squiz** [comment]
🤷‍♂️ Good to know it won't affect other people!
