### ISSUE TITLE
Make `Linter.should_lint` a classmethod

### ISSUE THREAD

**Issue by kaste** [SublimeLinter/SublimeLinter#1580]
`should_lint` currently is a normal instance method but we cannot assure a safe call anymore (e.g. mutating `self` is forbidden!). We could make it a plain function, but I opt for the `@classmethod` bc experimental PR's need full control over the election process of linters. E.g. they might introduce new 'reasons' like 'attempt_fix' or so. 

This is a non-trivial multi-step refactoring. E.g. `sublime_linter.py::get_linters_for_view` cannot instantiate the linters anymore. Maybe ideally instantiating linters is one step in `backend.py::get_lint_tasks` or likewise `get_lint_regions`. Cloning linters in the backend should not be necessary after the refactoring.

Also: Inject the lint reason into the instance `__init__(self, view, settings, *, reason=None)` bc it is otherwise lost. 

Also: `get_linters_for_view` has these stupid side-effects so it cannot be reused elsewhere. Ideally we have more like a `applicable_linters_for_view(view,...)` as a pure getter.

**Comment by kaste** [comment]
@AndrewMast I thought this one might be interesting for you, but it's a bit technical, and def tricky

**Comment by AndrewMast** [comment]
I'll take a look :D

**Comment by AndrewMast** [comment]
I don't really have the time to dig very deep into SublimeLinter's code. Many of the functions do more than what the name implies, and I don't want to make too many changes to it as I do not understand it all.

I agree that `should_lint` should be a `@classmethod`, and it also could easily be added to `get_linters_for_view` next to `can_lint_view`.
