### ISSUE TITLE
In the panel show 'affected' files nearby active file

### ISSUE THREAD

**Issue by kaste** [SublimeLinter/SublimeLinter#1582]
Usual sort order for the files in the panel is `a, b, c, d` (surprise!). 

In #1556 we focus the active view, and for that, say `b` is active, we re-sort to `a, c, d, b`. 

Since we have now multi-file linters, we should group 'related/affected' files. This information is stored in `affected_filenames_per_bid`. Say linting b produced results for files `b, x, a`, we should re-sort to `c, d, b, a, x`. 

Rationale: Typical, traditional linters report only per-file, and with #1556 we get a pretty clean picture. Type-checkers (ususally) can show results from dependent files and a user will likely see these results nearby. I think this could be a good default, automatic behavior.

**Comment by kaste** [comment]
@AndrewMast Or this one. That's a graphical thing on top of #1556

**Comment by AndrewMast** [comment]
I'll take two looks then
