### ISSUE TITLE
NodeLinter: Fallback to global linter no longer working since #1579

### ISSUE THREAD

**Issue by silverwind** [SublimeLinter/SublimeLinter#1594]
Since https://github.com/SublimeLinter/SublimeLinter/pull/1579 SublimeLinter fails to lint for me with a warning message about having `eslint` not installed in the project:

````
SublimeLinter: WARNING: Skipping 'eslint' for now which is listed as a devDependency in <dir> but not installed.  Forgot to 'npm install'?
````

My project intentionally not have a `node_modules` because it is synced from a remote system and I like avoid synching thousands of files. Could SublimeLinter fallback to a global linter binary defined in `paths.<os>` in case a local one is absent, like it did before https://github.com/SublimeLinter/SublimeLinter/pull/1579?

Here's my config,  `/Users/silverwind/.npm-global/bin/eslint` is present.
````json
    "paths": {
        "osx": [
          "/Users/silverwind/.npm-global/bin",
        ],
    },
````

cc: @kaste

**Comment by silverwind** [comment]
#1579 says:

> checks if a project is not installed yet, and does not use the global linter if so.

So it seems the change was intended, but I can't agree with it. Maybe emit a warning if the global linter was used instead of just refusing to lint at all?

**Comment by kaste** [comment]
Hm, that's unfortunate. 😢 

If you don't have a `node_modules` that means you don't have any other dependencies your code requires? Technically, you wouldn't necessarily sync the `node_modules` folder, you could still do a `npm install` locally... we'll see if we get a lot of reports here.

The workaround is to setup a project file, and fill in the `executable` setting manually:

```
{
    ...
    "settings": {
       "SublimeLinter.linters.eslint.executable": "/Users/silverwind/.npm-global/bin/eslint"
    }
}
```

[Why the change at all?: 1. Often a global eslint doesn't run with local config bc the plugins, rules aren't installed etc., in that case the global eslint would 'crash'. 2. If you just checkout some code, start fresh, you maybe first look around, read the code, try to find the right spot for a fix, in that phase running eslint is not necessary.]

**Comment by silverwind** [comment]
Yes, I'm aware of the drawbacks of using global eslint and I do replicate the plugins to the global installation. It's not ideal, but works.

I have worked around by installing locally, but would rather not have to do it for every remote project (I have a lot of them), so I'd strongly prefer if linting the global linter would at least be attempted, with a warning logged that results may not match the local installation.

**Comment by braver** [comment]
@silverwind as @kaste describes you can override the executable. This really is an edge case, which is what the settings are for. If you have eslint defined as a dependency, you don’t want to fall back to something else. Not as an automatic thing anyway. So you edit a setting to tell SL it can find the executable elsewhere. Please let us know if this works for you.

**Comment by silverwind** [comment]
Setting a executable will not work unfortunately as I have both projects that use local and global eslint and I like it to use the local `eslint`, if it is present.

`eslint` itself also support a fallback to global mode with configuration specified in `~/.eslintrc`, I don't see why SL couldn't do the same fallback. Is it really better to refuse linting then at least trying?

**Comment by braver** [comment]
You can use Sublime Text projects to manage different settings for different situations.

When a configuration is present, it’s not a good idea to fallback to something else if the config doesn’t work. It may yield unexpected results in a way that may be hard to figure out. I still believe we have a suitable work around here.

**Comment by silverwind** [comment]
Yes, thats why you would log a warning, to make the user aware of possibly inconsistent results. A incorrect result is better than no result. 

Maybe you want to take a hint from [vscode-eslint](https://github.com/Microsoft/vscode-eslint) which does exactly what I need:

> The extension uses the ESLint library installed in the opened workspace folder. If the folder doesn't provide one the extension looks for a global install version

**Comment by moszeed** [comment]
simliar problem here, i dont do "npm install" on my dev machine, this happens in a vm/container.
and sublime now does not find the eslint executable ... 

why no switch? "global_eslint_fallback" ...

**Comment by braver** [comment]
@moszeed You can configure the eslint executable to work around that.

@silverwind I can see your point, but wouldn't setting up Sublime projects allow for a good work around already?

**Comment by silverwind** [comment]
Can't answer that one as I've never user Sublime's projects feature and I'm not too keen on adding another dotfile to my projects for something that should be default behaviour, imho.

**Comment by braver** [comment]
> something that should be default behaviour, imho

Sure, but that’s your “imho” 😉

We propose a solution, so don’t expect us to move forward without you even trying it. I don’t see evidence that the solution isn’t a good match for the problem, I just see one user refusing to accept it. 

Another approach to moving this forward is to create a PR.

**Comment by kaste** [comment]
The VM maybe docker stuff is relatively interesting but it's too early for any best practices here I think. We can implement this only if this usage/configuration is somehow observable by looking at the project/filesystem. 

Please look at this issue from this point of view: How can we *compute* the executable we can use? How can we avoid false reports? How can we limit confusion and generally noise esp. for new developers?

**Comment by silverwind** [comment]
It's kind of unfortunate that Sublime Text shows warnings/errors only in the console where new users will never discover them. If they were more prominently displayed (like a small toast), I guess there would be no risk of confusing new users.

**Comment by braver** [comment]
I thought the output panel opening with a message is kinda prominent, also because it does not go away until you close it yourself. But sure, ST doesn't have a lot in the way of visual feedback.

**Comment by kaste** [comment]
@silverwind Any updates on this one? We're not interested in reverting this, but improving and making the software better is always 👌

**Comment by cuki** [comment]
I (barely) noticed this issue also the other day when changing code, which runs in Docker.

Just happened to notice it as result of code review, where normally SublimeLinter would help me out with the coding style, but in reality it silently failed.

Meaning, in the SublimeLinter output it shows "No lint results.", when in reality in Console it (silently) spits out the following **warning**:
```
SublimeLinter: WARNING: Skipping 'eslint' for now which is listed as a devDependency in /Users/cuki/projects/docker25/package.json but not installed.  Forgot to 'npm install'?
```
An pop-up or different SublimeLinter output would be useful to see whether you forgot to configure the project settings (as *workaround*) for one of the many projects you might have.

Otherwise it's really annoying to have to create a new project file (just for this workaround) for every Docker project, when ideally you would just (globally) install ESLint and SublimeLinter picks up your available installation and (try to) execute linter, instead of not linting the code at all.

**Comment by kaste** [comment]
The docker thing sure is interesting but it is also edge, latest state-of-art and there are no common, good practices yet. But when you use docker to get or replicate a specific state/setup, just fall back to the global eslint linter is goofy. We should do better here at least in the long run. 

Isn't what we want here a silent install just like what `npx -p eslint@5.x.y eslint` would do? 

I think we could totally do better than a 'No lint results.'. Showing the latest errors/hint in that view would be nice, I think. Maybe not completely trivial, but def doable.

Also (maybe) a drop down like "Here are some executables we found/you used lately, pick one!"

**Comment by silverwind** [comment]
doing the equivalent of `npx eslint@$(jq -r .devDependencies.eslint package.json) file` would also elegantly solve my issue.

**Comment by kaste** [comment]
Unfortunately `npx` never evolved beyond the simple stuff, t.i. `npx eslint@5.x` would actually install on every invocation. Just `npx eslint` would probably work for your use-case bc it would iirc fallback to a global installed package. You can try to set `"executable": ["npx", "eslint"]` (But not reliable on Windows or monorepos.)  Generally, such a wrapper *could* be written in JS *or* as a plugin/feature within Sublime.  

[
E.g. within Sublime, we can listen for a view's 'on_activated_async(view)' event, then inspect its `view.file_name()`, maybe see if we find a docker file in the path upwards, and so on, and finally dynamically configure SublimeLinter. 
]

Closing again until this gets actionable.
