### ISSUE TITLE
 How to close the console?

### ISSUE THREAD

**Issue by moonlitnighta** [SublimeLinter/SublimeLinter#1596]
I am going crazy, every time I open a new file it will open the console, but I don't want to do this, "debug" setting "false" is completely invalid, can anyone tell me what to do?
![image](https://user-images.githubusercontent.com/22231630/56423603-71eb8400-62df-11e9-8d91-ec708a5ddd67.png)
![image](https://user-images.githubusercontent.com/22231630/56423608-7dd74600-62df-11e9-8cbc-ac63d326f23a.png)

**Comment by braver** [comment]
What you’re seeing is output from the linter telling you it failed to run. It should not do that more that once per “session”. You may also be able to resolve the issue somehow.

**Comment by moonlitnighta** [comment]
@braver Hello, is there any solution?

**Comment by braver** [comment]
You need to look up the warning in the tslint documentation to learn how to make it go away.

**Comment by moonlitnighta** [comment]
@braver I am confused about a rookie. I checked eslint but I didn't find any clues. I can't stand this jerk.

**Comment by moonlitnighta** [comment]
I always thought that the "debug" mode of "SublimeLinter" was invalid because it clearly stated that "debug:true" can output warning messages to the console.

**Comment by braver** [comment]
This isn’t a debug warning: tslint (not eslint) is outputting information you need to know about. What you’re seeing also isn’t the console, it’s an output panel specifically for the purpose of this message. You’re trying to use tslint in a way that doesn’t work and it is telling you so. I don’t know anything about JSX, so I can’t help you. You need to read the message and resolve the problem it is reporting.

**Comment by AndrewMast** [comment]
In my unknowledgeable opinion, I think the tslint configuration does not know what a ‘tsk’ file is. Either that or no rules are specified for that file type. Do you know where the configuration file is stored for tslint?

**Comment by kaste** [comment]
Do you actually have a config file generated for you? E.g. did you run `tslint --init` from the root of your project?

**Comment by moonlitnighta** [comment]
I am getting confused.
I executed "tslint -v" and found that it was installed on my computer, but my project used eslint, and created the .eslintrc.js file. I only installed eslint and sublimeLinter in my sublime plugin. So is this related to tslint?
![image](https://user-images.githubusercontent.com/22231630/56703562-0fa9dd80-673c-11e9-9648-931136b704a4.png)

**Comment by moonlitnighta** [comment]
@AndrewMast I don't have a "tsk" file in my project.😂

**Comment by moonlitnighta** [comment]
I uninstalled tslint and it seems normal.

**Comment by AndrewMast** [comment]
@moonlitnighta I said that because it looks like tslint was trying to lint a "tsk" file but didn't know what to do and throwing an error because of that. Maybe change the selector for tslint under SublimeLinter to exclude tsk files?

**Comment by AndrewMast** [comment]
The selector for eslint is including tsk files as shown in the following image. I don't know why you need that, but maybe try removing that?
![image](https://user-images.githubusercontent.com/13026511/56707552-f45cb500-66de-11e9-8f3e-e4d8a3d63e6d.png)

**Comment by kaste** [comment]
Closing bc it looks resolved.
