### ISSUE TITLE
Filenames with $ signs mangled when using ESLint

### ISSUE THREAD

**Issue by pkaminski** [SublimeLinter/SublimeLinter#1599]
Somewhat recently, SublimeLinter started failing in an interesting way when scanning my files with paths that contain `$` signs using ESLint (not sure if other linters are affected too).  For example, when scanning the file `C:\Code\workspace\reviewable\client\src\model\reviews\files\reviews.$reviewKey.files.$fileKey.js`, which has some lint errors, SublimeLinter fails with the following:

```
[{'errorCount': 4,
  'filePath': 'C:\\Code\\workspace\\reviewable\\client\\src\\model\\reviews\\files\\reviews..files..js',
  'fixableErrorCount': 1,
  'fixableWarningCount': 0,
...
SublimeLinter: #323 linter.py:1177    WARNING: eslint reported errors coming from 'C:\Code\workspace\reviewable\client\src\model\reviews\files\reviews..files..js'. However, reading that file raised:
  [Errno 2] No such file or directory: 'C:\\Code\\workspace\\reviewable\\client\\src\\model\\reviews\\files\\reviews..files..js'.
```

Running ESLint from the command line with `--format json` outputs the correct filename, so I'm guessing the problem is somewhere on SublimeLinter's side.  Looks like it's accidentally interpolating file paths and treating `$foo` as variable names.

Versions used:
SublimeLinter v4.11.1
SublimeLinter-eslint v4.1.6
Sublime Text v3.2.1
ESLint v5.16.0
Windows 10

**Comment by braver** [comment]
I'd kinda expect all linters to be affected, just that nobody ever runs into this problem. Just cause I'm curious, your actual files have a `$` in the path?

**Comment by pkaminski** [comment]
Yes, my files have `$` in the path -- and ironically, it does actually indicate a variable to be substituted, just not when linting.  It's a long story.  :)
