### ISSUE TITLE
No lint output or highlighting

### ISSUE THREAD

**Issue by HactarCE** [SublimeLinter/SublimeLinter#1605]
Nothing is highlighted and the "Show All Lint Errors" panel is just blank. The file is being linted, however, but only manually (despite `"lint_mode": "save"`):

```
SublimeLinter: sublime_linter.py:266  Delay linting 'commands.py' for 0.0s
SublimeLinter: linter.py:985          flake8: checking lint mode 'save' vs lint reason 'on_user_request'
SublimeLinter: linter.py:985          annotations: checking lint mode 'save' vs lint reason 'on_user_request'
SublimeLinter: #1 linter.py:1003      flake8: linting 'commands.py'
SublimeLinter: #2 linter.py:1003      annotations: linting 'commands.py'
SublimeLinter: #1 python_linter.py:47 flake8: wanted python is 'None'
SublimeLinter: #1 python_linter.py:98 flake8: trying to use globally installed flake8
SublimeLinter: #1 util.py:132         PATH:
    /usr/local/bin
    /usr/bin
    /bin
    /usr/local/sbin
    /opt/android-sdk/platform-tools
    /opt/android-sdk/tools
    /opt/android-sdk/tools/bin
    /usr/lib/jvm/default/bin
    /usr/bin/site_perl
    /usr/bin/vendor_perl
    /usr/bin/core_perl
    /home/andy/.local/bin
SublimeLinter: #2 linter.py:1082      annotations: output:
  60:6: warning (TODO): blah
SublimeLinter: #1 linter.py:1478      Running ...

  /home/andy/Dropbox/Games/Nomic/Quobot  (working dir)
  $ cat utils/commands.py | /usr/bin/flake8 --format default --ignore=E128,E221,E501,E741,W503,W504 -

SublimeLinter: #1 linter.py:1082      flake8: output:
  stdin:8:1: F821 undefined name 'undefined'
  stdin:10:1: E302 expected 2 blank lines, found 1
  stdin:23:1: E302 expected 2 blank lines, found 1
  stdin:62:16: F821 undefined name 'utils'
  stdin:72:15: F821 undefined name 'YES_NO_COLORS'
SublimeLinter: sublime_linter.py:529  Linting 'commands.py' took 0.34s
```

Here is my `SublimeLinter.sublime-settings` file:

```
// SublimeLinter Settings - User
{
    "debug": true,
    "lint_mode": "save",
    "linters": {
        "flake8": {
            "args": "--ignore=E128,E221,E501,E741,W503,W504"
        }
    }
}
```

Let me know if there's anything else I should provide.

**Comment by kaste** [comment]
Actually looks okay. Does the status bar indicate the linters and errors? Is this an issue with the lint mode, t.i. does it work if you don't set the mode to save? It could also be a scrolling issue with the panel, maybe it scrolled beyond the end of the actual output.

**Comment by HactarCE** [comment]
![The status bar says nothing related to linting.](https://user-images.githubusercontent.com/6060305/58374895-ff407a80-7f14-11e9-9fbe-bfecd960a0d8.png) After restarting ST3 the lint panel just shows "No lint results." despite the lint results in the console, so I don't think it's a scrolling issue. Maybe it's just not updating the window?

I tried setting `"lint_mode": "background"`, but the behavior is the same.

**Comment by kaste** [comment]
That's an interesting, novelty bug, maybe. 

Please make sure to leave debug mode and background mode on, then restart Sublime and look at or post the complete console output until the first linting stopped. Have you any SublimeLinter *addons* installed? Any tracebacks shown in the console? 

Now it shows 'No lint results.', and the status bar doesn't show anything at all, so this is at least a consistent (albeit wrong) view. So it looks like the linters are running, produce output, but the lint results are thrown away. Do you work with symlinked directories here? E.g. is '/home/andy/Dropbox/Games/Nomic/Quobot' the dir you have open, or is it the resolved so-called 'realpath'? 

Now maybe exercise the following: With the python view active, open the console. Type `view.file_name()`. Does `window.find_open_file(view.file_name()) == view` hold `True`?

**Comment by kaste** [comment]
One guess is that it all happens in this function

https://github.com/SublimeLinter/SublimeLinter/blob/master/sublime_linter.py#L331-L383

If possible, git clone SublimeLinter into Packages, and instrument the function with `print` calls. Does this function receive the errors from the output? Does it propagate the errors (E.g. https://github.com/SublimeLinter/SublimeLinter/blob/master/sublime_linter.py#L365 or https://github.com/SublimeLinter/SublimeLinter/blob/master/sublime_linter.py#L369 are early exit conditions)?

**Comment by HactarCE** [comment]
> Have you any SublimeLinter addons installed

I don't think so. I have SublimeLinter-annotations, SublimeLinter-flake8, and SublimeLinter-luacheck installed, but to my understanding those are linters, not addons.

> Do you work with symlinked directories here? E.g. is '/home/andy/Dropbox/Games/Nomic/Quobot' the dir you have open, or is it the resolved so-called 'realpath'?

Nope. These are pure and simple folders all the way down. `/home/andy/Dropbox/Games/Nomic/Quobot` is the root directory of my project, and I ran Sublime Text from the directory with `subl3 -n .`

> Now maybe exercise the following: With the python view active, open the console. Type view.file_name(). Does window.find_open_file(view.file_name()) == view hold True?

Yep!

```py
>>> view
<sublime.View object at 0x7f10c44ca550>
>>> view.file_name()
'/home/andy/Dropbox/Games/Nomic/Quobot/main.py'
>>> window.find_open_file(view.file_name())
<sublime.View object at 0x7f10c41d6510>
>>> window.find_open_file(view.file_name()) == view
True
```

> One guess is that it all happens in this function
>
> https://github.com/SublimeLinter/SublimeLinter/blob/master/sublime_linter.py#L331-L383

I added a `print` line to the beginning of `group_by_filename_and_update()`, and it looks like it's never actually being called. `lint()` is being called though, and the list of linters looks fine (`annotations` and `flake8`).

**Comment by kaste** [comment]
If we never reach `group_by_filename_and_update` then the process dies because of a (handled but obviously unlogged) exception. Okay, let's go back the stacktrace. If you're editing one of the files in a subfolder (e.g. `backend.py` below) ensure you either restart Sublime or run the command 'Reload SublimeLinter ...' from the command palette.

Before `group_by_filename_and_update` we're in https://github.com/SublimeLinter/SublimeLinter/blob/master/lint/backend.py#L58-L62 T.i. check that the actual lint task returns `None` instead of e.g. `[]` (indicating no lint errors). 

Before that, we're at https://github.com/SublimeLinter/SublimeLinter/blob/master/lint/backend.py#L287-L293 where we catch any `Exception` without logging. Check if we catch here and maybe log the error.

Before that, we're already at the meat https://github.com/SublimeLinter/SublimeLinter/blob/master/lint/backend.py#L154-L176
Check if we're reaching `execute_lint_task`, we have catch alls here but we should actually log them except for `TransientError`s.

🤞 Thanks for looking into this.

**Comment by HactarCE** [comment]
`results` and `errors` in `run_tasks()` both look healthy. No exception occurs in `run_concurrently()` (it does execute twice; once for each linter, I guess). `execute_lint_task()` reaches [line #159](https://github.com/SublimeLinter/SublimeLinter/blob/master/lint/backend.py#L159) without error. Based on what I've seen, everything in the backend looks fine ... and yet still there is no output in the **Show All Errors** view and the file is not being highlighted.

And thank you for the quick responses to try and get this resolved! I'm glad I can be of actual use in troubleshooting.

**Comment by kaste** [comment]
Okidoki, `run_tasks` https://github.com/SublimeLinter/SublimeLinter/blob/master/lint/backend.py#L58 is the function immediately before we propagate the errors. As you can see `next` is the sink and should be a partially applied (or bound) version of `group_by_filename_and_update`. You can check that via `print(next)`. It should print something like `functools.partial(functools.partial(<function group_by_filename_and_update at 0x000002257C3382F0>, ...`. Try calling that function directly 

```
# sublime.set_timeout_async(lambda: next(errors))
next(errors)
```

**Comment by HactarCE** [comment]
FYI, `next` is a Python built-in, so its use here confused me at first. `print(next)` gave `functools.partial(functools.partial(<function group_by_filename_and_update at 0x7ff192acbef0>, 71, <function make_view_has_changed_fn.<locals>.view_has_changed at 0x7ff19048e0e0>), <SublimeLinter-annotations.linter.Annotations object at 0x7ff191e25890>)`.

Changing `sublime.set_timeout_async(lambda: next(errors))` to just `next(errors)` did make progress! Now my errors are highlighted, but they still don't show in the **Show All Errors**, and it's still only linting manually (not in background or on save).

**Comment by kaste** [comment]
Well, now it seems that your Sublime installation is fundamentally broken. It's like its worker thread isn't running. `sublime.set_timeout_async` should of course just work as it is calling a core API. This also explains why the 'on_save' behavior is broken because all event listeners are scheduled to run on said worker thread.

**Comment by HactarCE** [comment]
Okay I don't know what was wrong, but I removed `~/.config/sublime-text-3` and then copied my configuration files back and it all works now. Thank you for the help, and sorry that there wasn't actually any issue with SublimeLinter!

**Comment by kaste** [comment]
😁
