### ISSUE TITLE
Do not use `realpath('.')` as the fallback working dir 

### ISSUE THREAD

**Issue by kaste** [SublimeLinter/SublimeLinter#1606]
We use the short, handy `realpath('.')` as a fallback working dir

https://github.com/SublimeLinter/SublimeLinter/blob/11607e156389601bb67de3d0a348623490bfac76/lint/linter.py#L1247

Why not just use `os.getcwd()`?

**Comment by braver** [comment]
Maybe getcwd wasn't available in python 2.7 or whatever version was in SublimeText 2? I don't know that it would return in all situations but it looks a lot better indeed. 🤷‍♂
