### ISSUE TITLE
Error on erlc (Erlang)

### ISSUE THREAD

**Issue by SebCav** [SublimeLinter/SublimeLinter#1608]
Hi,
I noticed an error in the console while using SublimeLinter with Erlang files:

SublimeLinter: #43 linter.py:1076     annotations: no output
SublimeLinter: #42 linter.py:1082     erlc: output:
  /home/seba/src/eidon/./tmpbfy41l.beam: Module name 'include_erl_call' does not match file name 'tmpbfy41l'
  /tmp/tmpbfy41l.erl:35: Warning: function format_error/1 is unused
SublimeLinter: #42 linter.py:1118     erlc: No match for line: '/home/seba/src/eidon/./tmpbfy41l.beam: Module name 'include_erl_call' does not match file name 'tmpbfy41l''
SublimeLinter: sublime_linter.py:529  Linting 'include_erl_call.erl' took 0.28s

It seems it's trying to copy a file in tmp with a different name and compile it with erlc, but Erlang modules cannot be renamed unless the module directive inside the erl file is changed accordingly.

**Comment by kaste** [comment]
Hi! Looks like the linter plugin is outdated and not maintained. There is a PR though https://github.com/teh-cmc/SublimeLinter-contrib-erlc/pull/6 you could try. 

@braver Can we 'pull' this plugin?

**Comment by SebCav** [comment]
Thank you, I installed SublimeLinter a while ago and I forgot there was a separate plugin. The PR works fine.
