### ISSUE TITLE
Latest SublimeLinter not working at all on Mac with eslint

### ISSUE THREAD

**Issue by rifeljm** [SublimeLinter/SublimeLinter#1611]
I did a fresh install - Sublime Text 3 and SublimeLinter.

I can run eslint in terminal (installed it either locally in node_modules or globally with npm -g)
I see all javascript errors and eslint doesn't give me any warnings.

Last couple of lines in console is showing:
SublimeLinter: log_handler.py:74      Logging installed; log level INFO
SublimeLinter: sublime_linter.py:62   debug mode: on
SublimeLinter: sublime_linter.py:63   version: 4.11.2
SublimeLinter: log_handler.py:74      Logging installed; log level INFO
SublimeLinter: sublime_linter.py:266  Delay linting 'Todo.js' for 0.0s

I don't see any lint errors in the Sublime Text's GUI.

Linting works perfectly with VSCode though (same project).

Also installed FixMacPath...
Did this too, which doesn't help:
// SublimeLinter Settings - User
{
    "debug": true,
  	"linters": {
        "eslint": {
            "disable": false,
            "args": [],
            "excludes": [],
            "env": {
              "PATH": "/Users/rifeljm/.nvm/versions/node/v12.4.0/bin"
            }
        }
    }
}

Any clue what to test?

**Comment by kaste** [comment]
Actually looks like the eslint plugin to SublimeLinter is not installed (or maybe disabled?).

**Comment by rifeljm** [comment]
Yep. SublimeLinter-eslint plugin was not installed. My bad :)

**Comment by kaste** [comment]
🙋
