### ISSUE TITLE
SublimeLinter not detecting all errors

### ISSUE THREAD

**Issue by itsmemanoj** [SublimeLinter/SublimeLinter#1612]
![error](https://user-images.githubusercontent.com/48552515/59563210-7b326c00-9056-11e9-84d6-f1171f57d761.png)

i have just installed
SublimeLinter
SublimeLinter-php
SublimeLinter-jshint
SublimeLinter-csslint

i was checking if linter working or not, and got this attached screenshot.
its not detecting unkown string its should show error there too, its undefined constast
I'm using PHP 7 xamp.. and i'm on Windows 7

**Comment by kaste** [comment]
Hi! I'm not sure what the used linters here actually produce. Better to enable debug mode in the settings, and look at or post the logs in the console (`View > Show console`).

**Comment by itsmemanoj** [comment]
![err](https://user-images.githubusercontent.com/48552515/59669120-5dd9db00-91d9-11e9-9ba3-f1ba2389b22a.png)

here are the logs.

**Comment by kaste** [comment]
Well, then that's probably how it is. As you can see the linter does not produce more output. (A lot of the linters abort on syntax errors actually.) But there a plenty of other php linters you could try.

**Comment by kaste** [comment]
Closing because it doesn't look like a bug. Feel free to comment.
