### ISSUE TITLE
Re-enable .sublimelinterrc support

### ISSUE THREAD

**Issue by dndrsn** [SublimeLinter/SublimeLinter#1614]
I can't say I know the reasoning for removing .sublimelinterrc file support in v4 so there may be a very good reason not to, but I would love to see it added back.  I don't use Sublime project files and they don't work for my specific workflow, so right now I have no easy way to switch between different linters that process the same types of files on a project-by-project basis.  Thanks.

**Comment by kaste** [comment]
How do you switch between or open your projects? What's your workflow?

**Comment by braver** [comment]
Also, what are the linters you use? Many nowadays support directory or project based configuration.

The reasons to drop support for a SublimeLinter config file include:

- it would require SublimeLinter to process settings in a ways that’s not natural for the ST eco system, and is non-trivial.
- the work flows it supported are 99% of the time already covered by linter-native settings and ST project settings.
- using the ST native settings system allows anyone to write a plugin to change the behavior. You could write something that sets the settings for each view the way you want.
- it discourages non-shareable config files polluting projects.

**Comment by dndrsn** [comment]
All of the above make sense and I agree with the config files polluting projects issue.  The two linters that give me an issue are stylelint and sass-lint.  Newer projects use stylelint older ones use sass-lint.  

Ideally it would be great to have a way for SublimeLinter to have a way to know which linter to use based on the existing project files.  I.e. some way to configure the linters such that they are enabled or disabled based on the presence or absence of specific files in the project root directory.  This would allow, for example, stylelint to be enabled by default unless a sass-lint config file is present in the project directory and sass-lint to be disabled by default unless a sass-lint config file is present in the project directory.  No idea if that makes sense or is even feasible.

**Comment by braver** [comment]
Oh, I can see how that would conflict. You could try to cover that by adding a stylelint config to the old projects (or globally even, assuming the new projects have a stylelint config in them) that disables all the rules there, but that’s perhaps a bit unwieldy. 

Depending on how you set up ST, it should also be pretty easy to set up a little plugin that checks for the existence of a config file in the root directory and then disables the linter you don’t need. I’m not sure how savvy you are with python and/or the ST api, but I could try to whip up something that could get you started?

**Comment by kaste** [comment]
If both linters are node based... We have a switch here to disable the linter if it is not in package.json. 

Generally enabling/disabling or using a local or global install based on facts already present by looking at the file/folder structure is in the scope of SublimeLinter.

**Comment by braver** [comment]
The disable_if_not_dependency setting would work here, but only if you use package.json’s.

**Comment by dndrsn** [comment]
Thanks.  All of this gives me something to work with.  For the time being I removed global installs for both.

**Comment by braver** [comment]
Ok, since this is not really actionable on our end, I'm closing the issue. If you need any help, let us know.
