### ISSUE TITLE
In ST4 test for dangles

### ISSUE THREAD

**Issue by kaste** [SublimeLinter/SublimeLinter#1617]
Pretty sure newer Sublime regresses here. Whenever we reload a view which has regions drawn they become dangles, and also the viewport scrolls to the top nowadays. Also swap line up and down doesn't move the region with the selection but kinda invalidates them by turning them to dangles. Pretty annoying. 

(Easily observable: if you have the panel open, all errors are moved to position 1:1.)

![u7Uj2XVA8x](https://user-images.githubusercontent.com/8558/59923024-9d4f3400-9432-11e9-8d85-1a6302d073f5.gif)

**Comment by kaste** [comment]
Upstream https://github.com/SublimeTextIssues/Core/issues/2877

**Comment by braver** [comment]
Yeah I noticed them too. Not so often, but definitely more dangles than before.

**Comment by braver** [comment]
These are not even labeled yet upstream, so no way of knowing the status. 

Unrelated, but I thought I'd give you a heads-up, if you're not on the Discord channel, that a v4 is coming for Sublime and it will ship Python 3.8. So it's kinda early and under the radar now, but that might offer some opportunities for improvement etc.

**Comment by kaste** [comment]
I think I have a standing record with upstream issues not getting a single comment.

TBH, Sublime may have >1000 "issues" but here in SL we maybe have seen ~3 or so. We just don't have layers of code just to fix "their" bugs.

**Comment by kaste** [comment]
But they sure need a DevRel. If the developers of GitSavvy, SL, or LSP have problems, they should get help.  And they should look at these repos esp. when v4 is probably a breaking change. (I sure don't want pressure v4 suddenly being there and fixing this code base asap.)

**Comment by braver** [comment]
Well, for v4 they are definitely looking at the major packages and it has fixes specifically to improve LSP. So, I'm reading that as good signs. There is a dev release if you want it, but it's kinda alpha and only disclosed via the discord channel, ie. to the hard core group. SL "just works" though, looks like we're all good here. If you want I can dig up the download link for you. It's not a big secret, they just don't want it featured on hackernews right now.

**Comment by braver** [comment]
I changed the title. I feel like we should just revisit this when v4 drops. There has been a lot of work in this area and maybe it got better, maybe it got worse. But it doesn't make sense to do anything right now in v3, or in an alpha release of v4 when it still might change. But it is historically a re-occuring thing so it makes sense to be vigilant.

![be-sober](https://user-images.githubusercontent.com/2543659/73688453-5dd90d80-46cc-11ea-97e7-e4002cf4aa1f.jpg)
