### ISSUE TITLE
SublimeLinter sometimes parses node's package.json file incorrectly

### ISSUE THREAD

**Issue by ArtskydJ** [SublimeLinter/SublimeLinter#1621]
If I use SublimeLinter with a node-based linter, and I have a package.json property named bin that is a string, then I receive a TypeError.

Replication steps and code: https://github.com/ArtskydJ/sublimelinter-eslist-bin-issue

### tldr

I get this error
```
...
File "C:\Users\Joseph\AppData\Roaming\Sublime Text 3\Installed Packages\SublimeLinter.sublime-package\lint/base_linter/node_linter.py", line 126, in find_local_executable
    script = os.path.normpath(os.path.join(path, manifest['bin'][npm_name]))
TypeError: string indices must be integers
```

if I have a package.json file like this

```json
{ "bin": "whatever.js" }
```

but this package.json file works just fine

```json
{ "bin": { "cli": "whatever.js" } }

**Comment by kaste** [comment]
Thanks for reporting, that's clearly a bug.

**Comment by braver** [comment]
4.11.3 is out now and should fix this
