### ISSUE TITLE
How does a plugin determine the language to be linted?

### ISSUE THREAD

**Issue by bfoz** [SublimeLinter/SublimeLinter#1628]
I’m writing a linter plugin that’s going to be an experiment in supporting multiple languages with a single plugin, and I ran into a little issue.

It appears that a plugin can specify multiple selectors, or even specify no selector, to be able to lint multiple, or all, types of files. However, how does any particular invocation of `run()` know which of the selectors that invocation is for?

For example, if my plugin looks like...

```python
class DonQuixote(Linter):
    cmd = None
    defaults = {'selector': 'source.python, source.ruby'}

    def run(self, cmd, code):
        # ...
```

How does `run()` know if the text passed in `code` is supposed to be treated as `source.python` or `source.ruby`? 

If I just missed it in the docs somewhere, please point me in the right direction and I'll see myself out.

**Comment by braver** [comment]
Well, I can’t look it up for you right now, but perhaps this can set you on the right path. A linter runs in the context of a view, so you should be able to get a reference to that view from somewhere. And then it’s just a question of view.get_scope_name or something like that via the Sublime Text API.

**Comment by FichteFoll** [comment]
You can use ctrl+alt+shift+p to reveal the scope at the current caret position in any view. Set the Syntax you want to lint and then use the first scope name, separated (stacked, rather) by spaces.
