### ISSUE TITLE
sass: Defining 'cls.syntax' has no effect anymore.

### ISSUE THREAD

**Issue by Robpayot** [SublimeLinter/SublimeLinter#1632]
When I started Sublime Text this morning, I had an automatic update for SublimeLinter and now the plugin SublimeLinter-contrib-sass-lint is not working anymore.
Everything was working perfectly before this update.
The debug mode is showing me these errors:
```
SublimeLinter: ERROR:
=====================

sass: Defining 'cls.syntax' has no effect anymore. Use http://www.sublimelinter.com/en/stable/linter_settings.html#selector instead.


SublimeLinter: ERROR:
=====================

sass: Defining 'cls.selectors' has no effect anymore. Use http://www.sublimelinter.com/en/stable/linter_settings.html#selector instead.


SublimeLinter: ERROR:
=====================

sass disabled. 'cls.defaults' is mandatory and MUST be a dict.
```
I tried to uninstall and reinstall the plugin but I'm still having the same issues.

Is there something else I need to update?

My SublimeLinter version is `v.4.12.0`
and my SublimeLinter-contrib-sass-lint version is `v1.2.1`

Thank you,

**Comment by kaste** [comment]
There is a PR https://github.com/skovhus/SublimeLinter-contrib-sass-lint/pull/32

**Comment by kaste** [comment]
The plugin has been updated. The rollout usually takes up to an hour. 🚀

**Comment by Robpayot** [comment]
@kaste Awesome, it's working with the new release. Thanks for fixing it so fast! 🙏

**Comment by kaste** [comment]
💐 go to @TomasBarry.
