### ISSUE TITLE
SublimeLinter always triggers "plugin_host has exited unexpecte."

### ISSUE THREAD

**Issue by Sir-kay** [SublimeLinter/SublimeLinter#1637]
SublimeLinter is a great plugin.
But when I use it, it always triggers "plugin_host has exited unexpecte." and I have to disable it.
![The issue](https://segmentfault.com/img/bVRFFp?w=473&h=178)
I hope the issue can be fixed soon.

**Comment by kaste** [comment]
We need the full info here. Os, versions. Please enable SublimeLinter's debug, then restart, and look at the complete output in `View > Show console`. It is actually very likely that another plugin causes this.
