### ISSUE TITLE
Flip `kill_old_processes` switch

### ISSUE THREAD

**Issue by kaste** [SublimeLinter/SublimeLinter#1639]
We actually wanted to flip the default here to `true`. (And if this works out okay maybe remove the setting.) 

(I have this set to true on my Windows, so it looks proper for that OS at least.)

**Comment by braver** [comment]
Want me to toggle the setting, run with it for a while to see if any issues crop up? We can also just push it and see if people report issues...

**Comment by kaste** [comment]
That would be cool, just flip it already.

**Comment by braver** [comment]
👍
