### ISSUE TITLE
Remove `Linter.tab_width` setting

### ISSUE THREAD

**Issue by kaste** [SublimeLinter/SublimeLinter#1641]
`tab_width` (the default is `1` which does nothing) is unused throughout all the registered linters so it can go away, probably without deprecation, just the warning that this thing doesn't do anything anymore.

🙌

**Comment by braver** [comment]
Is that a linter setting? That doesn't make any sense whatsoever.

**Comment by kaste** [comment]
Not a setting a user could edit, but something you can define on the class. 🤷‍♂

**Comment by braver** [comment]
Oh ok.. doesn't make any more or less sense that way but ok. Let's drop it 👍
