### ISSUE TITLE
Automatically lock old closed issues?

### ISSUE THREAD

**Issue by kaste** [SublimeLinter/SublimeLinter#1642]
We sometimes get comments on very old issues. Me too. etc. The information in the thread is usually *outdated*, and it is in general not a good starting point for a conversation. Usually I don't know what they actually referring to ... 

We could add e.g. https://github.com/apps/lock but please no message when locking. Just lock closed issues after 6 months. Only issues, for PR's it is still possible to find regressions etc.

**Comment by braver** [comment]
Good idea. Especially in all the plugin repos the content in issues is usually really useless. Personally I just unsubscribe if I get too much noise from a repo though.

**Comment by cyrus303** [comment]
can i contribute to this, could you guide me through this?

**Comment by kaste** [comment]
I cannot guide you here, it's basically asking for a bot running as GitHub action. Probably there is already open source software doing this completely or almost.

**Comment by braver** [comment]
For me personally hitting unsubscribe on an issue that is resurrected is sufficient and easier than trying to figure out how to get a bot to do something. I.e. I’m not going to pursue this.
