### ISSUE TITLE
Linters stop working after 4.12.0 upgrade?

### ISSUE THREAD

**Issue by distortedsignal** [SublimeLinter/SublimeLinter#1643]
Hey all,

I recently realized that SublimeLinter stopped working for the Erlang linter that I use. I tried to follow the debugging steps (`debug=true`, print logs, etc) and I found that three of the linters that I'm currently using are throwing errors. Log follows, with added newlines:

```
SublimeLinter: sublime_linter.py:248  Delay linting 'Preferences.sublime-settings' for 0.0s


reloading settings Packages/User/Preferences.sublime-settings
ignored packages updated to: ["SublimeLinter-contrib-erlc2", "Erlyman"]


reloading plugin SublimeLinter.lint
reloading plugin SublimeLinter.__init__
reloading plugin SublimeLinter.active_linters_view
reloading plugin SublimeLinter.busy_indicator_view
reloading plugin SublimeLinter.goto_commands
reloading plugin SublimeLinter.highlight_view
reloading plugin SublimeLinter.lint
reloading plugin SublimeLinter.log_handler
reloading plugin SublimeLinter.message_view
reloading plugin SublimeLinter.panel_view
reloading plugin SublimeLinter.status_bar_view
reloading plugin SublimeLinter.sublime_linter

SublimeLinter: log_handler.py:74      Logging installed; log level INFO
SublimeLinter: sublime_linter.py:66   debug mode: on
SublimeLinter: sublime_linter.py:67   version: 4.12.0

SublimeLinter: sublime_linter.py:248  Delay linting 'bd_kube_authn_proxy.erl' for 0.0s
reloading plugin SublimeLinter-contrib-erlc.linter

SublimeLinter: linter.py:423          ERROR: erlc: Defining 'cls.syntax' has no effect anymore. Use http://www.sublimelinter.com/en/stable/linter_settings.html#selector instead.
SublimeLinter: linter.py:437          WARNING: erlc: Defining 'cls.executable' has no effect. Please cleanup and remove these settings.
SublimeLinter: linter.py:547          ERROR: erlc disabled. 'selector' is mandatory in 'cls.defaults'.
 See http://www.sublimelinter.com/en/stable/linter_settings.html#selector

reloading plugin SublimeLinter-contrib-julialintserver.linter
SublimeLinter: linter.py:423          ERROR: julialintserver: Defining 'cls.syntax' has no effect anymore. Use http://www.sublimelinter.com/en/stable/linter_settings.html#selector instead.
SublimeLinter: linter.py:423          ERROR: julialintserver: Defining 'cls.selectors' has no effect anymore. Use http://www.sublimelinter.com/en/stable/linter_settings.html#selector instead.
SublimeLinter: linter.py:437          WARNING: julialintserver: Defining 'cls.version_args' has no effect. Please cleanup and remove these settings.
SublimeLinter: linter.py:437          WARNING: julialintserver: Defining 'cls.version_re' has no effect. Please cleanup and remove these settings.
SublimeLinter: linter.py:437          WARNING: julialintserver: Defining 'cls.version_requirement' has no effect. Please cleanup and remove these settings.
SublimeLinter: linter.py:437          WARNING: julialintserver: Defining 'cls.inline_settings' has no effect. Please cleanup and remove these settings.
SublimeLinter: linter.py:437          WARNING: julialintserver: Defining 'cls.inline_overrides' has no effect. Please cleanup and remove these settings.
SublimeLinter: linter.py:437          WARNING: julialintserver: Defining 'cls.comment_re' has no effect. Please cleanup and remove these settings.
SublimeLinter: linter.py:437          WARNING: julialintserver: Defining 'cls.executable' has no effect. Please cleanup and remove these settings.
SublimeLinter: linter.py:547          ERROR: julialintserver disabled. 'selector' is mandatory in 'cls.defaults'.
 See http://www.sublimelinter.com/en/stable/linter_settings.html#selector

reloading plugin SublimeLinter-contrib-raml-cop.linter
SublimeLinter: linter.py:423          ERROR: ramlcop: Defining 'cls.syntax' has no effect anymore. Use http://www.sublimelinter.com/en/stable/linter_settings.html#selector instead.
SublimeLinter: linter.py:437          WARNING: ramlcop: Defining 'cls.version_requirement' has no effect. Please cleanup and remove these settings.
SublimeLinter: linter.py:541          ERROR: ramlcop disabled. 'cls.defaults' is mandatory and MUST be a dict.
```

I have no experience troubleshooting issues like this, but I tried my hand at this, and I feel like it's somehow related to the [4.12.0 change of setting `cls.disabled` to True on L425 of lint/linter.py](https://github.com/SublimeLinter/SublimeLinter/blob/fde3f094d1fb6efceb8fdb07b86f5ab8d92d08e0/lint/linter.py#L416-L427). Compare to [lines 400 - 402 in 4.11.3](https://github.com/SublimeLinter/SublimeLinter/blob/4.11.3/lint/linter.py#L393-L402).

I'm a little confused as to why 4.12.0 was chosen to make this change and drop support for older (and less compliant) linters, and why I can't find any release notes that specify that this change would happen. Where should I be looking for release notes? How can I make sure that my linters continue to work across releases in the future?

**Comment by kaste** [comment]
That's unfortunate, in the end it's a community thing. We actually shipped the release notes https://github.com/SublimeLinter/SublimeLinter/blob/master/messages/4.12.0.txt They should show up on upgrade automatically. At the same time an error panel should pop up showing mostly what you've found using `debug=True`. (The wording could be better, it is probably too technical.)

The deprecation period was > 1 year, the whole period we printed deprecation warnings to the console (with `debug=False`). The last couple of months we had a pinned, sticky issue in this repository. 

So, we're actually in control, `4.12` was a big release and we had no regressions so far, and this change was totally planned. The community can feedback, decide and work on how these warnings should be written to be actionable and helpful, how they should be presented. It's 2019, we can write bots to open github issues automatically, we can write code transformers to update plugins automatically. We can maybe do monorepos. But we cannot do it alone, all three failing linters are third party contrib plugins. 

(As this comes often: Package Control is not a classical package manager, all packages are on the most recent version all the time, it is also not semversioned, so `4.x` is the version of an app not a library.)

**Comment by distortedsignal** [comment]
Huh, well that kinda sucks, but I guess that means that I have two new hobby projects.

**Comment by braver** [comment]
The info in the console should be enough for the original authors to update the plugins. Or to create a PR. Usually it’s pretty trivial, but it does require some knowledge. If the authors are MIA and you’re unable to a new version published, let us know, there are things we can do.

**Comment by distortedsignal** [comment]
[The Erlang linter hasn't been updated in three years](https://packagecontrol.io/packages/SublimeLinter-contrib-erlc)
[The Julia linter hasn't been updated in three years](https://packagecontrol.io/packages/SublimeLinter-contrib-julialintserver)
[The RAML Linter hasn't been updated in two years](https://packagecontrol.io/packages/SublimeLinter-contrib-raml-cop)

Contributing to my doubt that these linters are actively maintained is the fact that [I've had a PR open against the Julia Linter for about two years](https://github.com/tomaskrehlik/SublimeLinter-contrib-julialint/pull/5)

**Comment by kaste** [comment]
Should we take them into the org, @braver?

**Comment by braver** [comment]
Well...

- https://github.com/thebinarypenguin/SublimeLinter-contrib-raml-cop doesn't have any activity, but there are no reported issues or pr's, so that isn't weird. The owner is active on GitHub. First try opening a PR there, the plugin is pretty trivial.
- https://github.com/teh-cmc/SublimeLinter-contrib-erlc seems to be abandoned. I've left a note in the ignored PR, let's give it a few days.
- https://github.com/invenia/SublimeLinter-contrib-julialintserver runs a daemon, and actually seems to ship a binary for that. It's not a trivial wrapper around a command line utility like most plugins. I don't feel comfortable about pulling it into the org. The other two we can just modify by reading and adjusting the code, you don't even need to know anything about the tool and you basically don't even have to test. If someone else (@distortedsignal ?) wants to fork it, we can point package control to that fork instead.
