### ISSUE TITLE
Support Yarn Plug'n'Play

### ISSUE THREAD

**Issue by HusamIbrahim** [SublimeLinter/SublimeLinter#1644]
This is more of a feature request. When working on a project that uses Yarn's [Plug'n'Play (PnP)](https://yarnpkg.com/lang/en/docs/pnp/) feature to manage dependency resolution SublimeLinter complains that it cannot find eslint ..

> SublimeLinter: WARNING: Skipping 'eslint' for now which is listed as a devDependency in C:\Path\To\package.json but not installed.  Forgot to 'npm install'? 

I suppose the current implementation [depends on the presence of a local `node_modules` folder](https://github.com/SublimeLinter/SublimeLinter/blob/9ed6b21468e9b5f4d0b03f52dedf78258e553a7e/lint/base_linter/node_linter.py#L68-L70)?

**Comment by braver** [comment]
> I suppose the current implementation depends on the presence of a local node_modules folder?

Yes, it mimics what Node does in that sense. Yarn PnP sounds pretty smart perhaps we should try to see if that’s available and then try that first.

**Comment by kaste** [comment]
How do you tell if a project uses pnp? And how do you actually run eslint on the command line?

**Comment by HusamIbrahim** [comment]
> How do you tell if a project uses pnp? And how do you actually run eslint on the command line?

A project that uses pnp will have the following setting in `package.json` ..

```
{
  "installConfig": {
    "pnp": true
  }
}
```

To run eslint I have the following script in my `package.json` ..

```
"scripts": {
    "lint": "eslint --ext .js src test",
    "lint:autofix": "yarn lint --fix"
},
```

So to run the script I just run `yarn lint`.

**Comment by HusamIbrahim** [comment]
@kaste Yarn keeps track of the dependencies in a `.pnp.js` file. I'm not sure if it is possible to load that file and do a RegEx search for the location of the eslint binary?

**Comment by kaste** [comment]
Looking at the docs it looks like you can just use `yarn run eslint .` to run arbitrary scripts/commands installed or reachable. (This would conflict of course if the user defined a script in package.json with that exact name.) Can you confirm?

**Comment by HusamIbrahim** [comment]
@kaste Yes I can confirm that. But that's also the case if a project doesn't use PnP.

**Comment by kaste** [comment]
Okay, then that's also the workaround for now. You can set 'executable' to `['yarn', 'run', 'eslint']` in the project settings to make it work at least. This is also what we would do automatically in the future so would be nice if you can confirm that this approach works in SublimeLinter.

**Comment by HusamIbrahim** [comment]
@kaste I'm afraid that didn't work. I get the following error message ..

> SublimeLinter: #20 eslint index.js ERROR:
> \=========================================
> 
>   Execution failed
> 
>   [WinError 2] The system cannot find the file specified
> 
>   C:\Users\Husam\Code\vue-ish  (working dir)
>   \> type src\index.js | yarn run eslint --format json --stdin --stdin-filename C:\Users\Husam\Code\vue-ish\src\index.js
>

**Comment by kaste** [comment]
Ok, on Windows, can you try `where yarn` on the command line and use that instead of the simple `yarn`. (yarn is probably a '.cmd', not an '.exe', anyway the complete absolute path just to make sure we have some path resolution error here.)

**Comment by HusamIbrahim** [comment]
@kaste Now I'm getting the following error message ..

> SublimeLinter: #&#x2060;21 eslint index.js ERROR:
> \=========================================
> 
> JSON Decode error: We expected JSON from 'eslint', but instead got this:
> yarn run v1.17.3
> $ C:\Users\Husam\AppData\Local\Yarn\Cache\v4\npm-eslint-6.1.0-06438a4a278b1d84fb107d24eaaa35471986e646\node_modules\eslint\.bin\eslint --format json --stdin --stdin-filename C:\Users\Husam\Code\vue-ish\src\index.js
> [{"filePath":"C:\\Users\\Husam\\Code\\vue-ish\\src\\index.js","messages":[],"errorCount":0,"warningCount":0,"fixableErrorCount":0,"fixableWarningCount":0}]
> Done in 0.83s.
> 
> Be aware that we only parse the last line of above output.

**Comment by kaste** [comment]
Okay, well they put noise on it. Maybe there is a no verbose option? Otherwise we can't use that, we would then need an equivalent of `yarn which eslint`.

**Comment by HusamIbrahim** [comment]
@kaste I'm not sure what exactly it's complaining about. Says JSON Decode error, but it seems to me that this is valid JSON, amirite?

**Comment by HusamIbrahim** [comment]
@kaste This is what I get if I run it with a `--silent` flag ..

> SublimeLinter: #&#x2060;22 eslint index.js ERROR:
> \=========================================
> 
> JSON Decode error: We expected JSON from 'eslint', but instead got this:
> yarn run v1.17.3
> $ C:\Users\Husam\AppData\Local\Yarn\Cache\v4\npm-eslint-6.1.0-06438a4a278b1d84fb107d24eaaa35471986e646\node_modules\eslint\.bin\eslint --silent --format json --stdin --stdin-filename C:\Users\Husam\Code\vue-ish\src\index.js
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
> 
> 
> Be aware that we only parse the last line of above output.

**Comment by HusamIbrahim** [comment]
Silly me. I got the command backwards 😳

I can confirm that it does indeed work with a `--silent` flag.  So the workaround for now is to use this in the project settings ..

```
"settings": {
    "SublimeLinter.linters.eslint.executable": ["C:\\Path\\To\\yarn.cmd", "run", "--silent", "eslint"]
}
```
Only thing is that it still squawks `error Command failed with exit code 1.` on linting errors. But hey I can't complain 😏

**Comment by kaste** [comment]
Upstream bug is https://github.com/yarnpkg/yarn/issues/5359

**Comment by HusamIbrahim** [comment]
> Upstream bug is [yarnpkg/yarn#5359](https://github.com/yarnpkg/yarn/issues/5359)

I see. I take it then the upstream bug has to be fixed before we see native PnP support in SublimeLinter?

**Comment by kaste** [comment]
Well, the upstream patch is way simpler than to adapt the code here.

**Comment by kaste** [comment]
I'm not a yarn user but I think you can run `yarn bin eslint` to get the actual script and just use that as `executable`. Then maybe you need to patch the execution environment as well like `"env": "NODE_OPTIONS=\"--require /path/to/.pnp.js\""` https://yarnpkg.com/en/docs/pnp/troubleshooting

`env` is like `executable` just another setting. You have to dig into that hole.

**Comment by HusamIbrahim** [comment]
@kaste I was just exploring `yarn bin eslint` yesterday but it doesn't seem to work. Even after setting `"env"` as you kindly suggested. I kinda got my hopes up that it might make native PnP support in SublimeLinter easier. Bummer 😞

**Comment by HusamIbrahim** [comment]
Pinging @arcanis because the workaround mentioned above which works fine with Yarn 1 doesn't seem to work with Yarn 2.

w/ `--slient` flag ..

> SublimeLinter: #&#x2060;911 eslint index.js ERROR:
> \==========================================
> 
> JSON Decode error: We expected JSON from 'eslint', but instead got this:
> Unknown Syntax Error: Command not found; did you mean one of:
> 
>   0. yarn run
>   1. yarn run [-T,--top-level] <arg> ...
> 
> 
> Be aware that we only parse the last line of above output.

w/o `--silent` flag ..

**Comment by arcanis** [comment]
The `--silent` flag isn't needed at the moment on the v2 (it doesn't print the header / footer), although I may add it if only for compatibility.

The second issue is interesting - can you add a `console.log` at the line referenced by the stacktrace to figure out what `p` contains that would explain why it's not a string (I suspect an `URL` but I want to be sure)?

**Comment by HusamIbrahim** [comment]
> can you add a `console.log` at the line referenced by the stacktrace to figure out what `p` contains that would explain why it's not a string (I suspect an `URL` but I want to be sure)?

This is what I get when I `console.log(p)` ..

`../../AppData/Local/Yarn/Berry/cache/eslint-npm-6.1.0-42fb0bc0c9.zip/node_modules/eslint/bin/eslint.js`

**Comment by arcanis** [comment]
The problem (which is on Yarn) comes from here:

https://github.com/eslint/eslint/blob/master/bin/eslint.js#L69

The `STDIN_FILE_DESCRIPTOR` variable is a file descriptor, but our FS layer doesn't support file descriptors at the moment. I've opened https://github.com/yarnpkg/berry/issues/359 to track it.

**Comment by kaste** [comment]
This is basically actionable since the PR is in their master and pending a release. Must be solved together with #1626. Strategy is easy: while looking for a `package.json` watch out for 

```
"installConfig": {
  "pnp": true
}
```

fragment. If present take that dir as the `project_dir`/`working_dir`, resolve `which yarn` and set executable to `[yarn_path, 'run', '--silent', cmd_name]`.

**Comment by arcanis** [comment]
Yep, I fixed it on master.

Note that the `"pnp": true` flag isn't needed anymore starting from the v2, because Yarn uses PnP by default. We strongly advise to call ESLint via `yarn run`, as that's guaranteed to work regardless of the user's environment.

**Comment by kaste** [comment]
Oh, which is the correct marker to look for then. We want to do this automatically, so we need a marker on the filesystem which tells us that we can use 'yarn run'.

**Comment by arcanis** [comment]
Imo the best marker would be to use `yarn run` when you detect a `yarn.lock` file.

A more conservative option is to check whether a `.pnp.js` file exists adjacent to the `package.json`, although it's semantically incorrect should another package manager implement PnP later on (pnpm considers it).

**Comment by HusamIbrahim** [comment]
> If present take that dir as the project_dir/working_dir, resolve which yarn and set executable to [yarn_path, 'run', '--silent', cmd_name].

This won't solve the issue with yarn v2 though as there's no `--silent` flag there.

**Comment by arcanis** [comment]
That can be fixed 🙂

**Comment by HusamIbrahim** [comment]
> That can be fixed 🙂

arcanis to the rescue!

**Comment by HusamIbrahim** [comment]
@kaste This just in! `--silent` flag support in yarn v2 thanks to **arcanis**  [yarnpkg/berry#400](yarnpkg/yarn#5359)

Seems to me the way is clear now to address this issue in SublimeLinter. I hope someone has picked this up already by now? If not I could give it a try.

**Comment by kaste** [comment]
Someone would be usually me, and I haven't started this one yet. Note that a PR will solve the eslint issue linked above and this one bc they basically touch the same code path. Implementation should be easy, testing usually hairy bc of all the mocking something like this requires.

**Comment by HusamIbrahim** [comment]
> Someone would be usually me, and I haven't started this one yet. Note that a PR will solve the eslint issue linked above and this one bc they basically touch the same code path. Implementation should be easy, testing usually hairy bc of all the mocking something like this requires.

I see. I'll have a go at a PR then but I might need some pointers along the way as I'm not a python guy, especially re: testing.

**Comment by kaste** [comment]
@arcanis We still have some problems here. 

Generally `yarn.lock` is not a good marker. A lot of projects ship such a file although end-users can just `npm install` such a project and hack on it. It is also not sufficient for the current community because you can use old-school `yarn` which everyone does atm and then you still have to `yarn install` prior to a `yarn run` (which will right now just create a `node_modules` dir like `npm`).

I've seen that 'berry' checks in a `.yarn/cache`. Is that a happy path `which yarn` and `exists .yarn/cache`? Because that's plug'n'play, you just checkout and run.

Technically, the `.pnp.js` marker is also not safe. I assume that file is also to be committed. But just seeing it does not mean the cache is hot and thus yarn is maybe not ready to run. 

(We basically use `node_modules/bin` somewhere, traversing up from the project dir as a marker right now which is of course safe because when you find a binary you can of course just use it. This is only important for automatic discovery; a user can manually configure to use `npx` or `yarn run` or whatever, but then said user is also prepared for some error messages and how to read and fix them.)

Ideally we want to be fast and efficient in the implementation bc we're in an editor not on a CI. And we want to be in charge: e.g. if we find a 'package.json' declaring `eslint` but no `node_modules/bin/eslint` we like to tell the user 'maybe you forgot to install this project' etc.

So, as I see it, if we see a 'package.json' declaring `eslint` and no `node_modules/bin` but a '.pnp.js', we could either try to be 'optimistic' and just run yarn. Or we ask `yarn bin` which is by definition not a cachable query. 

@HusamIbrahim If we go the 'optimistic' way, we *maybe* need to catch 

```
error Command "eslint" not found.
```

on stderr and transform it to an acceptable, actionable outcome.

**Comment by arcanis** [comment]
> Generally yarn.lock is not a good marker. A lot of projects ship such a file although end-users can just npm install such a project and hack on it.

Fwiw this is strongly discouraged as installing a project using a different one will lead to different installations and unexpected changes of behaviour (for example doing this on a project using workspaces will probably make things very wrong).

> It is also not sufficient for the current community because you can use old-school `yarn` which everyone does atm and then you still have to `yarn install` prior to a `yarn run` (which will right now just create a `node_modules` dir like `npm`).

Isn't it already the case with SublimeLinter at the moment? I'm not familiar with the codebase, but I guess you call ESLint using `node_modules/.bin/eslint`? If so, the project has to be installed before you're able to do this 🤔

> if we find a 'package.json' declaring `eslint` but no `node_modules/bin/eslint` we like to tell the user 'maybe you forgot to install this project' etc.

Totally agree! We could actually do this on Yarn's side (for the v2, at least; not sure we can do this on the v1). It's easy for us to figure out whether the cache archive targeted by a `run` call exists or not, and if it doesn't we can offer to run `yarn install`.

**Comment by adrian-gierakowski** [comment]
has anyone figured out how to make things like `LSP -> Goto Definition...` open file from a zip archive? Thanks!

**Comment by kaste** [comment]
@adrian-gierakowski wrong repo, wrong issue

**Comment by adrian-gierakowski** [comment]
@kaste wrong attitude 😉
