### ISSUE TITLE
Deprecate '*' usage in `cmd`

### ISSUE THREAD

**Issue by kaste** [SublimeLinter/SublimeLinter#1646]
We forgot this one 🤷‍♀. Instead of '*' we use the explicit '$args' these days, we forgot to print a warning here.

**Comment by braver** [comment]
👍🏻

**Comment by Patil2099** [comment]
@kaste do I have to replace "*" with "$args" ?If yes Can I work on it?

**Comment by kaste** [comment]
Hi! We have a compatibility layer in the method insert_args but we forgot to issue a deprecation_warning when we hit that code path. Ideally you write a test for it too.
