### ISSUE TITLE
Unhandled exception (eslint + typescript)

### ISSUE THREAD

**Issue by kbjr** [SublimeLinter/SublimeLinter#1650]
Getting an unhandled exception when trying to use SublimeLinter-eslint for typescript files.

```
Traceback (most recent call last):
  File "C:\Users\jbrumo\AppData\Roaming\Sublime Text 3\Installed Packages\SublimeLinter.sublime-package\lint/backend.py", line 155, in execute_lint_task
    errors = linter.lint(code, view_has_changed)
  File "C:\Users\jbrumo\AppData\Roaming\Sublime Text 3\Installed Packages\SublimeLinter.sublime-package\lint/linter.py", line 1091, in lint
    return self.filter_errors(self.parse_output(output, virtual_view))
  File "C:\Users\jbrumo\AppData\Roaming\Sublime Text 3\Installed Packages\SublimeLinter.sublime-package\lint/linter.py", line 1117, in filter_errors
    for error in errors
  File "C:\Users\jbrumo\AppData\Roaming\Sublime Text 3\Installed Packages\SublimeLinter.sublime-package\lint/linter.py", line 1116, in <listcomp>
    error
  File "C:\Users\jbrumo\AppData\Roaming\Sublime Text 3\Installed Packages\SublimeLinter.sublime-package\lint/linter.py", line 1157, in parse_output_via_regex
    for m in self.find_errors(output):
  File "C:\Users\jbrumo\AppData\Roaming\Sublime Text 3\Installed Packages\SublimeLinter-eslint.sublime-package\linter.py", line 92, in find_errors
    line=match['line'] - 1,  # apply line_col_base manually
KeyError: 'line'
```

Installed the following dependencies:

- @typescript-eslint/eslint-plugin@2.0.0
- @typescript-eslint/parser@2.0.0
- eslint@6.3.0
- typescript@3.6.2

**Comment by kaste** [comment]
Hey cool, thanks for reporting. Basically this means eslint reports an error without telling on which line it occurred.

I thought line is mandatory. Can you pinpoint either on the command line or by turning debug mode on here for SublimeLinter and looking at the output in the console which errors come without a line. Should we just throw these errors away, or fake it to line 1?

**Comment by kbjr** [comment]
Ah, debug mode revealed the issue. I changed the working_dir path, and that path doesn't have a tsconfig file, which returns different kind of error.

```
[{'errorCount': 1,
  'filePath': 'C:\\NikeDev\\node-utils\\redis\\src\\index.ts',
  'fixableErrorCount': 0,
  'fixableWarningCount': 0,
  'messages': [{'fatal': True,
                'message': "Parsing error: File 'C:\\NikeDev\\tsconfig.json' not found.",
                'ruleId': None,
                'severity': 2}],
  'source': ' ',
  'warningCount': 0}]
```

**Comment by kaste** [comment]
So we fake a line '1' here? Probably better than throwing away such an error.

**Comment by kbjr** [comment]
I would think so, it would be a useful thing to actually be told so it can be fixed

**Comment by kaste** [comment]
So you mean we show the error panel if no line and fatal is True with the error message. That would be probably even better. 🤔

**Comment by braver** [comment]
Yes that would be the idea. But I’d like confirmation on the idea that it’s a config error that the user should fix, i.e. that in this case it would run correctly with the default or no config.

**Comment by MicroDroid** [comment]
I just opened this PR that fixes this https://github.com/SublimeLinter/SublimeLinter-eslint/pull/283

**Comment by kaste** [comment]
Thanks for the PR! Do you have the same underlying cause as the OP?

We thought that for config errors like that it would be better to not fake a line but mark the linter run as erred and show the message directly to the end user. Wdyt?

**Comment by MicroDroid** [comment]
@kaste Yes, I do have the same issue the OP had, as I had set an invalid `ecmaVersion`.

Anyways, I could alter the behavior to show console with error or something, but *personally* I don't think it's a bad idea to fake first line.

Up to you.

**Comment by kaste** [comment]
SublimeLinter v3 did that, but we want to move to clear error messages for v4. If we fake the error line we basically tell the user the file has one problem but apparently for config errors the linter could not run at all. So if we know that for sure, we should report it as such. 

@braver wdyt?

**Comment by braver** [comment]
If it’s a config error the user made and has to correct, we should show the output panel. This way we don’t fake anything and the user doesn’t have to hunt down the error.

**Comment by MicroDroid** [comment]
Alright, I'll update the PR asap to reflect that!
