### ISSUE TITLE
Multi-file Linting Doesn't Display Errors In Related Files

### ISSUE THREAD

**Issue by rgant** [SublimeLinter/SublimeLinter#1665]
Really appreciate the work to support multi-file linting. It works really well so long as there is at least one match in the main file, but it doesn't display any results if the matches are only in the related files.

For example, if I introduce an error into the list.component.ts file, I will see the missing trackBy errors in the list.component.html file:
```
Users/rgant/Programming/LearnLux/learnlux-app/src/app/budget/list/list.component.ts:
  29:13  error  tslint:prefer-readonly                 Private member variable 'budgetService' is never reassigned; mark it as 'readonly'.

users/rgant/programming/learnlux/learnlux-app/src/app/budget/list/list.component.html:
   9:25  error  tslint:template-use-track-by-function  Missing trackBy function in ngFor directive
 113:22  error  tslint:template-use-track-by-function  Missing trackBy function in ngFor directive
 135:22  error  tslint:template-use-track-by-function  Missing trackBy function in ngFor directive
```

But if I remove that error from list.component.ts then the panel doesn't even open and I see no errors for the html file.

This is the result from the debug mode console:
```
reloading settings Packages/User/SublimeLinter.sublime-settings
SublimeLinter: log_handler.py:74      Logging installed; log level INFO
SublimeLinter: sublime_linter.py:291  Delay linting 'list.component.ts' for 1.7s
SublimeLinter: sublime_linter.py:291  Delay linting 'list.component.ts' for 1.7s
SublimeLinter: linter.py:1077         tslint: Checking lint mode 'save' vs lint reason 'on_modified'.  Skip.
SublimeLinter: sublime_linter.py:291  Delay linting 'list.component.ts' for 0.0s
SublimeLinter: linter.py:1077         tslint: Checking lint mode 'save' vs lint reason 'on_save'.  Ok.
SublimeLinter: #18 linter.py:1094     tslint: linting 'list.component.ts'
SublimeLinter: #18 linter.py:864      tslint: wanted executable is '/Users/rgant/Programming/LearnLux/learnlux-app/node_modules/.bin/tslint'
SublimeLinter: #18 linter.py:1607     Running ...

  /Users/rgant/Programming/LearnLux/learnlux-app  (working dir)
  $ /Users/rgant/Programming/LearnLux/learnlux-app/node_modules/.bin/tslint --format verbose /Users/rgant/Programming/LearnLux/learnlux-app/src/app/budget/list/list.component.ts --project /Users/rgant/Programming/LearnLux/learnlux-app

SublimeLinter: #18 linter.py:1176     tslint: output:
  ERROR: (template-use-track-by-function) /users/rgant/programming/learnlux/learnlux-app/src/app/budget/list/list.component.html[9, 25]: Missing trackBy function in ngFor directive
  ERROR: (template-use-track-by-function) /users/rgant/programming/learnlux/learnlux-app/src/app/budget/list/list.component.html[113, 22]: Missing trackBy function in ngFor directive
  ERROR: (template-use-track-by-function) /users/rgant/programming/learnlux/learnlux-app/src/app/budget/list/list.component.html[135, 22]: Missing trackBy function in ngFor directive
SublimeLinter: #18 linter.py:1228     tslint: No match for line: ''
SublimeLinter: sublime_linter.py:539  Linting 'list.component.ts' took 3.33s
```

**Comment by rgant** [comment]
Also, a bit concerned that all the file paths are lower cased. Sure on MacOS the filesystem is probably going to be case insensitive 😞, but in many other filesystems paths are sensitive.

**Comment by kaste** [comment]
Hm. Okay, the filename being lower cased is an issue with the tslint plugin, isn't it? Can you check in the Terminal?) We (currently) just take what we get. The error from the '.ts' file comes with proper case, and the rule 'template-use-track-by-function' comes with lower cased names.  Should we overrule the actual linter here. 🤔 

What does it mean the panel (`ctrl+k+a`, right?) doesn't even open? It should always open, it might be empty. If it doesn't open, does it crash? T.i. can you open the console and look if you see an exception traceback. 

The filename is the crucial part here bc we can't properly relate the view with its errors which leads to subtle bugs. But still as long as the 'ts' file is open, we should find the other errors and show them in the panel. (Is the 'html' file actually open, is it dirty/unsaved?)

**Comment by rgant** [comment]
Ahh, you are correct, tslint does lower case the paths:

```
Euphorbus:~/Programming/LearnLux/learnlux-app (feature/budget-line-items *$)$ tslint --project ./ --format verbose src/app/budget/list/list.component.ts
ERROR: (template-use-track-by-function) /users/rgant/programming/learnlux/learnlux-app/src/app/budget/list/list.component.html[9, 25]: Missing trackBy function in ngFor directive
ERROR: (template-use-track-by-function) /users/rgant/programming/learnlux/learnlux-app/src/app/budget/list/list.component.html[113, 22]: Missing trackBy function in ngFor directive
ERROR: (template-use-track-by-function) /users/rgant/programming/learnlux/learnlux-app/src/app/budget/list/list.component.html[135, 22]: Missing trackBy function in ngFor directive
```

In my experience the panel with the lint errors doesn't open when the file contains no lint errors. Exceptions appear in the console, which is different from where the SublimeLinter messages appear (which I referred to as "the panel").

That said, I restarted Sublime and now it does seem to be loading lint errors for the related files without an error in the main file. Perhaps Sublime was just upset at all of my reloading plugins trying to add multi-file support. So since that seems to be working I will close out this ticket.

**Comment by kaste** [comment]
Does the casing apply to all tslint rules or only to files when tslint follows an import to a HTML file.

**Comment by rgant** [comment]
Strange. I guess the "lower case the whole file path" thing is a codelyzer thing.

```
tslint --project ./ --format verbose src/app/budget/list/list.component.ts
ERROR: (prefer-readonly) /Users/rgant/Programming/LearnLux/learnlux-app/src/app/budget/list/list.component.ts[29, 13]: Private member variable 'budgetService' is never reassigned; mark it as 'readonly'.
ERROR: (template-use-track-by-function) /users/rgant/programming/learnlux/learnlux-app/src/app/budget/list/list.component.html[9, 25]: Missing trackBy function in ngFor directive
ERROR: (template-use-track-by-function) /users/rgant/programming/learnlux/learnlux-app/src/app/budget/list/list.component.html[113, 22]: Missing trackBy function in ngFor directive
ERROR: (template-use-track-by-function) /users/rgant/programming/learnlux/learnlux-app/src/app/budget/list/list.component.html[135, 22]: Missing trackBy function in ngFor directive
```

**Comment by kaste** [comment]
Then it's definitely worth when you open an issue with backlink to here at their repo.
