### ISSUE TITLE
Log if there are no linters installed, or none can be selected for the given view

### ISSUE THREAD

**Issue by kaste** [SublimeLinter/SublimeLinter#1668]
As long as there are no linters at all, we could emit a `warning`. If none match the views syntax, we should still log an `info`. 

Otherwise users see as last debug message e.g. `"Delay linting 'eslint' for 0.3s"` and then silence which is not very helpful.

**Comment by braver** [comment]
In debug mode you mean? Sure, that would be more helpful. Especially the case with no linters installed.
