### ISSUE TITLE
"No match for line" error using tslint

### ISSUE THREAD

**Issue by guiann** [SublimeLinter/SublimeLinter#1678]
hello everyone,

I cannot get sublimeLinter to display gutter marks properly using typescript linter.

I've got this error in console:

> SublimeLinter: #51 **linter**.py:1230     tslint: No match for line: '(no-trailing-whitespace) /home/username/Workspace/Project/ts/sourcefile.ts[122, 33]: trailing whitespace'

The linter errors shows up in console also whan run as command line but are not highlited on the proper line in source file.
the Path given for the source file is good.

The highlight works fine when using eslint for javascript files. 
In the console I can see the python file use is not the same, I cannot tell if that matters or not :

> SublimeLinter: **sublime_linter**.py:578  Linting 'mySrcFile.js' took 0.71s

here is my sublimeLinter settings file:

```
{
  "debug": true,
  "gutter_theme": "Packages/SublimeLinter/gutter-themes/Circle/Circle.gutter-theme",
  "linters": {
    "tslint" : {
      "disable": false,
       "args": ["--config", "${folder}/tslint.json"],
      "config_filename": "tslint.json",
      "lint_mode": "save",
      "include": [
        "*.tsx",
        "*.ts"
      ]
    }
  }
}
```

Thank you for your advice.

**Comment by kaste** [comment]
Hi 👋!

The output of tslint is not exactly what we expect. Do you set an output format in your config file. Don't know if that's even possible to be honest.

**Comment by guiann** [comment]
Thank you for your answer,  I don't set any output format. 

This is the full output for a file with lint errors:
Hope that can help,  can you please describe what is expected instead ?

`SublimeLinter: #114 linter.py:1178    tslint: output:
  (no-trailing-whitespace) /home/username/Workspace/Project/ts/component/srcFile.ts[137, 10]: trailing whitespace
  (no-trailing-whitespace) /home/username/Workspace/Project/ts/component/srcFile.ts[138, 8]: trailing whitespace
  (switch-default) /home/username/Workspace/Project/ts/component/srcFile.ts[158, 11]: Switch statement should include a 'default' case
SublimeLinter: #114 linter.py:1230    tslint: No match for line: '(no-trailing-whitespace) /home/username/Workspace/Project/ts/component/srcFile.ts[137, 10]: trailing whitespace'
SublimeLinter: #114 linter.py:1230    tslint: No match for line: '(no-trailing-whitespace) /home/username/Workspace/Project/ts/component/srcFile.ts[138, 8]: trailing whitespace'
SublimeLinter: #114 linter.py:1230    tslint: No match for line: '(switch-default) /home/username/Workspace/Project/ts/component/srcFile.ts[158, 11]: Switch statement should include a 'default' case'
SublimeLinter: sublime_linter.py:578  Linting 'replay.ts' took 0.45s`

**Comment by kaste** [comment]
We use the verbose formatter  https://palantir.github.io/tslint/formatters/verbose/

The regex can bound here: https://github.com/SublimeLinter/SublimeLinter-tslint/blob/43f6771008da67a9487d467ac5b4f9306c247fac/linter.py#L10-L18 

Basically it should output e.g. 

```
ERROR: (semicolon) myFile.ts[1, 14]: Missing semicolon
```

The literal `ERROR: ` or `WARNING: ` is missing.

**Comment by guiann** [comment]
Thank you.
I know what happened:  Sublime text was running a locally installed version of tslint, stucked at 3.X.
Removing the local tslint version from my package.json to force installation of  tslint 5.20.0 fixed it.

I'm closing this issue and again thank you for your answers.

**Comment by kaste** [comment]
🎉
