### ISSUE TITLE
Make `eslint` detect installed plugins and their potential selectors

### ISSUE THREAD

**Issue by kaste** [SublimeLinter/SublimeLinter#1689]
eslint can basically lint a lot of different file types with the various plugins. Generally, eslint is one of the most used and best linters around. Afaik TypeScript switches to eslint which would be nice to support 'automatically' bc it will get widespread, other than that there is 'vue' and 'svelte', and probably some 'jsx' stuff which I'm not used too at all.  And the list goes on with 'html' and 'json'. 

So there is a lot of interesting stuff in there. 

I can think of a simple implementation *iff* we somehow can get a map from 'plugin-name' to 'selector' to start with. 

However, the implementation would break **the current default** of linting parts of html files as 'js'.  So, I need some feedback here.  I personally don't think that linting the js parts within html is super useful (e.g. globals are not shared between scripts.), it is also not very performant because we start an eslint process per script tag. But it is the default.  The implementation idea I have would make it necessary to flip the default, t.i. users had to opt in by providing a custom selector to restore the current behavior. 

WDYT?

**Comment by braver** [comment]
In my experience linting JS embedded in HTML hardly ever works well enough to be useful. There are always so many false positives (indentation, missing variables, etc) it’s too hard to find anything useful. So I don’t think it’s actually a good default: the JS in the HTML cannot be assumed to hold against the same standards as the rest of your project.

I don’t have that much experience with the plugins for eslint, but I would put supporting them at a much higher priority. Mapping selectors against the plugins sounds pretty trivial. The domain is small enough that it should be doable with some elbow grease. And the eslint-using community is large enough that maintaining it shouldn’t be a problem.

**Comment by kaste** [comment]
Implementation idea is at https://github.com/SublimeLinter/SublimeLinter-eslint/pull/287 🤞
