### ISSUE TITLE
SublimeLinter-golangcilint not found

### ISSUE THREAD

**Issue by guoyucheng** [SublimeLinter/SublimeLinter#1699]
SublimeLinter-golangcilint not found

**Comment by guoyucheng** [comment]
Package Control: Install Package   not found SublimeLinter-golangcilint

**Comment by kaste** [comment]
Please make sure you don't have it already. 

![image](https://user-images.githubusercontent.com/8558/69617998-72988580-1039-11ea-9864-3305792fe01a.png)

Also check `Package Control: Enable Package`.  If you're behind a wall, try installing manually, e.g. `git clone https://github.com/SublimeLinter/SublimeLinter-golangcilint.git` into your `Packages` folder.

**Comment by guoyucheng** [comment]
> Please make sure you don't have it already.
> 
> ![image](https://user-images.githubusercontent.com/8558/69617998-72988580-1039-11ea-9864-3305792fe01a.png)
> 
> Also check `Package Control: Enable Package`. If you're behind a wall, try installing manually, e.g. `git clone https://github.com/SublimeLinter/SublimeLinter-golangcilint.git` into your `Packages` folder.

ths
