### ISSUE TITLE
Trying to write a linter for less - can't figure out working directories using tmp

### ISSUE THREAD

**Issue by dflock** [SublimeLinter/SublimeLinter#17]
I'm trying to implement a linter for [LESS](http://lesscss.org/), using [Recess](https://github.com/twitter/recess).

Everything seems to work okay, expect for this one thing:

Afaik, recess doesn't accept input on stdin, so I'm using `tmpfile_suffix = 'less'` - which means that the file that I'm linting will reside in /tmp (or somewhere similar) at lint time - correct?

LESS supports an `@import` statement that can use relative paths to import other files. This doesn't seem to be working, because the linted file isn't where it's expected to be - it's in `/tmp`, I think?

Recess supports an `--includePath` parameter to fix this, but I can't figure out how to get hold of the original path to the file currently being linted from inside my linter.py file.

How can I fix this?

Current version of this linter plugin is [here](https://github.com/dflock/SublimeLinter-recess), btw.

**Comment by pbojinov** [comment]
@aparajita did you end up releasing your Less linter plugin?

**Comment by skj3gg** [comment]
I don't believe @aparajita was working on a less plugin... @dflock was though. It remains unfinished but from the looks of it you are not alone in your interest.

**Comment by pbojinov** [comment]
@skj3gg you're right, duh! I was looking at the wrong comment when I posted that. Have you came across any ST3 less linters for SL3?

**Comment by skj3gg** [comment]
Not that I know, or can [find](https://github.com/search?utf8=%E2%9C%93&q=sublimelinter+less)

**Comment by dflock** [comment]
The problem isn't the lack of a SublimeLinter plugin for linting LESS - it's the lack of an *actual* linter for the LESS language itself. See here for discussion on this: https://github.com/dflock/SublimeLinter-recess/issues/1

**Comment by pbojinov** [comment]
@dflock That's the sad truth, the lack of linters. Hadn't realized that it was limited to `lessc --lint`. 

Having a basic SublimeLinter plugin to do what you mentioned wouldn't be a bad idea to quickly catch syntax errors.
