### ISSUE TITLE
SublimeLinter: WARNING: golangcilint cannot locate 'golangci-lint'

### ISSUE THREAD

**Issue by matianhe** [SublimeLinter/SublimeLinter#1702]
I already added the path.

"linters": {
      "eslint": {
          "env": {"PATH":"/Users/matianhe/go/bin/"}
      }
    }

**Comment by kaste** [comment]
Erm, you set that for the `eslint` linter 😬 

I would either set the `executable` for this particular linter, or add the path to `paths`. If you want to patch the `env`, you probably want to **prepend** something which looks more like this `"PATH": "/Users/matianhe/go/bin/:$PATH"`
