### ISSUE TITLE
KeyError on disabled linter

### ISSUE THREAD

**Issue by braver** [SublimeLinter/SublimeLinter#1703]
I just got this in the console:
```py
Traceback (most recent call last):
  File "/Users/koenlageveen/Library/Application Support/Sublime Text/Packages/SublimeLinter/panel_view.py", line 119, in <lambda>
    sublime.set_timeout_async(lambda: maybe_run(proposition, action))
  File "/Users/koenlageveen/Library/Application Support/Sublime Text/Packages/SublimeLinter/panel_view.py", line 125, in maybe_run
    action()
  File "/Users/koenlageveen/Library/Application Support/Sublime Text/Packages/SublimeLinter/panel_view.py", line 97, in <lambda>
    lambda: execute_on_lint_result_request(linter_name)
  File "/Users/koenlageveen/Library/Application Support/Sublime Text/Packages/SublimeLinter/panel_view.py", line 130, in execute_on_lint_result_request
    calls = LINT_RESULT_CACHE.pop(linter_name)
KeyError: 'phpcs'
```

It looks like it breaks here, the other linters I'm using will not run anymore.

I have set phpcs to disabled, enabling it seems to resolve the issue. The error seems to have been triggered by opening the panel? Maybe I'll be able to recreate the situation, but at least I've recorded it here.

**Comment by kaste** [comment]
1. It did not heal itself by e.g. just writing along and thereby triggering other lint processes?

2. How do you disable/enable here, using PackageControl or our settings (global or project)?

**Comment by braver** [comment]
1. nope, it stayed dead until I re-enabled the linter
2. which I did by going into our settings and setting `"disable": false` globally for phpcs

**Comment by kaste** [comment]
> dead

T.i. also no more tracebacks, just silence.

**Comment by braver** [comment]
Exactly. Without having debug on, nothing new in the console.

**Comment by kaste** [comment]
To see how often this happens you could patch

```diff
diff --git a/panel_view.py b/panel_view.py
index f1be766..9eeb134 100644
--- a/panel_view.py
+++ b/panel_view.py
@@ -127,7 +127,12 @@ def maybe_run(prop, action):
 
 def execute_on_lint_result_request(linter_name):
     # type: (LinterName) -> None
-    calls = LINT_RESULT_CACHE.pop(linter_name)
+    try:
+        calls = LINT_RESULT_CACHE.pop(linter_name)
+    except Exception as e:
+        import sublime
+        sublime.active_window().run_command('show_panel', {'panel': 'console'})
+        raise e from None
     filenames, reasons = unzip(calls)
     _on_lint_result(
         set(filenames),
```

Honestly, I can think of how and when this particular line throws. (Basically disable a linter, and *quickly* switch to different views for which we had results from that linter. I'm either not quick enough, or my computer is too fast, so I cannot actually reproduce. Probably also easier to hit when you have lots of views/windows open you actually used that linter on.)

I wouldn't know how this could be catastrophic though. Nothing can be catastrophic in SublimeLinter except Zombies and Dangles.

**Comment by braver** [comment]
Ah, but my setup here is actually really slow, so that might be something. I'll try with that patch, see if anything turns up.

**Comment by braver** [comment]
I haven’t seen anything similar for a while. I’ll blame it on the insane network lag and leave it at that.
