### ISSUE TITLE
Can't use eslint_d

### ISSUE THREAD

**Issue by brendonco** [SublimeLinter/SublimeLinter#1707]
Hi,

Cant use eslint_d.  Always execute using eslint.

```
// SublimeLinter Settings - User
{
    "debug": true,
    "styles": [
        {
            "mark_style": "outline",
            "priority": 1,
            "icon": "dot",
            "scope": "region.yellowish markup.changed.sublime_linter markup.warning.sublime_linter",
            "types": ["warning"]
        },
        {
            "mark_style": "outline",
            "priority": 1,
            "icon": "dot",
            "scope": "region.redish markup.deleted.sublime_linter markup.error.sublime_linter",
            "types": ["error"]
        },
        {
            "priority": 1,
            "icon": "dot",
            "mark_style": "outline"
        }
    ],
    "linters": {
        "eslint": {
          "disabled": true,
          "args": [],
          "excludes": []
        },
        "eslint_d": {
            "disabled": false,
            "args": [],
            "excludes": []
        }
    },
    // Provide extra paths to be searched when locating system executables.
    "paths": {
        "windows": ["%APPDATA%/npm/eslint_d"]
    },
}
```

console errors:

```
reloading plugin SublimeLinter-contrib-eslint_d.linter
eslint_d: Defining 'cls.syntax' has no effect anymore. Use http://www.sublimelinter.com/en/stable/linter_settings.html#selector instead.
eslint_d: Defining 'cls.selectors' has no effect anymore. Use http://www.sublimelinter.com/en/stable/linter_settings.html#selector instead.
eslint_d: Defining 'cls.version_args' has no effect. Please cleanup and remove this setting.
eslint_d: Defining 'cls.version_re' has no effect. Please cleanup and remove this setting.
eslint_d: Defining 'cls.version_requirement' has no effect. Please cleanup and remove this setting.
eslint_d: Defining 'cls.npm_name' has no effect. Please cleanup and remove this setting.
eslint_d: Defining 'cls.executable' has no effect. Please cleanup and remove this setting.
eslint_d: Defining 'cls.config_file' has no effect. Please cleanup and remove this setting.
eslint_d disabled. 'cls.defaults' is mandatory and MUST be a dict.
```

**Comment by kaste** [comment]
Hi! These errors basically mean that the eslint_d plugin is outdated and doesn't work with the newer SublimeLinter version anymore.  You could try a PR at their repo to fix that. 

Since afaik the command line API is the same as for eslint, it could be possible to just use the eslint plugin for that.  The eslint plugin can't find your eslint_d of course (because the binary has a different name) so you could try setting *executable* manually and cross your finger. (http://www.sublimelinter.com/en/stable/linter_settings.html#executable)

**Comment by brendonco** [comment]
> Hi! These errors basically mean that the eslint_d plugin is outdated and doesn't work with the newer SublimeLinter version anymore. You could try a PR at their repo to fix that.
> 
> Since afaik the command line API is the same as for eslint, it could be possible to just use the eslint plugin for that. The eslint plugin can't find your eslint_d of course (because the binary has a different name) so you could try setting _executable_ manually and cross your finger. (http://www.sublimelinter.com/en/stable/linter_settings.html#executable)

Disable eslint doesnt seem to work.

```
"linters": {
        "eslint": {
          **"disabled": true,**
          "args": [],
          "excludes": []
        },
        "eslint_d": {
            "disabled": false,
            "args": [],
            "excludes": []
        }
    },
```

**Comment by kaste** [comment]
> Disable eslint doesnt seem to work

That's because the setting is named "disable" but you set "disabled".

**Comment by brendonco** [comment]
yes, previous version was disabled.  I treid to used disable, stop/start eslint_d, doesnt seem to work. still pointing to eslint.

**Comment by kaste** [comment]
The "eslint_d" plugin doesn't work if you don't patch it! Either you uninstall it, or you fix it. 

As I said in my first comment, *maybe* the standard "eslint" plugin supports *eslint_d* as well iff you set "executable" manually.  

> at sublime logs, I can see Using eslint path on 'windows': %APPDATA%/npm/node_modules/eslint/bin/eslint

Never seen that we log something like that BTW. To get verbose logs from SublimeLinter you need to turn "debug" on in the settings.

**Comment by brendonco** [comment]
Got it, tried executable in eslint plugin.

```
eslint: wanted executable is %APPDATA%\npm\eslint_d
[WinError 193] %1 is not a valid Win32 application
```

**Comment by kaste** [comment]
Which is correct.  executables on Windows are by default *.exe*, *.bat*, or *.cmd* files.  (Honestly, why do you get down that configuration hell route here? What's the benefit? Isn't that too much hassle for what **you** can actually do?)

Ok, have you tried just setting "eslint_d" as executable? Otherwise you need to find the *real* binary. Maybe using `where eslint_d` on the command line.

**Comment by braver** [comment]
This is just a trouble shooting/ support issue right now. If there is a problem with eslint_d, please report it in that repo. It is not part of the org and we cannot support it.
https://github.com/roadhump/SublimeLinter-contrib-eslint_d
