### ISSUE TITLE
consider maxerr in jshint

### ISSUE THREAD

**Issue by paponius** [SublimeLinter/SublimeLinter#1708]
jshint does count warnings and errors with one counter. After 50 Warnings, it will show an Error.

e.g.

```
var obj = {};
obj['idx'] = 'huhu';
... (50x)
obj['idx'] = 'huhu';
obj['idx'] = 'huhu';
```

will produce a lint error: 'too many errors',
because on each line there is a warning: "is better written in dot notation."

When a warning is hidden using SublimeLinter option filter_errors,
all that can be seen is one non-descriptive lint error.

If instead of filter_errors a jshint option is used to hide such warning:

```
// jshint -W069
var obj = {};
obj['idx'] = 'huhu';
... (50x)
obj['idx'] = 'huhu';
obj['idx'] = 'huhu';
```

the error is not there.
jshint is obviously not counting hidden warnings.

SublimeLinter can't do nothing about the logic of one counter, but maybe it can somehow rise the limit: jshint's `maxerr` option for each hidden warning.
It must consider a user can set maxerr in option himself and possibly also in-line

**Comment by kaste** [comment]
Hi! AFAIK maxerr can only be set in a config file (t.i. not on the command line). Config files are in user land, we can't and probably shouldn't patch them because that would be confusing and probably error prone. Do you have a specific solution in mind?

**Comment by braver** [comment]
Unless there is a command line flag that we can set to ignore maxerr (there doesn't seem to be), there is nothing we can do.

**Comment by paponius** [comment]
I see one not too good way.

API has `JSHINT( source, options, predef )`
But it probably also disables options from files like .jshintrc,
disallows CLI options like --exclude, in case you use those.
Plus it means a need of node.js


Then there is "extends".
But there is no --config-extends CLI flag

Must call: jshint --config ./Options.json

where Options.json:
{
  "extends": "../.jshintrc",
  "maxerr": 9999
}

User config must be found beforehand.
To not confuse users, using the same mechanism jshint does that:
1. N/A
2. file package.json in current or any parent path
3. file .jshintrc in current or any parent path
4. file .jshintrc in user home path
https://jshint.com/docs/cli/#specifying-linting-options

Plus to further complicate it, if package.json is found, it must be parsed,
and config extracted from jshintConfig property of the obtained Object.


maxerr can be 1000 as discussed in jshint issue https://github.com/jshint/jshint/issues/180
this would kind of disable the feature, except if user allows it again, if possible, using in-line option.

Or SublimeLinter can count warnings, which were hidden by itself, then if it encounters error: too many errors,
it wound set the maxerr limit to that number of hidden warnings plus 50 (which is the default) and run lint again.

If error 'too many errors' persist in second run, than it's upon user to fix the code or rise the maxerr limit.
That way the functionality of maxerr somewhat remains.

There would be a weird case:
- If user has 60 warnings and sets maxerr to 61, then if there are 20 hidden warnings and SublimeLinter overrides the maxerr to 70, user will still see the error 'too many' because 60 shown and 20 hidden warnings. The confusion would be that user would only see 60 warnings and would see maxerr set to 61. But an error message could be changed to say: 'too many errors and warnings, 60 visible plus 20 hidden'
- If user has set maxerr limit below 50. No idea.

**Comment by kaste** [comment]
We don't have nodejs here, and I hate looking up config files 😏.

But from a different perspective, I rather could agree with just telling in the error panel something like "Some results hidden via filter_errors." or of course "42 messages hidden via filter_errors" and "No lint results but 21 hidden.".  (Likewise, a hint "No lint results (yet, the linter is still running)") 

This is also some effort to implement but all users would benefit. Maybe.

**Comment by paponius** [comment]
I know, but you asked.

As you proposed, the problem is the confusion about "too many errors" when A) it's warnings, not errors B) can't see them
So if there is a status bar message instead saying "too many errors and warnings, 42 warnings hidden by filter_errors"
And on hint (message or what you call it) to that error a small instruction, "jshint counts warnings as errors, use maxerr to increase the limit".
That will resolve the confusion and the issue.
Anything more wouldn't be a fix but a feature, solving a problem caused mostly by jshint's joining of error/warning counter, stopping error checking on to many warnings, and a confusing error message.

**Comment by kaste** [comment]
The jshint specific parts can be resolved by a PR against the jshint plugin t.i. not here in core. I would go cheap here and not count the filtered errors. 

T.i. when jshint emits "too many errors", check if filter_errors is set and just change the message.  I.e. into "too many errors (some may be hidden by filter_errors). Try increasing maxerr in your config file."

The more general message in the error panel e.g. "21 problems hidden by filter_errors" is a patch against core (here).  This would be also straight forward and relatively easy to implement. (It wouldn't make anything more complex so it seems acceptable we just had to discuss the exact wording.)

**Comment by paponius** [comment]
Anything that would stop user from wondering what's going on and wasting time figuring it out.
For the wording, me no English, but I would include keywords so users can google: maxerr and filter_errors and possibly also the original "too many errors" so they can complain about the nonsense.
It's too much for status bar, but maybe in a message or in config file as a comment next to filter_errors

Seeing an Error (red dot) and status text: "21 problems hidden by filter_errors"
for the first time would maybe make me go blame filter_errors that it somehow can't hide too many errors, then thinking about what errors? I don's see no errors.

"errmax limit reached, 21 problems hidden by filter_errors" (or "some")

t.i. [Treasure Island?](https://www.abbreviations.com/Ti)

**Comment by kaste** [comment]
Are you ready to make a PR here? Since we're actually talking two PR's, the one against jshint is absolutely doable.

**Comment by braver** [comment]
I think the way to go here is in the jshint plugin to output a warning "too many errors" at line 0. 

Since there is only one case, I don't feel like adding something to core for this. What doesn't help my motivation here is that I feel that a maximum amount of errors is a design error in jshint 😉. But really, first we should prove that nothing reasonable can be done in the plugin, that motivated users of the plugin have tried and failed. Then we can consider adding something in core.
