### ISSUE TITLE
SublineLinter SublimeLinter: WARNING

### ISSUE THREAD

**Issue by hirschferkel** [SublimeLinter/SublimeLinter#1709]
`SublimeLinter: WARNING: csslint: Implicit appending a filename to `cmd` has been deprecated, add '${temp_file}' explicitly.
`

**Comment by kaste** [comment]
Thanks for reporting, do you want to try a PR?

**Comment by hirschferkel** [comment]
Kind of Beta? I could...

**Comment by kaste** [comment]
Go for it!

**Comment by hirschferkel** [comment]
... How would I install it? I work with Package control, don't know how to proceed now...

**Comment by kaste** [comment]
Okay. The PR has to be made against the plugin/addon https://github.com/SublimeLinter/SublimeLinter-csslint actually.

- From the menu `Preferences > Browse Packages`.

- In that folder, clone `git clone https://github.com/SublimeLinter/SublimeLinter-csslint`.

- Then open in Sublime, `subl SublimeLinter-csslint`.

- The code is in `linter.py`. Every time you change and save that file, we will ho-reload it, so hacking around is after that install stuff relatively painless.

You can just delete the clone, and everything will be as before. (Just restart Sublime.) There is no risk.

**Comment by hirschferkel** [comment]
Ah you think I should code a personal release, right? Sorry I cannot. That's not my construction site ;D I could test a PR but not build one.

**Comment by kaste** [comment]
We'll see wer die Baustelle nimmt.

**Comment by braver** [comment]
CSSlint is essentially a dead end... I’ll report the issue in that repo, if someone still wants to work on it, he or she is very welcome.

**Comment by kaste** [comment]
What's the state of the art css linter this week?

**Comment by braver** [comment]
stylelint is what the hip kids use today

**Comment by hirschferkel** [comment]
CSSlint will automatically be installed with SublimeLinter, won't it? Or is it possible thus to change to stylelint?

> stylelint is what the hip kids use today
