### ISSUE TITLE
.bak files in a project folder causes sublime linter to stop working

### ISSUE THREAD

**Issue by mm4dd** [SublimeLinter/SublimeLinter#1712]
Hello,

I am using sublime linter 3 in conjunction with the SublimeLinter-contrib-modelsim package.  I have noticed that when sublime 3 creates a back up copy of a file with the .bak file extension my code linting using the SublimeLinter-contrib-modelsim stops working.  I have to remove the .bak file and remove the project folder  and re-add the project folder to get linting working again.  Is there any way to fix this problem?

Thanks

**Comment by kaste** [comment]
Do you have a screencast? Also enable debug setting, and open the Sublime console to see the verbose logging. I actually never had *.bak* files in Sublime. Is this a Sublime feature? Removing and then re-adding the project folder is very strange because iirc we don't cache anything related to that. (We don't cache anything at all.) Maybe the underlying linter from modelsim gets confused?

**Comment by braver** [comment]
Sublime Text does not make .bak files. Or any other files. Probably the linter program itself is getting stuck or something. Please follow the troubleshooting guide to give us some information to work with:
http://www.sublimelinter.com/en/stable/troubleshooting.html#

**Comment by mm4dd** [comment]
I firstly should apologise. It turns out that it is not Sublime 3 creating the .bak files but another software tool we use for FPGA development by Intel.
In any event it is the .bak files in my project directory that is causing the linter to stop working. Hopefully I can capture some useful feedback to give to you.
Thanks so much for the very quick reply to my question.

**Comment by mm4dd** [comment]
Thanks to kaste and braver I have found the issue with the linter and the modelsim linter plugin.  It turns out I needed to specify the work space directory path to the current directory for the lint tool.  Thank you again for help.

**Comment by braver** [comment]
🎉
