### ISSUE TITLE
Export `PermanentError` and `read_json_file`

### ISSUE THREAD

**Issue by kaste** [SublimeLinter/SublimeLinter#1713]
Reminder: Both are used *public* e.g. in the eslint plugin. Proper export them under `SublimeLinter.lint`. 

`PermanentError`and `TransientError` are probably no-brainers. 

About `read_json_file`: Although we have the policy to not export anything beyond core, and reading a json file is clearly a utility function, that particular fn has a built-in cache. Thus plugin authors _should_ really use our function here so that we share that cache.

**Comment by kaste** [comment]
Proposed PR #1724 will export the our exception classes. We will *NOT* export `read_json_file` because it's a commitment to the future we cannot make. Added a comment
here about its possible usage in the wild.

- Generally, `read_json_file` is easy to do in Vanilla Python even with the cache functionality if we ever remove this in core.  (Using a *shared* cache typically saves one call per Sublime session; so using a local cache would be no awful waste. Not using a cache at all is not recommended.)

- We already do not guarantee that the cache is warm because we always take the shortest path in SublimeLinter core possible. (T.i. if we don't need to read `package.json` we don't.)  We especially do not want to make the commitment to warm the cache. 

- Since we're multi-language, it is rather possible that we maybe read other "manifest"/"meta" data in the future which can be in any format. It is thus an option to make this data available in the `context` object, ready to use.  (For example we could do something like `self.context['manifest'] = read_json_file(...)` in the Node context.)

**Comment by braver** [comment]
Excellent 👌🏻
