### ISSUE TITLE
A project with `yarn@2` fails to find ESLint plugins and presets when global cache is used

### ISSUE THREAD

**Issue by kapooostin** [SublimeLinter/SublimeLinter#1715]
I migrated a project to `yarn@2`. `SublimeLinter-eslint` works fine (if only rather slower than global `eslint` on `yarn@1` without PnP).

In my project's settings I have:
```json
"settings": {
  "SublimeLinter.linters.eslint.executable": [ "/path/to/.yarn/bin/yarn", "run", "eslint" ],
}
```

But I only managed to start it if all dependencies are kept in the project locally. If I add `enableGlobalCache: true` to `.yamlrc.yml` and reinstall, SL returns an error:

`ERROR: Error: Cannot read config file: /path/to/project/.yarn/$$virtual/eslint-config-standard-virtual-108105a15f/7/path/to/yarn/.yarn/berry/cache/eslint-config-standard-npm-14.1.0-c6ff55be07-2.zip/node_modules/eslint-config-standard/index.js
`

macos 10.14.6
Sublime Text 4068
node 10.15.3
SublimeLinter 4

**Comment by kaste** [comment]
Afaik that is normal behavior of the newer eslint versions? T.i. all dependencies must be local or you have to set a command line arg (`--resolve-...`). 

Since yarn2 is relatively new, maybe enable "debug" in the global settings, just to confirm the working path etc. settings SublimeLinter uses here are sane. This will also print the command we execute to easily reproduce it on the command line.

**Comment by kapooostin** [comment]
Global cache for packages in Yarn@2 doesn't make them global since Yarn itself now doesn't have `yarn global` at all. `enableGlobalCache` just allows it to store deps in one place for a sake of saving up some space.

AFAIU Yarn mounts cache as some virtual drive, that is what `$$virtual` stands for in the path above.

Is it the output from debug mode you have meant?
```
$ cat src/hooks/add-border-to-images.js | /path/to/yarn/.yarn/bin/yarn run eslint --format json --stdin --stdin-filename /path/to/project/src/hooks/add-border-to-images.js

SublimeLinter: linter.py:1103         eslint: Checking lint mode 'background' vs lint reason 'on_load'.  Ok.
SublimeLinter: #3 linter.py:1196      annotations: no output
SublimeLinter: sublime_linter.py:575  Linting '.eslintrc.yml' took 0.05s
SublimeLinter: linter.py:1103         annotations: Checking lint mode 'background' vs lint reason 'on_load'.  Ok.
SublimeLinter: #4 linter.py:1120      annotations: linting 'helpers.js'
SublimeLinter: #5 linter.py:1120      eslint: linting 'helpers.js'
SublimeLinter: #5 linter.py:900       eslint: wanted executable is ['/path/to/yarn/.yarn/bin/yarn', 'run', 'eslint']
SublimeLinter: #6 linter.py:1120      annotations: linting '.yarnrc.yml'
SublimeLinter: #5 linter.py:1636      Running ...
...
SublimeLinter: #14 linter.py:112      ERROR: Error: Cannot read config file: /path/to/yarn/.yarn/berry/cache/eslint-npm-6.8.0-96f92f0dca-2.zip/node_modules/eslint/conf/eslint-recommended.js
Error: Cannot find module '/path/to/yarn/.yarn/berry/cache/eslint-npm-6.8.0-96f92f0dca-2.zip/node_modules/eslint/conf/eslint-recommended.js'
Require stack:
- /path/to/yarn/.yarn/berry/cache/eslint-npm-6.8.0-96f92f0dca-2.zip/node_modules/eslint/lib/cli-engine/noop.js
Referenced from: /path/to/project/.eslintrc.yml
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.module_1.Module._resolveFilename (/path/to/project/.pnp.js:30014:54)
    at resolveFileName (/path/to/yarn/.yarn/berry/cache/resolve-from-npm-4.0.0-f758ec21bf-2.zip/node_modules/resolve-from/index.js:29:39)
    at resolveFrom (/path/to/yarn/.yarn/berry/cache/resolve-from-npm-4.0.0-f758ec21bf-2.zip/node_modules/resolve-from/index.js:43:9)
    at module.exports (/path/to/yarn/.yarn/berry/cache/resolve-from-npm-4.0.0-f758ec21bf-2.zip/node_modules/resolve-from/index.js:46:41)
    at module.exports.moduleId (/path/to/yarn/.yarn/berry/cache/import-fresh-npm-3.0.0-0b0df76bef-2.zip/node_modules/import-fresh/index.js:11:19)
    at loadJSConfigFile (/path/to/yarn/.yarn/berry/cache/eslint-npm-6.8.0-96f92f0dca-2.zip/node_modules/eslint/lib/cli-engine/config-array-factory.js:201:16)
    at loadConfigFile (/path/to/yarn/.yarn/berry/cache/eslint-npm-6.8.0-96f92f0dca-2.zip/node_modules/eslint/lib/cli-engine/config-array-factory.js:284:20)
    at ConfigArrayFactory._loadConfigData (/path/to/yarn/.yarn/berry/cache/eslint-npm-6.8.0-96f92f0dca-2.zip/node_modules/eslint/lib/cli-engine/config-array-factory.js:496:13)
    at ConfigArrayFactory._loadExtendedBuiltInConfig (/path/to/yarn/.yarn/berry/cache/eslint-npm-6.8.0-96f92f0dca-2.zip/node_modules/eslint/lib/cli-engine/config-array-factory.js:753:25)```

**Comment by kapooostin** [comment]
Well, if I run `cat src/hooks/add-border-to-images.js | /path/to/yarn/.yarn/bin/yarn run eslint --format json --stdin --stdin-filename /path/to/project/src/hooks/add-border-to-images.js`, I get the same error. It means the problem is somewhere upstream, right?

**Comment by kaste** [comment]
Yeah, probably. Maybe try without the piping.

```
/path/to/yarn/.yarn/bin/yarn run eslint --format json /path/to/project/src/hooks/add-border-to-images.js
```

Also note the working dir.

**Comment by kapooostin** [comment]
Yep, it works only if all packages are installed locally. Yet the only difference is a _relative_ path to packages, like:
```diff
-          "packageLocation": "../../../../../../path/to/yarn/.yarn/berry/cache/@babel-helper-hoist-variables-npm-7.8.3-7f5d43561e-2.zip/node_modules/@babel/helper-hoist-variables/",
+          "packageLocation": "./.yarn/cache/@babel-helper-hoist-variables-npm-7.8.3-7f5d43561e-2.zip/node_modules/@babel/helper-hoist-variables/",
```

Thank you for help, I'll head to a ESLint repo now.

**Comment by kaste** [comment]
👍

**Comment by kapooostin** [comment]
The issue is filed as bug at Yarn https://github.com/yarnpkg/berry/issues/965.
And there is little benefit from global cache on Macos anyway https://github.com/yarnpkg/berry/issues/954
