### ISSUE TITLE
Allow and support multiline messages

### ISSUE THREAD

**Issue by kaste** [SublimeLinter/SublimeLinter#1716]
We currently smash "\n" in messages into " " (spaces). Usually type checker produce lengthy, informative messages and we should support their formatting. (I had this for Haskell, but flow, ts, and mypy would also benefit.)

Since the panel already wraps lengthy lines, and with it technically produces multiline messages, I hope this to be a simple change.

**Comment by braver** [comment]
Maybe it also depends on where the message shows up. Maybe in the statusbar we should just show the first line. And then if it looks good in the tooltips and output panel, why not have multiple lines? Ideally we should just show the message as-is whenever possible.

**Comment by kaste** [comment]
Yeah, the statusbar is only useful for the static old-scholl linter messages anyway, where you glimpse at the message and then already know the error. The type checkers produce unique messages in a context, and you really need to read carefully here and try to understand. 

But of course, git like, the first line is the subject, absolutely no need to change the backend data type and introduce "short_message" and "long_message".

**Comment by braver** [comment]
> But of course, git like, the first line is the subject, absolutely no need to change the backend data type and introduce "short_message" and "long_message".

exactly
