### ISSUE TITLE
Installation instructions don't describe linter installation

### ISSUE THREAD

**Issue by cliffckerr** [SublimeLinter/SublimeLinter#1718]
The text on

http://www.sublimelinter.com/en/stable/installation.html

does not explain how to actually install linters, does not include a link to the linters, and doesn't fully explain that SublimeLinter doesn't include any built-in. Suggested text:

```
SublimeLinter and corresponding linter plugins can be installed using PackageControl. Steps:

1. Install SublimeLinter
2. Install one or more linters from the list available here: https://packagecontrol.io/search/SublimeLinter

Note: it may be necessary to restart SublimeText after package installation.
```

Bonus points: have an option to automatically install SublimeLinter-written plugins (at least for major languages) rather than having to install each one separately.

**Comment by braver** [comment]
This information is already at the top of the README. Perhaps it could be more verbose though.

> Bonus points: have an option to automatically install SublimeLinter-written plugins (at least for major languages) rather than having to install each one separately.

There are over 50 plugins in the SublimeLinter org. We're definitely not going to install all of them. It's your editor, you make the choices for what to install or not. It's also one way that Sublime Text is different from VS Code or other editors that have everything pre-installed. You have to do some work, but it also gives you control.

**Comment by cliffckerr** [comment]
@braver Thanks, good point re: plugins, I didn't realize how many there were. Re: installation instructions, I've been using Sublime and Package Control for years, and it was still enough to confuse me, so I do believe more verbose would be appreciated! Specifically, there is no link to the actual plugins available to install from the installation instructions page, nor are they listed anywhere. As far as I can tell, unless you can somehow guess that there's a plugin with the name e.g. `SublimeLinter-jsl`, the only way you can get a working version of SublimeLinter is to leave the installation instructions and instead go to the GitHub readme, and from _there_ clicking on the link to https://packagecontrol.io/search/SublimeLinter. I figured this out eventually, but it wasn't an ideal experience! The minimal change would be to replace the generic Package Control link in the installation instructions with the SublimeLinter-specific above one (from that page, if you don't know what Package Control is, it's pretty easy to navigate back down).

**Comment by kaste** [comment]
Well, the build failed. 😁

**Comment by braver** [comment]
Aw crap
