### ISSUE TITLE
SublimeLinter missing on package manager

### ISSUE THREAD

**Issue by swagnercarena** [SublimeLinter/SublimeLinter#1720]
SublimeLinter currently shows up as missing on the sublime package manager. These seems to block me from installing it in Sublime3.

![image](https://user-images.githubusercontent.com/8857025/78304145-e4ef0a00-74f2-11ea-9b0c-4c7cb0b03576.png)

I've seen in previous version of this post that the issue was with package control. However I can install other packages just fine.

**Comment by braver** [comment]
Must've been a temporary hiccup

<img width="521" alt="Screen Shot 2020-04-03 at 09 54 21" src="https://user-images.githubusercontent.com/2543659/78337335-20d8ac80-7591-11ea-9e99-eeb435c65c8d.png">
