### ISSUE TITLE
Getting error after installing and unable to find SublimeLinter folder in Packages

### ISSUE THREAD

**Issue by ShivamS136** [SublimeLinter/SublimeLinter#1732]
I am on Windows 10 using Sublime Text 3 and getting below errors after downloading `htmllint-cli` and after reinstalling `SublimeLinter` after removing `htmllint-cli`.

Error is as below:
````
SublimeLinter: ERROR:
=====================

htmllint: Defining 'cls.syntax' has no effect anymore. Use http://www.sublimelinter.com/en/stable/linter_settings.html#selector instead.


SublimeLinter: ERROR:
=====================

htmllint disabled. 'cls.defaults' is mandatory and MUST be a dict.
````

Also I am not able to see `SublimeLinter` folder inside `Packages` folder. While the package is visible inside `Package Control` and `Package Settings`.

Seems similar issue like: [#1632](https://github.com/SublimeLinter/SublimeLinter/issues/1632)

**Comment by kaste** [comment]
Hm, the published htmllint package is outdated and doesn't work anymore. You could clone its master branch t.i. install manually into the Packages folder.

You don't see SublimeLinter there because installed packages using Package Control are in a different folder.

**Comment by braver** [comment]
Please see the open issues here: https://github.com/necramirez/SublimeLinter-contrib-htmllint. If htmllint is still widely in use, but the plugin's maintainer is MIA, we can consider pulling it into the SublimeLinter org so it can be updated. If you want to follow this path, please open an issue in said repo and give me a heads-up if there is no reaction from the maintainer in a week or two.
