### ISSUE TITLE
Defining 'cls.syntax' has no effect anymor

### ISSUE THREAD

**Issue by TAIFUNT** [SublimeLinter/SublimeLinter#1736]
Hello!
Can you help me? Please.

I have error:

> SublimeLinter: ERROR:
> =====================
> jsl: Defining 'cls.syntax' has no effect anymore. Use http://www.sublimelinter.com/en/stable> /linter_settings.html#selector instead.

My settings:
// SublimeLinter Settings - User
{
        "debug": true,
        "delay": 0.25,
        "gutter_theme": "Packages/SublimeLinter/gutter-themes/Circle/Circle.gutter-theme",
        "lint_mode": "background",
        "linters": {
            "csslint": {
                "@disable": false,
                "args": [],
                "errors": "",
                "excludes": [],
                "ignore": "",
                "warnings": ""
            },
            "hlint": {
                "@disable": false,
                "args": [],
                "excludes": []
            },
            "htmltidy": {
                "@disable": false,
                "args": [],
                "excludes": [],
                "executable": "D:\\Install\\Tidy\\tidy.exe"
            },
            "jscs": {
                "@disable": false,
                "args": [],
                "excludes": []
            },
            "jshint": {
                "@disable": false,
                "args": [],
                "excludes": []
            },
            "jsl": {
                "@disable": false,
                "args": [],
                "excludes": []
            },
            "php": {
                "@disable": false,
                "args": [],
                "excludes": [],
                "cmd": "C:\\Program Files (x86)\\PHP\\php.exe"
            },
            "phplint": {
                "@disable": false,
                "args": [],
                "excludes": [],
                "executable": "C:\\Program Files (x86)\\PHP\\php.exe"
            }
},
        "no_column_highlights_line": false,
            "paths": {
            "linux": [],
            "osx": [],
            "windows": []
        },
        "show_marks_in_minimap": true,
        //"sublimelinter_executable_map": {
        // "css": "node",
        // "html": "D:\\Install\\Tidy\\tidy.exe", //путь до вашей папки с tidy.exe, обратите внимание на двойные обратные слеши, они обязательны
        // "php": "C:\\Program Files (x86)\\PHP\\php.exe" //путь до вашей папки с php.exe
        //},
        "syntax_map": {
        "css": "css",
        "html (django)": "html",
        "html (rails)": "html",
        "html 5": "html",
        "js": "js",
        "php": "php",
        "python django": "python"
},
}
//executable

What can I do to fixed my SublimeLinter settings?

**Comment by kaste** [comment]
The error is coming from the linter plugin. This plugin "jsl" needs an update.

**Comment by TAIFUNT** [comment]
> 
> 
> The error is coming from the linter plugin. This plugin "jsl" needs an update.

Thx! Sorry, how can I update "jsl" plugin?

**Comment by kaste** [comment]
It is recommended to install using Package Control which also updates everything automatically by default. 

First find out how you installed jsl. Maybe you manually downloaded it to the Packages folder. Maybe it is enough to invoke "Remove Package" using the Command Palette. After removing a package it is always necessary to restart Sublime. Make sure it really has been removed after restarting Sublime. Only then attempt a new install.

**Comment by TAIFUNT** [comment]
> 
> 
> It is recommended to install using Package Control which also updates everything automatically by default.
> 
> First find out how you installed jsl. Maybe you manually downloaded it to the Packages folder. Maybe it is enough to invoke "Remove Package" using the Command Palette. After removing a package it is always necessary to restart Sublime. Make sure it really has been removed after restarting Sublime. Only then attempt a new install.

I install "jsl" from Package Control. Now I have **v.1.1.5** It`s ok?
![2020-05-01_13-32-24](https://user-images.githubusercontent.com/6401505/80799881-b414fa00-8bb0-11ea-9062-923ea53d1bef.png)

**Comment by kaste** [comment]
Well, I know see that master is not released, and the newest version is 5 years old 😒

@braver can you make a release?

**Comment by braver** [comment]
Huh, how did that happen? Release is done, should show up in Package Control in an hour or so.

**Comment by TAIFUNT** [comment]
Thx guys! :)
I upgrade "jsl" to v.1.2.0
