### ISSUE TITLE
[Question] How to handle default linting with nested scopes?

### ISSUE THREAD

**Issue by oconnor0** [SublimeLinter/SublimeLinter#1737]
Say I have 2 languages that need to be linted differently and have different scopes (ala Clojure and ClojureScript) but that are syntactically identical so that the language scopes are defined as `source.clojure` and `source.clojure.clojurescript` respectively. It looks like SublimeLinter runs all matching linters. Is there a way to change SublimeLinter to only run the "best matching" linter? Or something.

See https://github.com/ToxicFrog/SublimeLinter-contrib-clj-kondo/issues/1 and https://github.com/sublimehq/Packages/pull/2355 for work I've been trying to coordinate on this.

**Comment by braver** [comment]
[Selectors](https://www.sublimetext.com/docs/3/selectors.html) are actually pretty powerful here. `source.clojure - source.clojure.clojurescript` might be what you're looking for, or `source.clojure - clojurescript` ... I'm a bit rusty on the nitty gritty here.

This is also one of the reasons those scopes exist: if it's necessary for a package to be able to work on one language, but not the other, it should be possible to differentiate between the two using selectors. So if you can't get it to work, the first place to try to change something is the syntax, not SublimeLinter.

**Comment by oconnor0** [comment]
Perfect, thank you. This looks resolved to me!
