### ISSUE TITLE
Is there a way to make the linter results in the panel clickable?

### ISSUE THREAD

**Issue by oconnor0** [SublimeLinter/SublimeLinter#1738]
It would be amazing to be able to click on linter results that display in the panel and goto them in the code. Is such a thing possible?

**Comment by kaste** [comment]
Double-click 💪

**Comment by oconnor0** [comment]
But I want to single click! 🤦 

Thanks. Double-clicking is great. Even if this behavior isn't changed, maybe it's worth documenting?

**Comment by kaste** [comment]
We would need documents in the first place. 🤪

**Comment by braver** [comment]
It’s just an output panel, the interaction is the same as with all similar panels already available in Sublime Text (like search results). I’d expect their documents to already cover this.
