### ISSUE TITLE
mark_style: squiggly_underline

### ISSUE THREAD

**Issue by mauroreisvieira** [SublimeLinter/SublimeLinter#1740]
**SL Settings:**
The underline styles are replaced with outlines when there is whitespace in the problem region, because underlines aren't drawn on whitespace (ST issue https://github.com/sublimehq/sublime_text/issues/137).

ST issue [https://github.com/sublimehq/sublime_text/issues/137](https://github.com/sublimehq/sublime_text/issues/137) was solved, can you fix that from you side?

**Comment by kaste** [comment]
Maybe we should put this on the SL4 issue #1700?  Although... I'm actually used to the outlines now, and consider them generally better for (at least) multiline regions.  (I absolutely do not understand how VSCode can draw red squiggles over a whole function.)  Also our markers go away, into a "hidden" state, when you type "in" them.  We should produce some screenshots how this would look like for errors on one line, and of course multiple lines.

**Comment by braver** [comment]
Yeah, squiggles over multiple lines would are not something that I miss. But I also think that’s just linters being stupid. Anyway, newlines are a specific kind of white space and I definitely want squiggles across spaces. So we should really have a go at this and see if we can improve for ST4

**Comment by braver** [comment]
I'd call this a definite improvement and a good middle ground:

<img width="569" alt="Screen Shot 2020-05-27 at 21 26 52" src="https://user-images.githubusercontent.com/2543659/83064227-c1af8980-a061-11ea-8543-882faa463c20.png">

```diff
diff --git a/highlight_view.py b/highlight_view.py
index bd68e6e..ca1c356 100644
--- a/highlight_view.py
+++ b/highlight_view.py
@@ -293,8 +293,13 @@ def _compute_flags(error):
     # type: (LintError) -> int
     mark_style = style.get_value('mark_style', error, 'none')
     selected_text = error['offending_text']
-    # Work around Sublime bug, which cannot draw 'underlines' on spaces
-    if mark_style in UNDERLINE_STYLES and SOME_WS.search(selected_text):
+    if int(sublime.version()) < 4074:
+        # Work around Sublime < 4074 bug, which cannot draw 'underlines' on spaces
+        regex = SOME_WS
+    else:
+        # In Sublime > 4074, we still prefer outlines over multi-line errors
+        regex = MULTILINES
+    if mark_style in UNDERLINE_STYLES and regex.search(selected_text):
         mark_style = FALLBACK_MARK_STYLE
 
     flags = MARK_STYLES[mark_style]
```

Maybe we also need to change some of the demoting logic?

**Comment by kaste** [comment]
You see how easy it is to make changes to my fabulous code. 😉

Ensure that the version call does not go over the wire to the Sublime main thread. Make it a constant if possible, that's a hot path here.  SUBLIME_SUPPORTS_WS_SQUIGGLES

**Comment by braver** [comment]
> You see how easy it is to make changes to my fabulous code

If *I* can do it, everyone can!

> Ensure that the version call does not go over the wire to the Sublime main thread

I kinda expect this call immediately returns a constant from memory, but regardless I agree it should be a constant instead of littering such calls across the code.
