### ISSUE TITLE
SublimeLinter: ERROR:   Execution failed [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by yamyoume** [SublimeLinter/SublimeLinter#1743]
SublimeLinter stopped working after I moved all my files from builds/development/*files* to builds/development/public_html/*files*
I can't seem to be able to figure it out, why does it remember the previous dir, and also it's not working on new files created in this project.
Other sublimetext projects are working just fine
one thing I did after moving the files, is 
- close the project 
- manually edit my project.sublime-workspace and added /public_html to all the files so they are still linked 
- reopened the project
all the files are still linked 
```
SublimeLinter: ERROR:   Execution failed

  [Errno 2] No such file or directory: '/Users/yamantarakji/Sites/acapedia/builds/development/crm'

  /Users/yamantarakji/Sites/acapedia/builds/development/crm  (working dir)
  $ cat ../public_html/crm/test.php | /usr/local/bin/php -l -n -d display_errors=On -d log_errors=Off
```
it should be development/public_html/crm

**Comment by kaste** [comment]
Hi! 

SublimeLinter doesn't use caches.  Here the working dir is wrong.  The working dir is one of the folders you have opened; basically the top folders you see in the sidebar.  

You can open the Sublime console (View -> Show console) and type `window.folders()` which will return exactly this information available to SublimeLinter. 

If you have a project file open this can be set in the `.sublime-project` file, if you just use workspace files I actually don't know where the information is stored.

**Comment by yamyoume** [comment]
YESS, thank you, I swear I have done this at least 30 times, because I switched from Windows to linux to mac and I always copy and edit the sublimetext project files, for some reason yesterday after I edited `project.sublime-workspace`, it didn't occur to me to also edit the `project.sublime-project`
