### ISSUE TITLE
Couldn't find method of installation in README

### ISSUE THREAD

**Issue by yamak0224** [SublimeLinter/SublimeLinter#1747]
## Procedure I did
1. Saw [Page of GitHub of Sublime Linter](https://github.com/SublimeLinter/SublimeLinter/blob/5c7fed5d7737f9870ffa3089c9fe1504f107cd65/README.md)
2. Searched item of "Install", but don't exist
3. Looked at the README from the top of page, and began to look at the item of "Setting"
4. Saw Sentence "Additional information is in our docs at sublimelinter.com." and flew to [sublimelinter.com](http://www.sublimelinter.com/en/stable/)
5. Found the "User Documentation"->"Installation", So I proceeded installation from there.

## Expected Result
Item of "Installation" exist in step of "Procedure I did 2."

## Actual Result
When see the README, Couldn't find method of installation. So I couldn't install "Sublime Linter".

**Comment by braver** [comment]
Ah, sure, we could be clearer on this. The preferred installation method is via Package Control. I'll add a note about that and a link to our docs.
