### ISSUE TITLE
can't seem to ignore files

### ISSUE THREAD

**Issue by godbout** [SublimeLinter/SublimeLinter#1751]
hello!

i guess i'm not using some settings correctly. i'm linting my js using semistandard.js. works well, except i can't ignore js inside html (blade) files.

here are my current settings:

```json
"linters": {
        "standard": {
            "selector": "source.js - text.html.blade",
            "excludes": ["*/*.blade.php"],
        },
    }
```

probably a simple thing i'm missing? thanks!

**Comment by kaste** [comment]
A first shot in the dark, does it really say "standard" for example in the status bar or error panel. Don't they have a typo and named it "Standard"?

**Comment by godbout** [comment]
Aaaarrrrgggghhhhh. good catch. it's actually `semistandard`. it's a weird setup. i use the `semistandard` linter combined with the `StandardFormat` package but calling the `semistandard` tool 😅️.

<img width="444" alt="StandardFormat_sublime-settings_—_company_hq" src="https://user-images.githubusercontent.com/121373/85218160-1ed0fd80-b3ca-11ea-8956-bf4641574f70.png">

i mixed things up. with `semistandard` instead of `standard` in SublimeLinter settings, it works great. thanks!

PHP coder here, learning Python since last week to be able to develop and contribute to ST packages. hopefully will help on this too!

thanks @kaste. appreciated the help.

**Comment by kaste** [comment]
💐
