### ISSUE TITLE
`file_on_disk` linters may run on untitled buffers

### ISSUE THREAD

**Issue by kaste** [SublimeLinter/SublimeLinter#1761]
We have this forever, but

https://github.com/SublimeLinter/SublimeLinter/blob/7704326262023e9bece16932ef1a4dd36c4635b9/lint/linter.py#L1081

We should check `view.file_name()` actually for correctness. 

Ref: https://github.com/SublimeLinter/SublimeLinter-pylint/issues/62

**Comment by harshraj22** [comment]
> We should check view.file_name() actually for correctness.

as per API [documentation](https://www.sublimetext.com/docs/3/api_reference.html#sublime.View), view.file_name( ) would return:
`The full name file the file associated with the buffer, or None if it doesn't exist on disk.`
So, if user is editing a file which exists on disk, view.file_name( ) would **Not return None** even if file is currently being edited (un saved). while the comment on line 1080 says
 `# A 'saved-file-only' linter does not run on unsaved views`.

 So, wouldn't using view.file_name( ) create a problem in this case ?  @kaste

**Comment by kaste** [comment]
I thought we check for the file name *and* if the buffer is marked dirty. That should do it, no?

**Comment by harshraj22** [comment]
> I thought we check for the file name _and_ if the buffer is marked dirty. That should do it, no?

Oh ! now I see what you meant ! You just wanted to replace `cls.tempfile_suffix == '-'` with `view.file_name( )` and not the whole condition inside if block right ?
