### ISSUE TITLE
Cannot get SublimeLinter on wsl working

### ISSUE THREAD

**Issue by getify** [SublimeLinter/SublimeLinter#1764]
I have installed SublimeLinter plugin for ST3 install in windows 10, as well as the sublimelinter-eslint plugin. However, I'm having trouble getting it to start correctly.

I have eslint installed inside my WSL instance, so from windows, to execute binaries inside of WSL, the command is like `wsl eslint"`, where that `wsl` program (provided by windows) does the bridging. If you run that command from a normal `CMD` prompt, it works fine.

However, when I configured SublimeLinter-eslint like this:

```js
"executable": "wsl eslint"
```

I get this error in the ST3 console:

> You set 'executable' to 'wsl eslint'.  However, 'which wsl eslint' returned nothing. Try setting an absolute path to the binary.

I tried changing the path to:

```js
"executable": "\\\\wsl$\\Debian\\usr\\local\\bin\\eslint"
```

From inside the WSL terminal, you can run `/usr/local/bin/eslint` and it definitely runs. But unfortunately, when I set that absolute path, I get a different error in the ST3 console:

> SublimeLinter: WARNING: eslint cannot locate 'eslint'

So I'm stuck, not sure what to do?

**Comment by getify** [comment]
BTW, here's my full SL config:

```js
{
	"delay": 5,
	"gutter_theme": "Default",
	"highlights.demote_while_editing": "all",
	"highlights.time_to_idle": 5,
	"lint_mode": "load_save",
	"linters": {
		"eslint": {
			"executable": "\\\\wsl$\\Debian\\usr\\local\\bin\\eslint",
			"disable": false,
			"args": ["-c ~/.eslint.json"],
			"excludes": [],
			"styles": [
				{
					"priority": 1,
					"mark_style": "none"
				}
			]
		}
	},
	"show_marks_in_minimap": false
}
```

**Comment by kaste** [comment]
That's a chilling, distraction free config 👍 

About `wsl`, the problem always was that the actual file paths aren't translated back and forth.  

```
"executable": ["wsl", "eslint"]
```

would be - from my understanding - the correct setting.  Iirc we then send it a normal windows filename, the one we get from Sublime Text, and the wrapper or entrypoint `wsl` does *not* translate the arguments, here the filenames, to the unix world.  (Although `wsl` runs from the Windows world.)  

That's how I remember the situation, maybe 2 years ago.  Maybe that or something changed.  Try setting `executable` again and it will probably show a superb error message.

**Comment by getify** [comment]
Just curious, why does the linter need to send it a filename/filepath? Does it not feed the contents of the open file directly to eslint? How does it lint while typing if you haven't saved a file yet?

**Comment by getify** [comment]
Oh, also, there's a command called `wslpath` you can run to translate paths. It's (perplexingly) inside of WSL, but you can access it from the outside like this:

```cmd
wsl wslpath
Usage:
    -a    force result to absolute path format
    -u    translate from a Windows path to a WSL path (default)
    -w    translate from a WSL path to a Windows path
    -m    translate from a WSL path to a Windows path, with '/' instead of '\'
```

**Comment by kaste** [comment]
A lot of linters don't need the filename just stdin. But eslint is not that linter. It probably can apply different rules per path, and also the eslintignore rules.

**Comment by kaste** [comment]
Ideally we had a python implementation of wslpath because speed.  You could try wslpath with caching of course.  We had an issue open to support wsl but no upvotes on that nor PR so eventually closed. I'll take any PR here and I'm willing to test and guide on my Windows.  Maybe vim's ale or emacs solved it. Esp. Ale is a superb source.

**Comment by getify** [comment]
OK, so I'm now getting errors like this:

```cmd
SublimeLinter: WARNING: eslint reported errors coming from '\mnt\c\Users\whatever\Desktop\C:UserswhateverDesktoptest.js'. However, reading that file raised:
  [WinError 3] The system cannot find the path specified: '\\mnt\\c\\Users\\whatever\\Desktop\\C:UserswhateverDesktoptest.js'.
```

So I take it that's what you meant about the path problem?

**Comment by kaste** [comment]
Yeah that's the path translation problem.  It even eats the slashes (path separators) so we receive complete garbage.

**Comment by getify** [comment]
So, just to clarify, this is a problem without a workaround, as far as the current situation is concerned?

I don't know any python, but I wouldn't mind trying my hand at a PR, if you had any suggestions about approximately where such path-translation logic might need to go?

**Comment by getify** [comment]
Also... I just tried this from the `CMD` windows command line:

```cmd
C:\Users\whatever\Desktop>wsl eslint -c ~/.eslintrc.json test.js

/mnt/c/Users/whatever/Desktop/test.js
  1:9  error  A trailing decimal point can be confused with a dot  no-floating-decimal

✖ 1 problem (1 error, 0 warnings)
  1 error and 0 warnings potentially fixable with the `--fix` option.
```

IOW, if I provide a single filename to `eslint`, it works properly. It's only if I tried to provide a fully qualified (or relative) path that I see the path issues cropping in.

Would it be feasible for SL (and the eslint plugin) to only provide **just** the filename (in the cross-wsl boundary call) and not a full path?

**Comment by kaste** [comment]
I took a look at the eslint plugin and it looks like we actually have a flag if we should set/send the filename to eslint.  Maybe that's useful here:

```
"linters": {
    "eslint": {
      "stdin-filename": false",
	  ...
    },
    ...
}

This could actually work if we're lucky.  But the fancy rules stuff you can have with eslint will not work of course.

If we just send the filename (not the absolute path), no linter will probably make sense of it.  They will assume this is relative to the working dir.

**Comment by getify** [comment]
> If we just send the filename (not the absolute path), no linter will probably make sense of it. They will assume this is relative to the working dir.

Understood, that makes sense. Would it be impractical to change the CWD to where the file being linted is (usually, just the current open file, right) before sending it to eslint, and then perhaps revert the CWD back after getting the results back?

**Comment by kaste** [comment]
A proper fix is not a trivial task here.  We have a `context` object/mapping for example where we freeze all the paths etc. And since we have it we can of course fake everything here, and pretend whatever filename.  But the confusing part here is that `wsl` itself runs on the normal `cmd.exe`, so for example the working dir, `PATH` and the whole ENV(ironment) vars cannot change.  So we would need to fake it at the other boundary probably just before we execute the command. That would be here

https://github.com/SublimeLinter/SublimeLinter/blob/ea566d82db51c32a441dd7af8b5d182967d8215c/lint/linter.py#L1515-L1519

Here you can rewrite the `cmd` to your liking.  

The other idea is interesting.  For that you just set 

```
"working_dir": "${file_path}",
"stdin-filename": "${file_name}"
```

That could work.

**Comment by getify** [comment]
I added those to my config, and this is what the error says now:

```cmd
SublimeLinter: WARNING: eslint reported errors coming from '\mnt\c\Users\whatever\Desktop\test.js'. However, reading that file raised:
  [WinError 3] The system cannot find the path specified: '\\mnt\\c\\Users\\whatever\\Desktop\\test.js'.
```

So, the path munging problem seems to have been fixed, or at least significantly improved? But it's still not working.

Notable that, from the perspective of eslint inside WSL, the path `\mnt\c\Users\whatever\Desktop\test.js` is completely valid. But that path makes no sense outside of WSL, so I would guess this error is that SL doesn't know what to do with that path?

**Comment by getify** [comment]
BTW, if I try to specify a custom location for the config file via the `args` array, I get an interesting error that seems to indicate that SL is trying to parse out and handle configs manually?

```js
args: ["-c ~/some/other/config.json"]
```

The error is:

```cmd
Value for 'config' of type 'path::String' required.
```

If I instead do:

```js
args: ["-c", "~/some/other/config.json"]
```

I get the path munging problem, where that the error reported says the config can't be found and what it reports is a really messed up path string.

**Comment by 0xh4sh** [comment]
> I have installed SublimeLinter plugin for ST3 install in windows 10, as well as the sublimelinter-eslint plugin. However, I'm having trouble getting it to start correctly.
> 
> I have eslint installed inside my WSL instance, so from windows, to execute binaries inside of WSL, the command is like `wsl eslint"`, where that `wsl` program (provided by windows) does the bridging. If you run that command from a normal `CMD` prompt, it works fine.
> 
> However, when I configured SublimeLinter-eslint like this:
> 
> ```js
> "executable": "wsl eslint"
> ```
> 
> I get this error in the ST3 console:
> 
> > You set 'executable' to 'wsl eslint'.  However, 'which wsl eslint' returned nothing. Try setting an absolute path to the binary.
> 
> I tried changing the path to:
> 
> ```js
> "executable": "\\\\wsl$\\Debian\\usr\\local\\bin\\eslint"
> ```
> 
> From inside the WSL terminal, you can run `/usr/local/bin/eslint` and it definitely runs. But unfortunately, when I set that absolute path, I get a different error in the ST3 console:
> 
> > SublimeLinter: WARNING: eslint cannot locate 'eslint'
> 
> So I'm stuck, not sure what to do?

Try navigating into `wsl$\\Debian\\usr\\local\\bin\\eslint` using the WSL terminal and running `explorer.exe .` (Remember the dot at the end). This should open the folder using Windows File Explorer which will then give you the "normal" Windows path. 

Let me know how it goes.

**Comment by kaste** [comment]
> eslint reported errors coming from '\mnt\c\Users\whatever\Desktop\test.js'.

That's although we send in just the filename?  Well then eslint itself makes it an abs path in its reporter.  (If you enable debug in SublimeLinter settings, it should print the JSON we get from eslint. So you can check what eslint reports.)  My hope was that it reports the simple filename back, in that case SublimeLinter will make the absolute path by joining the used working dir and the reported (relative) filename.  That would have been great. 

On the `-c`.  `"args": ["-c ~/some/other/config.json"]` doesn't make sense, or is really different.  Either you set `"args": "-c ~/some/other/config.json"` t.i. just a/one string. Then we try to split it into args and do some quoting.  Since quoting is the issue here, this likely fails but may be interesting to see.  It is though convenient because it looks like what you type on the command line.  If instead you set it to an array of strings, we assume the user did the splitting and we just pass it down.   Honestly, I doubt it will expand `~` here. Does eslint expand this for convenience?

**Comment by kaste** [comment]
@0xh4sh The `executable` must be a Windows executable, t.i. `.exe|.bat|.cmd`. @getify is running ST in Windows.  (Totally different, but I think you can run the nix SublimeText inside the subsystem, and then everything just works.)

**Comment by 0xh4sh** [comment]
> @0xh4sh The `executable` must be a Windows executable, t.i. `.exe|.bat|.cmd`. @getify is running ST in Windows. (Totally different, but I think you can run the nix SublimeText inside the subsystem, and then everything just works.)

Ah, okay. That's my bad, my sleep-deprived brain is a little slow rn. Thanks for clearing that up 👍

**Comment by getify** [comment]
Yeah, they're definitely sending back a fully qualified path:

```js
[{
    "filePath": "/mnt/c/Users/whatever/Desktop/test.js",
    "messages": [{
        "ruleId": "no-floating-decimal",
        "severity": 2,
        "message": "A trailing decimal point can be confused with a dot.",
        "line": 1,
        "column": 9,
        "nodeType": "Literal",
        "messageId": "trailing",
        "endLine": 1,
        "endColumn": 11,
        "fix": {
            "range": [10, 10],
            "text": "0"
        }
    }],
    "errorCount": 1,
    "warningCount": 0,
    "fixableErrorCount": 1,
    "fixableWarningCount": 0,
    "source": "var x = 1.;\n",
    "usedDeprecatedRules": [{
        "ruleId": "handle-callback-err",
        "replacedBy": []
    }, {
        "ruleId": "id-blacklist",
        "replacedBy": ["id-denylist"]
    }, {
        "ruleId": "no-buffer-constructor",
        "replacedBy": []
    }, {
        "ruleId": "no-catch-shadow",
        "replacedBy": ["no-shadow"]
    }, {
        "ruleId": "no-native-reassign",
        "replacedBy": ["no-global-assign"]
    }, {
        "ruleId": "no-negated-in-lhs",
        "replacedBy": ["no-unsafe-negation"]
    }, {
        "ruleId": "no-new-require",
        "replacedBy": []
    }, {
        "ruleId": "no-path-concat",
        "replacedBy": []
    }, {
        "ruleId": "no-restricted-modules",
        "replacedBy": []
    }, {
        "ruleId": "valid-jsdoc",
        "replacedBy": []
    }]
}]
```

So, if the plugin sends in just a filename, could the plugin then strip off all but the response filename, and then fully qualify it based on the current working directory?

**Comment by kaste** [comment]
@getify Is this still something you're interested in?

**Comment by getify** [comment]
yes very much so (I can't use my linter in my editor while this remains unfixed). Sorry if it seemed I abandoned, I just don't know enough python to do it myself. I was trying to find others to help me tackle it.

**Comment by kaste** [comment]
Hm, okay.  Above

```
   if on_windows and filename.startswith("/mnt/"): 
		filename = transform_unix_like_path_to_win(filename)
```

translates to 

```
	if os.name == "nt" and filename.startswith("/mnt/"):
		filename = filename[5] + ":" + filename[6:]
```

To be inserted before line 1375.  The code assumes "/mnt/" is the static prefix of length 5.  At pos `[5]` is the drive letter which afaik is always **one** letter, then comes the typical Windows `:`.  For example, given `"/mnt/c/Users/whatever/Desktop/test.js" will produce `"c:/Users/whatever/Desktop/test.js"`.  The later `os.path.normpath` at line 1379 will normalize the slashes for us.

I think always calling into `wsl` will be very slow.  Did you actually consider running Sublime Text on the *nix side; t.i. installing a window manager within the wsl, and then working from that?  (Basically you do for example Photoshopping and Chrome in Windows, but the hacking t.i. Terminal, tooling, plus editor in the for example ubuntu world.  (Of course, you had Sublime Text *also* installed in the Windows world for when you need it.)

Or you just install eslint and other tooling in the Windows world.  I just think of this working environment as one thing and everything being close together.  Like if *I* do audio: I would want my main program (DAW), the plugins and so on, nearby.  It should be frictionless and very fast. The switch is between, now I do coding, and now I do music.  But that's just a thought, the technical thing is ☝️.

**Comment by kaste** [comment]
Yeah sure.  git clone this repo into your Packages folder. Change the code, call SublimeLinter reload all plugins from Command Palette. Or restart Sublime.

**Comment by getify** [comment]
OK, will try to find time soon to attempt that. Thanks!

**Comment by Asuza** [comment]
@getify did you happen to get this working? I am running into the same issue and also don't know Python.

**Comment by kaste** [comment]
Closing as it's stale anyway.  Running through (complex) wrappers is usually very slow so any solution might finally fail for perf reasons.  I would have liked a try-out-PR to see it myself.  🤷‍♀️

**Comment by TheDirigible** [comment]
This should be reopened.  Running "wsl eslint" is lightning fast, and works fine from the cmd line, so there's no reason this shouldn't be working in Sublime.

**Comment by TheDirigible** [comment]
I've spent several hours on this and I'm giving up.  The debug log messages when failing to find a linter are not helpful, I have no idea where it's failing.  Here's my work if it helps anyone else.  Please post any progress.

Executable settings tried:
```
           "executable": "eslint.bat",
            // "executable": ["bash.exe", "-c", "wsl-eslint"],
            // "executable": ["wsl", "wsl-eslint"],
            // "executable": "wsl-eslint",
```

Windows batch file: eslint.bat
```
wsl wsl-eslint %*
```

Linux hack to convert paths: wsl-path
```
#!/bin/bash
str="${*/\\\\wsl\$\\Ubuntu/}"
str="${str//\\/\/}"
echo $str
```

Linux wrapper: wsl-eslint
```
#!/bin/bash
echo $* >> ~/never-reached
eslint $(wsl-path $*)
```

It never, ever reaches the linux side, even though it works fine from the windows and linux command lines.

**Comment by kaste** [comment]
The logging for eslint **is** broken for anything not js itself, t.i. all the plugins.  Make sure to keep things simple and only try it with Javascript files.  

IIRC correctly, `["wsl", "eslint"]` worked as `wsl` is in the Windows PATH and `eslint` then is on the linux side PATH.  If something is not findable via PATH, make sure to set absolute paths.  For example, setting `wsl-eslint` doesn't make sense as this is a linux thing but you're on Windows still.  `wsl wsl-eslint` makes sense *iff* `wsl-eslint` can be found...
