### ISSUE TITLE
Support for MinGW64 (MSys2) Environment on MS Windows

### ISSUE THREAD

**Issue by vladipus** [SublimeLinter/SublimeLinter#177]
Seems like a POSIX-like MinGW64 environment isn't working right now. I have created a PR to solve this problem: https://github.com/SublimeLinter/SublimeLinter3/pull/176

Posting an extract from the linter's ST3 configuration file here, to help those, dealing with MinGW64 on MSys2:

``` python
        "paths": {
            "linux": [],
            "osx": [],
            "windows": [
                "C:\\msys64\\mingw64\\bin"
            ]
        },
        "python_paths": {
            "linux": [],
            "osx": [],
            "windows": [
                "C:\\msys64\\mingw64\\lib\\python2.7\\site-packages"
            ]
        },
```

**Comment by kaste** [comment]
This should work in SL4 so I'm closing.
