### ISSUE TITLE
linting does not appear to be attempted

### ISSUE THREAD

**Issue by sryza** [SublimeLinter/SublimeLinter#1771]
As far as I can tell, linting is not being attempted.  No linter warnings appear when I insert syntax errors into my code.  No errors appear in the Sublime console.  In the past, I've had success debugging bad linter paths, etc.  This one has been especially difficult because it's not that the linter is erroring - it doesn't seem to be being run at all.

Here are my settings:
```
// SublimeLinter Settings - User
{
    "linters": {
      "flake8": {
        "disable": false,
        "executable": "/Users/sryza/.pyenv/versions/3.6.8/envs/dagster-3.6.8/bin/flake8"
      },
    },
    "debug": true,
    "lint_mode": "background"
}
```

Any clues?  Thanks in advance for any help!

**Comment by kaste** [comment]
Maybe, it isn't running at all.  If "debug" is on it should log a lot of stuff.  Check if you have SublimeLinter itself and here the adapter SublimeLinter-flake8 installed.  Maybe it appears to be installed but it is disabled.  (Then it is in the global Sublime Preferences under the key "ignored_packages".)

**Comment by sryza** [comment]
Thanks for your help @kaste .

I checked, and Package Control says I do have both SublimeLinter and SublimeLinter-flake8 installed.  Neither appear to be in my list of ignored_packages.

**Comment by kaste** [comment]
Then just post the debug from the start of Sublime.

**Comment by sryza** [comment]
It seems to be working now after restarting my machine twice! Sorry for the noise.

**Comment by kaste** [comment]
The trick is usually to restart *twice*. 😆
