### ISSUE TITLE
htmlhint report an error in php file

### ISSUE THREAD

**Issue by gitckh** [SublimeLinter/SublimeLinter#1773]
sorry for my poor English, i just have a question about using htmlhint.

it report an error when like  :
- 1:2  error  htmlhint:spec-char-escape  Special characters must be escaped : [ < ].
- 1:2  error  htmlhint:doctype-first     Doctype must be declared first.
- 1:9  error  htmlhint:spec-char-escape  Special characters must be escaped : [ > ].
if i remove the php tag, then the error will be disappeared.

i tried to search using google but i didn't find the solution.
![htmlhint_error](https://user-images.githubusercontent.com/71753213/93978755-07315880-fdaf-11ea-9215-0b23611dec14.png)

**Comment by gitckh** [comment]
Oh, i find a way to fix it in other post. [[here]](https://github.com/microsoft/vscode-htmlhint/issues/50)

>>Just go to package.json for htmlhint,
then add "/<\?(php|=)?(.+?)\?>/is" in the exclude.

but... is there any solution can fix this issue too?

**Comment by kaste** [comment]
I don't know "htmlhint" enough. (htmltidy is also a html linter. Maybe there are others.)

Now, if htmlhint doesn't check for correct open/close tags we could split the php file, removing the php parts.  That would be, in the settings set 

```
   "selector": "text.html - meta.embedded.line.php"
```

A maybe better way is to preprocess the file contents.  Basically porting https://github.com/AtomLinter/linter-htmlhint/pull/167  That must be done via a PR in the https://github.com/htmlhint/SublimeLinter-contrib-htmlhint repo!
