### ISSUE TITLE
SublimeLinter-contrib-codeclimate

### ISSUE THREAD

**Issue by meengit** [SublimeLinter/SublimeLinter#1778]
Hi!

On June 24, 2020, I filed a [pull request][1] making the Package [*Sublime​Linter-contrib-codeclimate*][2] compatible with SublimeLinter 4 (including several improvements). Since then, I've got no reaction from [*Codeclimate*][3].

The [existing Package at Package Control][7] is "only" compatible with *SublimeLinter 3*. I really like the services of *Codeclimate* and want to bring up my updated version of *Sublime​Linter-contrib-codeclimate*, compatible with *SublimeLinter 4*, to *Package Control*. I will do this with the intention, that it could help other developers as well.

As far as I can see, *Sublime​Linter-contrib-codeclimate* isn't maintained by the *SublimeLinter Team*. I would appreciate to see the *Sublime​Linter-contrib-codeclimate* package maintained by the *SublimeLinter Team*. So, I suggest:

* I do a fork of [my fork][4] of the *Sublime​Linter-contrib-codeclimate* package (to make further changes independent);
* I do a [PR as mentioned in the docs][5] to bring the package to the *Package Control* channel of SublimeLinter (with the new name SublimeLinter-codeclimate). As far as I can see, there should be no legal issues because [*Sublime​Linter-contrib-codeclimate* is under MIT license][6].

What do you guys think about that? Is this a viable way? I'm open for improvements (because this would be my first public SublimeLinter package).

Thank you very much for your response.

[1]:https://github.com/codeclimate/SublimeLinter-contrib-codeclimate/pull/3
[2]:https://github.com/codeclimate/SublimeLinter-contrib-codeclimate
[3]:https://codeclimate.com/
[4]:https://github.com/meengit/SublimeLinter-contrib-codeclimate
[5]:https://sublimelinter.readthedocs.io/en/latest/linter_plugin.html
[6]:https://github.com/codeclimate/SublimeLinter-contrib-codeclimate/blob/master/LICENSE
[7]:https://packagecontrol.io/packages/SublimeLinter-contrib-codeclimate

**Comment by braver** [comment]
Well if you intend to maintain the plugin, for as much as it needs maintaining at all of course, it looks pretty simple, you can just fork the existing package and open a pull request to replace the existing contrib entry with your repo. I have no clue as to what code climate is, so pulling it into the org doesn't make an enormous amount of sense: probably none of the core maintainers know how to make sure it works. And we can always do that later. For now, it's easier to just replace the existing one with yours.

**Comment by kaste** [comment]
I also made a review of your PR.

**Comment by meengit** [comment]
Thank you very much for your answer @braver and your review @kaste.

@braver, yes, of course. I will maintain this plugin as well as I can. 

> ...and open a pull request to replace the existing contrib entry with your repo.

I'm not sure if I understand the procedure correctly. I took a look into the [Package Control Docs (Submitting a Package)](https://packagecontrol.io/docs/submitting_a_package) and searched for *SublimeLinter-contrib-codeclimate* in the [package_control_channel repository](https://github.com/wbond/package_control_channel) but can't find such an entry. Am I in the right place?

@kaste, I updated the package based on your review. The [master of my fork](https://github.com/meengit/SublimeLinter-contrib-codeclimate) is now up to date with the [pull request](https://github.com/codeclimate/SublimeLinter-contrib-codeclimate/pull/3). Would you be able to do a second review?

**Comment by kaste** [comment]
We have our own package control channel https://github.com/SublimeLinter/package_control_channel 😁

**Comment by meengit** [comment]
I close this issue since my PR (https://github.com/SublimeLinter/package_control_channel/pull/102) to overtake the responsibility is ready to merge. Thank you very much for your awesome support @kaste and @braver.
