### ISSUE TITLE
SublimeLinter: WARNING: golangcilint cannot locate 'golangci-lint'

### ISSUE THREAD

**Issue by gregtczap** [SublimeLinter/SublimeLinter#1781]
**Issue Summary**

I am still getting the following error despite `golangci-lint` being correctly installed, in my `PATH`, and/or configured in `SublimeLinter` as [this page](http://www.sublimelinter.com/en/stable/troubleshooting.html#debugging-path-problems) suggests.

```
SublimeLinter: WARNING: golangcilint cannot locate 'golangci-lint'
```

**System Information**

* Pop!_OS 20.04 (Essentially Ubuntu 20.04)
* Sublime v3.2.2 (via flatpak)
* SublimeLinter v4.16.2 (via Package Control)
* SublimeLinter-golangcilint v2.0.0 (via Package Control)
* golangci-lint v1.37.0 (via [curl install script](https://golangci-lint.run/usage/install/#linux-and-windows))

**Additional info / what I've tried**

Other plugins (such as `Gofmt`) are able to read the path (and specifically anything in the go bin) just fine

`$ tail -n 3 ~/.profile`:

```sh
# golang
export GOPATH=$HOME/dev/go
export PATH=$PATH:/usr/local/go/bin:$GOPATH/bin
```

`$ which golangci-lint`:

```
/home/greg/dev/go/bin/golangci-lint
```

`$ /home/greg/dev/go/bin/golangci-lint --version`:

```
golangci-lint has version 1.37.0 built from 34e5fc63 on 2021-02-17T09:32:37Z
```

I have tried adding the PATH and the executable to the package config as well. Based on the [documentation](http://www.sublimelinter.com/en/stable/troubleshooting.html#debugging-path-problems) I do not understand the way I should be forming up the linter key/name, so I have tried each of the permutations below, and none of them have worked:

Version 1 (`golangcilint`):
```json
// SublimeLinter Settings - User
{
    "debug": true,
    "linters": {
      "golangcilint": {
          "env": {"PATH":"/home/greg/dev/go/bin"}
      }
    }
}
```

After restarting sublime, the `SublimeLinter: #1 util.py:161 PATH:` console output still does NOT contain the added `/home/greg/dev/go/bin`.

Version 2 (`golangci-lint`):
```json
// SublimeLinter Settings - User
{
    "debug": true,
    "linters": {
      "golangci-lint": {
          "env": {"PATH":"/home/greg/dev/go/bin"}
      }
    }
}
```

After restarting sublime, the `SublimeLinter: #1 util.py:161 PATH:` console output still does NOT contain the added `/home/greg/dev/go/bin`.

Version 3 (`SublimeLinter-golangcilint`):
```json
// SublimeLinter Settings - User
{
    "debug": true,
    "linters": {
      "SublimeLinter-golangcilint": {
          "env": {"PATH":"/home/greg/dev/go/bin"}
      }
    }
}
```

After restarting sublime, the `SublimeLinter: #1 util.py:161 PATH:` console output still does NOT contain the added `/home/greg/dev/go/bin`

Version 4
```json
// SublimeLinter Settings - User
{
    "debug": true,
    "paths": {
        "linux": [
            "/home/greg/dev/go/bin/golangci-lint"
        ]
    }
}
```

After restarting sublime, the `SublimeLinter: #1 util.py:161 PATH:` console output now DOES contain the added `/home/greg/dev/go/bin/golangci-lint`. However, I still get `SublimeLinter: #1 linter.py:837 WARNING: golangcilint cannot locate 'golangci-lint'` in the subsequent line!

**Comment by kaste** [comment]
Well, the link to `Gofmt` is very interesting.  They do something more we don't do here.  

1. So, what I think happens here is that the Sublime process has a different "ENV" than what you expect; basically it might differ from the Terminal process.  The simplest test for this is to close all Sublime, and then restart it *from* the terminal using *subl .* -- in  a terminal where everything is setup to work with go. 

2. The path settings here in SublimeLinter are a bit confusing.  We have the *deprecated* `paths` key which is global and used to complement basically `ENV['PATH']` when **searching** for executables.  (Basically to enhance a `which x` command.)  -- Then **during execution** we have the rather low-level `"env"` key *per linter* which is used to enhance the env the subprocess uses.  (For the latter, version 1 is correct; for the former version 4 is almost correct but should point to a directory.)  

Of course, if you setup all this you probably can just set `executable` (per linter) to exact (abs path) to your golangclilint executable/binary.


---

Now `Gofmt` would have the same problem but they use a dependency https://github.com/codexns/shellenv to get a better env to start with.  They use it in combination with a special https://github.com/golang/sublime-config package.  We tried something very similar in https://github.com/SublimeLinter/SublimeLinter/pull/1509

@braver From my perspective, PATH issues are the only recurring issues for SublimeLinter.  I don't wish we would have pulled #1509 back then, but do wonder why we don't know anything about `shellenv` which is even written by @\wbond.  Why isn't this built into Sublime yet?  Why we had an issue against Sublime which got closed as implemented although Sublime does **not** use the method from `shellenv` or my #1509?  (Basically admitting, we want an *interactive* shell https://github.com/codexns/shellenv/blob/63ec866929f064c4716d06e9195ba51ef92381cc/all/shellenv/_posix.py#L49-L53 for user convenience.)

**Comment by braver** [comment]
Pfff, I can't really find all the upstream issues related to env that we've had to deal with. We had issues with shells taking forever to report the env to ST and this was mostly solved upstream. 

The other thing is env mis-match. This is not a problem in "static" situations. It's of course impossible for the ST process always match the shell, it's not a shell program. But opening ST from the shell is a workaround. 

[shellenv](https://github.com/codexns/shellenv) doesn't sound familiar to me. It's never mentioned in the [ST issue tracker](https://github.com/sublimehq/sublime_text). As for why it isn't built in, I can only guess. Matching the env isn't a primary goal, at least beyond what's already there? If something can be handled by a package, they tend to not want to take over that duty. Especially if there are caveats, ie. it cannot be made bulletproof easily. But it's weird, I know that LSP had mostly the same problems we had, and they take basically our route, and no talk of shellenv there. Also, shellenv is written for ST2, I don't even know how current the solutions are there, or if ST4 solves this in some way. 
By the way, there is a new formatter package that can also replace GoFMT, and it doesn't have any dependencies: https://github.com/mitranim/sublime-fmt. 

... so to conclude:
> but do wonder why we don't know anything about shellenv 

...nobody seems to be using it?

**Comment by kaste** [comment]
Since we already have the explicit `get_environment()` method per linter instance, I think I'll take a stab at it.  Also it's sound still useful and interesting (t.i.: not boring) implementation wise.  

A short chat with the nvm maintainer showed that we must read in the env as a login shell per working dir, t.i. not *once* globally, because there could be marker files (like `.nvmrc`) somewhere going upwards the path which influence the shell initialization.

**Comment by kaste** [comment]
Closing, follow up in #1795
