### ISSUE TITLE
Does not highlight errors at EOF position

### ISSUE THREAD

**Issue by pierresh** [SublimeLinter/SublimeLinter#1784]
Hello,

It seems that this error is not displayed by SublimeLinter-php (there are 2 opening curly brackets) if there are empty lines below the closing } , while it would be shown in the console:

```php
<?php

if (!$query->execute()) {{
	$a = 1;
}


```
<img width="815" alt="WechatIMG1412" src="https://user-images.githubusercontent.com/7520095/109166519-c0a9b500-77b7-11eb-8cc8-bbc7ad700b9c.png">

If you remove the empty lines, it would be then properly displayed in Sublime text.

<img width="774" alt="WechatIMG1413" src="https://user-images.githubusercontent.com/7520095/109166542-c7382c80-77b7-11eb-982e-aadcf4c64437.png">

**Comment by kaste** [comment]
That's indeed a bug for exactly this edge case.

Given the source code 

```
<?php

if (!$query->execute()) {{
  $a = 1;
}

```

we have 

```
>>> view.size()
47
```

Now, `view.add_regions("testss", [sublime.Region(47, 48)], "string", "dot")` (what we actually do here) does not produce a squiggle nor an icon.  

`view.add_regions("testss", [sublime.Region(47, 47)], "string", "dot")` produces just the dot icon
![image](https://user-images.githubusercontent.com/8558/109966093-2504d100-7cf0-11eb-8127-b3b4349a13d7.png)

The correct way probably is `view.add_regions("testss", [sublime.Region(47, 47)], "string", "dot", flags=sublime.DRAW_EMPTY_AS_OVERWRITE)` which looks like

![image](https://user-images.githubusercontent.com/8558/109968283-c9881280-7cf2-11eb-912d-09cdc2ae786c.png)

Normally we explicitly forbid zero length regions.  And we don't set `sublime.DRAW_EMPTY_AS_OVERWRITE` as a consequence.  Further more we take empty (zero length) regions as a marker for zombie squiggles/dangles we can or rather MUST remove.  

We can probably make an explicit marker as well as the only edge case we have to solve here is exactly to squiggle the EOF.  T.i. we still don't have to allow empty regions in arbitrary positions but just at EOF.

**Comment by kaste** [comment]
@braver You can see all the variants in this thread here.  The current behavior in OPs first picture.  My proposal is to implement the second screenshot in my reply above. 

As this is not a one-liner to implement, we should be sure of how we may proceed.

**Comment by braver** [comment]
Ah, yes, looks like we need special handling at EOF. That second screenshot seems preferable, ie. we should try to have all applicable highlights and not just the gutter mark or the underline/outline.
