### ISSUE TITLE
I had no clue how to find linters or that i needed linters based on the docs.

### ISSUE THREAD

**Issue by aiqc** [SublimeLinter/SublimeLinter#1788]
I did not know where to look for linters. I thought SublimeLinter was doing all of the linting itself. 

This is not clear when reading the docs. It should say something like you need to install language specific linter plugins which can be found by doing _
http://www.sublimelinter.com/en/stable/installation.html

Only by accident did I stumble upon the linters when typing in the command palette: "SublimeLinter-" I've been running around scouring docs and posting on forums and looking at path haha

**Comment by kaste** [comment]
Well, the docs on sublimelinter.com are too short.  The README here is better than what we have over there.

**Comment by braver** [comment]
Exactly. In their current state though, the README _and_ the install message are pretty clear. It was already pretty clearly stated that the core package does not include linters. So, sure, anyone can miss that and say "I thought SublimeLinter was doing all of the linting itself", but really, I think we're doing all we reasonably can here. Better ideas are welcome of course, contributions to the docs even more so 😉
