### ISSUE TITLE
Sublime Linter No Longer Installs

### ISSUE THREAD

**Issue by bqi343** [SublimeLinter/SublimeLinter#1789]
I've been using sublime linter for a while now. Today I tried reinstalling it via package control but it didn't work. Got the following in the console:

```
ignored packages updated to: ["SublimeLinter", "Vintage"]
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
Package Control: The dependency 'jsonschema' is not currently installed; installing...
Package Control: The dependency 'jsonschema' is not available
Package Control: The dependency 'jsonschema' could not be installed or updated
```

macOS Big Sur 11.3
Sublime Text Version 3.2.2, Build 3211

Seems related to https://github.com/wbond/package_control/issues/1402 (though `curl --version` gives 7.64.1) or https://github.com/wbond/package_control/issues/1564. Just wondering if anything could be done about this?

**Comment by bqi343** [comment]
Can I install sublimelinter + sublime-linter-gcc without package control? I tried unzipping `SublimeLinter` and `SublimeLinter-gcc` in the Packages folder as suggested [here](https://stackoverflow.com/questions/31945735/how-to-install-sublime-package-without-package-control) but it doesn't seem to be working. Any guidance would be appreciated. :)

**Comment by kaste** [comment]
Yeah, I prefer "git cloning" as follows: 

1. Open the Packages folder.  (`Preferences -> Browse Packages` from the menu)
2. Here, open up a terminal.  First, `git clone https://github.com/SublimeLinter/SublimeLinter.git`, then `git clone https://github.com/kylebebak/sublime-jsonschema.git jsonschema`.
3. Finalize the dependency with `Package Control: Install Local Dependency`

Probably have the Sublime console open to see if it requires restarts.

**Comment by dongliu0426** [comment]
> Yeah, I prefer "git cloning" as follows:
> 
> 1. Open the Packages folder.  (`Preferences -> Browse Packages` from the menu)
> 2. Here, open up a terminal.  First, `git clone https://github.com/SublimeLinter/SublimeLinter.git`, then `git clone https://github.com/kylebebak/sublime-jsonschema.git jsonschema`.
> 3. Finalize the dependency with `Package Control: Install Local Dependency`
> 
> Probably have the Sublime console open to see if it requires restarts.

This worked for me. Thanks!

**Comment by bqi343** [comment]
yeah I got this

```
using gpu buffer for window
unloading plugin SublimeLinter-gcc.linter
ignored packages updated to: ["SublimeLinter-gcc", "Vintage"]
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
reloading settings Packages/User/Package Control.sublime-settings
ignored packages updated to: ["Vintage"]
reloading plugin SublimeLinter-gcc.linter
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 125, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1199, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/benq/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter-gcc.sublime-package/linter.py", line 11, in <module>
  File "/Users/benq/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/__init__.py", line 6, in <module>
    from . import (
  File "/Users/benq/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/linter.py", line 15, in <module>
    from . import persist, util
  File "/Users/benq/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/persist.py", line 6, in <module>
    from .settings import Settings
  File "/Users/benq/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/settings.py", line 4, in <module>
    from . import events, util
ImportError: cannot import name events
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
```

in the console when I followed the steps, but using PackageControl to install SublimeLinter instead of `git clone https://github.com/SublimeLinter/SublimeLinter.git` worked

**Comment by kaste** [comment]
Closing as solved
