### ISSUE TITLE
Advice on linters with json output

### ISSUE THREAD

**Issue by bcomnes** [SublimeLinter/SublimeLinter#1791]
I'm investigating implementing a plugin for [Deno lint](https://deno.land/manual@v1.10.1/tools/linter).

Unfortunately its linter output is multiline, which is nice for humans, but a bit more complex for regex.  

It also supports a `--json` flag which would make it a lot easier parse output, but doesn't follow the regex pattern expected by SublimeLinter. 

I'm curious what people think would be the best approach in this situation.  

Would it be easier to attempt the multiline regex approach? Or perhaps implement my own Linter subclass that can handle json parsing and passing those results on.  

Some example output from the linter:

```terminal
?1 deno-tool-installer % deno lint
(no-unused-vars) `a` is never used
var a = foo.bar
    ^
    at /Users/bret/Developer/deno-tool-installer/mod.ts:1:4

    hint: If this is intentional, prefix it with an underscore like `_a`

(no-unused-vars) `b` is never used
var b = biz.baz
    ^
    at /Users/bret/Developer/deno-tool-installer/mod.ts:3:4

    hint: If this is intentional, prefix it with an underscore like `_b`

Found 2 problems
Checked 1 file
?1 deno-tool-installer % deno lint --json
{
  "diagnostics": [
    {
      "range": {
        "start": {
          "line": 1,
          "col": 4,
          "bytePos": 4
        },
        "end": {
          "line": 1,
          "col": 5,
          "bytePos": 5
        }
      },
      "filename": "/Users/bret/Developer/deno-tool-installer/mod.ts",
      "message": "`a` is never used",
      "code": "no-unused-vars",
      "hint": "If this is intentional, prefix it with an underscore like `_a`"
    },
    {
      "range": {
        "start": {
          "line": 3,
          "col": 4,
          "bytePos": 21
        },
        "end": {
          "line": 3,
          "col": 5,
          "bytePos": 22
        }
      },
      "filename": "/Users/bret/Developer/deno-tool-installer/mod.ts",
      "message": "`b` is never used",
      "code": "no-unused-vars",
      "hint": "If this is intentional, prefix it with an underscore like `_b`"
    }
  ],
  "errors": []
}
?1 deno-tool-installer %
```

**Comment by braver** [comment]
Regexes are to be avoided, if the linter can output a data format I would always choose that. Maybe if the linter has an output mode specifically meant for parsing with a simple regex (e.g. one line per error, “path:line:col message”) that would be even easier. But don’t try to parse a “pretty” output format like this one. We should have a few examples out there that have their own json based reporting.

**Comment by kaste** [comment]
regexes are recommended for parsable, one line per error output formats.  For your case JSON is recommended.  You have to implement `find_errors` for that, like so:


```
from SublimeLinter.lint import LintMatch
import json
import logging

logger = logging.getLogger('SublimeLinter.plugin.deno')  # <= use correct name of the linter


class ...
    ...
    def find_errors(self, output):
        """Parse errors from linter's output."""
        try:
            content = json.loads(output)
        except ValueError:
            logger.error(
                "JSON Decode error: We expected JSON from 'deno', "
                "but instead got this:\n{}\n\n"
                .format(output)
            )
            self.notify_failure()
            return

        for error in content['diagnostics']:
            yield LintMatch(
                match=error,
				filename=error['filename'],
                line=error['range']['start']['line'] - 1,  # apply line_col_base manually
                col=error['range']['start']['col'] - 1,
                message=error['message'],  # maybe `+ '. ' + error['hint']`
                error_type='error',   #  does 'deno' have different error types like 'warning'?
                code=error['code'],  # aka the rule name
            )
```

**Comment by bcomnes** [comment]
> if the linter can output a data format I would always choose that. 

Agreed.

>  For your case JSON is recommended. You have to implement find_errors for that, like so: 

Thank you! Before I close this out, do you know of any fully implemented sublime linter classes that implement a similar strategy for further reference?

**Comment by kaste** [comment]
I usually look at eslint https://github.com/SublimeLinter/SublimeLinter-eslint/blob/master/linter.py
