### ISSUE TITLE
Output console line break

### ISSUE THREAD

**Issue by prabh1601** [SublimeLinter/SublimeLinter#1798]
![Screenshot-20210521123210-1915x280](https://user-images.githubusercontent.com/56677063/119096146-d7ffe380-ba30-11eb-8a8e-e9955326c0d6.png)
 
Sorry, for a weird title to the issue, but I dont get why the error console is not using whole line and break at half and starts the newline with the remaining content of the error.(To be precise, see that 'into' in third warning shifts to newline instead of continuing in the same line).  I have tried to search on google for a solution but cant find one.

**Comment by kaste** [comment]
And what was the solution?

**Comment by prabh1601** [comment]
I dont know what was the issue, but changing the font to default fixed it magically on its own. Seems like its some issue with the font. I have tried many fonts and the issue is not there only when the default font it not used.

**Comment by kaste** [comment]
Ah yes, looking at the pic again you're not using a monospaced font, and the line breaking/wrapping we have here only works with monospaced fonts.
