### ISSUE TITLE
mark styles are not clearly visible specially 'squiggly_underline' in previous versions they are working fine

### ISSUE THREAD

**Issue by ShubhamDogra112** [SublimeLinter/SublimeLinter#1812]
![capture](https://user-images.githubusercontent.com/43871644/120095255-a1b61880-c142-11eb-9e13-ce83b8dd4df2.PNG)

**Comment by kaste** [comment]
Looking at your pic, that's a render bug.  It's not even a squiggle.  From my perspective that must be a core (rendering) bug.

**Comment by ShubhamDogra112** [comment]
I think you are right. This issue starts after updated to sublime text 4

**Comment by kaste** [comment]
This is now at https://github.com/sublimehq/sublime_text/issues/4378
