### ISSUE TITLE
[Feature Request] : Add option to show error messages in the same line they occur in.

### ISSUE THREAD

**Issue by arshappleid** [SublimeLinter/SublimeLinter#1813]
1. Add option to show error messages in the same line they occur in.
2. Option to highlight the entire line that has the error. Sometimes small highlights cannot be seen.

**Comment by braver** [comment]
Thank you for the requests.

1. The reason not to is that multiple errors can occur on the same line. Hence the marker in the gutter and a popup with all the info. 
2. Same reason and same solution. The gutter markers tend to jump out quite a bit (and you can select more visually invasive options even).

**Comment by kaste** [comment]
This has been implemented and ships right now.
