### ISSUE TITLE
[WinError 267] The directory name is invalid

### ISSUE THREAD

**Issue by deltafactory** [SublimeLinter/SublimeLinter#1820]
SublimeText 4107
SublimeLinter 4.17.0
SublimeLinter-php 1.3.1
Windows 10

Today I am starting to see messages like the following
```
SublimeLinter: #8 php PHPMail.php ERROR:
========================================

  Execution failed

  [WinError 267] The directory name is invalid

  C:\Users\XXXXXXXXREDACTEDXXXXXXXXXX  (working dir)
  > type ..\..\..\..\web\wp-content\plugins\mailpoet\lib\Mailer\Methods\PHPMail.php | "C:\Program Files\PHP\php.EXE" -l -n -d display_errors=On -d log_errors=Off
```

The biggest change to my environment was the upgrade of SublimeText. Linting still works as expected on some files but not others.

**Comment by deltafactory** [comment]
Quick follow-up: I'm wondering if the SublimeLinter-php package is problematic/deprecated and replacing it with SublimeLinter-phpcs would solve the issue.

**Comment by kaste** [comment]
Hm.  Did you set the `working_dir` manually?  Must think about all the dots here: `> type ..\..\..\..\`?

**Comment by deltafactory** [comment]
I believe the working_dir is set as the root of the first project folder. The file in question was outside of that path. Is there some security sandbox disallowing traversal to a parent dir? The ..\ are valid though do they need additional escaping as backslashes? I'm wondering if this is perhaps a ST4 or python error issue.

**Comment by kaste** [comment]
> The file in question was outside of that path. Is there some security sandbox disallowing traversal to a parent dir?

Not on our side, maybe on your side?

> The ..\ are valid though do they need additional escaping as backslashes?

They don't need more escaping as there are formatted for the end-user here.


Maybe just try it on the CLI.  Go to the working dir (you redacted), and try the command.

**Comment by deltafactory** [comment]
Not able to reproduce it today. Possibly a temporary read access issue. I'll reopen if I find something more conclusive. Thanks.
