### ISSUE TITLE
Double Clicking on Error Opens Duplicate Tab

### ISSUE THREAD

**Issue by JoshMayberry** [SublimeLinter/SublimeLinter#1821]
I just upgraded Sublime Text to build 4107, and now SublimeLinter is acting strange.

Before, when I would double click on an error in the popup window, it would navigate to where that error is in the current tab.
Now, a new tab is opened which has the error.

![image](https://user-images.githubusercontent.com/11482252/121914653-76195d80-cd00-11eb-8c85-d496678e2bc9.png)
![image](https://user-images.githubusercontent.com/11482252/121914542-5c781600-cd00-11eb-99d9-f57a43467a31.png)

In case it helps, here is what the [ctrl+`] window shows:
```
SublimeLinter: linter.py:1127         jshint: Checking lint mode 'load_save' vs lint reason 'on_user_request'.  Ok.
SublimeLinter: linter.py:1127         jshint: Checking lint mode 'load_save' vs lint reason 'on_user_request'.  Ok.
SublimeLinter: sublime_linter.py:345  Delay linting 'jquery-ui-dmte.js' for 0.0s
SublimeLinter: linter.py:1127         jshint: Checking lint mode 'load_save' vs lint reason 'on_user_request'.  Ok.
SublimeLinter: #7 linter.py:1144      jshint: linting 'jquery-ui-dmte.js'
SublimeLinter: #7 node_linter.py:83   Searching executable for 'jshint' starting at '\\dmte8\dev\wwwroot\.node\.lib\jquery-ui'.
SublimeLinter: #7 linter.py:1699      Running ...

  \\dmte8\dev\wwwroot\.node\.lib\jquery-ui  (working dir)
  > type jquery-ui-dmte.js | C:\Users\jmayberry\AppData\Roaming\npm\jshint.CMD --verbose --filename \\dmte8\dev\wwwroot\.node\.lib\jquery-ui\jquery-ui-dmte.js -

SublimeLinter: #7 linter.py:808       WARNING: jshint output:
'\\dmte8\dev\wwwroot\.node\.lib\jquery-ui'
CMD.EXE was started with the above path as the current directory.
UNC paths are not supported.  Defaulting to Windows directory.

SublimeLinter: #7 linter.py:810       Note: above warning will become an error in the future. Implement `on_stderr` if you think this is wrong.
SublimeLinter: #7 linter.py:1226      jshint: output:
  \\dmte8\dev\wwwroot\.node\.lib\jquery-ui\jquery-ui-dmte.js: line 5189, col 18, Missing semicolon. (W033)

  1 error
SublimeLinter: #7 linter.py:1278      jshint: No match for line: ''
SublimeLinter: #7 linter.py:1278      jshint: No match for line: '1 error'
SublimeLinter: sublime_linter.py:593  Linting 'jquery-ui-dmte.js' took 4.96s
```

**Comment by kaste** [comment]
If I look at the pic, the path starts with `?dmte8` in the second.  

That will be a bit rough to debug.  

Open the console, and switch it to python 3.3,  ![image](https://user-images.githubusercontent.com/8558/121917719-af1ff500-cd35-11eb-8d6b-a4ec799952f0.png)

Here try:

```
from SublimeLinter import panel_view as pv
errs = pv.get_window_errors(window, pv.persist.file_errors)
_, base_dir = pv.create_path_dict(tuple(errs.keys()))
base_dir
```

The last `base_dir` should print an absolute, "common" path.  In this case with 4 leading `\` I think.  (Because you have two `\`, and each one must be escaped by another one.)

**Comment by JoshMayberry** [comment]
I had not noticed the extra question mark. Good catch.

I switched the output to Python 3.3 and `base_dir` returned `'\\\\dmte8\\dev\\wwwroot\\.node\\.lib\\jquery-ui'`.
`errs` returned `{'\\\\dmte8\\dev\\wwwroot\\.node\\.lib\\jquery-ui\\jquery-ui-dmte.js': [{'code': 'W033', 'region': (422, 423), 'line': 16, 'panel_line': (1, 1), 'error_type': 'warning', 'msg': 'Missing semicolon.', 'start': 3, 'linter': 'jshint', 'filename': '\\\\dmte8\\dev\\wwwroot\\.node\\.lib\\jquery-ui\\jquery-ui-dmte.js', 'priority': 1, 'offending_text': '\n', 'uid': '97767c1cb7db196a6e38ce8e5079df75c313a9a7dc4d7010b322295d4587907d'}]}`

**Comment by kaste** [comment]
So that means we correctly accept the double slash.  Very possible then that ST replaces it with the question mark.  But why?  Are you sure the same project worked on the previous ST?

Thinking about how we could make a reduced test case to open an issue upstream.

**Comment by kaste** [comment]
A workaround could be to map for example dev to a simple drive letter and work from there.

**Comment by JoshMayberry** [comment]
Other files were working as expected.
I tried renaming the file to something else and it worked. I renamed it back to what it was- and it is still working.

O_o

I'm sorry to have bothered you with this. I do not know what is going on.

**Comment by kaste** [comment]
🤷‍♀️
