### ISSUE TITLE
package control refuses to install SublimeLinter

### ISSUE THREAD

**Issue by riverbasin** [SublimeLinter/SublimeLinter#1824]
Greetings.  I recently re-installed SublimeText 4 on Mac OS X Catalina.  This was a clean install, with all remnants of SublimeText removed. Firstly, package control:install package cannot seem to find SublimeLinter.  When I the add the Git repository, package control:install package seems to begin the install, but then quits abruptly.  Not sure if this is on my end or yours, but I thought I would report it.

Thanks.

**Comment by pynem** [comment]
In addition to @riverbasin's report, it seems that SublimeLinter (and many of the plugins) aren't displayed when searching on packagecontrol.io.

**Comment by dorbitbrown** [comment]
...and, there seems to be no manual installation option.

**Comment by jariztia** [comment]
Hey @riverbasin how did you do that?
> When I the add the Git repository, package control:install package seems to begin the install

**Comment by riverbasin** [comment]
I'm on a 2012 Intel processor, so M1 is not the issue.  Besides I had it installed previously and it worked fine. Presently, when try to install, it appears to begin installing and then aborts with no output.  This may be a larger issue than SublimeLinter, because I'm finding that other plugins won't install either with similar behavior. And as @pynem mentioned, it looks like some packages are not showing up when searching package.io from SublimeText.  I can't seem locate a place to report issues for package control, however.

**Comment by badcc** [comment]
This is inconvenient, hopefully resolved soon!

[SublimeLinter](https://packagecontrol.io/packages/SublimeLinter) on packagecontrol.io says "removed" and viewing [the author](https://packagecontrol.io/browse/authors/SublimeLinter) it looks like all the packages are now labeled as "NEEDS REVIEW"

![image](https://user-images.githubusercontent.com/990820/129285103-ca7f30e3-cfaa-4ec8-871e-e427e9e09e06.png)

Installs seem to be near zero for the day as well, relative to others.
![image](https://user-images.githubusercontent.com/990820/129285162-ef9550ef-1e5b-4841-af11-c73759bc8956.png)

**Comment by pynem** [comment]
SublimeLinter and linters seems to be back to life this morning: 

![github-sublimelinter](https://user-images.githubusercontent.com/88372122/129326886-09eee032-a5d9-4a7f-8b76-36d6da05051f.png)

I was able to install the linter I was after yesterday, and there are plenty of other linter packages listed when I use the 'Install Package' command in the editor.

**Comment by eivl** [comment]
I'm also not able to install `SublimeLinter` I just did this on a different machine a few days ago.

```
ignored packages updated to: ["SublimeLinter", "Vintage"]
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
Package Control: The dependency 'jsonschema' is not currently installed; installing...
Package Control: The dependency 'jsonschema' is not available
Package Control: The dependency 'jsonschema' could not be installed or updated
ignored packages updated to: ["Vintage"]
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
```

For anyone interested, this is my output when i try to install from package control.
