### ISSUE TITLE
Is it possible to override just cmd in settings, instead of using executable, for NodeLinter?

### ISSUE THREAD

**Issue by jo-sm** [SublimeLinter/SublimeLinter#1825]
I maintain a version of Stylelint called [`stylelint_d`](https://github.com/jo-sm/stylelint_d) which can be used as a drop-in replacement, and I'm planning to add some instructions on how to override `SublimeLinter-stylelint` so that it uses `stylelint_d` instead. My idea is that I can provide users with a simple instruction like, "Set `"SublimeLinter.linters.stylelint.cmd": "stylelint_d"` in your settings".

After some research, specifically looking at the docs and into the code of `NodeLinter` and the base `Linter` class, I haven't found a way to do it, because it looks like `NodeLinter`/`Linter` treat the package defined `cmd` and the settings defined `executable` differently. With `cmd` it will automatically find the appropriate package binary from `.node_modules/bin` directories going upwards from the current file, but with `executable` it will just directly try to call it (and make sure it exists using `which <executable>`). I can't seem to find a way to override this and achieve what I want, so as far as I can tell my two options are the following:

1. Use the absolute path for `stylelint_d`. 
2. Install it globally.

Both of these options work but are really not ideal because almost all users install using `npm i --save-dev`. 

Is there a way with the current `SublimeLinter` package to override just `cmd` so that I can use the internal node module resolution of `NodeLinter`, instead of setting `executable`?

**Comment by braver** [comment]
Not necesarrily, unless the linter plugin provides a setting for it there is no way to override those properties of a plugin from the settings. I'm also not really sure what the value of this would be over creating a fork and a specific plugin for stylelint_d? It's not like it's a whole lot of code.

**Comment by jo-sm** [comment]
@braver so the difference between `executable` and `cmd` is intentional in this case?

**Comment by braver** [comment]
Yes, the executable setting is there to entirely bypass any “smart” ways executables are found and simply point to one. It’s not intended for making a plug-in use an alternative executable. If that’s what you want there is hardly any “cost” in maintenance or setup to simply fork that plug-in. In fact I’d argue that it makes the plug-in vs executable relation clearer and prevents problems for users later on.

**Comment by kaste** [comment]
As there are only eslint_d and now stylelint_d a generalized solution is overkill atm but a niche solution would be great.  (There is also an issue in the eslint and eslint_d repo already so there is *some* user interest.) The main disadvantage of having two plugins is that you only want to run one of them, preferable the `_d` variant if available.  

eslint_d recommends a global install and manages multiple instances per working dir or project.  It also supports a local install of course.  Can we assume that when we find a stylelint or eslint installation, the `_d` variant *must* be on the same level **if** locally installed?  

Can we have a simple solution where we search for stylelint or eslint just like we do right now and on success first look for a `_d` installation on the same level (t.i. in the same `node_modules` folder or declared in the same `package.json` manifest) and for a global installation after that?

**Comment by jo-sm** [comment]
@kaste 

> eslint_d recommends a global install and manages multiple instances per working dir or project. It also supports a local install of course. Can we assume that when we find a stylelint or eslint installation, the `_d` variant _must_ be on the same level **if** locally installed?

I think it's a safe assumption that if there is a local installation of `stylelint` and `stylelint_d`, that it's okay to prefer the `_d` version (and same for the `eslint` ones). `stylelint_d` defers to the user's version of `stylelint` so it's likely that they would both be there, and that the user would prefer to use the `_d` version. 

> Can we have a simple solution where we search for stylelint or eslint just like we do right now and on success first look for a `_d` installation on the same level (t.i. in the same `node_modules` folder or declared in the same `package.json` manifest) and for a global installation after that?

If it's okay to have a niche solution this makes sense, in my opinion. It didn't really cross my mind initially since I felt a generalized solution is more appropriate but if it's okay to do this in the `eslint` and `stylelint` plugin code I think it's a good alternative (and has the benefit of requiring no user configuration in their settings).

**Comment by kaste** [comment]
I made a PR to use `eslint_d` automatically at https://github.com/SublimeLinter/SublimeLinter-eslint/pull/318

Should be the exact same code for `stylelint_d`.
