### ISSUE TITLE
Per-project `disable` setting is being ignored

### ISSUE THREAD

**Issue by ihatemornings** [SublimeLinter/SublimeLinter#1842]
I’m having trouble getting SublimeLinter to disable the `rubocop` linter for a particular project. I’m trying to do it using the .sublime-project file, which seems to work for other settings, but enable/disable is ignored.

My .sublime-project file looks like this:
```json
{
    "settings": {
        "SublimeLinter.linters.rubocop.env": {"RBENV_VERSION": "2.6.8"},
        "SublimeLinter.linters.rubocop.disable": true
    }
}
```

I have removed all SublimeLinter settings from Preferences.sublime-settings and my SublimeLinter.sublime-settings file looks like this (I removed all `linters` settings to isolate the issue):
```json
{
    "debug": true,
    "linters": {},
    "no_column_highlights_line": true,
    "paths": {
        "linux": [],
        "osx": [
            "~/.rbenv/shims",
            "/usr/local/bin"
        ],
        "windows": []
    }
}
```

The `env` value is correctly picked up from the .sublime-project file (and if I change it the setting changes accordingly), but the `disable` value is ignored (it remains `False` no matter what I set it to in the .sublime-project file). Here’s the console:
```python
>>> settings.get("SublimeLinter.linters.rubocop.env")
{'RBENV_VERSION': '2.6.8'}
>>> settings.get("SublimeLinter.linters.rubocop.disable")
False
```

How do I get that `False` to be `True` with a per-project setting? Am I missing a better way of achieving my goal?

**Comment by kaste** [comment]
It could be that you have syntax specific overrides here, or even global overrides in "Preferences.sublime-settings".  Also possible that you're actually loaded a different project file than you're editing of course.    

If you ask `settings.get("SublimeLinter.linters.rubocop.env")` does the return value change when you change the project file?

**Comment by ihatemornings** [comment]
> If you ask settings.get("SublimeLinter.linters.rubocop.env") does the return value change when you change the project file?

It does! That’s what was really confusing me – the `env` setting was working and the `disable` setting wasn’t.

But in fact, having cleared out all the settings I could find and carefully putting them back in, testing along the way, I’ve ended up with everything working as expected. It’s annoying that I don’t know what the problem was (so I could share it in case anyone else runs into it) but at least I’m back in business.

@kaste Thanks for your help!
