### ISSUE TITLE
Linter Reported Errors Coming From <stdin> No Such File or Directory

### ISSUE THREAD

**Issue by utkonos** [SublimeLinter/SublimeLinter#1847]
I'm using SublimeLinter with SublimeLinter-pyflakes. I hope this is the correct place to report and not SublimeLinter-pyflakes.

I am getting an error and a warning about a file not found. These repeat over and over in the console.

```
SublimeLinter: WARNING: pyflakes reported errors coming from '/Users/username/Desktop/project/<stdin>:217'. However, reading that file raised:
  [Errno 2] No such file or directory: '/Users/username/Desktop/project/<stdin>:217'.
[2022-05-14 23:52:18,819 - WARNING  - SublimeLinter.plugin.pyflakes] pyflakes reported errors coming from '/Users/username/Desktop/project/<stdin>:217'. However, reading that file raised:
  [Errno 2] No such file or directory: '/Users/username/Desktop/project/<stdin>:217'.
```

**Comment by kaste** [comment]
Which version of pyflakes is that?

**Comment by utkonos** [comment]
```
% pyflakes -V
2.4.0 Python 3.10.4 on Darwin
```

**Comment by kaste** [comment]
So we basically use the same version, though on a different platform.  That escalated quickly.

Can you check what the actual output from pyflakes is?  First on the command line probably:  `cat some_file.py | pyflakes` should be the command if I recall correctly.    Then within SublimeLinter:  enable "debug" in the settings, then open Sublime's console `View > Show Console`, trigger the linter by typing something, and see the command `Running...` and its output logged to the console.

**Comment by utkonos** [comment]
Ok. The problem is now visible. I have added some junk to my Python file to force the linter to trigger and to produce an error. I mashed the keyboard at the end of line 34.

```
SublimeLinter: #8 linter.py:1226      pyflakes: output:
  <stdin>:34:45: invalid syntax
      client_privkey, client_pubkey = _wgkey()dfg
                                              ^
[2022-05-15 16:41:50,083 - INFO     - SublimeLinter.plugin.pyflakes] pyflakes: output:
  <stdin>:34:45: invalid syntax
      client_privkey, client_pubkey = _wgkey()dfg
                                              ^
SublimeLinter: #8 linter.py:1355      WARNING: pyflakes reported errors coming from '/Users/username/Desktop/project/<stdin>:34'. However, reading that file raised:
  [Errno 2] No such file or directory: '/Users/username/Desktop/project/<stdin>:34'.
[2022-05-15 16:41:50,085 - WARNING  - SublimeLinter.plugin.pyflakes] pyflakes reported errors coming from '/Users/username/Desktop/project/<stdin>:34'. However, reading that file raised:
  [Errno 2] No such file or directory: '/Users/username/Desktop/project/<stdin>:34'.
SublimeLinter: sublime_linter.py:593  Linting 'core.py' took 0.32s
[2022-05-15 16:41:50,088 - INFO     - SublimeLinter.sublime_linter] Linting 'core.py' took 0.32s
```

Then this is what the command line shows using `cat core.py | pyflakes`:

```
<stdin>:34:45: invalid syntax
    client_privkey, client_pubkey = _wgkey()dfg
```

**Comment by kaste** [comment]
Okay that#s a bit of a joke

I get for example:

```
<stdin>:1044:12 undefined name 'settingss'
```
and you 
```
<stdin>:34:45: invalid syntax
```
Spot the difference?  There is an additional `:` after the column.

**Comment by utkonos** [comment]
Oh my. Good eye. So, the macOS build of pyflakes behaves differently than the Windows?

**Comment by utkonos** [comment]
Forgive me, but I do see that this ended up in the wrong bucket: SublimeLinter proper rather than SublimeLinter-pyflakes. Also, it looks like this exact problem or a very similar one is already in a PR and in process:

https://github.com/SublimeLinter/SublimeLinter-pyflakes/pull/17

**Comment by kaste** [comment]
Yeah I completely forgot about https://github.com/SublimeLinter/SublimeLinter-pyflakes/pull/17  🙄. Just released the fix.

**Comment by kaste** [comment]
It is *not* a difference between different platforms.  Syntax errors are handled ("reported") here: https://github.com/PyCQA/pyflakes/blob/2409df015d9d847890716b242cb418047cd9d6b7/pyflakes/reporter.py#L58  and typical messages are formatted like this: https://github.com/PyCQA/pyflakes/blob/2409df015d9d847890716b242cb418047cd9d6b7/pyflakes/messages.py#L16

**Comment by utkonos** [comment]
Does this change get pushed to Package Control automagically?

**Comment by kaste** [comment]
Yes, usually within 1 hour.  But locally, your computer asks Package Control only once when Sublime Text starts.
