### ISSUE TITLE
No linting after latest release

### ISSUE THREAD

**Issue by pags** [SublimeLinter/SublimeLinter#1877]
Release notes mention global on/off switch. Does it now default to "off"? Where is the switch located?

**Comment by kaste** [comment]
Haha.  No it's not off by default.  More likely the download or installation of the new version failed.  Usually View > Show Console has more information.  Maybe just a restart of Sublime Text?

**Comment by pags** [comment]
Wasn't getting any console errors, then reinstalled and now getting "ImportError: cannot import name IS_ENABLED_SWITCH"

**Comment by kaste** [comment]
Did you restart yet?

**Comment by pags** [comment]
Works after restart! Thanks for maintaining such a great plugin.

**Comment by kaste** [comment]
🙏 🙇
