### ISSUE TITLE
[REQUEST] Changing lint scale/size

### ISSUE THREAD

**Issue by notBradPitt** [SublimeLinter/SublimeLinter#1888]
Would be nice to have an option to change the scale since the current one can get too close with the line number and there's no option to change gutter width

**Comment by kaste** [comment]
Don't know what you mean, honestly.  The icons on the left of the line numbers getting too big?  If that's the case, I don't know any way to do this except resizing the icons itself and making a new icon set.

**Comment by notBradPitt** [comment]
Yep that's what I meant, gutter (the area with icons and number lines) can't be resized so the only way is to change the size of icons.

I guess making a new icon set would work, but is there no way to programmatically set the scale of the icons? Or would that be redundant?

**Comment by kaste** [comment]
Honestly, I don't know.  Maybe ask in the Sublime forum.

**Comment by AdriandeCita** [comment]
I felt like this is relevant, so decided to post it here.

What about having an option of displaying errors inline? There is a vscode plugin called ErrorLens, which, in addition to standard text highlighting and gutter icon, displays error message right at the code. Would be nice to have something similar here

![image](https://user-images.githubusercontent.com/11510394/236243467-d24d7308-810a-4c92-aa22-020c5cfa869b.png)

**Comment by kaste** [comment]
@AdriandeCita We have that already, some explanation is in the release notes https://github.com/SublimeLinter/SublimeLinter/releases/tag/4.20.0 and of course in the settings https://github.com/SublimeLinter/SublimeLinter/blob/master/SublimeLinter.sublime-settings#L176-L240 and additionally https://github.com/SublimeLinter/SublimeLinter/blob/master/SublimeLinter.sublime-settings#L43-L52

**Comment by kaste** [comment]
I close this as afaik this is not supported by Sublime Text, t.i. changing the icon size in the gutter on-the-fly.
