### ISSUE TITLE
Not working with pnpm

### ISSUE THREAD

**Issue by zzph** [SublimeLinter/SublimeLinter#1910]
Hi there,

Thanks for this great linter.

The linter works fine when I install projects using `npm install`.

I'm switched to using `pnpm`, it errors telling me:

`/Volumes/USER_NAME/PATH/PROJECT/node_modules/.bin/eslint: line 2: sed: command not found`

May not be relevant, but I'm using Volta.

My settings are:
```
{
    "linters": {
        "eslint": {
            "disable": false,
            "args": ["--env=es6"],
            "env": {
               "PATH": "/Users/USER_NAME/.volta/tools/image/node/18.16.0/bin"
            }
        }
    }
}
```

IIs it because the `pnpm` store path is somewhere different? 

`pnpm store path` tells me it's at `/Users/USER_NAME/Library/pnpm/store/v3`

If so, do I need to point SublimeLinter to 'that' node modules path? How would I do that?

**Comment by kaste** [comment]
Closing as stale

**Comment by flekschas-ozette** [comment]
I'm having the exact same issue. This is thrown in SublimeText:

```
SublimeLinter: ERROR: /Users/fritz/stuff/node_modules/.bin/eslint_d: line 2: sed: command not found
/Users/fritz/stuff/node_modules/.bin/eslint_d: line 2: dirname: command not found
/Users/fritz/stuff/node_modules/.bin/eslint_d: line 4: uname: command not found
node:internal/modules/cjs/loader:1147
  throw err;
  ^

Error: Cannot find module '/eslint_d/bin/eslint_d.js'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)
    at Module._load (node:internal/modules/cjs/loader:985:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)
    at node:internal/main/run_main_module:28:49 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v20.11.0
```

However, when I run `/Users/fritz/stuff/node_modules/.bin/eslint_d` in my terminal it works as expected:

```
/Users/fritz/stuff/node_modules/.bin/eslint_d src/components/button.tsx 
```

The only change we introduced was the switch from `yarn` to `pnpm`.

**Comment by flekschas-ozette** [comment]
I can confirm that

> Now I see you do "PATH": "/Users/USER_NAME/.volta/tools/image/node/18.16.0/bin" which replaces the PATH variable. I think prepending to PATH makes more sense, e.g. `"PATH": "/Users/USER_NAME/.volta/tools/image/node/18.16.0/bin:$PATH".

was the root issue. Prepending the path fixes the issue.
