### ISSUE TITLE
Recommended approach for linters that output error location relative to start of buffer?

### ISSUE THREAD

**Issue by harrymander** [SublimeLinter/SublimeLinter#1916]
Hi - thanks for the great plugin.

I am trying to improve [my plugin for `clang-format`](https://github.com/harrymander/SublimeLinter-contrib-clang-format), which was recently merged into the SublimeLinter package index, to highlight the entire error region. For example, the following include block in unsorted so clang-format returns an error on line 1, column 1:

```
main.c:1:1: warning: code should be clang-formatted [-Wclang-format-violations]
```
![image](https://github.com/SublimeLinter/SublimeLinter/assets/41089556/8ae46d7d-1144-46e7-a21b-2de2a51fb3b7)

Ideally it would highlight the entire block like so:

![image](https://github.com/SublimeLinter/SublimeLinter/assets/41089556/111fbc8b-cee0-4017-bda8-c3fdda6e4727)

My current solution is to use clang-format's `--output-replacements-xml` which returns an XML containing the location of the error relative to the start of the file and its length:

```
<replacement offset='0' length='88'> ... </replacement>
```

This is achieved by overriding `process_match` to manually set the region:

```python
class ClangFormat(lint.Linter):
    # ...

    regex = r"^<replacement offset='(?P<offset>\d+)' length='(?P<length>\d+)'"

    def split_match(self, match):
        return LintMatch({
            'warning': 'warning',
            'message': 'Not formatted properly',
            'offset': int(match.group('offset')),
            'length': int(match.group('length')),
            'line': 1,
        })

    def process_match(self, m, vv):
        r = super().process_match(m, vv)
        offset = m['offset']
        r['region'] = Region(offset, offset + m['length'])
        r['line'] = offset  # Will not report multiple errors on same line unless set to unique value
        return r
```

Obviously this sets the `line` field to an incorrect value. Even though `line` seems to be ignored anyway, it feels a little hacky. Is there a recommended way to handle this, or would you welcome a PR to add support for such linters?

**Comment by kaste** [comment]
That is somehow supported but you must not implement `process_match` because then you work with the type `LintError`. Users should stay in the `LintMatch` domain.  You have to implement `reposition_match` which given a virtual view (`vv`) can compute the correct line, starting column and length to highlight.  

The virtual view has no method ready to use because we never needed it but it has enough information to compute the line:col pair.  And the length you already have.  Hint: the private member `_newlines` (if I recall that misnamed thing correctly) is a mapping from line number to the character offset at the bol of that line.

You may have a look but I can also write more on it if you need further help.

**Comment by harrymander** [comment]
Have created a PR adding a `rowcol` method, similar to the [SublimeText API](https://www.sublimetext.com/docs/api_reference.html#sublime.View.rowcol): https://github.com/SublimeLinter/SublimeLinter/pull/1917

My linter implementation would then change to:

```python
# ...
    def reposition_match(self, line, col, m, vv):
        line, col = vv.rowcol(m['offset'])
        return line, col, col + m['length']

    def split_match(self, match):
        return LintMatch({
            'warning': 'warning',
            'message': 'Not formatted properly',
            'offset': int(match.group('offset')),
            'length': int(match.group('length')),
            'line': 1,
        })
```
