### ISSUE TITLE
Verilator command issue in sublimelinter

### ISSUE THREAD

**Issue by LSP35** [SublimeLinter/SublimeLinter#1922]
Hi there,

I saw there are some arguments I didn't set in SublimeLinter Setting file for verilator, but it was issued in the console. Is there any method to modify the command? Thanks.

Invalid arguments:
      1. -Wno-DECLFILENAME
      2. -Wno-PINMISSING

Command issue from console:
`C:\cygwin64\home\verilator\bin\verilator_bin.EXE --lint-only -Wall -Wwarn-DECLFILENAME -Wwarn-PINMISSING -Wwarn-lint -Wwarn-style --error-limit 500 -Wno-DECLFILENAME -Wno-PINMISSING`

**Comment by kaste** [comment]
Hello!  It looks like these two arguments are hard-coded (source: https://github.com/poucotm/SublimeLinter-contrib-verilator/blob/master/linter.py#L155-L156).  verilator is a contrib plugin (and it is a non-trivial plugin as well) so I can't tell you much about it.  Please ask over there https://github.com/poucotm/SublimeLinter-contrib-verilator/issues

Apparently the plugin doesn't use our `defaults` or `args` system.  Don't know why that is, it should.

**Comment by kaste** [comment]
Looks like you're not there anymore.  🤷
