### ISSUE TITLE
GCC Executing Instead of G++ for cpp/hpp Files on MacOS Using Homebrew

### ISSUE THREAD

**Issue by benwills** [SublimeLinter/SublimeLinter#1930]
I am unable to figure out how to get SublimeLinter on MacOS to use g++ and its options instead of gcc.

The problem: _For cpp/hpp files, SublimeLinter executes the settings for gcc, not for g++._

I have not had these issues on Linux/Ubuntu.

Below is my SublimeLinter.sublime-settings file, with paths and includes removed.

You can see various settings I've tried for the "selector," "executable," "args," etc, which are commented out.

gcc/g++ has been installed using HomeBrew, and all updates have been applied to SublimeText, HomeBrew, SublimeLinter, etc.

Any help you can provide would be appreciated.

Thanks.

	// SublimeLinter Settings - User
	{
		// "debug": false,
		"delay": 0.25,
		// "show_panel_on_save": "never",
		"lint_mode": "background",
		"linters":
		{
			"g++": {
				"disable": false,

				"selector": "source.hpp, source.cpp",
				// "selector": "source.hpp, source.cpp, source.hxx, source.cxx",

				"executable": "/opt/homebrew/bin/g++-13",
				// "executable": "/opt/homebrew/Cellar/gcc/13.2.0/bin/g++-13",

				"args": ["-fsyntax-only", "-std=c++20", "-Wno-register", "-Wno-deprecated-declarations", "-fpermissive", "-march=native"],

				"I": [
				],
				"excludes": [],
				"filter_errors": [
					"once in main file",
					"has incomplete type",
				],
				"filter_warnings": [
					"once in main file",
					"has incomplete type",
				],
				"paths": {
					"linux": [],
					"osx": [
					],
					"windows": []
				}
			},
			"gcc": {
				"disable": false,

				"selector": "source.h, source.c",
				// "selector": "source.hpp, source.cpp, source.h, source.c",

				"executable": "/opt/homebrew/bin/gcc-13",
				// "executable": "/opt/homebrew/bin/g++-13",

				"args": ["-std=c2x", "-fsyntax-only"],
				// "args": ["-fsyntax-only", "-std=c++23", "-Wno-register", "-Wno-deprecated-declarations", "-fpermissive", "-mavx", "-march=native"],

				"I": [
				],
				"filter_errors": [
					"once in main file",
					"has incomplete type",
				],
				"filter_warnings": [
					"once in main file",
					"has incomplete type",
				],
				"paths": {
					"linux": [],
					"osx": [
					],
					"windows": []
				}
			},
			"clang": {
				"disable": true,
			},
			"clang++": {
				"disable": true,
			}
		},
		"syntax_map": {
			"cmore": "c",
			"cppmore": "c++",
		},
	}

**Comment by kaste** [comment]
A structured approach could be to set selector just to something obvious like _source_.  That basically matches for every source file you open.  And you can set executable to something bogus, something that doesn't exist, because SublimeLinter should show an error in such cases.  

Then you could at least tell if it sees your settings.  You should then also set debug to true and watch the logging in Sublime's console.

**Comment by benwills** [comment]
Thanks. This helped a lot to start narrowing down what might be happening.

In short, doing as you said, setting `"debug":true` and `"selector":"source"`, did invoke g++ and it was properly triggering the g++ linter. The downside here is that now _every_ file is "linted" by g++, including json, etc.

But...it was also triggering the gcc linter, showing me both g++ _and_ gcc errors. Adding `"excludes": [ "*.hpp", "*.cpp" ],` to the gcc parameters stopped triggering the gcc linter.

When I then switch the g++ linter setting back to `"selector": "source.hpp, source.cpp"`, SublimeLinter showed the following in the console:

	SublimeLinter: sublime_linter.py:341  Delay linting 'count_file_ext_recursive.cpp' for 0.25s
	SublimeLinter: linter.py:1094         gcc skipped '/usr/local/src/o/lib/cpp/o/File/.dev/count_file_ext_recursive.cpp', excluded by '*.cpp'
	SublimeLinter: sublime_linter.py:360  No installed linter matches the view.

So it looks like what might be happening may be a couple things:
- Somewhere, it may be hardcoded that gcc should be run for .hpp, .cpp, .c, and .h files by default, given that I have to manually exclude .hpp and .cpp files for gcc to not trigger.
- Somehow, the "selector" setting doesn't seem to be working for g++, and may not be working with gcc, given that the only way I'm able to trigger g++ is by setting `"selector":"source"`

Any thoughts on where to go from here?

**Comment by kaste** [comment]
Hm, I think I know better where you're standing.  I don't know exactly why you changed so much defaults/settings.  Now when you set `source.hpp` I thought maybe you know exactly why you do this, but maybe you're just guessing.  The default selector for g++ is `"selector": "source.c++"` and for gc it is `source.c`.  These selectors match with the installed syntaxes.  Sublime Text does not ship with other (e.g. specialized) syntaxes.  So when you say `source.hpp` and SublimeLinter tells you `No installed linter matches the view.` it basically tells you that the view does *not* have such a syntax (a syntax that defines *source.hpp*).  

You can find the selector by invoking  `ctrl+alt+shit+p`.  
![image](https://github.com/SublimeLinter/SublimeLinter/assets/8558/b36ebebb-e402-4779-8c56-5ccaa9f43ac6)

On my vanilla system this is 
![image](https://github.com/SublimeLinter/SublimeLinter/assets/8558/87bebf9c-5f51-464a-a675-d786774503e1)

The scope/selector can be very long, then just take the first part of it.
It could be that Sublime uses the *same* syntax for different files.  You can usually fix that:

![image](https://github.com/SublimeLinter/SublimeLinter/assets/8558/879af20d-dcec-429a-aeb0-feecb9f68501)

**Comment by benwills** [comment]
Hi Herr,

Thanks a ton for your help on this. It helped me find a bug with my custom themes where my cpp theme was setting the scopeName to source.c, instead of source.c++.

It took me a bit to track that down, but I don't know that I would have figured that out without your help. And I've been trying to chip away at this here and there for a couple weeks now.

I'm going to go back to the settings files and rework them a bit more to remove anything unnecessary, as you mentioned.

I'll reopen this if I need anything else. But I think I've got it from here.

Thank you again.
