### ISSUE TITLE
[Feature Request] "show_panel_on_save" should able to specify it's scope

### ISSUE THREAD

**Issue by WZ-Tong** [SublimeLinter/SublimeLinter#1936]
Example:
```json
{
    "show_panel_on_save": "window",
    "show_panel_on_save_opt": "warning" // Warning, Error, or some higher level
}
```

or 

```json
{
    "show_panel_on_save": "window",
    "show_panel_on_save_opt": ["info", "warning"] // Specify levels
}
```

**Comment by kaste** [comment]
We maybe should go with `show_panel_on_save.ignored_error_types: []`.  The relevant code is https://github.com/SublimeLinter/SublimeLinter/blob/5177861c69b0b7181f1a76a6a0d2c7479ae3c67e/panel_view.py#L252-L267

`filename` here holds a set of filenames that got saved.  `has_relevant_errors` need to be changed to apply the new filter.  No unit tests have to be written unless the filtering gets too tricky to get it.

**Comment by kaste** [comment]
@WZ-Tong Do you want to try an implementation for this one?

**Comment by WZ-Tong** [comment]
> @WZ-Tong Do you want to try an implementation for this one?

I'm sorry but I'm not familiar with the sublime text api, but if it doesn't need to be implemented soon, I can have a try later.
