### ISSUE TITLE
Sublime Linter is broken with ST 4 build 4174

### ISSUE THREAD

**Issue by eblot** [SublimeLinter/SublimeLinter#1939]
After upgrading this morning to build 4174, Sublime Linter stopped to work, with the following traceback:

```
Traceback (most recent call last):
  File "/Users/eblot/Library/Application Support/Sublime Text/Installed Packages/SublimeLinter.sublime-package/highlight_view.py", line 477, in draw
  File "/Users/eblot/Library/Application Support/Sublime Text/Installed Packages/SublimeLinter.sublime-package/lint/util.py", line 82, in wrapped
RuntimeError: 'draw_view_region' must be called from the UI thread
```

Reverting ST4 to build 4173 enables running Sublime Linter, but I guess this is only a temporary workaround.

**Comment by kaste** [comment]
Really, a new Sublime Text build broke SublimeLinter?  I also updated SublimeLinter yesterday with a bug with a different trace but the same message.  

I don't have the newer Sublime version yet.  So I'll have to look later.

**Comment by eblot** [comment]
I think so, but I might be wrong. I've updated Sublime Linter with no issue. It breaks with 4174, and works fine with 4173.

**Comment by kaste** [comment]
Could you try and downgrade SublimeLinter too?  Appreciate your help because that may be hard to reproduce on different systems.

**Comment by eblot** [comment]
You mean ST 4174 + older Sublime Linter version? Yes I can give it a try.
What would be the procedure to downgrade Sublime Linter (I only installed it w/ Package Manager up to now)?

**Comment by kaste** [comment]
Well, you basically just git clone it into the Packages folder.  Then it automatically overrides the version from Package Control.  Check out any tag or commit you want. Restart Sublime Text.

**Comment by kaste** [comment]
I just updated and "of course" can't reproduce.  😐  (I'm on Windows.)  

The instruction in the previous post were a bit short, so...

![image](https://github.com/SublimeLinter/SublimeLinter/assets/8558/7aafb1cd-0b5a-4257-890f-e1499fa41e21)

should open the "Packages" folder where you `git clone https://github.com/SublimeLinter/SublimeLinter.git` to.

**Comment by eblot** [comment]
1. I moved `SublimeLinter.sublime-package` out of `$HOME/Library/Application Support/Sublime Text/Installed Packages` and checked out `https://github.com/SublimeLinter/SublimeLinter.git` into `$HOME/Library/Application Support/Sublime Text/Packages`
   * no issue

2. I upgraded ST4 once more to build 4174
   *  the problem .. no longer appears!

Comparing the Package Installer downloaded, unzipped version of SublimeLinter with the Git version, I see no difference (except missing test/doc files, etc, but no diff in existing files).

So let assume this was some kind of glitch, I really have no idea about what happened and close this issue for now.
Thanks for your help.

**Comment by kaste** [comment]
Did you also remove the "git clone" and are back to the Package Control version?  It may still be possible that the downloaded package, what you have in "Installed Packages", has a slightly different load mechanism than an unpacked folder.  Just want to be sure.
