### ISSUE TITLE
SublimeLinter gives an error message when SublimeText starts

### ISSUE THREAD

**Issue by PetSven** [SublimeLinter/SublimeLinter#1950]
When I launch sublime text, I get this error message. I uninstalled and reinstalled pycodestyle linter using package control, but I am still getting this error.

![IMG_3547](https://github.com/user-attachments/assets/5b89bd18-aee9-4a3a-8be6-5da41fcc1ff0)

**Comment by kaste** [comment]
Strange, pycodestyle.PY is not a typical executable in Windows.  Did it choose that automatically? I don't think having site-packages on PATH is very common as well.  Not sure where the %1 is coming from though.

**Comment by kaste** [comment]
Closing as stale
