### ISSUE TITLE
Add a ${sublime} variable

### ISSUE THREAD

**Issue by simonzack** [SublimeLinter/SublimeLinter#197]
This would allow putting linter config files in the sublime text config dir, e.g.:

```
"pylint": {"rcfile": "${sublime}/pylintrc"}
```

**Comment by skj3gg** [comment]
Since, to my knowledge, SL-pylint is the only linter that utilizes this setting, that project would probably be the place to implement this (cc. @NotSqrt)

**Comment by simonzack** [comment]
I'm just taking pylint as an example, pylint places it in `$HOME` by default.

**Comment by NotSqrt** [comment]
Isn't that what the ``${project}`` token does ? (folder of the sublime-project file)

**Comment by simonzack** [comment]
Note quite, this is the sublime text configuration directory, i.e. `~/.config/sublime-text-3` on linux. They're quite different on different environments, so I can't just use `$HOME`.

**Comment by NotSqrt** [comment]
ok.
Then it seems this token has its place in SL itself, not SL-pylint.

**Comment by skj3gg** [comment]
Alright so `${sublime}` your want to convert to the ST `Packages/User/` directory?

**Comment by skj3gg** [comment]
so for me it would be
'/Users/skj3gg/Library/Application Support/Sublime Text 3/Packages/User'
or
'C:\\sublime\\Data\\Packages\\User'

**Comment by i-akhmadullin** [comment]
There is `${packages}` variable to refer to Packages folder. [Docs](http://sublime-text-unofficial-documentation.readthedocs.org/en/latest/reference/build_systems/configuration.html#build-system-variables)

**Comment by skj3gg** [comment]
AFAIK, Thats only for `.sublime-build` files though

**Comment by i-akhmadullin** [comment]
It's also works in .sublime-keymap files

**Comment by simonzack** [comment]
@skj3gg Yes that's the idea.

**Comment by kaste** [comment]
@braver This has been implemented. You can close this.

**Comment by braver** [comment]
Thanks!
