### ISSUE TITLE
Enable a Linter to Support Autofixing (JSCS)

### ISSUE THREAD

**Issue by TheSavior** [SublimeLinter/SublimeLinter#207]
We are working on Autoformatting over at JSCS https://github.com/jscs-dev/node-jscs/issues/516 and I've been trying to figure out if SublimeLinter has any ability for a linter plugin to actually modify the content of the view that it is linting. 

We would love for the JSCS linter package, which is the de-facto standard for Sublime and JSCS integration to support this out of he gate but aren't sure if you guys are interested in this approach of doing more than just linting.

In the meantime, I've put up a repo for a separate Sublime plugin here: https://github.com/TheSavior/Sublime-JSCS-Formatter but I'd much prefer to delete that project and add the functionality to the SublimeLinter package.

**Comment by skj3gg** [comment]
Currently this isn't part of the SublimeLinter platform. It's a tough decision to make, whether or not this falls into scope of the project, but using the ST API you should be able to incorporate a setting in the existing SL-JSCS that would make the changes and push back to the view. I'm not promising cleanliness, but if you didn't want the separate formatter repo. `SublimeFormatter` maybe needs to become a thing. ;)

**Comment by braver** [comment]
Realistically, this is not going to happen. See also https://github.com/SublimeLinter/SublimeLinter/issues/375
