### ISSUE TITLE
add debug info when "unexpected syntax returned from get_syntax"

### ISSUE THREAD

**Issue by kpdecker** [SublimeLinter/SublimeLinter#263]
When using the JSX syntax available via package control, the syntax name resolves to `jsx-real` rather than the display name that is presented to the user (`javascript (jsx)`), causing the syntax map to break without any indication as to what happened.

https://github.com/allanhortle/JSX/blob/master/JSX-real.tmLanguage is the file in question that is being resolved by the `view.settings().get('syntax', '')` call.

Ideally the display name would be used here rather than the derived file name but at minimum it's be helpful if debug mode would have logging for this case to help tracking it down.

**Comment by braver** [comment]
We're going to attack the underlying problem via #691.
