### ISSUE TITLE
[virtualenv] Pylint not showing errors

### ISSUE THREAD

**Issue by DannyPinghero** [SublimeLinter/SublimeLinter#276]
Just installed Sublimelinter and pylint yesterday, can't seem to get it to work properly.  I have a python file with a number of errors, including some egregious ones deliberately introduced.  Running pylint from the command line finds them, but running from within sublime I get nothing after running Lint This View and just the 'no lint errors' pop up after running Show All Errors from the command palette.  

I'm using Sublime 3083 on Ubuntu 14.04, and the (presumably) most recent version of SublimeLinter and the pylint plugin.   I'm working in a virtualenv using python 2.7.6 - it wasn't really clear to me how to get sublimelinter to look there and find the right combination of python and pylint versions (I was getting cannot find pylint@python deactivation warnings, even with @python=2.7 in various settings files and with shebangs at the starts of my files), so I just went into the source and hard coded my paths as a temporary measure.  
As far as I can tell, my python and pylint are now being found correctly and the linter is active.  The paths shown match the output from which python and which pylint

Here is my relevant console output with debug on:

```
reloading plugin SublimeLinter-pylint.linter
SublimeLinter: pylint linter loaded 
reloading plugin SublimeLinter.commands
reloading plugin SublimeLinter.sublimelinter
plugins loaded
SublimeLinter: debug mode: on 
SublimeLinter: temp directory: /tmp/SublimeLinter3-danny 
SublimeLinter: find_python(version='3', script=None, module=None) 
SublimeLinter: find_python: requested version = {'minor': None, 'major': 3} 
SublimeLinter: user shell: /bin/bash 
SublimeLinter: computed PATH using /bin/bash:
/usr/local/sbin
/usr/local/bin
/usr/sbin
/usr/bin
/sbin
/bin
/usr/games
/usr/local/games

SublimeLinter: find_posix_python: python3 => /usr/bin/python3 
SublimeLinter: find_python: system python = /usr/bin/python3 
SublimeLinter: find_python: available version = {'minor': 4, 'major': 3} 
SublimeLinter: find_python: <= ('/usr/bin/python3', None, 3, 4) 
SublimeLinter: sys.path for /usr/bin/python3:
/usr/lib/python3.4
/usr/lib/python3.4/plat-x86_64-linux-gnu
/usr/lib/python3.4/lib-dynload
/usr/local/lib/python3.4/dist-packages
/usr/lib/python3/dist-packages

SublimeLinter: find_python(version=None, script='pylint', module=None) 
SublimeLinter: find_python: default python = /home/danny/ciq/env/bin/python 
SublimeLinter: find_python: available version = {'minor': 7, 'major': 2} 
SublimeLinter: find_python: 'pylint' path = /home/danny/ciq/env/bin/pylint 
SublimeLinter: find_python: <= ('/home/danny/ciq/env/bin/python', '/home/danny/ciq/env/bin/pylint', 2, 7) 
SublimeLinter: pylint version query: /home/danny/ciq/env/bin/python /home/danny/ciq/env/bin/pylint --version 
SublimeLinter: pylint version: 1.4.3 
SublimeLinter: pylint: (>= 1.0) satisfied by 1.4.3 
SublimeLinter: pylint activated: ('/home/danny/ciq/env/bin/python', '/home/danny/ciq/env/bin/pylint') 

SublimeLinter: found existing Rails syntax, version 1 
SublimeLinter: found existing HTML syntax, version 3 
SublimeLinter: find_python(version='2.7', script='pylint', module=None) 
SublimeLinter: find_python: requested version = {'minor': 7, 'major': 2} 
SublimeLinter: find_posix_python: python2.7 => /usr/bin/python2.7 
SublimeLinter: find_python: system python = /usr/bin/python2.7 
SublimeLinter: find_python: available version = {'minor': 7, 'major': 2} 
SublimeLinter: find_python: 'pylint' path = /home/danny/ciq/env/bin/pylint 
SublimeLinter: find_python: <= ('/usr/bin/python2.7', '/home/danny/ciq/env/bin/pylint', 2, 7) 
SublimeLinter: pylint: models.py ['/usr/bin/python2.7', '/home/danny/ciq/env/bin/pylint', "--msg-template='{line}:{column}:{msg_id}: {msg}'", '--module-rgx=.*', '--reports=n', '--persistent=n'] 
SublimeLinter: pylint: models.py ['/usr/bin/python2.7', '/home/danny/ciq/env/bin/pylint', "--msg-template='{line}:{column}:{msg_id}: {msg}'", '--module-rgx=.*', '--reports=n', '--persistent=n'] 
```

This is pretty similar to issue 246, I checked everything that was mentioned in there that applies to me, as far as I could tell.  I don't have a .sublimelinterrc file, I don't have any settings files with pylint disabled.

Any help would be appreciated

**Comment by NotSqrt** [comment]
Can you try with pylint installed with ``sudo pip install pylint``, not in a virtualenv ?

**Comment by timburke** [comment]
In case anyone runs into this still, here's a workaround for the likely cause.  Sublimelinter, as of today, looks for the `pylint`script in your global python environment.  However, if you specify a virtualenv python using `@python` in `.sublimelinterrc`, it will **run** that script using the virtualenv python interpreter.  This will fail silently because pylint's modules are not installed in the virtualenv.

**Conclusion:** `pip install pylint` both in the global python environment (so SublimeLinter can find it) and in your virtualenv so that when it is run it has access to the right installed modules.

**Comment by braver** [comment]
We have been making [many changes](https://github.com/SublimeLinter/SublimeLinter/blob/master/messages/4.0.0-rc.1.txt) to SublimeLinter, some of which also should have fixed this particular problem. It would be really nice if you could [try the beta](https://github.com/SublimeLinter/SublimeLinter/tree/15bb4a2e2024a623f60bb444eadd5790764fdfb9#sublimelinter-4-beta) and let us know if that fixes the problem for you.

**Comment by kaste** [comment]
Closing. Everything changed since then.
