### ISSUE TITLE
Attach linters to a specific python version

### ISSUE THREAD

**Issue by NotSqrt** [SublimeLinter/SublimeLinter#281]
This is a follow-up of SublimeLinter/SublimeLinter-pylint#12

The heavy work of this ticket needs to be done in SublimeLinter itself.

Current steps:
- find available python versions
- find one pylint executable
- call it with `<default python> pylint --version` to determine if the pylint linter is usable, which works if there is only 1 version of pylint installed (might be in multiple python versions), and fails if there are multiple versions, and the one installed for the default python is not the detected pylint executable.

It can fail because the pylint entrypoints look like:

``` python
from pkg_resources import load_entry_point
load_entry_point('pylint==1.3.1', 'console_scripts', 'pylint')()
```

and obviously, if 1.3.1 is installed for python3.3, and default python is 2.7, it won't find the proper distribution.

Desired steps:
- find available python versions
- **find pylint executable for each of the python versions**
- for each of them, identify their version to determine if the linter is compatible
- then, when linting, use the correct python and correct pylint according to `@python` version.

**Comment by braver** [comment]
We have been making [many changes](https://github.com/SublimeLinter/SublimeLinter/blob/master/messages/4.0.0-rc.1.txt) to SublimeLinter, some of which also should have fixed this particular problem. It would be really nice if you could [try the beta](https://github.com/SublimeLinter/SublimeLinter/tree/15bb4a2e2024a623f60bb444eadd5790764fdfb9#sublimelinter-4-beta) and let us know if that fixes the problem for you.

**Comment by braver** [comment]
I definitely think this was fixed in SL4
