### ISSUE TITLE
option to NOT use the local linter (e.g. local node module)

### ISSUE THREAD

**Issue by congqiao** [SublimeLinter/SublimeLinter#307]
I have eslint installed both globally and locally. The local eslint is maintained by colleagues. Is there a way to NOT use the local eslint?

**Comment by fatfisz** [comment]
It seems that currently there isn't. I was just having the same problem and found the line responsible for this:
```python
        node_cmd_path = local_cmd if local_cmd else global_cmd
```
(https://github.com/SublimeLinter/SublimeLinter3/blob/master/lint/node_linter.py#L128)

**Comment by braver** [comment]
This probably ends up as "won't fix", it runs counter to how this usually works. But let's keep it around as a feature request for later reference.

**Comment by braver** [comment]
tracking this feature here: https://github.com/SublimeLinter/SublimeLinter/issues/781
