### ISSUE TITLE
Accept a range instead of just line/col

### ISSUE THREAD

**Issue by sindresorhus** [SublimeLinter/SublimeLinter#314]
Some linters supports outputting a range instead of just line/col. Would be useful if SublimeLinter could somehow accept this. [Atom Linter](https://github.com/atom-community/linter) supports it with a [`range` option](https://github.com/atom-community/linter/wiki/Linter-API#messages).

Example:

```
1:1-1:7  warning  some error message
```

The above syntax is `fromLine:fromColumn-toLine:toColumn`.
## 

Similar to https://github.com/SublimeLinter/SublimeLinter3/pull/101, but more flexible.

**Comment by FPtje** [comment]
It's a shame how this issue hasn't had a reply yet. I just put some work in my own linter to give (some) warnings in ranges. 

@groteworld this feature would make SublimeLinter visibly and noticeably better. Could you look into it?

**Comment by kaste** [comment]
I also think that's a bit shameful here. Now, for SL4, the underlying data structure could really easily handle this. But of course, all our views, the panel, the status bar, would freak out. 

I think a problem here is also that we don't have good support in Sublime itself to highlight ranges. E.g. I don't know if we could draw vertical lines in the gutter. And Sublime has some problems to highlight whitespace. But I don't know enough in that area, I almost only touched the backend code. 

I also don't know if there are already enough linters that actually support this. This would be also a bit more motivating to implement it

**Comment by sindresorhus** [comment]
> I also don't know if there are already enough linters that actually support this.

ESLint and TSLint support ranges.

**Comment by kaste** [comment]
Oh, hi 👋 @sindresorhus 

Well, `eslint` is at least a big player. So @braver how can we visually appealing draw highlights, regions, gutter marks which span multiple lines?

**Comment by braver** [comment]
Errors over multiple lines are terrible. I get those sometimes using LSP with typescript. You cannot do anything *in* the code (i.e. highlight it) that isn't super distracting. 

Also, multiple gutter marks might seem to indicate multiple errors. The API only support images. You can fake a line with overlapping images, but you can't know if a user doesn't already use that style for something like GitGutter (which is one reason why the icons are configurable). 

So, depending on the behaviour of the linter highlighting ranges isn't even desirable or a good default. At least not over multiple lines. 

Perhaps we *could* highlight the range if your cursor is in it, that might be neat. You'd have a small indicator to say "here is an error" and it would expand if you jump to it (and show the message in the statusbar).

**Comment by FichteFoll** [comment]
`rustc` also outputs column ranges in its json format. Currently I use that to generate a `near` field, but I don't feel good about it.

**Comment by kaste** [comment]
Okay @braver that's a bit vague.

Here a typical less helpful highlight. This is a flake8 WS error. flake8 is trying to tell me that I have too many empty lines:

![image](https://user-images.githubusercontent.com/8558/35093911-fc0aa0fc-fc43-11e7-80c7-ff0ae0c9e357.png)

What I want is probably something like this:

![image](https://user-images.githubusercontent.com/8558/35094287-1f538186-fc45-11e7-8839-765594ff8502.png)

**Comment by braver** [comment]
> that's a bit vague

Sorry.

You're proposal/screenshot looks like it could work. However, that looks a lot like GitGutter telling me those lines are modified.

I think the most intelligent part of my previous post was the idea to make it dynamic, i.e. only highlight the region (code + gutter) when your cursor is inside the region. My primary concern is that highlighting large ranges of code (e.g. squiggly underline multiple lines) makes that code harder to read and edit. Whatever adds ranges to SL but circumvents that problem is 👍 with me.

**Comment by FichteFoll** [comment]
Underlines in general are not suited as region decoration because of the multiple lint errors targetting whitespace regions. You can easily have an outline covering multiple lines, however. It will even look linked.

**Comment by kaste** [comment]
I have something like this for python (using flake8):

![image](https://user-images.githubusercontent.com/8558/36097146-ec550bc4-0ff9-11e8-9010-a948b2484b2c.png)

Here, flake8 complains about too many empty lines between the two functions. For the implementation, you have to implement/extend `reposition_match` on the linter. For a proper 'view' (gutter marks, underlines) of this, a non-trivial iteration on `highlights_view.py` would have to follow. This is currently out of scope for the maintainers, so a user contribution (doesn't have to be a full solution of course) is needed here. (Esp. bc we don't even have a proper ui mockup we could design against.) 

Closing bc this is right now not actionable.

**Comment by kaste** [comment]
FWIW, I have the following for eslint. (I had to set the format to json to get the endLine endColumn properties.) Do you know good multi-column errors, to see how this would look usually, @sindresorhus ?

![image](https://user-images.githubusercontent.com/8558/36342528-6691a9ce-1400-11e8-9e91-05f4eb4cf2ac.png)

(empty block error)

![image](https://user-images.githubusercontent.com/8558/36342540-87f71d4c-1400-11e8-879e-a86d855e06ed.png)

(constant condition)

**Comment by kaste** [comment]
The eslint plugin is here https://github.com/SublimeLinter/SublimeLinter-eslint/pull/196

**Comment by braver** [comment]
@kaste how does this look with underlines? I would like to see a guarantee that it isn’t horrible like in the VS Code screenshot I shared.
