### ISSUE TITLE
Allow setting paths in projects

### ISSUE THREAD

**Issue by kstrauser** [SublimeLinter/SublimeLinter#32]
I'm on OS X 10.9.1 and using flake8 installed through Homebrew's Python. I've configured SL3 to look in `/usr/local` by adding this to my user settings:

``` json
{
    "user": {
        ...
        "paths": {
            "linux": [],
            "osx": [
                "/usr/local/bin"
            ],
            "windows": []
        },
        "python_paths": {
            "linux": [],
            "osx": [
                "/usr/local/lib/python2.7/site-packages"
            ],
            "windows": []
        }
        ...
    }
}
```

I wanted to override this on a per-project basis, though (since some of my projects use Python 3). I tried editing my project settings like so:

``` json
{
    ...
    "SublimeLinter": {
        "@python": 2,
         "paths": {
            "linux": [],
            "osx": ["/usr/local/bin"],
            "windows": []
        },
        "python_paths": {
           "linux": [],
           "osx": ["/usr/local/lib/python2.7/site-packages"],
           "windows": []
        }
    }
}
```

However, those settings are ignored. Unless I configure the paths in my user settings, they don't get applied.

If I've entered this wrong, please let me know and I'll update the docs with appropriate examples and open a pull request.

**Comment by ajmichels** [comment]
+1

I work on a lot of projects that use different versions of linters such as `edlint` and `phpcs`. Not being able to provide per-project binaries for linters is pretty much crippling my use of SublimeLinter.

**Comment by danpalmer** [comment]
What's the status on this?

**Comment by ExplodingCabbage** [comment]
@aparajita the main docs problem here is that the point about global settings not being settable from project settings files is tucked away in the "Setting types" section at http://www.sublimelinter.com/en/latest/settings.html#global. If I want to set up custom paths, I'm probably going to Google, learn about the "paths" setting, and at some point end up at http://www.sublimelinter.com/en/latest/global_settings.html which makes no mention at all of this limitation. Nor do any of the sections of project settings at http://www.sublimelinter.com/en/latest/settings.html mention it. If it was noted on the Global Settings page that Global Settings cannot be overridden from inside a project settings file, I think a lot of people would waste a lot less time failing to get project-specific paths to work.

**Comment by braver** [comment]
@kaste @FichteFoll I think right now we allow setting a specific executable, and also env vars. As mentioned in a comment here "The solution is actually to add an “executable” setting to each linter’s settings". So that's done then. You guys agree to close this?

**Comment by kaste** [comment]
I'm closing.

**Comment by Narretz** [comment]
@braver where can I set the "executable"? Should this work, for example, in a project file?
```
{
  "SublimeLinter":
    {
        "linters":
        {
            "eslint": {
              "executable": "C:\\Users\\Martin\\dev\\newnow\\atlasti-new\\node_modules\\.bin\\eslint"
            }
        }
    }
}
```

**Comment by kaste** [comment]
@Narretz Yes, that should do the trick. But we have variable substitutions here. OTOH I have e.g.  

``
"executable": "${folder}\\venv\\Scripts\flake8.exe"
``

for a python linter. And `${folder}` is the project/app folder.

**Comment by Narretz** [comment]
Ok, cool. Looks like this isn't documented currently where I would expect it: http://sublimelinter.readthedocs.io/en/latest/usage.html#how-linter-executables-are-located or here http://sublimelinter.readthedocs.io/en/latest/linter_settings.html

**Comment by braver** [comment]
The docs at readthedocs aren't updated for the beta yet. You can find the current version [in the repo](https://github.com/SublimeLinter/SublimeLinter/tree/master/docs).
