### ISSUE TITLE
[windows] Linting doesn't work if parent folder path or the opened filename contains a right parentheses ')'

### ISSUE THREAD

**Issue by darkred** [SublimeLinter/SublimeLinter#355]
I've noticed it by chance while using Sublime Text 3 x64 build 3086  (in win10 x64) as external editor for Greasemonkey, Using `SublimeLinter-jshint`.

I noticed frequently that whenever opening specific installed userscripts, linting doesn't work. 
But if I copied the code and pasted it in a new tab (as `javascript`) then linting would work again. 

**Eventually I found out that linting doesn't work if either the parent folder path or the opened filename contains a right parentheses ')'.**

---

<ins>Example</ins> (using a small userscript name length): 
- create this folder path: 
  `C:\Users\user\AppData\Roaming\Mozilla\Firefox\Profiles\abcdefgh.default\gm_scripts\Test_(1)` and 
- place a .js file in there (e.g. `Test_(1).user.js`) with some syntax errors. 
- If you try to open it in Sublime Text, then linting doesn't work. 
  Renaming that file to a minimum length, e,g, `1.js` doesn't work neither. 
- if now you delete the right parentheses from the parent folder `)`
  i.e. to become `Test_(1`  
  and rename the file to `Test_(1.user.js`
  and then open the file again, linting will work as expected. 
  _(if you don't rename both, then linting won't work)_

The same happens if you place the `Test_(1)` folder containing the `Test_(1).user.js` file 
to `C:\` i.e. having the minimum length possible.

---

_Enabling Debug mode in Sublimelinter3 reveals for the latter case:_ 

```
C:\Test_(1)>  "C:\Users\Kostas\AppData\Roaming\npm\\node.exe"  "C:\Users\Kostas\AppData\Roaming\npm\\node_modules\jshint\bin\jshint" --verbose --filename C:\Test_(1)\Test_(1).user.js -
\Test_(1).user.js was unexpected at this time. 
```

**Comment by grotewold** [comment]
This isn't very descriptive, so you mean if I'm in the `three.js/` project directory, I can't use any linters? What linter are you trying to use? Is there any console errors?

**Comment by darkred** [comment]
I had by mistake posted the OP while righting, Sorry. Please check it now.

**Comment by grotewold** [comment]
`Test_(1).user).js` is the file name?

**Comment by darkred** [comment]
Yes.

**Comment by darkred** [comment]
I have now finalized the post (sorry for the many edits, but it was very confusing).

**Comment by grotewold** [comment]
`/Users/grotewold/Library/Application Support/Firefox/Profiles/abcdef.default/gm_scripts/Test_(1)/Test_(1).user).js`
```javascript
var banana = 1

```

output
```
SublimeLinter: jshint: Test_(1).user).js ['/usr/local/bin/jshint', '--verbose', '--filename', '@', '-'] 
SublimeLinter: jshint output:
/Users/grotewold/Library/Application Support/Firefox/Profiles/abcdef.default/gm_scripts/Test_(1)/Test_(1).user).js: line 1, col 15, Missing semicolon. (W033)
```

Notably, this worked on a Mac, I'll dust off a vm and try on Windows. Let me know if my test is wrong.

**Comment by darkred** [comment]
Your test is right.
_(not that it matters but as I edited the OP, the filename is_ `Test_(1).user.js` 
_i.e. without the 2nd right parentheses_

So, I'm pretty sire it's a windows issue only.

**Comment by darkred** [comment]
This commit mentioned [here](https://github.com/roadhump/SublimeLinter-eslint/issues/113#issuecomment-186864493) it fixes the issue, but unfortunately not all cases.

Please try this _(using `eslint` 2.2.0 with `Sublimelinter-eslint` 1.9.4 in  `ST3` build 3107 in win 10 x64)_:
create in `C:\Users\User\Desktop`
a file named `New Text Document (3).js`
having as content `banana = ;`
it won't get linted.
Rename it to e.g. `3.js` and it will be linted.

Also, if now you move the `3.js` file inside a folder such as 
`C:\Users\User\Desktop\New folder (2)`
it won't be linted either.
Renaming the parent folder from `New folder (2)` to e.g. `2` fixes the issue.

**Comment by darkred** [comment]
_Currently using `SublmeLinter3` 3.6.1:_ 
the issue no longer occurs when using it together with `SublimeLinter-jshint`.

It only occurs when using `SublimeLinter-eslint` as I describe [here](https://github.com/roadhump/SublimeLinter-eslint/issues/113#issuecomment-189465675)

**Comment by darkred** [comment]
The cases I described in https://github.com/roadhump/SublimeLinter-eslint/issues/113#issuecomment-189465675 no longer occur (using current version of SublimeLinter 3,7,4) :

```
C:\Users\User\Desktop\New Text Document (3).js
C:\Users\User\Desktop\New folder (2)\3.js
```

But the issue in my OP still exists, and it's caused by SublimeLinter (not the SublimeLinter-jshint),
because neither SLjhint or SLeslint worked.

To reproduce: 
Create a flile contaning `something = ;` and place it in either:
```
C:\1)\2.js
C:\1\2).js
```

For reference I have enabled both SublimeLinter-esliint and SublimeLinter-jshint
and here is what I get in both cases while having the debug mode enabled:

```
SublimeLinter: jshint version query: C:\Users\Kostas\AppData\Roaming\npm\jshint.cmd --version 
SublimeLinter: jshint version: 2.9.3 
SublimeLinter: jshint: (>= 2.5.0) satisfied by 2.9.3 
SublimeLinter: jshint activated: C:\Users\Kostas\AppData\Roaming\npm\jshint.cmd 
SublimeLinter: jshint: 2).js ['C:\\Users\\Kostas\\AppData\\Roaming\\npm\\jshint.cmd', '--verbose', '--filename', '@', '-'] 
SublimeLinter: jshint output:

C:\1>  "C:\Users\Kostas\AppData\Roaming\npm\\node.exe"  "C:\Users\Kostas\AppData\Roaming\npm\\node_modules\jshint\bin\jshint" --verbose --filename C:\1\2).js -
.js was unexpected at this time. 
SublimeLinter: eslint: 2).js ['C:\\Users\\Kostas\\AppData\\Roaming\\npm\\eslint.cmd', '--format', 'compact', '--stdin', '--stdin-filename', '@'] 
SublimeLinter: eslint output:

C:\1>  "C:\Users\Kostas\AppData\Roaming\npm\\node.exe"  "C:\Users\Kostas\AppData\Roaming\npm\\node_modules\eslint\bin\eslint.js" --format compact --stdin --stdin-filename C:\1\2).js
.js was unexpected at this time. 
```

PS.  Using ST3 3126 x64 in win10 x64, node 6.8.1 x64, Sublimelinter 3.7.4.

**Comment by darkred** [comment]
I finally got it right:

In the example paths I gave in this https://github.com/roadhump/SublimeLinter-eslint/issues/113#issuecomment-189465675 (which I just deleted) the files _do_ get linted because there spaces in the path (in `New Text Document (3)` and in `New folder (2)`):

```
C:\Users\User\Desktop\New Text Document (3).js
C:\Users\User\Desktop\New folder (2)\3.js
```
But if you rename them to:
```
C:\Users\User\Desktop\3).js
C:\Users\User\Desktop\2\3).js
``` 
then they don't get linted.

And simpler paths:
```
C:\1)\2.js
C:\1\2).js
```

For reference I have enabled both SublimeLinter-esliint and SublimeLinter-jshint
and here is what I get in both cases while having the debug mode enabled:

```
SublimeLinter: jshint version query: C:\Users\Kostas\AppData\Roaming\npm\jshint.cmd --version 
SublimeLinter: jshint version: 2.9.3 
SublimeLinter: jshint: (>= 2.5.0) satisfied by 2.9.3 
SublimeLinter: jshint activated: C:\Users\Kostas\AppData\Roaming\npm\jshint.cmd 

SublimeLinter: jshint: 2).js ['C:\\Users\\Kostas\\AppData\\Roaming\\npm\\jshint.cmd', '--verbose', '--filename', '@', '-'] 
SublimeLinter: jshint output:
C:\1>  "C:\Users\Kostas\AppData\Roaming\npm\\node.exe"  "C:\Users\Kostas\AppData\Roaming\npm\\node_modules\jshint\bin\jshint" --verbose --filename C:\1\2).js -
.js was unexpected at this time. 

SublimeLinter: eslint: 2).js ['C:\\Users\\Kostas\\AppData\\Roaming\\npm\\eslint.cmd', '--format', 'compact', '--stdin', '--stdin-filename', '@'] 
SublimeLinter: eslint output:
C:\1>  "C:\Users\Kostas\AppData\Roaming\npm\\node.exe"  "C:\Users\Kostas\AppData\Roaming\npm\\node_modules\eslint\bin\eslint.js" --format compact --stdin --stdin-filename C:\1\2).js
.js was unexpected at this time. 
```

PS.  Using ST3 3126 x64 in win10 x64, node 6.8.1 x64, Sublimelinter 3.7.4.

**Comment by darkred** [comment]
Today I noticed I'm getting the following different error in console (`error in SublimeLinter daemon`).
whenever I open [this .js file](http://download1491.mediafire.com/4lbtkkec429g/ml39utjistj249s/test+file.zip).  (Please unzip it and open).

Removing the right parentheses in filename fixes the issue .

Currently using ST3 3126 x64 in win10 x64, node 7.7.2 x64, , Sublimelinter 3.7.4, Sublimelinter-contrib-eslint 1.10.0 and eslint 3.17.1 globally installed.

```
SublimeLinter: error in SublimeLinter daemon: 
SublimeLinter: -------------------- 
SublimeLinter: Traceback (most recent call last):
  File "C:\Users\Kostas\AppData\Roaming\Sublime Text 3\Packages\SublimeLinter\lint\queue.py", line 57, in loop
    item = self.q.get(block=True, timeout=self.MIN_DELAY)
  File "./python3.3/queue.py", line 175, in get
queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Kostas\AppData\Roaming\Sublime Text 3\Packages\SublimeLinter\lint\queue.py", line 65, in loop
    self.lint(view_id, timestamp)
  File "C:\Users\Kostas\AppData\Roaming\Sublime Text 3\Packages\SublimeLinter\lint\queue.py", line 111, in lint
    self.callback(view_id, timestamp)
  File "C:\Users\Kostas\AppData\Roaming\Sublime Text 3\Packages\SublimeLinter\sublimelinter.py", line 119, in lint
    Linter.lint_view(view, filename, code, hit_time, callback)
  File "C:\Users\Kostas\AppData\Roaming\Sublime Text 3\Packages\SublimeLinter\lint\linter.py", line 929, in lint_view
    linter.lint(hit_time)
  File "C:\Users\Kostas\AppData\Roaming\Sublime Text 3\Packages\SublimeLinter\lint\node_linter.py", line 77, in lint
    super(NodeLinter, self).lint(hit_time)
  File "C:\Users\Kostas\AppData\Roaming\Sublime Text 3\Packages\SublimeLinter\lint\linter.py", line 1397, in lint
    output = self.run(cmd, self.code)
  File "C:\Users\Kostas\AppData\Roaming\Sublime Text 3\Packages\SublimeLinter\lint\linter.py", line 1803, in run
    return self.communicate(cmd, code)
  File "C:\Users\Kostas\AppData\Roaming\Sublime Text 3\Packages\SublimeLinter-contrib-eslint\linter.py", line 101, in communicate
    return super().communicate(cmd, code)
  File "C:\Users\Kostas\AppData\Roaming\Sublime Text 3\Packages\SublimeLinter\lint\linter.py", line 1833, in communicate
    env=self.env)
  File "C:\Users\Kostas\AppData\Roaming\Sublime Text 3\Packages\SublimeLinter\lint\util.py", line 1110, in communicate
    out = out.communicate(code)
  File "./python3.3/subprocess.py", line 920, in communicate
  File "./python3.3/subprocess.py", line 1206, in _communicate
BrokenPipeError: [Errno 32] Broken pipe
 
SublimeLinter: -------------------- 
```
PS. (Sorry for the mediafire link but I was getting "We don’t support that file type. " when I tried to attach the zip file to this post)

**Comment by kaste** [comment]
That sounds like a reasonable bug in python 3.3. Would it break linux/osx if we just set `"{filename}"` or is python smart enough in that case.

**Comment by kaste** [comment]
Or is this the same as #347?

**Comment by kaste** [comment]
Closing as *can't replicate*

**Comment by darkred** [comment]
@kaste The issue unfortunately still exists.

STR
- Having
  - ST3 x64 build 3156 dev (in win10 x64) 
  - SL 4.0.0 rc.9.9.2 (or the current ZIP which has 21 commits more)
  - SublimeLinter-eslint 1.10.1
  - eslint 4.16.0 with a global .eslintrc (i.e. placed in C:\Users\User)  --> using npm 5.6,0
 - create a directory `C:\1)`,
 - create a .js file with some syntax errors, rename it as `2.js` and place it in the above folder:
 - the file won't get linted. Here is the log from console if you enable the 'debug' setting in SL:
 
 ```
 SublimeLinter: debug mode: on 

...

SublimeLinter: eslint: 2.js ['C:\\Users\\Kostas\\AppData\\Roaming\\npm\\eslint.cmd', '--format', 'compact', '--stdin', '--stdin-filename', 'C:\\1)\\2.js'] 
SublimeLinter: eslint output:

C:\Program Files\Sublime Text 3>  "C:\Users\Kostas\AppData\Roaming\npm\\node.exe"  "C:\Users\Kostas\AppData\Roaming\npm\\node_modules\eslint\bin\eslint.js" --format compact --stdin --stdin-filename C:\1)\2.js
\2.js was unexpected at this time. 
SublimeLinter: eslint: No match for line: '' 
SublimeLinter: eslint: No match for line: 'C:\Program Files\Sublime Text 3>  "C:\Users\Kostas\AppData\Roaming\npm\\node.exe"  "C:\Users\Kostas\AppData\Roaming\npm\\node_modules\eslint\bin\eslint.js" --format compact --stdin --stdin-filename C:\1)\2.js' 
SublimeLinter: eslint: No match for line: '\2.js was unexpected at this time.' 

 ```
 
 ----
 
 For reference the file gets linted ok via CLI 
 `eslint "\1)\2.js"`

**Comment by kaste** [comment]
Okay, I can replicate with exact that `C:\1)\2.js`. But I could not recreate with `C:\foo\bar\1)\2.js` or `C:\foo\bar\(1)\2.js`

**Comment by darkred** [comment]
> But I could not recreate with `C:\foo\bar\1)\2.js` or `C:\foo\bar\(1)\2.js`

@kaste
Unfortunately, I can still recreate them with SL 4.0.6 _(ST3 3157 dev, ESLint v4.18.2 - SL-eslint 4.0.3, node 9.8.0 in win10x64)_.

I get e.g.
```
SublimeLinter: #1 eslint 2.js ERROR:

 

C:\foo\bar\1)>  "C:\Users\Kostas\AppData\Roaming\npm\\node.exe"  "C:\Users\Kostas\AppData\Roaming\npm\\node_modules\eslint\bin\eslint.js" --format json --stdin --stdin-filename C:\foo\bar\1)\2.js

\2.js was unexpected at this time.
```

**Comment by kaste** [comment]
Hm, could you try setting executable to ['node', 'path/to/eslint']?

**Comment by darkred** [comment]
I tried adding the following in SublimeLinter settings (which was an empty file, before that) :
```
// SublimeLinter Settings - User
{
	"paths": {
        "linux": [],
        "osx": [],
        "windows": [],
        "node": ["C:\\Program Files\\nodejs"]
    }
}
```
but I still get the same error:
```
SublimeLinter: #3 eslint 2.js ERROR:

 

C:\1)>  "C:\Users\Kostas\AppData\Roaming\npm\\node.exe"  "C:\Users\Kostas\AppData\Roaming\npm\\node_modules\eslint\bin\eslint.js" --format json --stdin --stdin-filename C:\1)\2.js

\2.js was unexpected at this time.

```

PS. For reference I checked my system PATH and it includes (among others) these two entries `PATH=C:\Program Files\nodejs\;C:\Users\Kostas\AppData\Roaming\npm`

**Comment by kaste** [comment]
That's not what I meant but I'm on mobile now and can't type any code here. So I'll post it tomorrow.

**Comment by darkred** [comment]
Just for reference, I also tried:
```
// SublimeLinter Settings - User
{
	"paths": {
        "linux": [],
        "osx": [],
        "windows": ["node", "C:\\Program Files\\nodejs"]
       }
}
```
or setting it the last key as `     "windows": ["node", "C:\\Program Files\\nodejs\\node.exe"]` instead
but I still get the error.

**Comment by kaste** [comment]
Look here http://www.sublimelinter.com/en/stable/linter_settings.html#executable

**Comment by darkred** [comment]
Sorry for misreading your suggestion (I've deleted my last two comments).

By adding the following, the issue no longer occurs in any of the three cases. Thanks a lot!!
```
{
    "linters": {
        "eslint": {
            "executable": ["node", "C:\\Users\\Kostas\\AppData\\Roaming\\npm\\node_modules\\eslint\\bin\\eslint.js"]

        }
    }
}
```

**Comment by kaste** [comment]
Okay, so basically we're not doing it completely wrong here at least. Don't know if eslint could ship a better `eslint.cmd` here.
