### ISSUE TITLE
@python setting does not work when install location is not standard on Windows

### ISSUE THREAD

**Issue by aawilson** [SublimeLinter/SublimeLinter#402]
Resubmitted from here: https://github.com/SublimeLinter/SublimeLinter3/issues/226#issuecomment-176314162

In a nutshell: If Python is installed anywhere but `c:\Python<foo>`, SublimeLinter3 can't find it with the `@python` meta, and there's no way to specify a location for that lookup.

**Comment by braver** [comment]
We have been making [many changes](https://github.com/SublimeLinter/SublimeLinter/blob/master/messages/4.0.0-rc.1.txt) to SublimeLinter, some of which also should have fixed this particular problem. It would be really nice if you could [try the beta](https://github.com/SublimeLinter/SublimeLinter/tree/15bb4a2e2024a623f60bb444eadd5790764fdfb9#sublimelinter-4-beta) and let us know if that fixes the problem for you.

**Comment by kaste** [comment]
Outdated. I sure fixed that. 🤞
