### ISSUE TITLE
PATH order not honored (using zsh)

### ISSUE THREAD

**Issue by capripot** [SublimeLinter/SublimeLinter#421]
Hi guys,

In my ZSH, I have my `$PATH` var defined as:

```
/usr/local/var/rbenv/shims:/Users/capripot/.rbenv/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/capripot/.composer/vendor/bin:/Users/capripot/bin
```

But when I start Sublime, I get this order of paths:

```
SublimeLinter: computed PATH using /bin/zsh:
/usr/local/bin
/usr/bin
/bin
/usr/sbin
/sbin
/usr/local/var/rbenv/shims
/Users/capripot/.rbenv/bin
/usr/local/sbin
/Users/capripot/.composer/vendor/bin
/Users/capripot/bin
```

So SublimeLinter is clearly not respecting the order I defined in my `$PATH`. Furthermore, it's trying to use `/usr/bin/ruby` instead of `/usr/local/var/rbenv/shims/ruby`. Any idea why?

**Comment by braver** [comment]
> So SublimeLinter is clearly not respecting the order I defined in my $PATH. 

That's weird.

> Furthermore, it's trying to use /usr/bin/ruby instead of /usr/local/var/rbenv/shims/ruby. Any idea why?

Well, that's probably explained the messed up order?

**Comment by braver** [comment]
We have been making [many changes](https://github.com/SublimeLinter/SublimeLinter/blob/master/messages/4.0.0-rc.1.txt) to SublimeLinter, some of which also should have fixed this particular problem. It would be really nice if you could [try the beta](https://github.com/SublimeLinter/SublimeLinter/tree/15bb4a2e2024a623f60bb444eadd5790764fdfb9#sublimelinter-4-beta) and let us know if that fixes the problem for you.

**Comment by capripot** [comment]
Solved in version 4
