### ISSUE TITLE
Path token expansion does not works on Windows

### ISSUE THREAD

**Issue by nosuchip** [SublimeLinter/SublimeLinter#436]
Python and libraries installed into `$project_path/env`, here excerpt from sublime linter settings file:

```
        "paths": {
            "linux": [],
            "osx": [],
            "windows": [
                "${project}/env/Scripts",
                "${project}"
            ]
        },
        "python_paths": {
            "linux": [],
            "osx": [],
            "windows": [
                "${project}/env/Scripts",
                "${project}"
            ]
        },
```

and it looks like SL3 does not runs `replace_settings_tokens` at all. Here what I could see in console with debug mode turned on:

```
SublimeLinter: computed PATH from system:
C:\Program Files\Sublime Text 3\${project}\env\Scripts
C:\Program Files\Sublime Text 3\${project}
C:\Program Files\Sublime Text 3\${env:HOME}
```

I performed small research (like put `raise Exception` in method `replace_settings_tokens`) and found that this method never called, i.e. tokens not expanded correctly.

**Comment by woble** [comment]
Same here. Stopped working from `3.10.0`. `3.9` works fine.

**Comment by groteworld** [comment]
do you know if this issue was fixed in `3.10.1`?

**Comment by woble** [comment]
Does not work in `3.10.1`.

**Comment by kaste** [comment]
Token expansion is not implemented for the 'global' - I think that's what they're called - settings. Only specific linter settings are processed. 

Although I like the idea, and everything is doable, currently this is too much work aaaaaaaaaand 🥁 ... out of scope.

**Comment by FichteFoll** [comment]
A sensible approach might be to just have a couple settings like `path` and `env` that linter-specific configuration can fall back to. This should have its own issue, though.
