### ISSUE TITLE
Command path based on project path

### ISSUE THREAD

**Issue by phaistonian** [SublimeLinter/SublimeLinter#443]
Hello.

When linting files (eslint) on a remote mapped drive (using Samba) things don't play that well.

Is there a way to to, say,  enforce Sublime Linter use a different path (and not the one relative to the project) when, for example, the project path starts with `/Volumes/..` ?

I am not sure I am making much sense, but If I do and there's a reply you can share, please do.

**Comment by braver** [comment]
Ok, it's been a while, sorry about that. But have you tried setting up a Sublime project file and configuring paths that way?

**Comment by kaste** [comment]
Not completely sure about the question. But path can be understood as *working dir* which can be already set, or as the *filename* we're linting. A different filename is currently out of scope to implement. Sorry.
