### ISSUE TITLE
wrong GEM_HOME, wrong version

### ISSUE THREAD

**Issue by LeEnno** [SublimeLinter/SublimeLinter#446]
I'm using rvm with my default ruby being 2.2.4. For my project I'm using 2.3.0.

Obviously SublimeLinter should fetch `$GEM_HOME` from my project's root (ruby 2.3.0), not from my home folder (ruby 2.2.4). Unfortunately this doesn't happen. See the log:

```
SublimeLinter: computed PATH using /bin/bash:
/Users/Enno/.rvm/gems/ruby-2.3.0/bin
/Users/Enno/.rvm/gems/ruby-2.2.4/bin
/Users/Enno/.rvm/gems/ruby-2.2.4@global/bin
/Users/Enno/.rvm/rubies/ruby-2.2.4/bin
/usr/local/bin
/usr/bin
/bin
/usr/sbin
/sbin
/Users/Enno/.rvm/bin

SublimeLinter: ENV['GEM_HOME'] = '/Users/Enno/.rvm/gems/ruby-2.2.4' 
SublimeLinter: rubocop version query: /Users/Enno/.rvm/bin/rvm-auto-ruby -S rubocop --version 
SublimeLinter: rubocop version: 2.2.4 
SublimeLinter: rubocop: (>= 0.34.0) satisfied by 2.2.4 
SublimeLinter: rubocop activated: ['/Users/Enno/.rvm/bin/rvm-auto-ruby'] 
Emmet: No need to update PyV8
SublimeLinter: rubocop: boot.rb ['ruby', '-S', 'rubocop', '--format', 'emacs', '--stdin', '/Users/Enno/Sites/pictrs/master/pictrs/config/boot.rb'] 
SublimeLinter: rubocop output:
/Users/Enno/.rvm/rubies/ruby-2.2.4/lib/ruby/site_ruby/2.2.0/rubygems/dependency.rb:315:in `to_specs': Could not find 'rubocop' (>= 0.a) among 28 total gem(s) (Gem::LoadError)
Checked in 'GEM_PATH=/Users/Enno/.gem/ruby/2.2.0:/Users/Enno/.rvm/rubies/ruby-2.2.4/lib/ruby/gems/2.2.0:/Users/Enno/.rvm/gems/ruby-2.2.4', execute `gem env` for more information
    from /Users/Enno/.rvm/rubies/ruby-2.2.4/lib/ruby/site_ruby/2.2.0/rubygems/dependency.rb:324:in `to_spec'
    from /Users/Enno/.rvm/rubies/ruby-2.2.4/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_gem.rb:64:in `gem'
    from /Users/Enno/.rvm/gems/ruby-2.3.0/bin/rubocop:22:in `<main>' 
```

SublimeLinter manages to augment the path correctly (`/Users/Enno/.rvm/gems/ruby-2.3.0/bin` is at the top), but fails to fetch the correct `$GEM_HOME` (`/Users/Enno/.rvm/gems/ruby-2.2.4` instead of `/Users/Enno/.rvm/gems/ruby-2.3.0`).

This leads to the version query delivering weird results (`2.2.4` instead of `0.39.0`). Also dependencies can't be resolved correctly. SublimeLinter finds the correct binary due to the correct path, but will look for dependencies in the wrong `$GEM_HOME`.

Any chance of fixing this behavior?

**Comment by philister** [comment]
Hi.

I'm facing the same issue with rbenv.
​
On startup SublimeLinter tries to query a version for rubocop. Unfortunately it doesn't seem to execute the command (`/home/philipp/.rbenv/shims/ruby -S rubocop --version`) in the project folder, but somewhere else. I can't figure out where exactly SublimeLinter's executing the command.
​
Here's the log:
​
	reloading plugin SublimeLinter-rubocop.linter
	SublimeLinter: rubocop linter loaded 
	reloading plugin SublimeLinter.commands
	reloading plugin SublimeLinter.sublimelinter
	reloading plugin SublimeLinter-contrib-eslint.linter
	SublimeLinter: eslint linter loaded 
	plugins loaded
	SublimeLinter: debug mode: on 
	SublimeLinter: temp directory: /tmp/SublimeLinter3-philipp 
	SublimeLinter: user shell: /bin/bash 
	SublimeLinter: computed PATH using /bin/bash:
	/home/philipp/.rbenv/shims
	/home/philipp/bin
	/home/philipp/bin
	/usr/local/sbin
	/usr/local/bin
	/usr/sbin
	/usr/bin
	/sbin
	/bin
	/usr/games
	/usr/local/games
	 
	SublimeLinter: ENV['GEM_HOME'] = 'None' 
	SublimeLinter: rubocop version query: /home/philipp/.rbenv/shims/ruby -S rubocop --version 
	SublimeLinter: WARNING: no rubocop version could be extracted from:
	ruby: no Ruby script found in input (LoadError)
​
When I type the command (`/home/philipp/.rbenv/shims/ruby -S rubocop --version`) in the terminal, it works just fine in the project root or in home. It does not in every other folder.

Thnaks and regards, Phil

**Comment by djgerhab** [comment]
I'm seeing the same issue as philister above, but I'm using rvm. I added the appropriate paths in SublimeLinter.sublime-settings and the command does work in the terminal. Still getting:

`SublimeLinter: rubocop version query: /Users/gerhabd/.rvm/bin/rvm-auto-ruby -S rubocop --version 
SublimeLinter: WARNING: no rubocop version could be extracted from:
ruby: No such file or directory -- rubocop (LoadError)`

One thing to note is that this was working before without me having to touch the path settings. Not sure when, but sometime within the past few months it just stopped.

**Comment by djgerhab** [comment]
**UPDATE:**

I fixed my issue and of course right after posting that. The issue was that although I added a bunch of bin paths to the SublimeLinter.sublime-settings, I didn't add the specific one that the Sublime was reading off of. After using the `which` command, outlined in the link below, and adding that specific path, it works.

http://sublimelinter.readthedocs.io/en/latest/troubleshooting.html#finding-a-linter-executable

**Comment by LeEnno** [comment]
Thanks for the feedback @djgerhab .

Would you mind being a little more specific? What do you mean by "I didn't add the specific one that the Sublime was reading off of"?

It would be awesome if you could show your concrete paths, so I can learn from it and see if that might fix my issue, too

**Comment by djgerhab** [comment]
Sure thing,

So in the SublimeLinter.sublime-settings I had 

        "paths": {
            "linux": [],
            "osx": [
                "/Users/gerhabd/.rvm/rubies/ruby-2.3.1/bin",
                "/Users/gerhabd/.rvm/bin"
            ],
            "windows": []
        },

But once I did a `which` I realized I had missed placing the bin that contained rubocop

    $ hash -r
    $ which rubocop
    /Users/gerhabd/.rvm/gems/ruby-2.3.1/bin/rubocop

I still don't understand why this was working previously, then all of the sudden I had to include it. *shrug*

**Comment by LeEnno** [comment]
Ok, thanks for following up.

My paths are totally fine. Like I said SublimeLinter seems to execute the version query in the context of the user directory, no matter which paths I write into the settings. That's why I have to install the rubocop gem in 2 places (project folder *and* user folder) to make it work.

Another question to nail this bug down: do you actually use different ruby versions on your system? Let's say 2.3.1 as default, but in a certain project 2.2.4 because of $reason?

**Comment by LeEnno** [comment]
Just to make this clear: the thing going wrong here is the version query, nothing else. Somehow the version query doesn't respect the augmented path. This becomes evident when considering that the same issue occurs with hamllint (which also uses a version query on initialization).

Also, it's a timing issue. The issue only occurs on startup. It doesn't occur when a non-`.rb` file is open on startup. Same goes for hamllint. For clarification:

1. Start Sublime project with `something.rb` already open → rubocop linting is broken 😔 (and remains broken for every other `.rb` file)
2. Start Sublime project with `readme.txt` already open, then open `something.rb`  → rubocop linting works perfectly fine 🎉 (and remains fine for every other `.rb` file)

Hope this helps. I'm happy to help further drilling down the issue if necessary.

**Comment by djgerhab** [comment]
Sorry @LeEnno I couldn't help more. To answer your question above about the ruby versions. Yes I do have various versions of ruby on my computer and different projects use different ones.

**Comment by philister** [comment]
Any news on that? Can someone acknowledge this officially please?

**Comment by cerdiogenes** [comment]
I use rvm and the simplest way that I find to make it work was to install rubocop in the global slot of my default ruby, something like:

```bash
rvm use ruby-2.2.4@global
gem install rubocop
```

This also works for the case that you opened the issue. Right know I'm using this rubocop in a sublime project that uses ruby-2.4.0. If you work on multiple projects, and those depends on different versions of rubocop maybe this can still be an issue.

**Comment by LeEnno** [comment]
@cerdiogenes yeah, that's one way to get around this. Like I said I think it's weird to install a gem in 2 paces to make it work in Sublime. I used this solution anyway, but my coworker works on Ubuntu (I work on OS X) and it didn't work for him.

So I looked at the code and found a way to hack the correct path in the source file. I know it's not a good way to go either, but it fixes the actual problem. And if I had any clue of python I'd probably pull request the heck out of this.

In case anyone else stumbles upon this, here's what I did:
1. In packages folder (via menu item called `Browse Packages...`) open `SublimeLinter/lint/linter.py`.
2. Navigate to method `get_executable_version`, currently it's line `1672`.
3. The actual command that queries the version is `version = util.communicate(cmd, output_stream=util.STREAM_BOTH)`. Wrap it with your project root:

```python
with util.cd('/path/to/project/root'):
  version = util.communicate(cmd, output_stream=util.STREAM_BOTH)
```

This should do the trick, even though it may not survive updates of SublimeLinter Package.  
Anyone who's skilled enough and knows how to get the actual project root in this situation, please tell me, so I can fix this via a pull request.

**Comment by braver** [comment]
We have been making [many changes](https://github.com/SublimeLinter/SublimeLinter/blob/master/messages/4.0.0-rc.1.txt) to SublimeLinter, some of which also should have fixed this particular problem. It would be really nice if you could [try the beta](https://github.com/SublimeLinter/SublimeLinter/tree/15bb4a2e2024a623f60bb444eadd5790764fdfb9#sublimelinter-4-beta) and let us know if that fixes the problem for you.

**Comment by LeEnno** [comment]
I installed the beta, but it's still broken and I think it's even a little worse.

Just for clarification on the different ruby versions on my system to understand the log output:

- 2.0.0 ist the system ruby of OS X which should never be used by SublimeLinter.
- 2.2.4 is rvm's default ruby which should never be used by SublimeLinter.
- 2.3.1 is my project ruby, which should always be used by SublimeLinter.

Sublime Console:

```
SublimeLinter: debug mode: on 
SublimeLinter: temp directory: /var/folders/l2/j37t2cjs5ssgcgsrk1xyt1x40000gn/T/SublimeLinter3-Enno 
SublimeLinter: computed PATH using /bin/bash:
/Users/Enno/.rvm/gems/ruby-2.3.1/bin
/usr/bin
/bin
/usr/sbin
/sbin
 
SublimeLinter: ENV['GEM_HOME'] = '/Users/Enno/.rvm/gems/ruby-2.2.4' 
SublimeLinter: rubocop version query: /usr/bin/ruby -S rubocop --version 
SublimeLinter: rubocop version: 2.0.0 
SublimeLinter: rubocop: (>= 0.34.0) satisfied by 2.0.0 
Load settings: Open-Include
environment variables loaded using: /bin/bash -l
Emmet: No need to update PyV8
SublimeLinter: rubocop: gem ['/usr/bin/ruby', '-S', 'rubocop', '--format', 'emacs', '--force-exclusion', '--stdin', '/usr/bin/gem'] 
SublimeLinter: rubocop output:
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/dependency.rb:296:in `to_specs': Could not find 'rubocop' (>= 0.a) among 194 total gem(s) (Gem::LoadError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/dependency.rb:307:in `to_spec'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_gem.rb:47:in `gem'
	from /Users/Enno/.rvm/gems/ruby-2.3.1/bin/rubocop:22:in `<main>' 
SublimeLinter: No match for regex: ^.+?:(?P<line>\d+):(?P<col>\d+): (:?(?P<warning>[RCW])|(?P<error>[EF])): (?P<message>.+) 
SublimeLinter: No match for regex: ^.+?:(?P<line>\d+):(?P<col>\d+): (:?(?P<warning>[RCW])|(?P<error>[EF])): (?P<message>.+) 
SublimeLinter: No match for regex: ^.+?:(?P<line>\d+):(?P<col>\d+): (:?(?P<warning>[RCW])|(?P<error>[EF])): (?P<message>.+) 
SublimeLinter: No match for regex: ^.+?:(?P<line>\d+):(?P<col>\d+): (:?(?P<warning>[RCW])|(?P<error>[EF])): (?P<message>.+) 
```

The important parts:

- Old: Augmented path is still correct (`/Users/Enno/.rvm/gems/ruby-2.3.1/bin`).
- Old: `ENV['GEM_HOME']` is still wrong.
- New: Version query uses  `/usr/bin/ruby` (system ruby), although it should use `/Users/Enno/.rvm/rubies/ruby-2.3.1/bin/ruby` (project specific ruby).
- New: Version query now extracts `2.0.0` instead of `2.2.4`. This is due to a segmentation fault, that occurs while the version query is executed, and says (shortened):

```
/Users/Enno/.rvm/gems/ruby-2.3.1/gems/ruby-progressbar-1.9.0/lib/ruby-progressbar/refinements/enumerator.rb:4: warning: Refinements are experimental, and the behavior may change in future versions of Ruby!
/Users/Enno/.rvm/gems/ruby-2.3.1/gems/json-1.8.6/lib/json/ext/parser.bundle: [BUG] Segmentation fault
ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]
...
```

- My take: SublimeLinter somehow manages to speak to some gems in the right folder (shown by `ruby-2.3.1` in the path), but falsely extracts the `2.0.0` from the error output as the version number.
- Not new, but different: SublimeLinter still fails to execute the linter in the right context. It should have the project root as context. In older version it used the user directory (`~`) as context. In the beta it uses the system ruby as the context.
- New: Weird regex errors.

Hope this helps someway. If I need to clarify or test something else, please let me know.

**Comment by braver** [comment]
Thanks, seems clear enough. I think we may need to apply some serious scrubbing to the base ruby linter...

**Comment by braver** [comment]
fec7c79c8de14b9aa9d10cc78525bb0bff063f9a may have made an improvement here.

**Comment by LeEnno** [comment]
Thanks!

When opening Sublime with `.rb` file open:

```
SublimeLinter: PATH:
/usr/bin
/bin
/usr/sbin
/sbin
 
SublimeLinter: rubocop: shop_gallery_controller.rb ['/usr/bin/ruby', '-S', 'rubocop', '--format', 'emacs', '--force-exclusion', '--stdin', '/Users/Enno/Sites/pictrs/master/pictrs/app/controllers/shop_gallery_controller.rb'] 
environment variables loaded using: /bin/bash -l
SublimeLinter: rubocop output:
/usr/bin/ruby: No such file or directory -- rubocop (LoadError) 
SublimeLinter: No match for regex: ^.+?:(?P<line>\d+):(?P<col>\d+): (:?(?P<warning>[RCW])|(?P<error>[EF])): (?P<message>.+)
``` 

When opening Sublime with another file open and then opening a `.rb` file:

```
SublimeLinter: PATH:
/Users/Enno/.rvm/gems/ruby-2.2.4/bin
/Users/Enno/.rvm/gems/ruby-2.2.4@global/bin
/Users/Enno/.rvm/rubies/ruby-2.2.4/bin
/usr/local/bin
/usr/bin
/bin
/usr/sbin
/sbin
/Applications/VMware Fusion.app/Contents/Public
/Users/Enno/.rvm/bin
 
SublimeLinter: rubocop: shop_gallery_controller.rb ['/Users/Enno/.rvm/bin/rvm-auto-ruby', '-S', 'rubocop', '--format', 'emacs', '--force-exclusion', '--stdin', '/Users/Enno/Sites/pictrs/master/pictrs/app/controllers/shop_gallery_controller.rb'] 
SublimeLinter: rubocop output:
/Users/Enno/Sites/pictrs/master/pictrs/app/controllers/shop_gallery_controller.rb:1:1: C: Unnecessary utf-8 encoding comment.
...
/Users/Enno/Sites/pictrs/master/pictrs/app/controllers/shop_gallery_controller.rb:2023:11: C: Avoid more than 3 levels of block nesting.
/Users/Enno/Sites/pictrs/master/pictrs/.rubocop.yml: Style/MultilineOperationIndentation has the wrong namespace - should be Layout
/Users/Enno/Sites/pictrs/master/pictrs/.rubocop.yml: Style/SpaceBeforeBlockBraces has the wrong namespace - should be Layout 
SublimeLinter: No match for regex: ^.+?:(?P<line>\d+):(?P<col>\d+): (:?(?P<warning>[RCW])|(?P<error>[EF])): (?P<message>.+) 
SublimeLinter: No match for regex: ^.+?:(?P<line>\d+):(?P<col>\d+): (:?(?P<warning>[RCW])|(?P<error>[EF])): (?P<message>.+) 
```

This means:
- When opening Sublime with `.rb` file open, RVM paths will be ignored and linting fails.
- When opening Sublime and opening a `.rb` file later, RVM default paths will be recognized. Unfortunately not the RVM project path :(

**Comment by LeEnno** [comment]
I'm totally happy to help, but be prepared for even dumber answers.

> This should be okay e.g. before switching to (or into) a virtual environment. Yes?

I don't quite know the difference between normal and virtual environment because I'm a shell noob. What I do know: RVM's default paths (i.e. `/Users/Enno/.rvm/gems/ruby-2.2.4/bin`) get loaded as soon as I open Terminal/iTerm. This happens due to `/Users/Enno/.bash_profile` where RVM stuff gets loaded.  
Hopefully this answers your question.

> Honestly, how do you see here that it doesn't run the correct thing?

I assumed wrongly.  
I have a default ruby (2.2.4) and a different ruby (2.3.1) for my project (and also different corresponding gemsets). When checking the log I only see references for the default one (2.2.4):

```
SublimeLinter: Available variables: { 'Apple_PubSub_Socket_Render': '/private/tmp/com.apple.launchd.IjXa5eeLcp/Render',
  'GEM_HOME': '/Users/Enno/.rvm/gems/ruby-2.2.4',
  'GEM_PATH': '/Users/Enno/.rvm/gems/ruby-2.2.4:/Users/Enno/.rvm/gems/ruby-2.2.4@global',
  'HOME': '/Users/Enno',
  'IRBRC': '/Users/Enno/.rvm/rubies/ruby-2.2.4/.irbrc',
  'LOGNAME': 'Enno',
  'MY_RUBY_HOME': '/Users/Enno/.rvm/rubies/ruby-2.2.4',
  'PATH': '/Users/Enno/.rvm/gems/ruby-2.2.4/bin:/Users/Enno/.rvm/gems/ruby-2.2.4@global/bin:/Users/Enno/.rvm/rubies/ruby-2.2.4/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/VMware Fusion.app/Contents/Public:/Users/Enno/.rvm/bin',
  'RUBY_VERSION': 'ruby-2.2.4',
```

In the past I had to install `rubocop` in my default gemset to make SublimeLinter work (see the conversation in this issue). With the references to the wrong ruby I just assumed SublimeLinter took the wrong `rubocop`. After your comment I uninstalled `rubocop` in my default gemset and now SublimeLinter still gives the same output. This means SublimeLinter picks the correct rubocop now, I guess? 😱

> how does rvm-auto-ruby actually knows which ruby is correct. Must it be invoked from a special working dir?

I don't really know which magic it applies.  
I guess it takes the path which it was called from, looks for a `.ruby-version` or `.ruby-gemset` file ([further reading](https://rvm.io/workflow/projects#project-file-ruby-version)) and inspects them to find out which ruby to take. But that's just my guess. From my user directory (`cd ~ && rvm-auto-ruby -v`) it outputs `ruby 2.2.4p230 ...`. From my project directory (`cd ~/Sites/pictrs/master/pictrs && rvm-auto-ruby -v`) it outputs `ruby 2.3.1p112 ...`.

Did you read through the [actual code](https://github.com/rvm/rvm/blob/master/bin/rvm-auto-ruby) of rvm-auto-ruby? I have no clue in shell scripting so I don't really get what's going on there but maybe you do.

And regarding both of your links: the first one scares me (changing LaunchService databases to reference shell scripts in plist files?) and both of them confuse me (I don't have a performance problem and what do I even do with this .sublime-build thingy?). I'm afraid I can't help you without further assistance.

**Comment by kaste** [comment]
Yeah, sure that can be confusing. We log e.g. the GEM_PATH *before* `rvm-auto-ruby` mangles it. 

I close this for now

**Comment by LeEnno** [comment]
Ok, thx for your help.  
Is there an open issue for the startup problem which I can follow? As far as I can see that's the only thing keeping me from using the beta.

**Comment by kaste** [comment]
OTOH #863 should be the last one. 🙏
