### ISSUE TITLE
Problem to locate binaries if the default executable files can't be found in PATH

### ISSUE THREAD

**Issue by shulard** [SublimeLinter/SublimeLinter#455]
Hello !

I've encountered a tiny issue in the morning with the PHPCS checks.

Here my installation details: 
- ST3 Build 3113
- SublimeLinter: 3.7.4
- SublimeLinter-phpcs: 1.1.0

At load, I got this path details and the warning ... :

```
SublimeLinter: user shell: /bin/zsh 
SublimeLinter: computed PATH using /bin/zsh:
/usr/local/bin
/usr/bin
/bin
/usr/sbin
/sbin
/usr/local/MacGPG2/bin

SublimeLinter: WARNING: phpcs deactivated, cannot locate 'phpcs'
```

I created a specific project configuration :

``` json
{
    "folders":
    [
        {
            "path": "."
        }
    ],
    "SublimeLinter": {
        "linters": {
            "phpcs": {
                "@disable": false,
                "standard": "${project}/phpcs.xml",
                "cmd": "${project}/bin/phpcs"
            }
        }
    }
}
```

The `phpcs` binary exists in the `cmd` location but not as a default binary (`phpcs` is not available as an executable in my `$PATH`).

I never use the default `phpcs` binary location, do you think it's possible to use the defined `cmd` entry instead of the default one at plugin load ?

**Comment by FichteFoll** [comment]
There should probably be a general way to manually plug a linter's PATH before looking for the specified executable. That way it would work for all linters at once and phpcs wouldn't need their manual implementation with the cmd setting.

**Comment by shulard** [comment]
Yeah it would be a great improvement here, hope this will be heard 👍

**Comment by braver** [comment]
We have been making [many changes](https://github.com/SublimeLinter/SublimeLinter/blob/master/messages/4.0.0-rc.1.txt) to SublimeLinter, some of which also should have fixed this particular problem. It would be really nice if you could [try the beta](https://github.com/SublimeLinter/SublimeLinter/tree/15bb4a2e2024a623f60bb444eadd5790764fdfb9#sublimelinter-4-beta) and let us know if that fixes the problem for you.

**Comment by shulard** [comment]
Hello, 

I've just installed the beta version of SublimeLinter and made some tests.

To be able to use the `phpcs` linter with the project specific configuration, I've made some changes in the `SublimeLinter-phpcs` plugin. I don't know if it's an issue with the plugin directly but it seems that the `executable` property is checked before any project specific configuration...

I've the given sublime-project configuration file :

```
{
    "folders":
    [
        {
            "path": "."
        }
    ],
    "SublimeLinter": {
        "linters": {
            "phpcs": {
                "standard": "${project}/phpcs.xml",
                "cmd": "${project}/vendor/bin/phpcs"
            }
        }
    }
}
```

The executable exists in the specific `cmd` location. Also in the plugin linter the `executable` property is defined to : `phpcs` (global binary). This binary doesn't exists on my system. 

If I update the plugin and remove the `executable` property definition, it works like a charm. If the `executable` property is present, the `phpcs` linter is not ran against my file.

If you need more details please ask, maybe I missed an important thing in this explaination.

**Comment by kaste** [comment]
Okay, a bit group fighting is always good, haha, so the way *SublimeLinter-phpcs* is implemented is the actual reason why you have to have a globally installed executable here. 

If you set `executable` as a plugin author (of course bc of 🐛 s in SL3) you're damned to have a global executable in PATH. (There were ways to do this right even for SL3, but this is outdated, so why bother.)

So you could really try this: Remove the executable line. And in `self.cmd()` you don't have `cls.executable_path` anymore, just return a symbolic `['phpcs']` here instead. Now, SL4 should find a global 'phpcs' very lazy. And given your project settings, it shouldnt't at all, bc you don't need it and that's .. well ... lazy. 

If you could test this, send a PR and you get kudos or 💐

**Comment by shulard** [comment]
Hello,

Thank you for the detailed answer ! I'll check this asap and make a PR 😄.

**Comment by shulard** [comment]
I've just created the corresponding PR : SublimeLinter/SublimeLinter-phpcs#24
