### ISSUE TITLE
Sublime settings not available when initializing linter

### ISSUE THREAD

**Issue by josecanciani** [SublimeLinter/SublimeLinter#463]
I have a custom linter that uses the sublime module to get stuff like the package directory and a setting, in order to locate my command and send a setting value.

Recently (not sure how long, could be some months now), those settings are not enabled when I opened sublime for the first time (they are if I switch projects, but it's a pain to keep switching projects every time I start it).

Here's my code, I've commented what used to work and doesn't anymore, I had to hardcode the package path and I cannot send settings anymore:

``` python
from SublimeLinter.lint import Linter, util
import os
import sublime

class IatsPHP(Linter):
    syntax = ('php')
    # SublimeLinter bug? My original line was
    # cmd = (os.path.join(sublime.packages_path(), 'IATS', 'RESOURCE', 'runTests.sh'), 'yes' if sublime.load_settings('IATS.sublime-settings').get('useSandboxer') else 'no')
    cmd = (os.path.join(os.path.expanduser('~/.config/sublime-text-3/Packages'), 'IATS', 'RESOURCE', 'runTests.sh'))
    regex = (
        r'[0-9]+\) (?P<message>.*) in file .* at \[.* line (?P<line>[0-9]+)\]'
    )
```

I'm not sure if this is a SublimeLinter3 or a Sublime bug, or if I was doing something wrong. I tried using the exec instead of cmd (which I don't know how to use it, can't find samples either), and also overriding the get_cmd method, but couldn't make it work.

Any ideas?

Thanks,
Jose

**Comment by braver** [comment]
Do you still have this problem?

**Comment by kaste** [comment]
AFAIK you MUST not use functions on `sublime` (except a few one https://www.sublimetext.com/docs/3/api_reference.html#plugin_lifecycle) before `plugin_loaded` has been run. 

The code you're showing here runs at whatever time, when the module is imported or re-imported. 

If you want a dynamic `cmd`, you can just implement it as a method `def cmd(self): ...` and everything is fine. Unless you hit 🐛 s 😄

**Comment by josecanciani** [comment]
Thanks! I end up removing the use of Sublime Linter some months ago in my plugin since it was running wild, but if I try it again at some point I'll be sure to use a callback in the cmd argument.
