### ISSUE TITLE
New linter plugin: SublimeLinter-metadata-json-lint

### ISSUE THREAD

**Issue by byzent** [SublimeLinter/SublimeLinter#465]
Please review and test my linter plugin. It is a plugin to check the metadata on Puppet modules.

https://github.com/byzent/Sublimelinter-metadata-json-lint

**Comment by groteworld** [comment]
This project's name should/will be **`SublimeLinter-contrib-metadata-json-lint`**. The repo I guess doesn't have to follow that naming convention (but it should), and you will want to update it in the install message.

Your TravisCI hasn't been turned on yet, but really should be, to help you keep your code base clean and uniform.

After you have made those changes, please make a github release and I'll get you into Package Control.

**Comment by braver** [comment]
@byzent if you still want this added, please respond to the feedback.

**Comment by byzent** [comment]
@braver I totally forgot about this, I will look at it asap

**Comment by braver** [comment]
when you're ready please open a PR at https://github.com/SublimeLinter/package_control_channel
