### ISSUE TITLE
setting PYTHONPATH in sublimelinter

### ISSUE THREAD

**Issue by amrit-poudel** [SublimeLinter/SublimeLinter#473]
I tried setting "python_paths" variable in SublimeLinter.sublime-setting file  to point to wherever my python, pylint, setuptools, etc. packages are. However, this "python_paths" variable does not seem to work the way it should. It simply cannot augment my PYTHONPATH, unlike the "paths" variable which can augment my PATH.

I understand that I could set everything up in a .bash_profile/bashrc file. However, I would like to avoid using .bash_profile/.bashrc file for other reasons. I would like to be able to do this within SublimeLinter.sublime-setting file, because that is the whole point of having a "setting file" so that user can set PATH, PYTHONPATH, etc. without having to touch .bash_profile/.bashrc file.

Therefore, my question is: Is there a way to set PYTHONPATH variable, just like PATH variable, in SublimeLinter.sublime-setting file so that my PYTHONPATH is augmented ?

I am on OSX and using ST3 with python v 2.7.9 (not the system python).

Thanks for any help!

**Comment by amrit-poudel** [comment]
Anyone?

**Comment by amrit-poudel** [comment]
I tried exporting PYTHONPATH in my .bash_profile, sublime linter did not work in this case either.
I get the following warning message in the console:

SublimeLinter: pylint version query: /Users/amritpoudel/Desktop/HPC_LIB/PYTHON279/bin/python /Users/amritpoudel/Desktop/HPC_LIB/SPYDER/bin/pylint --version 
SublimeLinter: WARNING: no pylint version could be extracted from:
Traceback (most recent call last):
  File "/Users/amritpoudel/Desktop/HPC_LIB/SPYDER/bin/pylint", line 5, in <module>
    from pkg_resources import load_entry_point
ImportError: No module named pkg_resources

**Comment by ptim** [comment]
You've got a couple of options, as I understand it: 

- in your sublime project
- in a .sublimelinterrc file

I'm using a project, and have the following:

```
{
    "folders":
    [
        {
            "follow_symlinks": true,
            "path": "/Users/aparajita/Projects/Widget"
        }
    ],
    "SublimeLinter":
    {
        "@python": 3
    }
}
```
as documented here: http://sublimelinter.readthedocs.io/en/latest/meta_settings.html#python-meta-setting

I'm using [sublimelinter-flake8](https://github.com/SublimeLinter/SublimeLinter-flake8) so I also needed to ensure that flake8 was installed globally using both pip and pip3

```
# For python 2.x
[sudo] pip-2.x install flake8

# For python 3.x
[sudo] pip-3.x install flake8
```

hth!

**Comment by amrit-poudel** [comment]
hi,

Thanks for taking your time to answer my question.  I followed your suggestion, but could not make it to work. 

Since I do not have "project", I worked directly with .sublimelinterrc file.

First of all, I want to make it crystal clear that I have installed both Sublimelinter plugin AND actual python packages like pylint, pyflakes and pep8.  I am currently using python v 2.7.9.

These packages are *not installed* in the standard location like /usr/local or /usr/opt etc for very simple reason, that is, I do not have access to those folders!


The  .sublimelinterrc files looks like this:

{
    "@python": 2,
    "linters": {
        "pep8": {
            "@disable": false,
            "args": [],
            "excludes": [],
            "ignore": "",
            "max-line-length": null,
            "select": "",
            "paths": ["/Users/amritpoudel/Desktop/HPC_LIB/SPYDER/lib/python2.7/site-packages"]
        },
        "pyflakes": {
            "@disable": false,
            "args": [],
            "excludes": [],
            "paths": ["/Users/amritpoudel/Desktop/HPC_LIB/SPYDER/lib/python2.7/site-packages"]
        },
        "pylint": {
            "@disable": true,
            "args": [],
            "disable": "",
            "enable": "",
            "excludes": [],
            "rcfile": "",
            "show-codes": false,
            "paths": ["/Users/amritpoudel/Desktop/HPC_LIB/SPYDER/lib/python2.7/site-packages"]
        }
    }
}



However, I get  the exact same error as above in the sublime console.


SublimeLinter: find_python(version=None, script='pep8', module=None) 
SublimeLinter: find_python: default python = /Users/amritpoudel/Desktop/HPC_LIB/PYTHON279/bin/python 
SublimeLinter: find_python: available version = {'minor': 7, 'major': 2} 
SublimeLinter: find_python: 'pep8' path = /Users/amritpoudel/Desktop/HPC_LIB/SPYDER/bin/pep8 
SublimeLinter: find_python: <= ('/Users/amritpoudel/Desktop/HPC_LIB/PYTHON279/bin/python', '/Users/amritpoudel/Desktop/HPC_LIB/SPYDER/bin/pep8', 2, 7) 
SublimeLinter: pep8 version query: /Users/amritpoudel/Desktop/HPC_LIB/PYTHON279/bin/python /Users/amritpoudel/Desktop/HPC_LIB/SPYDER/bin/pep8 --version 
SublimeLinter: pep8 version: 1.7.0 
SublimeLinter: pep8: (>= 1.4.6) satisfied by 1.7.0 
SublimeLinter: pep8 activated: ('/Users/amritpoudel/Desktop/HPC_LIB/PYTHON279/bin/python', '/Users/amritpoudel/Desktop/HPC_LIB/SPYDER/bin/pep8') 
SublimeLinter: find_python(version=None, script='pyflakes', module=None) 
SublimeLinter: find_python: default python = /Users/amritpoudel/Desktop/HPC_LIB/PYTHON279/bin/python 
SublimeLinter: find_python: available version = {'minor': 7, 'major': 2} 
SublimeLinter: find_python: 'pyflakes' path = /Users/amritpoudel/Desktop/HPC_LIB/SPYDER/bin/pyflakes 
SublimeLinter: find_python: <= ('/Users/amritpoudel/Desktop/HPC_LIB/PYTHON279/bin/python', '/Users/amritpoudel/Desktop/HPC_LIB/SPYDER/bin/pyflakes', 2, 7) 
SublimeLinter: pyflakes version query: /Users/amritpoudel/Desktop/HPC_LIB/PYTHON279/bin/python /Users/amritpoudel/Desktop/HPC_LIB/SPYDER/bin/pyflakes --version 
SublimeLinter: pyflakes version: 1.0.0 
SublimeLinter: pyflakes: (>= 0.7.3) satisfied by 1.0.0 
SublimeLinter: pyflakes activated: ('/Users/amritpoudel/Desktop/HPC_LIB/PYTHON279/bin/python', '/Users/amritpoudel/Desktop/HPC_LIB/SPYDER/bin/pyflakes') 
SublimeLinter: find_python(version=None, script='pylint', module=None) 
SublimeLinter: find_python: default python = /Users/amritpoudel/Desktop/HPC_LIB/PYTHON279/bin/python 
SublimeLinter: find_python: available version = {'minor': 7, 'major': 2} 
SublimeLinter: find_python: 'pylint' path = /Users/amritpoudel/Desktop/HPC_LIB/SPYDER/bin/pylint 
SublimeLinter: find_python: <= ('/Users/amritpoudel/Desktop/HPC_LIB/PYTHON279/bin/python', '/Users/amritpoudel/Desktop/HPC_LIB/SPYDER/bin/pylint', 2, 7) 
SublimeLinter: pylint version query: /Users/amritpoudel/Desktop/HPC_LIB/PYTHON279/bin/python /Users/amritpoudel/Desktop/HPC_LIB/SPYDER/bin/pylint --version 
SublimeLinter: WARNING: no pylint version could be extracted from:
Traceback (most recent call last):
  File "/Users/amritpoudel/Desktop/HPC_LIB/SPYDER/bin/pylint", line 5, in <module>
    from pkg_resources import load_entry_point
  File "build/bdist.macosx-10.4-x86_64/egg/pkg_resources/__init__.py", line 2927, in <module>
  File "build/bdist.macosx-10.4-x86_64/egg/pkg_resources/__init__.py", line 2913, in _call_aside
  File "build/bdist.macosx-10.4-x86_64/egg/pkg_resources/__init__.py", line 2940, in _initialize_master_working_set
  File "build/bdist.macosx-10.4-x86_64/egg/pkg_resources/__init__.py", line 635, in _build_master
  File "build/bdist.macosx-10.4-x86_64/egg/pkg_resources/__init__.py", line 943, in require
  File "build/bdist.macosx-10.4-x86_64/egg/pkg_resources/__init__.py", line 829, in resolve
pkg_resources.DistributionNotFound: The 'pylint==1.4.4' distribution was not found and is required by the application
 
SublimeLinter: find_python(version='2', script='pep8', module=None) 
SublimeLinter: find_python: requested version = {'minor': None, 'major': 2} 
SublimeLinter: find_python: system python = /Users/amritpoudel/Desktop/HPC_LIB/PYTHON279/bin/python2 
SublimeLinter: find_python: available version = {'minor': 7, 'major': 2} 
SublimeLinter: find_python: 'pep8' path = /Users/amritpoudel/Desktop/HPC_LIB/SPYDER/bin/pep8 
SublimeLinter: find_python: <= ('/Users/amritpoudel/Desktop/HPC_LIB/PYTHON279/bin/python2', '/Users/amritpoudel/Desktop/HPC_LIB/SPYDER/bin/pep8', 2, 7) 
SublimeLinter: pep8: Script_QuantumTransport_Polariton_ManyBody.py ['/Users/amritpoudel/Desktop/HPC_LIB/PYTHON279/bin/python2', '/Users/amritpoudel/Desktop/HPC_LIB/SPYDER/bin/pep8', '-'] 
SublimeLinter: pep8 output:
Traceback (most recent call last):
  File "/Users/amritpoudel/Desktop/HPC_LIB/SPYDER/bin/pep8", line 5, in <module>
    from pkg_resources import load_entry_point
  File "build/bdist.macosx-10.4-x86_64/egg/pkg_resources/__init__.py", line 2927, in <module>
  File "build/bdist.macosx-10.4-x86_64/egg/pkg_resources/__init__.py", line 2913, in _call_aside
  File "build/bdist.macosx-10.4-x86_64/egg/pkg_resources/__init__.py", line 2940, in _initialize_master_working_set
  File "build/bdist.macosx-10.4-x86_64/egg/pkg_resources/__init__.py", line 635, in _build_master
  File "build/bdist.macosx-10.4-x86_64/egg/pkg_resources/__init__.py", line 943, in require
  File "build/bdist.macosx-10.4-x86_64/egg/pkg_resources/__init__.py", line 829, in resolve
pkg_resources.DistributionNotFound: The 'pep8==1.7.0' distribution was not found and is required by the application 
SublimeLinter: find_python(version='2', script='pyflakes', module=None) 
SublimeLinter: find_python: requested version = {'minor': None, 'major': 2} 
SublimeLinter: find_python: system python = /Users/amritpoudel/Desktop/HPC_LIB/PYTHON279/bin/python2 
SublimeLinter: find_python: available version = {'minor': 7, 'major': 2} 
SublimeLinter: find_python: 'pyflakes' path = /Users/amritpoudel/Desktop/HPC_LIB/SPYDER/bin/pyflakes 
SublimeLinter: find_python: <= ('/Users/amritpoudel/Desktop/HPC_LIB/PYTHON279/bin/python2', '/Users/amritpoudel/Desktop/HPC_LIB/SPYDER/bin/pyflakes', 2, 7) 
SublimeLinter: pyflakes: Script_QuantumTransport_Polariton_ManyBody.py ['/Users/amritpoudel/Desktop/HPC_LIB/PYTHON279/bin/python2', '/Users/amritpoudel/Desktop/HPC_LIB/SPYDER/bin/pyflakes'] 
SublimeLinter: pyflakes output:
Traceback (most recent call last):
  File "/Users/amritpoudel/Desktop/HPC_LIB/SPYDER/bin/pyflakes", line 5, in <module>
    from pkg_resources import load_entry_point
  File "build/bdist.macosx-10.4-x86_64/egg/pkg_resources/__init__.py", line 2927, in <module>
  File "build/bdist.macosx-10.4-x86_64/egg/pkg_resources/__init__.py", line 2913, in _call_aside
  File "build/bdist.macosx-10.4-x86_64/egg/pkg_resources/__init__.py", line 2940, in _initialize_master_working_set
  File "build/bdist.macosx-10.4-x86_64/egg/pkg_resources/__init__.py", line 635, in _build_master
  File "build/bdist.macosx-10.4-x86_64/egg/pkg_resources/__init__.py", line 943, in require
  File "build/bdist.macosx-10.4-x86_64/egg/pkg_resources/__init__.py", line 829, in resolve
pkg_resources.DistributionNotFound: The 'pyflakes==1.0.0' distribution was not found and is required by the application 
Package Control: Skipping automatic upgrade, last run at 2016-08-23 09:31:33, next run at 2016-08-23 10:31:33 or after



Clearly, the above error is thrown due to the fact that PYTHONPATH is not set or read correctly by the sublimelinter. 

Also, note that I have set PATH  (path that locate the binaries of pylint, pyflakes, and pep8) correctly and is read correctly by sublimelinter. However, I am unable to set PYTHONPATH.



I will appreciate any other suggestions. Thanks!

**Comment by amrit-poudel** [comment]
Also, I noticed that these is a missing information on this page: http://sublimelinter.readthedocs.io/en/latest/troubleshooting.html#linters-python-is-not-available)

Under the section "module not installed", it is implied that the type of error thrown there is indicative of flake8 package being not installed. While this true statement, but not a complete one.
A simple test can demonstrate that the same error is thrown if flake8 package is installed but the PYTHONPATH is not set or read by Sublimelinter. The author seem to focus heavily on how to set and augment the PATH, but there is no information on that page on how to augment the PYTHONPATH.


Module not installed
On the other hand, if python2 is available and you have a @python: 2 meta or inline setting, but you do not have flake8 installed for python 2, you would see something like this in the console:

SublimeLinter: flake8: test.py ['/usr/bin/python2', '/usr/local/bin/flake8', '--max-complexity=-1', '-']
SublimeLinter: flake8 output:
Traceback (most recent call last):
  File "/usr/local/bin/flake8", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 2556, in <module>
    working_set.require(__requires__)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 620, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 518, in resolve
    raise DistributionNotFound(req)  # XXX put more info here
pkg_resources.DistributionNotFound: flake8==2.1.0

**Comment by braver** [comment]
We have been making [many changes](https://github.com/SublimeLinter/SublimeLinter/blob/master/messages/4.0.0-rc.1.txt) to SublimeLinter, some of which also should have fixed this particular problem. It would be really nice if you could [try the beta](https://github.com/SublimeLinter/SublimeLinter/tree/15bb4a2e2024a623f60bb444eadd5790764fdfb9#sublimelinter-4-beta) and let us know if that fixes the problem for you.

**Comment by kaste** [comment]
This has been addressed for SL4. The tracebacks are not useful. If we have bugs, we need new ones. Closing.
