### ISSUE TITLE
JSON5 support

### ISSUE THREAD

**Issue by mathieumg** [SublimeLinter/SublimeLinter#476]
I've been using SublimeLinter with SublimeLinter-eslint for a while and really enjoying it. I currently use the global `eslint` executable approach, but I'm trying to migrate to the local executable approach. Among the reasons for that is that there are more and more ESLint plugins getting added to my configuration and I need to install them all globally. The main reason, however, is that different projects can be using different (and possibly incompatible) versions of ESLint and ESLint plugins and that cannot work with the global approach.

It is my understanding that this can already happen automatically if SublimeLinter locates a `package.json` file in a folder, is that correct? [This line](https://github.com/SublimeLinter/SublimeLinter3/blob/3f2973811f1fbb38568677be7be7bfbe77f7f4f4/lint/node_linter.py#L155) seems to indicate so.

If so, the only obstacle preventing me from migrating to the local approach would be the fact that I use [JSON5](http://json5.org/) and a `package.json5` through [`npm-json5`](https://github.com/wiredmax/npm-json5) rather than the conventional `package.json` to get trailing commas and JSON comments. Would you be open for a PR that modifies the lookup above by also looking for a `package.json5`? If so, I imagine you would rather the `package.json5` lookup occurs after the `package.json` lookup fails to find a file, for each directory level.

Thank you!

**Comment by braver** [comment]
Yeah, this is "won't fix", we need to focus on what's important to everyone. Also json5 and its npm fork seem to be pretty dead.

**Comment by mathieumg** [comment]
`npm-json5` wildcard-installs npm because it just mocks the filesystem read function, but noted!
