### ISSUE TITLE
When the linter is running, it reports "No lint errors."

### ISSUE THREAD

**Issue by fritz-c** [SublimeLinter/SublimeLinter#481]
On large files with errors, while the linter is still running (in my case, following a save), if I use the shortcut key to go to the next lint error, it shows the message "No lint errors." at the bottom. A message like "Checking for errors..." might be more useful and less misleading.

I think this stems from the issue that there's no clear way to know when linting has started or finished when the file has no errors.

**Comment by braver** [comment]
SublimeLinter4 includes a "busy linting" indicator in the statusbar. You can [try the beta](https://github.com/SublimeLinter/SublimeLinter/tree/15bb4a2e2024a623f60bb444eadd5790764fdfb9#sublimelinter-4-beta) if you want.
