### ISSUE TITLE
Disable for large files

### ISSUE THREAD

**Issue by fritz-c** [SublimeLinter/SublimeLinter#482]
When SublimeLinter runs on large files (e.g., bundled code), it can significantly slow down Sublime Text, sometimes to the point that it becomes unresponsive. As a safety measure, some plugins such as [TrailingSpaces account for this](https://github.com/SublimeText/TrailingSpaces#disabled-for-large-files) and disable themselves for large files.

Would it be possible to implement a similar setting?

**Comment by braver** [comment]
We have been making [many changes](https://github.com/SublimeLinter/SublimeLinter/blob/master/messages/4.0.0-rc.1.txt) to SublimeLinter, including performance improvements that should prevent it from blocking anything. It would be really nice if you could [try the beta](https://github.com/SublimeLinter/SublimeLinter/tree/15bb4a2e2024a623f60bb444eadd5790764fdfb9#sublimelinter-4-beta) and let us know if that fixes the problem for you.

**Comment by kaste** [comment]
No plan to implement this ATM. Needs for user feed back.

**Comment by arkin-** [comment]
This is still an issue as of v4.0.6.

Large files are crashing sublime, and this didn't happen previously until a javascript linter was installed for use with this plugin.

**Comment by kaste** [comment]
Moar info please.

**Comment by arkin-** [comment]
What kind of info would you like @kaste ?

I am running Mac OS X 10.13.3 on 3.2 Ghz quad core, eslint version 4.5.0, SublimeLinter version 4.0.6. The file in question is 192 lines and 158K, it is a few jQuery scripts concatenated into one - nothing too complicated. I had actually thought this file was larger.

Is there any way to debug the cause of the slow down? To provide more detail.

**Comment by kaste** [comment]
Slow down or crash is not the same thing. Also, you can have 150k with 3 errors or 1000 lint problems.

**Comment by arkin-** [comment]
Well, it is a bit of both occurring here for me.

> What kind of info would you like @kaste ?

**Comment by kaste** [comment]
I usually exclude my dist or build directory.

**Comment by kaste** [comment]
Well I still think we don't have a problem with large files. We probably have a problem with lots of errors.

**Comment by braver** [comment]
Sublime Text itself at some point keels over too. Long lines, e.g. minified files, etc. like stuffing 158k into only 192 lines, are usually the culprit.

**Comment by FichteFoll** [comment]
St certainly doesn't like too many added regions. wbond mentioned that the feature wasn't really built to handle hundreds of them at once (or less, idr), so having many errors and trying to mark them in the view can turn out to be detrimental. I think having a soft limit for lint messages to mark would be useful. Not sure if it needs to be configurable.

The idea would be to just not add any regions when there are too many lint problems and just show the total count in the status bar and individual errors in the panel.

**Comment by arkin-** [comment]
Sure, I still see it as an issue because these files can be opened, and are linted. Another file I'm having issues with is a routing file which had incorrect indentation over a hundred or so lines - it caused a huge slow down.

What about allowing configuration of the eslint cli option `--max-warnings` - would this help?

**Comment by FichteFoll** [comment]
No, that option is only for eslint's exit code and it will be non-zero if there are more than "max warnings" warnings.
