### ISSUE TITLE
Prevent scrolling to error

### ISSUE THREAD

**Issue by Stanzilla** [SublimeLinter/SublimeLinter#489]
Is there any setting/way (I can't find it in the docs) that prevents the editor from scrolling the bug into view? Like I forgot an `end` somewhere and therefore it errors at EOF and scrolls down to the bottom of the file.

**Comment by braver** [comment]
SublimeLinter4 will never scroll to anything if you don't ask it to. You can [try the beta](https://github.com/SublimeLinter/SublimeLinter/tree/15bb4a2e2024a623f60bb444eadd5790764fdfb9#sublimelinter-4-beta) if you want.
