### ISSUE TITLE
Trying to create AHK linter, but it doesn't work; no console messages; how should I debug this?

### ISSUE THREAD

**Issue by Cerberus-tm** [SublimeLinter/SublimeLinter#492]
If I ask in the wrong place, I apologize! I'm rather desperate. I've created the stub of an Autohotkey linter (ahklint.exe). It **works fine when I try it on a test file in a terminal** using this Python code:

```
python
from subprocess import Popen, PIPE, STDOUT
command = r'ahklint d:\downloads\test.ahk |more'
output = Popen(command, shell=True, stderr=STDOUT, stdout=PIPE)
errors = output.communicate()[0], output.returncode
print(errors)
```

This is the result in terminal, which is as desired and properly matched by the regex:

```
(b"Line: 12, Column: 3; If table = computer[1] ; {expressionless-if} the conditio
n after 'if' is not an expression, which might lead to confusion; enclose the co
ndition in brackets to avoid this.\r\n14: This hotstring does not use a ending c
haracter trigger. If '#Hotstring *0' is not specified, there is a risk of confli
cting hotstrings.\r\n\r\n", 0)
```

I've created a plugin for SublimeLinter, but **it doesn't do anything** (doesn't mark the error above in my test file in SublimeText). I've turned on "Debug" in SublimeLinter, but the **console shows no problems** at all (only things like "ahklint loaded"). Other linters work fine in my Sublimetext, like Eslint, Pydocstyle, and Flake8.

I know very little about coding and nothing at all about Python, alas, so I'm probably making many elementary mistakes. Could anyone give me a nudge as to **how I should debug this**? My linter.py:

```
"""This module exports the Ahklint plugin class."""

from SublimeLinter.lint import Linter, util
from subprocess import Popen, PIPE, STDOUT


class Ahklint(Linter):
    """Provides an interface to ahklint."""

    syntax = 'AutoHotkey'
    # cmd = '"ahklint" "@" |more'
    # cmd = 'ahklint d:\downloads\@ |more'
    # cmd = 'ahklint.exe', '@', '|more' #none of these work
    cmd = None
    version_args = '--version'
    version_re = r'(?P<version>\d+\.\d+\.\d+)'
    version_requirement = '>= 1.0'
    regex = r'^.{,3}Line: (?P<line>\d+), Column: (?P<col>\d+);(?P<error>[^;]+);(?P<message>[^\n]+)(?:\r?\n|$)'
    multiline = True
    line_col_base = (1, 1)
    tempfile_suffix = 'ahk'
    error_stream = util.STREAM_BOTH
    selectors = {}
    word_re = None
    defaults = {}
    inline_settings = None
    inline_overrides = None
    comment_re = r'\s;'

    def run(self):
        """Run the linter on the file and return its output."""
        command = r'ahklint d:\downloads\test.ahk |more'
        output = Popen(command, shell=True, stderr=STDOUT, stdout=PIPE)
        errors = output.communicate()[0], output.returncode
        #print(errors)
        return errors

```

When I uncomment the "print(errors)" line in the run() function above, that does not result in any information in the console. But when I put a print somewhere before the run() function, that does show up in the console.

**Comment by braver** [comment]
Err... Do you still need help with this?

**Comment by Cerberus-tm** [comment]
@braver Hello! Actually, I haven't made any progress. But I'm a total layman, and Sublime Linter is like a big black box to me. I had no idea whether this was the right place to ask for help, and won't blame anyone for closing this question...

The odd thing is that I can get the right output from my ahklint.exe to be printed to the Sublime Linter console, by putting this at the beginning of my linter.py file, as a test:
`from SublimeLinter.lint import Linter, util

from subprocess import Popen, PIPE, STDOUT
command = 'ahklint d:\\downloads\\test.ahk |more'
output = Popen(command, shell=True, stderr=STDOUT, stdout=PIPE)
errors = output.communicate()[0], output.returncode
print(errors)`

But, when I put that very same code inside the `def run(self, edit):` part, the console shows nothing, not even when I switch to a tab with an AutoHotkey file to edit. So when the `def run` part can't even print anything to the console, it seems like it's never executed.

When I put `cmd = 'ahklint d:\\downloads\\@ |more'` inside the class definition (instead of `cmd = None`), and comment out the entire `def run` part, still nothing happens. But I just have no idea how it all works, I'm just trying things.

**Comment by FichteFoll** [comment]
Try this:

```py
"""This module exports the Ahklint plugin class."""

from SublimeLinter.lint import Linter, util


class Ahklint(Linter):
    """Provides an interface to ahklint."""

    syntax = 'AutoHotkey'
    cmd = "ahklint"
    # version_args = '--version'
    # version_re = r'(?P<version>\d+\.\d+\.\d+)'
    # version_requirement = '>= 1.0'
    regex = r'^.{,3}Line: (?P<line>\d+), Column: (?P<col>\d+);(?P<error>[^;]+);(?P<message>[^\n]+)'
    line_col_base = (1, 1)
    tempfile_suffix = 'ahk'
    error_stream = util.STREAM_BOTH
    defaults = {}
    comment_re = r'\s;'
```

**Comment by Cerberus-tm** [comment]
@FichteFoll Wow!! That you so much, that did the trick! In addition, I had to change `AutoHotkey` to lower case `autohotkey` (an old mistake of mine), but then your script worked! Apparently, there were so many things wrong with my version that I couldn't find out what. By eliminating all of my other problems, your code made it work! I've never been happier in my life—well, at least not since August 2016, when I posted this 'issue'. Now I can finally get work and develop a linter for Autohotkey! Perhaps one day you'll have Autohotkey users as your fans everywhere.

**Comment by braver** [comment]
Mooi!

Let’s close this then?

**Comment by Cerberus-tm** [comment]
@braver Gedaan! (In case you want the honour of closing the last "questions & setup" issue, by all means reopen en reclose it...)

**Comment by Cerberus-tm** [comment]
I trust that made you feel good.

**Comment by braver** [comment]
💪 Awesome 😄 Thanks for the opportunity.
