### ISSUE TITLE
Setting to set environment variables for linters

### ISSUE THREAD

**Issue by Herst** [SublimeLinter/SublimeLinter#507]
For example for `mypy` I would need to set the `MYPYPATH` environment variable.

**Comment by braver** [comment]
We have been making [many changes](https://github.com/SublimeLinter/SublimeLinter/blob/master/messages/4.0.0-rc.1.txt) to SublimeLinter, some of which also should have fixed this particular problem. It would be really nice if you could [try the beta](https://github.com/SublimeLinter/SublimeLinter/tree/15bb4a2e2024a623f60bb444eadd5790764fdfb9#sublimelinter-4-beta) and let us know if that fixes the problem for you.

**Comment by FichteFoll** [comment]
I think I can still see use cases for this in the general sense, much like `executable` should be overridable.

**Comment by braver** [comment]
So, in most cases the linter would, in SL4, get the env vars automatically, but if you’re explicitly setting the executable it won’t? That makes sense. Working with SL in such a setup seems like a pain in the *** to me, is it even a worthwhile per suit at that point?

**Comment by kaste** [comment]
I think that is a good addition. This could be useful for `ruby` and `mypy`. In general, you wouldn't need to prepare the environment before starting sublime. No? 

It would be saved in the project file, and thus multiple windows/projects would work potentially with different, enhanced env settings in parallel. Isn't this just great? Did I miss something here. Too happy?

**Comment by kaste** [comment]
You could even override the `PATH`, no?

**Comment by braver** [comment]
If I’m right, the command line equivalent would be to set the vars and call the executable in one go. If the executable depends on PATH you can override that too, but you can’t override the PATH and then use it to find the executable. But I’d say if you’re taking control like this you would also call the executable directly and not via PATH.

**Comment by kaste** [comment]
If we overwrite the PATH, we don't need to find an executable bc the os does that for us. No?

**Comment by braver** [comment]
> If we overwrite the PATH, we don't need to find an executable bc the os does that for us. No?

You're guess is at least as good as mine here 🤷‍♂️
