### ISSUE TITLE
chdir not working

### ISSUE THREAD

**Issue by Yevs** [SublimeLinter/SublimeLinter#515]
I have setup a simple project with following structure:
```
folder
  shouldbelinted.js
shouldnotbelinted.js
.eslintrc.js
project.sublime_project
```
with following contents of `project.sublime_project`:
```
{
    "folders":
    [
        {
            "path": "."
        }
    ],
    "SublimeLinter":
    {
        "linters":
        {
            "eslint":
            {
                "chdir": "${project}/folder"
            }
        }
    }
}
```
According to [docs](http://www.sublimelinter.com/en/latest/linter_settings.html#chdir) only files in `folder/` must be linted, but for some reason `shouldnotbelinted.js` also gets linted.

**Comment by kaste** [comment]
This is not a bug. To exclude files you must set `excludes`.

**Comment by FichteFoll** [comment]
Is `chdir` implemented by SL core or by the eslint linter?

**Comment by kaste** [comment]
Core, I thought.

**Comment by braver** [comment]
Oh, yeah, now that I read the docs, I don’t think that’s what you use chdir for and I wouldn’t expect that to work.
