### ISSUE TITLE
Broadcast an event when linting has finsihed

### ISSUE THREAD

**Issue by kaste** [SublimeLinter/SublimeLinter#541]
I suggest you emit an event whenever SublimeLinter has finished linting a view. A user can listen to these events and react e.g. by annotating the view, showing phantoms etc. A showcase plugin can be found [here](https://github.com/kaste/SublimeLinter-Annotations). This plugin monkeypatches `SublimeLinter.highlight` which I found to be a good first candidate to send these events. [See the simple patch.](https://github.com/kaste/SublimeLinter-Annotations/blob/master/monkeypatch_sublimelinter.py)

Following this way, the builtin 'views' (regions marker, status bar updater), could be decoupled from SublimeLinter. In the long run.

[See a simple tooltip 'viewer'.](https://github.com/kaste/SublimeLinter-Annotations/blob/master/show_tooltips.py)

**Comment by braver** [comment]
I'm not sure about the "why" here? To separate the front-end/UI from the running of the linters? What does that accomplish?

**Comment by kaste** [comment]
I have actually three separate view plugins running with this monkeypatch system. I have custom phantoms, tooltips, and a patched status bar indicator. 

The question was how I could actually hook into SublimeLinter, and unless I'm wrong or everything changed since then, there was no official way to write custom "views". Then the first request would be, you provide such a hook, and `WindowCommand` is the best you can do here IMO.

But of course, you could use such a hook internally as well. Back in Feb the actual data model was not ready before `highlight` for which the name suggests it is actually a view function. So naturally, as a system grows and evolves, you can always factor things differently and choose to decouple more. I think it would be great if we would just install view plugins on top of SublimeLinter, a bit more competition helps. If I remember correctly, at the time I wrote my phantoms view, SublimeLinter actually had none to offer.

**Comment by kaste** [comment]
PS Does SublimeLinter actually show phantom/inline annotations? 😟

**Comment by braver** [comment]
> Does SublimeLinter actually show phantom/inline annotations?

No, although they sound nice for linting, they're actually super annoying in practice. In combination with a command that is run manually it might be useful, but we're working on some other stuff first.

**Comment by kaste** [comment]
I've not told you to do that, okay? I have already written a phantoms view. 

![image](https://user-images.githubusercontent.com/8558/33223834-c510c186-d163-11e7-8528-c3e19094c5a2.png)

I also colorize the complete status bar on hard errors. (Some Linters have a good separation of what is a warning and what is actually an error.)

![image](https://user-images.githubusercontent.com/8558/33223870-3db1d058-d164-11e7-9f6c-9effd9718e42.png)

I just think users should be able to that.

**Comment by braver** [comment]
@kaste I think you tackled this one now right?

**Comment by kaste** [comment]
Yep.
