### ISSUE TITLE
Custom gutter icons: colorize warnings and errors differently

### ISSUE THREAD

**Issue by Kristinita** [SublimeLinter/SublimeLinter#544]
### 1. Request

It would be nice, if in SublimeLinter will be possible make different colors, if user use not default gutter theme.

For example, I use [**Blueberry — round**](https://sublimelinter.readthedocs.io/en/latest/gutter_themes.html#standard-gutter-themes) gutter theme. I add in my color scheme file:

```xml
<dict>
    <key>name</key>
    <string>SublimeLinter: Gutter Mark</string>
    <key>scope</key>
    <string>sublimelinter.gutter-mark</string>
    <key>settings</key>
    <dict>
        <key>foreground</key>
        <string>green</string>
    </dict>
</dict>
```

I get result:

![Actual](http://i.imgur.com/bG8RbtY.png)

Warnings and errors now green.

### 2. Justification

1. Easy distinguish warnings and errors.
2. More customization — is good.

### 3. Desirable behavior

I add in my color scheme file:

```xml
<dict>
    <key>name</key>
    <string>SublimeLinter: Gutter Mark</string>
    <key>scope</key>
    <string>sublimelinter.gutter-mark.error</string>
    <key>settings</key>
    <dict>
        <key>foreground</key>
        <string>red</string>
    </dict>
</dict>
<dict>
    <key>name</key>
    <string>SublimeLinter: Gutter Mark</string>
    <key>scope</key>
    <string>sublimelinter.gutter-mark.warning</string>
    <key>settings</key>
    <dict>
        <key>foreground</key>
        <string>orange</string>
    </dict>
</dict>
```

I get result:

![Expected](http://i.imgur.com/xa34tWr.png)

Thanks.

**Comment by braver** [comment]
We have been making [many changes](https://github.com/SublimeLinter/SublimeLinter/blob/master/messages/4.0.0-rc.1.txt) to SublimeLinter, and it includes this feature. You can [try the beta](https://github.com/SublimeLinter/SublimeLinter/tree/15bb4a2e2024a623f60bb444eadd5790764fdfb9#sublimelinter-4-beta) if you want.
