### ISSUE TITLE
cmd HOME directory is not expanded causing error

### ISSUE THREAD

**Issue by gerardroche** [SublimeLinter/SublimeLinter#556]
Example

```
{
    "user": {
            "php": {
                "@disable": false,
                "cmd": "~/.phpenv/versions/7.x/bin/php",
                "args": [],
                "excludes": []
            }
    }
}
```

## Expected

`~/` to be expanded to my HOME directory and cmd executable to work.

## Actual

Error

```
SublimeLinter: ERROR: could not launch ['~/.phpenv/versions/7.x/bin/php', '-l', '-d', 'display_errors=On', '-d', 'log_errors=Off'] 
SublimeLinter: reason: [Errno 2] No such file or directory: '~/.phpenv/versions/7.x/bin/php' 
SublimeLinter: PATH: ... 
```

Changing the path to an absolute path works.

My workaround is to set the paths:

        "paths": {
            "linux": [
                "~/.phpenv/versions/7.x/bin"
            ],
            "osx": [],
            "windows": []
        },

**Comment by SaintDako** [comment]
I'm not sure if `~` will be supported, but try using `$HOME` (assuming it's set, which I think it always is? At least on OS X, in my experience).

**Comment by gerardroche** [comment]
`$HOME` is not supported.

**Comment by kaste** [comment]
For SL3, it is actually `${home}` (plus 🐛 s), but there are still moving parts here for SL4.

**Comment by FichteFoll** [comment]
If my proposal goes through, both `~` and `$HOME` will be supported (with `${home}` going away).

**Comment by kaste** [comment]
The PR we're working on for SL4 is https://github.com/SublimeLinter/SublimeLinter/pull/825

These are the moving parts 😄
