### ISSUE TITLE
@python meta setting documentation doesn't reflect #504

### ISSUE THREAD

**Issue by posita** [SublimeLinter/SublimeLinter#572]
#504 added support for identifying a path to an executable for the `@python` meta setting. However, [the documentation](https://github.com/SublimeLinter/SublimeLinter3/blob/a5f6c28ac7d88bfe28d524f6c2a6c2ed6b563cbc/docs/meta_settings.rst#python) seems to focus almost exclusively on version. It would be helpful to have an example that illustrates use of an executable.

Also, it would be helpful to know whether variable expansion does or does not work in that context (e.g., `${project}`).

**Comment by braver** [comment]
The docs are in this repo too, wouldn't mind a PR!

**Comment by braver** [comment]
The docs have been updated and the functionality referenced here (meta settings) has been removed.
