### ISSUE TITLE
SublimeLinter: WARNING: <linter> deactivated, cannot locate '<linter>'

### ISSUE THREAD

**Issue by ahmedelgabri** [SublimeLinter/SublimeLinter#59]
I'm getting these messages in the console for both `jshint`,  `csslint` & `coffeescript`

`SublimeLinter: WARNING: jshint deactivated, cannot locate 'jshint'`
`SublimeLinter: WARNING: csslint deactivated, cannot locate 'csslint'`
`SublimeLinter: WARNING: coffee deactivated, cannot locate 'coffee'`
Both are already installed globally & work properly from the command line, so how can I fix this?

**Comment by F1LT3R** [comment]
Tried the .zprofile thing (I use Oh-My-ZSH also). No joy there.

```bash
export PATH=/Users/@f1lt3r/local/bin/jshint
```
Gives me: 

`SublimeLinter: WARNING: jshint deactivated, cannot locate 'jshint' `

The `.zprofile' thing is also very confusing because SublimeLinter's debug says:

```
SublimeLinter: computed PATH using /bin/zsh:
/usr/local/lib/node_modules
/usr/local/share/npm/bin/
/Users/@f1lt3r/local/bin/jshint
```
... which looks like it is picking up the zsh'y things.

**Comment by F1LT3R** [comment]
OK, I think I have it now:

```bash
export PATH="/Users/@f1lt3r/local/bin/"
```

This works.

![screen shot 2015-01-28 at 1 26 51 pm](https://cloud.githubusercontent.com/assets/1218446/5943976/597a1bce-a6f1-11e4-9f61-a080b6705cc4.png)

**Comment by F1LT3R** [comment]
Ok, not working after all. Editing my `.zprofile` does get the linter to work, however adding that line to either my `.zprofile` or my `.zshrc`... breaks my the terminals.

```
Last login: Wed Jan 28 16:17:29 on ttys003
/Users/@f1lt3r/.oh-my-zsh/oh-my-zsh.sh:3: command not found: env
/Users/@f1lt3r/.oh-my-zsh/lib/theme-and-appearance.zsh:10: command not found: uname
/Users/@f1lt3r/.oh-my-zsh/lib/theme-and-appearance.zsh:14: command not found: uname
compdump:135: command not found: mv
/usr/local/bin/virtualenvwrapper.sh:50: command not found: which
virtualenvwrapper_derive_workon_home:12: command not found: grep
virtualenvwrapper_derive_workon_home:21: command not found: egrep
virtualenvwrapper_initialize:11: command not found: mkdir
virtualenvwrapper_mktemp:1: command not found: mktemp
ERROR: virtualenvwrapper could not create a temporary file name.
prompt_status:5: command not found: wc
prompt_context:1: command not found: whoami
 @f1lt3r's-MacBook-Pro ⮀ ~ ⮀
```

**Comment by F1LT3R** [comment]
@aparajita, `.zprofile` is loaded by `.zshrc` when it starts.

**Comment by F1LT3R** [comment]
I resolved this by putting it in `SublimeLinter.sublime-settings` as suggested by @ahmedelgabri.

```json
...
"paths": {
    "linux": [],
    "osx": [
        "/Users/@f1lt3r/local/bin/"
    ],
    "windows": []
},
...
```

**Comment by skj3gg** [comment]
The reason it breaks zsh is because you are literally overwriting your $PATH env variable. If it was like this `export PATH="$PATH:/Users/@f1lt3r/local/bin/"` or this `export PATH="/Users/@f1lt3r/local/bin/:$PATH"` it should work.

On a sidenote, Aparajita has stepped down from SublimeLinter ownership, so I wouldn't hold your breath on a response.

Glad you figured it out!

**Comment by F1LT3R** [comment]
thanks

**Comment by TensaZangetsu** [comment]
Adding a path doesnt work for me still same message 
SublimeLinter: WARNING: csslint deactivated, cannot locate 'csslint'

**Comment by Aedx** [comment]
@TensaZangetsu Please don't post multiple comments asking for help, you've already requested help at https://github.com/SublimeLinter/docs/issues/1#issuecomment-90020044. If you comment in multiple places then it will split up peoples' attempts to help you, resulting in wasted time and reduced productivity all round. Also, you have included barely any information here which could help us to help you: stating that something does not work without adding any additional information may result in you gaining you little help and will likely frustrate you further.

**Comment by jawshooah** [comment]
From your comment on the linked issue:

> I've read your documentation and i still cant find solution, your documentation is incomplete, hard to read and not at all for beginners users you might spend a little time working on your people skills.

Please refrain from using such inflammatory language here. There's no need for it, and it doesn't help anyone, least of all you.

**Comment by F1LT3R** [comment]
`<observation>`It's interesting to note that there is so much frustration installing and configuring SublimeLinter. While I  learned some neat things about my OS while getting up and running, I have noticed both online, and offline, many other people scrambling up the SublimeLinter install/config wall, and I wonder if the SublimeLinter community are planning on making it easier, or whether this is just one of those things that is hard to get around.`</observation>`

**Comment by skj3gg** [comment]
I appreciate the observations @F1LT3R. I wish there is more SublimeLinter could do, but the big piece of `SublimeLinter3` compared to `SublimeLinter-for-ST2` is that in SL3, "Batteries are not included". This was a very conscious decision so that people could setup and use their environment how THEY wanted, is was a push for a system of "configuration over convention". Because there is this flexibility, it does create many pain points trying to get every combination of environments working, and to make it easy for every knowledge-level to use.

**Comment by F1LT3R** [comment]
Makes sense.

**Comment by davicho** [comment]
Spent a lot of time trying to figure this out. Using  osx/oh-my-zsh. Thing is that used to work by simply adding the path to SublimeLinter settings file but then that broke for some reason.

So two things:
1)_ it used to work by manually updating the path in the settings file
2)_ "which <linter>" works for me. But still would get a jslint deactivation.

Upon searching for this error I came about this thread. **Adding the .zprofile  and adding this line to it: export PATH="/Users/@f1lt3r/local/bin/:$PATH" worked.** 

I am glad it's working but I don't understand why updating thru settings doesn't. Also, the instructions about this piece, I read over a hundred times are a bit confusing (at least in my scenario)... see I can find my path.... but instructions say to add the .zprofile when you can't.

**Comment by bugre** [comment]
Hi,
For those using mac osx with "bash" as the default shell (specially if NOT using the native osx bash version)

Maybe worth mentioning in the documentation at https://sublimelinter.readthedocs.org/en/latest/troubleshooting.html#special-considerations-for-bash) that:

For the native osx /bin/bash (my case osx 10.10.5 it's v3.2.57) the described procedure from the link above is correct.

But, if you're using an upgrades bash version from (port, brew...) probably better check the man page to see how initialization files are loaded. For the port bash (usually /opt/local/bin/bash  -- now v4.3.42) the initialization goes like the Unix system mentioned, where the ~/.bashrc file is called for the interactive/login shell and if you moved your PATH settings to ~/.bash_profile you should source it into the start of ~/.bashrc.

(this is at least happens on my machine)

**Comment by YuriGor** [comment]
Note, that you should keep all the OS keys in "paths" Sublime settings, even if they are empty.
This config didn't work for me:
```
"paths":
	{
		"linux": [
			"/home/gor/.nvm/versions/node/v6.2.0/bin/"
		],
	},
```
but this works well:
```
	"paths":
	{
		"linux": [
			"/home/gor/.nvm/versions/node/v6.2.0/bin/"
		],
		"osx": [],
		"windows": []
	},
```

**Comment by BB-000** [comment]
I had to create the SublimeLinter.sublime-settings and add the "paths" in

(OSX)  ~/Library/Application Support/Sublime Text 3/Packages/User/
