### ISSUE TITLE
[virtualenv] virtualenv/.sublimelinterrc support is broken

### ISSUE THREAD

**Issue by posita** [SublimeLinter/SublimeLinter#591]
SublimeLinter3 seems to require that linters executable are installed in `PATH` and will refuse to load them, even if they're in virtualenvs specified in `.sublimelinterrc`.

Project settings file:

```
{
    "SublimeLinter": {
        "linters": {
            "flake8": {
                "executable": "/Users/posita/.virtualenvs/foo/bin/flake8"
            }
        },
        "paths": {
            "linux": [],
            "osx": [
                "/Users/posita/.virtualenvs/foo/bin"
            ],
            "windows": []
        }
    },
    "folders": [
        {
            "follow_symlinks": true,
            "path": "/Users/posita/src/foo"
        }
    ],
    "settings": {
        "python_interpreter": "/Users/posita/.virtualenvs/foo/bin/python",
        "rulers": [100],
        "suppress_python_not_found_error": false
    }
}
```

`/Users/posita/src/foo/.sublimelinterrc` file:

```
{
    "@python": "/Users/posita/.virtualenvs/foo/bin/python"
}
```

Result with `pylint` and `flake8` installed **_only_** in `/Users/posita/.virtualenvs/foo`, but **_without_** `pylint` and `flake8` **_also_** installed in default `python` environment:

```
…
SublimeLinter: WARNING: flake8 deactivated, cannot locate 'flake8' 
…
SublimeLinter: WARNING: pylint deactivated, cannot locate 'pylint@python' 
…
```

Result **_with_** `pylint` and `flake8` installed in default `python` environment:

```
…
SublimeLinter: pylint: setup.py ['/Users/posita/.virtualenvs/foo/bin/python', '/usr/local/bin/pylint', "--msg-template='{line}:{column}:{msg_id}: {msg}'", '--module-rgx=.*', '--reports=n', '--persistent=n'] 
SublimeLinter: pylint output:
…
SublimeLinter: flake8: setup.py ['/Users/posita/.virtualenvs/foo/bin/flake8', '--jobs=1', '--max-complexity=-1', '-'] 
…
```

Even though the virtualenv executable is identified in the project settings file, and even though `@project` is set to the virtualenv in `.sublimelinterrc`, unless it **_first_** finds the `pylint` or `flake8` executables somewhere in `PATH`, it will disable the linter altogether.

**Comment by posita** [comment]
See:

- [`lint/linter.py`@L200-L202](https://github.com/SublimeLinter/SublimeLinter3/blob/2cab34326b9b8bfe994e1b6d5faa30a6274eb804/lint/linter.py#L200-L202)
- [`lint/linter.py`@L1602](https://github.com/SublimeLinter/SublimeLinter3/blob/2cab34326b9b8bfe994e1b6d5faa30a6274eb804/lint/linter.py#L1602)

**Comment by braver** [comment]
.sublimelinterrc support has been dropped in SublimeLinter4. It shouldn't be as necessary to change settings locally, and where needed they can be set in project settings. This specific request is therefore "won't fix".
