### ISSUE TITLE
Linter executable paths not being used properly

### ISSUE THREAD

**Issue by brupelo** [SublimeLinter/SublimeLinter#627]
You expect to have certain linters like `pep8` ready to be used at startup, that's not good design at all. 

For instance, I don't have any system-python available in PATH, which is a good choice IMHO. I work with virtualenvs instead and I  got a plugin which can switch between virtualenvs and change the sublimetext PATH accordingly so the virtualenv's tools are ready to be used in sublimetext. The problem is SublimeLinter won't use these ready to go tools because it's assumed they are not installed.

So, can we change this rigid behaviour to something more flexible which allows SublimeLinter using these tools on "Realtime"?

Thanks in advance.

**Comment by brupelo** [comment]
> A system like this is going to have to make some assumptions. If the design was so bad, it wouldn’t have thousands of users.

Don't take me wrong, I didn't mean to be harsh nor criticizing the package, obviously it's one of the best available choices when it comes to have a flexible linter system in sublime.

That said, I want you to realize the existing behaviour can be improved & extended and If I was familiar enough with the code I would propose an enhancement myself.

Thing is, the package should react properly to the current existing paths on realtime and not caching the paths at startup. For instance, let's say PATH doesn't contain any available tools at startup, it's expected that SublimeLinter doesn't find any linter... now, let's say the user edit the Preferences and edit the paths, at that moment SublimeLinter should react and scan the available Linters.

Or, for instance, let's say SublimeLinter starts with a PATH containing multiple available linters and everything works, if the user get rid of the tool's path in the preferences file, linters shouldn't work anymore.

Doesn't make sense? That's what a flexible system is, working accordingly to the current package configuration and not caching some initial configuration and that's it. Take a look to the ST architecture in general, why is so good the editor? Because it reacts to every user change in realtime...

So yeah, please don't take this ar a question or criticism but as an enhacement, in fact, if you guide me through the key hotspots in the code i could give it a shot and fix the existing rigid behaviour by myself.

Ty.

**Comment by braver** [comment]
Ok, sounds like good ideas all around. I can't do more that store and categorise it at this point, there is a general lack of maintainers on this repo right now so I can't say you should expect action on this any time soon. To save this for later, could you change the title to reflect either your enhancement proposal (or keep it as more of a bug fix entry as it is)?

**Comment by brupelo** [comment]
@braver I understand, I've changed the title but it seems I can't change the label as I don't have enough privileges, could you?. Also, If you have a better title suggestion which brings more attention to the request though please let me know and I'll change it.

Btw, If you know the codebase well enough and you can point me out to the key places where to look at, I could play a little bit with it. Otherwise  I guess I'll just wait :)

**Comment by brupelo** [comment]
[https://forum.sublimetext.com/t/editing-sublimetext-process-path-programatically](https://forum.sublimetext.com/t/editing-sublimetext-process-path-programatically/32182/14?u=bpl)

**Comment by FichteFoll** [comment]
I would adjust the title to something like "Determine linter executable path on-demand instead of at startup".

**Comment by braver** [comment]
We have been making [many changes](https://github.com/SublimeLinter/SublimeLinter/blob/master/messages/4.0.0-rc.1.txt) to SublimeLinter, some of which also should have fixed this particular problem. It would be really nice if you could [try the beta](https://github.com/SublimeLinter/SublimeLinter/tree/15bb4a2e2024a623f60bb444eadd5790764fdfb9#sublimelinter-4-beta) and let us know if that fixes the problem for you.

**Comment by brupelo** [comment]
@braver First of all, thank you for all the changes you guys have brought to us the users.

Now, just let you know I've tried the new beta right now but unfortunately it isn't solving my issue for some reason, take a look to this [video](https://dl.dropboxusercontent.com/s/mg5u0s02ykjjvbg/2018-01-06_17-50-04.mp4), as you can see there when i start a fresh sublimetext session the path will be empty (as you can see in the video i won't be able to run the script because neither python nor any of the linters: flake8, autopep8, ... are available). So after that, I just enable the virtualenv (so the d:\virtual_envs\py364_32\Scripts will be added to path) so you'll be able to see in the video the windows `where` command will show that python executable and flake8 are ready to go, but even so, the new SublimeLinter won't be aware of this fact, is this expected behaviour? What is it doing behind the curtains?

Am I missing something? In any case, I'll rollback to my previous workflow, that was starting sublimetext from a .bat file adding some system-wide python path to the ST process ;)

**Comment by FichteFoll** [comment]
Should have been fixed by #786.

**Comment by braver** [comment]
> Should have been fixed

I think so to. If not, @brupelo let me know!

**Comment by brupelo** [comment]
@braver Sorry for the late report, I've been living with v3.8.0 for months but today I've started using latest master branch. Yeah, it seems now it works properly as I can see the linter is used on "real-time", chosen from environ['PATH'] and yeah, that's the right way to go.

I can finally get rid of system-wide python from PATH when starting the sublime processs ;-)

So for that, I just can say, good job guys! ty a bunch :D

**Comment by braver** [comment]
Cool, thanks. It took a bit of work ☺️
