### ISSUE TITLE
Specify phpcs path inside .sublimelinterrc file

### ISSUE THREAD

**Issue by dingo-d** [SublimeLinter/SublimeLinter#648]
The phpcs linter works if I install the certain coding standard globally in my `users/username/wpcs` folder. But I am wondering when I set up a project and in the composer,  can I use the custom standard that is installed locally, per project?

I added `.sublimelinterrc` file in the root of my project with the following

```json
{
  "SublimeLinter": {
   "paths": {
        "linux": [],
        "osx": [
          "/vendor/bin"
        ],
        "windows": []
    }
  }
}
```

But when I lint, the console says

> SublimeLinter: phpcs output:
ERROR: the "Infinum" coding standard is not installed. The installed coding standards are PEAR, Zend, PSR2, MySource, Squiz, PSR1, WordPress-VIP, WordPress, WordPress-Extra, WordPress-Docs and WordPress-Core 
SublimeLinter: No match for <_sre.SRE_Pattern object at 0x7fead17c9ac0>

It only picks up the standards that are in the `users/username/wpcs` folder.

Can this be done?

**Comment by braver** [comment]
I think you're better of asking this in the repo for this particular linter?

**Comment by dingo-d** [comment]
Ok, will try that too.

**Comment by nkrh** [comment]
Have you tried the `{$project} ` token in the linter setting?

Example:

```
{
    "SublimeLinter":
        {
            "linters":
            {
                "phpcs": {
                    "standard": "${project}/vendor/phpcs/MyPHPCS"
                }
            }
        }
}
```

**Comment by dingo-d** [comment]
@nkrh I tried it, but I got a bunch of errors.

> Fatal error: Uncaught UnexpectedValueException: DirectoryIterator::__construct(vendor/wp-coding-standards/wpcs): failed to open dir: No such file or directory in /wpcs/vendor/squizlabs/php_codesniffer/src/Util/Standards.php:93

**Comment by nkrh** [comment]
Try to put them in the project settings. 

https://www.sublimetext.com/docs/3/projects.html
http://www.sublimelinter.com/en/latest/settings.html#setting-tokens

**Comment by braver** [comment]
.sublimelinterrc support has been dropped in SL4 rendering this "won't fix". Project settings should work though.
