### ISSUE TITLE
Refactor Module Structure - Remove Mutual Imports

### ISSUE THREAD

**Issue by pykong** [SublimeLinter/SublimeLinter#650]
In the current implementation **SL** relies on many mutual imports between individual files in the `lint` folder.

This may represent not only a dangerous anti-pattern but makes extending and modifying the code difficult.
As any software need to change over time a refactoring towards a cleaner module structure will help ensure **SL**'s maintainability. 

Therefore such a cleaned up module structure should be investigated.

**Comment by braver** [comment]
@pykong Think we covered this well enough for now?

**Comment by braver** [comment]
I don't see many problems here anymore. Please re-open if you don't agree.
