### ISSUE TITLE
On Windows: Implementation idea to find the best system python is outdated.

### ISSUE THREAD

**Issue by kaste** [SublimeLinter/SublimeLinter#654]
Implementation idea to find the best system python is outdated. Python by default does not get installed in `C:\\Python36`. It is installed either system wide or for the user only, or of course you choose your own path. But at end, it is reasonable to assume it somehow lands in your path and thus is executable.  

Implementation bug:

https://github.com/SublimeLinter/SublimeLinter3/blob/d95681c9f50f86880c6913a788b9f0be85a92de7/lint/util.py#L921-L924

If in `os.environ.get("SYSTEMROOT", "\\")[:2]` `SYSTEMROOT` is not set, the whole expression becomes the empty string. The net result is, that we take the current dir, and search below that. [The current dir is often the SublimeText installation path, and the following glob 

https://github.com/SublimeLinter/SublimeLinter3/blob/d95681c9f50f86880c6913a788b9f0be85a92de7/lint/util.py#L926 

then finds `<sublimetext>/python33.dll` as a candidate.] [Code review: The implementor probably should have used `os.environ.get("SYSTEMDRIVE", "C:")`.]

So in the end, the implementation idea is not a good idea, the implementation itself is buggy. The result is that this _magic_ will very, very likely fail. 

The code then immediately falls back to find the **first** python on PATHS without checking if it matches the version. (Although the semantics here are, give me a specific version; the func signature is `def find_windows_python(version):`!)

On windows, you can - of course -  have multiple python versions installed, and all land on PATHS, partially masking each other. The user can then use e.g. `python3` or `py -2` to launch a specific version. The implementation strategy should be to _iterate_ over all python installations in PATHS and choose the best, or the first good.

So if you didn't set up any settings, it will probably find a good python (the first one); but setting `@python` to a number (indicating a wanted _version_) will not help you. You will most likely get the same version. 

Rescue: You can set `@python` to a path to a python binary, like so `C:/dev/python3/python.exe` and it will look for a linter binary in `<path>/Scripts/<linter>.exe`. However - this is again poorly, buggy implemented -: virtual environments don't have the binary at the base path of the virtual env, they have the binary at `<venv-path>/Scripts/python.exe`. So this basically works, bc of pure luck. [It asks `<venv-path>/python.exe` for its version, 

https://github.com/SublimeLinter/SublimeLinter3/blob/d95681c9f50f86880c6913a788b9f0be85a92de7/lint/util.py#L834

this call will fail, there is no such file, but 'optimistically' returns the version is None. And a version of None then actually fulfills the version test. This is the actual code. It works, yay, but it is lucky; the intention of the user when setting `@python` to a string is more likely: that IS the version, don't check it.]

**Comment by braver** [comment]
@kaste I'd like to start moving what you did for the flake8 linter into the main repo, to be part of the SL4 release. I can provide guidance by answering questions, I can test, I can ask others to help review, I can probably even go out and make fixes here or in plugins. I just don't have the knowhow to really pull this forwards myself. SL4 is a major number release and that gives us an opportunity to make some big changes and move dependant plugins along, so if you're willing to take a go at this I'd very much be supportive of that.

**Comment by kaste** [comment]
Let's do it. 🙏

**Comment by kaste** [comment]
Done.
