### ISSUE TITLE
cpplint activated but not showing error

### ISSUE THREAD

**Issue by plnegre** [SublimeLinter/SublimeLinter#669]
I have an issue using SublimeLint with cpplint. Everything seems to be installed and configured correctly but ST3 is not showing the style errors on the gutter.

I installed SublimeLinter, SublimeLinter-cpplint and cpplint via pip.

Here is the log of ST3 at startup:

DPI scale: 1.75
startup, version: 3143 linux x64 channel: stable
executable: /opt/sublime_text/sublime_text
working dir: /
packages path: /home/plnegre/.config/sublime-text-3/Packages
state path: /home/plnegre/.config/sublime-text-3/Local
zip path: /opt/sublime_text/Packages
zip path: /home/plnegre/.config/sublime-text-3/Installed Packages
ignored_packages: ["SideBarEnhancements", "Vintage"]
pre session restore time: 0.058042
loading dictionary Packages/Language - English/en_GB.dic
startup time: 0.144301
first paint time: 0.17222
reloading plugin Default.auto_indent_tag
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.install_package_control
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.quick_panel
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.settings
reloading plugin Default.show_scope_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin Default.ui
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin 0_package_control_loader.00-package_control
reloading plugin DoxyDoxygen.Doxy
------==== DoxyDoxygen plugins loaded ====------
0 sub-modules to reload
reloading plugin Package Control.1_reloader
reloading plugin Package Control.2_bootstrap
reloading plugin Package Control.Package Control
reloading plugin SublimeLinter-cpplint.linter
SublimeLinter: cpplint linter loaded 
reloading plugin SublimeLog.SublimeLog
reloading plugin SublimeLinter.commands
reloading plugin SublimeLinter.sublimelinter
plugins loaded
SublimeLinter: cpplint activated: /usr/local/bin/cpplint 

Thank you

**Comment by braver** [comment]
Can you run this on a a file that has errors, and enable the debug mode, and then show us the output again? You may also want to try the new [version 4 beta](https://github.com/SublimeLinter/SublimeLinter#sublimelinter-4-beta).
