### ISSUE TITLE
[beta] output panel: show current file first

### ISSUE THREAD

**Issue by braver** [SublimeLinter/SublimeLinter#681]
To improve the workflow of removing lint using the output panel, the current file should be first in the list. This ensures you don't get a massive context switch when you jump to the first result.

**Comment by braver** [comment]
from @kaste 

> Currently, we show them in arbitrary order. Technically we loop over a dict, so this is order is also not stable.
>
> I propose that we order in a last-recently-used way. This would also mean, that the current, active view is always on top, if I open the panel. Old views, move slowly down. This reflects that I'm apparently not very interested in fixing them yet, bc I need to fix, write code in other views first.

**Comment by braver** [comment]
I can imagine re-sorting the panel a lot, especially *while* you're navigating it, could be far from ideal. We'll have to see what's a good idea here.

**Comment by kaste** [comment]
This has been resolved by the magic @pykong PR. Nope? 

The user story originally was: If I'm in a file and hit F4, I want to go to the next error in this file. And this works.


From a technical point of view: We still have an arbitrary order here. And sometimes the order changes with re-draws. (Naturally bc we just loop over `items()`.) 

And it still bugs me that if I have a lot of views open, I don't find anything scrolling the panel. Ah, well, bc it isn't sorted in any way.

**Comment by braver** [comment]
I think the magic PR has indeed solved the problem as best we can. I'm personally perpetually confused about anything that's MRU sorted so that wouldn't help me. I'd like everything to be spatially ordered and consistent, so in the order of the tabs or something. Which won't work because of a lot of other reasons.

So it's a bit hard to put a design on this that works better than it already does, and the original case has been solved.

**Comment by kaste** [comment]
`reversed((view.id(), view.file_name()) for view in sublime.active_window().views())` is a stable sort. With reversed the new ones go on top.

**Comment by FichteFoll** [comment]
Sounds good, although I wonder how views() iterates over multiple panes.
