### ISSUE TITLE
[beta] document new linter creation flow

### ISSUE THREAD

**Issue by braver** [SublimeLinter/SublimeLinter#682]
Starting SL4 (#666) you can't start a new linter from the SL plugin, but there will be a template repository you can fork.

We may also drop some of the wizard-like UI and just let you manually edit the few files that need editing.

~~Additionally, we may drop the entire review proces and re-integrate the package_control repository to make linter plugin authors more autonomous and reduce unnecessary maintenance load on SL devs.~~

**Comment by FichteFoll** [comment]
>Additionally, we may drop the entire review proces and re-integrate the package_control repository to make linter plugin authors more autonomous and reduce unnecessary maintenance load on SL devs.

It would increase *my* load, however. Considering that SL authors and collaborators have a much better understanding of *their* provided API, it sounds like a much better idea to have plugins *for* this API to be reviewed by them.

**Comment by braver** [comment]
Yes, that is a good point. Would it be possible and a good idea to organize that in the main package control repo?

**Comment by FichteFoll** [comment]
Not sure what you want to organize. The status quo seems quite good to me.

**Comment by braver** [comment]
Alright, let’s keep it that way.
