### ISSUE TITLE
[beta] More icons for the default theme

### ISSUE THREAD

**Issue by braver** [SublimeLinter/SublimeLinter#683]
Now that individual icons can be assigned to a style, it would be nice to have some more options. Examples:
[icons.zip](https://github.com/SublimeLinter/SublimeLinter3/files/1544563/icons.zip)

**Comment by braver** [comment]
@pykong I hope you'll enjoy the new cog, diamond,  diamond-outline, heart, heart-outline, pointer, pointer-outline, square, square-outline, star, star-outline, triangle, triangle-outline and x

**Comment by douglas** [comment]
How to use this, @braver? With these settings:

```json
// SublimeLinter Settings - User
{
  "lint_mode": "load_save",
  "gutter_theme": "Default",
  "styles": [
      {
          "mark_style": "solid_underline",
          "priority": 1,
          "scope": "region.yellowish markup.changed.sublime_linter markup.warning.sublime_linter",
          "icon": "cog",
          "types": [
              "warning"
          ]
      },
      {
          "mark_style": "solid_underline",
          "priority": 1,
          "scope": "region.redish markup.deleted.sublime_linter markup.error.sublime_linter",
          "icon": "cog",
          "types": [
              "error"
          ]
      }
  ]
}
```
I have this error:

<img width="1141" alt="screen shot 2018-01-23 at 19 47 33" src="https://user-images.githubusercontent.com/411301/35308591-5a863d90-0076-11e8-8529-6331bc98b797.png">
