### ISSUE TITLE
Base linter selection on scope instead of syntax file name

### ISSUE THREAD

**Issue by FichteFoll** [SublimeLinter/SublimeLinter#691]
Basing the linter selection on the base scope is much more flexible as opposed to having a large `syntax_map` mapping, since most JavaScript-like languages *will* be using `source.js` as the base scope and possibly add more leaves to that, e.g. `source.js.babel`. Or `source.json.sublime.settings`.

Kind of nullifies #431 too, since all use cases I had in mind for that would be solved by this solution.

To outline the extend of this problem, this is my current `syntax_map` settings (which I didn't even realize to have grown so much – probably the work of a plugin, and I suspect a theme providing icons, like @ihodev's A File Icon):

```
    "syntax_map": {
        "coffeescript (gulpfile)": "coffeescript",
        "html (django)": "html",
        "html (rails)": "html",
        "html 5": "html",
        "javascript (babel)": "javascript",
        "javascript (eslint)": "javascript",
        "javascript (gruntfile)": "javascript",
        "javascript (gulpfile)": "javascript",
        "javascript (postcss)": "javascript",
        "javascript (stylelint)": "javascript",
        "javascript (webpack)": "javascript",
        "json": "javascript",
        "json (babel)": "json",
        "json (bower)": "json",
        "json (composer)": "json",
        "json (eslint)": "json",
        "json (npm)": "json",
        "json (postcss)": "json",
        "json (settings)": "json",
        "json (stylelint)": "json",
        "json (sublime)": "json",
        "json (tern js)": "json",
        "php": "html",
        "python django": "python",
        "sublime commands": "javascript",
        "sublime completions": "javascript",
        "sublime key map": "javascript",
        "sublime macros": "javascript",
        "sublime settings": "javascript",
        "sublime text build system": "javascript",
        "sublime text syntax def (json)": "javascript",
        "sublime text syntax def (yaml)": "yaml",
        "xml (config)": "xml",
        "xml (svg)": "xml",
        "yaml": "yaml",
        "yaml (circleci)": "yaml",
        "yaml (docker)": "yaml",
        "yaml (eslint)": "yaml",
        "yaml (lock)": "yaml",
        "yaml (procfile)": "yaml",
        "yaml (stylelint)": "yaml",
        "yaml (yarn)": "yaml"
    },
```

**Comment by braver** [comment]
Let’s close this once the PR has been merged.

**Comment by braver** [comment]
via @pykong in #740

> The current syntax map quickly grows unreadable when adding new entries.
A cleaner structure may consist of an object mapping `syntax_name` to and array of `syntaxes`.
_(See proposed syntax map below.)_


**Current:**
```
    "syntax_map": {
        "html (django)": "html",
        "html (rails)": "html",
        "html 5": "html",
        "javascript (babel)": "javascript",
        "magicpython": "python",
        "php": "html",
        "python django": "python",
        "pythonimproved": "python"
    }
```

**Proposed:**
```
"syntax_map": {
        "html":  [ "html (django)",  "html (rails)", "html 5", "php"],
        "javascript":  ["javascript (babel)"],
        "python": [  "magicpython" , "python django", "pythonimproved"]     
    }
```

An attempt was made in #799, but it would take quite an effort in the core repo, but also affect all linters. The OP here lists a huge syntax map, usually it isn't as bad. Although perhaps inelegant it *does* work.

**Comment by pykong** [comment]
The most elegant way would be to allow Linters to maintain their own list of scope selectors.
This would give plugin authors most control to decide which syntaxes to lint.
At the same time it allows us to get rid of a big syntax map, which serves only as crutch.

Indeed linters already have the attribute `selectors` albeit it is only used for determining embedded syntaxes (like JS in HTML) and by a different mechanism than OP proposed (AFAIK).

**Comment by FichteFoll** [comment]
I agree with what @pykong says here.

To reiterate on what we are actually talking about here, I want to summarize the reason for this feature to exist:

- Linters should be able to specify which syntaxes they operate on, e.g. Python or HTML.
- Users may need to tweak the automatic syntax detection to their environment.

As I stated in my OP, basing the syntax selection solely on the syntax's name is sub-optimal because of the many variants and aliases of some syntaxes caused by alternative syntax definitions or themes that  provide fine-grained file type icons. Furthermore, some linters may support a syntax like JavaScript but not support JSX, a variant of JavaScript, while some do, so it should be configured individually per linter.

In the current implementation, we have a middle layer between what a linter supports and what a syntax is by mapping the syntax's name to a common name that a linter may choose from, but a linter can then only choose one name, so we have a n:1 mapping, while in reality it is n:m.

Now, allowing linters to state their target syntax with a scope selector would allow us to make use of the hierarchical scope structure and skip the entire alias problem while still being able to exclude certain flavors or dialects like JSX using an additional negative selector (e.g. `source.js - source.js.jsx`). If this selector was then overridable by the user in a linter's setting, we'd have everything we need.

The mechanism proposed in OP can be thought of as more of a migration step or compatibility layer between this selector approach and the existing one.

Unfortunately, I do not know enough about how embedded syntax detection is implemented currently, but in theory they are quite similar and you can get embedded linting automatically using the scope provided for the overall compatibility. Depending on the implementation, emebdded syntax detection can be quite imperformant, so it might be a good idea to hide that behind a boolean flag that is only enabled for linters that target frequently embedded languages, while only the base scope (at position 0) is checked for normal linters instead of the entire file.

PS: I'd like to take the time to better inform myself, but technically I can't even afford writing this much in a comment. At least until Wednesday.

**Comment by FichteFoll** [comment]
Okay, I have a bit more free time this week, so I *could* work on a syntax->selector translation this week. But this time I want to confirm whether this is in scope before I spend more than a day on things that don't align with SL's scope.

So, the idea is to be backwards compatible, but also make most of the syntax map with variants such as "JavaScript (Babel) => JavaScript" redundant and match on the selector directly.

I think the best option currently is to automatically infer a `selector` attribute from `syntax` based on an internal lookup map and otherwise just prepending `scope.` to the syntax name, if none was specified, and prioritize scope-based linting. If the scope selector doesn't match, we still need to check the syntax name as a fallback or in case our automatic translation was errorneous.

For user configuration, a user would probably like to override a linter's scope selectors if needed - or maybe even the general syntax->scope map? Do we still want syntax name overrides then?
#994 currently implements linter-specific overrides (for the name) only, as far as I understand.

As mentioned earlier, I'd like to hear some feedback on these ideas before I start hacking on it.
I do wonder what the performance impact is, though.

**Comment by kaste** [comment]
Neither the API nor the internals here are really clear to me. 

Say a plugin author implements this new thing for eslint at `eslint.syntax = ('source.js', )`. This `eslint` plugin arrives at SL in `linter_classes`, now whenever we have a new view, we need to find which linter_class would be appropriate for that view. Do you propose the following for that use-case:

```
def linters_for_view(linter_classes, view):
	return [
		linter_class 
        for linter_class in linter_classes
		if any(bool(view.find_by_selector(syntax)) for syntax in linter_class.syntax)
	]

```

This would select 'html' with embedded 'js' as well as normal 'js' files/buffers.

**Comment by FichteFoll** [comment]
Yes, something along the lines. (I'd probably re-introduce `can_lint` with a `view` argument because of the separation of concern.)

Again, I haven't yet checked how the current implementation of selector-based linting with pseudo views works. I can probably give more targetted descriptions once I figured out where I would hook this in.

**Comment by kaste** [comment]
Two problems with this approach:

- We would have to re-assign linters on every 'hit', because a 'html' file may or may not have a 'js' section.

- People want e.g. to lint html using eslint and a plugin. So, they have to opt out of the selector based approach. (With various plugins a linter operates really on different file types. So our workaround or 'feature' needs to be pluggable.)

**Comment by FichteFoll** [comment]
Can you elaborate on the second issue? I never used eslint, but it sounds like it supports a differnt lint mode for HTML files?

**Comment by kaste** [comment]
jshint and eslint can both operate on html files. (eslint needs a plugin for that.) So basically people do `eslint index.html`. 

(Obviously, the eslint-plugin-html is more sophisticated than our solution. It has a notion of global scope across script tags within that file.)

**Comment by braver** [comment]
Wouldn’t that be solved via user defined syntaxes (#994)? I.e. a user would enable eslint for the text.html scope.

**Comment by kaste** [comment]
The users actually would set `syntaxes: ['source.js', 'text.html']`, obviously they also have js files in such a project. But in a 'html' file we can find both selectors.

**Comment by kaste** [comment]
If you look at it: Clearly the user doesn't know about 'source.js' and 'text.html'. They usually know their file type (or extension), then maybe the sublime syntax which at least is shown in the status bar, sure they don't know about scopes. So we again need a map 'js => source.js; html => text.html'. 

Before we have an automagic system, we need a clear data representation, so the user has full control. I think we learned that from the linter executable finding. We had a lot of magic, but the stupid, simple `executable` setting to override our 500 LOC was missing.

**Comment by braver** [comment]
Sure, but scopes you can find out and they’re the central concept in ST for specifying languages. At some point users are bound to find out about scopes.

If we use scopes, pretty much no one will ever need to bother configuring anything because it will just work. Except of course when one linter can suddenly do other things as well but that rarely happens. That’s what readme’s are for at that point. The current mapping exists because there are tons of variations for JS, while they all start with the source.js scope. If a linter can do source.js he can do all the variations without anyone ever configuring anything. 

That’s the primary reason for switching to scopes: users won’t have to do or know about anything anymore. They don’t need control. This isn’t a user configuration problem. We’re letting users fix our broken design. Plugin authors need a sane way to declare what languages the linter can handle, so no one else needs to.

If we do have the user configure anything it would be by the name displayed on the status bar. However, there is no API for us to read that directly, we’d have to retrieve the syntax file and parse it to look for the syntax name. Can be done, but if we do this right we don’t need to expose configuration to 90% of end users, unless they run eslint with plugins. And in that case we tell them about scopes.

**Comment by kaste** [comment]
Okay, I think I understand this as follows: The plugin author defines `Eslint.selectors = ('source.js', )`, the user overrides `selectors: ['text.html', 'source.js']`. Then to pick a linter for a view:

```
def linters_for_view(linter_classes, view, selectors):
	return [
		linter_class 
        for linter_class in linter_classes
		if (
			any(bool(view.score_selector(0, selector)) for selector in selectors) or
			any(bool(view.find_by_selector(selector)) for selector in selectors)
		)
	]

```

And in the backend, we need to get the regions to lint:

```
def get_lint_regions(linters, view):
	for (linter, settings) in linters:
		selectors = settings.get('selectors') or linter.selectors
		for selector in selectors:
			regions = view.find_by_selector(selector)
			if regions:			
				yield linter, settings, [region for region in regions]
				break
```

So, basically `selectors` would be ordered. I really don't know if ordering alone would be sufficient for the users though. 

Still problems:

- Generally, I don't understand/grasp the compatibility layer, upgrade path.
- I don't think users know the right scopes.
- We have to run above `linters_for_view` on every hit (on_modified_async)

**Comment by braver** [comment]
> Generally, I don't understand/grasp the compatibility layer, upgrade path.

Me neither. Previously we discussed introducing an internal mapping from syntax to scope, but it’s not clear to me that that’s easy to get right.

The second point I think we can document.
The third doesn’t sound ideal and perhaps it’s a deal breaker?

**Comment by kaste** [comment]
Okay, #1007 is just the two functions I wrote here applied.

**Comment by kaste** [comment]
Apparently markdown is `text.html.markdown`. How do we prevent such hiccups? Why should scope selectors follow a sane strategy here?

**Comment by kaste** [comment]
Oh, html is actually `text.html.basic` 🤣

**Comment by FichteFoll** [comment]
#1007 looks good.

For the compatibility layer, I had something like this in mind:

```py
SYNTAX_SCOPE_MAP = {
    'javascript': 'source.js',
    'typescript': 'source.ts',
    'html': 'text.html.basic',
    'markdown': 'text.html.markdown',
    # TODO go through all syntaxes currently used by linters and add non-obvious translations
}


def syntax_to_selector(syntax):
    """Makes a greedy translation from a syntax name to a scope selector.
    
    Utilize a lookup map for less obvious translations, 
    otherwise fall back to `source.<syntax>`.
    """
    syntax = syntax.lower()
    return SYNTAX_SCOPE_MAP.get(syntax, "source.{}".format(syntax))
```

**Comment by kaste** [comment]
Hm, we probably need `unselectors`? Otherwise, eslint runs on markdown files?

**Comment by braver** [comment]
There is this concept of a `-` operator in selectors that should be able to do that. `text.html.markdown - source` or something like that.

**Comment by kaste** [comment]
That's absolutely nuts `source.js - text.html` 🎆

**Comment by FichteFoll** [comment]
>Otherwise, a linter runs on the embedded code in markdown files?

I thought that was intended? I mean, I'd like to see that tbh.

**Comment by kaste** [comment]
Okay, I just write down some user requirements. Can we achieve them? (I read quite some issues.) We just consider eslint.

- The plugin author wants by default that eslint lints js files and embedded scripts in say html.

- A user wants that eslint runs only on js files. (Bc the scripts in index.html doesn't conform to the eslint rules anyway.)

- A user wants that eslint runs on js files and on embedded scripts in html, but sure markdown is overkill. (Bc the appropriate eslintrc is usually missing, and an annoying warning pops up every time.)

- A user wants that eslint actually lints html files (and js files of course) bc she has installed the super eslint-plugin-html (alternatives: installed the json plugin, or the php plugin, or the vue plugin)

- The plugin author needs to tweak the actual cmd based on which 'file type' (previously syntax) the code supposed to be.

**Comment by braver** [comment]
Users currently don’t really have much to say about what linter runs when right? Especially the embedded stuff is completely up to the plugin author IIRC.

For 2, 3 and 6 I’d imagine eslint to have configuration files that cover that. Our configuration to add syntaxes, the linters own config to fine tune it.

**Comment by FichteFoll** [comment]
I'll try to answer the user (and plugin dev) requirements for the current state of #1007.

>The plugin author wants by default that eslint lints js files and embedded scripts in say html.

The author provides a `selectors` default setting of `source.js` (as a string, ofc).

>A user wants that eslint runs only on js files. (Bc the scripts in index.html doesn't conform to the eslint rules anyway.)

The user overrides the `selectors` setting with `source.js - source source - text source`. This could be mentioned in the docs as a comon example.

Alternatively, we could introduce an "embedded" setting that is true by default but can be disabled by a user. If this is a common thing to do, I'm sure users would appreciate a short-hand setting for this rather than the not so immediate scope selector I suggested. This also allows optimizations because `View.find_selector` doesn't need to be called anymore.

>A user wants that eslint runs on js files and on embedded scripts in html, but sure markdown is overkill. (Bc the appropriate eslintrc is usually missing, and an annoying warning pops up every time.)

`source.js - text.html.markdown`

>A user wants that eslint actually lints html files (and js files of course) bc she has installed the super eslint-plugin-html (alternatives: installed the json plugin, or the php plugin, or the vue plugin)

`source.js | text.html.basic` (to be documented in the eslint linter plugin readme)

>A user has also installed the json plugin, and thus wants to lint json files with eslint. (This is merely how complicated gets the configuration with multiple plugins?)

`source.js | text.html.basic | source.json`

>The plugin author needs to tweak the actual cmd based on which 'file type' (previously syntax) the code supposed to be.

Plugins can modify the cmd in the `run` method, but they would need to consider user overrides.

>The plugin author wants to tweak the selectors automatically, based on if a eslint plugin is installed or not.

This is tricky. It's not possible at the moment, because a linter's methods are only called after its regions have been extracted. It *would* work if the region search was moved from `backend.get_lint_regions` to `linter.Linter.get_regions` where plugins could override it and choose a different selector depending on the availability of eslint plugins.

**Comment by kaste** [comment]
I've been playing around with this. Short for `source.js - source source - text source` could be `source.js - text`? Embedded `source` in `source`, is that a thing even?

What's nice here is that for `source.js | text.html.basic` using this with a html file `find_by_selector` selects automatically the widest possible region, which is the complete html file. So, our peek `score_selector(0, ...)` is really premature optimization (we didn't measure). I actually implemented this bc I thought I had to.

**Comment by FichteFoll** [comment]
I knew that `find_by_selector` selects the widest region set possible with the given selector, but I was questioning the performance of that. I asked you about that earlier since I didn't test it locally, but it seems like you missed that.

**Comment by kaste** [comment]
Just for the documentation:

I would (maybe) prefer

```
"selector": "source.js, text.html.basic"
```

over 

```
"selector": "source.js | text.html.basic",
```

**Comment by FichteFoll** [comment]
They are equivalent, so it comes down to personal preference. I think I prefer pipes because of the similarity to the logical or operator (or unions with Python sets).

**Comment by braver** [comment]
The similarity to CSS selectors is on purpose, therefore `,` is what I'd expect and what most color schemes use. That said, I didn't even know pipes were a thing here. 🤷‍♂️

**Comment by FichteFoll** [comment]
Good point. I also use them for color schemes (but mostly due to [CSScheme](https://github.com/FichteFoll/CSScheme)).
Either way, it doesn't matter.

**Comment by kaste** [comment]
Fixed via #1007

**Comment by FichteFoll** [comment]
Any comments on my proposed compatibility layer or do we just deprecate 'syntax' and ask linters to specify a selector instead?

**Comment by kaste** [comment]
ATM we're already compatible afaik.
