### ISSUE TITLE
syntax_map only allows one linter

### ISSUE THREAD

**Issue by ipkpjersi** [SublimeLinter/SublimeLinter#692]
Hello,

I found an issue. There can only be one active linter in syntax map. For example, if I do this: ![](https://i.imgur.com/jQmoBjt.png) then ESLint works on PHP files, but PHP linters no longer work on PHP files. If I remove that, then ESLint no longer works on PHP files but PHP linters work fine again. I want PHP and JavaScript linters to be able to work on PHP files at the same time. Both VSCode and Atom have this functionality.

Thank you.

**Comment by braver** [comment]
You only need to update the syntax map to map variant languages to the main language (e.g. javascript (babel) to javascript). Embedded syntaxes are supported and ESLint should work in HTML, possibly also in PHP. If that doesn't work for you, please open an issue at the eslint plugin repo.

**Comment by kaste** [comment]
@ipkpjersi  PTAL @ PR #994

**Comment by kaste** [comment]
Fixed via #1007
