### ISSUE TITLE
[beta] Add blacklist to hide errors from the panel

### ISSUE THREAD

**Issue by FichteFoll** [SublimeLinter/SublimeLinter#710]
For some linters or errors, I don't want to see a summary in the panel, e.g. the annotations plugin.

**Comment by braver** [comment]
You can add filtering arguments when you call toggle_panel. See the keybindings settings for how to do that. Would that work for you?

**Comment by FichteFoll** [comment]
Can you exclude certain linters? From how the invocation looks like, I assume it's an "include only" type of filter.

**Comment by braver** [comment]
Yes, I think it’s a whitelist. @pykong

**Comment by pykong** [comment]
Indeed it is whitelisting only.

**Comment by pykong** [comment]
Solved by referenced PR. Discussion may continue over there.

**Comment by braver** [comment]
fixed in #798
