### ISSUE TITLE
[beta] enable path shortening with untitled views

### ISSUE THREAD

**Issue by braver** [SublimeLinter/SublimeLinter#727]
Now, path shortening is skipped if there are untitled views. Previously it tried something but failed (at least on macOS) and produced this:

<img width="642" alt="screen shot 2017-12-20 at 10 19 23" src="https://user-images.githubusercontent.com/2543659/34199919-8da4cac4-e56f-11e7-8f85-f13625f7f444.png">

(if `panel.py` line 41 is `common_path = os.path.commonprefix([path + '/' for path in paths if path and not path.startswith("<untitled")])`).

Ideally path shortening works all the time and doesn't mangle the "path" of untitled views.

**Comment by FichteFoll** [comment]
Right ... I think I know why this happens 🤦‍♂️ .

**Comment by kaste** [comment]
Em, this is fixed, isn't it?

**Comment by braver** [comment]
Nope. It is not broken per se, but as soon as you have an untitled view, all other views are represented by the absolute path to the file instead of a nicely shortened one:

<img width="747" alt="screen shot 2018-01-10 at 22 47 45" src="https://user-images.githubusercontent.com/2543659/34797316-52f53d2e-f658-11e7-9594-99ff144affe8.png">

**Comment by FichteFoll** [comment]
flake8 is pyflakes + pycodestyle, essentially, plus other optional plugins
pylint is separate (and *very* verbose and powerful. I don't use it as it produces too much noise and needs too much fidling with default settings)

I have this on my todo btw, but can't tell when I'll get to it. Didn't work out today at least.
