### ISSUE TITLE
Separate hotkeys for goto error and goto warning

### ISSUE THREAD

**Issue by pribilinskiy** [SublimeLinter/SublimeLinter#73]
Currently there are two hotkeys available

> sublimelinter_goto_error direction next
> sublimelinter_goto_error direction previous

the limitation here is that goto_error also acts as goto_warning

having ability to setup additional hotkeys to step through warnings would be awesome

> sublimelinter_goto_warning direction next
> sublimelinter_goto_warning direction previous,

and, of course, goto_error should step through errors only

to step through errors/warnings additional hotkeys could be specified:

> sublimelinter_goto direction next
> sublimelinter_goto direction previous,

**Comment by braver** [comment]
We're going with a solution where you can set up differently filtered output panels, and list errors and warnings separately if you want. This will also allow you to browser errors and warnings separately using hotkeys. This is already available in [the beta](https://github.com/SublimeLinter/SublimeLinter/tree/15bb4a2e2024a623f60bb444eadd5790764fdfb9#sublimelinter-4-beta).
