### ISSUE TITLE
[beta] Publish jsonschema as dependency and implement settings validation

### ISSUE THREAD

**Issue by pykong** [SublimeLinter/SublimeLinter#742]
`jsonschema` represent the de facto standard implementation of the json schema protocol in python.
We like to use it for validations, so the user can be informed about malformed settings.

Especially since SublimeLinter settings have grown to be complex in terms of numbers of options and nesting, such validation would be very helpful.

The `jsonschema` library is rather big and we like to keep it out of the SublimeLinter code base, hence publishing it as separate entity makes sense. A big additional advantage is that other plugins may use settings validation in the future.

Link:
https://github.com/Julian/jsonschema

**Comment by braver** [comment]
@pykong this isn’t done yet?
