### ISSUE TITLE
[beta] perf: `update_gutter_icons` called per `on_activated_async`

### ISSUE THREAD

**Issue by kaste** [SublimeLinter/SublimeLinter#749]
https://github.com/SublimeLinter/SublimeLinter/blob/c6438d25748f2ad50e61ec96570e12b715d8fe93/sublime_linter.py#L97-L102

https://github.com/SublimeLinter/SublimeLinter/blob/c6438d25748f2ad50e61ec96570e12b715d8fe93/lint/settings.py#L58-L64

I don't know why we do `settings.load()` per activate anyway. It doesn't take an argument, and seems global. Maybe the call in `plugin_loaded` is enough.

**Comment by braver** [comment]
I think those are remnants of how it used to try to optimize around settings changes or something. We don’t have to call settings.load on activate.
