### ISSUE TITLE
[beta] PythonLinter has its own `expand_variables`

### ISSUE THREAD

**Issue by kaste** [SublimeLinter/SublimeLinter#750]
Currently PythonLinter 'expands' strings in settings (e.g. `{project_path}`) using its own mechanism. 

Since SublimeLinter comes with its own settings tokens replacement thing, we should use it instead. Maybe this just works and we can remove `expand_variables` and hope `get_view_settings` already does the correct thing.

**Comment by braver** [comment]
Yes, this does sound a bit superfluous. I don't really know how to test if removing it breaks anything?

**Comment by kaste** [comment]
Prima. I didn't even knew about *settings tokens replacement thing*, otherwise I would have used it. 🍭

**Comment by FichteFoll** [comment]
Same https://github.com/SublimeLinter/SublimeLinter/pull/581#issuecomment-356323907.
