### ISSUE TITLE
[beta] Jump to next/previous change jumps to incorrect line

### ISSUE THREAD

**Issue by gerardroche** [SublimeLinter/SublimeLinter#755]
When a file is linted SL uses the built-in `next_result` and `prev_result`. When you delete lines then the next/prev line positions are incorrect i.e.  `next_result` and `prev_result` are not updating to reflect the line number changes due to the delete.

# Steps

* Open a file with several lint errors
* `F4` to jumpt ot the first result
* Delete some lines before the current line (first result)
* Press `F4` which should now jump to the 2nd result line number minus the count of lines you deleted

# Expected 

Jump to correct number.

Also, notice that the jumps are not taking into account the cursor position i.e. when you jump to the first result and then move the cursor above that result, then you kinda expext the next result to be the next one after the curor position.  

# Environment

ST 3154
Latest SL version.

**Comment by pykong** [comment]
@gerardroche Thank you for your report!

> Also, notice that the jumps are not taking into account the cursor position i.e. when you jump to the first result and then move the cursor above that result, then you kinda expext the next result to be the next one after the curor position.

PR #752 implements a synchronisation between view and panel.

**Comment by FichteFoll** [comment]
In theory, the panel should be updated when you edit the view. Either linter output should disappear, if it's on saved files only, or the results should be updated with the line and column numbers, obviously.

**Comment by braver** [comment]
> Either linter output should disappear, if it's on saved files only

If you do that you lose the ability to view and go through the list of errors. 

> results should be updated with the line and column numbers

This happens when you save again.

As much as I would like the panel to be live synced to the buffer, that’s not how it works: it will get out of sync, and then it syncs back up. Build systems work exactly like that too. It’s not perfect but it’s easy enough to understand.

**Comment by FichteFoll** [comment]
>If you do that you lose the ability to view and go through the list of errors.

I know, but this is what has always happened with that linting style. At least since SL3, as I don't remember any older version anymore tbh.

**Comment by braver** [comment]
#752 won't fix this unless you run SL in background linting mode. Perhaps we should solve #715 with something like the old solution, not by enhancing our usage of the output panel.

**Comment by braver** [comment]
#788 fixes this. #752 may additionally improve the UX of the panel.

**Comment by gerardroche** [comment]
This doesn't fix this. In fact it seems a little worse, but the worse part was probably same before, I just didn't hit upon that context.

Now, when your cursor is in the current file and you press `F4`, it jumps straight to another file. I assume because the files in the diagnostics panel are sorted.

The No jump to next/previous (current buffer only) feature is a deal breaker for me. I've been trying LSP again. If that doesn't pan out (and I don't think it will, there are some useful features like the symbol references and mypy for python, but completions are inherently broken or impoverished; even if I do disable it I'll still use the symbol references feature and mypy features from time to time), so if *doesn't* pan out, I'll probably end up keeping SL disabled. 

Even things like "Lint this view" are intrisicly broken, IMO. I know it's by design so I'm not they are bugs e.g. each time you lint a view it's added to the build panel results with previous lints so F4 jumps from file to file which is out side of the bounds of the context, which is "this view".

**Comment by braver** [comment]
@gerardroche I can't make sense of most of your reaction (rant?) here, but you should really read the #788 PR, check the new keybindings: https://github.com/SublimeLinter/SublimeLinter#key-bindings. 

If you still have a problem with the current state of SL4 you may want to state this in a way that I can understand and relate to, and that motivates someone to do something about it. It's not like we're not trying to make SL4 as excellent as it can be. Your reactions tend to radiate negative energy that I'm not sure is because communicating via internet is hard.

**Comment by gerardroche** [comment]
Sorry about the rant. I didn't read all the threads. I assumed dedicated next/previous were not being added, they were ruled out a while ago, and `F4` was still the key for jumps. Those new commands *do* actually jump to next/previous correctly. Again, sorry about the rant.
