### ISSUE TITLE
Last hit_time is irrelevant to invalidate/abort a lint

### ISSUE THREAD

**Issue by kaste** [SublimeLinter/SublimeLinter#758]
Throughout our code we do something like

https://github.com/SublimeLinter/SublimeLinter/blob/d2f87bace77e520488ba4b37edf01c460f6c0125/sublime_linter.py#L227-L228

to decide if we should abort the linting. But the hit_time is irrelevant. a) it is coupled with the view.id() which is irrelevant in this regards bc only the underlying buffer matters. b) if you don't lint in `background` mode, you can easily alter the view before linting has finished: 

![image](https://user-images.githubusercontent.com/8558/34500313-83808376-f00a-11e7-8f20-a70ae9b6e90f.png)

(above: \<ctrl-s> then (quickly) add new lines above)

We should explore if `view.change_count()` fulfills our needs.

**Comment by kaste** [comment]
Candidates for this check: change_count(), just the (source) code, or a md5/sha hash of the source code.

**Comment by FichteFoll** [comment]
Is change_count view- or buffer-specific?

**Comment by kaste** [comment]
buffer-specific

From Sublime docs

> Returns the current change count. Each time the buffer is modified, the change count is incremented. The change count can be used to determine if the buffer has changed since the last it was inspected.
