### ISSUE TITLE
Consider taking ownership of SublimeLinter-eslint plugin

### ISSUE THREAD

**Issue by Standard8** [SublimeLinter/SublimeLinter#759]
Hi, I've been in contact with @roadhump who is the original owner of the SublimeLinter-eslint plugin. They have said that they don't use Sublime any more, and hence won't be maintaining the plugin and are prepared to transfer it.

Personally I don't use Sublime either, but I support people who do, so I'd like to see the plugin supported.

Is moving the plugin to the SublimeLinter organisation a possibility? ESLint seems to be highly regarded in the javascript community now, so getting someone to support it would be very useful.

**Comment by Standard8** [comment]
The existing repository for the plugin is https://github.com/roadhump/SublimeLinter-eslint

**Comment by braver** [comment]
Sounds like a good idea. @roadhump can transfer the repo to me personally and I’ll then move it to the SL group.

**Comment by braver** [comment]
Ok, this happening one way or the other.
