### ISSUE TITLE
[beta] Incorrect file paths for lint errors (SublimeLinter 4)...

### ISSUE THREAD

**Issue by thezimmee** [SublimeLinter/SublimeLinter#760]
I couldn't find another issue that described this, which surprised me because it seems it would be an obvious bug and would be known. So maybe I'm doing something wrong, I just don't see what. I'm using the SublimeLinter4 pre-release, and the linter errors do not point to the correct filepaths. When I navigate through the filepaths in the output linter errors, it pulls up an empty file. The best way to describe is to show, so here is a video of what I'm talking about:

http://take.ms/CbRAo

As an example, the first time it opens a file it opens this path:

~/Projects/brikcss/tim/lib/boot/**brikcss/tim/lib/boot**/[filename]

where the bold part repeats itself. In fact, each time I navigate to a lint error SublimeLinter pulls up a new file, even though it had already pulled up what it thought to be the correct file (but was incorrect). So the more I navigate through errors, the more empty files that are opened by SublimeLinter. It looks like it's not operating on the correct root or something. But as is I can not navigate through any errors, which makes it hard to know where they are.

I don't see any errors in the console or anything out of the ordinary. Here is my SublimeLInter user config:

```
// SublimeLinter Settings - User
{
	"gutter_theme": "Default",
	"lint_mode": "background",
	"no_column_highlights_line": true,
	"@python": "/Library/Frameworks/Python.framework/Versions/3.6/bin/python3",
	"linters": {
		"annotations": {
			"@disable": false,
			"args": [],
			"errors": ["@FIXME", "@fixme", "@BUG", "@bug", "@TODO", "@todo"],
			"excludes": [],
			"warnings": ["@NOTE", "@note"],
			"mark_style": "fill",
			"priority": 1,
			"scope": "region.yellowish markup.changed.sublime_linter markup.warning.sublime_linter",
			"icon": "dot",
			"types": ["warning"]
		}
	},
	"styles": [
		{
			"mark_style": "fill",
			"priority": 1,
			"scope": "region.yellowish markup.changed.sublime_linter markup.warning.sublime_linter",
			"icon": "dot",
			"types": ["warning"]
		},
		{
			"mark_style": "fill",
			"priority": 1,
			"scope": "region.redish markup.deleted.sublime_linter markup.error.sublime_linter",
			"icon": "dot",
			"types": ["error"]
		}
	]
}
```

Thanks for your help.

**Comment by pykong** [comment]
Likely related to #727

**Comment by braver** [comment]
Can you check if this still occurs in the latest pre-release (rc9.1)?

**Comment by thezimmee** [comment]
Just upgraded, and it works! Works from my end. Thank you!
