### ISSUE TITLE
[beta] Parse Error when constructing the tooltip if the linter text contains single quote

### ISSUE THREAD

**Issue by andyghiuta** [SublimeLinter/SublimeLinter#765]
When hovering the gutter to display the tooltip, with the linter output, only the count and the type (eg: 1 warning / jshint: W - ) is shown, without the actual message.
In the Linter Panel the text is shown in full: `53:23  	warning	      jshint: W           	'undefinedFunction' is not defined.`
In the standard Console, the following error is shown: 
```
Parse Error: #x27;undefinedFunction&#x27; is not defined.</div>
        </div>
            </body>
         code: Unexpected character
```
It seems to me that the single quote encoding (`&#x27;`) is causing the issue.

**Comment by pykong** [comment]
Also see: #738 #706

**Comment by braver** [comment]
Cannot reproduce this in SublimeLinter4 with JSHint.
