### ISSUE TITLE
Wrong column number on first line of selector based lintings

### ISSUE THREAD

**Issue by kaste** [SublimeLinter/SublimeLinter#767]
As you can see, a col offset must be applied to the first line.

![image](https://user-images.githubusercontent.com/8558/34603285-9edf776c-f203-11e7-8ac7-6c03b55962b1.png)

I actually got this bug from code reviewing, and I have a fix.

**Comment by kaste** [comment]
Yeah okay, but when you add something like this

https://github.com/SublimeLinter/SublimeLinter/blob/78d42361daaacbd71865f4c5c21a96c97fd3239e/lint/linter.py#L762-L775

then you actually already know that your own API doesn't fit your need. Obviously, you find bugs in here.

First, we reset the linter with `reset(code)`, then we patch it `linter.code = code[region.begin():region.end()]`. 

And why is `lint(...)` a 'pure side effect method' that doesn't return any results, but instead populates some members I have then to inspect? But of course, a linter can't be reused, but must be reset before each use.  When can't reuse linters then we could throw them away after use.

👿

**Comment by kaste** [comment]
Okay, I would like to refactor this, so that `lint` actually just returns the lint errors as a plain list. Merging errors becomes then trivial bc we can just append more and more errors to this list. If we're finished, we can just do a goup_by operation on that data structure. (`persist.errors` is a grouped view of this errors list.)

**Comment by braver** [comment]
Yeah, much of SL is like that. It's bewildering really. It cannot be designed like that, right? 🤷‍♂️

**Comment by braver** [comment]
> I would like to refactor this

I'm not going to stop you man.
