### ISSUE TITLE
Errors on column 0 get a length of 0

### ISSUE THREAD

**Issue by kaste** [SublimeLinter/SublimeLinter#769]
![image](https://user-images.githubusercontent.com/8558/34603907-270fe7be-f206-11e7-93a0-359114d39ccc.png)

**Comment by kaste** [comment]
I have a fix for this too

**Comment by braver** [comment]
You know, if everyone who finds something wrong also comes with a fix, the world would be a better place. Thanks man!

**Comment by pykong** [comment]
@kaste You are awesome, dude!

**Comment by kaste** [comment]
@pykong  👋
