### ISSUE TITLE
[beta] Output panel name

### ISSUE THREAD

**Issue by buildersbrewery** [SublimeLinter/SublimeLinter#775]
Why is the output panel named `Sublime Linter Panel` instead of `SublimeLinter Panel`?

---

I'd also vote for changing the `Panel` substring to something more meaningful.

**Comment by FichteFoll** [comment]
"Error Panel" maybe? I think the panel is enough personally, though.

Also +1 for removing the space.

**Comment by braver** [comment]
How about:

<img width="351" alt="screen shot 2018-01-07 at 11 02 39" src="https://user-images.githubusercontent.com/2543659/34648493-6261fd76-f39a-11e7-995a-fe025069222c.png">
