### ISSUE TITLE
Does backup of old settings (after the upgrade) work?

### ISSUE THREAD

**Issue by LeEnno** [SublimeLinter/SublimeLinter#779]
Just 3 things I stumbled when upgrading to the beta following the upgrade section in https://github.com/SublimeLinter/SublimeLinter/blob/master/messages/4.0.0-rc.1.txt:

1. `mark_style` appears twice under removed settings.
2. "Your old settings will be backed up to SublimeLinter old.sublime-settings" → didn't happen for me.
3. Older versions of the plugin had source files under `Packages/User/SublimeLinter` which I tweaked to get around a bug. This seems to not be the case anymore. You could add that to the guide.

(BTW: great to see the project moving forward 👍)

**Comment by braver** [comment]
Thanks for reporting!

> "Your old settings will be backed up to SublimeLinter old.sublime-settings" → didn't happen for me.

Oh, I'll need to check that, that would be a bug.

**Comment by FichteFoll** [comment]
Have you restarted ST after the update? I think the backup is only performed after the next restart because of module loading issues after a partial unload.

**Comment by LeEnno** [comment]
I probably did not but will try again.

**Comment by braver** [comment]
> I think the backup is only performed after the next restart because of module loading issues after a partial unload.

Yes, I just found that out too. SL doesn't load successfully the first time because we need a dependency now. After a restart it does back up, but only if you user settings contains the `"user"` key.

**Comment by LeEnno** [comment]
So to get that straight, the correct order would be:

1. Add SublimeLinter to `install_prereleases` in Package Control.
2. Restart.
3. Wait for install message to appear.
4. Restart.

And the old settings file should be backed up?  
Or am I getting this wrong?

**Comment by braver** [comment]
Jup, that should be it.

**Comment by FichteFoll** [comment]
You can skip the first restart by explicitly telling PC to update SL with *Package Control: Upgrade Pacakge*.

**Comment by LeEnno** [comment]
Yes, this works.

![image](https://user-images.githubusercontent.com/2038814/34731262-28663546-f562-11e7-8d59-e60a189e3d7b.png)

**Comment by LeEnno** [comment]
The other 2 things I mentioned in the opening post are already taken care of? (`mark_style` and no source files anymore)

Also I would suggest to mention the double restart (or the explicit upgrade via command palette) in the readme where people probably go to find out how to install the beta.

Anyway, thx for helping 👍

**Comment by braver** [comment]
Yeah I covered those in 66d8bfb.

Thanks!
