### ISSUE TITLE
[beta] [cpplint] errors and warning only showing on unmodified files

### ISSUE THREAD

**Issue by Gliptal** [SublimeLinter/SublimeLinter#780]
It seems like the "background" setting isn't working with [cpplint](https://github.com/SublimeLinter/SublimeLinter-cpplint): with the following settings (excerpt)

````
"delay": 0.3,
"lint_mode": "background",
````

errors and warnings are shown only on unmodified files. As soon as the file is modified, all errors disappears from both the gutter and the code: they subsequently reappar as soon as the file is saved. Is this something that can be fixed within SL4, or is it a problem with the linter?

Other linters work as expected.

Windows 10 1709 (16299.192)
Sublime Text 3 (3143)
SublimeLinter v4.0.0-rc.9.3

**Comment by FichteFoll** [comment]
SublimeLinter-cpplint only runs on saved files due to this line:

https://github.com/SublimeLinter/SublimeLinter-cpplint/blob/master/linter.py#L22

http://www.sublimelinter.com/en/latest/linter_attributes.html#file-only-linters

**Comment by Gliptal** [comment]
Thank you, makes sense.
