### ISSUE TITLE
Missing Information in documentation!

### ISSUE THREAD

**Issue by ugajin-nijagu** [SublimeLinter/SublimeLinter#785]
I followed the instructions here: http://www.sublimelinter.com/en/latest/installation.html# [Revision 15bb4a2e], which do not appear to say anything about installing the jshint packages globally.

There is a note which says: 
> Most linter plugins require you to install a linter binary or library and configure your PATH so that SublimeLinter can find it. You must follow the linter plugin’s installation instructions to successfully use it.

A link to this page may help:
https://github.com/SublimeLinter/SublimeLinter-jshint#installation

**Comment by FichteFoll** [comment]
You *can* install it somewhere else as long as you ensure the binary is in PATH. Global installation is recommended because it is automatically added to your system's PATH.

**Comment by ugajin-nijagu** [comment]
> You can install it somewhere else as long as you ensure the binary is in PATH. Global installation is recommended because it is automatically added to your system's PATH.

@FichteFoll Are you missing my point?

**Comment by FichteFoll** [comment]
I'm not seeing your point, indeed. The [SublimeLinter-jshint](https://github.com/SublimeLinter/SublimeLinter-jshint) package clearly indicates that `jshint` should be installed on your system and be made available on PATH. It even includes the command line `npm install -g jshint` to run.

http://www.sublimelinter.com/en/latest/installation.html#linter-plugins clearly points towards reading each linter's installation instructions.

**Comment by ugajin-nijagu** [comment]
@FichteFoll 
Please point to where on the http://www.sublimelinter.com/en/latest/installation.html#linter-plugins page is there a link for  'The SublimeLinter-jshint'  [https://github.com/SublimeLinter/SublimeLinter-jshint] ? 

My point is simply, that such a link, would help.

**Comment by braver** [comment]
It clearly states:

> You must follow the linter plugin’s installation instructions to successfully use it.

When you install a linter plugin, a message is displayed with a link to the respective repo and readme. We're not going to list all 130+ linters in the docs.

**Comment by ugajin-nijagu** [comment]
The instructions are not clear. Now you can close issue [or not] as you like.
