### ISSUE TITLE
[beta] RubyLinter is not lazy

### ISSUE THREAD

**Issue by kaste** [SublimeLinter/SublimeLinter#787]
As mentioned in #782 `RubyLinter` loads eager. It is thus prone to err on fast start-ups on OSX bc if the `env[PATH]` is not immediately ready and good to use, it will disable itself bc it cannot find any reasonable executable.

Note: `RubyLinter` has its own interpretation of how and what extension points `Linter` provides. It should really implement `can_lint` and `context_sensitive_executable_path` to be lazy.

**Comment by braver** [comment]
I'm labeling this as a bug not because something breaks exactly, but I do believe our enhanced performance means this will feel like a regression for ruby users because they will run into this problem a lot more often (I sure did with the node linters).

**Comment by braver** [comment]
@kaste I have zero experience with Ruby. I'm debating whether to try and do something about it before release, and just releasing and hope that a Ruby user turns up and contributes a fix... How do you feel about this?

**Comment by kaste** [comment]
Dumb and dumber meeting again 😺 

I could provide a rewrite, how it should look like. But zero ways to test it. 🍭

**Comment by kaste** [comment]
Ugh, we actually ship a broken version and nobody called.

**Comment by braver** [comment]
I have no idea how many people you reach with a beta like this but in the end it's open source. If people want something nice sometimes they will have to go out and get it themselves. 

We'll just see what happens then.

**Comment by kaste** [comment]
Ok, PR is #819

**Comment by kaste** [comment]
You can see in the PR it's really the same thing in a different package.

**Comment by braver** [comment]
I can certainly live with that. Thanks!
