### ISSUE TITLE
The panel should order the files/views in a useful way

### ISSUE THREAD

**Issue by kaste** [SublimeLinter/SublimeLinter#791]
Currently, we show them in arbitrary order. Technically we loop over a dict, so this is order is also not stable.

I propose that we order in a last-recently-used way. This would also mean, that the current, active view is always on top, if I open the panel. Old views, move slowly down. This reflects that I'm apparently not very interested in fixing them yet, bc I need to fix, write code in other views first.

**Comment by braver** [comment]
Please see #681 . It had been closed erroneously before, assuming #752 would provide a solution for it. I'll quote your comment there.
