### ISSUE TITLE
Render lint errors as they arrive 

### ISSUE THREAD

**Issue by kaste** [SublimeLinter/SublimeLinter#792]
The new async backend runs linters in parallel. E.g. it runs `flake8` and `mypy` concurrently even for the same file/view. However, it waits for both to finish (fan-in), before it passes the errors back to our views which then update, e.g. draw gutter marks.

We could instead pass the errors as they arrive. This would result in multiple renders, so it could be that we put too much pressure on Sublime.

**Comment by kaste** [comment]
Oh, you know that I don't get notifications for 👍 

So, shut up. I want to leave my notes here.

The implementation here is not completely trivial. Currently the data structure is almost flat, we only group by `buffer_id`. If we don't fan-in, we must merge the data in our callback. For (view, linter) pairs this is simple bc they translate to (buffer_id, linter_name). However, this doesn't work for our selector based, virtual view based, lintings. E.g. we a html file with two script tags. We run eslint twice in parallel, but from outside we cannot have a differentiator here, we'd need (bid, linter_name, x) here, but I don't see it. 

So currently it seems that we need a group by (linter) operation, where we still fan-in in the backend, and a merge operation in the callback. E.g. the html file above, we start *three* `lint`s concurrently, html once, and eslint twice. But we call the callback only two times, once for html, once for eslint.

**Comment by FichteFoll** [comment]
`x` could be the point at which the region to be linted starts. For whole-file lints, it would just be 0.
