### ISSUE TITLE
[beta] Enhancement: Add a "Toggle debug mode" as a menu item or a Command Palette item.

### ISSUE THREAD

**Issue by mandx** [SublimeLinter/SublimeLinter#794]
While the `debug` setting exists, debug mode could also be useful for the user to diagnose linter configuration, not just to help the development of SublimeLinter itself.

SublimeLinter 3 had this and that was the one menu item I used the most, since I tend to keep linter executables scoped inside project folders, instead of installed globally. This is only one thing I miss when I switched from SublimeLinter 3 to SublimeLinter 4-beta.

**Comment by braver** [comment]
I don’t want to restore any commands that change settings. Having to debug your SL setup shouldn’t be something you do every day. There is a command to open your settings, it should be easy enough to quickly edit that, e.g. uncomment the “debug” line.
