### ISSUE TITLE
[beta] Error trying to parse Linux keymap

### ISSUE THREAD

**Issue by ipkpjersi** [SublimeLinter/SublimeLinter#795]
Hello,

The default Linux keymap that the SublimeLinter package comes with produces an error. The error is: ![idngba1](https://user-images.githubusercontent.com/33754783/34903272-2a34c0c4-f826-11e7-842c-129bf3fa937e.png)

Here is where the error seems to be: ![z2o1xwd](https://user-images.githubusercontent.com/33754783/34903274-36c41830-f826-11e7-9c6c-07dbe9325dbb.png)

Here is the keymap file: https://hastebin.com/irowuqokoy.coffeescript

Thank you.

**Comment by braver** [comment]
Fixed!
