### ISSUE TITLE
[beta] refactor: statusbar shouldn't update panel

### ISSUE THREAD

**Issue by braver** [SublimeLinter/SublimeLinter#800]
The statusbar and the panel are updated in the same event_listener. That's a good idea from a performance standpoint, but it's not very transparent that that code lives in statusbar. 

See also: https://github.com/SublimeLinter/SublimeLinter/pull/797#pullrequestreview-88666942

**Comment by kaste** [comment]
Fixed in #822

**Comment by pykong** [comment]
Fixed by: #822 
@kaste Just in case you did not know it.

You can reference issues in a PR, like this:
Fixes: #822 

Once the PR gets merged the issue gets closed automatically.
