### ISSUE TITLE
[beta] Highlight all errors under cursor in panel

### ISSUE THREAD

**Issue by kaste** [SublimeLinter/SublimeLinter#803]
Here I'm on pos 1:1. It would be cool if both lines were highlighted

![image](https://user-images.githubusercontent.com/8558/34918809-966f25d4-f959-11e7-897e-b230a1d67841.png)

**Comment by pykong** [comment]
This suggestion has been raised in the past.

Indeed I think it is a good suggestion.

Maybe related to #804
