### ISSUE TITLE
[beta] For multiple errors on the same position, jump to the next position, not the next error

### ISSUE THREAD

**Issue by kaste** [SublimeLinter/SublimeLinter#804]
Here, again my cursor is at 1:1. If I hit F4, I currently 'jump' to the next error in the list, which is still on 1:1, but I expect to go to 1:13.

![image](https://user-images.githubusercontent.com/8558/34918835-060ce610-f95a-11e7-93fe-d2be9d8f9a69.png)

(If I'm at pos 1:13, pressing shift-F4 actually jumps to the first 1:1 in the panel list. So it jumps correctly *over* the D101 error.)

**Comment by pykong** [comment]
@kaste can you tell whether this behavior has been introduced by #797?

**Comment by kaste** [comment]
Sorry, I can't, before your PR I actually never used F4 movement, bc it was just too confusing for me. It always jumped all over the places to whatever file. So I basically used the panel only with the mouse double click.

**Comment by braver** [comment]
We do not control what F4 does in any way and I don't think we can (or should even try) because it would break the pattern. This behaviour therefore hasn't been introduced in any way by us.

**Comment by pykong** [comment]
#803 implies a possible easy fix. If we extend the panel selection to encompass multiple lines this may well do the trick.

**Comment by kaste** [comment]
I hoped for that as well 🐈
