### ISSUE TITLE
Error columns for virtual views need to be adjusted or the content not dedented

### ISSUE THREAD

**Issue by FichteFoll** [SublimeLinter/SublimeLinter#805]
When linting virtual views (I think that's the canonical name), the output seems to be dedented, which leads to the column that the linter outputs being wrong and offset by the number of characters/spaces that were removed.

Following is an example that shows this with HTML:

```
<script>
  var link = document.createElement( 'link' );
  link.rel = 'stylesheet';
  link.type = 'text/css';
  link.href = (window.location.search.match( /print-pdf/gi )
               ? 'css/print/pdf.css'
               : 'css/print/paper.css');
  document.getElementsByTagName( 'head' )[0].appendChild( link );
</script>
```

![2018-01-14_18-43-36](https://user-images.githubusercontent.com/931051/34918892-f1eac750-f95a-11e7-8b79-0e17b98a2a23.png)

```
<untitled 232>:
     6:14   warning       jshint: W014         Misleading line break before '?'; readers may interpret this as an expression boundary.
```

It works when the line has less indentation than the rest of the block

![2018-01-14_18-45-26](https://user-images.githubusercontent.com/931051/34918902-259dc566-f95b-11e7-806a-000989b8d3cc.png)

**Comment by braver** [comment]
Good catch. I have noticed this before but forgot to log an issue. It's not a regression in SL3 ➡️ SL4 as far as I could tell, but it's there.

**Comment by kaste** [comment]
That's somehow a bug with jshint. eslint works here.

**Comment by kaste** [comment]
Look at the raw output from jshint (using the console). But note that jshint actually could lint `html` files. So this selector based approach seems redundant, outdated.

**Comment by FichteFoll** [comment]
Well, just because jshint can lint html files directly it doesn't mean that the entire approach is redundant. It can't lint javascript embedded in markdown, for example, but I'm not sure if that is even supported by the virtual view feature. I don't usually do stuff in this area.

**Comment by kaste** [comment]
Fix me: I looked at the jshint plugin and it doesn't seem to use the selector based approach, hence no virtual views. 

@FichteFoll tabs or spaces?

**Comment by kaste** [comment]
Maybe it would work, if it used our virtual view feat. 😸

**Comment by FichteFoll** [comment]
Spaces here.

**Comment by kaste** [comment]
@braver You didn't merge https://github.com/SublimeLinter/SublimeLinter-jshint/pull/108 Intended or mistake?

**Comment by braver** [comment]
@kaste you said not to merge before a feature was merged into core, but wouldn’t that also mean it will render it incompatible with SL3? So I could merge it but hat would block SL3 compatible changes.

**Comment by kaste** [comment]
Hm, I get interesting results here

Correct:

![image](https://user-images.githubusercontent.com/8558/34920514-5893dc76-f974-11e7-8fc7-8c2c27e6d99e.png)

Wrong:

![image](https://user-images.githubusercontent.com/8558/34920531-90fd61b8-f974-11e7-97eb-2e85757b2249.png)

And basically usage via stdin:

![image](https://user-images.githubusercontent.com/8558/34920672-7f287b38-f976-11e7-8b3a-ecfab1dfe742.png)

**Comment by kaste** [comment]
I thought that this a compatible change. But without the merge, it would be redundant.

**Comment by braver** [comment]
Oh, I misunderstood then. I’ll try to test tomorrow and then merge.

**Comment by kaste** [comment]
Fixed via https://github.com/SublimeLinter/SublimeLinter-jshint/pull/109  

![image](https://user-images.githubusercontent.com/8558/34920824-84620396-f979-11e7-88f2-6a729074b112.png)

**Comment by FichteFoll** [comment]
Closing as this doesn't appear to be an issue with the core but jshint.
