### ISSUE TITLE
Add a visual marker in the panel when we are between two errors

### ISSUE THREAD

**Issue by kaste** [SublimeLinter/SublimeLinter#806]
Maybe we could mark a region with underlines. Or do something with Phantoms

**Comment by FichteFoll** [comment]
Underlining sounds pretty great, actually. Didn't think of that.

**Comment by braver** [comment]
I kinda hoped an indicator like that would be superfluous, but now that I used it a bit I'd definitely like a marker. There is some kind of gutter you can enable in the panel right? Can we put an icon in there? I'm thinking along the lines of the lines-removed indicator from GitGutter:

<img width="189" alt="screen shot 2018-01-14 at 19 00 51" src="https://user-images.githubusercontent.com/2543659/34919014-557665ca-f95d-11e7-91e1-93a99c3b3eb5.png">

**Comment by FichteFoll** [comment]
Imo using gutter icons like GitGutter does would be too subtle. The panel is already side information and not supposed to be your main focus. If you add more side info to a side info gadget, things become too unclear. A small line through the entire panel (or at least as wide as the next/previous line) sounds like a good option to me.

**Comment by braver** [comment]
Ok, I don’t disagree. I guess it depends on wether inserting a phantom, even if it’s just a single pixel high, makes everything jump up and down a lot.

**Comment by pykong** [comment]
I really like the idea of having some in-between indicator.
Yet, did not found any satisfying solution to it.

One attempt was to mark only the first two columns of the next error line.
This was an experiment I immediately ditched, as it was difficult to detect.

I am with @FichteFoll here. Certainly a moving gutter marker would look super cool.
Still, I'd rather keep it simple for now, unless simpler solutions prove inadequate.

Using a line as an in-between marker, is also a logical step from
using a selection. It conveys being a zero height, thereby empty selection, squeezed in-between.

**Comment by kaste** [comment]
Hi @pykong Can you develop a prototype of this?

![image](https://user-images.githubusercontent.com/8558/35460458-630044be-02e4-11e8-9d6b-9044036927e7.png)

from https://github.com/SublimeLinter/SublimeLinter/issues/806#issuecomment-357529539

It's basically your code. I know you somehow get the current line in panel.py and also knows if you should select it (full_line). T.i. if we sit on an error to highlight. Also, you did a lot of the gutter stuff in highlights. I did none. 

So it is probably easy. ❓

**Comment by braver** [comment]
> [Edit: My GitGutter looks different so I don't even know if @braver did a mockup here, or if this is real.)

Naw, that's real: `"theme": "Bars.gitgutter-theme",`

**Comment by pykong** [comment]
@kaste Sorry, did not receive the mention or missed it.
As you have noticed, I have now withdrawn from active development.
Still, feel free to summon me here, if there is anything.
