### ISSUE TITLE
Replace `@` and `*` in cmd with self-explanatory templates

### ISSUE THREAD

**Issue by FichteFoll** [SublimeLinter/SublimeLinter#810]
Via https://sublimelinter.readthedocs.io/en/latest/linter_attributes.html#cmd,
`@` and `*` stand for the view's filename and for the computed args respectively.

It would be better if those used some more descriptive names like `{file_path}` and `{args}` (Python format syntax) or `$file_path` and `$args` (ST template format) respectively. Neither `{}` nor `$` should occur in command parameters regularly.

For backwards compat, the old placeholders could be treated as aliases.

**Comment by FichteFoll** [comment]
Also, since `@` is currently replaced with the temp file's path if that exists, there should be a way to have the original file's path substituted too, as would be useful for mypy's `--shadow-file` arg usage.

https://github.com/fredcallaway/SublimeLinter-contrib-mypy/blob/cd6fbaf0cd9c8f52b23df621537fa9276a92bae1/linter.py#L99

Possibly related to #750. I still don't know where these templates are actually used.

**Comment by kaste** [comment]
Would be ${file_path} and ${args}, correct?

Idea for the original_file_path?

**Comment by FichteFoll** [comment]
The braces are optional for ST's template eyntax, but yes, those would work too.

**Comment by kaste** [comment]
So, we need some up or downvotes here, folks. @braver @pykong

**Comment by braver** [comment]
The way SL sometimes treats a single character string to carry meaning is really stupid. IIRC a tempfile_suffix of “-“ also means something special... So upvote for the basic premise of this issue.

**Comment by FichteFoll** [comment]
Good hint about the `-`. That should actually get its own attribute imo.

Regarding the issue at hand, I was wondering whether we could just resort to our favorite `sublime.expand_variables` function and provide some useful variables, like computed args, the original file name, the temp file name, the other convenience variables like file_path etc. Only problem: shell escaping and, for the case of computed args that they are actually multiple arguments. Ideas welcome.

**Comment by kaste** [comment]
So can I just introduce `${args} ${filename} ${tmpfilename}`, bc what is especially confusing is that `@` changes its meaning here.

I still don't know what `-` means. LOL

**Comment by braver** [comment]
> I still don't know what - means. LOL

I found it:

> you can mark a linter as “file-only” by setting :ref:`tempfile_suffix` to ``'-'``.

Probably completely irrelevant to the issue at hand. Just wanted to share this wonderful piece of engineering I found.

**Comment by FichteFoll** [comment]
>So can I just introduce `${args}${file_name} ${tmpfilename}`, bc what is especially confusing is that @ changes its meaning here.

Not exactly. I think currently `Linter.cmd` may be a list or a string, behaving much like `subprocess.Popen` where the string would be split with `shlex` and the list composed of the command and the following args. Now, the problem is that `${args}` would essentially represent *multiple args*, so if you're using the string version, you need to to this:

`cmd = 'cmd ${args} "${file_name}"'` (note the quotes around the file name for spaces)

This works. For the list/sequence, you'd probably do this:

`cmd = ('cmd', '${args}', '${file_name}')`,

but without some special handling, `${args}` would be treated as a *single* parameter, which won't wokr.
