### ISSUE TITLE
[beta] Cannot open panel at start up

### ISSUE THREAD

**Issue by kaste** [SublimeLinter/SublimeLinter#811]
I don't know why but you cannot open the panel on startup. You have to wait until the initial active_view() has been linted.

**Comment by FichteFoll** [comment]
It needs to be created before it can be opened. This should probably happen when SL loads.

**Comment by kaste** [comment]
Bc of an early return

https://github.com/SublimeLinter/SublimeLinter/blob/69d0ea27072ca40ccef077b23512baacb5b696ed/panel/panel.py#L188-L191

it doesn't `ensure_panel`, and so forth.
