### ISSUE TITLE
[beta] RenderLines abstraction is unnecessary

### ISSUE THREAD

**Issue by kaste** [SublimeLinter/SublimeLinter#812]
Generally, `RenderLines` is only used here:

https://github.com/SublimeLinter/SublimeLinter/blob/5ee12b9256605ff57115686b3c61876645de021b/panel/panel.py#L209-L227

Issues: 

Since `to_render` is a simple object without any `__magic__` overrides, it can never be None: 

https://github.com/SublimeLinter/SublimeLinter/blob/5ee12b9256605ff57115686b3c61876645de021b/panel/panel.py#L227

The only useful method, `current_lineno` returns always `len(to_render)` if `to_render` were a simple list.

https://github.com/SublimeLinter/SublimeLinter/blob/5ee12b9256605ff57115686b3c61876645de021b/panel/panel.py#L222

**Comment by pykong** [comment]
That class is indeed a relic and has lived past its time. I'll remove it.
