### ISSUE TITLE
[beta] panel scrolls up if you're below the last error of the current view

### ISSUE THREAD

**Issue by kaste** [SublimeLinter/SublimeLinter#813]
![image](https://user-images.githubusercontent.com/8558/34921948-5ada45f0-f989-11e7-8712-7c2dbf61f180.png)

**Comment by pykong** [comment]
To ensure I understood the issue correctly:
The panel scrolls to the **first** error of of the respective buffer, while the caret is placed below the last error in the view. *Hence the problem is not the up scroll per se, but that it scrolls to the wrong position in the panel.*
