### ISSUE TITLE
[beta] AttributeError: 'module' object has no attribute 'update_panel_selection'

### ISSUE THREAD

**Issue by OdinTech3** [SublimeLinter/SublimeLinter#827]
I am repeatedly getting this error in the sublime text console:

`Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 538, in on_activated_async
    callback.on_activated_async(v)
  File "status_bar_view in /Users/nickmuoh/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 50, in on_activated_async
AttributeError: 'module' object has no attribute 'update_panel_selection'`

I am using sublimelinter v4.0.0-rc.9.9. 

Has anyone else observed this??

**Comment by pykong** [comment]
Thanks fro reporting. That error will be fixed by #822

**Comment by kaste** [comment]
Sidenote: These tracebacks are not helpful. @braver @FichteFoll Can we at least during beta install unpackaged or however this is called. Is this to further punish the developers?

**Comment by OdinTech3** [comment]
What do you suggest then? I presented the trace back thinking it would help? If there is something else you would like me to provide, I am all open to suggestions.

**Comment by kaste** [comment]
Hey, hey this was a sidenote for the other maintainers of this repo. You posted everything you got. That's totally 👍.

**Comment by OdinTech3** [comment]
Alright cool

**Comment by braver** [comment]
> Can we at least during beta install unpackaged or however this is called

Sure, but then you also cannot trust that the contents aren’t tempered with. Also, we will get bug reports after the beta, so we need a reliable way to debug without shenanigans anyway.

**Comment by FichteFoll** [comment]
@kaste why do you think they are not helpful? Because the file/module name is in the front of the traceback path? I complained about that a few times alreay, but wbond (or jps) preferred it that way as opposed to just adding a slash after the archive, as Python does for normal zip-imported files. (It can be modified in `sublime_plugin.py` at the bottom in the ZipImporter somewhere.

**Comment by kaste** [comment]
@FichteFoll 
> Because the file/module name is in the front of the traceback path?

Yes

And it doesn't print the lines. Now here the traceback is short. But if it throws ten and more levels deep?

**Comment by FichteFoll** [comment]
`File "status_bar_view in /Users/nickmuoh/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 50, in on_activated_async`
has line a number, the file it occured in (although kind of obscure) and the function frame.

**Comment by kaste** [comment]
Hm, what are you telling me here @FichteFoll 

That's a normal traceback

```
Traceback (most recent call last):
  File "C:\Dev\Sublime Text 3\sublime_plugin.py", line 513, in on_selection_modified_async
    callback.on_selection_modified_async(v)
  File "C:\Users\c-flo\AppData\Roaming\Sublime Text 3\Packages\SublimeLinter\status_bar_view.py", line 60, in on_selection_modified_async
    panel.update_panel_srelection(**State)
AttributeError: 'module' object has no attribute 'update_panel_srelection'
```

It prints the line, not just lineno

**Comment by FichteFoll** [comment]
Ah right, it doesn't include the line because the traceback module doesn't find the code for the file specified since it's non-standard.

https://github.com/sublimehq/Packages/issues/75#issuecomment-210151158

Should probably create an issue & fix for this on either the packages or the core repo after some experimentation. I propose the packages repo.

**Comment by FichteFoll** [comment]
https://github.com/SublimeTextIssues/Core/issues/2161
