### ISSUE TITLE
util.cd is not thread aware

### ISSUE THREAD

**Issue by kaste** [SublimeLinter/SublimeLinter#828]
Due to async linting you can see something like this in action:

> Already patched
** chdir C:\Users\c-flo\AppData\Roaming\Sublime Text 3\Packages\User** chdir C:\Users\c-flo\AppData\Roaming\Sublime Text 3\Packages\SublimeLinter

SublimeLinter: flake8: wanted executable is 'C:\Dev\python35\Scripts\flake8.exe' 
** chdir C:\Users\c-flo\AppData\Roaming\Sublime Text 3\Packages\SublimeLinter\lint
SublimeLinter: flake8: util.py ['C:\\Dev\\python35\\Scripts\\flake8.exe', '-'] 

What do you think the current dir will be after all this? T.i. when https://github.com/SublimeLinter/SublimeLinter/blob/4cb3dd5903aa83e69b2c4a136c093fd2819eee59/lint/util.py#L604-L606 runs 😒 😶

**Comment by kaste** [comment]
As always wonder why we do 

https://github.com/SublimeLinter/SublimeLinter/blob/4cb3dd5903aa83e69b2c4a136c093fd2819eee59/lint/linter.py#L989-L992

I think we must just pass the wanted `cwd` down the road to `Popen` and set it there.

**Comment by FichteFoll** [comment]
I would prefer that as well.
