### ISSUE TITLE
Warning message when trying to install jshint in terminal 

### ISSUE THREAD

**Issue by erictheofanis** [SublimeLinter/SublimeLinter#830]
Hey I'm trying to get my IDE set up with sublime text and I'm having a hard time getting jshint to install properly. 

I have package controller and node installed. These are the messages I get when I run the npm install command in terminal: 

Erics-MacBook-Air:~ erictheofanis$ npm install jshint
npm WARN saveError ENOENT: no such file or directory, open '/Users/erictheofanis/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/Users/erictheofanis/package.json'
npm WARN erictheofanis No description
npm WARN erictheofanis No repository field.
npm WARN erictheofanis No README data
npm WARN erictheofanis No license field.

+ jshint@2.9.5
updated 1 package in 1.768s
Erics-MacBook-Air:~ erictheofanis$ npm install
npm WARN saveError ENOENT: no such file or directory, open '/Users/erictheofanis/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/Users/erictheofanis/package.json'
npm WARN erictheofanis No description
npm WARN erictheofanis No repository field.
npm WARN erictheofanis No README data
npm WARN erictheofanis No license field.

And this is the message that is coming up on the Sublime debug console:

plugins loaded
SublimeLinter: debug mode: on 
SublimeLinter: temp directory: /var/folders/2_/v4wfm5gx5nlc5j9jxpkcycgr0000gn/T/SublimeLinter3-erictheofanis 
environment variables loaded using: /bin/bash -l
Package Control: No updated packages

Can some one point me in the right direction of how I can get linter working?

**Comment by kaste** [comment]
`npm install -g jshint` 👍

**Comment by erictheofanis** [comment]
thanks! @kaste  Sorry i should have mentioned I'm also getting this error message when using -g: 

Erics-MacBook-Air:~ erictheofanis$ npm install -g jshint
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules
npm ERR! path /usr/local/lib/node_modules
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall access
npm ERR! Error: EACCES: permission denied, access '/usr/local/lib/node_modules'
npm ERR!  { Error: EACCES: permission denied, access '/usr/local/lib/node_modules'
npm ERR!   stack: 'Error: EACCES: permission denied, access \'/usr/local/lib/node_modules\'',
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/usr/local/lib/node_modules' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/erictheofanis/.npm/_l

**Comment by erictheofanis** [comment]
Any idea of what the issue might be?

**Comment by kaste** [comment]
Nope, it wants you to run this with sudo. But this shouldn't be that way. You have to google the error message.

**Comment by braver** [comment]
I dunno, I always have to sudo npm install -g on my Mac. Not a SublimeLinter problem in any case.

**Comment by erictheofanis** [comment]
thanks, I figured it out
