### ISSUE TITLE
Lint errors are being display in the console, but no code highlighting is occurring

### ISSUE THREAD

**Issue by whw** [SublimeLinter/SublimeLinter#833]
PROBLEM: Lint errors are not being highlighted in the source code

DESCRIPTION: When linting a bad python file, I see the lint error occurring both on the command line and in the console, but no highlighting is occurring in the file.

EXPECTED BEHAVIOR: When there are lint errors, I would expect to see outlines or highlights within the code where the lint error is occurring.

CONTEXT:
ST v3.0, Build 3143
OS: 10.12.6
Python: 3.6
I've installed flake8 via pip inside of a conda environment.
I've installed both SublimeLinter and SublimeLinter-flake8 plugin via Package Control

Package Control settings:
```
{
	"bootstrapped": true,
	"in_process_packages":
	[
	],
	"install_prereleases":
	[
		"SublimeLinter",
		"SublimeLinter-flake8"
	],
	"installed_packages":
	[
		"AdvancedNewFile",
		"Copy Relative Path",
		"GitGutter",
		"GitSavvy",
		"Package Control",
		"Pretty JSON",
		"Python PEP8 Autoformat",
		"SideBarEnhancements",
		"SublimeLinter",
		"SublimeLinter-flake8"
	]
}
```

SublimeLinter setting:
```
// SublimeLinter Settings - User
{
	"debug": true,
	"lint_mode": "load_save",
	"linters": {
		"flake8": {
			"executable": "~/miniconda3/bin/flake8",
			"show-code": false
		},
	},
}
```

Console output:
```
SublimeLinter: flake8: wanted executable is '/Users/wwilliams/miniconda3/bin/flake8' 
SublimeLinter: flake8: taxes.py ['/Users/wwilliams/miniconda3/bin/flake8', '-'] 
SublimeLinter: flake8 output:
stdin:4: [F401] 'datetime' imported but unused 
```

Command-line output:
```
> ~/miniconda3/bin/flake8 taxes.py                                                                                                                                                                               
taxes.py:4: [F401] 'datetime' imported but unused
```

**Comment by kaste** [comment]
If you open the panel, usually `ctrl-k, a` do you see any errors? Similiar, does the status bar indicate, that you have errors/warnings?

**Comment by whw** [comment]
Status bar does not show an error. 

Is this the output panel you're referring to?
![image](https://user-images.githubusercontent.com/62686/35118846-fcc7617a-fc47-11e7-8746-eab6fa3602d8.png)

If not, then I'm not sure - ctrl-k cuts a line for me.

**Comment by kaste** [comment]
`ctrl-k, a`

That's the console panel

**Comment by kaste** [comment]
Ah, can you set `"lint_mode": "background",` please.

**Comment by braver** [comment]
@kaste the keybindings are different on a Mac. Also, can't really rely on the keybindings so it's always better to point to the UI, or the command palette.

**Comment by whw** [comment]
Ah, this one:

![image](https://user-images.githubusercontent.com/62686/35120353-b17a34fe-fc4c-11e7-8f94-8c7f1e32fd1a.png)

Appears to be `cmd-ctrl-a` on my machine /shrug

That console shows `No lint errors.`
![image](https://user-images.githubusercontent.com/62686/35120407-dc597f18-fc4c-11e7-8724-4a2aa366bd84.png)

**Comment by kaste** [comment]
In the settings `"lint_mode": "background"` please

**Comment by whw** [comment]
@kaste yup, set it back to `backgound`:

```
// SublimeLinter Settings - User
{
	"debug": true,
	"lint_mode": "background",
	"linters": {
		"flake8": {
			"executable": "~/miniconda3/bin/flake8",
			"show-code": false
		},
	},
}
```

**Comment by whw** [comment]
And if it helps, here are the specific versions of SL and SL-flake8:

`SublimeLinter: v4.0.0-rc9.9`
`SublimeLinter-flake8: v4.0.0-rc.1`

**Comment by kaste** [comment]
There is something with flake8 here.

You get: 

```
stdin:4: [F401] 'datetime' imported but unused
```

I get something like:

```
stdin:4:1: F401 'datetime' imported but unused
```

**Comment by kaste** [comment]
@braver knows regexes. Hey @braver do you think @whw linter output will match https://github.com/SublimeLinter/SublimeLinter-flake8/blob/871754c69e1447478836491ca5292cf644664e73/linter.py#L43-L48

**Comment by whw** [comment]
Interesting - currently on version `3.4.1` of `flake8` if that helps:

```
> ~/miniconda3/bin/flake8 --version 
3.4.1 (mccabe: 0.6.1, pycodestyle: 2.3.1, pyflakes: 1.5.0) CPython 3.6.1 on Darwin
```

**Comment by kaste** [comment]
Usually, you should get a warning if it can't match a line, but I think there is a bug here

https://github.com/SublimeLinter/SublimeLinter/blob/965fba0445a5b7c68b886e5fd229e93c15ae697e/lint/linter.py#L936-L941

The return value of `finditer` is an iterator and always truthy.

**Comment by braver** [comment]
> @braver knows regexes

🤣 

Braver knows [regex 101](https://regex101.com).

`stdin:4: [F401] 'datetime' imported but unused` will not match our regex, I don't think we don't expect to get `[]` around the error code.

I also run the same version: `3.4.1 (mccabe: 0.6.1, pycodestyle: 2.3.1, pyflakes: 1.6.0) CPython 3.6.3 on Darwin`, but my output looks like `stdin:391:80: E501 line too long (85 > 79 characters)`.

**Comment by FichteFoll** [comment]
```
~ ж flake8 --version
3.5.0 (flake8-docstrings: 1.1.0, pydocstyle: 2.1.1, mccabe: 0.6.1, pycodestyle: 2.3.1, pyflakes: 1.6.0) CPython 3.6.4 on Linux

~/.config/sublime-text-3/Packages/SublimeLinter ∃ flake8 . --max-line-length=100
./lint/style.py:47:101: E501 line too long (103 > 100 characters)
./lint/linter.py:15:101: E501 line too long (117 > 100 characters)
./lint/linter.py:566:101: E501 line too long (114 > 100 characters)
./lint/linter.py:1255:101: E501 line too long (110 > 100 characters)
./lint/linter.py:1332:101: E501 line too long (104 > 100 characters)
./lint/base_linter/python_linter.py:318:101: E501 line too long (107 > 100 characters)
```

Something about your flake8 output is very weird. I've never seen that before and I'd be very interested into where this is coming from. I would suggest running flake8 with `-v` manually, so `-vv` it is. As that is *very* verbose, please post the output somewhere external.

**Comment by kaste** [comment]
Please look up your config file for flake8. It does not use the standard format. Do you hand coded it, or is this pylint style?

**Comment by kaste** [comment]
The solution to this is anyway, that we must add the `--format default` to the `cmd` in the flake8 plugin. No?

**Comment by braver** [comment]
💯  Either that or a specific format.

**Comment by kaste** [comment]
Follow up https://github.com/SublimeLinter/SublimeLinter-flake8/issues/75
Follow up https://github.com/SublimeLinter/SublimeLinter/issues/834

**Comment by kaste** [comment]
So the fix is https://github.com/SublimeLinter/SublimeLinter-flake8/pull/76 @ anyone How can a user like @whw test this?

**Comment by braver** [comment]
> How can a user like @whw test this?

remove flake8 via package control, and run this in Packages: `git clone https://github.com/SublimeLinter/SublimeLinter-flake8.git --branch kaste-patch-1`

**Comment by whw** [comment]
Yup, that works

**Comment by kaste** [comment]
I'll get the 💐 , yeah

**Comment by kaste** [comment]
New release of the flake8 available.

**Comment by whw** [comment]
Thanks @kaste @braver !
