### ISSUE TITLE
Trigger lints based on `buffer_id` not `view_id`

### ISSUE THREAD

**Issue by kaste** [SublimeLinter/SublimeLinter#838]
Otherwise, we get multiple, concurrent lints per buffer if the user has multiple views into the same file. 

E.g. changing a setting, triggers a fresh lint per view

**Comment by pykong** [comment]
I do not get why the entire logic of SL got structured around views instead of buffers in the first place.
We should try to get rid of that relic entirely!

**Comment by FichteFoll** [comment]
It's a common misconception. Just like many assume there will always be exactly one selection. I actually have some notes for a "common misconceptions" post for my non-existant blog with stuff like this, similar to https://haasn.xyz/posts/2016-12-25-falsehoods-programmers-believe-about-[video-stuff].html.
