### ISSUE TITLE
Centralize message sanitation

### ISSUE THREAD

**Issue by pykong** [SublimeLinter/SublimeLinter#854]
We should call `.strip()` once on linter messages.
Currently, it seems that linter messages get sanitized in multiple places.
This is a minor redundancy that should be removed.

Also, currently `.rstrip()` is used. It makes sense to strip at both ends of the linter message.

**Comment by FichteFoll** [comment]
>`good first issue`

?

**Comment by pykong** [comment]
From SublimeLinter's issue page:
![image](https://user-images.githubusercontent.com/20211140/35189892-ccb891b6-fe54-11e7-9851-b23d7d256515.png)
