### ISSUE TITLE
SL-pylint doesn't work on unsaved buffers, throws errors

### ISSUE THREAD

**Issue by braver** [SublimeLinter/SublimeLinter#864]
```py
Traceback (most recent call last):
  File "/Users/koenlageveen/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/backend.py", line 158, in await_futures
    yield future.result()
  File "./python3.3/concurrent/futures/_base.py", line 394, in result
  File "./python3.3/concurrent/futures/_base.py", line 353, in __get_result
  File "./python3.3/concurrent/futures/thread.py", line 54, in run
  File "/Users/koenlageveen/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/backend.py", line 39, in <lambda>
    lambda: execute_lint_task(*task, hit_time=hit_time)
  File "/Users/koenlageveen/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/backend.py", line 52, in execute_lint_task
    errors = linter.lint(code, hit_time) or []
  File "/Users/koenlageveen/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/linter.py", line 922, in lint
    output = self.run(cmd, code)
  File "/Users/koenlageveen/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/linter.py", line 1282, in run
    return self.tmpfile(cmd, code)
  File "/Users/koenlageveen/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/linter.py", line 1352, in tmpfile
    cwd=cwd)
  File "/Users/koenlageveen/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/util.py", line 415, in tmpfile
    os.remove(path)
FileNotFoundError: [Errno 2] No such file or directory: '/var/folders/cp/659wm5bs1pl2kpz8j9jvckrw0000gn/T/SublimeLinter3-koenlageveen/linter.py'
```

The temp dir exists, but the tempfile doesn't and hence cannot be removed. I only get this with SublimeLinter-pylint, and always as soon as I edit a file (linters running in "background").

**Comment by braver** [comment]
@kaste some questions here based on an earlier comment of yours. It seems that `util.tmpfile` doesn't expect to have to deal with more that one linter at a time, resulting in this case in a situation where multiple linters try to remove the tmpfile. In my case, flake8 is ready before pylint, causing tmpfile to be removed before pylint gets a chance to run on it.

I don't think we regressed here, but improved asynchronicity and performance may have surfaced it. However, I really want to solve this before pushing out another beta release because [let nobody see your bugs](http://blog.felipe.rs/2017/02/25/id-software-programming-principles/). I see two possible paths:

1. Be more lazy about removing tmpfiles. The tempdir is already removed each time SL is loaded (ie. on startup), that may just be enough already in this age of large SSD disks. Perhaps cleanup up `on_finished_linting` is another solution.
2. Each linter gets his own temp dir to work in. 

To me 2 seems like the cleanest way of doing things. Being the total rooky that I am, 1 seems easy, perhaps just something like this:

```diff
@ util.py line 413
-    finally:
-        os.remove(path)
+    except Exception as err:
+        printf('Error writing to tmpfile:', str(path))
+        printf('reason:', str(err))
```

**Comment by kaste** [comment]
I would go with 

``` diff
diff --git a/lint/util.py b/lint/util.py
index 74f2a95..1d3b9d5 100644
--- a/lint/util.py
+++ b/lint/util.py
@@ -402,7 +402,10 @@ def tmpfile(cmd, code, filename, suffix='', output_stream=STREAM_STDOUT, env=Non

         return communicate(cmd, output_stream=output_stream, env=env, cwd=cwd)
     finally:
-        os.remove(path)
+        try:
+            os.remove(path)
+        except FileNotFoundErrorX?ExactName:
+            pass

```

**Comment by kaste** [comment]
Better play with `tempfile.NamedTemporaryFile` of course. Is the name here important? Otherwise we can just use a random name.

**Comment by braver** [comment]
Well, that would still result in one linter removing the tmp file before another linter has the chance to run on it, solving nothing but changing the outcome: pylint won't break but report  
`1:0:F0001: No module named <snip>/util.py (fatal)`).

**Comment by kaste** [comment]
Okay, actually just use our own tmpdir.

**Comment by braver** [comment]
> Is the name here important

I'm not sure. Does it create a single temp file or does it try to copy an entire environment for relative imports? If it's just the single file a random name may be better. The core problem remains that multiple linters try to run on the same temp file and nobody owns it. 

> Okay, actually just use our own tmpdir.

I'm not sure I follow you here?

**Comment by kaste** [comment]
Maybe?
``` diff
diff --git a/lint/util.py b/lint/util.py
index 74f2a95..d23a320 100644
--- a/lint/util.py
+++ b/lint/util.py
@@ -383,16 +383,12 @@ def tmpfile(cmd, code, filename, suffix='', output_stream=STREAM_STDOUT, env=Non
     if suffix:
         filename = os.path.splitext(filename)[0] + suffix

-    path = os.path.join(tempdir, filename)
-
     try:
-        with open(path, mode='wb') as f:
-            if isinstance(code, str):
-                code = code.encode('utf-8')
-
-            f.write(code)
-            f.flush()
+        f = tempfile.NamedTemporaryFile(delete=False)
+        f.write(code)
+        f.close()

+        path = f.name
         cmd = list(cmd)
```

**Comment by braver** [comment]
`f.write(bytes(code, 'UTF-8'))` actually, but yeah, that seems to work. Thanks.
