### ISSUE TITLE
Global Settings page's "Edit on GitHub" link is broken

### ISSUE THREAD

**Issue by ExplodingCabbage** [SublimeLinter/SublimeLinter#873]
If I click "Edit on GitHub" at http://www.sublimelinter.com/en/latest/global_settings.html I get sent to this 404 page: https://github.com/SublimeLinter/SublimeLinter/blob/master/docs/global_settings.rst

Probably not the only affected page - just the first I found.

**Comment by braver** [comment]
Yeah, the published docs are way behind master, it doesn’t update on prereleases I think. Nothing I can do about that. If you want to contribute to the docs, they’re moving really fast right now so perhaps just open an issue about what’s wrong.
