### ISSUE TITLE
Add note to global settings page that they can only be changed from user settings

### ISSUE THREAD

**Issue by ExplodingCabbage** [SublimeLinter/SublimeLinter#874]
This confused me (and wasted hours of my time) years back, and judging by the :+1:s on https://github.com/SublimeLinter/SublimeLinter/issues/32#issuecomment-239475867 I'm not the only one.

I suggest modifying the first paragraph at http://www.sublimelinter.com/en/latest/global_settings.html, which currently reads

> SublimeLinter supports the following global settings:

to instead read

> SublimeLinter supports the global settings listed below. Note that global settings can only be modified by [user settings](http://www.sublimelinter.com/en/latest/settings.html#user-settings), *not* by [project settings](http://www.sublimelinter.com/en/latest/settings.html#project-settings), [.sublimelinterrc](http://www.sublimelinter.com/en/latest/settings.html#sublimelinterrc-settings), or [inline settings](http://www.sublimelinter.com/en/latest/settings.html#inline-settings).

I'd make the change myself but I'm [not sure where to do so](https://github.com/SublimeLinter/SublimeLinter/issues/873).

**Comment by braver** [comment]
Thanks, that *is* somewhat unclear. I've made some changes to the current documentation.
