### ISSUE TITLE
"Show All Errors" in output panel at bottom instead of quick panel

### ISSUE THREAD

**Issue by RwwL** [SublimeLinter/SublimeLinter#888]
Sorry to use the issues room to ask about this, but I'm wondering if the "Show All Errors" option is likely to ever be configurable to render in an output panel at the bottom of the window instead of the current quick panel.... just a personal preference based on years of use with other code-checking plugins.

**Comment by braver** [comment]
Yes, SublimeLinter 4 (you can try it [right now](https://github.com/SublimeLinter/SublimeLinter#sublimelinter-4-beta)) does exactly this. The quick panel will no longer be (ab-)used for this.
