### ISSUE TITLE
Remove `config_file` setting

### ISSUE THREAD

**Issue by kaste** [SublimeLinter/SublimeLinter#891]
We have special handling for *config files*. Like `config_file = ('--config', '.jshintrc')`. These are set on `cls` so basically configurable for plugin authors. 

Now, the 90% case is probably these days that linters find their configuration automatically, esp. if you start with a good working_dir, which we probably do, right now. 

If that's not the case, a *user* setting is probably way better and more useful. WDYT?

(Note: The last remaining lrucached function in util.py would go away with that. 😄)

**Comment by braver** [comment]
> If that's not the case, a user setting is probably way better and more useful. WDYT?

Well yes. Although a linter could set the canonical default. 

Lot's of plugins set this value, probably for various reasons. I really don't like the idea of having to go through all of them to figure out what's what and if it's still needed. But I agree with the general idea that you shouldn't have to have this set.

**Comment by kaste** [comment]
But what's the difference, if the plugin author sets this to:

```
defaults = {
	'--config': '${folder}/.jshintrc'
}
```

**Comment by braver** [comment]
No difference, but someone has to go out and change all the plugins.

**Comment by kaste** [comment]
Okay, can we get back to normal development mode here? Usually I ask you and @FichteFoll to do a quick grep, so we can see what impact such a change would have. And then we decide. I think we did a lot of effort in this section, and maybe can deprecate it. (But I also committed https://github.com/SublimeLinter/SublimeLinter-jshint/commit/fe67fce54b5889e4a798eacc8c983d294bb4a9cb bc our implementation actually bugs the *correct* behavior of jshint https://github.com/SublimeLinter/SublimeLinter-jshint/issues/104)

**Comment by braver** [comment]
There’s a [script](https://github.com/SublimeLinter/package_control_channel/blob/master/fetch_all_repos.py) you can run and then just search through everything using ST. You don’t need me for that.

In this particular case, about 33 linters set the `config_file`. The big ones like stylelint and tslint I trust to work without it, but there are plenty in there I know nothing about.

In most cases I would say that this should only be required in specific situations and we have an `args` option for that. However, if I understand the comments around this in our code, some linters need this when reading from `stdin`. I don't know which of those 33 linters are "some linters".

In some previous cases there were only a few affected linters and we could figure out how to move them forwards. Here though, I don't know what "SublimeLinter-contrib-tailor" or "SublimeLinter-slim-lint" does or how to check if they still work.

**Comment by kaste** [comment]
Both SublimeLinter-contrib-tailor and SublimeLinter-slim-lint have a default behavior which is good enough after our recent changes. They look in the working dir, which we now set correctly.

**Comment by braver** [comment]
Ok, that's fast. How's this (repo names, not linter names):

- [ ] SublimeLinter-contrib-bemlint
- [ ] SublimeLinter-contrib-CFLint
- [ ] SublimeLinter-contrib-clang-tidy
- [ ] SublimeLinter-contrib-dockerfilelint
- [ ] SublimeLinter-contrib-eslint_d
- [ ] SublimeLinter-contrib-glualint
- [ ] SublimeLinter-contrib-haml-lint
- [ ] SublimeLinter-contrib-htmlhint
- [ ] SublimeLinter-contrib-htmllint
- [ ] SublimeLinter-contrib-markdownlint
- [ ] SublimeLinter-contrib-mdl
- [ ] SublimeLinter-contrib-mypy (probably ok)
- [ ] SublimeLinter-contrib-php-cs-fixer
- [ ] SublimeLinter-contrib-pug-lint
- [ ] SublimeLinter-contrib-reek
- [ ] SublimeLinter-contrib-ruby-lint
- [ ] SublimeLinter-contrib-sass-lint
- [ ] SublimeLinter-contrib-scalastyle
- [x] SublimeLinter-contrib-stylint
- [ ] SublimeLinter-contrib-swiftlint
- [x] SublimeLinter-contrib-tailor
- [x] SublimeLinter-contrib-tslint
- [ ] SublimeLinter-jslint
- [ ] SublimeLinter-scss-lint
- [x] SublimeLinter-slim-lint
- [ ] SublimeLinter-bandit
- [ ] SublimeLinter-chktex
- [ ] SublimeLinter-coffeelint
- [ ] SublimeLinter-gjslint
- [ ] SublimeLinter-jscs
- [x] SublimeLinter-jshint
- [ ] SublimeLinter-jsl
- [ ] SublimeLinter-jsxhint

**Comment by kaste** [comment]
Note. Stopped at SublimeLinter-contrib-htmlhint

**Comment by braver** [comment]
Well probably it’s ok for most and otherwise we’ll find out and it’s an easy enough fix. Let’s do this.
