### ISSUE TITLE
Apply syntax attribute from a setting

### ISSUE THREAD

**Issue by mighty-pirate** [SublimeLinter/SublimeLinter#896]
Is it possible to apply the syntax attribute from a linter specific setting, making the attribute setting dynamic. I can only find inline and override settings, are there any other setting types for linters? I couldn't find anything in the docs, although I may not have read them thoroughly enough.

**Comment by braver** [comment]
If a linter’s attribute reports it can lint `<syntax>`, users can map any given syntax to `<syntax>`. The syntax attribute shouldn’t, and shouldn’t have to be, dynamic.

Or do you have a use case in mind where this doesn’t work?

**Comment by braver** [comment]
Yes, if you map ‘c++’ to ‘c’ you’re saying “c++ is actually just c by another name”, which tells all “c” linters they can also lint it. 

The basic premise here is that we’ll run all linters that are capable of linting a given syntax. You can disable linters using [sublime-project](https://github.com/SublimeLinter/SublimeLinter/blob/master/docs/settings.rst#project-settings) settings, to tune this behavior from project to project.

The syntax attribute does seem a bit limiting for your examples, but do you run into them in practice?

**Comment by mighty-pirate** [comment]
For the first example, this does happen in practice. I use SublimeLinter-contrib-clang and SublimeLinter-cpplint (modified to add C to the syntax attribute) but there are cases where I don't want to use cpplint. 

The second example hasn't happened to me yet.

I think the way for me to go is to disable linters in certain projects using the `@disable` meta setting in a sublimelinterrc file. 

Thanks a lot

**Comment by braver** [comment]
That's one way to do it. However, the upcoming SublimeLinter version 4 will drop support for .sublimelinterrc files. Usually it's best to use the linter's native configuration options. 
Additionally, you can use Sublime Text's [project configuration](https://www.sublimetext.com/docs/3/projects.html) to disable linters in specific contexts, or pass them different arguments.

**Comment by FichteFoll** [comment]
I intend to make this configurable for https://github.com/SublimeLinter/SublimeLinter/issues/691, but no promises.
