### ISSUE TITLE
Provide API major version for plugins

### ISSUE THREAD

**Issue by braver** [SublimeLinter/SublimeLinter#897]
SL3 has no means to report its version.

SL4 has util.get_sl_version, which reports a semver version string when installed through package control and “unknown” otherwise.

Currently the version is set manually when creating a release. I don’t like hardcoding a version number and trying to keep it in sync with the version in PC. Manually managing a semver versioning scheme is already broken enough if you do it in one place. 
However, we could have a different version number internally for the api to plugins. I propose exposing an integer via sublimelinter.version, hardcoded as a constant, and we should remember to bump it when we hit the api. It would by nature be None on SL3 or manual installs of old versions, which plugins need to guard for anyway.

**Comment by braver** [comment]
cc @kaste

**Comment by FichteFoll** [comment]
Hardcoding a semi-constant value such as `(major, minor)` sounds like a good compromise here, imho. Minor releases aren't as frequent but could still be useful for plugins in case a new feature was introduced.
That will also work for `master` checkouts.

A CI test for tag branches could be added to ensure that the hardcoded version tuple doesn't go out of sync.

**Comment by braver** [comment]
fixed in e19efc326f8d29c0c7d4ebedd27a2fef667d27e1 and 72e66ebe97fa47f7bc2aad3367808a0113776a65
