### ISSUE TITLE
Factor out "clear methods" in linter

### ISSUE THREAD

**Issue by pykong** [SublimeLinter/SublimeLinter#899]
We need to check whether the following methods:
- `clear_view`
- `clear_all` 
- `clear`
 which can be found in `sublime_linter` and `linter`, are still being used.
Both internally and by plugins.

A removal or refactoring may follow.

**Comment by braver** [comment]
I think they’re all still used, but they’re also a bit tangled up.

**Comment by kaste** [comment]
Tag as 'bug' bc it is *forbidden* to import 'views' (any top level module actually) from below. (So to be clear, this is not a design choice, but the inner workings of SublimeText forbid that.)
