### ISSUE TITLE
'Available variables' debug print is noisy

### ISSUE THREAD

**Issue by FichteFoll** [SublimeLinter/SublimeLinter#907]
It can be useful at times, but since the print includes all my environment variables, which count 36 in total right now, each printed on a new line and not ever changing, I don't thing this is useful. We could print the environment variables once on startup and `window.extract_variables` on each lint, as that seems useful for context on the file to be linted, but is also excessive since most of the values are deterministic aside from `file`, `folder` and `project` (and `packages` potentially).

PS: Since `window.extract_variables` only accounts for the window's active view, is linting only ever run for the active view? It does seem like it, though.

**Comment by FichteFoll** [comment]
I just noticed that the *entire* console is filled with debug prints for this when I save a linter plugin (which probably causes a reload of SL). Yes, everything from the top to the bottom. I didn't even know there was a limit for this.

This definitely needs to be optimized. I have 44 views open currently.
```py
>>> sum(len(list(w.views())) for w in sublime.windows())
44
```

**Comment by FichteFoll** [comment]
Looking into this, the entire debug print of the variables to substitute is kind of questionable since linters are run asynchronously. You have no way to associate which prints are coming from which lint task and which linter is being run on which view since they all come in at random.

We're either looking at a logger abstraction to have logging/debug events attributed to certain linters/tasks by their associated logger instance attribute, or removing this basically useless debug statement.

**Comment by kaste** [comment]
> PS: Since window.extract_variables only accounts for the window's active view, is linting only ever run for the active view? It does seem like it, though.

No that's a real bug. I never came to file this.

Otherwise, printing env variables is not only noisy as hell, but often this data contains stuff you shouldn't post here in issues. 

I wanted to change that so we only log changed settings. E.g. Changed 'executable' from '..' to '..'. Or: executable now is '...'
