### ISSUE TITLE
Problem with get_syntax

### ISSUE THREAD

**Issue by schreda** [SublimeLinter/SublimeLinter#914]
I am getting following error with sublimelinter4

.config/sublime-text-3/Packages/SublimeLinter-contrib-clang/linter.py", line 78, in cmd
    if persist.get_syntax(self.view) in ['c', 'c improved']:
AttributeError: 'module' object has no attribute 'get_syntax'

**Comment by braver** [comment]
@kaste 4 linters will have this problem. I created a proposal reference PR at https://github.com/SublimeLinter/SublimeLinter-coffeelint/pull/28.

- [ ] SublimeLinter-clang
- [ ] SublimeLinter-contrib-avr-gcc
- [ ] SublimeLinter-contrib-gcc
- [ ] SublimeLinter-coffeelint
