### ISSUE TITLE
cwd wrong directory

### ISSUE THREAD

**Issue by schreda** [SublimeLinter/SublimeLinter#918]
For my project setup the linted source file is in another folder then the project folder. Now the linter can't find the include files, that are in the same folder as the source file. cwd should change the directory where the source file is located and not into the project dir, like this:

os.path.dirname(os.path.realpath(sublime.active_window().active_view().file_name()))

**Comment by FichteFoll** [comment]
Ideally it should already do that, but I can't check why it's not right now. This seems like a bug or regression though.

**Comment by schreda** [comment]
I think the problem is in _guess_project_path()
My project setup is a bit special. The folders are symlinked to the original ones, so taking the folders from the project setup maybe lead to the wrong location. Taking the folder from the file location would be better here

**Comment by FichteFoll** [comment]
In any case, you can override the behavior in your project file by specifying the `working_dir` setting per linter. Assuming you are using the SL4 beta.

**Comment by schreda** [comment]
The directory differs from source to souce, this wouldn't work in my case..

**Comment by kaste** [comment]
`working_dir` can be dynamic as well. E.g. set it to `${file_path}`

**Comment by schreda** [comment]
Thanks! This solved the problem
