### ISSUE TITLE
SublimeLinter commands list, toggle, disable not in Palette

### ISSUE THREAD

**Issue by GregMacdonald** [SublimeLinter/SublimeLinter#919]
The commands to toggle individual linters or see a list of installed linters have disappeared. There used to be a SublimeLinter section under the Tools menu which is now gone, and your doc says I should now find them in Package Control, but they aren't there either.  Uninstalled all linters and SublimeLinter and reinstalled and still they are missing.

![image](https://user-images.githubusercontent.com/4240293/35668638-195703a0-06e7-11e8-9008-59f9260f4707.png)

**Comment by braver** [comment]
Ah, you’re using the SL4 beta? 

- To list all linters use Package Control to list all packages and then filter on SublimeLinter.
<img width="477" alt="screen shot 2018-02-01 at 09 44 24" src="https://user-images.githubusercontent.com/2543659/35669168-82afd640-0734-11e8-8dea-06eaea785e8d.png">


- All commands to change settings have been removed. They didn’t always work reliably and not all of them were useful, especially not in new versions of Sublime Text. To toggle a linter you now open your SL settings, add your linter to "Iinters" and set "disable" to true for it. Not that you can comment out parts of a settings file, so you can more easily toggle that linter.

**Comment by FichteFoll** [comment]
The commenting part is really significant  here since the automatic modifications of the previous commands caused them to be discarded.

**Comment by kaste** [comment]
I would like to see a plugin for that. Maybe even do it myself.

**Comment by braver** [comment]
I hate packages that write to my settings and make me lose my comments. Someone should make a json parser that handles comments. Just disabling a linter temporarily for a given view, e.g. like how wrapping can be toggled, that would be handy though.

**Comment by GregMacdonald** [comment]
Thanks all for the info.

Regarding comments, ST uses a pattern where there is a default settings file and a separate user's setting file that gets written.  I think the default settings file is never automatically written, so any doc or comments there should be preserved, yes?

**Comment by braver** [comment]
Most packages will work that way. The default settings are never changed, cannot be changed if the package was installed via package control, and are not written to. The user settings can be changed, and comments there are allowed (ST has a custom json parser that accepts comments), so you can disable customizations temporarily without losing them.

**Comment by humatic** [comment]
Perhaps I'm a rare use case, but I quite regularly used the enable/ disable toggle via the command palette. Why? I rely on the linter quite regularly, but I don't want want to see the results all the time while I'm in the middle of developing. Perfect code styling isn't where my head is at while writing and seeing all of that highlighting pop in and out of existence is super distracting. But then when I'm ready to commit the code, I like to run the linter real quick.

Is there a recommended method for turning the highlighting on/ off with a keyboard shortcut or something similar? Opening up settings to comment out a line of configuration is a non-starter for me.

**Comment by braver** [comment]
See #1149 we’re working on bringing that feature back, doing it right this time.
