### ISSUE TITLE
Default working_dir should be equivalent to `${folder:$file_path}`

### ISSUE THREAD

**Issue by FichteFoll** [SublimeLinter/SublimeLinter#927]
We previously talked about how the default for `working_dir` should be `${folder:$file_path}`, but in #918 I was made aware that the actual default is just `${folder}` (compare `Linter.get_working_dir`).

https://github.com/SublimeLinter/SublimeLinter/blob/329b5d78ca6d6146cd475a7ead307a265d861481/lint/linter.py#L885-L899

To add this, we either have the option to have settings expansion do the work for us, which would be easy on the surface but require a way to specify a setting default *before* expansion, which currently does not exist, or just enhance `get_working_dir` to check for `self.view.file_name()` and return its dirname if `self._guess_project_path` returned `None`.

**Comment by kaste** [comment]
But this was not the issue in #918.  The thing here is that `guess_project_path` almost never returns `None` at the moment. We need real user feedback here.

**Comment by FichteFoll** [comment]
Well, it returns none for files that aren't contained in any project folder, and I thought that's expected.

**Comment by kaste** [comment]
Ok, I see now, LOL. 

But you were my reviewer here. 😸

**Comment by FichteFoll** [comment]
Yeah I think I was being lazy there. I do remember noticing the lack of the file_path fallback though.
