### ISSUE TITLE
Errors in current view showing errors from another file

### ISSUE THREAD

**Issue by gerardroche** [SublimeLinter/SublimeLinter#928]
When a linter outputs results for multiple files SL shows all the errors regardless of file. 

For example when `mypy` output is:

```
SublimeLinter: mypy output:
    /home/code/.local/lib/mypy/typeshed/stdlib/2and3/logging/handlers.pyi:86:4: error: Return type becomes "Any" due to an unfollowed import
    /home/code/project/name/module.py:24:4: error: Need type annotation for variable
    /home/code/project/name/module.py:52:4: error: Decorated property not supported
    /home/code/project/name/module.py:122: error: Missing return statement 
```

## Actual

`module.py` highlights an error at `86:4`.

There's also an exception when the current view doesn't have lines > than the line number (in this example 86):

```
Traceback (most recent call last):
  File "/home/code/.config/sublime-text-3/Packages/SublimeLinter/lint/backend.py", line 154, in await_futures
    yield future.result()
  File "./python3.3/concurrent/futures/_base.py", line 394, in result
  File "./python3.3/concurrent/futures/_base.py", line 353, in __get_result
  File "./python3.3/concurrent/futures/thread.py", line 54, in run
  File "/home/code/.config/sublime-text-3/Packages/SublimeLinter/lint/backend.py", line 51, in execute_lint_task
    errors = linter.lint(code, hit_time) or []
  File "/home/code/.config/sublime-text-3/Packages/SublimeLinter/lint/linter.py", line 950, in lint
    error = self.process_match(m, vv)
  File "/home/code/.config/sublime-text-3/Packages/SublimeLinter/lint/linter.py", line 1023, in process_match
    start, end = vv.full_line(m.line)
  File "/home/code/.config/sublime-text-3/Packages/SublimeLinter/lint/linter.py", line 69, in full_line
    start = self._newlines[line]
IndexError: list index out of range
```

## Expected

The error in `/home/code/.local/lib/mypy/typeshed/stdlib/2and3/logging/handlers.pyi:86:4` should be ignored.

Technically this is a bug in typeshed, but ideally SL could filter these errors out. 

## Steps to reproduce 

You can use the following `mypy.ini` configuration which should produce the logging file error above:

```
[mypy]

check_untyped_defs = True
follow_imports = silent
ignore_missing_imports = False

incremental = True
show_column_numbers = True
strict_optional = True
quick_and_dirty = True
verbosity = 0

warn_no_return = True
warn_redundant_casts = True
#warn_return_any = True
warn_unused_configs = True
warn_unused_ignores = True

#disallow_any_decorated = True
disallow_any_unimported = True
#disallow_incomplete_defs = True

#disallow_any_explicit = True
#disallow_any_expr = True
disallow_any_generics = True
disallow_subclassing_any = True
#disallow_untyped_calls = True
#disallow_untyped_decorators = True
#disallow_untyped_defs = True
```

**Comment by braver** [comment]
SublimeLinter expects to be able to run the results through a regex to find the errors pertaining to a file. In no way does it support parsing project-level results, or results for anything other that the input file. If `mypy` can't be instructed to give only results on the input file, the linter plugin needs to tweak the results. In this case it seems like the regex should be able to exclude the file ending with `.pyi`. I think you should raise this issue in the mypy plugin repo.

**Comment by FichteFoll** [comment]
I fixed this in mypy through specifying `--follow-imports=silent` again (which I removed prior but then quickly remembered why it was needed in the first place), but it appears you are setting that in your ini as well.

I don't think linters should be showing stuff for files that are "not the requested one" since linter plugins usually supply the pile path to be linted, they actual linters should also only output stuff for that file and pretty much all do. Mypy doesn't by default, but you can easily make it behave. If a linter does not support direct file lints, some special attention is needed anyway, in which case you might as well filter out the lines that don't affect the requested file within the plugin itself.

**Comment by braver** [comment]
💯

**Comment by gerardroche** [comment]
I don't know how to filter by active file. Using the regex to filter pyi has the unwanted side effect of not linting pyi files haha.

**Comment by kaste** [comment]
`linter.find_errors(self, output)` is probably your friend here. It can do prefiltering on the output and returns regex matches.
