### ISSUE TITLE
Status bar busy indicator stops on first response from backend

### ISSUE THREAD

**Issue by kaste** [SublimeLinter/SublimeLinter#935]
We only fire 'BEGIN_LINTING' and 'FINISHED_LINTING'. But since #887 the responses fly in as soon as possible. Currently all responses fire 'FINISHED_LINTING'. 

We need three events here

'START_LINTING(bid)' -> 'LINT_RESULT(bid, linter, errors)' -> 'STOP_LINTING(bid [,errors])'

Feel free to bike-shed the naming here.

**Comment by braver** [comment]
linting-start, lint-result, linting-end? 🤷🏼‍♂️
