### ISSUE TITLE
Implement workaround for whitespace 'underline' highlights

### ISSUE THREAD

**Issue by kaste** [SublimeLinter/SublimeLinter#940]
Proposal:

If the user chooses one of the underline highlights (which I personally would like to do), we check if the actual text the error is about *only* contains white-space. In such a case, due to a bug in Sublime, the highights would not show up at all. So we switch to 'outline'/'fill' style for these regions.

**Comment by braver** [comment]
I tend to use the squiggly underlines, but getting an outline on regions that contain only whitespace (e.g. trailing whitespace) would be really handy. 👍🏻
