### ISSUE TITLE
De-highlight (invalidate) error as soon as your editing on it

### ISSUE THREAD

**Issue by kaste** [SublimeLinter/SublimeLinter#941]
Take a normal spell checker. It squiggles unknown or wrong words. But as soon as you *edit* (**not** *move* the cursor into) such a word, the squiggles disappear (and then maybe reappear of course, if you're still incorrect).

**Comment by braver** [comment]
I would totally love this 👍🏻👍🏻

**Comment by FichteFoll** [comment]
Just to be clear, this is only about the word that was changed and not all markers, right?

**Comment by braver** [comment]
That’s my reading of it too, just the region(s) at the cursor(s) that is(are) being changed.
