### ISSUE TITLE
How do I get flake8 to work with different versions of Python?

### ISSUE THREAD

**Issue by deanishe** [SublimeLinter/SublimeLinter#945]
I've tried setting `@python` to "/usr/bin/python" and "2.7", but it just uses `/usr/local/bin/flake8`, which is linked with Python 3, instead.

Is there a way to tell SublimeLinter to run `/path/to/python -m flake8` instead of looking for a `flake8` command?

**Comment by kaste** [comment]
This only works with SL4 which is beta right now. 

With SL4 you can set `exectuable: '...'` in your global or project settings. You can also prepare the execution environment using `env: {...}`

**Comment by deanishe** [comment]
Thanks for the reply. 

How exactly do I do that? Can I set `executable` to `.../python -m flake8` or does it need to be the path of an executable?

**Comment by kaste** [comment]
executable should usually point to the linter binary. However, you can set executable to a list of strings [python, m, flake8].

**Comment by deanishe** [comment]
Thanks.

> executable should usually point to the linter binary

Why is that? I mean, it's not exactly straightforward to install two copies of `flake8` (2.7 and 3.x), whereas adding `-m flake8` to the specified Python should "just work" if `flake8` is installed in it, executable or not.

Does `python -m xyz` not work on Windows?

**Comment by kaste** [comment]
Hm, I don't think I understand your last comment. You can also set python (in SL4 without the @) and point to a python environment. 

But this will also look for a bin/flake8 executable in the end. What's the difference between specifying Foo/bar/python -m flake8 or Foo/bar/python/bin/flake8?

**Comment by deanishe** [comment]
Perhaps I've misunderstood what `@python` is supposed to be. Is it not a version number or the path to a `python` executable?

**Comment by kaste** [comment]
python can set to a version number. Then we search your PATH to find a python environment matching that version.

Otherwise, it points to the root path of a python environment.

We actually don't get much feedback in this area. The only thing clear here is that it was completely broken aka unpredictable in SL3.

We could treat a python setting differently. Like searching for a python bin instead, and then do python -m flake8. But honestly, an installed script or program e.g. bin/flake8 should already be bound to its python environment.

**Comment by deanishe** [comment]
> Otherwise, it points to the root path of a python environment.

What does that mean? A virtual environment?

> an installed script or program e.g. bin/flake8 should already be bound to its python environment.

They are. The problem is, I'd like to be able to use `flake8` with both the system Python 2.7 (`/usr/bin/python`) and Python 3 installed at `/usr/local/bin/python3`, both of which install `flake8` to `/usr/local/bin/flake8`.

If SL used `python -m flake8`, I could install one or both with `pip --user` so they don't conflict.

As best as I can tell, currently only one of `@python: 2` or `@python: 3` can work.

If `@python` has to point to a Python environment, not a Python executable, then presumably that won't work with multiple system-wide installations, either, as they all put their executables in the same directory (`/usr/local/bin`).

**Comment by kaste** [comment]
> That means a virtual environment, right?

A *real* or a *virtual* environment. 

You cannot have two flake8 at the same /usr/local/bin/flake8.  If you have multiple programs with the same name on PATH, the first one wins. If you literally do python -m flake8 it will invoke the python on your PATH. But maybe you want to take a python that is actually *not* on your PATH.

**Comment by kaste** [comment]
Now we could add a `os.path.realpath` expansion somewhere here.

https://github.com/SublimeLinter/SublimeLinter/blob/17dd328870e12402e21fc812cc780eda8f6c15ee/lint/base_linter/python_linter.py#L141-L163

Best candidate maybe on L158

**Comment by deanishe** [comment]
> A real or a virtual environment.

What constitutes a "real" environment? From my usage, it seems SL looks for `flake8` in a `bin` subdirectory. This is the issue I'm having, as in those terms `/usr/local` would be the environment for all of `/usr/bin/python2.7`, `/usr/bin/python2.6` and `/usr/local/bin/python3`.

> You cannot have two flake8 at the same /usr/local/bin/flake8 …

I'm not an idiot. I'd appreciate your not talking to me as if I were.

> But maybe you want to take a python that is actually not on your PATH

Could you explain how pointing `@python` to a Python environment achieves this, but the path to a `python` executable wouldn't?

Here's how I had expected and hoped `@python` would work:

I don't set `@python`, SL searches `PATH` for a `flake8` executable.

I set `@python: 2`, SL searches `PATH` for `python2`, then calls `/path/it/found/python2 -m flake8`.

I set `@python: 2.7`, SL searches `PATH` for `python2.6`, then calls `/path/it/found/python2.7 -m flake8`.

I set `@python: 3`, SL searches `PATH` for `python3`, then calls `/path/it/found/python3 -m flake8`.

I set `@python: /usr/bin/python`, SL calls `/usr/bin/python -m flake8`.

That works with `PATH`. It's compatible with system-wide Pythons that aren't in an "environment". It's compatible with multiple system-wide Pythons that would both install the `flake8` executable at `/usr/local/bin/flake8`.

I'm having trouble getting my head around the way SL *actually* works, as it clearly doesn't work the obvious (to me) way described above.

> We try to find a python with its complete environment, not just a symbolic link or so. 

In particular, I don't understand exactly what exactly this "environment" is, or why it's used. As far as the above code goes, it looks like it'll return `/usr/bin` for `/usr/bin/python` and `/usr/local/bin` for both `/usr/local/bin/python2` *and* `/usr/local/bin/python3`.

Is that correct?

**Comment by kaste** [comment]
Now, we're talking. What you explain how the `python` setting *should* work is actually something I can totally relate with. It's just (I wrote a lot of questions and comments) never got enough feedback from the users here. Now, the current `python` setting works as the old one in SL3, just without bugs. 

I borrow the 'environment' notion from the virtual environment definition. (When there is a virtual environment, let's call the other ones the real environments.) And it's literally just a folder with special subfolders in it, namely `bin` vs `Scripts`.

Now, I pointed you already to a bug or underdeveloped line. We just take `os.dirname`, but we should probably call `realpath` before.

However, the problem with `python -m flake8` generally is: we cannot say if this invocation will succeed. E.g. we can not check `os.path.exists` or something similar. So at this point in the code of SL, we would have to assume, okay this call will succeed, and we had no chance to disable a linter automatically bc its requirements aren't fulfilled. That's the con aspect. So, you cannot just do the pro side without thinking about this con aspect.

**Comment by kaste** [comment]
ADD: I said you could try `executable`as well, `executable` is setting for all linters, so it does not borrow any python semantics. Did you actually try `['/foo/bar/python', '-m', 'flake8']`?

**Comment by deanishe** [comment]
> how the python setting *should* work

"Should" is too strong. That's just the "obvious" way to do it to me, as a person who hasn't actually tried to implement it yet…

> However, the problem with python -m flake8 generally is: we cannot say if this invocation will succeed. E.g. we can not check os.path.exists or something similar

I don't follow. Why can't you call `os.path.exists()` on the `python` executable,  and `/path/to/python -c 'import flake8'` to check if `flake8` is actually installed with that Python?

>  Did you actually try `['/foo/bar/python', '-m', 'flake8']`?

Not yet. I was hoping there's a simpler, more portable way.

My expectation was that setting `@python: 2` or `@python: 3` would work in a portable fashion, so I could share the `.sublime-project` files with other people who may be using a linter other than `flake8`.

For that reason, I'd hoped to be able to avoid specifying paths.

**Comment by kaste** [comment]
For that use case: I would recommend you use pipenv. Create a Pipfile, commit it. Let others install the virtual environment using pipenv. SL will (beta 🤞 ) ask pipenv for the flake8, and you eat a 🍰

**Comment by kaste** [comment]
Maybe we just take a step back. We have different definitions of 'portable', sharing an environment or project with other people, sharing a `.sublime-project`, it's *your* workflow, but others should follow it.

**Comment by deanishe** [comment]
My definition of "portable" is that I can specify a Python version, say `2.7` or `3.6`, in the `.sublime-project` file and it will "just work" for other SL users who have corresponding linters configured.

> it's your workflow, but others should follow it.

That hardly includes dictating which editor a collaborator should use, nor where they should create their virtual envs.

Indeed, the majority of my public projects are hard-coded to `/usr/bin/python` (a standard part of macOS) and vendor all dependencies, so that they "just work" for users without any messing around.

A virtual env is entirely inappropriate for those projects.

**Comment by FichteFoll** [comment]
`executable` does searching on `PATH`, right? So a working solution could be settings `executable` to `['python2', '-m', 'flake8']` for the Python 2 and `['python3.6', '-m', 'flake8']` for the 3.6 version. This would then choose whatever `python2` or `python3.6` on the system's PATH point to.

Setting a number for the `python` (`@python` is the old SL3 name) setting should indeed try to resolve to the corresponding version, however it can't just prepend `python<version> -m` to the command because a Python package could have different entry points for its PATH-accessible executable and for the module running version (`python -m`). Although I'm not sure if anyone actually does that. The idea would be to try and resolve a `python<version>` on PATH first, then use `realpath` on that to expand symlinks and then use the dirname of that as the environment's root folder. Then, it would look into `bin/` or `Scripts/` to look for an appropriate executable. Thoughts?

**Comment by deanishe** [comment]
> Then, it would look into bin/ or Scripts/ to look for an appropriate executable. Thoughts?

My general issue with this is that it assumes a virtual env-like layout.

That assumption falls apart with system-wide installs (i.e. in `/usr/bin` or `/usr/local/bin`) because they aren't laid out that way, and `pip` will install their executables in `/usr/local/bin`, not `/usr/bin/bin` or `/usr/local/bin/bin`, which is where SL apparently looks for them.

Using `realpath` wouldn't help here because a system-wide Python's `pip` installs executables in `/usr/local/bin`, not wherever the real `python` executable actually is.

Secondly, you can't install `flake8` for both (system-wide) Python 2 *and* Python 3 (which is what I'm trying to achieve and why I posted this issue) because the install path for both is `/usr/local/bin/flake8` so you only get to have one.

> So a working solution could be settings executable to `['python2', '-m', 'flake8']`

It looks like that's the only workable solution.

It's rather more complicated that simply setting `python: 2` (what with the necessary additional nested JSON objects), but not unworkable.

My main objection to that solution is that it's essentially a workaround for what seems to me to be questionable assumptions/excessive magic applied to the `python: XX` setting.

Genuinely, what is the upside to assuming `flake8` exists at `bin/flake8` or `./flake8` relative to for whatever `python:...` resolves to?

It makes it impossible to support both Py2 and Py3 at the same time without virtual envs.

Unless it causes Windows to upchuck (I have no idea how Python works on Windows), I really can't understand why SL doesn't call whichever Python it found with `-m flake8` instead of grubbing around for a nearby `flake8` executable. In the case of system-wide Pythons, it isn't going to be where SL is looking and/or it's not guaranteed to be the correct `flake8` for the specified version of Python.

It seems to me that the [behaviour I outlined above](https://github.com/SublimeLinter/SublimeLinter/issues/945#issuecomment-362903405) would avoid these issues.

But as noted above, I haven't actually tried to implement that, so I presume I've overlooked at least one issue.

**Comment by kaste** [comment]
> Using realpath wouldn't help here because a system-wide Python's pip installs executables in /usr/local/bin, not wherever the real python executable actually is.

Hm, shouldn't these be symlinks as well?

**Comment by FichteFoll** [comment]
I think it's more complicated than that. For Windows, things are actually very easy because the *global* environment is structured exactly the same as a virtual environment (with the folders and stuff).

On my Arch system however, things look like this:
```py
$ which flake8
/usr/bin/flake8


$ cat `which flake8`
#!/usr/bin/python
# EASY-INSTALL-ENTRY-SCRIPT: 'flake8==3.5.0','console_scripts','flake8'
__requires__ = 'flake8==3.5.0'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('flake8==3.5.0', 'console_scripts', 'flake8')()
    )
```

**Comment by deanishe** [comment]
> So on Mac these are the real things?

Wrapper scripts, like @FichteFoll's.

Here's how things look on my Mac:

`/usr/bin/python` is a real binary, not a symlink. `/usr/bin/python2.7` is a symlink into the Python Framework in `/System/Library/Frameworks`.

The Homebrew Pythons at `/usr/local/bin/python*` are symlinks, also into Framework builds.

Framework builds, which are kinda the standard way to build Python on Mac, look like this:
```
Headers
Python
Resources
bin
include
lib
```

However, the only programs in the `bin` directory are Python's own (`python`, `python-config`, `idle` etc.), and this whole tree is replaced on upgrading Python.

`pip install flake8` (with *any* Python) creates `/usr/local/bin/flake8` by default, and that is a wrapper script much like the one @FichteFoll posted above:

```python
#!/usr/local/opt/python/bin/python2.7

# -*- coding: utf-8 -*-
import re
import sys

from flake8.main.cli import main

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(main())
```

**Comment by kaste** [comment]
Hej, cool, and for the virtual environments. We have `.venv/bin/python` and `.venv/bin/flake8` at least. And `.venc/bin/flake8` is linked via shebang to the correct python.

**Comment by FichteFoll** [comment]
>How do you actually call pip for different installs? 

`pip2` or `pip3.6`.

```
/usr/bin Ξ diff pip3.6 pip3
2c2
< # EASY-INSTALL-ENTRY-SCRIPT: 'pip==9.0.1','console_scripts','pip3.6'
---
> # EASY-INSTALL-ENTRY-SCRIPT: 'pip==9.0.1','console_scripts','pip3'
11c11
<         load_entry_point('pip==9.0.1', 'console_scripts', 'pip3.6')()
---
>         load_entry_point('pip==9.0.1', 'console_scripts', 'pip3')()

/usr/bin ∃ diff pip pip3
2c2
< # EASY-INSTALL-ENTRY-SCRIPT: 'pip==9.0.1','console_scripts','pip'
---
> # EASY-INSTALL-ENTRY-SCRIPT: 'pip==9.0.1','console_scripts','pip3'
11c11
<         load_entry_point('pip==9.0.1', 'console_scripts', 'pip')()
---
>         load_entry_point('pip==9.0.1', 'console_scripts', 'pip3')()
```

>How do you call different flake8 or different pythons

`python2 -m flake8` and `python3.6 -m flake8`.

**Comment by deanishe** [comment]
> How do you actually call pip for different installs?

`/path/to/python -m pip ...`

**Comment by kaste** [comment]
Why don't you spawn prepared shells. I mean `python3.6 -m pytest` or even `/path/to/pythpn -m pytest`. Usually Windows guys are the old'schoolers here on the command line. (We made a setting `env` here in SublimeLinter btw to prepare an ENV.)

Very useful information. ❤️

**Comment by deanishe** [comment]
> Why don't you spawn prepared shells.

I don't know what that is. Could you expand?

**Comment by kaste** [comment]
Now, let's just try that.

Proposal:

- `executable` is a setting available to a linters. If set, it should point to e.g. a flake8 *binary*. We support some dynamism here via variables. E.g. `${folder}/.venv/bin/flake8` or `~/venvs/${project_name}/bin/flake8`

- `python` generally points to a python binary and will then execute e.g. `python -m flake8`. If set to a number, we will search the path for a binary called `python`, check its version and eventually take something or fail. If set to a string, we just take that value. 

Cons: If you call `nothere arg1 arg2` the OS will throw at us. If we call `python -m flake8` and flake8 is actually not installed, the call will succeed (and only python will throw at us).

**Comment by drcongo** [comment]
Just add something into the mix here, feel free to move / remove if it's too far removed from the OP. I'm trying to get the linter to use flake8 installed in a virtualenv inside a vagrant / virtual box VM. I'm also using Anaconda which allows me to point at a python executable inside the VM, so I hoped the same syntax would work for flake8 but it doesn't seem to. I'm running the pre-release versions of SL and SL-flake8, mostly just to try to get it not to report type hints as a syntax error. My .sublime-project looks like this...

```
{
    "python_interpreter": "vagrant://web:19360??network=private&address=10.0.0.2&interpreter=/vagrant/venv3/bin/python",
    "build_systems":
    [
        {
            "file_regex": "^[ ]*File \"(...*?)\", line ([0-9]*)",
            "name": "Anaconda Python Builder",
            "selector": "source.python",
            "shell_cmd": "\"python\" -u \"$file\""
        }
    ],
    "folders":
    [
        {
            "path": "."
        }
    ],
    "SublimeLinter":
    {
        "@python": 3,
        "python": 3,
        "linters":
        {
            "flake8":
            {
                "executable": "vagrant://web:19360??network=private&address=10.0.0.2&interpreter=/vagrant/venv3/bin/flake8",
            }
        }
    }
}
```

Debug output...
```
SublimeLinter: flake8: wanted python is 'None' 
SublimeLinter: flake8: trying to use globally installed flake8 
SublimeLinter: PATH:
    /usr/local/bin
    /usr/bin
    /bin
    /usr/sbin
    /sbin
    /usr/local/MacGPG2/bin 
SublimeLinter: flake8: task.py ['/usr/local/bin/flake8', '--format', 'default', '--max-complexity=10', '--max-line-length=100', '--ignore=E402', '-'] 
SublimeLinter: flake8: cwd: /Users/andy/src/projectname 
SublimeLinter: flake8 output:
    stdin:45:19: E999 SyntaxError: invalid syntax 
Package Control: Skipping automatic upgrade, last run at 2018-02-09 11:31:58, next run at 2018-02-09 12:31:58 or after
environment variables loaded using: /bin/zsh -l
```

**Comment by kaste** [comment]
PTAL at PR #973

**Comment by kaste** [comment]
@drcongo Probably something with your installation. It should at least log 'SublimeLinter: flake8: wanted executable is ...'

**Comment by drcongo** [comment]
@kaste Anything else I can log or paste here to help?

**Comment by kaste** [comment]
@drcongo Don't hijack this issue, open a new one, does it work if you set the global settings? Probably post full log.
