### ISSUE TITLE
SublimeLinter Package for xqlint

### ISSUE THREAD

**Issue by jmeischner** [SublimeLinter/SublimeLinter#962]
Dear All,

I created a sublimelinter-package for xqlint:
https://github.com/jmeischner/SublimeLinter-contrib-xqlint

I followed the instructions at [SublimeLinter](http://www.sublimelinter.com/en/latest/creating_a_linter.html) and ended up here, creating a ticket.

Thank You,
Jan

**Comment by braver** [comment]
You may want to update the README to match the new template: https://github.com/SublimeLinter/SublimeLinter-template/blob/master/README.md

I'll add your plugin to the repo shortly.

**Comment by braver** [comment]
Oh, also be sure to create a `1.0.0` release.

**Comment by jmeischner** [comment]
I created the tag now.

**Comment by braver** [comment]
Thanks! 

https://github.com/SublimeLinter/package_control_channel/commit/ee5e29ec29ea486da899c4eed5e8b5bbcabc7e80
