### ISSUE TITLE
Error in Panel syntax

### ISSUE THREAD

**Issue by ipkpjersi** [SublimeLinter/SublimeLinter#964]
Hello,

On the 4.0 beta there appears to be an error in the Panel syntax. When loading Sublime on either Windows 10 or Ubuntu 16.04, I am greeted with this error: 

![](https://i.imgur.com/mSe1Qtk.png)

**Comment by braver** [comment]
I don't get this unless I uninstall SL... did package control just update SublimeLinter when this happened?

**Comment by ipkpjersi** [comment]
SublimeLinter was updated I think like a week or two ago and then it just randomly started doing this out of nowhere, it was fine before. I was able to replicate this on Linux and on Windows. I could try uninstalling/deleting SublimeLinter but I want to keep my settings, I guess I could back it up first.

**Comment by braver** [comment]
If you uninstall a package ST doesn’t remove your settings, so that’s a safe thing to try.

**Comment by ipkpjersi** [comment]
Uninstalling seems to have fixed the issue so I will be closing this issue. I will re-open it if it occurs again.

**Comment by FichteFoll** [comment]
I created https://github.com/wbond/package_control/issues/1331 because I believe Package Control to be at fault here (or rather, to be in the position to prevent this), but am not entirely sure.

**Comment by drcongo** [comment]
I just hit this too, uninstalled SublimeLinter, reinstalled SublimeLinter and now I get no linting.

**Comment by drcongo** [comment]
A bit more info: I tried uninstalling and reinstalling SublimeLinter-flake8 too (also using the SL4 compatible pre-release), but got this message in the console:

```
reloading plugin SublimeLinter-flake8.linter
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 109, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "linter in /Users/andy/Dropbox/Libraries/Application Support/Sublime Text 3/Installed Packages/SublimeLinter-flake8.sublime-package", line 15, in <module>
ImportError: No module named 'SublimeLinter'
```

I had to uninstall both, restart Sublime Text and then re-install both.

**Comment by FichteFoll** [comment]
You probably had SublimeLinter disabled (for an unknown reason).
