### ISSUE TITLE
missing gutter icons

### ISSUE THREAD

**Issue by braver** [SublimeLinter/SublimeLinter#968]
Sometimes not all icons are rendered in the gutter, apparently primarily during editing. Discovered while testing #966, note the absent icon on line #599:

![](https://user-images.githubusercontent.com/2543659/35967767-29b66f84-0cc2-11e8-9ae1-175a4d6bfdd2.png)

**Comment by kaste** [comment]
How can I reproduce this?

**Comment by braver** [comment]
Ok, for example on line 198 in stylepy, put your cursor before `in` and insert a line break. For me, this results in a trailing whitespace warning inline, but no icon in the gutter. 

Now that I'm trying this though, I think this may be related to the way 3143 updates the gutter (which is super lazy). Recent ST builds were better (but buggy in other areas).

**Comment by kaste** [comment]
Hm, but you have two linters here running, both reporting the same error.

**Comment by braver** [comment]
Sure, I'm running ALL the linters. Going where no man has gone before.

**Comment by kaste** [comment]
If you set the priority of one of the linters up, say pydocstyle overrules flake8 always. Do you still see the error?

**Comment by braver** [comment]
I already have pycodestyle at prio 2.

**Comment by kaste** [comment]
Can't reproduce 

![image](https://user-images.githubusercontent.com/8558/36025544-ad26246e-0d93-11e8-858e-28db175dbe98.png)

**Comment by kaste** [comment]
Possible 'fix' in #971 if that's what your actual problem was.

**Comment by braver** [comment]
Could be, will go and test the new PR’s this afternoon (CET)

**Comment by kaste** [comment]
Already afternoon 🎉

**Comment by braver** [comment]
I can already smell the weekend man
