### ISSUE TITLE
New error panel does not show message

### ISSUE THREAD

**Issue by kaste** [SublimeLinter/SublimeLinter#972]
![image](https://user-images.githubusercontent.com/8558/36027966-9b2c0cd8-0d9d-11e8-8aa5-e3ddc74e5c11.png)

**Comment by braver** [comment]
Weird. What happens if you change `def plugin_loaded():` by adding 

```py
util.message('Hello\nblalblabal')
```

❓

**Comment by kaste** [comment]
Shows up as expected
