### ISSUE TITLE
[feature request] support for jinja and sql

### ISSUE THREAD

**Issue by emilielimaburke** [SublimeLinter/SublimeLinter#978]
Examples of where this is happening: 
* http://multithreaded.stitchfix.com/blog/2017/07/06/one-weird-trick/
* getdbt.com

**Comment by braver** [comment]
What does “support for jinja and sql” mean? There is an sqlint plugin...?

**Comment by emilielimaburke** [comment]
It is not uncommon for the two languages to be used at once more and more often.

**Comment by braver** [comment]
I don’t know what you want here. What doesn’t work for you right now?

**Comment by kaste** [comment]
This is not an 'issue' with SublimeLinter per se as we rely on third party linters. Actually you had to develop or find such a linter (a jinja or sql or both linter which works on the command line/terminal). Closing this, does not mean we will not respond if you have any further questions.
