### ISSUE TITLE
gutter icons don't always reflect priority

### ISSUE THREAD

**Issue by braver** [SublimeLinter/SublimeLinter#979]
The squiggly underline is orange (default for warning), in this case reflecting the flake8 warning. The gutter icon is purple, reflecting the pycodestyle error which has a lower priority.

<img width="482" alt="screen shot 2018-02-10 at 22 16 54" src="https://user-images.githubusercontent.com/2543659/36066768-27ffdbea-0eb0-11e8-9017-3ad20abd93df.png">

<img width="402" alt="screen shot 2018-02-10 at 22 20 46" src="https://user-images.githubusercontent.com/2543659/36066788-ab404ada-0eb0-11e8-80d0-cda0ab858a5a.png">

The linter problem was introduced by adding some newlines. I see the same colors, also after saving, restarting ST, etc.

Settings:

```json
// SublimeLinter Settings - User
{
    // "debug": true,
    "linters": {
        "pydocstyle": {
            // "disable": true,
            "styles": [
                {
                    "scope": "region.bluish",
                    "priority": 0,
                    "types": ["error", "warning"]
                }
            ]
        },
        "pycodestyle": {
            // "disable": true,
            "styles": [
                {
                    "scope": "region.purplish",
                    "priority": 0,
                    "types": ["error", "warning"]
                }
            ]
        }
    },
    "styles": [
        {
            "mark_style": "squiggly_underline",
            "priority": 1,
            "scope": "region.orangish",
            "icon": "dot",
            "types": [
                "warning"
            ]
        },
        {
            "mark_style": "squiggly_underline",
            "priority": 1,
            "scope": "region.redish",
            "icon": "dot",
            "types": [
                "error"
            ]
        }
    ]
}
```

**Comment by kaste** [comment]
Can't reproduce.

![image](https://user-images.githubusercontent.com/8558/36142206-ad33a028-10a7-11e8-8b56-13b423a91be1.png)


![image](https://user-images.githubusercontent.com/8558/36142271-d7474540-10a7-11e8-9f98-033e367e376e.png)

**Comment by kaste** [comment]
What I do get

![image](https://user-images.githubusercontent.com/8558/36142411-4f09f924-10a8-11e8-88dd-849e9066863e.png)

BUT

![image](https://user-images.githubusercontent.com/8558/36142466-7a7440f6-10a8-11e8-822c-5feaf5bd7369.png)

**Comment by braver** [comment]
🤔

**Comment by kaste** [comment]
Okay I know what's going on 

Say we have two errors, same priority, same position, different linters

```
[
  linterA,
  linterB
]
```

Now `linterA` updates. We get following `persist.errors`:

```
[
  linterB,
  linterA
]  
```

`highlights` picks `linterB`the first one as the winner, but only draws the *updates* from linterA, hence nothing.

Now `linterB` comes in:

```
[
  linterA,
  linterB
]
``` 
`highlights` picks `linterA` as the winner, but only draws `linterB`, again nothing.

So, we essentially need a stable sort and picking algorithm, when selecting the winner.

**Comment by kaste** [comment]
Current code is 

```
        winner = sorted(errors, key=lambda e: (-e['priority'], e['error_type']))[0]
```

We could either sort by linter name

```
        winner = sorted(errors, key=lambda e: (-e['priority'], e['error_type'], e['linter']))[0]
```

Or we just take the most recent update

```
        winner = sorted(reversed(errors), key=lambda e: (-e['priority'], e['error_type']))[0]
```

The latte, results in more redraws.

**Comment by kaste** [comment]
Sorting by name reduces flicker/redraws and is the winner here.
