### ISSUE TITLE
Disable for current file only

### ISSUE THREAD

**Issue by stdavis** [SublimeLinter/SublimeLinter#98]
I believe that this is the way that the only disable command worked. Seemed like it applied only to the current file. But now it disabled all linting globally.

Disabling for the current file only is super-useful for when you are opening up source code from external libraries that you are not concerned about linting.

**Comment by kaste** [comment]
This is simple. 

- Provide a toggle command in `sublime_linter.py` which basically set a setting on `view.settings()`. A typical name for that setting would be `SL.disabled`.

- Read and act upon that setting in `backend.py`. Somewhere around here:

https://github.com/SublimeLinter/SublimeLinter/blob/4ef4d62adc5d00ea59274e7bdd4bab828c97343c/lint/backend.py#L162-L176

**Comment by FichteFoll** [comment]
I suggest `sublime_linter.disabled`. It could be set as a project-specific setting (SL wouldn't know this) and being explicit about it is better.

**Comment by kaste** [comment]
view.settings() can be set via the project settings? And then all views in that project, or the same window, inherit these settings.

**Comment by braver** [comment]
IIRC view settings contains the aggregate of all settings that apply to a view, so project settings also affect view settings.

**Comment by kaste** [comment]
So I can set the font size per project, or what?

**Comment by braver** [comment]
Sure, you can even set font size, or color scheme, and you can even do that per syntax if you want.

**Comment by kaste** [comment]
That's completely insane.

But why does SublimeLinter has this strict notion of user settings vs project settings. It seems that users could set different styles or lint_mode per project.

**Comment by FichteFoll** [comment]
Because the user settings (read: global settings) are specified in a separate `SublimeLinter.sublime-settings` file and the merged settings are only sourced from `Preferences.sublime-settings` (and project settings, and syntax-specific settings and view-specific settings).

**Comment by kaste** [comment]
Hm, I mean 

https://github.com/SublimeLinter/SublimeLinter/blob/ed9cbd277d656260e5382e4ceabed71437bee237/lint/linter.py#L365-L375

Why do I call `window.project_data() or {}` and not `view.settings()`?

**Comment by FichteFoll** [comment]
Because the SL project settings use a different key next to `settings`. If we were  to just use `view.settings`, setting naming conflicts would be likely since we now share the same settings with the default preferences and any other plugin that opted to use them.

A possible solution would be to prefix every setting name in the resolved view settings with `sublime_linter.`.

**Comment by kaste** [comment]
Hey sorry, but what are the differences here

```
  	settings: {
		'SublimeLinter.disabled': true
	}
```

vs 

```
	settings: {
		SublimeLinter: {
			disabled: true
		}
	}
```

**Comment by FichteFoll** [comment]
Depending on where the `SublimeLinter` setting was specified, re-specifying it in e.g. the project settings would override the *entire* mapping.

**Comment by kaste** [comment]
It's key-map, not deep map 😄

**Comment by kaste** [comment]
Closing in favor of #1149

**Comment by kaste** [comment]
I would actually take a ugly key then, until we (in a next iteration) find a way to react on changes in the project file. (Basically a hacker can tweak even an ugly key, but know what to expect from doing that. E.g. restart.)
