### ISSUE TITLE
Status bar stopped showing errors per line

### ISSUE THREAD

**Issue by martinbohman** [SublimeLinter/SublimeLinter#986]
The status bar no longer shows errors per line. I have to move the cursor to a column that includes the error. What is the reasoning behind this change? Personally I find it much more convenient to only have to move the cursor to the line to get any error messages for that line.

The code in question is in `status_bar_view.py`, line 87 to 92 which takes only the errors under the cursor instead of the entire line:

```
def messages_under_cursor(errors, current_pos):
    line, col = current_pos
    return [
        error['msg'] for error in errors[line]
        if error["start"] <= col <= error["end"]
    ]
```

**Comment by braver** [comment]
Thanks for your question. I assume you’re using SublimeLinter 4.

- A lot of plugins fight for space on the status bar. Error messages usually take up a lot of space, basically claiming it all.
- There can be multiple problems on a line. You can’t tell from the status bar what is what. It also worsens the point above.
- There is now an output panel that shows all errors, and it always scrolls your cursor position into view. It also highlights the current line. This allows you to find out what’s wrong in great detail, and even navigate from one problem to another. 
- There are key bindings that allow you to jump to the exact position of the error nearest to your cursor. The message for that problem will then display in the status bar.
- There is now a tooltip if you hover over the gutter that displays all the errors for a given line in a very readable format.

**Comment by martinbohman** [comment]
Thanks for replying, I guess I can see how it makes sense. I will start working next/prev error keybinds more, and also check out the output panel and see if I find it useful for my workflow.

Also thanks for making a great plugin.
